<?php
$comune = [
    createComuna("Albac", [
        createLoc("Albac", "sat", createAdresaCompleta("sat Albac, comuna Albac, judetul ALBA, România")),
        createLoc("Bărăști", "sat", createAdresaCompleta("sat Bărăști, comuna Albac, judetul ALBA, România")),
        createLoc("Budăiești", "sat", createAdresaCompleta("sat Budăiești, comuna Albac, judetul ALBA, România")),
        createLoc("Cionești", "sat", createAdresaCompleta("sat Cionești, comuna Albac, judetul ALBA, România")),
        createLoc("Costești", "sat", createAdresaCompleta("sat Costești, comuna Albac, judetul ALBA, România")),
        createLoc("Dealu Lămășoi", "sat", createAdresaCompleta("sat Dealu Lămășoi, comuna Albac, judetul ALBA, România")),
        createLoc("Deve", "sat", createAdresaCompleta("sat Deve, comuna Albac, judetul ALBA, România")),
        createLoc("După Pleșe", "sat", createAdresaCompleta("sat După Pleșe, comuna Albac, judetul ALBA, România")),
        createLoc("Fața", "sat", createAdresaCompleta("sat Fața, comuna Albac, judetul ALBA, România")),
        createLoc("Pleșești", "sat", createAdresaCompleta("sat Pleșești, comuna Albac, judetul ALBA, România")),
        createLoc("Potionci", "sat", createAdresaCompleta("sat Potionci, comuna Albac, judetul ALBA, România")),
        createLoc("Rogoz", "sat", createAdresaCompleta("sat Rogoz, comuna Albac, judetul ALBA, România")),
        createLoc("Roșești", "sat", createAdresaCompleta("sat Roșești, comuna Albac, judetul ALBA, România")),
        createLoc("Rusești", "sat", createAdresaCompleta("sat Rusești, comuna Albac, judetul ALBA, România")),
        createLoc("Sohodol", "sat", createAdresaCompleta("sat Sohodol, comuna Albac, judetul ALBA, România")),
        createLoc("Tamborești", "sat", createAdresaCompleta("sat Tamborești, comuna Albac, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Albac, judetul ALBA, România")),
    createComuna("Almașu Mare", [
        createLoc("Almașu Mare", "sat", createAdresaCompleta("sat Almașu Mare, comuna Almașu Mare, judetul ALBA, România")),
        createLoc("Almașu de Mijloc", "sat", createAdresaCompleta("sat Almașu de Mijloc, comuna Almașu Mare, judetul ALBA, România")),
        createLoc("Brădet", "sat", createAdresaCompleta("sat Brădet, comuna Almașu Mare, judetul ALBA, România")),
        createLoc("Cheile Cibului", "sat", createAdresaCompleta("sat Cheile Cibului, comuna Almașu Mare, judetul ALBA, România")),
        createLoc("Cib", "sat", createAdresaCompleta("sat Cib, comuna Almașu Mare, judetul ALBA, România")),
        createLoc("Glod", "sat", createAdresaCompleta("sat Glod, comuna Almașu Mare, judetul ALBA, România")),
        createLoc("Nădăștia", "sat", createAdresaCompleta("sat Nădăștia, comuna Almașu Mare, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Almașu Mare, judetul ALBA, România")),
    createComuna("Arieșeni", [
        createLoc("Arieșeni", "sat", createAdresaCompleta("sat Arieșeni, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Avrămești", "sat", createAdresaCompleta("sat Avrămești, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Bubești", "sat", createAdresaCompleta("sat Bubești, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Casa de Piatră", "sat", createAdresaCompleta("sat Casa de Piatră, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Cobleș", "sat", createAdresaCompleta("sat Cobleș, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Dealu Bajului", "sat", createAdresaCompleta("sat Dealu Bajului, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Fața Cristesei", "sat", createAdresaCompleta("sat Fața Cristesei, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Fața Lăpușului", "sat", createAdresaCompleta("sat Fața Lăpușului, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Galbena", "sat", createAdresaCompleta("sat Galbena, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Hodobana", "sat", createAdresaCompleta("sat Hodobana, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Izlaz", "sat", createAdresaCompleta("sat Izlaz, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Păntești", "sat", createAdresaCompleta("sat Păntești, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Pătrăhăițești", "sat", createAdresaCompleta("sat Pătrăhăițești, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Poienița", "sat", createAdresaCompleta("sat Poienița, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Ravicești", "sat", createAdresaCompleta("sat Ravicești, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Sturu", "sat", createAdresaCompleta("sat Sturu, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Ștei-Arieșeni", "sat", createAdresaCompleta("sat Ștei-Arieșeni, comuna Arieșeni, judetul ALBA, România")),
        createLoc("Vanvucești", "sat", createAdresaCompleta("sat Vanvucești, comuna Arieșeni, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Arieșeni, judetul ALBA, România")),
    createComuna("Avram Iancu", [
        createLoc("Avram Iancu", "sat", createAdresaCompleta("sat Avram Iancu, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Achimețești", "sat", createAdresaCompleta("sat Achimețești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Avrămești", "sat", createAdresaCompleta("sat Avrămești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Bădăi", "sat", createAdresaCompleta("sat Bădăi, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Boldești", "sat", createAdresaCompleta("sat Boldești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Călugărești", "sat", createAdresaCompleta("sat Călugărești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Căsoaia", "sat", createAdresaCompleta("sat Căsoaia, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Cândești", "sat", createAdresaCompleta("sat Cândești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Cârăști", "sat", createAdresaCompleta("sat Cârăști, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Cârțulești", "sat", createAdresaCompleta("sat Cârțulești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Cocești", "sat", createAdresaCompleta("sat Cocești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Cocoșești", "sat", createAdresaCompleta("sat Cocoșești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Coroiești", "sat", createAdresaCompleta("sat Coroiești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Dealu Crișului", "sat", createAdresaCompleta("sat Dealu Crișului, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Dolești", "sat", createAdresaCompleta("sat Dolești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Dumăcești", "sat", createAdresaCompleta("sat Dumăcești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Gojeiești", "sat", createAdresaCompleta("sat Gojeiești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Helerești", "sat", createAdresaCompleta("sat Helerești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Incești", "sat", createAdresaCompleta("sat Incești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Jojei", "sat", createAdresaCompleta("sat Jojei, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Mărtești", "sat", createAdresaCompleta("sat Mărtești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Orgești", "sat", createAdresaCompleta("sat Orgești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Pătruțești", "sat", createAdresaCompleta("sat Pătruțești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Plai", "sat", createAdresaCompleta("sat Plai, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Pușelești", "sat", createAdresaCompleta("sat Pușelești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Șoicești", "sat", createAdresaCompleta("sat Șoicești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Ștertești", "sat", createAdresaCompleta("sat Ștertești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Târsa", "sat", createAdresaCompleta("sat Târsa, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Târsa-Plai", "sat", createAdresaCompleta("sat Târsa-Plai, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Valea Maciului", "sat", createAdresaCompleta("sat Valea Maciului, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Valea Uțului", "sat", createAdresaCompleta("sat Valea Uțului, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Verdești", "sat", createAdresaCompleta("sat Verdești, comuna Avram Iancu, judetul ALBA, România")),
        createLoc("Vidrișoara", "sat", createAdresaCompleta("sat Vidrișoara, comuna Avram Iancu, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Avram Iancu, judetul ALBA, România")),
    createComuna("Berghin", [
        createLoc("Berghin", "sat", createAdresaCompleta("sat Berghin, comuna Berghin, judetul ALBA, România")),
        createLoc("Ghirbom", "sat", createAdresaCompleta("sat Ghirbom, comuna Berghin, judetul ALBA, România")),
        createLoc("Henig", "sat", createAdresaCompleta("sat Henig, comuna Berghin, judetul ALBA, România")),
        createLoc("Straja", "sat", createAdresaCompleta("sat Straja, comuna Berghin, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Berghin, judetul ALBA, România")),
    createComuna("Bistra", [
        createLoc("Bistra", "sat", createAdresaCompleta("sat Bistra, comuna Bistra, judetul ALBA, România")),
        createLoc("Aronești", "sat", createAdresaCompleta("sat Aronești, comuna Bistra, judetul ALBA, România")),
        createLoc("Bălești", "sat", createAdresaCompleta("sat Bălești, comuna Bistra, judetul ALBA, România")),
        createLoc("Bălești-Cătun", "sat", createAdresaCompleta("sat Bălești-Cătun, comuna Bistra, judetul ALBA, România")),
        createLoc("Bârlești", "sat", createAdresaCompleta("sat Bârlești, comuna Bistra, judetul ALBA, România")),
        createLoc("Cheleteni", "sat", createAdresaCompleta("sat Cheleteni, comuna Bistra, judetul ALBA, România")),
        createLoc("Ciuldești", "sat", createAdresaCompleta("sat Ciuldești, comuna Bistra, judetul ALBA, România")),
        createLoc("Crețești", "sat", createAdresaCompleta("sat Crețești, comuna Bistra, judetul ALBA, România")),
        createLoc("Dealu Muntelui", "sat", createAdresaCompleta("sat Dealu Muntelui, comuna Bistra, judetul ALBA, România")),
        createLoc("Dâmbureni", "sat", createAdresaCompleta("sat Dâmbureni, comuna Bistra, judetul ALBA, România")),
        createLoc("Durăști", "sat", createAdresaCompleta("sat Durăști, comuna Bistra, judetul ALBA, România")),
        createLoc("Gănești", "sat", createAdresaCompleta("sat Gănești, comuna Bistra, judetul ALBA, România")),
        createLoc("Gârde", "sat", createAdresaCompleta("sat Gârde, comuna Bistra, judetul ALBA, România")),
        createLoc("Hodișești", "sat", createAdresaCompleta("sat Hodișești, comuna Bistra, judetul ALBA, România")),
        createLoc("Hudricești", "sat", createAdresaCompleta("sat Hudricești, comuna Bistra, judetul ALBA, România")),
        createLoc("Lipaia", "sat", createAdresaCompleta("sat Lipaia, comuna Bistra, judetul ALBA, România")),
        createLoc("Lunca Largă", "sat", createAdresaCompleta("sat Lunca Largă, comuna Bistra, judetul ALBA, România")),
        createLoc("Lunca Merilor", "sat", createAdresaCompleta("sat Lunca Merilor, comuna Bistra, judetul ALBA, România")),
        createLoc("Mihăiești", "sat", createAdresaCompleta("sat Mihăiești, comuna Bistra, judetul ALBA, România")),
        createLoc("Nămaș", "sat", createAdresaCompleta("sat Nămaș, comuna Bistra, judetul ALBA, România")),
        createLoc("Novăcești", "sat", createAdresaCompleta("sat Novăcești, comuna Bistra, judetul ALBA, România")),
        createLoc("Perjești", "sat", createAdresaCompleta("sat Perjești, comuna Bistra, judetul ALBA, România")),
        createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Bistra, judetul ALBA, România")),
        createLoc("Poiu", "sat", createAdresaCompleta("sat Poiu, comuna Bistra, judetul ALBA, România")),
        createLoc("Rătitiș", "sat", createAdresaCompleta("sat Rătitiș, comuna Bistra, judetul ALBA, România")),
        createLoc("Runcuri", "sat", createAdresaCompleta("sat Runcuri, comuna Bistra, judetul ALBA, România")),
        createLoc("Sălăgești", "sat", createAdresaCompleta("sat Sălăgești, comuna Bistra, judetul ALBA, România")),
        createLoc("Ștefanca", "sat", createAdresaCompleta("sat Ștefanca, comuna Bistra, judetul ALBA, România")),
        createLoc("Tolăcești", "sat", createAdresaCompleta("sat Tolăcești, comuna Bistra, judetul ALBA, România")),
        createLoc("Tomnatec", "sat", createAdresaCompleta("sat Tomnatec, comuna Bistra, judetul ALBA, România")),
        createLoc("Trișorești", "sat", createAdresaCompleta("sat Trișorești, comuna Bistra, judetul ALBA, România")),
        createLoc("Țărănești", "sat", createAdresaCompleta("sat Țărănești, comuna Bistra, judetul ALBA, România")),
        createLoc("Vârși-Rontu", "sat", createAdresaCompleta("sat Vârși-Rontu, comuna Bistra, judetul ALBA, România")),
        createLoc("Vârșii Mari", "sat", createAdresaCompleta("sat Vârșii Mari, comuna Bistra, judetul ALBA, România")),
        createLoc("Vârșii Mici", "sat", createAdresaCompleta("sat Vârșii Mici, comuna Bistra, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Bistra, judetul ALBA, România")),
    createComuna("Blandiana", [
        createLoc("Blandiana", "sat", createAdresaCompleta("sat Blandiana, comuna Blandiana, judetul ALBA, România")),
        createLoc("Acmariu", "sat", createAdresaCompleta("sat Acmariu, comuna Blandiana, judetul ALBA, România")),
        createLoc("Ibru", "sat", createAdresaCompleta("sat Ibru, comuna Blandiana, judetul ALBA, România")),
        createLoc("Poieni", "sat", createAdresaCompleta("sat Poieni, comuna Blandiana, judetul ALBA, România")),
        createLoc("Răcătău", "sat", createAdresaCompleta("sat Răcătău, comuna Blandiana, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Blandiana, judetul ALBA, România")),
    createComuna("Bucerdea Grânoasă", [
        createLoc("Bucerdea Grânoasă", "sat", createAdresaCompleta("sat Bucerdea Grânoasă, comuna Bucerdea Grânoasă, judetul ALBA, România")),
        createLoc("Cornu", "sat", createAdresaCompleta("sat Cornu, comuna Bucerdea Grânoasă, judetul ALBA, România")),
        createLoc("Pădure", "sat", createAdresaCompleta("sat Pădure, comuna Bucerdea Grânoasă, judetul ALBA, România")),
        createLoc("Pânca", "sat", createAdresaCompleta("sat Pânca, comuna Bucerdea Grânoasă, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Bucerdea Grânoasă, judetul ALBA, România")),
    createComuna("Bucium", [
        createLoc("Bucium", "sat", createAdresaCompleta("sat Bucium, comuna Bucium, judetul ALBA, România")),
        createLoc("Anghelești", "sat", createAdresaCompleta("sat Anghelești, comuna Bucium, judetul ALBA, România")),
        createLoc("Bisericani", "sat", createAdresaCompleta("sat Bisericani, comuna Bucium, judetul ALBA, România")),
        createLoc("Bucium-Sat", "sat", createAdresaCompleta("sat Bucium-Sat, comuna Bucium, judetul ALBA, România")),
        createLoc("Cerbu", "sat", createAdresaCompleta("sat Cerbu, comuna Bucium, judetul ALBA, România")),
        createLoc("Ciuculești", "sat", createAdresaCompleta("sat Ciuculești, comuna Bucium, judetul ALBA, România")),
        createLoc("Coleșeni", "sat", createAdresaCompleta("sat Coleșeni, comuna Bucium, judetul ALBA, România")),
        createLoc("Dogărești", "sat", createAdresaCompleta("sat Dogărești, comuna Bucium, judetul ALBA, România")),
        createLoc("Ferești", "sat", createAdresaCompleta("sat Ferești, comuna Bucium, judetul ALBA, România")),
        createLoc("Florești", "sat", createAdresaCompleta("sat Florești, comuna Bucium, judetul ALBA, România")),
        createLoc("Gura Izbitei", "sat", createAdresaCompleta("sat Gura Izbitei, comuna Bucium, judetul ALBA, România")),
        createLoc("Helești", "sat", createAdresaCompleta("sat Helești, comuna Bucium, judetul ALBA, România")),
        createLoc("Izbicioara", "sat", createAdresaCompleta("sat Izbicioara, comuna Bucium, judetul ALBA, România")),
        createLoc("Izbita", "sat", createAdresaCompleta("sat Izbita, comuna Bucium, judetul ALBA, România")),
        createLoc("Jurcuiești", "sat", createAdresaCompleta("sat Jurcuiești, comuna Bucium, judetul ALBA, România")),
        createLoc("Lupulești", "sat", createAdresaCompleta("sat Lupulești, comuna Bucium, judetul ALBA, România")),
        createLoc("Măgura", "sat", createAdresaCompleta("sat Măgura, comuna Bucium, judetul ALBA, România")),
        createLoc("Muntari", "sat", createAdresaCompleta("sat Muntari, comuna Bucium, judetul ALBA, România")),
        createLoc("Petreni", "sat", createAdresaCompleta("sat Petreni, comuna Bucium, judetul ALBA, România")),
        createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Bucium, judetul ALBA, România")),
        createLoc("Poieni", "sat", createAdresaCompleta("sat Poieni, comuna Bucium, judetul ALBA, România")),
        createLoc("Stâlnișoara", "sat", createAdresaCompleta("sat Stâlnișoara, comuna Bucium, judetul ALBA, România")),
        createLoc("Valea Abruzel", "sat", createAdresaCompleta("sat Valea Abruzel, comuna Bucium, judetul ALBA, România")),
        createLoc("Valea Albă", "sat", createAdresaCompleta("sat Valea Albă, comuna Bucium, judetul ALBA, România")),
        createLoc("Valea Cerbului", "sat", createAdresaCompleta("sat Valea Cerbului, comuna Bucium, judetul ALBA, România")),
        createLoc("Valea Negrilesii", "sat", createAdresaCompleta("sat Valea Negrilesii, comuna Bucium, judetul ALBA, România")),
        createLoc("Valea Poienii", "sat", createAdresaCompleta("sat Valea Poienii, comuna Bucium, judetul ALBA, România")),
        createLoc("Valea Șesii", "sat", createAdresaCompleta("sat Valea Șesii, comuna Bucium, judetul ALBA, România")),
        createLoc("Văleni", "sat", createAdresaCompleta("sat Văleni, comuna Bucium, judetul ALBA, România")),
        createLoc("Vâlcea", "sat", createAdresaCompleta("sat Vâlcea, comuna Bucium, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Bucium, judetul ALBA, România")),
    createComuna("Câlnic", [
        createLoc("Câlnic", "sat", createAdresaCompleta("sat Câlnic, comuna Câlnic, judetul ALBA, România")),
        createLoc("Deal", "sat", createAdresaCompleta("sat Deal, comuna Câlnic, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Câlnic, judetul ALBA, România")),
    createComuna("Cenade", [
        createLoc("Cenade", "sat", createAdresaCompleta("sat Cenade, comuna Cenade, judetul ALBA, România")),
        createLoc("Capu Dealului", "sat", createAdresaCompleta("sat Capu Dealului, comuna Cenade, judetul ALBA, România")),
        createLoc("Gorgan", "sat", createAdresaCompleta("sat Gorgan, comuna Cenade, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Cenade, judetul ALBA, România")),
    createComuna("Cergău", [
        createLoc("Cergău Mare", "sat", createAdresaCompleta("sat Cergău Mare, comuna Cergău, judetul ALBA, România")),
        createLoc("Cergău Mic", "sat", createAdresaCompleta("sat Cergău Mic, comuna Cergău, judetul ALBA, România")),
        createLoc("Lupu", "sat", createAdresaCompleta("sat Lupu, comuna Cergău, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Cergău, judetul ALBA, România")),
    createComuna("Ceru-Băcăinți", [
        createLoc("Ceru-Băcăinți", "sat", createAdresaCompleta("sat Ceru-Băcăinți, comuna Ceru-Băcăinți, judetul ALBA, România")),
        createLoc("Bolovănești", "sat", createAdresaCompleta("sat Bolovănești, comuna Ceru-Băcăinți, judetul ALBA, România")),
        createLoc("Bulbuc", "sat", createAdresaCompleta("sat Bulbuc, comuna Ceru-Băcăinți, judetul ALBA, România")),
        createLoc("Cucuta", "sat", createAdresaCompleta("sat Cucuta, comuna Ceru-Băcăinți, judetul ALBA, România")),
        createLoc("Curpeni", "sat", createAdresaCompleta("sat Curpeni, comuna Ceru-Băcăinți, judetul ALBA, România")),
        createLoc("Dumbrăvița", "sat", createAdresaCompleta("sat Dumbrăvița, comuna Ceru-Băcăinți, judetul ALBA, România")),
        createLoc("Fântânele", "sat", createAdresaCompleta("sat Fântânele, comuna Ceru-Băcăinți, judetul ALBA, România")),
        createLoc("Groși", "sat", createAdresaCompleta("sat Groși, comuna Ceru-Băcăinți, judetul ALBA, România")),
        createLoc("Valea Mare", "sat", createAdresaCompleta("sat Valea Mare, comuna Ceru-Băcăinți, judetul ALBA, România")),
        createLoc("Viezuri", "sat", createAdresaCompleta("sat Viezuri, comuna Ceru-Băcăinți, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Ceru-Băcăinți, judetul ALBA, România")),
    createComuna("Cetatea de Baltă", [
        createLoc("Cetatea de Baltă", "sat", createAdresaCompleta("sat Cetatea de Baltă, comuna Cetatea de Baltă, judetul ALBA, România")),
        createLoc("Crăciunelu de Sus", "sat", createAdresaCompleta("sat Crăciunelu de Sus, comuna Cetatea de Baltă, judetul ALBA, România")),
        createLoc("Sântămărie", "sat", createAdresaCompleta("sat Sântămărie, comuna Cetatea de Baltă, judetul ALBA, România")),
        createLoc("Tătârlaua", "sat", createAdresaCompleta("sat Tătârlaua, comuna Cetatea de Baltă, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Cetatea de Baltă, judetul ALBA, România")),
    createComuna("Ciugud", [
        createLoc("Ciugud", "sat", createAdresaCompleta("sat Ciugud, comuna Ciugud, judetul ALBA, România")),
        createLoc("Drâmbar", "sat", createAdresaCompleta("sat Drâmbar, comuna Ciugud, judetul ALBA, România")),
        createLoc("Hăpria", "sat", createAdresaCompleta("sat Hăpria, comuna Ciugud, judetul ALBA, România")),
        createLoc("Limba", "sat", createAdresaCompleta("sat Limba, comuna Ciugud, judetul ALBA, România")),
        createLoc("Șeușa", "sat", createAdresaCompleta("sat Șeușa, comuna Ciugud, judetul ALBA, România")),
        createLoc("Teleac", "sat", createAdresaCompleta("sat Teleac, comuna Ciugud, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Ciugud, judetul ALBA, România")),
    createComuna("Ciuruleasa", [
        createLoc("Ciuruleasa", "sat", createAdresaCompleta("sat Ciuruleasa, comuna Ciuruleasa, judetul ALBA, România")),
        createLoc("Bidigești", "sat", createAdresaCompleta("sat Bidigești, comuna Ciuruleasa, judetul ALBA, România")),
        createLoc("Bodrești", "sat", createAdresaCompleta("sat Bodrești, comuna Ciuruleasa, judetul ALBA, România")),
        createLoc("Boglești", "sat", createAdresaCompleta("sat Boglești, comuna Ciuruleasa, judetul ALBA, România")),
        createLoc("Buninginea", "sat", createAdresaCompleta("sat Buninginea, comuna Ciuruleasa, judetul ALBA, România")),
        createLoc("Ghedulești", "sat", createAdresaCompleta("sat Ghedulești, comuna Ciuruleasa, judetul ALBA, România")),
        createLoc("Mătișești", "sat", createAdresaCompleta("sat Mătișești, comuna Ciuruleasa, judetul ALBA, România")),
        createLoc("Morărești", "sat", createAdresaCompleta("sat Morărești, comuna Ciuruleasa, judetul ALBA, România")),
        createLoc("Vulcan", "sat", createAdresaCompleta("sat Vulcan, comuna Ciuruleasa, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Ciuruleasa, judetul ALBA, România")),
    createComuna("Crăciunelu de Jos", [
        createLoc("Crăciunelu de Jos", "sat", createAdresaCompleta("sat Crăciunelu de Jos, comuna Crăciunelu de Jos, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Crăciunelu de Jos, judetul ALBA, România")),
    createComuna("Cricău", [
        createLoc("Cricău", "sat", createAdresaCompleta("sat Cricău, comuna Cricău, judetul ALBA, România")),
        createLoc("Craiva", "sat", createAdresaCompleta("sat Craiva, comuna Cricău, judetul ALBA, România")),
        createLoc("Tibru", "sat", createAdresaCompleta("sat Tibru, comuna Cricău, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Cricău, judetul ALBA, România")),
    createComuna("Cut", [
        createLoc("Cut", "sat", createAdresaCompleta("sat Cut, comuna Cut, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Cut, judetul ALBA, România")),
    createComuna("Daia Română", [
        createLoc("Daia Română", "sat", createAdresaCompleta("sat Daia Română, comuna Daia Română, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Daia Română, judetul ALBA, România")),
    createComuna("Doștat", [
        createLoc("Doștat", "sat", createAdresaCompleta("sat Doștat, comuna Doștat, judetul ALBA, România")),
        createLoc("Boz", "sat", createAdresaCompleta("sat Boz, comuna Doștat, judetul ALBA, România")),
        createLoc("Dealu Doștatului", "sat", createAdresaCompleta("sat Dealu Doștatului, comuna Doștat, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Doștat, judetul ALBA, România")),
    createComuna("Fărău", [
        createLoc("Fărău", "sat", createAdresaCompleta("sat Fărău, comuna Fărău, judetul ALBA, România")),
        createLoc("Heria", "sat", createAdresaCompleta("sat Heria, comuna Fărău, judetul ALBA, România")),
        createLoc("Medveș", "sat", createAdresaCompleta("sat Medveș, comuna Fărău, judetul ALBA, România")),
        createLoc("Sânbenedic", "sat", createAdresaCompleta("sat Sânbenedic, comuna Fărău, judetul ALBA, România")),
        createLoc("Șilea", "sat", createAdresaCompleta("sat Șilea, comuna Fărău, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Fărău, judetul ALBA, România")),
    createComuna("Galda de Jos", [
        createLoc("Galda de Jos", "sat", createAdresaCompleta("sat Galda de Jos, comuna Galda de Jos, judetul ALBA, România")),
        createLoc("Benic", "sat", createAdresaCompleta("sat Benic, comuna Galda de Jos, judetul ALBA, România")),
        createLoc("Cetea", "sat", createAdresaCompleta("sat Cetea, comuna Galda de Jos, judetul ALBA, România")),
        createLoc("Galda de Sus", "sat", createAdresaCompleta("sat Galda de Sus, comuna Galda de Jos, judetul ALBA, România")),
        createLoc("Lupșeni", "sat", createAdresaCompleta("sat Lupșeni, comuna Galda de Jos, judetul ALBA, România")),
        createLoc("Măgura", "sat", createAdresaCompleta("sat Măgura, comuna Galda de Jos, judetul ALBA, România")),
        createLoc("Mesentea", "sat", createAdresaCompleta("sat Mesentea, comuna Galda de Jos, judetul ALBA, România")),
        createLoc("Oiejdea", "sat", createAdresaCompleta("sat Oiejdea, comuna Galda de Jos, judetul ALBA, România")),
        createLoc("Poaiana Galdei", "sat", createAdresaCompleta("sat Poaiana Galdei, comuna Galda de Jos, judetul ALBA, România")),
        createLoc("Răicani", "sat", createAdresaCompleta("sat Răicani, comuna Galda de Jos, judetul ALBA, România")),
        createLoc("Zăgriș", "sat", createAdresaCompleta("sat Zăgriș, comuna Galda de Jos, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Galda de Jos, judetul ALBA, România")),
    createComuna("Gârbova", [
        createLoc("Gârbova", "sat", createAdresaCompleta("sat Gârbova, comuna Gârbova, judetul ALBA, România")),
        createLoc("Cărpiniș", "sat", createAdresaCompleta("sat Cărpiniș, comuna Gârbova, judetul ALBA, România")),
        createLoc("Reciu", "sat", createAdresaCompleta("sat Reciu, comuna Gârbova, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Gârbova, judetul ALBA, România")),
    createComuna("Gârda de Sus", [
        createLoc("Gârda de Sus", "sat", createAdresaCompleta("sat Gârda de Sus, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Biharia", "sat", createAdresaCompleta("sat Biharia, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Dealu Frumos", "sat", createAdresaCompleta("sat Dealu Frumos, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Dealu Ordâncușii", "sat", createAdresaCompleta("sat Dealu Ordâncușii, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Dobrești", "sat", createAdresaCompleta("sat Dobrești, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Ghețari", "sat", createAdresaCompleta("sat Ghețari, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Gârda Seacă", "sat", createAdresaCompleta("sat Gârda Seacă, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Hanășești", "sat", createAdresaCompleta("sat Hanășești, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Huzărești", "sat", createAdresaCompleta("sat Huzărești, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Izvoarele", "sat", createAdresaCompleta("sat Izvoarele, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Munună", "sat", createAdresaCompleta("sat Munună, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Ocoale", "sat", createAdresaCompleta("sat Ocoale, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Plai", "sat", createAdresaCompleta("sat Plai, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Pliști", "sat", createAdresaCompleta("sat Pliști, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Scoarța", "sat", createAdresaCompleta("sat Scoarța, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Snide", "sat", createAdresaCompleta("sat Snide, comuna Gârda de Sus, judetul ALBA, România")),
        createLoc("Sucești", "sat", createAdresaCompleta("sat Sucești, comuna Gârda de Sus, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Gârda de Sus, judetul ALBA, România")),
    createComuna("Hopârta", [
        createLoc("Hopârta", "sat", createAdresaCompleta("sat Hopârta, comuna Hopârta, judetul ALBA, România")),
        createLoc("Silivaș", "sat", createAdresaCompleta("sat Silivaș, comuna Hopârta, judetul ALBA, România")),
        createLoc("Șpălnaca", "sat", createAdresaCompleta("sat Șpălnaca, comuna Hopârta, judetul ALBA, România")),
        createLoc("Turdaș", "sat", createAdresaCompleta("sat Turdaș, comuna Hopârta, judetul ALBA, România")),
        createLoc("Vama Seacă", "sat", createAdresaCompleta("sat Vama Seacă, comuna Hopârta, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Hopârta, judetul ALBA, România")),
    createComuna("Horea", [
        createLoc("Horea", "sat", createAdresaCompleta("sat Horea, comuna Horea, judetul ALBA, România")),
        createLoc("Baba", "sat", createAdresaCompleta("sat Baba, comuna Horea, judetul ALBA, România")),
        createLoc("Butești", "sat", createAdresaCompleta("sat Butești, comuna Horea, judetul ALBA, România")),
        createLoc("Dârlești", "sat", createAdresaCompleta("sat Dârlești, comuna Horea, judetul ALBA, România")),
        createLoc("Fericet", "sat", createAdresaCompleta("sat Fericet, comuna Horea, judetul ALBA, România")),
        createLoc("Giurgiuț", "sat", createAdresaCompleta("sat Giurgiuț, comuna Horea, judetul ALBA, România")),
        createLoc("Măncești", "sat", createAdresaCompleta("sat Măncești, comuna Horea, judetul ALBA, România")),
        createLoc("Mătișești", "sat", createAdresaCompleta("sat Mătișești, comuna Horea, judetul ALBA, România")),
        createLoc("Niculești", "sat", createAdresaCompleta("sat Niculești, comuna Horea, judetul ALBA, România")),
        createLoc("Pătrușești", "sat", createAdresaCompleta("sat Pătrușești, comuna Horea, judetul ALBA, România")),
        createLoc("Petreasa", "sat", createAdresaCompleta("sat Petreasa, comuna Horea, judetul ALBA, România")),
        createLoc("Preluca", "sat", createAdresaCompleta("sat Preluca, comuna Horea, judetul ALBA, România")),
        createLoc("Teiu", "sat", createAdresaCompleta("sat Teiu, comuna Horea, judetul ALBA, România")),
        createLoc("Trifești", "sat", createAdresaCompleta("sat Trifești, comuna Horea, judetul ALBA, România")),
        createLoc("Zânzești", "sat", createAdresaCompleta("sat Zânzești, comuna Horea, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Horea, judetul ALBA, România")),
    createComuna("Ighiu", [
        createLoc("Ighiu", "sat", createAdresaCompleta("sat Ighiu, comuna Ighiu, judetul ALBA, România")),
        createLoc("Bucerdea Vinoasă", "sat", createAdresaCompleta("sat Bucerdea Vinoasă, comuna Ighiu, judetul ALBA, România")),
        createLoc("Ighiel", "sat", createAdresaCompleta("sat Ighiel, comuna Ighiu, judetul ALBA, România")),
        createLoc("Șard", "sat", createAdresaCompleta("sat Șard, comuna Ighiu, judetul ALBA, România")),
        createLoc("Țelna", "sat", createAdresaCompleta("sat Țelna, comuna Ighiu, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Ighiu, judetul ALBA, România")),
    createComuna("Întregalde", [
        createLoc("Întregalde", "sat", createAdresaCompleta("sat Întregalde, comuna Întregalde, judetul ALBA, România")),
        createLoc("Dealu Geoagiului", "sat", createAdresaCompleta("sat Dealu Geoagiului, comuna Întregalde, judetul ALBA, România")),
        createLoc("Ghioncani", "sat", createAdresaCompleta("sat Ghioncani, comuna Întregalde, judetul ALBA, România")),
        createLoc("Iliești", "sat", createAdresaCompleta("sat Iliești, comuna Întregalde, judetul ALBA, România")),
        createLoc("Ivăniș", "sat", createAdresaCompleta("sat Ivăniș, comuna Întregalde, judetul ALBA, România")),
        createLoc("Mărinești", "sat", createAdresaCompleta("sat Mărinești, comuna Întregalde, judetul ALBA, România")),
        createLoc("Modolești", "sat", createAdresaCompleta("sat Modolești, comuna Întregalde, judetul ALBA, România")),
        createLoc("Necrilești", "sat", createAdresaCompleta("sat Necrilești, comuna Întregalde, judetul ALBA, România")),
        createLoc("Popești", "sat", createAdresaCompleta("sat Popești, comuna Întregalde, judetul ALBA, România")),
        createLoc("Sfârcea", "sat", createAdresaCompleta("sat Sfârcea, comuna Întregalde, judetul ALBA, România")),
        createLoc("Tecșești", "sat", createAdresaCompleta("sat Tecșești, comuna Întregalde, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Întregalde, judetul ALBA, România")),
    createComuna("Jidvei", [
        createLoc("Jidvei", "sat", createAdresaCompleta("sat Jidvei, comuna Jidvei, judetul ALBA, România")),
        createLoc("Bălcaciu", "sat", createAdresaCompleta("sat Bălcaciu, comuna Jidvei, judetul ALBA, România")),
        createLoc("Căpâlna de Jos", "sat", createAdresaCompleta("sat Căpâlna de Jos, comuna Jidvei, judetul ALBA, România")),
        createLoc("Feisa", "sat", createAdresaCompleta("sat Feisa, comuna Jidvei, judetul ALBA, România")),
        createLoc("Veseuș", "sat", createAdresaCompleta("sat Veseuș, comuna Jidvei, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Jidvei, judetul ALBA, România")),
    createComuna("Livezile", [
        createLoc("Livezile", "sat", createAdresaCompleta("sat Livezile, comuna Livezile, judetul ALBA, România")),
        createLoc("Izvoarele", "sat", createAdresaCompleta("sat Izvoarele, comuna Livezile, judetul ALBA, România")),
        createLoc("Poiana Aiudului", "sat", createAdresaCompleta("sat Poiana Aiudului, comuna Livezile, judetul ALBA, România")),
        createLoc("Vălișoara", "sat", createAdresaCompleta("sat Vălișoara, comuna Livezile, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Livezile, judetul ALBA, România")),
    createComuna("Lopadea Nouă", [
        createLoc("Lopadea Nouă", "sat", createAdresaCompleta("sat Lopadea Nouă, comuna Lopadea Nouă, judetul ALBA, România")),
        createLoc("Asinip", "sat", createAdresaCompleta("sat Asinip, comuna Lopadea Nouă, judetul ALBA, România")),
        createLoc("Beța", "sat", createAdresaCompleta("sat Beța, comuna Lopadea Nouă, judetul ALBA, România")),
        createLoc("Băgău", "sat", createAdresaCompleta("sat Băgău, comuna Lopadea Nouă, judetul ALBA, România")),
        createLoc("Cicârd", "sat", createAdresaCompleta("sat Cicârd, comuna Lopadea Nouă, judetul ALBA, România")),
        createLoc("Ciuguzel", "sat", createAdresaCompleta("sat Ciuguzel, comuna Lopadea Nouă, judetul ALBA, România")),
        createLoc("Ocnișoara", "sat", createAdresaCompleta("sat Ocnișoara, comuna Lopadea Nouă, judetul ALBA, România")),
        createLoc("Odverem", "sat", createAdresaCompleta("sat Odverem, comuna Lopadea Nouă, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Lopadea Nouă, judetul ALBA, România")),
    createComuna("Lunca Mureșului", [
        createLoc("Lunca Mureșului", "sat", createAdresaCompleta("sat Lunca Mureșului, comuna Lunca Mureșului, judetul ALBA, România")),
        createLoc("Gura Arieșului", "sat", createAdresaCompleta("sat Gura Arieșului, comuna Lunca Mureșului, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Lunca Mureșului, judetul ALBA, România")),
    createComuna("Lupșa", [
        createLoc("Lupșa", "sat", createAdresaCompleta("sat Lupșa, comuna Lupșa, judetul ALBA, România")),
        createLoc("Bârdești", "sat", createAdresaCompleta("sat Bârdești, comuna Lupșa, judetul ALBA, România")),
        createLoc("Bârzan", "sat", createAdresaCompleta("sat Bârzan, comuna Lupșa, judetul ALBA, România")),
        createLoc("Curmătură", "sat", createAdresaCompleta("sat Curmătură, comuna Lupșa, judetul ALBA, România")),
        createLoc("După Deal", "sat", createAdresaCompleta("sat După Deal, comuna Lupșa, judetul ALBA, România")),
        createLoc("Geamăna", "sat", createAdresaCompleta("sat Geamăna, comuna Lupșa, judetul ALBA, România")),
        createLoc("Hădărău", "sat", createAdresaCompleta("sat Hădărău, comuna Lupșa, judetul ALBA, România")),
        createLoc("Holobani", "sat", createAdresaCompleta("sat Holobani, comuna Lupșa, judetul ALBA, România")),
        createLoc("Lazuri", "sat", createAdresaCompleta("sat Lazuri, comuna Lupșa, judetul ALBA, România")),
        createLoc("Lunca", "sat", createAdresaCompleta("sat Lunca, comuna Lupșa, judetul ALBA, România")),
        createLoc("Mănăstire", "sat", createAdresaCompleta("sat Mănăstire, comuna Lupșa, judetul ALBA, România")),
        createLoc("Mărgaia", "sat", createAdresaCompleta("sat Mărgaia, comuna Lupșa, judetul ALBA, România")),
        createLoc("Mușca", "sat", createAdresaCompleta("sat Mușca, comuna Lupșa, judetul ALBA, România")),
        createLoc("Pițiga", "sat", createAdresaCompleta("sat Pițiga, comuna Lupșa, judetul ALBA, România")),
        createLoc("Pârâu-Cărbunări", "sat", createAdresaCompleta("sat Pârâu-Cărbunări, comuna Lupșa, judetul ALBA, România")),
        createLoc("Poșogani", "sat", createAdresaCompleta("sat Poșogani, comuna Lupșa, judetul ALBA, România")),
        createLoc("Șasa", "sat", createAdresaCompleta("sat Șasa, comuna Lupșa, judetul ALBA, România")),
        createLoc("Trifești", "sat", createAdresaCompleta("sat Trifești, comuna Lupșa, judetul ALBA, România")),
        createLoc("Valea Holhorii", "sat", createAdresaCompleta("sat Valea Holhorii, comuna Lupșa, judetul ALBA, România")),
        createLoc("Valea Lupșii", "sat", createAdresaCompleta("sat Valea Lupșii, comuna Lupșa, judetul ALBA, România")),
        createLoc("Valea Șesii", "sat", createAdresaCompleta("sat Valea Șesii, comuna Lupșa, judetul ALBA, România")),
        createLoc("Văi", "sat", createAdresaCompleta("sat Văi, comuna Lupșa, judetul ALBA, România")),
        createLoc("Vința", "sat", createAdresaCompleta("sat Vința, comuna Lupșa, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Lupșa, judetul ALBA, România")),
    createComuna("Meteș", [
        createLoc("Meteș", "sat", createAdresaCompleta("sat Meteș, comuna Meteș, judetul ALBA, România")),
        createLoc("Ampoița", "sat", createAdresaCompleta("sat Ampoița, comuna Meteș, judetul ALBA, România")),
        createLoc("Isca", "sat", createAdresaCompleta("sat Isca, comuna Meteș, judetul ALBA, România")),
        createLoc("Lunca Ampoiței", "sat", createAdresaCompleta("sat Lunca Ampoiței, comuna Meteș, judetul ALBA, România")),
        createLoc("Lunca Meteșului", "sat", createAdresaCompleta("sat Lunca Meteșului, comuna Meteș, judetul ALBA, România")),
        createLoc("Pădurea", "sat", createAdresaCompleta("sat Pădurea, comuna Meteș, judetul ALBA, România")),
        createLoc("Poiana Ampoiului", "sat", createAdresaCompleta("sat Poiana Ampoiului, comuna Meteș, judetul ALBA, România")),
        createLoc("Poiana Ursului", "sat", createAdresaCompleta("sat Poiana Ursului, comuna Meteș, judetul ALBA, România")),
        createLoc("Presaca Ampoiului", "sat", createAdresaCompleta("sat Presaca Ampoiului, comuna Meteș, judetul ALBA, România")),
        createLoc("Remetea", "sat", createAdresaCompleta("sat Remetea, comuna Meteș, judetul ALBA, România")),
        createLoc("Tăuți", "sat", createAdresaCompleta("sat Tăuți, comuna Meteș, judetul ALBA, România")),
        createLoc("Văleni", "sat", createAdresaCompleta("sat Văleni, comuna Meteș, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Meteș, judetul ALBA, România")),
    createComuna("Mihalț", [
        createLoc("Mihalț", "sat", createAdresaCompleta("sat Mihalț, comuna Mihalț, judetul ALBA, România")),
        createLoc("Cistei", "sat", createAdresaCompleta("sat Cistei, comuna Mihalț, judetul ALBA, România")),
        createLoc("Obreja", "sat", createAdresaCompleta("sat Obreja, comuna Mihalț, judetul ALBA, România")),
        createLoc("Zărieș", "sat", createAdresaCompleta("sat Zărieș, comuna Mihalț, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Mihalț, judetul ALBA, România")),
    createComuna("Mirăslău", [
        createLoc("Mirăslău", "sat", createAdresaCompleta("sat Mirăslău, comuna Mirăslău, judetul ALBA, România")),
        createLoc("Cicău", "sat", createAdresaCompleta("sat Cicău, comuna Mirăslău, judetul ALBA, România")),
        createLoc("Decea", "sat", createAdresaCompleta("sat Decea, comuna Mirăslău, judetul ALBA, România")),
        createLoc("Lopadea Veche", "sat", createAdresaCompleta("sat Lopadea Veche, comuna Mirăslău, judetul ALBA, România")),
        createLoc("Ormeniș", "sat", createAdresaCompleta("sat Ormeniș, comuna Mirăslău, judetul ALBA, România")),
        createLoc("Rachiș", "sat", createAdresaCompleta("sat Rachiș, comuna Mirăslău, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Mirăslău, judetul ALBA, România")),
    createComuna("Mogoș", [
        createLoc("Mogoș", "sat", createAdresaCompleta("sat Mogoș, comuna Mogoș, judetul ALBA, România")),
        createLoc("Bărbești", "sat", createAdresaCompleta("sat Bărbești, comuna Mogoș, judetul ALBA, România")),
        createLoc("Bârlești", "sat", createAdresaCompleta("sat Bârlești, comuna Mogoș, judetul ALBA, România")),
        createLoc("Bârlești-Cătun", "sat", createAdresaCompleta("sat Bârlești-Cătun, comuna Mogoș, judetul ALBA, România")),
        createLoc("Bârzogani", "sat", createAdresaCompleta("sat Bârzogani, comuna Mogoș, judetul ALBA, România")),
        createLoc("Bocești", "sat", createAdresaCompleta("sat Bocești, comuna Mogoș, judetul ALBA, România")),
        createLoc("Bogdănești", "sat", createAdresaCompleta("sat Bogdănești, comuna Mogoș, judetul ALBA, România")),
        createLoc("Butești", "sat", createAdresaCompleta("sat Butești, comuna Mogoș, judetul ALBA, România")),
        createLoc("Cojocani", "sat", createAdresaCompleta("sat Cojocani, comuna Mogoș, judetul ALBA, România")),
        createLoc("Cristești", "sat", createAdresaCompleta("sat Cristești, comuna Mogoș, judetul ALBA, România")),
        createLoc("Mămăligani", "sat", createAdresaCompleta("sat Mămăligani, comuna Mogoș, judetul ALBA, România")),
        createLoc("Negrești", "sat", createAdresaCompleta("sat Negrești, comuna Mogoș, judetul ALBA, România")),
        createLoc("Oncești", "sat", createAdresaCompleta("sat Oncești, comuna Mogoș, judetul ALBA, România")),
        createLoc("Poienile-Mogoș", "sat", createAdresaCompleta("sat Poienile-Mogoș, comuna Mogoș, judetul ALBA, România")),
        createLoc("Tomești", "sat", createAdresaCompleta("sat Tomești, comuna Mogoș, judetul ALBA, România")),
        createLoc("Valea Barnii", "sat", createAdresaCompleta("sat Valea Barnii, comuna Mogoș, judetul ALBA, România")),
        createLoc("Valea Bârluțești", "sat", createAdresaCompleta("sat Valea Bârluțești, comuna Mogoș, judetul ALBA, România")),
        createLoc("Valea Cocești", "sat", createAdresaCompleta("sat Valea Cocești, comuna Mogoș, judetul ALBA, România")),
        createLoc("Valea Giogești", "sat", createAdresaCompleta("sat Valea Giogești, comuna Mogoș, judetul ALBA, România")),
        createLoc("Valea Mlacii", "sat", createAdresaCompleta("sat Valea Mlacii, comuna Mogoș, judetul ALBA, România")),
        createLoc("Valea Țupilor", "sat", createAdresaCompleta("sat Valea Țupilor, comuna Mogoș, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Mogoș, judetul ALBA, România")),
    createComuna("Noșlac", [
        createLoc("Noșlac", "sat", createAdresaCompleta("sat Noșlac, comuna Noșlac, judetul ALBA, România")),
        createLoc("Căptălan", "sat", createAdresaCompleta("sat Căptălan, comuna Noșlac, judetul ALBA, România")),
        createLoc("Copand", "sat", createAdresaCompleta("sat Copand, comuna Noșlac, judetul ALBA, România")),
        createLoc("Găbud", "sat", createAdresaCompleta("sat Găbud, comuna Noșlac, judetul ALBA, România")),
        createLoc("Stâna de Mureș", "sat", createAdresaCompleta("sat Stâna de Mureș, comuna Noșlac, judetul ALBA, România")),
        createLoc("Valea Ciuciului", "sat", createAdresaCompleta("sat Valea Ciuciului, comuna Noșlac, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Noșlac, judetul ALBA, România")),
    createComuna("Ocoliș", [
        createLoc("Ocoliș", "sat", createAdresaCompleta("sat Ocoliș, comuna Ocoliș, judetul ALBA, România")),
        createLoc("Lunca Largă", "sat", createAdresaCompleta("sat Lunca Largă, comuna Ocoliș, judetul ALBA, România")),
        createLoc("Runc", "sat", createAdresaCompleta("sat Runc, comuna Ocoliș, judetul ALBA, România")),
        createLoc("Vidolm", "sat", createAdresaCompleta("sat Vidolm, comuna Ocoliș, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Ocoliș, judetul ALBA, România")),
    createComuna("Ohaba", [
        createLoc("Ohaba", "sat", createAdresaCompleta("sat Ohaba, comuna Ohaba, judetul ALBA, România")),
        createLoc("Colibi", "sat", createAdresaCompleta("sat Colibi, comuna Ohaba, judetul ALBA, România")),
        createLoc("Măghierat", "sat", createAdresaCompleta("sat Măghierat, comuna Ohaba, judetul ALBA, România")),
        createLoc("Secășel", "sat", createAdresaCompleta("sat Secășel, comuna Ohaba, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Ohaba, judetul ALBA, România")),
    createComuna("Pianu", [
        createLoc("Pianu de Sus", "sat", createAdresaCompleta("sat Pianu de Sus, comuna Pianu, judetul ALBA, România")),
        createLoc("Pianu de Jos", "sat", createAdresaCompleta("sat Pianu de Jos, comuna Pianu, judetul ALBA, România")),
        createLoc("Plaiuri", "sat", createAdresaCompleta("sat Plaiuri, comuna Pianu, judetul ALBA, România")),
        createLoc("Purcăreți", "sat", createAdresaCompleta("sat Purcăreți, comuna Pianu, judetul ALBA, România")),
        createLoc("Strungari", "sat", createAdresaCompleta("sat Strungari, comuna Pianu, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Pianu, judetul ALBA, România")),
    createComuna("Poiana Vadului", [
        createLoc("Poiana Vadului", "sat", createAdresaCompleta("sat Poiana Vadului, comuna Poiana Vadului, judetul ALBA, România")),
        createLoc("Costești", "sat", createAdresaCompleta("sat Costești, comuna Poiana Vadului, judetul ALBA, România")),
        createLoc("Duduieni", "sat", createAdresaCompleta("sat Duduieni, comuna Poiana Vadului, judetul ALBA, România")),
        createLoc("Făgetu de Jos", "sat", createAdresaCompleta("sat Făgetu de Jos, comuna Poiana Vadului, judetul ALBA, România")),
        createLoc("Făgetu de Sus", "sat", createAdresaCompleta("sat Făgetu de Sus, comuna Poiana Vadului, judetul ALBA, România")),
        createLoc("Hănășești", "sat", createAdresaCompleta("sat Hănășești, comuna Poiana Vadului, judetul ALBA, România")),
        createLoc("Lupăiești", "sat", createAdresaCompleta("sat Lupăiești, comuna Poiana Vadului, judetul ALBA, România")),
        createLoc("Morcănești", "sat", createAdresaCompleta("sat Morcănești, comuna Poiana Vadului, judetul ALBA, România")),
        createLoc("Păștești", "sat", createAdresaCompleta("sat Păștești, comuna Poiana Vadului, judetul ALBA, România")),
        createLoc("Petelei", "sat", createAdresaCompleta("sat Petelei, comuna Poiana Vadului, judetul ALBA, România")),
        createLoc("Stănești", "sat", createAdresaCompleta("sat Stănești, comuna Poiana Vadului, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Poiana Vadului, judetul ALBA, România")),
    createComuna("Ponor", [
        createLoc("Ponor", "sat", createAdresaCompleta("sat Ponor, comuna Ponor, judetul ALBA, România")),
        createLoc("După Deal", "sat", createAdresaCompleta("sat După Deal, comuna Ponor, judetul ALBA, România")),
        createLoc("Geogel", "sat", createAdresaCompleta("sat Geogel, comuna Ponor, judetul ALBA, România")),
        createLoc("Măcărești", "sat", createAdresaCompleta("sat Măcărești, comuna Ponor, judetul ALBA, România")),
        createLoc("Valea Bucurului", "sat", createAdresaCompleta("sat Valea Bucurului, comuna Ponor, judetul ALBA, România")),
        createLoc("Vale în Jos", "sat", createAdresaCompleta("sat Vale în Jos, comuna Ponor, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Ponor, judetul ALBA, România")),
    createComuna("Poșaga", [
        createLoc("Poșaga", "sat", createAdresaCompleta("sat Poșaga, comuna Poșaga, judetul ALBA, România")),
        createLoc("Poșaga de Jos", "sat", createAdresaCompleta("sat Poșaga de Jos, comuna Poșaga, judetul ALBA, România")),
        createLoc("Corțești", "sat", createAdresaCompleta("sat Corțești, comuna Poșaga, judetul ALBA, România")),
        createLoc("Incești", "sat", createAdresaCompleta("sat Incești, comuna Poșaga, judetul ALBA, România")),
        createLoc("Lunca", "sat", createAdresaCompleta("sat Lunca, comuna Poșaga, judetul ALBA, România")),
        createLoc("Orăști", "sat", createAdresaCompleta("sat Orăști, comuna Poșaga, judetul ALBA, România")),
        createLoc("Poșaga de Sus", "sat", createAdresaCompleta("sat Poșaga de Sus, comuna Poșaga, judetul ALBA, România")),
        createLoc("Săgagea", "sat", createAdresaCompleta("sat Săgagea, comuna Poșaga, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Poșaga, judetul ALBA, România")),
    createComuna("Rădești", [
        createLoc("Rădești", "sat", createAdresaCompleta("sat Rădești, comuna Rădești, judetul ALBA, România")),
        createLoc("Leorinț", "sat", createAdresaCompleta("sat Leorinț, comuna Rădești, judetul ALBA, România")),
        createLoc("Meșcreac", "sat", createAdresaCompleta("sat Meșcreac, comuna Rădești, judetul ALBA, România")),
        createLoc("Șoimuș", "sat", createAdresaCompleta("sat Șoimuș, comuna Rădești, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Rădești, judetul ALBA, România")),
    createComuna("Rimetea", [
        createLoc("Rimetea", "sat", createAdresaCompleta("sat Rimetea, comuna Rimetea, judetul ALBA, România")),
        createLoc("Colțești", "sat", createAdresaCompleta("sat Colțești, comuna Rimetea, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Rimetea, judetul ALBA, România")),
    createComuna("Râmetea", [
        createLoc("Râmetea", "sat", createAdresaCompleta("sat Râmetea, comuna Râmetea, judetul ALBA, România")),
        createLoc("Boțani", "sat", createAdresaCompleta("sat Boțani, comuna Râmetea, judetul ALBA, România")),
        createLoc("Brădești", "sat", createAdresaCompleta("sat Brădești, comuna Râmetea, judetul ALBA, România")),
        createLoc("Cheia", "sat", createAdresaCompleta("sat Cheia, comuna Râmetea, judetul ALBA, România")),
        createLoc("Cotorăști", "sat", createAdresaCompleta("sat Cotorăști, comuna Râmetea, judetul ALBA, România")),
        createLoc("Florești", "sat", createAdresaCompleta("sat Florești, comuna Râmetea, judetul ALBA, România")),
        createLoc("Olteni", "sat", createAdresaCompleta("sat Olteni, comuna Râmetea, judetul ALBA, România")),
        createLoc("Valea Făgetului", "sat", createAdresaCompleta("sat Valea Făgetului, comuna Râmetea, judetul ALBA, România")),
        createLoc("Valea Inzelului", "sat", createAdresaCompleta("sat Valea Inzelului, comuna Râmetea, judetul ALBA, România")),
        createLoc("Valea Mănăstirii", "sat", createAdresaCompleta("sat Valea Mănăstirii, comuna Râmetea, judetul ALBA, România")),
        createLoc("Valea Poienii", "sat", createAdresaCompleta("sat Valea Poienii, comuna Râmetea, judetul ALBA, România")),
        createLoc("Valea Uzei", "sat", createAdresaCompleta("sat Valea Uzei, comuna Râmetea, judetul ALBA, România")),
        createLoc("Vlădești", "sat", createAdresaCompleta("sat Vlădești, comuna Râmetea, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Râmetea, judetul ALBA, România")),
    createComuna("Roșia Montană", [
        createLoc("Roșia Montană", "sat", createAdresaCompleta("sat Roșia Montană, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Bălmoșești", "sat", createAdresaCompleta("sat Bălmoșești, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Blidești", "sat", createAdresaCompleta("sat Blidești, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Bunta", "sat", createAdresaCompleta("sat Bunta, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Cărpiniș", "sat", createAdresaCompleta("sat Cărpiniș, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Coasta Henții", "sat", createAdresaCompleta("sat Coasta Henții, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Corna", "sat", createAdresaCompleta("sat Corna, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Curături", "sat", createAdresaCompleta("sat Curături, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Dăroaia", "sat", createAdresaCompleta("sat Dăroaia, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Gârda-Bărbulești", "sat", createAdresaCompleta("sat Gârda-Bărbulești, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Gura Roșiei", "sat", createAdresaCompleta("sat Gura Roșiei, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Iacobești", "sat", createAdresaCompleta("sat Iacobești, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Ignățești", "sat", createAdresaCompleta("sat Ignățești, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Șoal", "sat", createAdresaCompleta("sat Șoal, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Țarina", "sat", createAdresaCompleta("sat Țarina, comuna Roșia Montană, judetul ALBA, România")),
        createLoc("Vârtop", "sat", createAdresaCompleta("sat Vârtop, comuna Roșia Montană, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Roșia Montană, judetul ALBA, România")),
    createComuna("Roșia de Secaș", [
        createLoc("Roșia de Secaș", "sat", createAdresaCompleta("sat Roșia de Secaș, comuna Roșia de Secaș, judetul ALBA, România")),
        createLoc("Tău", "sat", createAdresaCompleta("sat Tău, comuna Roșia de Secaș, judetul ALBA, România")),
        createLoc("Ungurei", "sat", createAdresaCompleta("sat Ungurei, comuna Roșia de Secaș, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Roșia de Secaș, judetul ALBA, România")),
    createComuna("Sălciua", [
        createLoc("Sălciua de Jos", "sat", createAdresaCompleta("sat Sălciua de Jos, comuna Sălciua, judetul ALBA, România")),
        createLoc("Dealu Caselor", "sat", createAdresaCompleta("sat Dealu Caselor, comuna Sălciua, judetul ALBA, România")),
        createLoc("Dumești", "sat", createAdresaCompleta("sat Dumești, comuna Sălciua, judetul ALBA, România")),
        createLoc("Sălciua de Sus", "sat", createAdresaCompleta("sat Sălciua de Sus, comuna Sălciua, judetul ALBA, România")),
        createLoc("Sub Piatră", "sat", createAdresaCompleta("sat Sub Piatră, comuna Sălciua, judetul ALBA, România")),
        createLoc("Valea Largă", "sat", createAdresaCompleta("sat Valea Largă, comuna Sălciua, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Sălciua, judetul ALBA, România")),
    createComuna("Săliștea", [
        createLoc("Săliștea", "sat", createAdresaCompleta("sat Săliștea, comuna Săliștea, judetul ALBA, România")),
        createLoc("Mărgineni", "sat", createAdresaCompleta("sat Mărgineni, comuna Săliștea, judetul ALBA, România")),
        createLoc("Săliștea-Deal", "sat", createAdresaCompleta("sat Săliștea-Deal, comuna Săliștea, judetul ALBA, România")),
        createLoc("Tărtăria", "sat", createAdresaCompleta("sat Tărtăria, comuna Săliștea, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Săliștea, judetul ALBA, România")),
    createComuna("Săsciori", [
        createLoc("Săsciori", "sat", createAdresaCompleta("sat Săsciori, comuna Săsciori, judetul ALBA, România")),
        createLoc("Căpâlna", "sat", createAdresaCompleta("sat Căpâlna, comuna Săsciori, judetul ALBA, România")),
        createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, comuna Săsciori, judetul ALBA, România")),
        createLoc("Laz", "sat", createAdresaCompleta("sat Laz, comuna Săsciori, judetul ALBA, România")),
        createLoc("Loman", "sat", createAdresaCompleta("sat Loman, comuna Săsciori, judetul ALBA, România")),
        createLoc("Pleși", "sat", createAdresaCompleta("sat Pleși, comuna Săsciori, judetul ALBA, România")),
        createLoc("Răchita", "sat", createAdresaCompleta("sat Răchita, comuna Săsciori, judetul ALBA, România")),
        createLoc("Sebeșel", "sat", createAdresaCompleta("sat Sebeșel, comuna Săsciori, judetul ALBA, România")),
        createLoc("Tonea", "sat", createAdresaCompleta("sat Tonea, comuna Săsciori, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Săsciori, judetul ALBA, România")),
    createComuna("Scărișoara", [
        createLoc("Scărișoara", "sat", createAdresaCompleta("sat Scărișoara, comuna Scărișoara, judetul ALBA, România")),
        createLoc("Bârlești", "sat", createAdresaCompleta("sat Bârlești, comuna Scărișoara, judetul ALBA, România")),
        createLoc("Botești", "sat", createAdresaCompleta("sat Botești, comuna Scărișoara, judetul ALBA, România")),
        createLoc("Fața-Lăzești", "sat", createAdresaCompleta("sat Fața-Lăzești, comuna Scărișoara, judetul ALBA, România")),
        createLoc("Florești", "sat", createAdresaCompleta("sat Florești, comuna Scărișoara, judetul ALBA, România")),
        createLoc("Lăzești", "sat", createAdresaCompleta("sat Lăzești, comuna Scărișoara, judetul ALBA, România")),
        createLoc("Lespezea", "sat", createAdresaCompleta("sat Lespezea, comuna Scărișoara, judetul ALBA, România")),
        createLoc("Maței", "sat", createAdresaCompleta("sat Maței, comuna Scărișoara, judetul ALBA, România")),
        createLoc("Negești", "sat", createAdresaCompleta("sat Negești, comuna Scărișoara, judetul ALBA, România")),
        createLoc("Prelucă", "sat", createAdresaCompleta("sat Prelucă, comuna Scărișoara, judetul ALBA, România")),
        createLoc("Runc", "sat", createAdresaCompleta("sat Runc, comuna Scărișoara, judetul ALBA, România")),
        createLoc("Sfoartea", "sat", createAdresaCompleta("sat Sfoartea, comuna Scărișoara, judetul ALBA, România")),
        createLoc("Știuleți", "sat", createAdresaCompleta("sat Știuleți, comuna Scărișoara, judetul ALBA, România")),
        createLoc("Trâncești", "sat", createAdresaCompleta("sat Trâncești, comuna Scărișoara, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Scărișoara, judetul ALBA, România")),
    createComuna("Sâncel", [
        createLoc("Sâncel", "sat", createAdresaCompleta("sat Sâncel, comuna Sâncel, judetul ALBA, România")),
        createLoc("Iclod", "sat", createAdresaCompleta("sat Iclod, comuna Sâncel, judetul ALBA, România")),
        createLoc("Pănade", "sat", createAdresaCompleta("sat Pănade, comuna Sâncel, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Sâncel, judetul ALBA, România")),
    createComuna("Sântimbru", [
        createLoc("Sântimbru", "sat", createAdresaCompleta("sat Sântimbru, comuna Sântimbru, judetul ALBA, România")),
        createLoc("Coșlariu", "sat", createAdresaCompleta("sat Coșlariu, comuna Sântimbru, judetul ALBA, România")),
        createLoc("Dumitra", "sat", createAdresaCompleta("sat Dumitra, comuna Sântimbru, judetul ALBA, România")),
        createLoc("Galtiu", "sat", createAdresaCompleta("sat Galtiu, comuna Sântimbru, judetul ALBA, România")),
        createLoc("Totoi", "sat", createAdresaCompleta("sat Totoi, comuna Sântimbru, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Sântimbru, judetul ALBA, România")),
    createComuna("Sohodol", [
        createLoc("Sohodol", "sat", createAdresaCompleta("sat Sohodol, comuna Sohodol, judetul ALBA, România")),
        createLoc("Băzești", "sat", createAdresaCompleta("sat Băzești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Bilănești", "sat", createAdresaCompleta("sat Bilănești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Bobărești", "sat", createAdresaCompleta("sat Bobărești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Brădeana", "sat", createAdresaCompleta("sat Brădeana, comuna Sohodol, judetul ALBA, România")),
        createLoc("Burzonești", "sat", createAdresaCompleta("sat Burzonești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Deoncești", "sat", createAdresaCompleta("sat Deoncești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Dilimani", "sat", createAdresaCompleta("sat Dilimani, comuna Sohodol, judetul ALBA, România")),
        createLoc("Furduiești", "sat", createAdresaCompleta("sat Furduiești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Gura Sohodol", "sat", createAdresaCompleta("sat Gura Sohodol, comuna Sohodol, judetul ALBA, România")),
        createLoc("Hoancă", "sat", createAdresaCompleta("sat Hoancă, comuna Sohodol, judetul ALBA, România")),
        createLoc("Joldișești", "sat", createAdresaCompleta("sat Joldișești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Lazuri", "sat", createAdresaCompleta("sat Lazuri, comuna Sohodol, judetul ALBA, România")),
        createLoc("Lehești", "sat", createAdresaCompleta("sat Lehești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Luminești", "sat", createAdresaCompleta("sat Luminești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Medrești", "sat", createAdresaCompleta("sat Medrești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Morărești", "sat", createAdresaCompleta("sat Morărești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Munești", "sat", createAdresaCompleta("sat Munești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Năpăiești", "sat", createAdresaCompleta("sat Năpăiești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Nelegești", "sat", createAdresaCompleta("sat Nelegești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Nicorești", "sat", createAdresaCompleta("sat Nicorești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Peleș", "sat", createAdresaCompleta("sat Peleș, comuna Sohodol, judetul ALBA, România")),
        createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Sohodol, judetul ALBA, România")),
        createLoc("Robești", "sat", createAdresaCompleta("sat Robești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Sicoiești", "sat", createAdresaCompleta("sat Sicoiești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Surdești", "sat", createAdresaCompleta("sat Surdești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Sebișești", "sat", createAdresaCompleta("sat Sebișești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Șimocești", "sat", createAdresaCompleta("sat Șimocești, comuna Sohodol, judetul ALBA, România")),
        createLoc("Țoci", "sat", createAdresaCompleta("sat Țoci, comuna Sohodol, judetul ALBA, România")),
        createLoc("Valea Verde", "sat", createAdresaCompleta("sat Valea Verde, comuna Sohodol, judetul ALBA, România")),
        createLoc("Vlădoșești", "sat", createAdresaCompleta("sat Vlădoșești, comuna Sohodol, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Sohodol, judetul ALBA, România")),
    createComuna("Stremț", [
        createLoc("Stremț", "sat", createAdresaCompleta("sat Stremț, comuna Stremț, judetul ALBA, România")),
        createLoc("Fața Pietrii", "sat", createAdresaCompleta("sat Fața Pietrii, comuna Stremț, judetul ALBA, România")),
        createLoc("Geoagiu de Sus", "sat", createAdresaCompleta("sat Geoagiu de Sus, comuna Stremț, judetul ALBA, România")),
        createLoc("Geomal", "sat", createAdresaCompleta("sat Geomal, comuna Stremț, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Stremț, judetul ALBA, România")),
    createComuna("Șibot", [
        createLoc("Șibot", "sat", createAdresaCompleta("sat Șibot, comuna Șibot, judetul ALBA, România")),
        createLoc("Balomiru de Câmp", "sat", createAdresaCompleta("sat Balomiru de Câmp, comuna Șibot, judetul ALBA, România")),
        createLoc("Băcăinți", "sat", createAdresaCompleta("sat Băcăinți, comuna Șibot, judetul ALBA, România")),
        createLoc("Sărăcsău", "sat", createAdresaCompleta("sat Sărăcsău, comuna Șibot, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Șibot, judetul ALBA, România")),
    createComuna("Șona", [
        createLoc("Șona", "sat", createAdresaCompleta("sat Șona, comuna Șona, judetul ALBA, România")),
        createLoc("Alecuș", "sat", createAdresaCompleta("sat Alecuș, comuna Șona, judetul ALBA, România")),
        createLoc("Biia", "sat", createAdresaCompleta("sat Biia, comuna Șona, judetul ALBA, România")),
        createLoc("Doptău", "sat", createAdresaCompleta("sat Doptău, comuna Șona, judetul ALBA, România")),
        createLoc("Lunca Târnavei", "sat", createAdresaCompleta("sat Lunca Târnavei, comuna Șona, judetul ALBA, România")),
        createLoc("Sânmiclăuș", "sat", createAdresaCompleta("sat Sânmiclăuș, comuna Șona, judetul ALBA, România")),
        createLoc("Valea Sasului", "sat", createAdresaCompleta("sat Valea Sasului, comuna Șona, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Șona, judetul ALBA, România")),
    createComuna("Șpring", [
        createLoc("Șpring", "sat", createAdresaCompleta("sat Șpring, comuna Șpring, judetul ALBA, România")),
        createLoc("Carpen", "sat", createAdresaCompleta("sat Carpen, comuna Șpring, judetul ALBA, România")),
        createLoc("Carpenii de Sus", "sat", createAdresaCompleta("sat Carpenii de Sus, comuna Șpring, judetul ALBA, România")),
        createLoc("Cunța", "sat", createAdresaCompleta("sat Cunța, comuna Șpring, judetul ALBA, România")),
        createLoc("Drașov", "sat", createAdresaCompleta("sat Drașov, comuna Șpring, judetul ALBA, România")),
        createLoc("Vingard", "sat", createAdresaCompleta("sat Vingard, comuna Șpring, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Șpring, judetul ALBA, România")),
    createComuna("Șugag", [
        createLoc("Șugag", "sat", createAdresaCompleta("sat Șugag, comuna Șugag, judetul ALBA, România")),
        createLoc("Arți", "sat", createAdresaCompleta("sat Arți, comuna Șugag, judetul ALBA, România")),
        createLoc("Bârsana", "sat", createAdresaCompleta("sat Bârsana, comuna Șugag, judetul ALBA, România")),
        createLoc("Dobra", "sat", createAdresaCompleta("sat Dobra, comuna Șugag, judetul ALBA, România")),
        createLoc("Jidoștina", "sat", createAdresaCompleta("sat Jidoștina, comuna Șugag, judetul ALBA, România")),
        createLoc("Mărtinie", "sat", createAdresaCompleta("sat Mărtinie, comuna Șugag, judetul ALBA, România")),
        createLoc("Tău Bistra", "sat", createAdresaCompleta("sat Tău Bistra, comuna Șugag, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Șugag, judetul ALBA, România")),
    createComuna("Unirea", [
        createLoc("Unirea", "sat", createAdresaCompleta("sat Unirea, comuna Unirea, judetul ALBA, România")),
        createLoc("Ciugudu de Jos", "sat", createAdresaCompleta("sat Ciugudu de Jos, comuna Unirea, judetul ALBA, România")),
        createLoc("Ciugudu de Sus", "sat", createAdresaCompleta("sat Ciugudu de Sus, comuna Unirea, judetul ALBA, România")),
        createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, comuna Unirea, judetul ALBA, România")),
        createLoc("Inoc", "sat", createAdresaCompleta("sat Inoc, comuna Unirea, judetul ALBA, România")),
        createLoc("Măhăceni", "sat", createAdresaCompleta("sat Măhăceni, comuna Unirea, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Unirea, judetul ALBA, România")),
    createComuna("Vadu Moților", [
        createLoc("Vadu Moților", "sat", createAdresaCompleta("sat Vadu Moților, comuna Vadu Moților, judetul ALBA, România")),
        createLoc("Bodești", "sat", createAdresaCompleta("sat Bodești, comuna Vadu Moților, judetul ALBA, România")),
        createLoc("Burzești", "sat", createAdresaCompleta("sat Burzești, comuna Vadu Moților, judetul ALBA, România")),
        createLoc("Dealu Frumos", "sat", createAdresaCompleta("sat Dealu Frumos, comuna Vadu Moților, judetul ALBA, România")),
        createLoc("Lăzești", "sat", createAdresaCompleta("sat Lăzești, comuna Vadu Moților, judetul ALBA, România")),
        createLoc("Necșești", "sat", createAdresaCompleta("sat Necșești, comuna Vadu Moților, judetul ALBA, România")),
        createLoc("Poduri-Bricești", "sat", createAdresaCompleta("sat Poduri-Bricești, comuna Vadu Moților, judetul ALBA, România")),
        createLoc("Popeștii de Jos", "sat", createAdresaCompleta("sat Popeștii de Jos, comuna Vadu Moților, judetul ALBA, România")),
        createLoc("Popeștii de Sus", "sat", createAdresaCompleta("sat Popeștii de Sus, comuna Vadu Moților, judetul ALBA, România")),
        createLoc("Tomuțești", "sat", createAdresaCompleta("sat Tomuțești, comuna Vadu Moților, judetul ALBA, România")),
        createLoc("Toțești", "sat", createAdresaCompleta("sat Toțești, comuna Vadu Moților, judetul ALBA, România")),
        createLoc("Vâltori", "sat", createAdresaCompleta("sat Vâltori, comuna Vadu Moților, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Vadu Moților, judetul ALBA, România")),
    createComuna("Valea Lungă", [
        createLoc("Valea Lungă", "sat", createAdresaCompleta("sat Valea Lungă, comuna Valea Lungă, judetul ALBA, România")),
        createLoc("Făget", "sat", createAdresaCompleta("sat Făget, comuna Valea Lungă, judetul ALBA, România")),
        createLoc("Glogoveț", "sat", createAdresaCompleta("sat Glogoveț, comuna Valea Lungă, judetul ALBA, România")),
        createLoc("Lodroman", "sat", createAdresaCompleta("sat Lodroman, comuna Valea Lungă, judetul ALBA, România")),
        createLoc("Lunca", "sat", createAdresaCompleta("sat Lunca, comuna Valea Lungă, judetul ALBA, România")),
        createLoc("Tăuni", "sat", createAdresaCompleta("sat Tăuni, comuna Valea Lungă, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Valea Lungă, judetul ALBA, România")),
    createComuna("Vidra", [
        createLoc("Vidra", "sat", createAdresaCompleta("sat Vidra, comuna Vidra, judetul ALBA, România")),
        createLoc("Băi", "sat", createAdresaCompleta("sat Băi, comuna Vidra, judetul ALBA, România")),
        createLoc("Bobărești", "sat", createAdresaCompleta("sat Bobărești, comuna Vidra, judetul ALBA, România")),
        createLoc("Bogdănești", "sat", createAdresaCompleta("sat Bogdănești, comuna Vidra, judetul ALBA, România")),
        createLoc("Bordeștii Poieni", "sat", createAdresaCompleta("sat Bordeștii Poieni, comuna Vidra, judetul ALBA, România")),
        createLoc("Culdești", "sat", createAdresaCompleta("sat Culdești, comuna Vidra, judetul ALBA, România")),
        createLoc("Dealu Goiești", "sat", createAdresaCompleta("sat Dealu Goiești, comuna Vidra, judetul ALBA, România")),
        createLoc("Dos", "sat", createAdresaCompleta("sat Dos, comuna Vidra, judetul ALBA, România")),
        createLoc("Dosu Luncii", "sat", createAdresaCompleta("sat Dosu Luncii, comuna Vidra, judetul ALBA, România")),
        createLoc("Dosu Văsești", "sat", createAdresaCompleta("sat Dosu Văsești, comuna Vidra, judetul ALBA, România")),
        createLoc("Drăgoiești-Luncă", "sat", createAdresaCompleta("sat Drăgoiești-Luncă, comuna Vidra, judetul ALBA, România")),
        createLoc("Ficărești", "sat", createAdresaCompleta("sat Ficărești, comuna Vidra, judetul ALBA, România")),
        createLoc("Gligorești", "sat", createAdresaCompleta("sat Gligorești, comuna Vidra, judetul ALBA, România")),
        createLoc("Goiești", "sat", createAdresaCompleta("sat Goiești, comuna Vidra, judetul ALBA, România")),
        createLoc("Haiducești", "sat", createAdresaCompleta("sat Haiducești, comuna Vidra, judetul ALBA, România")),
        createLoc("Hărăști", "sat", createAdresaCompleta("sat Hărăști, comuna Vidra, judetul ALBA, România")),
        createLoc("Hoancă", "sat", createAdresaCompleta("sat Hoancă, comuna Vidra, judetul ALBA, România")),
        createLoc("Jeflești", "sat", createAdresaCompleta("sat Jeflești, comuna Vidra, judetul ALBA, România")),
        createLoc("Lunca", "sat", createAdresaCompleta("sat Lunca, comuna Vidra, judetul ALBA, România")),
        createLoc("Lunca Bisericii", "sat", createAdresaCompleta("sat Lunca Bisericii, comuna Vidra, judetul ALBA, România")),
        createLoc("Lunca de Jos", "sat", createAdresaCompleta("sat Lunca de Jos, comuna Vidra, judetul ALBA, România")),
        createLoc("Lunca Goiești", "sat", createAdresaCompleta("sat Lunca Goiești, comuna Vidra, judetul ALBA, România")),
        createLoc("Lunca Vesești", "sat", createAdresaCompleta("sat Lunca Vesești, comuna Vidra, judetul ALBA, România")),
        createLoc("Modolești", "sat", createAdresaCompleta("sat Modolești, comuna Vidra, judetul ALBA, România")),
        createLoc("Nemeși", "sat", createAdresaCompleta("sat Nemeși, comuna Vidra, judetul ALBA, România")),
        createLoc("Oidești", "sat", createAdresaCompleta("sat Oidești, comuna Vidra, judetul ALBA, România")),
        createLoc("Pitărcești", "sat", createAdresaCompleta("sat Pitărcești, comuna Vidra, judetul ALBA, România")),
        createLoc("Pleșcuța", "sat", createAdresaCompleta("sat Pleșcuța, comuna Vidra, judetul ALBA, România")),
        createLoc("Poieni", "sat", createAdresaCompleta("sat Poieni, comuna Vidra, judetul ALBA, România")),
        createLoc("Ponorel", "sat", createAdresaCompleta("sat Ponorel, comuna Vidra, judetul ALBA, România")),
        createLoc("Puiulețești", "sat", createAdresaCompleta("sat Puiulețești, comuna Vidra, judetul ALBA, România")),
        createLoc("Runc", "sat", createAdresaCompleta("sat Runc, comuna Vidra, judetul ALBA, România")),
        createLoc("Segaj", "sat", createAdresaCompleta("sat Segaj, comuna Vidra, judetul ALBA, România")),
        createLoc("Urdeș", "sat", createAdresaCompleta("sat Urdeș, comuna Vidra, judetul ALBA, România")),
        createLoc("Valea Morii", "sat", createAdresaCompleta("sat Valea Morii, comuna Vidra, judetul ALBA, România")),
        createLoc("Văsești", "sat", createAdresaCompleta("sat Văsești, comuna Vidra, judetul ALBA, România")),
        createLoc("Vâlcăneasa", "sat", createAdresaCompleta("sat Vâlcăneasa, comuna Vidra, judetul ALBA, România")),
        createLoc("Vâlcești", "sat", createAdresaCompleta("sat Vâlcești, comuna Vidra, judetul ALBA, România")),
        createLoc("Vârtănești", "sat", createAdresaCompleta("sat Vârtănești, comuna Vidra, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Vidra, judetul ALBA, România")),
    createComuna("Vințu de Jos", [
        createLoc("Vințu de Jos", "sat", createAdresaCompleta("sat Vințu de Jos, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Ciocașu", "sat", createAdresaCompleta("sat Ciocașu, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Câmpu Goblii", "sat", createAdresaCompleta("sat Câmpu Goblii, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Crișeni", "sat", createAdresaCompleta("sat Crișeni, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Dealu Ferului", "sat", createAdresaCompleta("sat Dealu Ferului, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Gura Cuțului", "sat", createAdresaCompleta("sat Gura Cuțului, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Hațegana", "sat", createAdresaCompleta("sat Hațegana, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Inuri", "sat", createAdresaCompleta("sat Inuri, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Laz", "sat", createAdresaCompleta("sat Laz, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Mătăcina", "sat", createAdresaCompleta("sat Mătăcina, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Mereteu", "sat", createAdresaCompleta("sat Mereteu, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Pârău lui Mihai", "sat", createAdresaCompleta("sat Părău lui Mihai, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Poienița", "sat", createAdresaCompleta("sat Poienița, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Stăuini", "sat", createAdresaCompleta("sat Stăuini, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Valea Goblii", "sat", createAdresaCompleta("sat Valea Goblii, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Valea lui Mihai", "sat", createAdresaCompleta("sat Valea lui Mihai, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Valea Vințului", "sat", createAdresaCompleta("sat Valea Vințului, comuna Vințu de Jos, judetul ALBA, România")),
        createLoc("Vurpăr", "sat", createAdresaCompleta("sat Vurpăr, comuna Vințu de Jos, judetul ALBA, România")),
    ], createAdresaCompleta("comuna Vințu de Jos, judetul ALBA, România")),
];
?>
