<?php
$comune =[
			createComuna("Albac", [
					createLoc("Albac", "sat"),
					createLoc("Bărăști", "sat"),
					createLoc("Budăiești", "sat"),
					createLoc("Cionești", "sat"),
					createLoc("Costești", "sat"),
					createLoc("Dealu Lămășoi", "sat"),
					createLoc("Deve", "sat"),
					createLoc("După Pleșe", "sat"),
					createLoc("Fața", "sat"),
					createLoc("Pleșești", "sat"),
					createLoc("Potionci", "sat"),
					createLoc("Rogoz", "sat"),
					createLoc("Roșești", "sat"),
					createLoc("Rusești", "sat"),
					createLoc("Sohodol", "sat"),
					createLoc("Tamborești", "sat"),
								  ]),
			createComuna("Almașu Mare", [
					createLoc("Almașu Mare", "sat"),
					createLoc("Almașu de Mijloc", "sat"),
					createLoc("Brădet", "sat"),
					createLoc("Cheile Cibului", "sat"),
					createLoc("Cib", "sat"),
					createLoc("Glod", "sat"),
					createLoc("Nădăștia", "sat"),
								  ]),	
			createComuna("Arieșeni", [
					createLoc("Arieșeni", "sat"),
					createLoc("Avrămești", "sat"),
					createLoc("Bubești", "sat"),
					createLoc("Casa de Piatră", "sat"),
					createLoc("Cobleș", "sat"),
					createLoc("Dealu Bajului", "sat"),
					createLoc("Fața Cristesei", "sat"),
					createLoc("Fața Lăpușului", "sat"),
					createLoc("Galbena", "sat"),
					createLoc("Hodobana", "sat"),
					createLoc("Izlaz", "sat"),
					createLoc("Păntești", "sat"),
					createLoc("Pătrăhăițești", "sat"),
					createLoc("Poienița", "sat"),
					createLoc("Ravicești", "sat"),
					createLoc("Sturu", "sat"),
					createLoc("Ștei-Arieșeni", "sat"),
					createLoc("Vanvucești", "sat"),
								  ]),
			createComuna("Avram Iancu", [
					createLoc("Avram Iancu", "sat"),
					createLoc("Achimețești", "sat"),
					createLoc("Avrămești", "sat"),
					createLoc("Bădăi", "sat"),
					createLoc("Boldești", "sat"),
					createLoc("Călugărești", "sat"),
					createLoc("Căsoaia", "sat"),
					createLoc("Cândești", "sat"),
					createLoc("Cârăști", "sat"),
					createLoc("Cârțulești", "sat"),
					createLoc("Cocești", "sat"),
					createLoc("Cocoșești", "sat"),
					createLoc("Coroiești", "sat"),
					createLoc("Dealu Crișului", "sat"),
					createLoc("Dolești", "sat"),
					createLoc("Dumăcești", "sat"),
					createLoc("Gojeiești", "sat"),
					createLoc("Helerești", "sat"),
					createLoc("Incești", "sat"),
					createLoc("Jojei", "sat"),
					createLoc("Mărtești", "sat"),
					createLoc("Orgești", "sat"),
					createLoc("Pătruțești", "sat"),
					createLoc("Plai", "sat"),
					createLoc("Pușelești", "sat"),
					createLoc("Șoicești", "sat"),
					createLoc("Ștertești", "sat"),
					createLoc("Târsa", "sat"),
					createLoc("Târsa-Plai", "sat"),
					createLoc("Valea Maciului", "sat"),
					createLoc("Valea Uțului", "sat"),
					createLoc("Verdești", "sat"),
					createLoc("Vidrișoara", "sat"),
								  ]),
			createComuna("Berghin", [
					createLoc("Berghin", "sat"),
					createLoc("Ghirbom", "sat"),
					createLoc("Henig", "sat"),
					createLoc("Straja", "sat"),					
								  ]),
			createComuna("Bistra", [
					createLoc("Bistra", "sat"),
					createLoc("Aronești", "sat"),
					createLoc("Bălești", "sat"),
					createLoc("Bălești-Cătun", "sat"),
					createLoc("Bârlești", "sat"),
					createLoc("Cheleteni", "sat"),
					createLoc("Ciuldești", "sat"),
					createLoc("Crețești", "sat"),
					createLoc("Dealu Muntelui", "sat"),
					createLoc("Dâmbureni", "sat"),
					createLoc("Durăști", "sat"),
					createLoc("Gănești", "sat"),
					createLoc("Gârde", "sat"),
					createLoc("Hodișești", "sat"),
					createLoc("Hudricești", "sat"),
					createLoc("Lipaia", "sat"),
					createLoc("Lunca Largă", "sat"),
					createLoc("Lunca Merilor", "sat"),
					createLoc("Mihăiești", "sat"),
					createLoc("Nămaș", "sat"),
					createLoc("Novăcești", "sat"),
					createLoc("Perjești", "sat"),
					createLoc("Poiana", "sat"),
					createLoc("Poiu", "sat"),
					createLoc("Rătitiș", "sat"),
					createLoc("Runcuri", "sat"),
					createLoc("Sălăgești", "sat"),
					createLoc("Ștefanca", "sat"),
					createLoc("Tolăcești", "sat"),
					createLoc("Tomnatec", "sat"),
					createLoc("Trișorești", "sat"),
					createLoc("Țărănești", "sat"),
					createLoc("Vârși-Rontu", "sat"),
					createLoc("Vârșii Mari", "sat"),
					createLoc("Vârșii Mici", "sat"),							
								  ]),
			createComuna("Blandiana", [
					createLoc("Blandiana", "sat"),
					createLoc("Acmariu", "sat"),
					createLoc("Ibru", "sat"),
					createLoc("Poieni", "sat"),
					createLoc("Răcătău", "sat"),						
								  ]),
			createComuna("Bucerdea Grânoasă", [
					createLoc("Bucerdea Grânoasă", "sat"),
					createLoc("Cornu", "sat"),
					createLoc("Pădure", "sat"),
					createLoc("Pânca", "sat"),						
								  ]),
			createComuna("Bucium", [
					createLoc("Bucium", "sat"),
					createLoc("Anghelești", "sat"),
					createLoc("Bisericani", "sat"),
					createLoc("Bucium-Sat", "sat"),
					createLoc("Cerbu", "sat"),
					createLoc("Ciuculești", "sat"),
					createLoc("Coleșeni", "sat"),
					createLoc("Dogărești", "sat"),
					createLoc("Ferești", "sat"),
					createLoc("Florești", "sat"),
					createLoc("Gura Izbitei", "sat"),
					createLoc("Helești", "sat"),
					createLoc("Izbicioara", "sat"),
					createLoc("Izbita", "sat"),
					createLoc("Jurcuiești", "sat"),
					createLoc("Lupulești", "sat"),	
					createLoc("Măgura", "sat"),
					createLoc("Muntari", "sat"),
					createLoc("Petreni", "sat"),
					createLoc("Poiana", "sat"),
					createLoc("Poieni", "sat"),
					createLoc("Stâlnișoara", "sat"),
					createLoc("Valea Abruzel", "sat"),
					createLoc("Valea Albă", "sat"),
					createLoc("Valea Cerbului", "sat"),
					createLoc("Valea Negrilesii", "sat"),
					createLoc("Valea Poienii", "sat"),
					createLoc("Valea Șesii", "sat"),
					createLoc("Văleni", "sat"),
					createLoc("Vâlcea", "sat"),				
								  ]),
			createComuna("Câlnic", [
					createLoc("Câlnic", "sat"),
					createLoc("Deal", "sat"),						
								  ]),
			createComuna("Cenade", [
					createLoc("Cenade", "sat"),
					createLoc("Capu Dealului", "sat"),
					createLoc("Gorgan", "sat"),					
								  ]),
			createComuna("Cergău", [
					createLoc("Cergău Mare", "sat"),
					createLoc("Cergău Mic", "sat"),
					createLoc("Lupu", "sat"),					
								  ]),	
			createComuna("Ceru-Băcăinți", [
					createLoc("Ceru-Băcăinți", "sat"),
					createLoc("Bolovănești", "sat"),
					createLoc("Bulbuc", "sat"),
					createLoc("Cucuta", "sat"),
					createLoc("Curpeni", "sat"),
					createLoc("Dumbrăvița", "sat"),
					createLoc("Fântânele", "sat"),
					createLoc("Groși", "sat"),
					createLoc("Valea Mare", "sat"),
					createLoc("Viezuri", "sat"),				
								  ]),
			createComuna("Cetatea de Baltă", [
					createLoc("Cetatea de Baltă", "sat"),
					createLoc("Crăciunelu de Sus", "sat"),
					createLoc("Sântămărie", "sat"),	
					createLoc("Tătârlaua", "sat"),						
								  ]),	
			createComuna("Ciugud", [
					createLoc("Ciugud", "sat"),
					createLoc("Drâmbar", "sat"),
					createLoc("Hăpria", "sat"),	
					createLoc("Limba", "sat"),
					createLoc("Șeușa", "sat"),	
					createLoc("Teleac", "sat"),						
								  ]),
			createComuna("Ciuruleasa", [
					createLoc("Ciuruleasa", "sat"),
					createLoc("Bidigești", "sat"),
					createLoc("Bodrești", "sat"),	
					createLoc("Boglești", "sat"),
					createLoc("Buninginea", "sat"),	
					createLoc("Ghedulești", "sat"),
					createLoc("Mătișești", "sat"),
					createLoc("Morărești", "sat"),
					createLoc("Vulcan", "sat"),						
								  ]),
			createComuna("Crăciunelu de Jos", [
					createLoc("Crăciunelu de Jos", "sat"),						
								  ]),	
			createComuna("Cricău", [
					createLoc("Cricău", "sat"),
					createLoc("Craiva", "sat"),
					createLoc("Tibru", "sat"),						
								  ]),
			createComuna("Cut", [
					createLoc("Cut", "sat"),						
								  ]),
			createComuna("Daia Română", [
					createLoc("Daia Română", "sat"),						
								  ]),
			createComuna("Doștat", [
					createLoc("Doștat", "sat"),	
					createLoc("Boz", "sat"),
					createLoc("Dealu Doștatului", "sat"),					
								  ]),
			createComuna("Fărău", [
					createLoc("Fărău", "sat"),	
					createLoc("Heria", "sat"),
					createLoc("Medveș", "sat"),		
					createLoc("Sânbenedic", "sat"),	
					createLoc("Șilea", "sat"),						
								  ]),
			createComuna("Galda de Jos", [
					createLoc("Galda de Jos", "sat"),	
					createLoc("Benic", "sat"),
					createLoc("Cetea", "sat"),		
					createLoc("Galda de Sus", "sat"),	
					createLoc("Lupșeni", "sat"),
					createLoc("Măgura", "sat"),	
					createLoc("Mesentea", "sat"),
					createLoc("Oiejdea", "sat"),		
					createLoc("Poaiana Galdei", "sat"),	
					createLoc("Răicani", "sat"),
					createLoc("Zăgriș", "sat"),						
								  ]),
			createComuna("Gârbova", [
					createLoc("Gârbova", "sat"),	
					createLoc("Cărpiniș", "sat"),
					createLoc("Reciu", "sat"),								
								  ]),
			createComuna("Gârda de Sus", [
					createLoc("Gârda de Sus", "sat"),	
					createLoc("Biharia", "sat"),
					createLoc("Dealu Frumos", "sat"),
					createLoc("Dealu Ordâncușii", "sat"),	
					createLoc("Dobrești", "sat"),
					createLoc("Ghețari", "sat"),
					createLoc("Gârda Seacă", "sat"),	
					createLoc("Hanășești", "sat"),
					createLoc("Huzărești", "sat"),
					createLoc("Izvoarele", "sat"),	
					createLoc("Munună", "sat"),
					createLoc("Ocoale", "sat"),	
					createLoc("Plai", "sat"),	
					createLoc("Pliști", "sat"),
					createLoc("Scoarța", "sat"),
					createLoc("Snide", "sat"),	
					createLoc("Sucești", "sat"),							
								  ]),	
			createComuna("Hopârta", [
					createLoc("Hopârta", "sat"),	
					createLoc("Silivaș", "sat"),
					createLoc("Șpălnaca", "sat"),
					createLoc("Turdaș", "sat"),	
					createLoc("Vama Seacă", "sat"),						
								  ]),
			createComuna("Horea", [
					createLoc("Horea", "sat"),	
					createLoc("Baba", "sat"),
					createLoc("Butești", "sat"),
					createLoc("Dârlești", "sat"),	
					createLoc("Fericet", "sat"),	
					createLoc("Giurgiuț", "sat"),	
					createLoc("Măncești", "sat"),
					createLoc("Mătișești", "sat"),
					createLoc("Niculești", "sat"),	
					createLoc("Pătrușești", "sat"),	
					createLoc("Petreasa", "sat"),	
					createLoc("Preluca", "sat"),
					createLoc("Teiu", "sat"),
					createLoc("Trifești", "sat"),	
					createLoc("Zânzești", "sat"),						
								  ]),
			createComuna("Ighiu", [
					createLoc("Ighiu", "sat"),	
					createLoc("Bucerdea Vinoasă", "sat"),
					createLoc("Ighiel", "sat"),
					createLoc("Șard", "sat"),	
					createLoc("Țelna", "sat"),							
								  ]),	
			createComuna("Întregalde", [
					createLoc("Întregalde", "sat"),	
					createLoc("Dealu Geoagiului", "sat"),
					createLoc("Ghioncani", "sat"),
					createLoc("Iliești", "sat"),	
					createLoc("Ivăniș", "sat"),	
					createLoc("Mărinești", "sat"),	
					createLoc("Modolești", "sat"),
					createLoc("Necrilești", "sat"),
					createLoc("Popești", "sat"),	
					createLoc("Sfârcea", "sat"),
					createLoc("Tecșești", "sat"),					
								  ]),
			createComuna("Jidvei", [
					createLoc("Jidvei", "sat"),	
					createLoc("Bălcaciu", "sat"),
					createLoc("Căpâlna de Jos", "sat"),
					createLoc("Feisa", "sat"),	
					createLoc("Veseuș", "sat"),						
								  ]),
			createComuna("Livezile", [
					createLoc("Livezile", "sat"),	
					createLoc("Izvoarele", "sat"),
					createLoc("Poiana Aiudului", "sat"),
					createLoc("Vălișoara", "sat"),							
								  ]),
			createComuna("Lopadea Nouă", [
					createLoc("Lopadea Nouă", "sat"),	
					createLoc("Asinip", "sat"),
					createLoc("Beța", "sat"),
					createLoc("Băgău", "sat"),	
					createLoc("Cicârd", "sat"),	
					createLoc("Ciuguzel", "sat"),
					createLoc("Ocnișoara", "sat"),
					createLoc("Odverem", "sat"),						
								  ]),	
			createComuna("Lunca Mureșului", [
					createLoc("Lunca Mureșului", "sat"),	
					createLoc("Gura Arieșului", "sat"),						
								  ]),
			createComuna("Lupșa", [
					createLoc("Lupșa", "sat"),	
					createLoc("Bârdești", "sat"),
					createLoc("Bârzan", "sat"),	
					createLoc("Curmătură", "sat"),
					createLoc("După Deal", "sat"),
					createLoc("Geamăna", "sat"),	
					createLoc("Hădărău", "sat"),
					createLoc("Holobani", "sat"),	
					createLoc("Lazuri", "sat"),
					createLoc("Lunca", "sat"),		
					createLoc("Mănăstire", "sat"),	
					createLoc("Mărgaia", "sat"),
					createLoc("Mușca", "sat"),	
					createLoc("Pițiga", "sat"),
					createLoc("Pârâu-Cărbunări", "sat"),
					createLoc("Poșogani", "sat"),	
					createLoc("Șasa", "sat"),
					createLoc("Trifești", "sat"),	
					createLoc("Valea Holhorii", "sat"),
					createLoc("Valea Lupșii", "sat"),	
					createLoc("Valea Șesii", "sat"),
					createLoc("Văi", "sat"),	
					createLoc("Vința", "sat"),						
								  ]),
			createComuna("Meteș", [
					createLoc("Meteș", "sat"),	
					createLoc("Ampoița", "sat"),
					createLoc("Isca", "sat"),	
					createLoc("Lunca Ampoiței", "sat"),
					createLoc("Lunca Meteșului", "sat"),
					createLoc("Pădurea", "sat"),	
					createLoc("Poiana Ampoiului", "sat"),
					createLoc("Poiana Ursului", "sat"),	
					createLoc("Presaca Ampoiului", "sat"),
					createLoc("Remetea", "sat"),		
					createLoc("Tăuți", "sat"),	
					createLoc("Văleni", "sat"),					
								  ]),
			createComuna("Mihalț", [
					createLoc("Mihalț", "sat"),	
					createLoc("Cistei", "sat"),
					createLoc("Obreja", "sat"),	
					createLoc("Zărieș", "sat"),				
								  ]),
			createComuna("Mirăslău", [
					createLoc("Mirăslău", "sat"),	
					createLoc("Cicău", "sat"),
					createLoc("Decea", "sat"),	
					createLoc("Lopadea Veche", "sat"),
					createLoc("Ormeniș", "sat"),	
					createLoc("Rachiș", "sat"),				
								  ]),	
			createComuna("Mogoș", [
					createLoc("Mogoș", "sat"),	
					createLoc("Bărbești", "sat"),
					createLoc("Bârlești", "sat"),	
					createLoc("Bârlești-Cătun", "sat"),
					createLoc("Bârzogani", "sat"),	
					createLoc("Bocești", "sat"),
					createLoc("Bogdănești", "sat"),	
					createLoc("Butești", "sat"),
					createLoc("Cojocani", "sat"),	
					createLoc("Cristești", "sat"),
					createLoc("Mămăligani", "sat"),	
					createLoc("Negrești", "sat"),	
					createLoc("Oncești", "sat"),	
					createLoc("Poienile-Mogoș", "sat"),
					createLoc("Tomești", "sat"),	
					createLoc("Valea Barnii", "sat"),
					createLoc("Valea Bârluțești", "sat"),	
					createLoc("Valea Cocești", "sat"),
					createLoc("Valea Giogești", "sat"),	
					createLoc("Valea Mlacii", "sat"),
					createLoc("Valea Țupilor", "sat"),							
								  ]),
			createComuna("Noșlac", [
					createLoc("Noșlac", "sat"),	
					createLoc("Căptălan", "sat"),
					createLoc("Copand", "sat"),	
					createLoc("Găbud", "sat"),
					createLoc("Stâna de Mureș", "sat"),	
					createLoc("Valea Ciuciului", "sat"),						
								  ]),
			createComuna("Ocoliș", [
					createLoc("Ocoliș", "sat"),	
					createLoc("Lunca Largă", "sat"),
					createLoc("Runc", "sat"),	
					createLoc("Vidolm", "sat"),						
								  ]),	
			createComuna("Ohaba", [
					createLoc("Ohaba", "sat"),	
					createLoc("Colibi", "sat"),
					createLoc("Măghierat", "sat"),	
					createLoc("Secășel", "sat"),						
								  ]),
			createComuna("Pianu", [
					createLoc("Pianu de Sus", "sat"),	
					createLoc("Pianu de Jos", "sat"),
					createLoc("Plaiuri", "sat"),	
					createLoc("Purcăreți", "sat"),
					createLoc("Strungari", "sat"),						
								  ]),	
			createComuna("Poiana Vadului", [
					createLoc("Poiana Vadului", "sat"),	
					createLoc("Costești", "sat"),
					createLoc("Duduieni", "sat"),	
					createLoc("Făgetu de Jos", "sat"),
					createLoc("Făgetu de Sus", "sat"),	
					createLoc("Hănășești", "sat"),	
					createLoc("Lupăiești", "sat"),
					createLoc("Morcănești", "sat"),	
					createLoc("Păștești", "sat"),
					createLoc("Petelei", "sat"),
					createLoc("Stănești", "sat"),					
								  ]),									  
			createComuna("Ponor", [
					createLoc("Ponor", "sat"),	
					createLoc("După Deal", "sat"),
					createLoc("Geogel", "sat"),	
					createLoc("Măcărești", "sat"),
					createLoc("Valea Bucurului", "sat"),	
					createLoc("Vale în Jos", "sat"),						
								  ]),	
			createComuna("Poșaga", [
					createLoc("Poșaga", "sat"),	
					createLoc("Poșaga de Jos", "sat"),
					createLoc("Corțești", "sat"),	
					createLoc("Incești", "sat"),
					createLoc("Lunca", "sat"),	
					createLoc("Orăști", "sat"),	
					createLoc("Poșaga de Sus", "sat"),	
					createLoc("Săgagea", "sat"),					
								  ]),		
			createComuna("Rădești", [
					createLoc("Rădești", "sat"),	
					createLoc("Leorinț", "sat"),
					createLoc("Meșcreac", "sat"),	
					createLoc("Șoimuș", "sat"),				
								  ]),								  
];
?>