<?php
$orase=[
            createOras("ABRUD", [
                createLoc("ABRUD", "oras", createAdresaCompleta("orasul ABRUD, orasul ABRUD, judetul ALBA, România", "orasul ABRUD, orasul ABRUD, judetul ALBA, Romania")),
                createLoc("Abrud-Sat", "sat", createAdresaCompleta("sat Abrud-Sat, orasul ABRUD, judetul ALBA, România", "sat Abrud-Sat, orasul ABRUD, judetul ALBA, Romania")),
                createLoc("Gura Cornei", "sat", createAdresaCompleta("sat Gura Cornei, orasul ABRUD, judetul ALBA, România", "sat Gura Cornei, orasul ABRUD, judetul ALBA, Romania")),
                createLoc("Soharu", "sat", createAdresaCompleta("sat Soharu, orasul ABRUD, judetul ALBA, România", "sat Soharu, orasul ABRUD, judetul ALBA, Romania")),
            ], createAdresaCompleta("orasul ABRUD, judetul ALBA, România", "orasul ABRUD, judetul ALBA, Romania")),
            createOras("BAIA DE ARIEȘ", [
                createLoc("BAIA DE ARIEȘ", "oras", [
                    createLoc("Brăzești", "sat", createAdresaCompleta("sat Brăzești, orasul BAIA DE ARIEȘ, judetul ALBA, România", "sat Brazesti, orasul BAIA DE ARIES, judetul ALBA, Romania")),
                    createLoc("Cioara de Sus", "sat", createAdresaCompleta("sat Cioara de Sus, orasul BAIA DE ARIEȘ, judetul ALBA, România", "sat Cioara de Sus, orasul BAIA DE ARIES, judetul ALBA, Romania")),
                    createLoc("Muncelu", "sat", createAdresaCompleta("sat Muncelu, orasul BAIA DE ARIEȘ, judetul ALBA, România", "sat Muncelu, orasul BAIA DE ARIES, judetul ALBA, Romania")),
                    createLoc("Sartăș", "sat", createAdresaCompleta("sat Sartăș, orasul BAIA DE ARIEȘ, judetul ALBA, România", "sat Sartas, orasul BAIA DE ARIES, judetul ALBA, Romania")),
                    createLoc("Simulești", "sat", createAdresaCompleta("sat Simulești, orasul BAIA DE ARIEȘ, judetul ALBA, România", "sat Simulesti, orasul BAIA DE ARIES, judetul ALBA, Romania")),
                ], createAdresaCompleta("orasul BAIA DE ARIEȘ, judetul ALBA, România", "orasul BAIA DE ARIES, judetul ALBA, Romania")),
            ], createAdresaCompleta("orasul BAIA DE ARIEȘ, judetul ALBA, România", "orasul BAIA DE ARIES, judetul ALBA, Romania")),
            createOras("CÂMPENI", [
                createLoc("CÂMPENI", "oras", createAdresaCompleta("orasul CÂMPENI, judetul ALBA, România", "orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Boncești", "sat", createAdresaCompleta("sat Boncești, orasul CÂMPENI, judetul ALBA, România", "sat Boncesti, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Borlești", "sat", createAdresaCompleta("sat Borlești, orasul CÂMPENI, judetul ALBA, România", "sat Borlesti, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Botești", "sat", createAdresaCompleta("sat Botești, orasul CÂMPENI, judetul ALBA, România", "sat Botesti, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Certege", "sat", createAdresaCompleta("sat Certege, orasul CÂMPENI, judetul ALBA, România", "sat Certege, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Coasta Vâscului", "sat", createAdresaCompleta("sat Coasta Vâscului, orasul CÂMPENI, judetul ALBA, România", "sat Coasta Vascului, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Dănduț", "sat", createAdresaCompleta("sat Dănduț, orasul CÂMPENI, judetul ALBA, România", "sat Dandut, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Dealu Bistrii", "sat", createAdresaCompleta("sat Dealu Bistrii, orasul CÂMPENI, judetul ALBA, România", "sat Dealu Bistrii, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Dealu Capsei", "sat", createAdresaCompleta("sat Dealu Capsei, orasul CÂMPENI, judetul ALBA, România", "sat Dealu Capsei, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Dric", "sat", createAdresaCompleta("sat Dric, orasul CÂMPENI, judetul ALBA, România", "sat Dric, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Fața Abrudului", "sat", createAdresaCompleta("sat Fața Abrudului, orasul CÂMPENI, judetul ALBA, România", "sat Fata Abrudului, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Florești", "sat", createAdresaCompleta("sat Florești, orasul CÂMPENI, judetul ALBA, România", "sat Floresti, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Furduiești", "sat", createAdresaCompleta("sat Furduiești, orasul CÂMPENI, judetul ALBA, România", "sat Furduiesti, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Mihoești", "sat", createAdresaCompleta("sat Mihoești, orasul CÂMPENI, judetul ALBA, România", "sat Mihoesti, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Motorăști", "sat", createAdresaCompleta("sat Motorăști, orasul CÂMPENI, judetul ALBA, România", "sat Motorasti, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Peste Valea Bistrii", "sat", createAdresaCompleta("sat Peste Valea Bistrii, orasul CÂMPENI, judetul ALBA, România", "sat Peste Valea Bistrii, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Poduri", "sat", createAdresaCompleta("sat Poduri, orasul CÂMPENI, judetul ALBA, România", "sat Poduri, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Sorlița", "sat", createAdresaCompleta("sat Sorlița, orasul CÂMPENI, judetul ALBA, România", "sat Sorlita, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Tomușești", "sat", createAdresaCompleta("sat Tomușești, orasul CÂMPENI, judetul ALBA, România", "sat Tomusesti, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Valea Bistrii", "sat", createAdresaCompleta("sat Valea Bistrii, orasul CÂMPENI, judetul ALBA, România", "sat Valea Bistrii, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Valea Caselor", "sat", createAdresaCompleta("sat Valea Caselor, orasul CÂMPENI, judetul ALBA, România", "sat Valea Caselor, orasul CAMPENI, judetul ALBA, Romania")),
                createLoc("Vârși", "sat", createAdresaCompleta("sat Vârși, orasul CÂMPENI, judetul ALBA, România", "sat Varsi, orasul CAMPENI, judetul ALBA, Romania")),
            ], createAdresaCompleta("orasul CÂMPENI, judetul ALBA, România", "orasul CAMPENI, judetul ALBA, Romania")),
            createOras("CUGIR", [
                createLoc("CUGIR", "oras", createAdresaCompleta("orasul CUGIR, judetul ALBA, România", "orasul CUGIR, judetul ALBA, Romania")),
                createLoc("Bocșitura", "sat", createAdresaCompleta("sat Bocșitura, orasul CUGIR, judetul ALBA, România", "sat Bocsitura, orasul CUGIR, judetul ALBA, Romania")),
                createLoc("Bucuru", "sat", createAdresaCompleta("sat Bucuru, orasul CUGIR, judetul ALBA, România", "sat Bucuru, orasul CUGIR, judetul ALBA, Romania")),
                createLoc("Călene", "sat", createAdresaCompleta("sat Călene, orasul CUGIR, judetul ALBA, România", "sat Calene, orasul CUGIR, judetul ALBA, Romania")),
                createLoc("Fețeni", "sat", createAdresaCompleta("sat Fețeni, orasul CUGIR, judetul ALBA, România", "sat Feteni, orasul CUGIR, judetul ALBA, Romania")),
                createLoc("Goașele", "sat", createAdresaCompleta("sat Goașele, orasul CUGIR, judetul ALBA, România", "sat Goasele, orasul CUGIR, judetul ALBA, Romania")),
                createLoc("Mugești", "sat", createAdresaCompleta("sat Mugești, orasul CUGIR, judetul ALBA, România", "sat Mugesti, orasul CUGIR, judetul ALBA, Romania")),
                createLoc("Vinerea", "sat", createAdresaCompleta("sat Vinerea, orasul CUGIR, judetul ALBA, România", "sat Vinerea, orasul CUGIR, judetul ALBA, Romania")),
            ], createAdresaCompleta("orasul CUGIR, judetul ALBA, România", "orasul CUGIR, judetul ALBA, Romania")),
            createOras("OCNA MUREȘ", [
                createLoc("OCNA MUREȘ", "oras", [
                    createLoc("Cisteiu de Mureș", "sat", createAdresaCompleta("sat Cisteiu de Mureș, orasul OCNA MUREȘ, judetul ALBA, România", "sat Cisteiu de Mures, orasul OCNA MURES, judetul ALBA, Romania")),
                    createLoc("Micoșlaca", "sat", createAdresaCompleta("sat Micoșlaca, orasul OCNA MUREȘ, judetul ALBA, România", "sat Micoslaca, orasul OCNA MURES, judetul ALBA, Romania")),
                    createLoc("Războieni-Cetate", "sat", createAdresaCompleta("sat Războieni-Cetate, orasul OCNA MUREȘ, judetul ALBA, România", "sat Razboieni-Cetate, orasul OCNA MURES, judetul ALBA, Romania")),
                ], createAdresaCompleta("orasul OCNA MUREȘ, judetul ALBA, România", "orasul OCNA MURES, judetul ALBA, Romania")),
                createLoc("Uioara de Jos", "sat", createAdresaCompleta("sat Uioara de Jos, orasul OCNA MUREȘ, judetul ALBA, România", "sat Uioara de Jos, orasul OCNA MURES, judetul ALBA, Romania")),
                createLoc("Uioara de Sus", "sat", createAdresaCompleta("sat Uioara de Sus, orasul OCNA MUREȘ, judetul ALBA, România", "sat Uioara de Sus, orasul OCNA MURES, judetul ALBA, Romania")),
            ], createAdresaCompleta("orasul OCNA MUREȘ, judetul ALBA, România", "orasul OCNA MURES, judetul ALBA, Romania")),
            createOras("TEIUȘ", [
                createLoc("TEIUȘ", "oras", [
                    createLoc("Beldiu", "sat", createAdresaCompleta("sat Beldiu, orasul TEIUȘ, judetul ALBA, România", "sat Beldiu, orasul TEIUS, judetul ALBA, Romania")),
                    createLoc("Căpud", "sat", createAdresaCompleta("sat Căpud, orasul TEIUȘ, judetul ALBA, România", "sat Capud, orasul TEIUS, judetul ALBA, Romania")),
                    createLoc("Coșlariu Nou", "sat", createAdresaCompleta("sat Coșlariu Nou, orasul TEIUȘ, judetul ALBA, România", "sat Coslariu Nou, orasul TEIUS, judetul ALBA, Romania")),
                    createLoc("Pețelca", "sat", createAdresaCompleta("sat Pețelca, orasul TEIUȘ, judetul ALBA, România", "sat Petelca, orasul TEIUS, judetul ALBA, Romania")),
                ], createAdresaCompleta("orasul TEIUȘ, judetul ALBA, România", "orasul TEIUS, judetul ALBA, Romania")),
            ], createAdresaCompleta("orasul TEIUȘ, judetul ALBA, România", "orasul TEIUS, judetul ALBA, Romania")),
            createOras("ZLATNA", [
                createLoc("ZLATNA", "oras", [
                    createLoc("Botești", "sat", createAdresaCompleta("sat Botești, orasul ZLATNA, judetul ALBA, România", "sat Botesti, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Budeni", "sat", createAdresaCompleta("sat Budeni, orasul ZLATNA, judetul ALBA, România", "sat Budeni, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Dealu Roatei", "sat", createAdresaCompleta("sat Dealu Roatei, orasul ZLATNA, judetul ALBA, România", "sat Dealu Roatei, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Dobrot", "sat", createAdresaCompleta("sat Dobrot, orasul ZLATNA, judetul ALBA, România", "sat Dobrot, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, orasul ZLATNA, judetul ALBA, România", "sat Dumbrava, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Feneș", "sat", createAdresaCompleta("sat Feneș, orasul ZLATNA, judetul ALBA, România", "sat Fenes, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Galați", "sat", createAdresaCompleta("sat Galați, orasul ZLATNA, judetul ALBA, România", "sat Galati, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Izvoru Ampoiului", "sat", createAdresaCompleta("sat Izvoru Ampoiului, orasul ZLATNA, judetul ALBA, România", "sat Izvoru Ampoiului, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Pătrângeni", "sat", createAdresaCompleta("sat Pătrângeni, orasul ZLATNA, judetul ALBA, România", "sat Patrangeni, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Pirita", "sat", createAdresaCompleta("sat Pirita, orasul ZLATNA, judetul ALBA, România", "sat Pirita, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Pârău Gruiului", "sat", createAdresaCompleta("sat Pârău Gruiului, orasul ZLATNA, judetul ALBA, România", "sat Parau Gruiului, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Podu lui Paul", "sat", createAdresaCompleta("sat Podu lui Paul, orasul ZLATNA, judetul ALBA, România", "sat Podu lui Paul, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Runc", "sat", createAdresaCompleta("sat Runc, orasul ZLATNA, judetul ALBA, România", "sat Runc, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Ruși", "sat", createAdresaCompleta("sat Ruși, orasul ZLATNA, judetul ALBA, România", "sat Rusi, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Suseni", "sat", createAdresaCompleta("sat Suseni, orasul ZLATNA, judetul ALBA, România", "sat Suseni, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Trâmpoiele", "sat", createAdresaCompleta("sat Trâmpoiele, orasul ZLATNA, judetul ALBA, România", "sat Trampoiele, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Valea Mică", "sat", createAdresaCompleta("sat Valea Mică, orasul ZLATNA, judetul ALBA, România", "sat Valea Mica, orasul ZLATNA, judetul ALBA, Romania")),
                    createLoc("Vâltori", "sat", createAdresaCompleta("sat Vâltori, orasul ZLATNA, judetul ALBA, România", "sat Valtori, orasul ZLATNA, judetul ALBA, Romania")),
                ], createAdresaCompleta("orasul ZLATNA, judetul ALBA, România", "orasul ZLATNA, judetul ALBA, Romania")),
            ], createAdresaCompleta("orasul ZLATNA, judetul ALBA, România", "orasul ZLATNA, judetul ALBA, Romania")),
            
];

?>
