<?php
$orase=[
            createOras("ABRUD", [
                createLoc("ABRUD", "oras", createAdresaCompleta("orasul ABRUD, orasul ABRUD, judetul ALBA, România")),
                createLoc("Abrud-Sat", "sat", createAdresaCompleta("sat Abrud-Sat, orasul ABRUD, judetul ALBA, România")),
                createLoc("Gura Cornei", "sat", createAdresaCompleta("sat Gura Cornei, orasul ABRUD, judetul ALBA, România")),
                createLoc("Soharu", "sat", createAdresaCompleta("sat Soharu, orasul ABRUD, judetul ALBA, România")),
            ], createAdresaCompleta("orasul ABRUD, judetul ALBA, România")),
            createOras("BAIA DE ARIEȘ", [
                createLoc("BAIA DE ARIEȘ", "oras", [
                    createLoc("Brăzești", "sat", createAdresaCompleta("sat Brăzești, orasul BAIA DE ARIEȘ, judetul ALBA, România")),
                    createLoc("Cioara de Sus", "sat", createAdresaCompleta("sat Cioara de Sus, orasul BAIA DE ARIEȘ, judetul ALBA, România")),
                    createLoc("Muncelu", "sat", createAdresaCompleta("sat Muncelu, orasul BAIA DE ARIEȘ, judetul ALBA, România")),
                    createLoc("Sartăș", "sat", createAdresaCompleta("sat Sartăș, orasul BAIA DE ARIEȘ, judetul ALBA, România")),
                    createLoc("Simulești", "sat", createAdresaCompleta("sat Simulești, orasul BAIA DE ARIEȘ, judetul ALBA, România")),
                ], createAdresaCompleta("orasul BAIA DE ARIEȘ, judetul ALBA, România")),
            ], createAdresaCompleta("orasul BAIA DE ARIEȘ, judetul ALBA, România")),
            createOras("CÂMPENI", [
                createLoc("CÂMPENI", "oras", createAdresaCompleta("orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Boncești", "sat", createAdresaCompleta("sat Boncești, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Borlești", "sat", createAdresaCompleta("sat Borlești, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Botești", "sat", createAdresaCompleta("sat Botești, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Certege", "sat", createAdresaCompleta("sat Certege, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Coasta Vâscului", "sat", createAdresaCompleta("sat Coasta Vâscului, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Dănduț", "sat", createAdresaCompleta("sat Dănduț, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Dealu Bistrii", "sat", createAdresaCompleta("sat Dealu Bistrii, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Dealu Capsei", "sat", createAdresaCompleta("sat Dealu Capsei, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Dric", "sat", createAdresaCompleta("sat Dric, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Fața Abrudului", "sat", createAdresaCompleta("sat Fața Abrudului, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Florești", "sat", createAdresaCompleta("sat Florești, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Furduiești", "sat", createAdresaCompleta("sat Furduiești, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Mihoești", "sat", createAdresaCompleta("sat Mihoești, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Motorăști", "sat", createAdresaCompleta("sat Motorăști, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Peste Valea Bistrii", "sat", createAdresaCompleta("sat Peste Valea Bistrii, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Poduri", "sat", createAdresaCompleta("sat Poduri, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Sorlița", "sat", createAdresaCompleta("sat Sorlița, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Tomușești", "sat", createAdresaCompleta("sat Tomușești, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Valea Bistrii", "sat", createAdresaCompleta("sat Valea Bistrii, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Valea Caselor", "sat", createAdresaCompleta("sat Valea Caselor, orasul CÂMPENI, judetul ALBA, România")),
                createLoc("Vârși", "sat", createAdresaCompleta("sat Vârși, orasul CÂMPENI, judetul ALBA, România")),
            ], createAdresaCompleta("orasul CÂMPENI, judetul ALBA, România")),
            createOras("CUGIR", [
                createLoc("CUGIR", "oras", createAdresaCompleta("orasul CUGIR, judetul ALBA, România")),
                createLoc("Bocșitura", "sat", createAdresaCompleta("sat Bocșitura, orasul CUGIR, judetul ALBA, România")),
                createLoc("Bucuru", "sat", createAdresaCompleta("sat Bucuru, orasul CUGIR, judetul ALBA, România")),
                createLoc("Călene", "sat", createAdresaCompleta("sat Călene, orasul CUGIR, judetul ALBA, România")),
                createLoc("Fețeni", "sat", createAdresaCompleta("sat Fețeni, orasul CUGIR, judetul ALBA, România")),
                createLoc("Goașele", "sat", createAdresaCompleta("sat Goașele, orasul CUGIR, judetul ALBA, România")),
                createLoc("Mugești", "sat", createAdresaCompleta("sat Mugești, orasul CUGIR, judetul ALBA, România")),
                createLoc("Vinerea", "sat", createAdresaCompleta("sat Vinerea, orasul CUGIR, judetul ALBA, România")),
            ], createAdresaCompleta("orasul CUGIR, judetul ALBA, România")),
            createOras("OCNA MUREȘ", [
                createLoc("OCNA MUREȘ", "oras", [
                    createLoc("Cisteiu de Mureș", "sat", createAdresaCompleta("sat Cisteiu de Mureș, orasul OCNA MUREȘ, judetul ALBA, România")),
                    createLoc("Micoșlaca", "sat", createAdresaCompleta("sat Micoșlaca, orasul OCNA MUREȘ, judetul ALBA, România")),
                    createLoc("Războieni-Cetate", "sat", createAdresaCompleta("sat Războieni-Cetate, orasul OCNA MUREȘ, judetul ALBA, România")),
                ], createAdresaCompleta("orasul OCNA MUREȘ, judetul ALBA, România")),
                createLoc("Uioara de Jos", "sat", createAdresaCompleta("sat Uioara de Jos, orasul OCNA MUREȘ, judetul ALBA, România")),
                createLoc("Uioara de Sus", "sat", createAdresaCompleta("sat Uioara de Sus, orasul OCNA MUREȘ, judetul ALBA, România")),
            ], createAdresaCompleta("orasul OCNA MUREȘ, judetul ALBA, România")),
            createOras("TEIUȘ", [
                createLoc("TEIUȘ", "oras", [
                    createLoc("Beldiu", "sat", createAdresaCompleta("sat Beldiu, orasul TEIUȘ, judetul ALBA, România")),
                    createLoc("Căpud", "sat", createAdresaCompleta("sat Căpud, orasul TEIUȘ, judetul ALBA, România")),
                    createLoc("Coșlariu Nou", "sat", createAdresaCompleta("sat Coșlariu Nou, orasul TEIUȘ, judetul ALBA, România")),
                    createLoc("Pețelca", "sat", createAdresaCompleta("sat Pețelca, orasul TEIUȘ, judetul ALBA, România")),
                ], createAdresaCompleta("orasul TEIUȘ, judetul ALBA, România")),
            ], createAdresaCompleta("orasul TEIUȘ, judetul ALBA, România")),
            createOras("ZLATNA", [
                createLoc("ZLATNA", "oras", [
                    createLoc("Botești", "sat", createAdresaCompleta("sat Botești, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Budeni", "sat", createAdresaCompleta("sat Budeni, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Dealu Roatei", "sat", createAdresaCompleta("sat Dealu Roatei, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Dobrot", "sat", createAdresaCompleta("sat Dobrot, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Feneș", "sat", createAdresaCompleta("sat Feneș, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Galați", "sat", createAdresaCompleta("sat Galați, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Izvoru Ampoiului", "sat", createAdresaCompleta("sat Izvoru Ampoiului, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Pătrângeni", "sat", createAdresaCompleta("sat Pătrângeni, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Pirita", "sat", createAdresaCompleta("sat Pirita, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Pârău Gruiului", "sat", createAdresaCompleta("sat Pârău Gruiului, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Podu lui Paul", "sat", createAdresaCompleta("sat Podu lui Paul, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Runc", "sat", createAdresaCompleta("sat Runc, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Ruși", "sat", createAdresaCompleta("sat Ruși, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Suseni", "sat", createAdresaCompleta("sat Suseni, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Trâmpoiele", "sat", createAdresaCompleta("sat Trâmpoiele, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Valea Mică", "sat", createAdresaCompleta("sat Valea Mică, orasul ZLATNA, judetul ALBA, România")),
                    createLoc("Vâltori", "sat", createAdresaCompleta("sat Vâltori, orasul ZLATNA, judetul ALBA, România")),
                ], createAdresaCompleta("orasul ZLATNA, judetul ALBA, România")),
            ], createAdresaCompleta("orasul ZLATNA, judetul ALBA, România")),
            
];

?>
