<?php
$comune =[
createComuna("Abram", [
    createLoc("Abram", "sat", createAdresaCompleta("sat Abram, comuna Abram, judetul BIHOR, România", "sat Abram, comuna Abram, judetul BIHOR, Romania")),
    createLoc("Cohani", "sat", createAdresaCompleta("sat Cohani, comuna Abram, judetul BIHOR, România", "sat Cohani, comuna Abram, judetul BIHOR, Romania")),
    createLoc("Dijir", "sat", createAdresaCompleta("sat Dijir, comuna Abram, judetul BIHOR, România", "sat Dijir, comuna Abram, judetul BIHOR, Romania")),
    createLoc("Iteu", "sat", createAdresaCompleta("sat Iteu, comuna Abram, judetul BIHOR, România", "sat Iteu, comuna Abram, judetul BIHOR, Romania")),
    createLoc("Iteu Nou", "sat", createAdresaCompleta("sat Iteu Nou, comuna Abram, judetul BIHOR, România", "sat Iteu Nou, comuna Abram, judetul BIHOR, Romania")),
    createLoc("Margine", "sat", createAdresaCompleta("sat Margine, comuna Abram, judetul BIHOR, România", "sat Margine, comuna Abram, judetul BIHOR, Romania")),
    createLoc("Satu Barbă", "sat", createAdresaCompleta("sat Satu Barbă, comuna Abram, judetul BIHOR, România", "sat Satu Barba, comuna Abram, judetul BIHOR, Romania")),
    createLoc("Suiug", "sat", createAdresaCompleta("sat Suiug, comuna Abram, judetul BIHOR, România", "sat Suiug, comuna Abram, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Abram, judetul BIHOR, România", "comuna Abram, judetul BIHOR, Romania")),

createComuna("Aștileu", [
    createLoc("Aștileu", "sat", createAdresaCompleta("sat Aștileu, comuna Aștileu, judetul BIHOR, România", "sat Astileu, comuna Astileu, judetul BIHOR, Romania")),
    createLoc("Călățea", "sat", createAdresaCompleta("sat Călățea, comuna Aștileu, judetul BIHOR, România", "sat Calatea, comuna Astileu, judetul BIHOR, Romania")),
    createLoc("Chistag", "sat", createAdresaCompleta("sat Chistag, comuna Aștileu, judetul BIHOR, România", "sat Chistag, comuna Astileu, judetul BIHOR, Romania")),
    createLoc("Peștere", "sat", createAdresaCompleta("sat Peștere, comuna Aștileu, judetul BIHOR, România", "sat Pestere, comuna Astileu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Aștileu, judetul BIHOR, România", "comuna Astileu, judetul BIHOR, Romania")),
createComuna("Aușeu", [
    createLoc("Aușeu", "sat", createAdresaCompleta("sat Aușeu, comuna Aușeu, judetul BIHOR, România", "sat Auseu, comuna Auseu, judetul BIHOR, Romania")),
    createLoc("Cacuciu Vechi", "sat", createAdresaCompleta("sat Cacuciu Vechi, comuna Aușeu, judetul BIHOR, România", "sat Cacuciu Vechi, comuna Auseu, judetul BIHOR, Romania")),
    createLoc("Codrișoru", "sat", createAdresaCompleta("sat Codrișoru, comuna Aușeu, judetul BIHOR, România", "sat Codrisoru, comuna Auseu, judetul BIHOR, Romania")),
    createLoc("Gheghie", "sat", createAdresaCompleta("sat Gheghie, comuna Aușeu, judetul BIHOR, România", "sat Gheghie, comuna Auseu, judetul BIHOR, Romania")),
    createLoc("Groși", "sat", createAdresaCompleta("sat Groși, comuna Aușeu, judetul BIHOR, România", "sat Grosi, comuna Auseu, judetul BIHOR, Romania")),
    createLoc("Luncșoara", "sat", createAdresaCompleta("sat Luncșoara, comuna Aușeu, judetul BIHOR, România", "sat Luncsoara, comuna Auseu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Aușeu, judetul BIHOR, România", "comuna Auseu, judetul BIHOR, Romania")),
createComuna("Avram Iancu", [
    createLoc("Avram Iancu", "sat", createAdresaCompleta("sat Avram Iancu, comuna Avram Iancu, judetul BIHOR, România", "sat Avram Iancu, comuna Avram Iancu, judetul BIHOR, Romania")),
    createLoc("Ant", "sat", createAdresaCompleta("sat Ant, comuna Avram Iancu, judetul BIHOR, România", "sat Ant, comuna Avram Iancu, judetul BIHOR, Romania")),
    createLoc("Tămașda", "sat", createAdresaCompleta("sat Tămașda, comuna Avram Iancu, judetul BIHOR, România", "sat Tamasda, comuna Avram Iancu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Avram Iancu, judetul BIHOR, România", "comuna Avram Iancu, judetul BIHOR, Romania")),
createComuna("Balc", [
    createLoc("Balc", "sat", createAdresaCompleta("sat Balc, comuna Balc, judetul BIHOR, România", "sat Balc, comuna Balc, judetul BIHOR, Romania")),
    createLoc("Almașu Mare", "sat", createAdresaCompleta("sat Almașu Mare, comuna Balc, judetul BIHOR, România", "sat Almasu Mare, comuna Balc, judetul BIHOR, Romania")),
    createLoc("Almașu Mic", "sat", createAdresaCompleta("sat Almașu Mic, comuna Balc, judetul BIHOR, România", "sat Almasu Mic, comuna Balc, judetul BIHOR, Romania")),
    createLoc("Ghida", "sat", createAdresaCompleta("sat Ghida, comuna Balc, judetul BIHOR, România", "sat Ghida, comuna Balc, judetul BIHOR, Romania")),
    createLoc("Săldăbagiu de Barcău", "sat", createAdresaCompleta("sat Săldăbagiu de Barcău, comuna Balc, judetul BIHOR, România", "sat Saldabagiu de Barcau, comuna Balc, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Balc, judetul BIHOR, România", "comuna Balc, judetul BIHOR, Romania")),
createComuna("Batăr", [
    createLoc("Batăr", "sat", createAdresaCompleta("sat Batăr, comuna Batăr, judetul BIHOR, România", "sat Batar, comuna Batar, judetul BIHOR, Romania")),
    createLoc("Arpășel", "sat", createAdresaCompleta("sat Arpășel, comuna Batăr, judetul BIHOR, România", "sat Arpasel, comuna Batar, judetul BIHOR, Romania")),
    createLoc("Talpoș", "sat", createAdresaCompleta("sat Talpoș, comuna Batăr, judetul BIHOR, România", "sat Talpos, comuna Batar, judetul BIHOR, Romania")),
    createLoc("Tăut", "sat", createAdresaCompleta("sat Tăut, comuna Batăr, judetul BIHOR, România", "sat Taut, comuna Batar, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Batăr, judetul BIHOR, România", "comuna Batar, judetul BIHOR, Romania")),
createComuna("Biharia", [
    createLoc("Biharia", "sat", createAdresaCompleta("sat Biharia, comuna Biharia, judetul BIHOR, România", "sat Biharia, comuna Biharia, judetul BIHOR, Romania")),
    createLoc("Cauaceu", "sat", createAdresaCompleta("sat Cauaceu, comuna Biharia, judetul BIHOR, România", "sat Cauaceu, comuna Biharia, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Biharia, judetul BIHOR, România", "comuna Biharia, judetul BIHOR, Romania")),
createComuna("Boianu Mare", [
    createLoc("Boianu Mare", "sat", createAdresaCompleta("sat Boianu Mare, comuna Boianu Mare, judetul BIHOR, România", "sat Boianu Mare, comuna Boianu Mare, judetul BIHOR, Romania")),
    createLoc("Corboaia", "sat", createAdresaCompleta("sat Corboaia, comuna Boianu Mare, judetul BIHOR, România", "sat Corboaia, comuna Boianu Mare, judetul BIHOR, Romania")),
    createLoc("Huta", "sat", createAdresaCompleta("sat Huta, comuna Boianu Mare, judetul BIHOR, România", "sat Huta, comuna Boianu Mare, judetul BIHOR, Romania")),
    createLoc("Păgaia", "sat", createAdresaCompleta("sat Păgaia, comuna Boianu Mare, judetul BIHOR, România", "sat Pagaia, comuna Boianu Mare, judetul BIHOR, Romania")),
    createLoc("Rugea", "sat", createAdresaCompleta("sat Rugea, comuna Boianu Mare, judetul BIHOR, România", "sat Rugea, comuna Boianu Mare, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Boianu Mare, judetul BIHOR, România", "comuna Boianu Mare, judetul BIHOR, Romania")),
createComuna("Borod", [
    createLoc("Borod", "sat", createAdresaCompleta("sat Borod, comuna Borod, judetul BIHOR, România", "sat Borod, comuna Borod, judetul BIHOR, Romania")),
    createLoc("Borozel", "sat", createAdresaCompleta("sat Borozel, comuna Borod, judetul BIHOR, România", "sat Borozel, comuna Borod, judetul BIHOR, Romania")),
    createLoc("Cetea", "sat", createAdresaCompleta("sat Cetea, comuna Borod, judetul BIHOR, România", "sat Cetea, comuna Borod, judetul BIHOR, Romania")),
    createLoc("Cornițel", "sat", createAdresaCompleta("sat Cornițel, comuna Borod, judetul BIHOR, România", "sat Cornitel, comuna Borod, judetul BIHOR, Romania")),
    createLoc("Șerani", "sat", createAdresaCompleta("sat Șerani, comuna Borod, judetul BIHOR, România", "sat Serani, comuna Borod, judetul BIHOR, Romania")),
    createLoc("Valea Mare de Criș", "sat", createAdresaCompleta("sat Valea Mare de Criș, comuna Borod, judetul BIHOR, România", "sat Valea Mare de Cris, comuna Borod, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Borod, judetul BIHOR, România", "comuna Borod, judetul BIHOR, Romania")),

createComuna("Borș", [
    createLoc("Borș", "sat", createAdresaCompleta("sat Borș, comuna Borș, judetul BIHOR, România", "sat Bors, comuna Bors, judetul BIHOR, Romania")),
    createLoc("Santăul Mare", "sat", createAdresaCompleta("sat Santăul Mare, comuna Borș, judetul BIHOR, România", "sat Santaul Mare, comuna Bors, judetul BIHOR, Romania")),
    createLoc("Santăul Mic", "sat", createAdresaCompleta("sat Santăul Mic, comuna Borș, judetul BIHOR, România", "sat Santaul Mic, comuna Bors, judetul BIHOR, Romania")),
    createLoc("Sântion", "sat", createAdresaCompleta("sat Sântion, comuna Borș, judetul BIHOR, România", "sat Santion, comuna Bors, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Borș, judetul BIHOR, România", "comuna Bors, judetul BIHOR, Romania")),
createComuna("Bratca", [
    createLoc("Bratca", "sat", createAdresaCompleta("sat Bratca, comuna Bratca, judetul BIHOR, România", "sat Bratca, comuna Bratca, judetul BIHOR, Romania")),
    createLoc("Beznea", "sat", createAdresaCompleta("sat Beznea, comuna Bratca, judetul BIHOR, România", "sat Beznea, comuna Bratca, judetul BIHOR, Romania")),
    createLoc("Damiș", "sat", createAdresaCompleta("sat Damiș, comuna Bratca, judetul BIHOR, România", "sat Damis, comuna Bratca, judetul BIHOR, Romania")),
    createLoc("Lorău", "sat", createAdresaCompleta("sat Lorău, comuna Bratca, judetul BIHOR, România", "sat Lorau, comuna Bratca, judetul BIHOR, Romania")),
    createLoc("Ponoară", "sat", createAdresaCompleta("sat Ponoară, comuna Bratca, judetul BIHOR, România", "sat Ponoara, comuna Bratca, judetul BIHOR, Romania")),
    createLoc("Valea Crișului", "sat", createAdresaCompleta("sat Valea Crișului, comuna Bratca, judetul BIHOR, România", "sat Valea Crisului, comuna Bratca, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Bratca, judetul BIHOR, România", "comuna Bratca, judetul BIHOR, Romania")),
createComuna("Brusturi", [
    createLoc("Brusturi", "sat", createAdresaCompleta("sat Brusturi, comuna Brusturi, judetul BIHOR, România", "sat Brusturi, comuna Brusturi, judetul BIHOR, Romania")),
    createLoc("Cuieșd", "sat", createAdresaCompleta("sat Cuieșd, comuna Brusturi, judetul BIHOR, România", "sat Cuiesd, comuna Brusturi, judetul BIHOR, Romania")),
    createLoc("Loranta", "sat", createAdresaCompleta("sat Loranta, comuna Brusturi, judetul BIHOR, România", "sat Loranta, comuna Brusturi, judetul BIHOR, Romania")),
    createLoc("Orvișele", "sat", createAdresaCompleta("sat Orvișele, comuna Brusturi, judetul BIHOR, România", "sat Orvisele, comuna Brusturi, judetul BIHOR, Romania")),
    createLoc("Păulești", "sat", createAdresaCompleta("sat Păulești, comuna Brusturi, judetul BIHOR, România", "sat Paulesti, comuna Brusturi, judetul BIHOR, Romania")),
    createLoc("Picleu", "sat", createAdresaCompleta("sat Picleu, comuna Brusturi, judetul BIHOR, România", "sat Picleu, comuna Brusturi, judetul BIHOR, Romania")),
    createLoc("Țigăneștii de Criș", "sat", createAdresaCompleta("sat Țigăneștii de Criș, comuna Brusturi, judetul BIHOR, România", "sat Tiganestii de Cris, comuna Brusturi, judetul BIHOR, Romania")),
    createLoc("Varasău", "sat", createAdresaCompleta("sat Varasău, comuna Brusturi, judetul BIHOR, România", "sat Varasau, comuna Brusturi, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Brusturi, judetul BIHOR, România", "comuna Brusturi, judetul BIHOR, Romania")),
createComuna("Budureasa", [
    createLoc("Budureasa", "sat", createAdresaCompleta("sat Budureasa, comuna Budureasa, judetul BIHOR, România", "sat Budureasa, comuna Budureasa, judetul BIHOR, Romania")),
    createLoc("Burda", "sat", createAdresaCompleta("sat Burda, comuna Budureasa, judetul BIHOR, România", "sat Burda, comuna Budureasa, judetul BIHOR, Romania")),
    createLoc("Saca", "sat", createAdresaCompleta("sat Saca, comuna Budureasa, judetul BIHOR, România", "sat Saca, comuna Budureasa, judetul BIHOR, Romania")),
    createLoc("Săliște de Beiuș", "sat", createAdresaCompleta("sat Săliște de Beiuș, comuna Budureasa, judetul BIHOR, România", "sat Saliste de Beius, comuna Budureasa, judetul BIHOR, Romania")),
    createLoc("Teleac", "sat", createAdresaCompleta("sat Teleac, comuna Budureasa, judetul BIHOR, România", "sat Teleac, comuna Budureasa, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Budureasa, judetul BIHOR, România", "comuna Budureasa, judetul BIHOR, Romania")),
createComuna("Buduslău", [
    createLoc("Buduslău", "sat", createAdresaCompleta("sat Buduslău, comuna Buduslău, judetul BIHOR, România", "sat Buduslau, comuna Buduslau, judetul BIHOR, Romania")),
    createLoc("Albiș", "sat", createAdresaCompleta("sat Albiș, comuna Buduslău, judetul BIHOR, România", "sat Albis, comuna Buduslau, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Buduslău, judetul BIHOR, România", "comuna Buduslau, judetul BIHOR, Romania")),
createComuna("Bulz", [
    createLoc("Bulz", "sat", createAdresaCompleta("sat Bulz, comuna Bulz, judetul BIHOR, România", "sat Bulz, comuna Bulz, judetul BIHOR, Romania")),
    createLoc("Munteni", "sat", createAdresaCompleta("sat Munteni, comuna Bulz, judetul BIHOR, România", "sat Munteni, comuna Bulz, judetul BIHOR, Romania")),
    createLoc("Remeți", "sat", createAdresaCompleta("sat Remeți, comuna Bulz, judetul BIHOR, România", "sat Remeti, comuna Bulz, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Bulz, judetul BIHOR, România", "comuna Bulz, judetul BIHOR, Romania")),
createComuna("Buntești", [
    createLoc("Buntești", "sat", createAdresaCompleta("sat Buntești, comuna Buntești, judetul BIHOR, România", "sat Buntesti, comuna Buntesti, judetul BIHOR, Romania")),
    createLoc("Brădet", "sat", createAdresaCompleta("sat Brădet, comuna Buntești, judetul BIHOR, România", "sat Bradet, comuna Buntesti, judetul BIHOR, Romania")),
    createLoc("Dumbrăvani", "sat", createAdresaCompleta("sat Dumbrăvani, comuna Buntești, judetul BIHOR, România", "sat Dumbravani, comuna Buntesti, judetul BIHOR, Romania")),
    createLoc("Ferice", "sat", createAdresaCompleta("sat Ferice, comuna Buntești, judetul BIHOR, România", "sat Ferice, comuna Buntesti, judetul BIHOR, Romania")),
    createLoc("Lelești", "sat", createAdresaCompleta("sat Lelești, comuna Buntești, judetul BIHOR, România", "sat Lelesti, comuna Buntesti, judetul BIHOR, Romania")),
    createLoc("Poienii de Jos", "sat", createAdresaCompleta("sat Poienii de Jos, comuna Buntești, judetul BIHOR, România", "sat Poienii de Jos, comuna Buntesti, judetul BIHOR, Romania")),
    createLoc("Poienii de Sus", "sat", createAdresaCompleta("sat Poienii de Sus, comuna Buntești, judetul BIHOR, România", "sat Poienii de Sus, comuna Buntesti, judetul BIHOR, Romania")),
    createLoc("Săud", "sat", createAdresaCompleta("sat Săud, comuna Buntești, judetul BIHOR, România", "sat Saud, comuna Buntesti, judetul BIHOR, Romania")),
    createLoc("Stâncești", "sat", createAdresaCompleta("sat Stâncești, comuna Buntești, judetul BIHOR, România", "sat Stancesti, comuna Buntesti, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Buntești, judetul BIHOR, România", "comuna Buntesti, judetul BIHOR, Romania")),
createComuna("Căbești", [
    createLoc("Căbești", "sat", createAdresaCompleta("sat Căbești, comuna Căbești, judetul BIHOR, România", "sat Cabesti, comuna Cabesti, judetul BIHOR, Romania")),
    createLoc("Goila", "sat", createAdresaCompleta("sat Goila, comuna Căbești, judetul BIHOR, România", "sat Goila, comuna Cabesti, judetul BIHOR, Romania")),
    createLoc("Gurbești", "sat", createAdresaCompleta("sat Gurbești, comuna Căbești, judetul BIHOR, România", "sat Gurbesti, comuna Cabesti, judetul BIHOR, Romania")),
    createLoc("Josani", "sat", createAdresaCompleta("sat Josani, comuna Căbești, judetul BIHOR, România", "sat Josani, comuna Cabesti, judetul BIHOR, Romania")),
    createLoc("Sohodol", "sat", createAdresaCompleta("sat Sohodol, comuna Căbești, judetul BIHOR, România", "sat Sohodol, comuna Cabesti, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Căbești, judetul BIHOR, România", "comuna Cabesti, judetul BIHOR, Romania")),
createComuna("Căpâlna", [
    createLoc("Căpâlna", "sat", createAdresaCompleta("sat Căpâlna, comuna Căpâlna, judetul BIHOR, România", "sat Capalna, comuna Capalna, judetul BIHOR, Romania")),
    createLoc("Ginta", "sat", createAdresaCompleta("sat Ginta, comuna Căpâlna, judetul BIHOR, România", "sat Ginta, comuna Capalna, judetul BIHOR, Romania")),
    createLoc("Rohani", "sat", createAdresaCompleta("sat Rohani, comuna Căpâlna, judetul BIHOR, România", "sat Rohani, comuna Capalna, judetul BIHOR, Romania")),
    createLoc("Săldăbagiu Mic", "sat", createAdresaCompleta("sat Săldăbagiu Mic, comuna Căpâlna, judetul BIHOR, România", "sat Saldabagiu Mic, comuna Capalna, judetul BIHOR, Romania")),
    createLoc("Suplacu de Tinca", "sat", createAdresaCompleta("sat Suplacu de Tinca, comuna Căpâlna, judetul BIHOR, România", "sat Suplacu de Tinca, comuna Capalna, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Căpâlna, judetul BIHOR, România", "comuna Capalna, judetul BIHOR, Romania")),
createComuna("Cărpinet", [
    createLoc("Cărpinet", "sat", createAdresaCompleta("sat Cărpinet, comuna Cărpinet, judetul BIHOR, România", "sat Carpinet, comuna Carpinet, judetul BIHOR, Romania")),
    createLoc("Călugări", "sat", createAdresaCompleta("sat Călugări, comuna Cărpinet, judetul BIHOR, România", "sat Calugari, comuna Carpinet, judetul BIHOR, Romania")),
    createLoc("Izbuc", "sat", createAdresaCompleta("sat Izbuc, comuna Cărpinet, judetul BIHOR, România", "sat Izbuc, comuna Carpinet, judetul BIHOR, Romania")),
    createLoc("Leheceni", "sat", createAdresaCompleta("sat Leheceni, comuna Cărpinet, judetul BIHOR, România", "sat Leheceni, comuna Carpinet, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Cărpinet, judetul BIHOR, România", "comuna Carpinet, judetul BIHOR, Romania")),
createComuna("Cefa", [
    createLoc("Cefa", "sat", createAdresaCompleta("sat Cefa, comuna Cefa, judetul BIHOR, România", "sat Cefa, comuna Cefa, judetul BIHOR, Romania")),
    createLoc("Ateaș", "sat", createAdresaCompleta("sat Ateaș, comuna Cefa, judetul BIHOR, România", "sat Ateas, comuna Cefa, judetul BIHOR, Romania")),
    createLoc("Inand", "sat", createAdresaCompleta("sat Inand, comuna Cefa, judetul BIHOR, România", "sat Inand, comuna Cefa, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Cefa, judetul BIHOR, România", "comuna Cefa, judetul BIHOR, Romania")),
createComuna("Ceica", [
    createLoc("Ceica", "sat", createAdresaCompleta("sat Ceica, comuna Ceica, judetul BIHOR, România", "sat Ceica, comuna Ceica, judetul BIHOR, Romania")),
    createLoc("Bucium", "sat", createAdresaCompleta("sat Bucium, comuna Ceica, judetul BIHOR, România", "sat Bucium, comuna Ceica, judetul BIHOR, Romania")),
    createLoc("Ceișoara", "sat", createAdresaCompleta("sat Ceișoara, comuna Ceica, judetul BIHOR, România", "sat Ceisoara, comuna Ceica, judetul BIHOR, Romania")),
    createLoc("Corbești", "sat", createAdresaCompleta("sat Corbești, comuna Ceica, judetul BIHOR, România", "sat Corbesti, comuna Ceica, judetul BIHOR, Romania")),
    createLoc("Cotiglet", "sat", createAdresaCompleta("sat Cotiglet, comuna Ceica, judetul BIHOR, România", "sat Cotiglet, comuna Ceica, judetul BIHOR, Romania")),
    createLoc("Dușești", "sat", createAdresaCompleta("sat Dușești, comuna Ceica, judetul BIHOR, România", "sat Dusesti, comuna Ceica, judetul BIHOR, Romania")),
    createLoc("Incești", "sat", createAdresaCompleta("sat Incești, comuna Ceica, judetul BIHOR, România", "sat Incesti, comuna Ceica, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Ceica, judetul BIHOR, România", "comuna Ceica, judetul BIHOR, Romania")),
createComuna("Cetariu", [
    createLoc("Cetariu", "sat", createAdresaCompleta("sat Cetariu, comuna Cetariu, judetul BIHOR, România", "sat Cetariu, comuna Cetariu, judetul BIHOR, Romania")),
    createLoc("Șișterea", "sat", createAdresaCompleta("sat Șișterea, comuna Cetariu, judetul BIHOR, România", "sat Sisterea, comuna Cetariu, judetul BIHOR, Romania")),
    createLoc("Șușturogi", "sat", createAdresaCompleta("sat Șușturogi, comuna Cetariu, judetul BIHOR, România", "sat Susturogi, comuna Cetariu, judetul BIHOR, Romania")),
    createLoc("Tăutelec", "sat", createAdresaCompleta("sat Tăutelec, comuna Cetariu, judetul BIHOR, România", "sat Tautelec, comuna Cetariu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Cetariu, judetul BIHOR, România", "comuna Cetariu, judetul BIHOR, Romania")),
createComuna("Cherechiu", [
    createLoc("Cherechiu", "sat", createAdresaCompleta("sat Cherechiu, comuna Cherechiu, judetul BIHOR, România", "sat Cherechiu, comuna Cherechiu, judetul BIHOR, Romania")),
    createLoc("Cheșereu", "sat", createAdresaCompleta("sat Cheșereu, comuna Cherechiu, judetul BIHOR, România", "sat Chesereu, comuna Cherechiu, judetul BIHOR, Romania")),
    createLoc("Târgușor", "sat", createAdresaCompleta("sat Târgușor, comuna Cherechiu, judetul BIHOR, România", "sat Targusor, comuna Cherechiu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Cherechiu, judetul BIHOR, România", "comuna Cherechiu, judetul BIHOR, Romania")),
createComuna("Chișlaz", [
    createLoc("Chișlaz", "sat", createAdresaCompleta("sat Chișlaz, comuna Chișlaz, judetul BIHOR, România", "sat Chislaz, comuna Chislaz, judetul BIHOR, Romania")),
    createLoc("Chiraleu", "sat", createAdresaCompleta("sat Chiraleu, comuna Chișlaz, judetul BIHOR, România", "sat Chiraleu, comuna Chislaz, judetul BIHOR, Romania")),
    createLoc("Hăucești", "sat", createAdresaCompleta("sat Hăucești, comuna Chișlaz, judetul BIHOR, România", "sat Haucesti, comuna Chislaz, judetul BIHOR, Romania")),
    createLoc("Mișca", "sat", createAdresaCompleta("sat Mișca, comuna Chișlaz, judetul BIHOR, România", "sat Misca, comuna Chislaz, judetul BIHOR, Romania")),
    createLoc("Poclușa de Barcău", "sat", createAdresaCompleta("sat Poclușa de Barcău, comuna Chișlaz, judetul BIHOR, România", "sat Poclusa de Barcau, comuna Chislaz, judetul BIHOR, Romania")),
    createLoc("Sărsig", "sat", createAdresaCompleta("sat Sărsig, comuna Chișlaz, judetul BIHOR, România", "sat Sarsig, comuna Chislaz, judetul BIHOR, Romania")),
    createLoc("Sânlazăr", "sat", createAdresaCompleta("sat Sânlazăr, comuna Chișlaz, judetul BIHOR, România", "sat Sanlazar, comuna Chislaz, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Chișlaz, judetul BIHOR, România", "comuna Chislaz, judetul BIHOR, Romania")),
createComuna("Ciumeghiu", [
    createLoc("Ciumeghiu", "sat", createAdresaCompleta("sat Ciumeghiu, comuna Ciumeghiu, judetul BIHOR, România", "sat Ciumeghiu, comuna Ciumeghiu, judetul BIHOR, Romania")),
    createLoc("Boiu", "sat", createAdresaCompleta("sat Boiu, comuna Ciumeghiu, judetul BIHOR, România", "sat Boiu, comuna Ciumeghiu, judetul BIHOR, Romania")),
    createLoc("Ghiorac", "sat", createAdresaCompleta("sat Ghiorac, comuna Ciumeghiu, judetul BIHOR, România", "sat Ghiorac, comuna Ciumeghiu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Ciumeghiu, judetul BIHOR, România", "comuna Ciumeghiu, judetul BIHOR, Romania")),
createComuna("Câmpani", [
    createLoc("Câmpani", "sat", createAdresaCompleta("sat Câmpani, comuna Câmpani, judetul BIHOR, România", "sat Campani, comuna Campani, judetul BIHOR, Romania")),
    createLoc("Fânațe", "sat", createAdresaCompleta("sat Fânațe, comuna Câmpani, judetul BIHOR, România", "sat Fanate, comuna Campani, judetul BIHOR, Romania")),
    createLoc("Hârsești", "sat", createAdresaCompleta("sat Hârsești, comuna Câmpani, judetul BIHOR, România", "sat Harsesti, comuna Campani, judetul BIHOR, Romania")),
    createLoc("Sighiștel", "sat", createAdresaCompleta("sat Sighiștel, comuna Câmpani, judetul BIHOR, România", "sat Sighistel, comuna Campani, judetul BIHOR, Romania")),
    createLoc("Valea de Sus", "sat", createAdresaCompleta("sat Valea de Sus, comuna Câmpani, judetul BIHOR, România", "sat Valea de Sus, comuna Campani, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Câmpani, judetul BIHOR, România", "comuna Campani, judetul BIHOR, Romania")),
createComuna("Cociuba Mare", [
    createLoc("Cociuba Mare", "sat", createAdresaCompleta("sat Cociuba Mare, comuna Cociuba Mare, judetul BIHOR, România", "sat Cociuba Mare, comuna Cociuba Mare, judetul BIHOR, Romania")),
    createLoc("Cărăsău", "sat", createAdresaCompleta("sat Cărăsău, comuna Cociuba Mare, judetul BIHOR, România", "sat Carasau, comuna Cociuba Mare, judetul BIHOR, Romania")),
    createLoc("Cheșa", "sat", createAdresaCompleta("sat Cheșa, comuna Cociuba Mare, judetul BIHOR, România", "sat Chesa, comuna Cociuba Mare, judetul BIHOR, Romania")),
    createLoc("Petid", "sat", createAdresaCompleta("sat Petid, comuna Cociuba Mare, judetul BIHOR, România", "sat Petid, comuna Cociuba Mare, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Cociuba Mare, judetul BIHOR, România", "comuna Cociuba Mare, judetul BIHOR, Romania")),
createComuna("Copăcel", [
    createLoc("Copăcel", "sat", createAdresaCompleta("sat Copăcel, comuna Copăcel, judetul BIHOR, România", "sat Copacel, comuna Copacel, judetul BIHOR, Romania")),
    createLoc("Bucuroaia", "sat", createAdresaCompleta("sat Bucuroaia, comuna Copăcel, judetul BIHOR, România", "sat Bucuroaia, comuna Copacel, judetul BIHOR, Romania")),
    createLoc("Chijic", "sat", createAdresaCompleta("sat Chijic, comuna Copăcel, judetul BIHOR, România", "sat Chijic, comuna Copacel, judetul BIHOR, Romania")),
    createLoc("Poiana Tășad", "sat", createAdresaCompleta("sat Poiana Tășad, comuna Copăcel, judetul BIHOR, România", "sat Poiana Tasad, comuna Copacel, judetul BIHOR, Romania")),
    createLoc("Sărand", "sat", createAdresaCompleta("sat Sărand, comuna Copăcel, judetul BIHOR, România", "sat Sarand, comuna Copacel, judetul BIHOR, Romania")),
    createLoc("Surduc", "sat", createAdresaCompleta("sat Surduc, comuna Copăcel, judetul BIHOR, România", "sat Surduc, comuna Copacel, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Copăcel, judetul BIHOR, România", "comuna Copacel, judetul BIHOR, Romania")),
createComuna("Criștioru de Jos", [
    createLoc("Criștioru de Jos", "sat", createAdresaCompleta("sat Criștioru de Jos, comuna Criștioru de Jos, judetul BIHOR, România", "sat Cristioru de Jos, comuna Cristioru de Jos, judetul BIHOR, Romania")),
    createLoc("Bâlc", "sat", createAdresaCompleta("sat Bâlc, comuna Criștioru de Jos, judetul BIHOR, România", "sat Balc, comuna Cristioru de Jos, judetul BIHOR, Romania")),
    createLoc("Criștioru de Sus", "sat", createAdresaCompleta("sat Criștioru de Sus, comuna Criștioru de Jos, judetul BIHOR, România", "sat Cristioru de Sus, comuna Cristioru de Jos, judetul BIHOR, Romania")),
    createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Criștioru de Jos, judetul BIHOR, România", "sat Poiana, comuna Cristioru de Jos, judetul BIHOR, Romania")),
    createLoc("Săliște de Vașcău", "sat", createAdresaCompleta("sat Săliște de Vașcău, comuna Criștioru de Jos, judetul BIHOR, România", "sat Saliste de Vascau, comuna Cristioru de Jos, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Criștioru de Jos, judetul BIHOR, România", "comuna Cristioru de Jos, judetul BIHOR, Romania")),
createComuna("Curățele", [
    createLoc("Curățele", "sat", createAdresaCompleta("sat Curățele, comuna Curățele, judetul BIHOR, România", "sat Curatele, comuna Curatele, judetul BIHOR, Romania")),
    createLoc("Beiușele", "sat", createAdresaCompleta("sat Beiușele, comuna Curățele, judetul BIHOR, România", "sat Beiusele, comuna Curatele, judetul BIHOR, Romania")),
    createLoc("Cresuia", "sat", createAdresaCompleta("sat Cresuia, comuna Curățele, judetul BIHOR, România", "sat Cresuia, comuna Curatele, judetul BIHOR, Romania")),
    createLoc("Nimăiești", "sat", createAdresaCompleta("sat Nimăiești, comuna Curățele, judetul BIHOR, România", "sat Nimaiesti, comuna Curatele, judetul BIHOR, Romania")),
    createLoc("Pocioveliște", "sat", createAdresaCompleta("sat Pocioveliște, comuna Curățele, judetul BIHOR, România", "sat Pocioveliste, comuna Curatele, judetul BIHOR, Romania")),
]),
createComuna("Curtuișeni", [
    createLoc("Curtuișeni", "sat", createAdresaCompleta("sat Curtuișeni, comuna Curtuișeni, judetul BIHOR, România", "sat Curtuiseni, comuna Curtuiseni, judetul BIHOR, Romania")),
    createLoc("Vășad", "sat", createAdresaCompleta("sat Vășad, comuna Curtuișeni, judetul BIHOR, România", "sat Vasad, comuna Curtuiseni, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Curtuișeni, judetul BIHOR, România", "comuna Curtuiseni, judetul BIHOR, Romania")),
createComuna("Derna", [
    createLoc("Derna", "sat", createAdresaCompleta("sat Derna, comuna Derna, judetul BIHOR, România", "sat Derna, comuna Derna, judetul BIHOR, Romania")),
    createLoc("Dernișoara", "sat", createAdresaCompleta("sat Dernișoara, comuna Derna, judetul BIHOR, România", "sat Dernisoara, comuna Derna, judetul BIHOR, Romania")),
    createLoc("Sacalasău", "sat", createAdresaCompleta("sat Sacalasău, comuna Derna, judetul BIHOR, România", "sat Sacalasau, comuna Derna, judetul BIHOR, Romania")),
    createLoc("Sacalasău Nou", "sat", createAdresaCompleta("sat Sacalasău Nou, comuna Derna, judetul BIHOR, România", "sat Sacalasau Nou, comuna Derna, judetul BIHOR, Romania")),
    createLoc("Tria", "sat", createAdresaCompleta("sat Tria, comuna Derna, judetul BIHOR, România", "sat Tria, comuna Derna, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Derna, judetul BIHOR, România", "comuna Derna, judetul BIHOR, Romania")),
createComuna("Diosig", [
    createLoc("Diosig", "sat", createAdresaCompleta("sat Diosig, comuna Diosig, judetul BIHOR, România", "sat Diosig, comuna Diosig, judetul BIHOR, Romania")),
    createLoc("Ianca", "sat", createAdresaCompleta("sat Ianca, comuna Diosig, judetul BIHOR, România", "sat Ianca, comuna Diosig, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Diosig, judetul BIHOR, România", "comuna Diosig, judetul BIHOR, Romania")),
createComuna("Dobrești", [
    createLoc("Dobrești", "sat", createAdresaCompleta("sat Dobrești, comuna Dobrești, judetul BIHOR, România", "sat Dobresti, comuna Dobresti, judetul BIHOR, Romania")),
    createLoc("Cornișești", "sat", createAdresaCompleta("sat Cornișești, comuna Dobrești, judetul BIHOR, România", "sat Cornisesti, comuna Dobresti, judetul BIHOR, Romania")),
    createLoc("Crâncești", "sat", createAdresaCompleta("sat Crâncești, comuna Dobrești, judetul BIHOR, România", "sat Crancesti, comuna Dobresti, judetul BIHOR, Romania")),
    createLoc("Hidișel", "sat", createAdresaCompleta("sat Hidișel, comuna Dobrești, judetul BIHOR, România", "sat Hidisel, comuna Dobresti, judetul BIHOR, Romania")),
    createLoc("Luncasprie", "sat", createAdresaCompleta("sat Luncasprie, comuna Dobrești, judetul BIHOR, România", "sat Luncasprie, comuna Dobresti, judetul BIHOR, Romania")),
    createLoc("Răcaș", "sat", createAdresaCompleta("sat Răcaș, comuna Dobrești, judetul BIHOR, România", "sat Racas, comuna Dobresti, judetul BIHOR, Romania")),
    createLoc("Topa de Jos", "sat", createAdresaCompleta("sat Topa de Jos, comuna Dobrești, judetul BIHOR, România", "sat Topa de Jos, comuna Dobresti, judetul BIHOR, Romania")),
    createLoc("Topa de Sus", "sat", createAdresaCompleta("sat Topa de Sus, comuna Dobrești, judetul BIHOR, România", "sat Topa de Sus, comuna Dobresti, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Dobrești, judetul BIHOR, România", "comuna Dobresti, judetul BIHOR, Romania")),
createComuna("Drăgănești", [
    createLoc("Drăgănești", "sat", createAdresaCompleta("sat Drăgănești, comuna Drăgănești, judetul BIHOR, România", "sat Draganesti, comuna Draganesti, judetul BIHOR, Romania")),
    createLoc("Belejeni", "sat", createAdresaCompleta("sat Belejeni, comuna Drăgănești, judetul BIHOR, România", "sat Belejeni, comuna Draganesti, judetul BIHOR, Romania")),
    createLoc("Grădinari", "sat", createAdresaCompleta("sat Grădinari, comuna Drăgănești, judetul BIHOR, România", "sat Gradinari, comuna Draganesti, judetul BIHOR, Romania")),
    createLoc("Livada Beiușului", "sat", createAdresaCompleta("sat Livada Beiușului, comuna Drăgănești, judetul BIHOR, România", "sat Livada Beiusului, comuna Draganesti, judetul BIHOR, Romania")),
    createLoc("Mizieș", "sat", createAdresaCompleta("sat Mizieș, comuna Drăgănești, judetul BIHOR, România", "sat Mizies, comuna Draganesti, judetul BIHOR, Romania")),
    createLoc("Păcălești", "sat", createAdresaCompleta("sat Păcălești, comuna Drăgănești, judetul BIHOR, România", "sat Pacalesti, comuna Draganesti, judetul BIHOR, Romania")),
    createLoc("Păntășești", "sat", createAdresaCompleta("sat Păntășești, comuna Drăgănești, judetul BIHOR, România", "sat Pantasesti, comuna Draganesti, judetul BIHOR, Romania")),
    createLoc("Șebiș", "sat", createAdresaCompleta("sat Șebiș, comuna Drăgănești, judetul BIHOR, România", "sat Sebis, comuna Draganesti, judetul BIHOR, Romania")),
    createLoc("Talpe", "sat", createAdresaCompleta("sat Talpe, comuna Drăgănești, judetul BIHOR, România", "sat Talpe, comuna Draganesti, judetul BIHOR, Romania")),
    createLoc("Țigăneștii de Beiuș", "sat", createAdresaCompleta("sat Țigăneștii de Beiuș, comuna Drăgănești, judetul BIHOR, România", "sat Tiganestii de Beius, comuna Draganesti, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Drăgănești, judetul BIHOR, România", "comuna Draganesti, judetul BIHOR, Romania")),
createComuna("Drăgești", [
    createLoc("Drăgești", "sat", createAdresaCompleta("sat Drăgești, comuna Drăgești, judetul BIHOR, România", "sat Dragesti, comuna Dragesti, judetul BIHOR, Romania")),
    createLoc("Dicănești", "sat", createAdresaCompleta("sat Dicănești, comuna Drăgești, judetul BIHOR, România", "sat Dicanesti, comuna Dragesti, judetul BIHOR, Romania")),
    createLoc("Stracoș", "sat", createAdresaCompleta("sat Stracoș, comuna Drăgești, judetul BIHOR, România", "sat Stracos, comuna Dragesti, judetul BIHOR, Romania")),
    createLoc("Tășad", "sat", createAdresaCompleta("sat Tășad, comuna Drăgești, judetul BIHOR, România", "sat Tasad, comuna Dragesti, judetul BIHOR, Romania")),
    createLoc("Topești", "sat", createAdresaCompleta("sat Topești, comuna Drăgești, judetul BIHOR, România", "sat Topesti, comuna Dragesti, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Drăgești, judetul BIHOR, România", "comuna Dragesti, judetul BIHOR, Romania")),
createComuna("Finiș", [
    createLoc("Finiș", "sat", createAdresaCompleta("sat Finiș, comuna Finiș, judetul BIHOR, România", "sat Finis, comuna Finis, judetul BIHOR, Romania")),
    createLoc("Brusturi", "sat", createAdresaCompleta("sat Brusturi, comuna Finiș, judetul BIHOR, România", "sat Brusturi, comuna Finis, judetul BIHOR, Romania")),
    createLoc("Fiziș", "sat", createAdresaCompleta("sat Fiziș, comuna Finiș, judetul BIHOR, România", "sat Fizis, comuna Finis, judetul BIHOR, Romania")),
    createLoc("Ioaniș", "sat", createAdresaCompleta("sat Ioaniș, comuna Finiș, judetul BIHOR, România", "sat Ioanis, comuna Finis, judetul BIHOR, Romania")),
    createLoc("Șuncuiș", "sat", createAdresaCompleta("sat Șuncuiș, comuna Finiș, judetul BIHOR, România", "sat Suncuis, comuna Finis, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Finiș, judetul BIHOR, România", "comuna Finis, judetul BIHOR, Romania")),
createComuna("Gepiu", [
    createLoc("Gepiu", "sat", createAdresaCompleta("sat Gepiu, comuna Gepiu, judetul BIHOR, România", "sat Gepiu, comuna Gepiu, judetul BIHOR, Romania")),
    createLoc("Bicaci", "sat", createAdresaCompleta("sat Bicaci, comuna Gepiu, judetul BIHOR, România", "sat Bicaci, comuna Gepiu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Gepiu, judetul BIHOR, România", "comuna Gepiu, judetul BIHOR, Romania")),
createComuna("Girișu de Criș", [
    createLoc("Girișu de Criș", "sat", createAdresaCompleta("sat Girișu de Criș, comuna Girișu de Criș, judetul BIHOR, România", "sat Girisu de Cris, comuna Girisu de Cris, judetul BIHOR, Romania")),
    createLoc("Tărian", "sat", createAdresaCompleta("sat Tărian, comuna Girișu de Criș, judetul BIHOR, România", "sat Tarian, comuna Girisu de Cris, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Girișu de Criș, judetul BIHOR, România", "comuna Girisu de Cris, judetul BIHOR, Romania")),
createComuna("Hidișelu de Sus", [
    createLoc("Hidișelu de Sus", "sat", createAdresaCompleta("sat Hidișelu de Sus, comuna Hidișelu de Sus, judetul BIHOR, România", "sat Hidiselu de Sus, comuna Hidiselu de Sus, judetul BIHOR, Romania")),
    createLoc("Hidișelu de Jos", "sat", createAdresaCompleta("sat Hidișelu de Jos, comuna Hidișelu de Sus, judetul BIHOR, România", "sat Hidiselu de Jos, comuna Hidiselu de Sus, judetul BIHOR, Romania")),
    createLoc("Mierlău", "sat", createAdresaCompleta("sat Mierlău, comuna Hidișelu de Sus, judetul BIHOR, România", "sat Mierlau, comuna Hidiselu de Sus, judetul BIHOR, Romania")),
    createLoc("Sântelec", "sat", createAdresaCompleta("sat Sântelec, comuna Hidișelu de Sus, judetul BIHOR, România", "sat Santelec, comuna Hidiselu de Sus, judetul BIHOR, Romania")),
    createLoc("Șumugiu", "sat", createAdresaCompleta("sat Șumugiu, comuna Hidișelu de Sus, judetul BIHOR, România", "sat Sumugiu, comuna Hidiselu de Sus, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Hidișelu de Sus, judetul BIHOR, România", "comuna Hidiselu de Sus, judetul BIHOR, Romania")),
createComuna("Holod", [
    createLoc("Holod", "sat", createAdresaCompleta("sat Holod, comuna Holod, judetul BIHOR, România", "sat Holod, comuna Holod, judetul BIHOR, Romania")),
    createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, comuna Holod, judetul BIHOR, România", "sat Dumbrava, comuna Holod, judetul BIHOR, Romania")),
    createLoc("Dumbrăvița", "sat", createAdresaCompleta("sat Dumbrăvița, comuna Holod, judetul BIHOR, România", "sat Dumbravita, comuna Holod, judetul BIHOR, Romania")),
    createLoc("Forosig", "sat", createAdresaCompleta("sat Forosig, comuna Holod, judetul BIHOR, România", "sat Forosig, comuna Holod, judetul BIHOR, Romania")),
    createLoc("Hodiș", "sat", createAdresaCompleta("sat Hodiș, comuna Holod, judetul BIHOR, România", "sat Hodis, comuna Holod, judetul BIHOR, Romania")),
    createLoc("Lupoaia", "sat", createAdresaCompleta("sat Lupoaia, comuna Holod, judetul BIHOR, România", "sat Lupoaia, comuna Holod, judetul BIHOR, Romania")),
    createLoc("Valea Mare de Codru", "sat", createAdresaCompleta("sat Valea Mare de Codru, comuna Holod, judetul BIHOR, România", "sat Valea Mare de Codru, comuna Holod, judetul BIHOR, Romania")),
    createLoc("Vintere", "sat", createAdresaCompleta("sat Vintere, comuna Holod, judetul BIHOR, România", "sat Vintere, comuna Holod, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Holod, judetul BIHOR, România", "comuna Holod, judetul BIHOR, Romania")),
createComuna("Husasău de Tinca", [
    createLoc("Husasău de Tinca", "sat", createAdresaCompleta("sat Husasău de Tinca, comuna Husasău de Tinca, judetul BIHOR, România", "sat Husasau de Tinca, comuna Husasau de Tinca, judetul BIHOR, Romania")),
    createLoc("Fonău", "sat", createAdresaCompleta("sat Fonău, comuna Husasău de Tinca, judetul BIHOR, România", "sat Fonau, comuna Husasau de Tinca, judetul BIHOR, Romania")),
    createLoc("Miersig", "sat", createAdresaCompleta("sat Miersig, comuna Husasău de Tinca, judetul BIHOR, România", "sat Miersig, comuna Husasau de Tinca, judetul BIHOR, Romania")),
    createLoc("Oșand", "sat", createAdresaCompleta("sat Oșand, comuna Husasău de Tinca, judetul BIHOR, România", "sat Osand, comuna Husasau de Tinca, judetul BIHOR, Romania")),
    createLoc("Sititelec", "sat", createAdresaCompleta("sat Sititelec, comuna Husasău de Tinca, judetul BIHOR, România", "sat Sititelec, comuna Husasau de Tinca, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Husasău de Tinca, judetul BIHOR, România", "comuna Husasau de Tinca, judetul BIHOR, Romania")),
createComuna("Ineu", [
    createLoc("Ineu", "sat", createAdresaCompleta("sat Ineu, comuna Ineu, judetul BIHOR, România", "sat Ineu, comuna Ineu, judetul BIHOR, Romania")),
    createLoc("Botean", "sat", createAdresaCompleta("sat Botean, comuna Ineu, judetul BIHOR, România", "sat Botean, comuna Ineu, judetul BIHOR, Romania")),
    createLoc("Husasău de Criș", "sat", createAdresaCompleta("sat Husasău de Criș, comuna Ineu, judetul BIHOR, România", "sat Husasau de Cris, comuna Ineu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Ineu, judetul BIHOR, România", "comuna Ineu, judetul BIHOR, Romania")),
createComuna("Lazuri de Beiuș", [
    createLoc("Lazuri de Beiuș", "sat", createAdresaCompleta("sat Lazuri de Beiuș, comuna Lazuri de Beiuș, judetul BIHOR, România", "sat Lazuri de Beius, comuna Lazuri de Beius, judetul BIHOR, Romania")),
    createLoc("Băleni", "sat", createAdresaCompleta("sat Băleni, comuna Lazuri de Beiuș, judetul BIHOR, România", "sat Baleni, comuna Lazuri de Beius, judetul BIHOR, Romania")),
    createLoc("Cusuiuș", "sat", createAdresaCompleta("sat Cusuiuș, comuna Lazuri de Beiuș, judetul BIHOR, România", "sat Cusuius, comuna Lazuri de Beius, judetul BIHOR, Romania")),
    createLoc("Hinchiriș", "sat", createAdresaCompleta("sat Hinchiriș, comuna Lazuri de Beiuș, judetul BIHOR, România", "sat Hinchiris, comuna Lazuri de Beius, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Lazuri de Beiuș, judetul BIHOR, România", "comuna Lazuri de Beius, judetul BIHOR, Romania")),
createComuna("Lăzăreni", [
    createLoc("Lăzăreni", "sat", createAdresaCompleta("sat Lăzăreni, comuna Lăzăreni, judetul BIHOR, România", "sat Lazareni, comuna Lazareni, judetul BIHOR, Romania")),
    createLoc("Bicăcel", "sat", createAdresaCompleta("sat Bicăcel, comuna Lăzăreni, judetul BIHOR, România", "sat Bicacel, comuna Lazareni, judetul BIHOR, Romania")),
    createLoc("Calea Mare", "sat", createAdresaCompleta("sat Calea Mare, comuna Lăzăreni, judetul BIHOR, România", "sat Calea Mare, comuna Lazareni, judetul BIHOR, Romania")),
    createLoc("Cărăndeni", "sat", createAdresaCompleta("sat Cărăndeni, comuna Lăzăreni, judetul BIHOR, România", "sat Carandeni, comuna Lazareni, judetul BIHOR, Romania")),
    createLoc("Cărănzel", "sat", createAdresaCompleta("sat Cărănzel, comuna Lăzăreni, judetul BIHOR, România", "sat Caranzel, comuna Lazareni, judetul BIHOR, Romania")),
    createLoc("Gepiș", "sat", createAdresaCompleta("sat Gepiș, comuna Lăzăreni, judetul BIHOR, România", "sat Gepis, comuna Lazareni, judetul BIHOR, Romania")),
    createLoc("Gruilung", "sat", createAdresaCompleta("sat Gruilung, comuna Lăzăreni, judetul BIHOR, România", "sat Gruilung, comuna Lazareni, judetul BIHOR, Romania")),
    createLoc("Miheleu", "sat", createAdresaCompleta("sat Miheleu, comuna Lăzăreni, judetul BIHOR, România", "sat Miheleu, comuna Lazareni, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Lăzăreni, judetul BIHOR, România", "comuna Lazareni, judetul BIHOR, Romania")),
createComuna("Lugașu de Jos", [
    createLoc("Lugașu de Jos", "sat", createAdresaCompleta("sat Lugașu de Jos, comuna Lugașu de Jos, judetul BIHOR, România", "sat Lugasu de Jos, comuna Lugasu de Jos, judetul BIHOR, Romania")),
    createLoc("Lugașu de Sus", "sat", createAdresaCompleta("sat Lugașu de Sus, comuna Lugașu de Jos, judetul BIHOR, România", "sat Lugasu de Sus, comuna Lugasu de Jos, judetul BIHOR, Romania")),
    createLoc("Urvind", "sat", createAdresaCompleta("sat Urvind, comuna Lugașu de Jos, judetul BIHOR, România", "sat Urvind, comuna Lugasu de Jos, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Lugașu de Jos, judetul BIHOR, România", "comuna Lugasu de Jos, judetul BIHOR, Romania")),
createComuna("Lunca", [
    createLoc("Lunca", "sat", createAdresaCompleta("sat Lunca, comuna Lunca, judetul BIHOR, România", "sat Lunca, comuna Lunca, judetul BIHOR, Romania")),
    createLoc("Briheni", "sat", createAdresaCompleta("sat Briheni, comuna Lunca, judetul BIHOR, România", "sat Briheni, comuna Lunca, judetul BIHOR, Romania")),
    createLoc("Hotărel", "sat", createAdresaCompleta("sat Hotărel, comuna Lunca, judetul BIHOR, România", "sat Hotarel, comuna Lunca, judetul BIHOR, Romania")),
    createLoc("Seghiște", "sat", createAdresaCompleta("sat Seghiște, comuna Lunca, judetul BIHOR, România", "sat Seghiste, comuna Lunca, judetul BIHOR, Romania")),
    createLoc("Sârbești", "sat", createAdresaCompleta("sat Sârbești, comuna Lunca, judetul BIHOR, România", "sat Sarbesti, comuna Lunca, judetul BIHOR, Romania")),
    createLoc("Șuștiu", "sat", createAdresaCompleta("sat Șuștiu, comuna Lunca, judetul BIHOR, România", "sat Sustiu, comuna Lunca, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Lunca, judetul BIHOR, România", "comuna Lunca, judetul BIHOR, Romania")),
createComuna("Mădăras", [
    createLoc("Mădăras", "sat", createAdresaCompleta("sat Mădăras, comuna Mădăras, judetul BIHOR, România", "sat Madaras, comuna Madaras, judetul BIHOR, Romania")),
    createLoc("Homorog", "sat", createAdresaCompleta("sat Homorog, comuna Mădăras, judetul BIHOR, România", "sat Homorog, comuna Madaras, judetul BIHOR, Romania")),
    createLoc("Ianoșda", "sat", createAdresaCompleta("sat Ianoșda, comuna Mădăras, judetul BIHOR, România", "sat Ianosda, comuna Madaras, judetul BIHOR, Romania")),
    createLoc("Marțihaz", "sat", createAdresaCompleta("sat Marțihaz, comuna Mădăras, judetul BIHOR, România", "sat Martihaz, comuna Madaras, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Mădăras, judetul BIHOR, România", "comuna Madaras, judetul BIHOR, Romania")),
createComuna("Măgești", [
    createLoc("Măgești", "sat", createAdresaCompleta("sat Măgești, comuna Măgești, judetul BIHOR, România", "sat Magesti, comuna Magesti, judetul BIHOR, Romania")),
    createLoc("Butani", "sat", createAdresaCompleta("sat Butani, comuna Măgești, judetul BIHOR, România", "sat Butani, comuna Magesti, judetul BIHOR, Romania")),
    createLoc("Cacuciu Nou", "sat", createAdresaCompleta("sat Cacuciu Nou, comuna Măgești, judetul BIHOR, România", "sat Cacuciu Nou, comuna Magesti, judetul BIHOR, Romania")),
    createLoc("Dobricionești", "sat", createAdresaCompleta("sat Dobricionești, comuna Măgești, judetul BIHOR, România", "sat Dobricionesti, comuna Magesti, judetul BIHOR, Romania")),
    createLoc("Gălășeni", "sat", createAdresaCompleta("sat Gălășeni, comuna Măgești, judetul BIHOR, România", "sat Galaseni, comuna Magesti, judetul BIHOR, Romania")),
    createLoc("Josani", "sat", createAdresaCompleta("sat Josani, comuna Măgești, judetul BIHOR, România", "sat Josani, comuna Magesti, judetul BIHOR, Romania")),
    createLoc("Ortiteag", "sat", createAdresaCompleta("sat Ortiteag, comuna Măgești, judetul BIHOR, România", "sat Ortiteag, comuna Magesti, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Măgești, judetul BIHOR, România", "comuna Magesti, judetul BIHOR, Romania")),
createComuna("Nojorid", [
    createLoc("Nojorid", "sat", createAdresaCompleta("sat Nojorid, comuna Nojorid, judetul BIHOR, România", "sat Nojorid, comuna Nojorid, judetul BIHOR, Romania")),
    createLoc("Apateu", "sat", createAdresaCompleta("sat Apateu, comuna Nojorid, judetul BIHOR, România", "sat Apateu, comuna Nojorid, judetul BIHOR, Romania")),
    createLoc("Chișirid", "sat", createAdresaCompleta("sat Chișirid, comuna Nojorid, judetul BIHOR, România", "sat Chisirid, comuna Nojorid, judetul BIHOR, Romania")),
    createLoc("Leș", "sat", createAdresaCompleta("sat Leș, comuna Nojorid, judetul BIHOR, România", "sat Les, comuna Nojorid, judetul BIHOR, Romania")),
    createLoc("Livada de Bihor", "sat", createAdresaCompleta("sat Livada de Bihor, comuna Nojorid, judetul BIHOR, România", "sat Livada de Bihor, comuna Nojorid, judetul BIHOR, Romania")),
    createLoc("Păușa", "sat", createAdresaCompleta("sat Păușa, comuna Nojorid, judetul BIHOR, România", "sat Pausa, comuna Nojorid, judetul BIHOR, Romania")),
    createLoc("Șauaieu", "sat", createAdresaCompleta("sat Șauaieu, comuna Nojorid, judetul BIHOR, România", "sat Sauaieu, comuna Nojorid, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Nojorid, judetul BIHOR, România", "comuna Nojorid, judetul BIHOR, Romania")),
createComuna("Olcea", [
    createLoc("Olcea", "sat", createAdresaCompleta("sat Olcea, comuna Olcea, judetul BIHOR, România", "sat Olcea, comuna Olcea, judetul BIHOR, Romania")),
    createLoc("Călacea", "sat", createAdresaCompleta("sat Călacea, comuna Olcea, judetul BIHOR, România", "sat Calacea, comuna Olcea, judetul BIHOR, Romania")),
    createLoc("Hodișel", "sat", createAdresaCompleta("sat Hodișel, comuna Olcea, judetul BIHOR, România", "sat Hodisel, comuna Olcea, judetul BIHOR, Romania")),
    createLoc("Ucuriș", "sat", createAdresaCompleta("sat Ucuriș, comuna Olcea, judetul BIHOR, România", "sat Ucuris, comuna Olcea, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Olcea, judetul BIHOR, România", "comuna Olcea, judetul BIHOR, Romania")),
createComuna("Oșorhei", [
    createLoc("Oșorhei", "sat", createAdresaCompleta("sat Oșorhei, comuna Oșorhei, judetul BIHOR, România", "sat Osorhei, comuna Osorhei, judetul BIHOR, Romania")),
    createLoc("Alparea", "sat", createAdresaCompleta("sat Alparea, comuna Oșorhei, judetul BIHOR, România", "sat Alparea, comuna Osorhei, judetul BIHOR, Romania")),
    createLoc("Cheriu", "sat", createAdresaCompleta("sat Cheriu, comuna Oșorhei, judetul BIHOR, România", "sat Cheriu, comuna Osorhei, judetul BIHOR, Romania")),
    createLoc("Felcheriu", "sat", createAdresaCompleta("sat Felcheriu, comuna Oșorhei, judetul BIHOR, România", "sat Felcheriu, comuna Osorhei, judetul BIHOR, Romania")),
    createLoc("Fughiu", "sat", createAdresaCompleta("sat Fughiu, comuna Oșorhei, judetul BIHOR, România", "sat Fughiu, comuna Osorhei, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Oșorhei, judetul BIHOR, România", "comuna Osorhei, judetul BIHOR, Romania")),
createComuna("Paleu", [
    createLoc("Paleu", "sat", createAdresaCompleta("sat Paleu, comuna Paleu, judetul BIHOR, România", "sat Paleu, comuna Paleu, judetul BIHOR, Romania")),
    createLoc("Săldăbagiu de Munte", "sat", createAdresaCompleta("sat Săldăbagiu de Munte, comuna Paleu, judetul BIHOR, România", "sat Saldabagiu de Munte, comuna Paleu, judetul BIHOR, Romania")),
    createLoc("Uileacu de Munte", "sat", createAdresaCompleta("sat Uileacu de Munte, comuna Paleu, judetul BIHOR, România", "sat Uileacu de Munte, comuna Paleu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Paleu, judetul BIHOR, România", "comuna Paleu, judetul BIHOR, Romania")),
createComuna("Petreu", [
    createLoc("Petreu", "sat", createAdresaCompleta("sat Petreu, comuna Petreu, judetul BIHOR, România", "sat Petreu, comuna Petreu, judetul BIHOR, Romania")),
    createLoc("Abrămuț", "sat", createAdresaCompleta("sat Abrămuț, comuna Petreu, judetul BIHOR, România", "sat Abramut, comuna Petreu, judetul BIHOR, Romania")),
    createLoc("Crestur", "sat", createAdresaCompleta("sat Crestur, comuna Petreu, judetul BIHOR, România", "sat Crestur, comuna Petreu, judetul BIHOR, Romania")),
    createLoc("Făncica", "sat", createAdresaCompleta("sat Făncica, comuna Petreu, judetul BIHOR, România", "sat Fancica, comuna Petreu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Petreu, judetul BIHOR, România", "comuna Petreu, judetul BIHOR, Romania")),
createComuna("Pietroasa", [
    createLoc("Pietroasa", "sat", createAdresaCompleta("sat Pietroasa, comuna Pietroasa, judetul BIHOR, România", "sat Pietroasa, comuna Pietroasa, judetul BIHOR, Romania")),
    createLoc("Chișcău", "sat", createAdresaCompleta("sat Chișcău, comuna Pietroasa, judetul BIHOR, România", "sat Chiscau, comuna Pietroasa, judetul BIHOR, Romania")),
    createLoc("Cociuba Mică", "sat", createAdresaCompleta("sat Cociuba Mică, comuna Pietroasa, judetul BIHOR, România", "sat Cociuba Mica, comuna Pietroasa, judetul BIHOR, Romania")),
    createLoc("Giulești", "sat", createAdresaCompleta("sat Giulești, comuna Pietroasa, judetul BIHOR, România", "sat Giulesti, comuna Pietroasa, judetul BIHOR, Romania")),
    createLoc("Gurani", "sat", createAdresaCompleta("sat Gurani, comuna Pietroasa, judetul BIHOR, România", "sat Gurani, comuna Pietroasa, judetul BIHOR, Romania")),
    createLoc("Măgura", "sat", createAdresaCompleta("sat Măgura, comuna Pietroasa, judetul BIHOR, România", "sat Magura, comuna Pietroasa, judetul BIHOR, Romania")),
    createLoc("Moțești", "sat", createAdresaCompleta("sat Moțești, comuna Pietroasa, judetul BIHOR, România", "sat Motesti, comuna Pietroasa, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Pietroasa, judetul BIHOR, România", "comuna Pietroasa, judetul BIHOR, Romania")),
createComuna("Pocola", [
    createLoc("Pocola", "sat", createAdresaCompleta("sat Pocola, comuna Pocola, judetul BIHOR, România", "sat Pocola, comuna Pocola, judetul BIHOR, Romania")),
    createLoc("Feneriș", "sat", createAdresaCompleta("sat Feneriș, comuna Pocola, judetul BIHOR, România", "sat Feneris, comuna Pocola, judetul BIHOR, Romania")),
    createLoc("Petrani", "sat", createAdresaCompleta("sat Petrani, comuna Pocola, judetul BIHOR, România", "sat Petrani, comuna Pocola, judetul BIHOR, Romania")),
    createLoc("Poietari", "sat", createAdresaCompleta("sat Poietari, comuna Pocola, judetul BIHOR, România", "sat Poietari, comuna Pocola, judetul BIHOR, Romania")),
    createLoc("Sânmartin de Beiuș", "sat", createAdresaCompleta("sat Sânmartin de Beiuș, comuna Pocola, judetul BIHOR, România", "sat Sanmartin de Beius, comuna Pocola, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Pocola, judetul BIHOR, România", "comuna Pocola, judetul BIHOR, Romania")),
createComuna("Pomezeu", [
    createLoc("Pomezeu", "sat", createAdresaCompleta("sat Pomezeu, comuna Pomezeu, judetul BIHOR, România", "sat Pomezeu, comuna Pomezeu, judetul BIHOR, Romania")),
    createLoc("Câmpani de Pomezeu", "sat", createAdresaCompleta("sat Câmpani de Pomezeu, comuna Pomezeu, judetul BIHOR, România", "sat Campani de Pomezeu, comuna Pomezeu, judetul BIHOR, Romania")),
    createLoc("Coșdeni", "sat", createAdresaCompleta("sat Coșdeni, comuna Pomezeu, judetul BIHOR, România", "sat Cosdeni, comuna Pomezeu, judetul BIHOR, Romania")),
    createLoc("Hidiș", "sat", createAdresaCompleta("sat Hidiș, comuna Pomezeu, judetul BIHOR, România", "sat Hidis, comuna Pomezeu, judetul BIHOR, Romania")),
    createLoc("Lacu Sărat", "sat", createAdresaCompleta("sat Lacu Sărat, comuna Pomezeu, judetul BIHOR, România", "sat Lacu Sarat, comuna Pomezeu, judetul BIHOR, Romania")),
    createLoc("Sitani", "sat", createAdresaCompleta("sat Sitani, comuna Pomezeu, judetul BIHOR, România", "sat Sitani, comuna Pomezeu, judetul BIHOR, Romania")),
    createLoc("Spinuș de Pomezeu", "sat", createAdresaCompleta("sat Spinuș de Pomezeu, comuna Pomezeu, judetul BIHOR, România", "sat Spinus de Pomezeu, comuna Pomezeu, judetul BIHOR, Romania")),
    createLoc("Vălani de Pomezeu", "sat", createAdresaCompleta("sat Vălani de Pomezeu, comuna Pomezeu, judetul BIHOR, România", "sat Valani de Pomezeu, comuna Pomezeu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Pomezeu, judetul BIHOR, România", "comuna Pomezeu, judetul BIHOR, Romania")),
createComuna("Popești", [
    createLoc("Popești", "sat", createAdresaCompleta("sat Popești, comuna Popești, judetul BIHOR, România", "sat Popesti, comuna Popesti, judetul BIHOR, Romania")),
    createLoc("Bistra", "sat", createAdresaCompleta("sat Bistra, comuna Popești, judetul BIHOR, România", "sat Bistra, comuna Popesti, judetul BIHOR, Romania")),
    createLoc("Budoi", "sat", createAdresaCompleta("sat Budoi, comuna Popești, judetul BIHOR, România", "sat Budoi, comuna Popesti, judetul BIHOR, Romania")),
    createLoc("Cuzap", "sat", createAdresaCompleta("sat Cuzap, comuna Popești, judetul BIHOR, România", "sat Cuzap, comuna Popesti, judetul BIHOR, Romania")),
    createLoc("Varviz", "sat", createAdresaCompleta("sat Varviz, comuna Popești, judetul BIHOR, România", "sat Varviz, comuna Popesti, judetul BIHOR, Romania")),
    createLoc("Vărzari", "sat", createAdresaCompleta("sat Vărzari, comuna Popești, judetul BIHOR, România", "sat Varzari, comuna Popesti, judetul BIHOR, Romania")),
    createLoc("Voivozi", "sat", createAdresaCompleta("sat Voivozi, comuna Popești, judetul BIHOR, România", "sat Voivozi, comuna Popesti, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Popești, judetul BIHOR, România", "comuna Popesti, judetul BIHOR, Romania")),
createComuna("Răbăgani", [
    createLoc("Răbăgani", "sat", createAdresaCompleta("sat Răbăgani, comuna Răbăgani, judetul BIHOR, România", "sat Rabagani, comuna Rabagani, judetul BIHOR, Romania")),
    createLoc("Albești", "sat", createAdresaCompleta("sat Albești, comuna Răbăgani, judetul BIHOR, România", "sat Albesti, comuna Rabagani, judetul BIHOR, Romania")),
    createLoc("Brătești", "sat", createAdresaCompleta("sat Brătești, comuna Răbăgani, judetul BIHOR, România", "sat Bratesti, comuna Rabagani, judetul BIHOR, Romania")),
    createLoc("Săliște de Pomezeu", "sat", createAdresaCompleta("sat Săliște de Pomezeu, comuna Răbăgani, judetul BIHOR, România", "sat Saliste de Pomezeu, comuna Rabagani, judetul BIHOR, Romania")),
    createLoc("Săucani", "sat", createAdresaCompleta("sat Săucani, comuna Răbăgani, judetul BIHOR, România", "sat Saucani, comuna Rabagani, judetul BIHOR, Romania")),
    createLoc("Vărășeni", "sat", createAdresaCompleta("sat Vărășeni, comuna Răbăgani, judetul BIHOR, România", "sat Varaseni, comuna Rabagani, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Răbăgani, judetul BIHOR, România", "comuna Rabagani, judetul BIHOR, Romania")),
createComuna("Remetea", [
    createLoc("Remetea", "sat", createAdresaCompleta("sat Remetea, comuna Remetea, judetul BIHOR, România", "sat Remetea, comuna Remetea, judetul BIHOR, Romania")),
    createLoc("Drăgoteni", "sat", createAdresaCompleta("sat Drăgoteni, comuna Remetea, judetul BIHOR, România", "sat Dragoteni, comuna Remetea, judetul BIHOR, Romania")),
    createLoc("Meziad", "sat", createAdresaCompleta("sat Meziad, comuna Remetea, judetul BIHOR, România", "sat Meziad, comuna Remetea, judetul BIHOR, Romania")),
    createLoc("Petreasa", "sat", createAdresaCompleta("sat Petreasa, comuna Remetea, judetul BIHOR, România", "sat Petreasa, comuna Remetea, judetul BIHOR, Romania")),
    createLoc("Șoimuș", "sat", createAdresaCompleta("sat Șoimuș, comuna Remetea, judetul BIHOR, România", "sat Soimus, comuna Remetea, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Remetea, judetul BIHOR, România", "comuna Remetea, judetul BIHOR, Romania")),
createComuna("Rieni", [
    createLoc("Rieni", "sat", createAdresaCompleta("sat Rieni, comuna Rieni, judetul BIHOR, România", "sat Rieni, comuna Rieni, judetul BIHOR, Romania")),
    createLoc("Cucuceni", "sat", createAdresaCompleta("sat Cucuceni, comuna Rieni, judetul BIHOR, România", "sat Cucuceni, comuna Rieni, judetul BIHOR, Romania")),
    createLoc("Ghighișeni", "sat", createAdresaCompleta("sat Ghighișeni, comuna Rieni, judetul BIHOR, România", "sat Ghighiseni, comuna Rieni, judetul BIHOR, Romania")),
    createLoc("Petrileni", "sat", createAdresaCompleta("sat Petrileni, comuna Rieni, judetul BIHOR, România", "sat Petrileni, comuna Rieni, judetul BIHOR, Romania")),
    createLoc("Sudrigiu", "sat", createAdresaCompleta("sat Sudrigiu, comuna Rieni, judetul BIHOR, România", "sat Sudrigiu, comuna Rieni, judetul BIHOR, Romania")),
    createLoc("Valea de Jos", "sat", createAdresaCompleta("sat Valea de Jos, comuna Rieni, judetul BIHOR, România", "sat Valea de Jos, comuna Rieni, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Rieni, judetul BIHOR, România", "comuna Rieni, judetul BIHOR, Romania")),
createComuna("Roșia", [
    createLoc("Roșia", "sat", createAdresaCompleta("sat Roșia, comuna Roșia, judetul BIHOR, România", "sat Rosia, comuna Rosia, judetul BIHOR, Romania")),
    createLoc("Lazuri", "sat", createAdresaCompleta("sat Lazuri, comuna Roșia, judetul BIHOR, România", "sat Lazuri, comuna Rosia, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Roșia, judetul BIHOR, România", "comuna Rosia, judetul BIHOR, Romania")),
createComuna("Roșiori", [
    createLoc("Roșiori", "sat", createAdresaCompleta("sat Roșiori, comuna Roșiori, judetul BIHOR, România", "sat Rosiori, comuna Rosiori, judetul BIHOR, Romania")),
    createLoc("Mihai Bravu", "sat", createAdresaCompleta("sat Mihai Bravu, comuna Roșiori, judetul BIHOR, România", "sat Mihai Bravu, comuna Rosiori, judetul BIHOR, Romania")),
    createLoc("Vaida", "sat", createAdresaCompleta("sat Vaida, comuna Roșiori, judetul BIHOR, România", "sat Vaida, comuna Rosiori, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Roșiori, judetul BIHOR, România", "comuna Rosiori, judetul BIHOR, Romania")),
createComuna("Săcădat", [
    createLoc("Săcădat", "sat", createAdresaCompleta("sat Săcădat, comuna Săcădat, judetul BIHOR, România", "sat Sacadat, comuna Sacadat, judetul BIHOR, Romania")),
    createLoc("Borșa", "sat", createAdresaCompleta("sat Borșa, comuna Săcădat, judetul BIHOR, România", "sat Borsa, comuna Sacadat, judetul BIHOR, Romania")),
    createLoc("Săbolciu", "sat", createAdresaCompleta("sat Săbolciu, comuna Săcădat, judetul BIHOR, România", "sat Sabolciu, comuna Sacadat, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Săcădat, judetul BIHOR, România", "comuna Sacadat, judetul BIHOR, Romania")),
createComuna("Sălacea", [
    createLoc("Sălacea", "sat", createAdresaCompleta("sat Sălacea, comuna Sălacea, judetul BIHOR, România", "sat Salacea, comuna Salacea, judetul BIHOR, Romania")),
    createLoc("Otomani", "sat", createAdresaCompleta("sat Otomani, comuna Sălacea, judetul BIHOR, România", "sat Otomani, comuna Salacea, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Sălacea, judetul BIHOR, România", "comuna Salacea, judetul BIHOR, Romania")),
createComuna("Sălard", [
    createLoc("Sălard", "sat", createAdresaCompleta("sat Sălard, comuna Sălard, judetul BIHOR, România", "sat Salard, comuna Salard, judetul BIHOR, Romania")),
    createLoc("Hodoș", "sat", createAdresaCompleta("sat Hodoș, comuna Sălard, judetul BIHOR, România", "sat Hodos, comuna Salard, judetul BIHOR, Romania")),
    createLoc("Sântimreu", "sat", createAdresaCompleta("sat Sântimreu, comuna Sălard, judetul BIHOR, România", "sat Santimreu, comuna Salard, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Sălard, judetul BIHOR, România", "comuna Salard, judetul BIHOR, Romania")),
createComuna("Sâniob", [
    createLoc("Sâniob", "sat", createAdresaCompleta("sat Sâniob, comuna Sâniob, judetul BIHOR, România", "sat Saniob, comuna Saniob, judetul BIHOR, Romania")),
    createLoc("Cenaloș", "sat", createAdresaCompleta("sat Cenaloș, comuna Sâniob, judetul BIHOR, România", "sat Cenalos, comuna Saniob, judetul BIHOR, Romania")),
    createLoc("Ciuhoi", "sat", createAdresaCompleta("sat Ciuhoi, comuna Sâniob, judetul BIHOR, România", "sat Ciuhoi, comuna Saniob, judetul BIHOR, Romania")),
    createLoc("Sfârnaș", "sat", createAdresaCompleta("sat Sfârnaș, comuna Sâniob, judetul BIHOR, România", "sat Sfarnas, comuna Saniob, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Sâniob, judetul BIHOR, România", "comuna Saniob, judetul BIHOR, Romania")),
createComuna("Sânnicolau Român", [
    createLoc("Sânnicolau Român", "sat", createAdresaCompleta("sat Sânnicolau Român, comuna Sânnicolau Român, judetul BIHOR, România", "sat Sannicolau Roman, comuna Sannicolau Roman, judetul BIHOR, Romania")),
    createLoc("Berechiu", "sat", createAdresaCompleta("sat Berechiu, comuna Sânnicolau Român, judetul BIHOR, România", "sat Berechiu, comuna Sannicolau Roman, judetul BIHOR, Romania")),
    createLoc("Roit", "sat", createAdresaCompleta("sat Roit, comuna Sânnicolau Român, judetul BIHOR, România", "sat Roit, comuna Sannicolau Roman, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Sânnicolau Român, judetul BIHOR, România", "comuna Sannicolau Roman, judetul BIHOR, Romania")),
createComuna("Sâmbăta", [
    createLoc("Sâmbăta", "sat", createAdresaCompleta("sat Sâmbăta, comuna Sâmbăta, judetul BIHOR, România", "sat Sambata, comuna Sambata, judetul BIHOR, Romania")),
    createLoc("Copăceni", "sat", createAdresaCompleta("sat Copăceni, comuna Sâmbăta, judetul BIHOR, România", "sat Copaceni, comuna Sambata, judetul BIHOR, Romania")),
    createLoc("Ogești", "sat", createAdresaCompleta("sat Ogești, comuna Sâmbăta, judetul BIHOR, România", "sat Ogesti, comuna Sambata, judetul BIHOR, Romania")),
    createLoc("Rogoz", "sat", createAdresaCompleta("sat Rogoz, comuna Sâmbăta, judetul BIHOR, România", "sat Rogoz, comuna Sambata, judetul BIHOR, Romania")),
    createLoc("Rotărești", "sat", createAdresaCompleta("sat Rotărești, comuna Sâmbăta, judetul BIHOR, România", "sat Rotaresti, comuna Sambata, judetul BIHOR, Romania")),
    createLoc("Zăvoiu", "sat", createAdresaCompleta("sat Zăvoiu, comuna Sâmbăta, judetul BIHOR, România", "sat Zavoiu, comuna Sambata, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Sâmbăta, judetul BIHOR, România", "comuna Sambata, judetul BIHOR, Romania")),
createComuna("Sânmartin", [
    createLoc("Sânmartin", "sat", createAdresaCompleta("sat Sânmartin, comuna Sânmartin, judetul BIHOR, România", "sat Sanmartin, comuna Sanmartin, judetul BIHOR, Romania")),
    createLoc("Betfia", "sat", createAdresaCompleta("sat Betfia, comuna Sânmartin, judetul BIHOR, România", "sat Betfia, comuna Sanmartin, judetul BIHOR, Romania")),
    createLoc("Cihei", "sat", createAdresaCompleta("sat Cihei, comuna Sânmartin, judetul BIHOR, România", "sat Cihei, comuna Sanmartin, judetul BIHOR, Romania")),
    createLoc("Cordău", "sat", createAdresaCompleta("sat Cordău, comuna Sânmartin, judetul BIHOR, România", "sat Cordau, comuna Sanmartin, judetul BIHOR, Romania")),
    createLoc("Haieu", "sat", createAdresaCompleta("sat Haieu, comuna Sânmartin, judetul BIHOR, România", "sat Haieu, comuna Sanmartin, judetul BIHOR, Romania")),
    createLoc("Rontău", "sat", createAdresaCompleta("sat Rontău, comuna Sânmartin, judetul BIHOR, România", "sat Rontau, comuna Sanmartin, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Sânmartin, judetul BIHOR, România", "comuna Sanmartin, judetul BIHOR, Romania")),
createComuna("Sântandrei", [
    createLoc("Sântandrei", "sat", createAdresaCompleta("sat Sântandrei, comuna Sântandrei, judetul BIHOR, România", "sat Santandrei, comuna Santandrei, judetul BIHOR, Romania")),
    createLoc("Palota", "sat", createAdresaCompleta("sat Palota, comuna Sântandrei, judetul BIHOR, România", "sat Palota, comuna Santandrei, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Sântandrei, judetul BIHOR, România", "comuna Santandrei, judetul BIHOR, Romania")),
createComuna("Sârbi", [
    createLoc("Sârbi", "sat", createAdresaCompleta("sat Sârbi, comuna Sârbi, judetul BIHOR, România", "sat Sarbi, comuna Sarbi, judetul BIHOR, Romania")),
    createLoc("Almașu Mic", "sat", createAdresaCompleta("sat Almașu Mic, comuna Sârbi, judetul BIHOR, România", "sat Almasu Mic, comuna Sarbi, judetul BIHOR, Romania")),
    createLoc("Burzuc", "sat", createAdresaCompleta("sat Burzuc, comuna Sârbi, judetul BIHOR, România", "sat Burzuc, comuna Sarbi, judetul BIHOR, Romania")),
    createLoc("Chioag", "sat", createAdresaCompleta("sat Chioag, comuna Sârbi, judetul BIHOR, România", "sat Chioag, comuna Sarbi, judetul BIHOR, Romania")),
    createLoc("Fegernic", "sat", createAdresaCompleta("sat Fegernic, comuna Sârbi, judetul BIHOR, România", "sat Fegernic, comuna Sarbi, judetul BIHOR, Romania")),
    createLoc("Fegernicu Nou", "sat", createAdresaCompleta("sat Fegernicu Nou, comuna Sârbi, judetul BIHOR, România", "sat Fegernicu Nou, comuna Sarbi, judetul BIHOR, Romania")),
    createLoc("Sarcău", "sat", createAdresaCompleta("sat Sarcău, comuna Sârbi, judetul BIHOR, România", "sat Sarcau, comuna Sarbi, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Sârbi, judetul BIHOR, România", "comuna Sarbi, judetul BIHOR, Romania")),
createComuna("Spinuș", [
    createLoc("Spinuș", "sat", createAdresaCompleta("sat Spinuș, comuna Spinuș, judetul BIHOR, România", "sat Spinus, comuna Spinus, judetul BIHOR, Romania")),
    createLoc("Ciulești", "sat", createAdresaCompleta("sat Ciulești, comuna Spinuș, judetul BIHOR, România", "sat Ciulesti, comuna Spinus, judetul BIHOR, Romania")),
    createLoc("Gurbești", "sat", createAdresaCompleta("sat Gurbești, comuna Spinuș, judetul BIHOR, România", "sat Gurbesti, comuna Spinus, judetul BIHOR, Romania")),
    createLoc("Nădar", "sat", createAdresaCompleta("sat Nădar, comuna Spinuș, judetul BIHOR, România", "sat Nadar, comuna Spinus, judetul BIHOR, Romania")),
    createLoc("Săliște", "sat", createAdresaCompleta("sat Săliște, comuna Spinuș, judetul BIHOR, România", "sat Saliste, comuna Spinus, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Spinuș, judetul BIHOR, România", "comuna Spinus, judetul BIHOR, Romania")),
createComuna("Suplacu de Barcău", [
    createLoc("Suplacu de Barcău", "sat", createAdresaCompleta("sat Suplacu de Barcău, comuna Suplacu de Barcău, judetul BIHOR, România", "sat Suplacu de Barcau, comuna Suplacu de Barcau, judetul BIHOR, Romania")),
    createLoc("Borumlaca", "sat", createAdresaCompleta("sat Borumlaca, comuna Suplacu de Barcău, judetul BIHOR, România", "sat Borumlaca, comuna Suplacu de Barcau, judetul BIHOR, Romania")),
    createLoc("Dolea", "sat", createAdresaCompleta("sat Dolea, comuna Suplacu de Barcău, judetul BIHOR, România", "sat Dolea, comuna Suplacu de Barcau, judetul BIHOR, Romania")),
    createLoc("Foglaș", "sat", createAdresaCompleta("sat Foglaș, comuna Suplacu de Barcău, judetul BIHOR, România", "sat Foglas, comuna Suplacu de Barcau, judetul BIHOR, Romania")),
    createLoc("Valea Cerului", "sat", createAdresaCompleta("sat Valea Cerului, comuna Suplacu de Barcău, judetul BIHOR, România", "sat Valea Cerului, comuna Suplacu de Barcau, judetul BIHOR, Romania")),
    createLoc("Vâlcelele", "sat", createAdresaCompleta("sat Vâlcelele, comuna Suplacu de Barcău, judetul BIHOR, România", "sat Valcelele, comuna Suplacu de Barcau, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Suplacu de Barcău, judetul BIHOR, România", "comuna Suplacu de Barcau, judetul BIHOR, Romania")),
createComuna("Șimian", [
    createLoc("Șimian", "sat", createAdresaCompleta("sat Șimian, comuna Șimian, judetul BIHOR, România", "sat Simian, comuna Simian, judetul BIHOR, Romania")),
    createLoc("Șilindru", "sat", createAdresaCompleta("sat Șilindru, comuna Șimian, judetul BIHOR, România", "sat Silindru, comuna Simian, judetul BIHOR, Romania")),
    createLoc("Voivozi", "sat", createAdresaCompleta("sat Voivozi, comuna Șimian, judetul BIHOR, România", "sat Voivozi, comuna Simian, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Șimian, judetul BIHOR, România", "comuna Simian, judetul BIHOR, Romania")),
createComuna("Șinteu", [
    createLoc("Șinteu", "sat", createAdresaCompleta("sat Șinteu, comuna Șinteu, judetul BIHOR, România", "sat Sinteu, comuna Sinteu, judetul BIHOR, Romania")),
    createLoc("Huta Voivozi", "sat", createAdresaCompleta("sat Huta Voivozi, comuna Șinteu, judetul BIHOR, România", "sat Huta Voivozi, comuna Sinteu, judetul BIHOR, Romania")),
    createLoc("Socet", "sat", createAdresaCompleta("sat Socet, comuna Șinteu, judetul BIHOR, România", "sat Socet, comuna Sinteu, judetul BIHOR, Romania")),
    createLoc("Valea Târnei", "sat", createAdresaCompleta("sat Valea Târnei, comuna Șinteu, judetul BIHOR, România", "sat Valea Tarnei, comuna Sinteu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Șinteu, judetul BIHOR, România", "comuna Sinteu, judetul BIHOR, Romania")),
createComuna("Șoimi", [
    createLoc("Șoimi", "sat", createAdresaCompleta("sat Șoimi, comuna Șoimi, judetul BIHOR, România", "sat Soimi, comuna Soimi, judetul BIHOR, Romania")),
    createLoc("Borz", "sat", createAdresaCompleta("sat Borz, comuna Șoimi, judetul BIHOR, România", "sat Borz, comuna Soimi, judetul BIHOR, Romania")),
    createLoc("Codru", "sat", createAdresaCompleta("sat Codru, comuna Șoimi, judetul BIHOR, România", "sat Codru, comuna Soimi, judetul BIHOR, Romania")),
    createLoc("Dumbrăvița de Codru", "sat", createAdresaCompleta("sat Dumbrăvița de Codru, comuna Șoimi, judetul BIHOR, România", "sat Dumbravita de Codru, comuna Soimi, judetul BIHOR, Romania")),
    createLoc("Poclușa de Beiuș", "sat", createAdresaCompleta("sat Poclușa de Beiuș, comuna Șoimi, judetul BIHOR, România", "sat Poclusa de Beius, comuna Soimi, judetul BIHOR, Romania")),
    createLoc("Sânnicolau de Beiuș", "sat", createAdresaCompleta("sat Sânnicolau de Beiuș, comuna Șoimi, judetul BIHOR, România", "sat Sannicolau de Beius, comuna Soimi, judetul BIHOR, Romania")),
    createLoc("Ursad", "sat", createAdresaCompleta("sat Ursad, comuna Șoimi, judetul BIHOR, România", "sat Ursad, comuna Soimi, judetul BIHOR, Romania")),
    createLoc("Urviș de Beiuș", "sat", createAdresaCompleta("sat Urviș de Beiuș, comuna Șoimi, judetul BIHOR, România", "sat Urvis de Beius, comuna Soimi, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Șoimi, judetul BIHOR, România", "comuna Soimi, judetul BIHOR, Romania")),
createComuna("Șuncuiuș", [
    createLoc("Șuncuiuș", "sat", createAdresaCompleta("sat Șuncuiuș, comuna Șuncuiuș, judetul BIHOR, România", "sat Suncuius, comuna Suncuius, judetul BIHOR, Romania")),
    createLoc("Bălnaca", "sat", createAdresaCompleta("sat Bălnaca, comuna Șuncuiuș, judetul BIHOR, România", "sat Balnaca, comuna Suncuius, judetul BIHOR, Romania")),
    createLoc("Bălnaca-Groși", "sat", createAdresaCompleta("sat Bălnaca-Groși, comuna Șuncuiuș, judetul BIHOR, România", "sat Balnaca-Grosi, comuna Suncuius, judetul BIHOR, Romania")),
    createLoc("Zece Hotare", "sat", createAdresaCompleta("sat Zece Hotare, comuna Șuncuiuș, judetul BIHOR, România", "sat Zece Hotare, comuna Suncuius, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Șuncuiuș, judetul BIHOR, România", "comuna Suncuius, judetul BIHOR, Romania")),
createComuna("Tarcea", [
    createLoc("Tarcea", "sat", createAdresaCompleta("sat Tarcea, comuna Tarcea, judetul BIHOR, România", "sat Tarcea, comuna Tarcea, judetul BIHOR, Romania")),
    createLoc("Adoni", "sat", createAdresaCompleta("sat Adoni, comuna Tarcea, judetul BIHOR, România", "sat Adoni, comuna Tarcea, judetul BIHOR, Romania")),
    createLoc("Galoșpetreu", "sat", createAdresaCompleta("sat Galoșpetreu, comuna Tarcea, judetul BIHOR, România", "sat Galospetreu, comuna Tarcea, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Tarcea, judetul BIHOR, România", "comuna Tarcea, judetul BIHOR, Romania")),
createComuna("Tămășeu", [
    createLoc("Tămășeu", "sat", createAdresaCompleta("sat Tămășeu, comuna Tămășeu, judetul BIHOR, România", "sat Tamaseu, comuna Tamaseu, judetul BIHOR, Romania")),
    createLoc("Niuved", "sat", createAdresaCompleta("sat Niuved, comuna Tămășeu, judetul BIHOR, România", "sat Niuved, comuna Tamaseu, judetul BIHOR, Romania")),
    createLoc("Parhida", "sat", createAdresaCompleta("sat Parhida, comuna Tămășeu, judetul BIHOR, România", "sat Parhida, comuna Tamaseu, judetul BIHOR, Romania")),
    createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Tămășeu, judetul BIHOR, România", "sat Satu Nou, comuna Tamaseu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Tămășeu, judetul BIHOR, România", "comuna Tamaseu, judetul BIHOR, Romania")),
createComuna("Tărcaia", [
    createLoc("Tărcaia", "sat", createAdresaCompleta("sat Tărcaia, comuna Tărcaia, judetul BIHOR, România", "sat Tarcaia, comuna Tarcaia, judetul BIHOR, Romania")),
    createLoc("Mierag", "sat", createAdresaCompleta("sat Mierag, comuna Tărcaia, judetul BIHOR, România", "sat Mierag, comuna Tarcaia, judetul BIHOR, Romania")),
    createLoc("Tărcăița", "sat", createAdresaCompleta("sat Tărcăița, comuna Tărcaia, judetul BIHOR, România", "sat Tarcaita, comuna Tarcaia, judetul BIHOR, Romania")),
    createLoc("Totoreni", "sat", createAdresaCompleta("sat Totoreni, comuna Tărcaia, judetul BIHOR, România", "sat Totoreni, comuna Tarcaia, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Tărcaia, judetul BIHOR, România", "comuna Tarcaia, judetul BIHOR, Romania")),
createComuna("Tăuteu", [
    createLoc("Tăuteu", "sat", createAdresaCompleta("sat Tăuteu, comuna Tăuteu, judetul BIHOR, România", "sat Tauteu, comuna Tauteu, judetul BIHOR, Romania")),
    createLoc("Bogei", "sat", createAdresaCompleta("sat Bogei, comuna Tăuteu, judetul BIHOR, România", "sat Bogei, comuna Tauteu, judetul BIHOR, Romania")),
    createLoc("Chiribiș", "sat", createAdresaCompleta("sat Chiribiș, comuna Tăuteu, judetul BIHOR, România", "sat Chiribis, comuna Tauteu, judetul BIHOR, Romania")),
    createLoc("Ciutelec", "sat", createAdresaCompleta("sat Ciutelec, comuna Tăuteu, judetul BIHOR, România", "sat Ciutelec, comuna Tauteu, judetul BIHOR, Romania")),
    createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Tăuteu, judetul BIHOR, România", "sat Poiana, comuna Tauteu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Tăuteu, judetul BIHOR, România", "comuna Tauteu, judetul BIHOR, Romania")),
createComuna("Tileagd", [
    createLoc("Tileagd", "sat", createAdresaCompleta("sat Tileagd, comuna Tileagd, judetul BIHOR, România", "sat Tileagd, comuna Tileagd, judetul BIHOR, Romania")),
    createLoc("Bălaia", "sat", createAdresaCompleta("sat Bălaia, comuna Tileagd, judetul BIHOR, România", "sat Balaia, comuna Tileagd, judetul BIHOR, Romania")),
    createLoc("Călătani", "sat", createAdresaCompleta("sat Călătani, comuna Tileagd, judetul BIHOR, România", "sat Calatani, comuna Tileagd, judetul BIHOR, Romania")),
    createLoc("Poșoloaca", "sat", createAdresaCompleta("sat Poșoloaca, comuna Tileagd, judetul BIHOR, România", "sat Posoloaca, comuna Tileagd, judetul BIHOR, Romania")),
    createLoc("Tilecuș", "sat", createAdresaCompleta("sat Tilecuș, comuna Tileagd, judetul BIHOR, România", "sat Tilecus, comuna Tileagd, judetul BIHOR, Romania")),
    createLoc("Uileacu de Criș", "sat", createAdresaCompleta("sat Uileacu de Criș, comuna Tileagd, judetul BIHOR, România", "sat Uileacu de Cris, comuna Tileagd, judetul BIHOR, Romania")),
]),
createComuna("Tinca", [
    createLoc("Tinca", "sat", createAdresaCompleta("sat Tinca, comuna Tinca, judetul BIHOR, România", "sat Tinca, comuna Tinca, judetul BIHOR, Romania")),
    createLoc("Belfir", "sat", createAdresaCompleta("sat Belfir, comuna Tinca, judetul BIHOR, România", "sat Belfir, comuna Tinca, judetul BIHOR, Romania")),
    createLoc("Girișu Negru", "sat", createAdresaCompleta("sat Girișu Negru, comuna Tinca, judetul BIHOR, România", "sat Girisu Negru, comuna Tinca, judetul BIHOR, Romania")),
    createLoc("Gurbediu", "sat", createAdresaCompleta("sat Gurbediu, comuna Tinca, judetul BIHOR, România", "sat Gurbediu, comuna Tinca, judetul BIHOR, Romania")),
    createLoc("Râpa", "sat", createAdresaCompleta("sat Râpa, comuna Tinca, judetul BIHOR, România", "sat Rapa, comuna Tinca, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Tinca, judetul BIHOR, România", "comuna Tinca, judetul BIHOR, Romania")),
createComuna("Toboliu", [
    createLoc("Toboliu", "sat", createAdresaCompleta("sat Toboliu, comuna Toboliu, judetul BIHOR, România", "sat Toboliu, comuna Toboliu, judetul BIHOR, Romania")),
    createLoc("Cheresig", "sat", createAdresaCompleta("sat Cheresig, comuna Toboliu, judetul BIHOR, România", "sat Cheresig, comuna Toboliu, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Toboliu, judetul BIHOR, România", "comuna Toboliu, judetul BIHOR, Romania")),
createComuna("Tulca", [
    createLoc("Tulca", "sat", createAdresaCompleta("sat Tulca, comuna Tulca, judetul BIHOR, România", "sat Tulca, comuna Tulca, judetul BIHOR, Romania")),
    createLoc("Căuașd", "sat", createAdresaCompleta("sat Căuașd, comuna Tulca, judetul BIHOR, România", "sat Cauasd, comuna Tulca, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Tulca, judetul BIHOR, România", "comuna Tulca, judetul BIHOR, Romania")),
createComuna("Țețchea", [
    createLoc("Țețchea", "sat", createAdresaCompleta("sat Țețchea, comuna Țețchea, judetul BIHOR, România", "sat Tetchea, comuna Tetchea, judetul BIHOR, Romania")),
    createLoc("Hotar", "sat", createAdresaCompleta("sat Hotar, comuna Țețchea, judetul BIHOR, România", "sat Hotar, comuna Tetchea, judetul BIHOR, Romania")),
    createLoc("Subpiatră", "sat", createAdresaCompleta("sat Subpiatră, comuna Țețchea, judetul BIHOR, România", "sat Subpiatra, comuna Tetchea, judetul BIHOR, Romania")),
    createLoc("Telechiu", "sat", createAdresaCompleta("sat Telechiu, comuna Țețchea, judetul BIHOR, România", "sat Telechiu, comuna Tetchea, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Țețchea, judetul BIHOR, România", "comuna Tetchea, judetul BIHOR, Romania")),
createComuna("Uileacu de Beiuș", [
    createLoc("Uileacu de Beiuș", "sat", createAdresaCompleta("sat Uileacu de Beiuș, comuna Uileacu de Beiuș, judetul BIHOR, România", "sat Uileacu de Beius, comuna Uileacu de Beius, judetul BIHOR, Romania")),
    createLoc("Forău", "sat", createAdresaCompleta("sat Forău, comuna Uileacu de Beiuș, judetul BIHOR, România", "sat Forau, comuna Uileacu de Beius, judetul BIHOR, Romania")),
    createLoc("Prisaca", "sat", createAdresaCompleta("sat Prisaca, comuna Uileacu de Beiuș, judetul BIHOR, România", "sat Prisaca, comuna Uileacu de Beius, judetul BIHOR, Romania")),
    createLoc("Vălanii de Beiuș", "sat", createAdresaCompleta("sat Vălanii de Beiuș, comuna Uileacu de Beiuș, judetul BIHOR, România", "sat Valanii de Beius, comuna Uileacu de Beius, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Uileacu de Beiuș, judetul BIHOR, România", "comuna Uileacu de Beius, judetul BIHOR, Romania")),
createComuna("Vadu Crișului", [
    createLoc("Vadu Crișului", "sat", createAdresaCompleta("sat Vadu Crișului, comuna Vadu Crișului, judetul BIHOR, România", "sat Vadu Crisului, comuna Vadu Crisului, judetul BIHOR, Romania")),
    createLoc("Birtin", "sat", createAdresaCompleta("sat Birtin, comuna Vadu Crișului, judetul BIHOR, România", "sat Birtin, comuna Vadu Crisului, judetul BIHOR, Romania")),
    createLoc("Tomnatic", "sat", createAdresaCompleta("sat Tomnatic, comuna Vadu Crișului, judetul BIHOR, România", "sat Tomnatic, comuna Vadu Crisului, judetul BIHOR, Romania")),
    createLoc("Topa de Criș", "sat", createAdresaCompleta("sat Topa de Criș, comuna Vadu Crișului, judetul BIHOR, România", "sat Topa de Cris, comuna Vadu Crisului, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Vadu Crișului, judetul BIHOR, România", "comuna Vadu Crisului, judetul BIHOR, Romania")),
createComuna("Viișoara", [
    createLoc("Viișoara", "sat", createAdresaCompleta("sat Viișoara, comuna Viișoara, judetul BIHOR, România", "sat Viisoara, comuna Viisoara, judetul BIHOR, Romania")),
    createLoc("Izvoarele", "sat", createAdresaCompleta("sat Izvoarele, comuna Viișoara, judetul BIHOR, România", "sat Izvoarele, comuna Viisoara, judetul BIHOR, Romania")),
    createLoc("Pădureni", "sat", createAdresaCompleta("sat Pădureni, comuna Viișoara, judetul BIHOR, România", "sat Padureni, comuna Viisoara, judetul BIHOR, Romania")),
    createLoc("Reghea", "sat", createAdresaCompleta("sat Reghea, comuna Viișoara, judetul BIHOR, România", "sat Reghea, comuna Viisoara, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Viișoara, judetul BIHOR, România", "comuna Viisoara, judetul BIHOR, Romania")),
createComuna("Vârciorog", [
    createLoc("Vârciorog", "sat", createAdresaCompleta("sat Vârciorog, comuna Vârciorog, judetul BIHOR, România", "sat Varciorog, comuna Varciorog, judetul BIHOR, Romania")),
    createLoc("Fâșca", "sat", createAdresaCompleta("sat Fâșca, comuna Vârciorog, judetul BIHOR, România", "sat Fasca, comuna Varciorog, judetul BIHOR, Romania")),
    createLoc("Surducel", "sat", createAdresaCompleta("sat Surducel, comuna Vârciorog, judetul BIHOR, România", "sat Surducel, comuna Varciorog, judetul BIHOR, Romania")),
    createLoc("Șerghiș", "sat", createAdresaCompleta("sat Șerghiș, comuna Vârciorog, judetul BIHOR, România", "sat Serghis, comuna Varciorog, judetul BIHOR, Romania")),
], createAdresaCompleta("comuna Vârciorog, judetul BIHOR, România", "comuna Varciorog, judetul BIHOR, Romania")),


			  
			
];
?>