<?php
$comune =[
createComuna("Abram", [
    createLoc("Abram", "sat", createAdresaCompleta("sat Abram, comuna Abram, judetul BIHOR, România")),
    createLoc("Cohani", "sat", createAdresaCompleta("sat Cohani, comuna Abram, judetul BIHOR, România")),
    createLoc("Dijir", "sat", createAdresaCompleta("sat Dijir, comuna Abram, judetul BIHOR, România")),
    createLoc("Iteu", "sat", createAdresaCompleta("sat Iteu, comuna Abram, judetul BIHOR, România")),
    createLoc("Iteu Nou", "sat", createAdresaCompleta("sat Iteu Nou, comuna Abram, judetul BIHOR, România")),
    createLoc("Margine", "sat", createAdresaCompleta("sat Margine, comuna Abram, judetul BIHOR, România")),
    createLoc("Satu Barbă", "sat", createAdresaCompleta("sat Satu Barbă, comuna Abram, judetul BIHOR, România")),
    createLoc("Suiug", "sat", createAdresaCompleta("sat Suiug, comuna Abram, judetul BIHOR, România")),
], createAdresaCompleta("comuna Abram, judetul BIHOR, România")),

createComuna("Aștileu", [
    createLoc("Aștileu", "sat", createAdresaCompleta("sat Aștileu, comuna Aștileu, judetul BIHOR, România")),
    createLoc("Călățea", "sat", createAdresaCompleta("sat Călățea, comuna Aștileu, judetul BIHOR, România")),
    createLoc("Chistag", "sat", createAdresaCompleta("sat Chistag, comuna Aștileu, judetul BIHOR, România")),
    createLoc("Peștere", "sat", createAdresaCompleta("sat Peștere, comuna Aștileu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Aștileu, judetul BIHOR, România")),
createComuna("Aușeu", [
    createLoc("Aușeu", "sat", createAdresaCompleta("sat Aușeu, comuna Aușeu, judetul BIHOR, România")),
    createLoc("Cacuciu Vechi", "sat", createAdresaCompleta("sat Cacuciu Vechi, comuna Aușeu, judetul BIHOR, România")),
    createLoc("Codrișoru", "sat", createAdresaCompleta("sat Codrișoru, comuna Aușeu, judetul BIHOR, România")),
    createLoc("Gheghie", "sat", createAdresaCompleta("sat Gheghie, comuna Aușeu, judetul BIHOR, România")),
    createLoc("Groși", "sat", createAdresaCompleta("sat Groși, comuna Aușeu, judetul BIHOR, România")),
    createLoc("Luncșoara", "sat", createAdresaCompleta("sat Luncșoara, comuna Aușeu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Aușeu, judetul BIHOR, România")),
createComuna("Avram Iancu", [
    createLoc("Avram Iancu", "sat", createAdresaCompleta("sat Avram Iancu, comuna Avram Iancu, judetul BIHOR, România")),
    createLoc("Ant", "sat", createAdresaCompleta("sat Ant, comuna Avram Iancu, judetul BIHOR, România")),
    createLoc("Tămașda", "sat", createAdresaCompleta("sat Tămașda, comuna Avram Iancu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Avram Iancu, judetul BIHOR, România")),
createComuna("Balc", [
    createLoc("Balc", "sat", createAdresaCompleta("sat Balc, comuna Balc, judetul BIHOR, România")),
    createLoc("Almașu Mare", "sat", createAdresaCompleta("sat Almașu Mare, comuna Balc, judetul BIHOR, România")),
    createLoc("Almașu Mic", "sat", createAdresaCompleta("sat Almașu Mic, comuna Balc, judetul BIHOR, România")),
    createLoc("Ghida", "sat", createAdresaCompleta("sat Ghida, comuna Balc, judetul BIHOR, România")),
    createLoc("Săldăbagiu de Barcău", "sat", createAdresaCompleta("sat Săldăbagiu de Barcău, comuna Balc, judetul BIHOR, România")),
], createAdresaCompleta("comuna Balc, judetul BIHOR, România")),
createComuna("Batăr", [
    createLoc("Batăr", "sat", createAdresaCompleta("sat Batăr, comuna Batăr, judetul BIHOR, România")),
    createLoc("Arpășel", "sat", createAdresaCompleta("sat Arpășel, comuna Batăr, judetul BIHOR, România")),
    createLoc("Talpoș", "sat", createAdresaCompleta("sat Talpoș, comuna Batăr, judetul BIHOR, România")),
    createLoc("Tăut", "sat", createAdresaCompleta("sat Tăut, comuna Batăr, judetul BIHOR, România")),
], createAdresaCompleta("comuna Batăr, judetul BIHOR, România")),
createComuna("Biharia", [
    createLoc("Biharia", "sat", createAdresaCompleta("sat Biharia, comuna Biharia, judetul BIHOR, România")),
    createLoc("Cauaceu", "sat", createAdresaCompleta("sat Cauaceu, comuna Biharia, judetul BIHOR, România")),
], createAdresaCompleta("comuna Biharia, judetul BIHOR, România")),
createComuna("Boianu Mare", [
    createLoc("Boianu Mare", "sat", createAdresaCompleta("sat Boianu Mare, comuna Boianu Mare, judetul BIHOR, România")),
    createLoc("Corboaia", "sat", createAdresaCompleta("sat Corboaia, comuna Boianu Mare, judetul BIHOR, România")),
    createLoc("Huta", "sat", createAdresaCompleta("sat Huta, comuna Boianu Mare, judetul BIHOR, România")),
    createLoc("Păgaia", "sat", createAdresaCompleta("sat Păgaia, comuna Boianu Mare, judetul BIHOR, România")),
    createLoc("Rugea", "sat", createAdresaCompleta("sat Rugea, comuna Boianu Mare, judetul BIHOR, România")),
], createAdresaCompleta("comuna Boianu Mare, judetul BIHOR, România")),
createComuna("Borod", [
    createLoc("Borod", "sat", createAdresaCompleta("sat Borod, comuna Borod, judetul BIHOR, România")),
    createLoc("Borozel", "sat", createAdresaCompleta("sat Borozel, comuna Borod, judetul BIHOR, România")),
    createLoc("Cetea", "sat", createAdresaCompleta("sat Cetea, comuna Borod, judetul BIHOR, România")),
    createLoc("Cornițel", "sat", createAdresaCompleta("sat Cornițel, comuna Borod, judetul BIHOR, România")),
    createLoc("Șerani", "sat", createAdresaCompleta("sat Șerani, comuna Borod, judetul BIHOR, România")),
    createLoc("Valea Mare de Criș", "sat", createAdresaCompleta("sat Valea Mare de Criș, comuna Borod, judetul BIHOR, România")),
], createAdresaCompleta("comuna Borod, judetul BIHOR, România")),

createComuna("Borș", [
    createLoc("Borș", "sat", createAdresaCompleta("sat Borș, comuna Borș, judetul BIHOR, România")),
    createLoc("Santăul Mare", "sat", createAdresaCompleta("sat Santăul Mare, comuna Borș, judetul BIHOR, România")),
    createLoc("Santăul Mic", "sat", createAdresaCompleta("sat Santăul Mic, comuna Borș, judetul BIHOR, România")),
    createLoc("Sântion", "sat", createAdresaCompleta("sat Sântion, comuna Borș, judetul BIHOR, România")),
], createAdresaCompleta("comuna Borș, judetul BIHOR, România")),
createComuna("Bratca", [
    createLoc("Bratca", "sat", createAdresaCompleta("sat Bratca, comuna Bratca, judetul BIHOR, România")),
    createLoc("Beznea", "sat", createAdresaCompleta("sat Beznea, comuna Bratca, judetul BIHOR, România")),
    createLoc("Damiș", "sat", createAdresaCompleta("sat Damiș, comuna Bratca, judetul BIHOR, România")),
    createLoc("Lorău", "sat", createAdresaCompleta("sat Lorău, comuna Bratca, judetul BIHOR, România")),
    createLoc("Ponoară", "sat", createAdresaCompleta("sat Ponoară, comuna Bratca, judetul BIHOR, România")),
    createLoc("Valea Crișului", "sat", createAdresaCompleta("sat Valea Crișului, comuna Bratca, judetul BIHOR, România")),
], createAdresaCompleta("comuna Bratca, judetul BIHOR, România")),
createComuna("Brusturi", [
    createLoc("Brusturi", "sat", createAdresaCompleta("sat Brusturi, comuna Brusturi, judetul BIHOR, România")),
    createLoc("Cuieșd", "sat", createAdresaCompleta("sat Cuieșd, comuna Brusturi, judetul BIHOR, România")),
    createLoc("Loranta", "sat", createAdresaCompleta("sat Loranta, comuna Brusturi, judetul BIHOR, România")),
    createLoc("Orvișele", "sat", createAdresaCompleta("sat Orvișele, comuna Brusturi, judetul BIHOR, România")),
    createLoc("Păulești", "sat", createAdresaCompleta("sat Păulești, comuna Brusturi, judetul BIHOR, România")),
    createLoc("Picleu", "sat", createAdresaCompleta("sat Picleu, comuna Brusturi, judetul BIHOR, România")),
    createLoc("Țigăneștii de Criș", "sat", createAdresaCompleta("sat Țigăneștii de Criș, comuna Brusturi, judetul BIHOR, România")),
    createLoc("Varasău", "sat", createAdresaCompleta("sat Varasău, comuna Brusturi, judetul BIHOR, România")),
], createAdresaCompleta("comuna Brusturi, judetul BIHOR, România")),
createComuna("Budureasa", [
    createLoc("Budureasa", "sat", createAdresaCompleta("sat Budureasa, comuna Budureasa, judetul BIHOR, România")),
    createLoc("Burda", "sat", createAdresaCompleta("sat Burda, comuna Budureasa, judetul BIHOR, România")),
    createLoc("Saca", "sat", createAdresaCompleta("sat Saca, comuna Budureasa, judetul BIHOR, România")),
    createLoc("Săliște de Beiuș", "sat", createAdresaCompleta("sat Săliște de Beiuș, comuna Budureasa, judetul BIHOR, România")),
    createLoc("Teleac", "sat", createAdresaCompleta("sat Teleac, comuna Budureasa, judetul BIHOR, România")),
], createAdresaCompleta("comuna Budureasa, judetul BIHOR, România")),
createComuna("Buduslău", [
    createLoc("Buduslău", "sat", createAdresaCompleta("sat Buduslău, comuna Buduslău, judetul BIHOR, România")),
    createLoc("Albiș", "sat", createAdresaCompleta("sat Albiș, comuna Buduslău, judetul BIHOR, România")),
], createAdresaCompleta("comuna Buduslău, judetul BIHOR, România")),
createComuna("Bulz", [
    createLoc("Bulz", "sat", createAdresaCompleta("sat Bulz, comuna Bulz, judetul BIHOR, România")),
    createLoc("Munteni", "sat", createAdresaCompleta("sat Munteni, comuna Bulz, judetul BIHOR, România")),
    createLoc("Remeți", "sat", createAdresaCompleta("sat Remeți, comuna Bulz, judetul BIHOR, România")),
], createAdresaCompleta("comuna Bulz, judetul BIHOR, România")),
createComuna("Buntești", [
    createLoc("Buntești", "sat", createAdresaCompleta("sat Buntești, comuna Buntești, judetul BIHOR, România")),
    createLoc("Brădet", "sat", createAdresaCompleta("sat Brădet, comuna Buntești, judetul BIHOR, România")),
    createLoc("Dumbrăvani", "sat", createAdresaCompleta("sat Dumbrăvani, comuna Buntești, judetul BIHOR, România")),
    createLoc("Ferice", "sat", createAdresaCompleta("sat Ferice, comuna Buntești, judetul BIHOR, România")),
    createLoc("Lelești", "sat", createAdresaCompleta("sat Lelești, comuna Buntești, judetul BIHOR, România")),
    createLoc("Poienii de Jos", "sat", createAdresaCompleta("sat Poienii de Jos, comuna Buntești, judetul BIHOR, România")),
    createLoc("Poienii de Sus", "sat", createAdresaCompleta("sat Poienii de Sus, comuna Buntești, judetul BIHOR, România")),
    createLoc("Săud", "sat", createAdresaCompleta("sat Săud, comuna Buntești, judetul BIHOR, România")),
    createLoc("Stâncești", "sat", createAdresaCompleta("sat Stâncești, comuna Buntești, judetul BIHOR, România")),
], createAdresaCompleta("comuna Buntești, judetul BIHOR, România")),
createComuna("Căbești", [
    createLoc("Căbești", "sat", createAdresaCompleta("sat Căbești, comuna Căbești, judetul BIHOR, România")),
    createLoc("Goila", "sat", createAdresaCompleta("sat Goila, comuna Căbești, judetul BIHOR, România")),
    createLoc("Gurbești", "sat", createAdresaCompleta("sat Gurbești, comuna Căbești, judetul BIHOR, România")),
    createLoc("Josani", "sat", createAdresaCompleta("sat Josani, comuna Căbești, judetul BIHOR, România")),
    createLoc("Sohodol", "sat", createAdresaCompleta("sat Sohodol, comuna Căbești, judetul BIHOR, România")),
], createAdresaCompleta("comuna Căbești, judetul BIHOR, România")),
createComuna("Căpâlna", [
    createLoc("Căpâlna", "sat", createAdresaCompleta("sat Căpâlna, comuna Căpâlna, judetul BIHOR, România")),
    createLoc("Ginta", "sat", createAdresaCompleta("sat Ginta, comuna Căpâlna, judetul BIHOR, România")),
    createLoc("Rohani", "sat", createAdresaCompleta("sat Rohani, comuna Căpâlna, judetul BIHOR, România")),
    createLoc("Săldăbagiu Mic", "sat", createAdresaCompleta("sat Săldăbagiu Mic, comuna Căpâlna, judetul BIHOR, România")),
    createLoc("Suplacu de Tinca", "sat", createAdresaCompleta("sat Suplacu de Tinca, comuna Căpâlna, judetul BIHOR, România")),
], createAdresaCompleta("comuna Căpâlna, judetul BIHOR, România")),
createComuna("Cărpinet", [
    createLoc("Cărpinet", "sat", createAdresaCompleta("sat Cărpinet, comuna Cărpinet, judetul BIHOR, România")),
    createLoc("Călugări", "sat", createAdresaCompleta("sat Călugări, comuna Cărpinet, judetul BIHOR, România")),
    createLoc("Izbuc", "sat", createAdresaCompleta("sat Izbuc, comuna Cărpinet, judetul BIHOR, România")),
    createLoc("Leheceni", "sat", createAdresaCompleta("sat Leheceni, comuna Cărpinet, judetul BIHOR, România")),
], createAdresaCompleta("comuna Cărpinet, judetul BIHOR, România")),
createComuna("Cefa", [
    createLoc("Cefa", "sat", createAdresaCompleta("sat Cefa, comuna Cefa, judetul BIHOR, România")),
    createLoc("Ateaș", "sat", createAdresaCompleta("sat Ateaș, comuna Cefa, judetul BIHOR, România")),
    createLoc("Inand", "sat", createAdresaCompleta("sat Inand, comuna Cefa, judetul BIHOR, România")),
], createAdresaCompleta("comuna Cefa, judetul BIHOR, România")),
createComuna("Ceica", [
    createLoc("Ceica", "sat", createAdresaCompleta("sat Ceica, comuna Ceica, judetul BIHOR, România")),
    createLoc("Bucium", "sat", createAdresaCompleta("sat Bucium, comuna Ceica, judetul BIHOR, România")),
    createLoc("Ceișoara", "sat", createAdresaCompleta("sat Ceișoara, comuna Ceica, judetul BIHOR, România")),
    createLoc("Corbești", "sat", createAdresaCompleta("sat Corbești, comuna Ceica, judetul BIHOR, România")),
    createLoc("Cotiglet", "sat", createAdresaCompleta("sat Cotiglet, comuna Ceica, judetul BIHOR, România")),
    createLoc("Dușești", "sat", createAdresaCompleta("sat Dușești, comuna Ceica, judetul BIHOR, România")),
    createLoc("Incești", "sat", createAdresaCompleta("sat Incești, comuna Ceica, judetul BIHOR, România")),
], createAdresaCompleta("comuna Ceica, judetul BIHOR, România")),
createComuna("Cetariu", [
    createLoc("Cetariu", "sat", createAdresaCompleta("sat Cetariu, comuna Cetariu, judetul BIHOR, România")),
    createLoc("Șișterea", "sat", createAdresaCompleta("sat Șișterea, comuna Cetariu, judetul BIHOR, România")),
    createLoc("Șușturogi", "sat", createAdresaCompleta("sat Șușturogi, comuna Cetariu, judetul BIHOR, România")),
    createLoc("Tăutelec", "sat", createAdresaCompleta("sat Tăutelec, comuna Cetariu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Cetariu, judetul BIHOR, România")),
createComuna("Cherechiu", [
    createLoc("Cherechiu", "sat", createAdresaCompleta("sat Cherechiu, comuna Cherechiu, judetul BIHOR, România")),
    createLoc("Cheșereu", "sat", createAdresaCompleta("sat Cheșereu, comuna Cherechiu, judetul BIHOR, România")),
    createLoc("Târgușor", "sat", createAdresaCompleta("sat Târgușor, comuna Cherechiu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Cherechiu, judetul BIHOR, România")),
createComuna("Chișlaz", [
    createLoc("Chișlaz", "sat", createAdresaCompleta("sat Chișlaz, comuna Chișlaz, judetul BIHOR, România")),
    createLoc("Chiraleu", "sat", createAdresaCompleta("sat Chiraleu, comuna Chișlaz, judetul BIHOR, România")),
    createLoc("Hăucești", "sat", createAdresaCompleta("sat Hăucești, comuna Chișlaz, judetul BIHOR, România")),
    createLoc("Mișca", "sat", createAdresaCompleta("sat Mișca, comuna Chișlaz, judetul BIHOR, România")),
    createLoc("Poclușa de Barcău", "sat", createAdresaCompleta("sat Poclușa de Barcău, comuna Chișlaz, judetul BIHOR, România")),
    createLoc("Sărsig", "sat", createAdresaCompleta("sat Sărsig, comuna Chișlaz, judetul BIHOR, România")),
    createLoc("Sânlazăr", "sat", createAdresaCompleta("sat Sânlazăr, comuna Chișlaz, judetul BIHOR, România")),
], createAdresaCompleta("comuna Chișlaz, judetul BIHOR, România")),
createComuna("Ciumeghiu", [
    createLoc("Ciumeghiu", "sat", createAdresaCompleta("sat Ciumeghiu, comuna Ciumeghiu, judetul BIHOR, România")),
    createLoc("Boiu", "sat", createAdresaCompleta("sat Boiu, comuna Ciumeghiu, judetul BIHOR, România")),
    createLoc("Ghiorac", "sat", createAdresaCompleta("sat Ghiorac, comuna Ciumeghiu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Ciumeghiu, judetul BIHOR, România")),
createComuna("Câmpani", [
    createLoc("Câmpani", "sat", createAdresaCompleta("sat Câmpani, comuna Câmpani, judetul BIHOR, România")),
    createLoc("Fânațe", "sat", createAdresaCompleta("sat Fânațe, comuna Câmpani, judetul BIHOR, România")),
    createLoc("Hârsești", "sat", createAdresaCompleta("sat Hârsești, comuna Câmpani, judetul BIHOR, România")),
    createLoc("Sighiștel", "sat", createAdresaCompleta("sat Sighiștel, comuna Câmpani, judetul BIHOR, România")),
    createLoc("Valea de Sus", "sat", createAdresaCompleta("sat Valea de Sus, comuna Câmpani, judetul BIHOR, România")),
], createAdresaCompleta("comuna Câmpani, judetul BIHOR, România")),
createComuna("Cociuba Mare", [
    createLoc("Cociuba Mare", "sat", createAdresaCompleta("sat Cociuba Mare, comuna Cociuba Mare, judetul BIHOR, România")),
    createLoc("Cărăsău", "sat", createAdresaCompleta("sat Cărăsău, comuna Cociuba Mare, judetul BIHOR, România")),
    createLoc("Cheșa", "sat", createAdresaCompleta("sat Cheșa, comuna Cociuba Mare, judetul BIHOR, România")),
    createLoc("Petid", "sat", createAdresaCompleta("sat Petid, comuna Cociuba Mare, judetul BIHOR, România")),
], createAdresaCompleta("comuna Cociuba Mare, judetul BIHOR, România")),
createComuna("Copăcel", [
    createLoc("Copăcel", "sat", createAdresaCompleta("sat Copăcel, comuna Copăcel, judetul BIHOR, România")),
    createLoc("Bucuroaia", "sat", createAdresaCompleta("sat Bucuroaia, comuna Copăcel, judetul BIHOR, România")),
    createLoc("Chijic", "sat", createAdresaCompleta("sat Chijic, comuna Copăcel, judetul BIHOR, România")),
    createLoc("Poiana Tășad", "sat", createAdresaCompleta("sat Poiana Tășad, comuna Copăcel, judetul BIHOR, România")),
    createLoc("Sărand", "sat", createAdresaCompleta("sat Sărand, comuna Copăcel, judetul BIHOR, România")),
    createLoc("Surduc", "sat", createAdresaCompleta("sat Surduc, comuna Copăcel, judetul BIHOR, România")),
], createAdresaCompleta("comuna Copăcel, judetul BIHOR, România")),
createComuna("Criștioru de Jos", [
    createLoc("Criștioru de Jos", "sat", createAdresaCompleta("sat Criștioru de Jos, comuna Criștioru de Jos, judetul BIHOR, România")),
    createLoc("Bâlc", "sat", createAdresaCompleta("sat Bâlc, comuna Criștioru de Jos, judetul BIHOR, România")),
    createLoc("Criștioru de Sus", "sat", createAdresaCompleta("sat Criștioru de Sus, comuna Criștioru de Jos, judetul BIHOR, România")),
    createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Criștioru de Jos, judetul BIHOR, România")),
    createLoc("Săliște de Vașcău", "sat", createAdresaCompleta("sat Săliște de Vașcău, comuna Criștioru de Jos, judetul BIHOR, România")),
], createAdresaCompleta("comuna Criștioru de Jos, judetul BIHOR, România")),
createComuna("Curățele", [
    createLoc("Curățele", "sat", createAdresaCompleta("sat Curățele, comuna Curățele, judetul BIHOR, România")),
    createLoc("Beiușele", "sat", createAdresaCompleta("sat Beiușele, comuna Curățele, judetul BIHOR, România")),
    createLoc("Cresuia", "sat", createAdresaCompleta("sat Cresuia, comuna Curățele, judetul BIHOR, România")),
    createLoc("Nimăiești", "sat", createAdresaCompleta("sat Nimăiești, comuna Curățele, judetul BIHOR, România")),
    createLoc("Pocioveliște", "sat", createAdresaCompleta("sat Pocioveliște, comuna Curățele, judetul BIHOR, România")),
]),
createComuna("Curtuișeni", [
    createLoc("Curtuișeni", "sat", createAdresaCompleta("sat Curtuișeni, comuna Curtuișeni, judetul BIHOR, România")),
    createLoc("Vășad", "sat", createAdresaCompleta("sat Vășad, comuna Curtuișeni, judetul BIHOR, România")),
], createAdresaCompleta("comuna Curtuișeni, judetul BIHOR, România")),
createComuna("Derna", [
    createLoc("Derna", "sat", createAdresaCompleta("sat Derna, comuna Derna, judetul BIHOR, România")),
    createLoc("Dernișoara", "sat", createAdresaCompleta("sat Dernișoara, comuna Derna, judetul BIHOR, România")),
    createLoc("Sacalasău", "sat", createAdresaCompleta("sat Sacalasău, comuna Derna, judetul BIHOR, România")),
    createLoc("Sacalasău Nou", "sat", createAdresaCompleta("sat Sacalasău Nou, comuna Derna, judetul BIHOR, România")),
    createLoc("Tria", "sat", createAdresaCompleta("sat Tria, comuna Derna, judetul BIHOR, România")),
], createAdresaCompleta("comuna Derna, judetul BIHOR, România")),
createComuna("Diosig", [
    createLoc("Diosig", "sat", createAdresaCompleta("sat Diosig, comuna Diosig, judetul BIHOR, România")),
    createLoc("Ianca", "sat", createAdresaCompleta("sat Ianca, comuna Diosig, judetul BIHOR, România")),
], createAdresaCompleta("comuna Diosig, judetul BIHOR, România")),
createComuna("Dobrești", [
    createLoc("Dobrești", "sat", createAdresaCompleta("sat Dobrești, comuna Dobrești, judetul BIHOR, România")),
    createLoc("Cornișești", "sat", createAdresaCompleta("sat Cornișești, comuna Dobrești, judetul BIHOR, România")),
    createLoc("Crâncești", "sat", createAdresaCompleta("sat Crâncești, comuna Dobrești, judetul BIHOR, România")),
    createLoc("Hidișel", "sat", createAdresaCompleta("sat Hidișel, comuna Dobrești, judetul BIHOR, România")),
    createLoc("Luncasprie", "sat", createAdresaCompleta("sat Luncasprie, comuna Dobrești, judetul BIHOR, România")),
    createLoc("Răcaș", "sat", createAdresaCompleta("sat Răcaș, comuna Dobrești, judetul BIHOR, România")),
    createLoc("Topa de Jos", "sat", createAdresaCompleta("sat Topa de Jos, comuna Dobrești, judetul BIHOR, România")),
    createLoc("Topa de Sus", "sat", createAdresaCompleta("sat Topa de Sus, comuna Dobrești, judetul BIHOR, România")),
], createAdresaCompleta("comuna Dobrești, judetul BIHOR, România")),
createComuna("Drăgănești", [
    createLoc("Drăgănești", "sat", createAdresaCompleta("sat Drăgănești, comuna Drăgănești, judetul BIHOR, România")),
    createLoc("Belejeni", "sat", createAdresaCompleta("sat Belejeni, comuna Drăgănești, judetul BIHOR, România")),
    createLoc("Grădinari", "sat", createAdresaCompleta("sat Grădinari, comuna Drăgănești, judetul BIHOR, România")),
    createLoc("Livada Beiușului", "sat", createAdresaCompleta("sat Livada Beiușului, comuna Drăgănești, judetul BIHOR, România")),
    createLoc("Mizieș", "sat", createAdresaCompleta("sat Mizieș, comuna Drăgănești, judetul BIHOR, România")),
    createLoc("Păcălești", "sat", createAdresaCompleta("sat Păcălești, comuna Drăgănești, judetul BIHOR, România")),
    createLoc("Păntășești", "sat", createAdresaCompleta("sat Păntășești, comuna Drăgănești, judetul BIHOR, România")),
    createLoc("Șebiș", "sat", createAdresaCompleta("sat Șebiș, comuna Drăgănești, judetul BIHOR, România")),
    createLoc("Talpe", "sat", createAdresaCompleta("sat Talpe, comuna Drăgănești, judetul BIHOR, România")),
    createLoc("Țigăneștii de Beiuș", "sat", createAdresaCompleta("sat Țigăneștii de Beiuș, comuna Drăgănești, judetul BIHOR, România")),
], createAdresaCompleta("comuna Drăgănești, judetul BIHOR, România")),
createComuna("Drăgești", [
    createLoc("Drăgești", "sat", createAdresaCompleta("sat Drăgești, comuna Drăgești, judetul BIHOR, România")),
    createLoc("Dicănești", "sat", createAdresaCompleta("sat Dicănești, comuna Drăgești, judetul BIHOR, România")),
    createLoc("Stracoș", "sat", createAdresaCompleta("sat Stracoș, comuna Drăgești, judetul BIHOR, România")),
    createLoc("Tășad", "sat", createAdresaCompleta("sat Tășad, comuna Drăgești, judetul BIHOR, România")),
    createLoc("Topești", "sat", createAdresaCompleta("sat Topești, comuna Drăgești, judetul BIHOR, România")),
], createAdresaCompleta("comuna Drăgești, judetul BIHOR, România")),
createComuna("Finiș", [
    createLoc("Finiș", "sat", createAdresaCompleta("sat Finiș, comuna Finiș, judetul BIHOR, România")),
    createLoc("Brusturi", "sat", createAdresaCompleta("sat Brusturi, comuna Finiș, judetul BIHOR, România")),
    createLoc("Fiziș", "sat", createAdresaCompleta("sat Fiziș, comuna Finiș, judetul BIHOR, România")),
    createLoc("Ioaniș", "sat", createAdresaCompleta("sat Ioaniș, comuna Finiș, judetul BIHOR, România")),
    createLoc("Șuncuiș", "sat", createAdresaCompleta("sat Șuncuiș, comuna Finiș, judetul BIHOR, România")),
], createAdresaCompleta("comuna Finiș, judetul BIHOR, România")),
createComuna("Gepiu", [
    createLoc("Gepiu", "sat", createAdresaCompleta("sat Gepiu, comuna Gepiu, judetul BIHOR, România")),
    createLoc("Bicaci", "sat", createAdresaCompleta("sat Bicaci, comuna Gepiu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Gepiu, judetul BIHOR, România")),
createComuna("Girișu de Criș", [
    createLoc("Girișu de Criș", "sat", createAdresaCompleta("sat Girișu de Criș, comuna Girișu de Criș, judetul BIHOR, România")),
    createLoc("Tărian", "sat", createAdresaCompleta("sat Tărian, comuna Girișu de Criș, judetul BIHOR, România")),
], createAdresaCompleta("comuna Girișu de Criș, judetul BIHOR, România")),
createComuna("Hidișelu de Sus", [
    createLoc("Hidișelu de Sus", "sat", createAdresaCompleta("sat Hidișelu de Sus, comuna Hidișelu de Sus, judetul BIHOR, România")),
    createLoc("Hidișelu de Jos", "sat", createAdresaCompleta("sat Hidișelu de Jos, comuna Hidișelu de Sus, judetul BIHOR, România")),
    createLoc("Mierlău", "sat", createAdresaCompleta("sat Mierlău, comuna Hidișelu de Sus, judetul BIHOR, România")),
    createLoc("Sântelec", "sat", createAdresaCompleta("sat Sântelec, comuna Hidișelu de Sus, judetul BIHOR, România")),
    createLoc("Șumugiu", "sat", createAdresaCompleta("sat Șumugiu, comuna Hidișelu de Sus, judetul BIHOR, România")),
], createAdresaCompleta("comuna Hidișelu de Sus, judetul BIHOR, România")),
createComuna("Holod", [
    createLoc("Holod", "sat", createAdresaCompleta("sat Holod, comuna Holod, judetul BIHOR, România")),
    createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, comuna Holod, judetul BIHOR, România")),
    createLoc("Dumbrăvița", "sat", createAdresaCompleta("sat Dumbrăvița, comuna Holod, judetul BIHOR, România")),
    createLoc("Forosig", "sat", createAdresaCompleta("sat Forosig, comuna Holod, judetul BIHOR, România")),
    createLoc("Hodiș", "sat", createAdresaCompleta("sat Hodiș, comuna Holod, judetul BIHOR, România")),
    createLoc("Lupoaia", "sat", createAdresaCompleta("sat Lupoaia, comuna Holod, judetul BIHOR, România")),
    createLoc("Valea Mare de Codru", "sat", createAdresaCompleta("sat Valea Mare de Codru, comuna Holod, judetul BIHOR, România")),
    createLoc("Vintere", "sat", createAdresaCompleta("sat Vintere, comuna Holod, judetul BIHOR, România")),
], createAdresaCompleta("comuna Holod, judetul BIHOR, România")),
createComuna("Husasău de Tinca", [
    createLoc("Husasău de Tinca", "sat", createAdresaCompleta("sat Husasău de Tinca, comuna Husasău de Tinca, judetul BIHOR, România")),
    createLoc("Fonău", "sat", createAdresaCompleta("sat Fonău, comuna Husasău de Tinca, judetul BIHOR, România")),
    createLoc("Miersig", "sat", createAdresaCompleta("sat Miersig, comuna Husasău de Tinca, judetul BIHOR, România")),
    createLoc("Oșand", "sat", createAdresaCompleta("sat Oșand, comuna Husasău de Tinca, judetul BIHOR, România")),
    createLoc("Sititelec", "sat", createAdresaCompleta("sat Sititelec, comuna Husasău de Tinca, judetul BIHOR, România")),
], createAdresaCompleta("comuna Husasău de Tinca, judetul BIHOR, România")),
createComuna("Ineu", [
    createLoc("Ineu", "sat", createAdresaCompleta("sat Ineu, comuna Ineu, judetul BIHOR, România")),
    createLoc("Botean", "sat", createAdresaCompleta("sat Botean, comuna Ineu, judetul BIHOR, România")),
    createLoc("Husasău de Criș", "sat", createAdresaCompleta("sat Husasău de Criș, comuna Ineu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Ineu, judetul BIHOR, România")),
createComuna("Lazuri de Beiuș", [
    createLoc("Lazuri de Beiuș", "sat", createAdresaCompleta("sat Lazuri de Beiuș, comuna Lazuri de Beiuș, judetul BIHOR, România")),
    createLoc("Băleni", "sat", createAdresaCompleta("sat Băleni, comuna Lazuri de Beiuș, judetul BIHOR, România")),
    createLoc("Cusuiuș", "sat", createAdresaCompleta("sat Cusuiuș, comuna Lazuri de Beiuș, judetul BIHOR, România")),
    createLoc("Hinchiriș", "sat", createAdresaCompleta("sat Hinchiriș, comuna Lazuri de Beiuș, judetul BIHOR, România")),
], createAdresaCompleta("comuna Lazuri de Beiuș, judetul BIHOR, România")),
createComuna("Lăzăreni", [
    createLoc("Lăzăreni", "sat", createAdresaCompleta("sat Lăzăreni, comuna Lăzăreni, judetul BIHOR, România")),
    createLoc("Bicăcel", "sat", createAdresaCompleta("sat Bicăcel, comuna Lăzăreni, judetul BIHOR, România")),
    createLoc("Calea Mare", "sat", createAdresaCompleta("sat Calea Mare, comuna Lăzăreni, judetul BIHOR, România")),
    createLoc("Cărăndeni", "sat", createAdresaCompleta("sat Cărăndeni, comuna Lăzăreni, judetul BIHOR, România")),
    createLoc("Cărănzel", "sat", createAdresaCompleta("sat Cărănzel, comuna Lăzăreni, judetul BIHOR, România")),
    createLoc("Gepiș", "sat", createAdresaCompleta("sat Gepiș, comuna Lăzăreni, judetul BIHOR, România")),
    createLoc("Gruilung", "sat", createAdresaCompleta("sat Gruilung, comuna Lăzăreni, judetul BIHOR, România")),
    createLoc("Miheleu", "sat", createAdresaCompleta("sat Miheleu, comuna Lăzăreni, judetul BIHOR, România")),
], createAdresaCompleta("comuna Lăzăreni, judetul BIHOR, România")),
createComuna("Lugașu de Jos", [
    createLoc("Lugașu de Jos", "sat", createAdresaCompleta("sat Lugașu de Jos, comuna Lugașu de Jos, judetul BIHOR, România")),
    createLoc("Lugașu de Sus", "sat", createAdresaCompleta("sat Lugașu de Sus, comuna Lugașu de Jos, judetul BIHOR, România")),
    createLoc("Urvind", "sat", createAdresaCompleta("sat Urvind, comuna Lugașu de Jos, judetul BIHOR, România")),
], createAdresaCompleta("comuna Lugașu de Jos, judetul BIHOR, România")),
createComuna("Lunca", [
    createLoc("Lunca", "sat", createAdresaCompleta("sat Lunca, comuna Lunca, judetul BIHOR, România")),
    createLoc("Briheni", "sat", createAdresaCompleta("sat Briheni, comuna Lunca, judetul BIHOR, România")),
    createLoc("Hotărel", "sat", createAdresaCompleta("sat Hotărel, comuna Lunca, judetul BIHOR, România")),
    createLoc("Seghiște", "sat", createAdresaCompleta("sat Seghiște, comuna Lunca, judetul BIHOR, România")),
    createLoc("Sârbești", "sat", createAdresaCompleta("sat Sârbești, comuna Lunca, judetul BIHOR, România")),
    createLoc("Șuștiu", "sat", createAdresaCompleta("sat Șuștiu, comuna Lunca, judetul BIHOR, România")),
], createAdresaCompleta("comuna Lunca, judetul BIHOR, România")),
createComuna("Mădăras", [
    createLoc("Mădăras", "sat", createAdresaCompleta("sat Mădăras, comuna Mădăras, judetul BIHOR, România")),
    createLoc("Homorog", "sat", createAdresaCompleta("sat Homorog, comuna Mădăras, judetul BIHOR, România")),
    createLoc("Ianoșda", "sat", createAdresaCompleta("sat Ianoșda, comuna Mădăras, judetul BIHOR, România")),
    createLoc("Marțihaz", "sat", createAdresaCompleta("sat Marțihaz, comuna Mădăras, judetul BIHOR, România")),
], createAdresaCompleta("comuna Mădăras, judetul BIHOR, România")),
createComuna("Măgești", [
    createLoc("Măgești", "sat", createAdresaCompleta("sat Măgești, comuna Măgești, judetul BIHOR, România")),
    createLoc("Butani", "sat", createAdresaCompleta("sat Butani, comuna Măgești, judetul BIHOR, România")),
    createLoc("Cacuciu Nou", "sat", createAdresaCompleta("sat Cacuciu Nou, comuna Măgești, judetul BIHOR, România")),
    createLoc("Dobricionești", "sat", createAdresaCompleta("sat Dobricionești, comuna Măgești, judetul BIHOR, România")),
    createLoc("Gălășeni", "sat", createAdresaCompleta("sat Gălășeni, comuna Măgești, judetul BIHOR, România")),
    createLoc("Josani", "sat", createAdresaCompleta("sat Josani, comuna Măgești, judetul BIHOR, România")),
    createLoc("Ortiteag", "sat", createAdresaCompleta("sat Ortiteag, comuna Măgești, judetul BIHOR, România")),
], createAdresaCompleta("comuna Măgești, judetul BIHOR, România")),
createComuna("Nojorid", [
    createLoc("Nojorid", "sat", createAdresaCompleta("sat Nojorid, comuna Nojorid, judetul BIHOR, România")),
    createLoc("Apateu", "sat", createAdresaCompleta("sat Apateu, comuna Nojorid, judetul BIHOR, România")),
    createLoc("Chișirid", "sat", createAdresaCompleta("sat Chișirid, comuna Nojorid, judetul BIHOR, România")),
    createLoc("Leș", "sat", createAdresaCompleta("sat Leș, comuna Nojorid, judetul BIHOR, România")),
    createLoc("Livada de Bihor", "sat", createAdresaCompleta("sat Livada de Bihor, comuna Nojorid, judetul BIHOR, România")),
    createLoc("Păușa", "sat", createAdresaCompleta("sat Păușa, comuna Nojorid, judetul BIHOR, România")),
    createLoc("Șauaieu", "sat", createAdresaCompleta("sat Șauaieu, comuna Nojorid, judetul BIHOR, România")),
], createAdresaCompleta("comuna Nojorid, judetul BIHOR, România")),
createComuna("Olcea", [
    createLoc("Olcea", "sat", createAdresaCompleta("sat Olcea, comuna Olcea, judetul BIHOR, România")),
    createLoc("Călacea", "sat", createAdresaCompleta("sat Călacea, comuna Olcea, judetul BIHOR, România")),
    createLoc("Hodișel", "sat", createAdresaCompleta("sat Hodișel, comuna Olcea, judetul BIHOR, România")),
    createLoc("Ucuriș", "sat", createAdresaCompleta("sat Ucuriș, comuna Olcea, judetul BIHOR, România")),
], createAdresaCompleta("comuna Olcea, judetul BIHOR, România")),
createComuna("Oșorhei", [
    createLoc("Oșorhei", "sat", createAdresaCompleta("sat Oșorhei, comuna Oșorhei, judetul BIHOR, România")),
    createLoc("Alparea", "sat", createAdresaCompleta("sat Alparea, comuna Oșorhei, judetul BIHOR, România")),
    createLoc("Cheriu", "sat", createAdresaCompleta("sat Cheriu, comuna Oșorhei, judetul BIHOR, România")),
    createLoc("Felcheriu", "sat", createAdresaCompleta("sat Felcheriu, comuna Oșorhei, judetul BIHOR, România")),
    createLoc("Fughiu", "sat", createAdresaCompleta("sat Fughiu, comuna Oșorhei, judetul BIHOR, România")),
], createAdresaCompleta("comuna Oșorhei, judetul BIHOR, România")),
createComuna("Paleu", [
    createLoc("Paleu", "sat", createAdresaCompleta("sat Paleu, comuna Paleu, judetul BIHOR, România")),
    createLoc("Săldăbagiu de Munte", "sat", createAdresaCompleta("sat Săldăbagiu de Munte, comuna Paleu, judetul BIHOR, România")),
    createLoc("Uileacu de Munte", "sat", createAdresaCompleta("sat Uileacu de Munte, comuna Paleu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Paleu, judetul BIHOR, România")),
createComuna("Petreu", [
    createLoc("Petreu", "sat", createAdresaCompleta("sat Petreu, comuna Petreu, judetul BIHOR, România")),
    createLoc("Abrămuț", "sat", createAdresaCompleta("sat Abrămuț, comuna Petreu, judetul BIHOR, România")),
    createLoc("Crestur", "sat", createAdresaCompleta("sat Crestur, comuna Petreu, judetul BIHOR, România")),
    createLoc("Făncica", "sat", createAdresaCompleta("sat Făncica, comuna Petreu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Petreu, judetul BIHOR, România")),
createComuna("Pietroasa", [
    createLoc("Pietroasa", "sat", createAdresaCompleta("sat Pietroasa, comuna Pietroasa, judetul BIHOR, România")),
    createLoc("Chișcău", "sat", createAdresaCompleta("sat Chișcău, comuna Pietroasa, judetul BIHOR, România")),
    createLoc("Cociuba Mică", "sat", createAdresaCompleta("sat Cociuba Mică, comuna Pietroasa, judetul BIHOR, România")),
    createLoc("Giulești", "sat", createAdresaCompleta("sat Giulești, comuna Pietroasa, judetul BIHOR, România")),
    createLoc("Gurani", "sat", createAdresaCompleta("sat Gurani, comuna Pietroasa, judetul BIHOR, România")),
    createLoc("Măgura", "sat", createAdresaCompleta("sat Măgura, comuna Pietroasa, judetul BIHOR, România")),
    createLoc("Moțești", "sat", createAdresaCompleta("sat Moțești, comuna Pietroasa, judetul BIHOR, România")),
], createAdresaCompleta("comuna Pietroasa, judetul BIHOR, România")),
createComuna("Pocola", [
    createLoc("Pocola", "sat", createAdresaCompleta("sat Pocola, comuna Pocola, judetul BIHOR, România")),
    createLoc("Feneriș", "sat", createAdresaCompleta("sat Feneriș, comuna Pocola, judetul BIHOR, România")),
    createLoc("Petrani", "sat", createAdresaCompleta("sat Petrani, comuna Pocola, judetul BIHOR, România")),
    createLoc("Poietari", "sat", createAdresaCompleta("sat Poietari, comuna Pocola, judetul BIHOR, România")),
    createLoc("Sânmartin de Beiuș", "sat", createAdresaCompleta("sat Sânmartin de Beiuș, comuna Pocola, judetul BIHOR, România")),
], createAdresaCompleta("comuna Pocola, judetul BIHOR, România")),
createComuna("Pomezeu", [
    createLoc("Pomezeu", "sat", createAdresaCompleta("sat Pomezeu, comuna Pomezeu, judetul BIHOR, România")),
    createLoc("Câmpani de Pomezeu", "sat", createAdresaCompleta("sat Câmpani de Pomezeu, comuna Pomezeu, judetul BIHOR, România")),
    createLoc("Coșdeni", "sat", createAdresaCompleta("sat Coșdeni, comuna Pomezeu, judetul BIHOR, România")),
    createLoc("Hidiș", "sat", createAdresaCompleta("sat Hidiș, comuna Pomezeu, judetul BIHOR, România")),
    createLoc("Lacu Sărat", "sat", createAdresaCompleta("sat Lacu Sărat, comuna Pomezeu, judetul BIHOR, România")),
    createLoc("Sitani", "sat", createAdresaCompleta("sat Sitani, comuna Pomezeu, judetul BIHOR, România")),
    createLoc("Spinuș de Pomezeu", "sat", createAdresaCompleta("sat Spinuș de Pomezeu, comuna Pomezeu, judetul BIHOR, România")),
    createLoc("Vălani de Pomezeu", "sat", createAdresaCompleta("sat Vălani de Pomezeu, comuna Pomezeu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Pomezeu, judetul BIHOR, România")),
createComuna("Popești", [
    createLoc("Popești", "sat", createAdresaCompleta("sat Popești, comuna Popești, judetul BIHOR, România")),
    createLoc("Bistra", "sat", createAdresaCompleta("sat Bistra, comuna Popești, judetul BIHOR, România")),
    createLoc("Budoi", "sat", createAdresaCompleta("sat Budoi, comuna Popești, judetul BIHOR, România")),
    createLoc("Cuzap", "sat", createAdresaCompleta("sat Cuzap, comuna Popești, judetul BIHOR, România")),
    createLoc("Varviz", "sat", createAdresaCompleta("sat Varviz, comuna Popești, judetul BIHOR, România")),
    createLoc("Vărzari", "sat", createAdresaCompleta("sat Vărzari, comuna Popești, judetul BIHOR, România")),
    createLoc("Voivozi", "sat", createAdresaCompleta("sat Voivozi, comuna Popești, judetul BIHOR, România")),
], createAdresaCompleta("comuna Popești, judetul BIHOR, România")),
createComuna("Răbăgani", [
    createLoc("Răbăgani", "sat", createAdresaCompleta("sat Răbăgani, comuna Răbăgani, judetul BIHOR, România")),
    createLoc("Albești", "sat", createAdresaCompleta("sat Albești, comuna Răbăgani, judetul BIHOR, România")),
    createLoc("Brătești", "sat", createAdresaCompleta("sat Brătești, comuna Răbăgani, judetul BIHOR, România")),
    createLoc("Săliște de Pomezeu", "sat", createAdresaCompleta("sat Săliște de Pomezeu, comuna Răbăgani, judetul BIHOR, România")),
    createLoc("Săucani", "sat", createAdresaCompleta("sat Săucani, comuna Răbăgani, judetul BIHOR, România")),
    createLoc("Vărășeni", "sat", createAdresaCompleta("sat Vărășeni, comuna Răbăgani, judetul BIHOR, România")),
], createAdresaCompleta("comuna Răbăgani, judetul BIHOR, România")),
createComuna("Remetea", [
    createLoc("Remetea", "sat", createAdresaCompleta("sat Remetea, comuna Remetea, judetul BIHOR, România")),
    createLoc("Drăgoteni", "sat", createAdresaCompleta("sat Drăgoteni, comuna Remetea, judetul BIHOR, România")),
    createLoc("Meziad", "sat", createAdresaCompleta("sat Meziad, comuna Remetea, judetul BIHOR, România")),
    createLoc("Petreasa", "sat", createAdresaCompleta("sat Petreasa, comuna Remetea, judetul BIHOR, România")),
    createLoc("Șoimuș", "sat", createAdresaCompleta("sat Șoimuș, comuna Remetea, judetul BIHOR, România")),
], createAdresaCompleta("comuna Remetea, judetul BIHOR, România")),
createComuna("Rieni", [
    createLoc("Rieni", "sat", createAdresaCompleta("sat Rieni, comuna Rieni, judetul BIHOR, România")),
    createLoc("Cucuceni", "sat", createAdresaCompleta("sat Cucuceni, comuna Rieni, judetul BIHOR, România")),
    createLoc("Ghighișeni", "sat", createAdresaCompleta("sat Ghighișeni, comuna Rieni, judetul BIHOR, România")),
    createLoc("Petrileni", "sat", createAdresaCompleta("sat Petrileni, comuna Rieni, judetul BIHOR, România")),
    createLoc("Sudrigiu", "sat", createAdresaCompleta("sat Sudrigiu, comuna Rieni, judetul BIHOR, România")),
    createLoc("Valea de Jos", "sat", createAdresaCompleta("sat Valea de Jos, comuna Rieni, judetul BIHOR, România")),
], createAdresaCompleta("comuna Rieni, judetul BIHOR, România")),
createComuna("Roșia", [
    createLoc("Roșia", "sat", createAdresaCompleta("sat Roșia, comuna Roșia, judetul BIHOR, România")),
    createLoc("Lazuri", "sat", createAdresaCompleta("sat Lazuri, comuna Roșia, judetul BIHOR, România")),
], createAdresaCompleta("comuna Roșia, judetul BIHOR, România")),
createComuna("Roșiori", [
    createLoc("Roșiori", "sat", createAdresaCompleta("sat Roșiori, comuna Roșiori, judetul BIHOR, România")),
    createLoc("Mihai Bravu", "sat", createAdresaCompleta("sat Mihai Bravu, comuna Roșiori, judetul BIHOR, România")),
    createLoc("Vaida", "sat", createAdresaCompleta("sat Vaida, comuna Roșiori, judetul BIHOR, România")),
], createAdresaCompleta("comuna Roșiori, judetul BIHOR, România")),
createComuna("Săcădat", [
    createLoc("Săcădat", "sat", createAdresaCompleta("sat Săcădat, comuna Săcădat, judetul BIHOR, România")),
    createLoc("Borșa", "sat", createAdresaCompleta("sat Borșa, comuna Săcădat, judetul BIHOR, România")),
    createLoc("Săbolciu", "sat", createAdresaCompleta("sat Săbolciu, comuna Săcădat, judetul BIHOR, România")),
], createAdresaCompleta("comuna Săcădat, judetul BIHOR, România")),
createComuna("Sălacea", [
    createLoc("Sălacea", "sat", createAdresaCompleta("sat Sălacea, comuna Sălacea, judetul BIHOR, România")),
    createLoc("Otomani", "sat", createAdresaCompleta("sat Otomani, comuna Sălacea, judetul BIHOR, România")),
], createAdresaCompleta("comuna Sălacea, judetul BIHOR, România")),
createComuna("Sălard", [
    createLoc("Sălard", "sat", createAdresaCompleta("sat Sălard, comuna Sălard, judetul BIHOR, România")),
    createLoc("Hodoș", "sat", createAdresaCompleta("sat Hodoș, comuna Sălard, judetul BIHOR, România")),
    createLoc("Sântimreu", "sat", createAdresaCompleta("sat Sântimreu, comuna Sălard, judetul BIHOR, România")),
], createAdresaCompleta("comuna Sălard, judetul BIHOR, România")),
createComuna("Sâniob", [
    createLoc("Sâniob", "sat", createAdresaCompleta("sat Sâniob, comuna Sâniob, judetul BIHOR, România")),
    createLoc("Cenaloș", "sat", createAdresaCompleta("sat Cenaloș, comuna Sâniob, judetul BIHOR, România")),
    createLoc("Ciuhoi", "sat", createAdresaCompleta("sat Ciuhoi, comuna Sâniob, judetul BIHOR, România")),
    createLoc("Sfârnaș", "sat", createAdresaCompleta("sat Sfârnaș, comuna Sâniob, judetul BIHOR, România")),
], createAdresaCompleta("comuna Sâniob, judetul BIHOR, România")),
createComuna("Sânnicolau Român", [
    createLoc("Sânnicolau Român", "sat", createAdresaCompleta("sat Sânnicolau Român, comuna Sânnicolau Român, judetul BIHOR, România")),
    createLoc("Berechiu", "sat", createAdresaCompleta("sat Berechiu, comuna Sânnicolau Român, judetul BIHOR, România")),
    createLoc("Roit", "sat", createAdresaCompleta("sat Roit, comuna Sânnicolau Român, judetul BIHOR, România")),
], createAdresaCompleta("comuna Sânnicolau Român, judetul BIHOR, România")),
createComuna("Sâmbăta", [
    createLoc("Sâmbăta", "sat", createAdresaCompleta("sat Sâmbăta, comuna Sâmbăta, judetul BIHOR, România")),
    createLoc("Copăceni", "sat", createAdresaCompleta("sat Copăceni, comuna Sâmbăta, judetul BIHOR, România")),
    createLoc("Ogești", "sat", createAdresaCompleta("sat Ogești, comuna Sâmbăta, judetul BIHOR, România")),
    createLoc("Rogoz", "sat", createAdresaCompleta("sat Rogoz, comuna Sâmbăta, judetul BIHOR, România")),
    createLoc("Rotărești", "sat", createAdresaCompleta("sat Rotărești, comuna Sâmbăta, judetul BIHOR, România")),
    createLoc("Zăvoiu", "sat", createAdresaCompleta("sat Zăvoiu, comuna Sâmbăta, judetul BIHOR, România")),
], createAdresaCompleta("comuna Sâmbăta, judetul BIHOR, România")),
createComuna("Sânmartin", [
    createLoc("Sânmartin", "sat", createAdresaCompleta("sat Sânmartin, comuna Sânmartin, judetul BIHOR, România")),
    createLoc("Betfia", "sat", createAdresaCompleta("sat Betfia, comuna Sânmartin, judetul BIHOR, România")),
    createLoc("Cihei", "sat", createAdresaCompleta("sat Cihei, comuna Sânmartin, judetul BIHOR, România")),
    createLoc("Cordău", "sat", createAdresaCompleta("sat Cordău, comuna Sânmartin, judetul BIHOR, România")),
    createLoc("Haieu", "sat", createAdresaCompleta("sat Haieu, comuna Sânmartin, judetul BIHOR, România")),
    createLoc("Rontău", "sat", createAdresaCompleta("sat Rontău, comuna Sânmartin, judetul BIHOR, România")),
], createAdresaCompleta("comuna Sânmartin, judetul BIHOR, România")),
createComuna("Sântandrei", [
    createLoc("Sântandrei", "sat", createAdresaCompleta("sat Sântandrei, comuna Sântandrei, judetul BIHOR, România")),
    createLoc("Palota", "sat", createAdresaCompleta("sat Palota, comuna Sântandrei, judetul BIHOR, România")),
], createAdresaCompleta("comuna Sântandrei, judetul BIHOR, România")),
createComuna("Sârbi", [
    createLoc("Sârbi", "sat", createAdresaCompleta("sat Sârbi, comuna Sârbi, judetul BIHOR, România")),
    createLoc("Almașu Mic", "sat", createAdresaCompleta("sat Almașu Mic, comuna Sârbi, judetul BIHOR, România")),
    createLoc("Burzuc", "sat", createAdresaCompleta("sat Burzuc, comuna Sârbi, judetul BIHOR, România")),
    createLoc("Chioag", "sat", createAdresaCompleta("sat Chioag, comuna Sârbi, judetul BIHOR, România")),
    createLoc("Fegernic", "sat", createAdresaCompleta("sat Fegernic, comuna Sârbi, judetul BIHOR, România")),
    createLoc("Fegernicu Nou", "sat", createAdresaCompleta("sat Fegernicu Nou, comuna Sârbi, judetul BIHOR, România")),
    createLoc("Sarcău", "sat", createAdresaCompleta("sat Sarcău, comuna Sârbi, judetul BIHOR, România")),
], createAdresaCompleta("comuna Sârbi, judetul BIHOR, România")),
createComuna("Spinuș", [
    createLoc("Spinuș", "sat", createAdresaCompleta("sat Spinuș, comuna Spinuș, judetul BIHOR, România")),
    createLoc("Ciulești", "sat", createAdresaCompleta("sat Ciulești, comuna Spinuș, judetul BIHOR, România")),
    createLoc("Gurbești", "sat", createAdresaCompleta("sat Gurbești, comuna Spinuș, judetul BIHOR, România")),
    createLoc("Nădar", "sat", createAdresaCompleta("sat Nădar, comuna Spinuș, judetul BIHOR, România")),
    createLoc("Săliște", "sat", createAdresaCompleta("sat Săliște, comuna Spinuș, judetul BIHOR, România")),
], createAdresaCompleta("comuna Spinuș, judetul BIHOR, România")),
createComuna("Suplacu de Barcău", [
    createLoc("Suplacu de Barcău", "sat", createAdresaCompleta("sat Suplacu de Barcău, comuna Suplacu de Barcău, judetul BIHOR, România")),
    createLoc("Borumlaca", "sat", createAdresaCompleta("sat Borumlaca, comuna Suplacu de Barcău, judetul BIHOR, România")),
    createLoc("Dolea", "sat", createAdresaCompleta("sat Dolea, comuna Suplacu de Barcău, judetul BIHOR, România")),
    createLoc("Foglaș", "sat", createAdresaCompleta("sat Foglaș, comuna Suplacu de Barcău, judetul BIHOR, România")),
    createLoc("Valea Cerului", "sat", createAdresaCompleta("sat Valea Cerului, comuna Suplacu de Barcău, judetul BIHOR, România")),
    createLoc("Vâlcelele", "sat", createAdresaCompleta("sat Vâlcelele, comuna Suplacu de Barcău, judetul BIHOR, România")),
], createAdresaCompleta("comuna Suplacu de Barcău, judetul BIHOR, România")),
createComuna("Șimian", [
    createLoc("Șimian", "sat", createAdresaCompleta("sat Șimian, comuna Șimian, judetul BIHOR, România")),
    createLoc("Șilindru", "sat", createAdresaCompleta("sat Șilindru, comuna Șimian, judetul BIHOR, România")),
    createLoc("Voivozi", "sat", createAdresaCompleta("sat Voivozi, comuna Șimian, judetul BIHOR, România")),
], createAdresaCompleta("comuna Șimian, judetul BIHOR, România")),
createComuna("Șinteu", [
    createLoc("Șinteu", "sat", createAdresaCompleta("sat Șinteu, comuna Șinteu, judetul BIHOR, România")),
    createLoc("Huta Voivozi", "sat", createAdresaCompleta("sat Huta Voivozi, comuna Șinteu, judetul BIHOR, România")),
    createLoc("Socet", "sat", createAdresaCompleta("sat Socet, comuna Șinteu, judetul BIHOR, România")),
    createLoc("Valea Târnei", "sat", createAdresaCompleta("sat Valea Târnei, comuna Șinteu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Șinteu, judetul BIHOR, România")),
createComuna("Șoimi", [
    createLoc("Șoimi", "sat", createAdresaCompleta("sat Șoimi, comuna Șoimi, judetul BIHOR, România")),
    createLoc("Borz", "sat", createAdresaCompleta("sat Borz, comuna Șoimi, judetul BIHOR, România")),
    createLoc("Codru", "sat", createAdresaCompleta("sat Codru, comuna Șoimi, judetul BIHOR, România")),
    createLoc("Dumbrăvița de Codru", "sat", createAdresaCompleta("sat Dumbrăvița de Codru, comuna Șoimi, judetul BIHOR, România")),
    createLoc("Poclușa de Beiuș", "sat", createAdresaCompleta("sat Poclușa de Beiuș, comuna Șoimi, judetul BIHOR, România")),
    createLoc("Sânnicolau de Beiuș", "sat", createAdresaCompleta("sat Sânnicolau de Beiuș, comuna Șoimi, judetul BIHOR, România")),
    createLoc("Ursad", "sat", createAdresaCompleta("sat Ursad, comuna Șoimi, judetul BIHOR, România")),
    createLoc("Urviș de Beiuș", "sat", createAdresaCompleta("sat Urviș de Beiuș, comuna Șoimi, judetul BIHOR, România")),
], createAdresaCompleta("comuna Șoimi, judetul BIHOR, România")),
createComuna("Șuncuiuș", [
    createLoc("Șuncuiuș", "sat", createAdresaCompleta("sat Șuncuiuș, comuna Șuncuiuș, judetul BIHOR, România")),
    createLoc("Bălnaca", "sat", createAdresaCompleta("sat Bălnaca, comuna Șuncuiuș, judetul BIHOR, România")),
    createLoc("Bălnaca-Groși", "sat", createAdresaCompleta("sat Bălnaca-Groși, comuna Șuncuiuș, judetul BIHOR, România")),
    createLoc("Zece Hotare", "sat", createAdresaCompleta("sat Zece Hotare, comuna Șuncuiuș, judetul BIHOR, România")),
], createAdresaCompleta("comuna Șuncuiuș, judetul BIHOR, România")),
createComuna("Tarcea", [
    createLoc("Tarcea", "sat", createAdresaCompleta("sat Tarcea, comuna Tarcea, judetul BIHOR, România")),
    createLoc("Adoni", "sat", createAdresaCompleta("sat Adoni, comuna Tarcea, judetul BIHOR, România")),
    createLoc("Galoșpetreu", "sat", createAdresaCompleta("sat Galoșpetreu, comuna Tarcea, judetul BIHOR, România")),
], createAdresaCompleta("comuna Tarcea, judetul BIHOR, România")),
createComuna("Tămășeu", [
    createLoc("Tămășeu", "sat", createAdresaCompleta("sat Tămășeu, comuna Tămășeu, judetul BIHOR, România")),
    createLoc("Niuved", "sat", createAdresaCompleta("sat Niuved, comuna Tămășeu, judetul BIHOR, România")),
    createLoc("Parhida", "sat", createAdresaCompleta("sat Parhida, comuna Tămășeu, judetul BIHOR, România")),
    createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Tămășeu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Tămășeu, judetul BIHOR, România")),
createComuna("Tărcaia", [
    createLoc("Tărcaia", "sat", createAdresaCompleta("sat Tărcaia, comuna Tărcaia, judetul BIHOR, România")),
    createLoc("Mierag", "sat", createAdresaCompleta("sat Mierag, comuna Tărcaia, judetul BIHOR, România")),
    createLoc("Tărcăița", "sat", createAdresaCompleta("sat Tărcăița, comuna Tărcaia, judetul BIHOR, România")),
    createLoc("Totoreni", "sat", createAdresaCompleta("sat Totoreni, comuna Tărcaia, judetul BIHOR, România")),
], createAdresaCompleta("comuna Tărcaia, judetul BIHOR, România")),
createComuna("Tăuteu", [
    createLoc("Tăuteu", "sat", createAdresaCompleta("sat Tăuteu, comuna Tăuteu, judetul BIHOR, România")),
    createLoc("Bogei", "sat", createAdresaCompleta("sat Bogei, comuna Tăuteu, judetul BIHOR, România")),
    createLoc("Chiribiș", "sat", createAdresaCompleta("sat Chiribiș, comuna Tăuteu, judetul BIHOR, România")),
    createLoc("Ciutelec", "sat", createAdresaCompleta("sat Ciutelec, comuna Tăuteu, judetul BIHOR, România")),
    createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Tăuteu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Tăuteu, judetul BIHOR, România")),
createComuna("Tileagd", [
    createLoc("Tileagd", "sat", createAdresaCompleta("sat Tileagd, comuna Tileagd, judetul BIHOR, România")),
    createLoc("Bălaia", "sat", createAdresaCompleta("sat Bălaia, comuna Tileagd, judetul BIHOR, România")),
    createLoc("Călătani", "sat", createAdresaCompleta("sat Călătani, comuna Tileagd, judetul BIHOR, România")),
    createLoc("Poșoloaca", "sat", createAdresaCompleta("sat Poșoloaca, comuna Tileagd, judetul BIHOR, România")),
    createLoc("Tilecuș", "sat", createAdresaCompleta("sat Tilecuș, comuna Tileagd, judetul BIHOR, România")),
    createLoc("Uileacu de Criș", "sat", createAdresaCompleta("sat Uileacu de Criș, comuna Tileagd, judetul BIHOR, România")),
]),
createComuna("Tinca", [
    createLoc("Tinca", "sat", createAdresaCompleta("sat Tinca, comuna Tinca, judetul BIHOR, România")),
    createLoc("Belfir", "sat", createAdresaCompleta("sat Belfir, comuna Tinca, judetul BIHOR, România")),
    createLoc("Girișu Negru", "sat", createAdresaCompleta("sat Girișu Negru, comuna Tinca, judetul BIHOR, România")),
    createLoc("Gurbediu", "sat", createAdresaCompleta("sat Gurbediu, comuna Tinca, judetul BIHOR, România")),
    createLoc("Râpa", "sat", createAdresaCompleta("sat Râpa, comuna Tinca, judetul BIHOR, România")),
], createAdresaCompleta("comuna Tinca, judetul BIHOR, România")),
createComuna("Toboliu", [
    createLoc("Toboliu", "sat", createAdresaCompleta("sat Toboliu, comuna Toboliu, judetul BIHOR, România")),
    createLoc("Cheresig", "sat", createAdresaCompleta("sat Cheresig, comuna Toboliu, judetul BIHOR, România")),
], createAdresaCompleta("comuna Toboliu, judetul BIHOR, România")),
createComuna("Tulca", [
    createLoc("Tulca", "sat", createAdresaCompleta("sat Tulca, comuna Tulca, judetul BIHOR, România")),
    createLoc("Căuașd", "sat", createAdresaCompleta("sat Căuașd, comuna Tulca, judetul BIHOR, România")),
], createAdresaCompleta("comuna Tulca, judetul BIHOR, România")),
createComuna("Țețchea", [
    createLoc("Țețchea", "sat", createAdresaCompleta("sat Țețchea, comuna Țețchea, judetul BIHOR, România")),
    createLoc("Hotar", "sat", createAdresaCompleta("sat Hotar, comuna Țețchea, judetul BIHOR, România")),
    createLoc("Subpiatră", "sat", createAdresaCompleta("sat Subpiatră, comuna Țețchea, judetul BIHOR, România")),
    createLoc("Telechiu", "sat", createAdresaCompleta("sat Telechiu, comuna Țețchea, judetul BIHOR, România")),
], createAdresaCompleta("comuna Țețchea, judetul BIHOR, România")),
createComuna("Uileacu de Beiuș", [
    createLoc("Uileacu de Beiuș", "sat", createAdresaCompleta("sat Uileacu de Beiuș, comuna Uileacu de Beiuș, judetul BIHOR, România")),
    createLoc("Forău", "sat", createAdresaCompleta("sat Forău, comuna Uileacu de Beiuș, judetul BIHOR, România")),
    createLoc("Prisaca", "sat", createAdresaCompleta("sat Prisaca, comuna Uileacu de Beiuș, judetul BIHOR, România")),
    createLoc("Vălanii de Beiuș", "sat", createAdresaCompleta("sat Vălanii de Beiuș, comuna Uileacu de Beiuș, judetul BIHOR, România")),
], createAdresaCompleta("comuna Uileacu de Beiuș, judetul BIHOR, România")),
createComuna("Vadu Crișului", [
    createLoc("Vadu Crișului", "sat", createAdresaCompleta("sat Vadu Crișului, comuna Vadu Crișului, judetul BIHOR, România")),
    createLoc("Birtin", "sat", createAdresaCompleta("sat Birtin, comuna Vadu Crișului, judetul BIHOR, România")),
    createLoc("Tomnatic", "sat", createAdresaCompleta("sat Tomnatic, comuna Vadu Crișului, judetul BIHOR, România")),
    createLoc("Topa de Criș", "sat", createAdresaCompleta("sat Topa de Criș, comuna Vadu Crișului, judetul BIHOR, România")),
], createAdresaCompleta("comuna Vadu Crișului, judetul BIHOR, România")),
createComuna("Viișoara", [
    createLoc("Viișoara", "sat", createAdresaCompleta("sat Viișoara, comuna Viișoara, judetul BIHOR, România")),
    createLoc("Izvoarele", "sat", createAdresaCompleta("sat Izvoarele, comuna Viișoara, judetul BIHOR, România")),
    createLoc("Pădureni", "sat", createAdresaCompleta("sat Pădureni, comuna Viișoara, judetul BIHOR, România")),
    createLoc("Reghea", "sat", createAdresaCompleta("sat Reghea, comuna Viișoara, judetul BIHOR, România")),
], createAdresaCompleta("comuna Viișoara, judetul BIHOR, România")),
createComuna("Vârciorog", [
    createLoc("Vârciorog", "sat", createAdresaCompleta("sat Vârciorog, comuna Vârciorog, judetul BIHOR, România")),
    createLoc("Fâșca", "sat", createAdresaCompleta("sat Fâșca, comuna Vârciorog, judetul BIHOR, România")),
    createLoc("Surducel", "sat", createAdresaCompleta("sat Surducel, comuna Vârciorog, judetul BIHOR, România")),
    createLoc("Șerghiș", "sat", createAdresaCompleta("sat Șerghiș, comuna Vârciorog, judetul BIHOR, România")),
], createAdresaCompleta("comuna Vârciorog, judetul BIHOR, România")),


			  
			
];
?>