<?php
$comune =[
createComuna("Abram", [
    createLoc("Abram", "sat"),
    createLoc("Cohani", "sat"),
    createLoc("Dijir", "sat"),
    createLoc("Iteu", "sat"),
    createLoc("Iteu Nou", "sat"),
    createLoc("Margine", "sat"),
    createLoc("Satu Barbă", "sat"),
    createLoc("Suiug", "sat"),
]),
createComuna("Abrogat", [

]),
createComuna("Aștileu", [
    createLoc("Aștileu", "sat"),
    createLoc("Călățea", "sat"),
    createLoc("Chistag", "sat"),
    createLoc("Peștere", "sat"),
]),
createComuna("Aușeu", [
    createLoc("Aușeu", "sat"),
    createLoc("Cacuciu Vechi", "sat"),
    createLoc("Codrișoru", "sat"),
    createLoc("Gheghie", "sat"),
    createLoc("Groși", "sat"),
    createLoc("Luncșoara", "sat"),
]),
createComuna("Avram Iancu", [
    createLoc("Avram Iancu", "sat"),
    createLoc("Ant", "sat"),
    createLoc("Tămașda", "sat"),
]),
createComuna("Balc", [
    createLoc("Balc", "sat"),
    createLoc("Almașu Mare", "sat"),
    createLoc("Almașu Mic", "sat"),
    createLoc("Ghida", "sat"),
    createLoc("Săldăbagiu de Barcău", "sat"),
]),
createComuna("Batăr", [
    createLoc("Batăr", "sat"),
    createLoc("Arpășel", "sat"),
    createLoc("Talpoș", "sat"),
    createLoc("Tăut", "sat"),
]),
createComuna("Biharia", [
    createLoc("Biharia", "sat"),
    createLoc("Cauaceu", "sat"),
]),
createComuna("Boianu Mare", [
    createLoc("Boianu Mare", "sat"),
    createLoc("Corboaia", "sat"),
    createLoc("Huta", "sat"),
    createLoc("Păgaia", "sat"),
    createLoc("Rugea", "sat"),
]),
createComuna("Borod", [
    createLoc("Borod", "sat"),
    createLoc("Borozel", "sat"),
    createLoc("Cetea", "sat"),
    createLoc("Cornițel", "sat"),
    createLoc("Șerani", "sat"),
    createLoc("Valea Mare de Criș", "sat"),
]),

createComuna("Borș", [
    createLoc("Borș", "sat"),
    createLoc("Santăul Mare", "sat"),
    createLoc("Santăul Mic", "sat"),
    createLoc("Sântion", "sat"),
]),
createComuna("Bratca", [
    createLoc("Bratca", "sat"),
    createLoc("Beznea", "sat"),
    createLoc("Damiș", "sat"),
    createLoc("Lorău", "sat"),
    createLoc("Ponoară", "sat"),
    createLoc("Valea Crișului", "sat"),
]),
createComuna("Brusturi", [
    createLoc("Brusturi", "sat"),
    createLoc("Cuieșd", "sat"),
    createLoc("Loranta", "sat"),
    createLoc("Orvișele", "sat"),
    createLoc("Păulești", "sat"),
    createLoc("Picleu", "sat"),
    createLoc("Țigăneștii de Criș", "sat"),
    createLoc("Varasău", "sat"),
]),
createComuna("Budureasa", [
    createLoc("Budureasa", "sat"),
    createLoc("Burda", "sat"),
    createLoc("Saca", "sat"),
    createLoc("Săliște de Beiuș", "sat"),
    createLoc("Teleac", "sat"),
]),
createComuna("Buduslău", [
    createLoc("Buduslău", "sat"),
    createLoc("Albiș", "sat"),
]),
createComuna("Bulz", [
    createLoc("Bulz", "sat"),
    createLoc("Munteni", "sat"),
    createLoc("Remeți", "sat"),
]),
createComuna("Buntești", [
    createLoc("Buntești", "sat"),
    createLoc("Brădet", "sat"),
    createLoc("Dumbrăvani", "sat"),
    createLoc("Ferice", "sat"),
    createLoc("Lelești", "sat"),
    createLoc("Poienii de Jos", "sat"),
    createLoc("Poienii de Sus", "sat"),
    createLoc("Săud", "sat"),
    createLoc("Stâncești", "sat"),
]),
createComuna("Căbești", [
    createLoc("Căbești", "sat"),
    createLoc("Goila", "sat"),
    createLoc("Gurbești", "sat"),
    createLoc("Josani", "sat"),
    createLoc("Sohodol", "sat"),
]),
createComuna("Căpâlna", [
    createLoc("Căpâlna", "sat"),
    createLoc("Ginta", "sat"),
    createLoc("Rohani", "sat"),
    createLoc("Săldăbagiu Mic", "sat"),
    createLoc("Suplacu de Tinca", "sat"),
]),
createComuna("Cărpinet", [
    createLoc("Cărpinet", "sat"),
    createLoc("Călugări", "sat"),
    createLoc("Izbuc", "sat"),
    createLoc("Leheceni", "sat"),
]),
createComuna("Cefa", [
    createLoc("Cefa", "sat"),
    createLoc("Ateaș", "sat"),
    createLoc("Inand", "sat"),
]),
createComuna("Ceica", [
    createLoc("Ceica", "sat"),
    createLoc("Bucium", "sat"),
    createLoc("Ceișoara", "sat"),
    createLoc("Corbești", "sat"),
    createLoc("Cotiglet", "sat"),
    createLoc("Dușești", "sat"),
    createLoc("Incești", "sat"),
]),
createComuna("Cetariu", [
    createLoc("Cetariu", "sat"),
    createLoc("Șișterea", "sat"),
    createLoc("Șușturogi", "sat"),
    createLoc("Tăutelec", "sat"),
]),
createComuna("Cherechiu", [
    createLoc("Cherechiu", "sat"),
    createLoc("Cheșereu", "sat"),
    createLoc("Târgușor", "sat"),
]),
createComuna("Chișlaz", [
    createLoc("Chișlaz", "sat"),
    createLoc("Chiraleu", "sat"),
    createLoc("Hăucești", "sat"),
    createLoc("Mișca", "sat"),
    createLoc("Poclușa de Barcău", "sat"),
    createLoc("Sărsig", "sat"),
    createLoc("Sânlazăr", "sat"),
]),
createComuna("Ciumeghiu", [
    createLoc("Ciumeghiu", "sat"),
    createLoc("Boiu", "sat"),
    createLoc("Ghiorac", "sat"),
]),
createComuna("Câmpani", [
    createLoc("Câmpani", "sat"),
    createLoc("Fânațe", "sat"),
    createLoc("Hârsești", "sat"),
    createLoc("Sighiștel", "sat"),
    createLoc("Valea de Sus", "sat"),
]),
createComuna("Cociuba Mare", [
    createLoc("Cociuba Mare", "sat"),
    createLoc("Cărăsău", "sat"),
    createLoc("Cheșa", "sat"),
    createLoc("Petid", "sat"),
]),
createComuna("Copăcel", [
    createLoc("Copăcel", "sat"),
    createLoc("Bucuroaia", "sat"),
    createLoc("Chijic", "sat"),
    createLoc("Poiana Tășad", "sat"),
    createLoc("Sărand", "sat"),
    createLoc("Surduc", "sat"),
]),
createComuna("Criștioru de Jos", [
    createLoc("Criștioru de Jos", "sat"),
    createLoc("Bâlc", "sat"),
    createLoc("Criștioru de Sus", "sat"),
    createLoc("Poiana", "sat"),
    createLoc("Săliște de Vașcău", "sat"),
]),
createComuna("Curățele", [
    createLoc("Curățele", "sat"),
    createLoc("Beiușele", "sat"),
    createLoc("Cresuia", "sat"),
    createLoc("Nimăiești", "sat"),
    createLoc("Pocioveliște", "sat"),
]),
createComuna("Curtuișeni", [
    createLoc("Curtuișeni", "sat"),
    createLoc("Vășad", "sat"),
]),
createComuna("Derna", [
    createLoc("Derna", "sat"),
    createLoc("Dernișoara", "sat"),
    createLoc("Sacalasău", "sat"),
    createLoc("Sacalasău Nou", "sat"),
    createLoc("Tria", "sat"),
]),
createComuna("Diosig", [
    createLoc("Diosig", "sat"),
    createLoc("Ianca", "sat"),
]),
createComuna("Dobrești", [
    createLoc("Dobrești", "sat"),
    createLoc("Cornișești", "sat"),
    createLoc("Crâncești", "sat"),
    createLoc("Hidișel", "sat"),
    createLoc("Luncasprie", "sat"),
    createLoc("Răcaș", "sat"),
    createLoc("Topa de Jos", "sat"),
    createLoc("Topa de Sus", "sat"),
]),
createComuna("Drăgănești", [
    createLoc("Drăgănești", "sat"),
    createLoc("Belejeni", "sat"),
    createLoc("Grădinari", "sat"),
    createLoc("Livada Beiușului", "sat"),
    createLoc("Mizieș", "sat"),
    createLoc("Păcălești", "sat"),
    createLoc("Păntășești", "sat"),
    createLoc("Șebiș", "sat"),
    createLoc("Talpe", "sat"),
    createLoc("Țigăneștii de Beiuș", "sat"),
]),
createComuna("Drăgești", [
    createLoc("Drăgești", "sat"),
    createLoc("Dicănești", "sat"),
    createLoc("Stracoș", "sat"),
    createLoc("Tășad", "sat"),
    createLoc("Topești", "sat"),
]),
createComuna("Finiș", [
    createLoc("Finiș", "sat"),
    createLoc("Brusturi", "sat"),
    createLoc("Fiziș", "sat"),
    createLoc("Ioaniș", "sat"),
    createLoc("Șuncuiș", "sat"),
]),
createComuna("Gepiu", [
    createLoc("Gepiu", "sat"),
    createLoc("Bicaci", "sat"),
]),
createComuna("Girișu de Criș", [
    createLoc("Girișu de Criș", "sat"),
    createLoc("Tărian", "sat"),
]),
createComuna("Hidișelu de Sus", [
    createLoc("Hidișelu de Sus", "sat"),
    createLoc("Hidișelu de Jos", "sat"),
    createLoc("Mierlău", "sat"),
    createLoc("Sântelec", "sat"),
    createLoc("Șumugiu", "sat"),
]),
createComuna("Holod", [
    createLoc("Holod", "sat"),
    createLoc("Dumbrava", "sat"),
    createLoc("Dumbrăvița", "sat"),
    createLoc("Forosig", "sat"),
    createLoc("Hodiș", "sat"),
    createLoc("Lupoaia", "sat"),
    createLoc("Valea Mare de Codru", "sat"),
    createLoc("Vintere", "sat"),
]),
createComuna("Husasău de Tinca", [
    createLoc("Husasău de Tinca", "sat"),
    createLoc("Fonău", "sat"),
    createLoc("Miersig", "sat"),
    createLoc("Oșand", "sat"),
    createLoc("Sititelec", "sat"),
]),
createComuna("Ineu", [
    createLoc("Ineu", "sat"),
    createLoc("Botean", "sat"),
    createLoc("Husasău de Criș", "sat"),
]),
createComuna("Lazuri de Beiuș", [
    createLoc("Lazuri de Beiuș", "sat"),
    createLoc("Băleni", "sat"),
    createLoc("Cusuiuș", "sat"),
    createLoc("Hinchiriș", "sat"),
]),
createComuna("Lăzăreni", [
    createLoc("Lăzăreni", "sat"),
    createLoc("Bicăcel", "sat"),
    createLoc("Calea Mare", "sat"),
    createLoc("Cărăndeni", "sat"),
    createLoc("Cărănzel", "sat"),
    createLoc("Gepiș", "sat"),
    createLoc("Gruilung", "sat"),
    createLoc("Miheleu", "sat"),
]),
createComuna("Lugașu de Jos", [
    createLoc("Lugașu de Jos", "sat"),
    createLoc("Lugașu de Sus", "sat"),
    createLoc("Urvind", "sat"),
]),
createComuna("Lunca", [
    createLoc("Lunca", "sat"),
    createLoc("Briheni", "sat"),
    createLoc("Hotărel", "sat"),
    createLoc("Seghiște", "sat"),
    createLoc("Sârbești", "sat"),
    createLoc("Șuștiu", "sat"),
]),
createComuna("Mădăras", [
    createLoc("Mădăras", "sat"),
    createLoc("Homorog", "sat"),
    createLoc("Ianoșda", "sat"),
    createLoc("Marțihaz", "sat"),
]),
createComuna("Măgești", [
    createLoc("Măgești", "sat"),
    createLoc("Butani", "sat"),
    createLoc("Cacuciu Nou", "sat"),
    createLoc("Dobricionești", "sat"),
    createLoc("Gălășeni", "sat"),
    createLoc("Josani", "sat"),
    createLoc("Ortiteag", "sat"),
]),
createComuna("Nojorid", [
    createLoc("Nojorid", "sat"),
    createLoc("Apateu", "sat"),
    createLoc("Chișirid", "sat"),
    createLoc("Leș", "sat"),
    createLoc("Livada de Bihor", "sat"),
    createLoc("Păușa", "sat"),
    createLoc("Șauaieu", "sat"),
]),
createComuna("Olcea", [
    createLoc("Olcea", "sat"),
    createLoc("Călacea", "sat"),
    createLoc("Hodișel", "sat"),
    createLoc("Ucuriș", "sat"),
]),
createComuna("Oșorhei", [
    createLoc("Oșorhei", "sat"),
    createLoc("Alparea", "sat"),
    createLoc("Cheriu", "sat"),
    createLoc("Felcheriu", "sat"),
    createLoc("Fughiu", "sat"),
]),
createComuna("Paleu", [
    createLoc("Paleu", "sat"),
    createLoc("Săldăbagiu de Munte", "sat"),
    createLoc("Uileacu de Munte", "sat"),
]),
createComuna("Petreu", [
    createLoc("Petreu", "sat"),
    createLoc("Abrămuț", "sat"),
    createLoc("Crestur", "sat"),
    createLoc("Făncica", "sat"),
]),
createComuna("Pietroasa", [
    createLoc("Pietroasa", "sat"),
    createLoc("Chișcău", "sat"),
    createLoc("Cociuba Mică", "sat"),
    createLoc("Giulești", "sat"),
    createLoc("Gurani", "sat"),
    createLoc("Măgura", "sat"),
    createLoc("Moțești", "sat"),
]),
createComuna("Pocola", [
    createLoc("Pocola", "sat"),
    createLoc("Feneriș", "sat"),
    createLoc("Petrani", "sat"),
    createLoc("Poietari", "sat"),
    createLoc("Sânmartin de Beiuș", "sat"),
]),
createComuna("Pomezeu", [
    createLoc("Pomezeu", "sat"),
    createLoc("Câmpani de Pomezeu", "sat"),
    createLoc("Coșdeni", "sat"),
    createLoc("Hidiș", "sat"),
    createLoc("Lacu Sărat", "sat"),
    createLoc("Sitani", "sat"),
    createLoc("Spinuș de Pomezeu", "sat"),
    createLoc("Vălani de Pomezeu", "sat"),
]),
createComuna("Popești", [
    createLoc("Popești", "sat"),
    createLoc("Bistra", "sat"),
    createLoc("Budoi", "sat"),
    createLoc("Cuzap", "sat"),
    createLoc("Varviz", "sat"),
    createLoc("Vărzari", "sat"),
    createLoc("Voivozi", "sat"),
]),
createComuna("Răbăgani", [
    createLoc("Răbăgani", "sat"),
    createLoc("Albești", "sat"),
    createLoc("Brătești", "sat"),
    createLoc("Săliște de Pomezeu", "sat"),
    createLoc("Săucani", "sat"),
    createLoc("Vărășeni", "sat"),
]),
createComuna("Remetea", [
    createLoc("Remetea", "sat"),
    createLoc("Drăgoteni", "sat"),
    createLoc("Meziad", "sat"),
    createLoc("Petreasa", "sat"),
    createLoc("Șoimuș", "sat"),
]),
createComuna("Rieni", [
    createLoc("Rieni", "sat"),
    createLoc("Cucuceni", "sat"),
    createLoc("Ghighișeni", "sat"),
    createLoc("Petrileni", "sat"),
    createLoc("Sudrigiu", "sat"),
    createLoc("Valea de Jos", "sat"),
]),
createComuna("Roșia", [
    createLoc("Roșia", "sat"),
    createLoc("Lazuri", "sat"),
]),
createComuna("Roșiori", [
    createLoc("Roșiori", "sat"),
    createLoc("Mihai Bravu", "sat"),
    createLoc("Vaida", "sat"),
]),
createComuna("Săcădat", [
    createLoc("Săcădat", "sat"),
    createLoc("Borșa", "sat"),
    createLoc("Săbolciu", "sat"),
]),
createComuna("Sălacea", [
    createLoc("Sălacea", "sat"),
    createLoc("Otomani", "sat"),
]),
createComuna("Sălard", [
    createLoc("Sălard", "sat"),
    createLoc("Hodoș", "sat"),
    createLoc("Sântimreu", "sat"),
]),
createComuna("Sâniob", [
    createLoc("Sâniob", "sat"),
    createLoc("Cenaloș", "sat"),
    createLoc("Ciuhoi", "sat"),
    createLoc("Sfârnaș", "sat"),
]),
createComuna("Sânnicolau Român", [
    createLoc("Sânnicolau Român", "sat"),
    createLoc("Berechiu", "sat"),
    createLoc("Roit", "sat"),
]),
createComuna("Sâmbăta", [
    createLoc("Sâmbăta", "sat"),
    createLoc("Copăceni", "sat"),
    createLoc("Ogești", "sat"),
    createLoc("Rogoz", "sat"),
    createLoc("Rotărești", "sat"),
    createLoc("Zăvoiu", "sat"),
]),
createComuna("Sânmartin", [
    createLoc("Sânmartin", "sat"),
    createLoc("Betfia", "sat"),
    createLoc("Cihei", "sat"),
    createLoc("Cordău", "sat"),
    createLoc("Haieu", "sat"),
    createLoc("Rontău", "sat"),
]),
createComuna("Sântandrei", [
    createLoc("Sântandrei", "sat"),
    createLoc("Palota", "sat"),
]),
createComuna("Sârbi", [
    createLoc("Sârbi", "sat"),
    createLoc("Almașu Mic", "sat"),
    createLoc("Burzuc", "sat"),
    createLoc("Chioag", "sat"),
    createLoc("Fegernic", "sat"),
    createLoc("Fegernicu Nou", "sat"),
    createLoc("Sarcău", "sat"),
]),
createComuna("Spinuș", [
    createLoc("Spinuș", "sat"),
    createLoc("Ciulești", "sat"),
    createLoc("Gurbești", "sat"),
    createLoc("Nădar", "sat"),
    createLoc("Săliște", "sat"),
]),
createComuna("Suplacu de Barcău", [
    createLoc("Suplacu de Barcău", "sat"),
    createLoc("Borumlaca", "sat"),
    createLoc("Dolea", "sat"),
    createLoc("Foglaș", "sat"),
    createLoc("Valea Cerului", "sat"),
    createLoc("Vâlcelele", "sat"),
]),
createComuna("Șimian", [
    createLoc("Șimian", "sat"),
    createLoc("Șilindru", "sat"),
    createLoc("Voivozi", "sat"),
]),
createComuna("Șinteu", [
    createLoc("Șinteu", "sat"),
    createLoc("Huta Voivozi", "sat"),
    createLoc("Socet", "sat"),
    createLoc("Valea Târnei", "sat"),
]),
createComuna("Șoimi", [
    createLoc("Șoimi", "sat"),
    createLoc("Borz", "sat"),
    createLoc("Codru", "sat"),
    createLoc("Dumbrăvița de Codru", "sat"),
    createLoc("Poclușa de Beiuș", "sat"),
    createLoc("Sânnicolau de Beiuș", "sat"),
    createLoc("Ursad", "sat"),
    createLoc("Urviș de Beiuș", "sat"),
]),
createComuna("Șuncuiuș", [
    createLoc("Șuncuiuș", "sat"),
    createLoc("Bălnaca", "sat"),
    createLoc("Bălnaca-Groși", "sat"),
    createLoc("Zece Hotare", "sat"),
]),
createComuna("Tarcea", [
    createLoc("Tarcea", "sat"),
    createLoc("Adoni", "sat"),
    createLoc("Galoșpetreu", "sat"),
]),
createComuna("Tămășeu", [
    createLoc("Tămășeu", "sat"),
    createLoc("Niuved", "sat"),
    createLoc("Parhida", "sat"),
    createLoc("Satu Nou", "sat"),
]),
createComuna("Tărcaia", [
    createLoc("Tărcaia", "sat"),
    createLoc("Mierag", "sat"),
    createLoc("Tărcăița", "sat"),
    createLoc("Totoreni", "sat"),
]),
createComuna("Tăuteu", [
    createLoc("Tăuteu", "sat"),
    createLoc("Bogei", "sat"),
    createLoc("Chiribiș", "sat"),
    createLoc("Ciutelec", "sat"),
    createLoc("Poiana", "sat"),
]),
createComuna("Tileagd", [
    createLoc("Tileagd", "sat"),
    createLoc("Bălaia", "sat"),
    createLoc("Călătani", "sat"),
    createLoc("Poșoloaca", "sat"),
    createLoc("Tilecuș", "sat"),
    createLoc("Uileacu de Criș", "sat"),
]),
createComuna("Tinca", [
    createLoc("Tinca", "sat"),
    createLoc("Belfir", "sat"),
    createLoc("Girișu Negru", "sat"),
    createLoc("Gurbediu", "sat"),
    createLoc("Râpa", "sat"),
]),
createComuna("Toboliu", [
    createLoc("Toboliu", "sat"),
    createLoc("Cheresig", "sat"),
]),
createComuna("Tulca", [
    createLoc("Tulca", "sat"),
    createLoc("Căuașd", "sat"),
]),
createComuna("Țețchea", [
    createLoc("Țețchea", "sat"),
    createLoc("Hotar", "sat"),
    createLoc("Subpiatră", "sat"),
    createLoc("Telechiu", "sat"),
]),
createComuna("Uileacu de Beiuș", [
    createLoc("Uileacu de Beiuș", "sat"),
    createLoc("Forău", "sat"),
    createLoc("Prisaca", "sat"),
    createLoc("Vălanii de Beiuș", "sat"),
]),
createComuna("Vadu Crișului", [
    createLoc("Vadu Crișului", "sat"),
    createLoc("Birtin", "sat"),
    createLoc("Tomnatic", "sat"),
    createLoc("Topa de Criș", "sat"),
]),
createComuna("Viișoara", [
    createLoc("Viișoara", "sat"),
    createLoc("Izvoarele", "sat"),
    createLoc("Pădureni", "sat"),
    createLoc("Reghea", "sat"),
]),
createComuna("Vârciorog", [
    createLoc("Vârciorog", "sat"),
    createLoc("Fâșca", "sat"),
    createLoc("Surducel", "sat"),
    createLoc("Șerghiș", "sat"),
]),

									  
			
];
?>