<?php
$comune = [
    createComuna("Bărăganul", [
        createLoc("Bărăganul", "sat", createAdresaCompleta("sat Bărăganul, comuna Bărăganul, judetul Brăila, România", "sat Baraganul, comuna Baraganul, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Bărăganul, judetul BRAILA, România", "comuna Baraganul, judetul BRAILA, Romania")),
    createComuna("Berteștii de Jos", [
        createLoc("Berteștii de Jos", "sat", createAdresaCompleta("sat Berteștii de Jos, comuna Berteștii de Jos, judetul Brăila, România", "sat Bertestii de Jos, comuna Bertestii de Jos, judetul Braila, Romania")),
        createLoc("Berteștii de Sus", "sat", createAdresaCompleta("sat Berteștii de Sus, comuna Berteștii de Jos, judetul Brăila, România", "sat Bertestii de Sus, comuna Bertestii de Jos, judetul Braila, Romania")),
        createLoc("Gura Călmățui", "sat", createAdresaCompleta("sat Gura Călmățui, comuna Berteștii de Jos, judetul Brăila, România", "sat Gura Calmatui, comuna Bertestii de Jos, judetul Braila, Romania")),
        createLoc("Gura Gârluței", "sat", createAdresaCompleta("sat Gura Gârluței, comuna Berteștii de Jos, judetul Brăila, România", "sat Gura Garlutei, comuna Bertestii de Jos, judetul Braila, Romania")),
        createLoc("Nicolești", "sat", createAdresaCompleta("sat Nicolești, comuna Berteștii de Jos, judetul Brăila, România", "sat Nicolesti, comuna Bertestii de Jos, judetul Braila, Romania")),
        createLoc("Spiru Haret", "sat", createAdresaCompleta("sat Spiru Haret, comuna Berteștii de Jos, judetul Brăila, România", "sat Spiru Haret, comuna Bertestii de Jos, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Berteștii de Jos, judetul BRAILA, România", "comuna Bertestii de Jos, judetul BRAILA, Romania")),
    createComuna("Bordei Verde", [
        createLoc("Bordei Verde", "sat", createAdresaCompleta("sat Bordei Verde, comuna Bordei Verde, judetul Brăila, România", "sat Bordei Verde, comuna Bordei Verde, judetul Braila, Romania")),
        createLoc("Constantin Gabrielescu", "sat", createAdresaCompleta("sat Constantin Gabrielescu, comuna Bordei Verde, judetul Brăila, România", "sat Constantin Gabrielescu, comuna Bordei Verde, judetul Braila, Romania")),
        createLoc("Filiu", "sat", createAdresaCompleta("sat Filiu, comuna Bordei Verde, judetul Brăila, România", "sat Filiu, comuna Bordei Verde, judetul Braila, Romania")),
        createLoc("Lișcoteanca", "sat", createAdresaCompleta("sat Lișcoteanca, comuna Bordei Verde, judetul Brăila, România", "sat Liscoteanca, comuna Bordei Verde, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Bordei Verde, judetul BRAILA, România", "comuna Bordei Verde, judetul BRAILA, Romania")),
    createComuna("Cazasu", [
        createLoc("Cazasu", "sat", createAdresaCompleta("sat Cazasu, comuna Cazasu, judetul Brăila, România", "sat Cazasu, comuna Cazasu, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Cazasu, judetul BRAILA, România", "comuna Cazasu, judetul BRAILA, Romania")),
    createComuna("Chiscani", [
        createLoc("Chiscani", "sat", createAdresaCompleta("sat Chiscani, comuna Chiscani, judetul Brăila, România", "sat Chiscani, comuna Chiscani, judetul Braila, Romania")),
        createLoc("Lacu Sărat", "sat", createAdresaCompleta("sat Lacu Sărat, comuna Chiscani, judetul Brăila, România", "sat Lacu Sarat, comuna Chiscani, judetul Braila, Romania")),
        createLoc("Vărsătura", "sat", createAdresaCompleta("sat Vărsătura, comuna Chiscani, judetul Brăila, România", "sat Varsatura, comuna Chiscani, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Chiscani, judetul BRAILA, România", "comuna Chiscani, judetul BRAILA, Romania")),
    createComuna("Ciocile", [
        createLoc("Ciocile", "sat", createAdresaCompleta("sat Ciocile, comuna Ciocile, judetul Brăila, România", "sat Ciocile, comuna Ciocile, judetul Braila, Romania")),
        createLoc("Chichinețu", "sat", createAdresaCompleta("sat Chichinețu, comuna Ciocile, judetul Brăila, România", "sat Chichinetu, comuna Ciocile, judetul Braila, Romania")),
        createLoc("Chioibășești", "sat", createAdresaCompleta("sat Chioibășești, comuna Ciocile, judetul Brăila, România", "sat Chioibasesti, comuna Ciocile, judetul Braila, Romania")),
        createLoc("Odăieni", "sat", createAdresaCompleta("sat Odăieni, comuna Ciocile, judetul Brăila, România", "sat Odaieni, comuna Ciocile, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Ciocile, judetul BRAILA, România", "comuna Ciocile, judetul BRAILA, Romania")),
    createComuna("Cireșu", [
        createLoc("Cireșu", "sat", createAdresaCompleta("sat Cireșu, comuna Cireșu, judetul Brăila, România", "sat Ciresu, comuna Ciresu, judetul Braila, Romania")),
        createLoc("Batogu", "sat", createAdresaCompleta("sat Batogu, comuna Cireșu, judetul Brăila, România", "sat Batogu, comuna Ciresu, judetul Braila, Romania")),
        createLoc("Ionești", "sat", createAdresaCompleta("sat Ionești, comuna Cireșu, judetul Brăila, România", "sat Ionesti, comuna Ciresu, judetul Braila, Romania")),
        createLoc("Scărlătești", "sat", createAdresaCompleta("sat Scărlătești, comuna Cireșu, judetul Brăila, România", "sat Scarlatesti, comuna Ciresu, judetul Braila, Romania")),
        createLoc("Vultureni", "sat", createAdresaCompleta("sat Vultureni, comuna Cireșu, judetul Brăila, România", "sat Vultureni, comuna Ciresu, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Cireșu, judetul BRAILA, România", "comuna Ciresu, judetul BRAILA, Romania")),
    createComuna("Dudești", [
        createLoc("Dudești", "sat", createAdresaCompleta("sat Dudești, comuna Dudești, judetul Brăila, România", "sat Dudesti, comuna Dudesti, judetul Braila, Romania")),
        createLoc("Brătilești", "sat", createAdresaCompleta("sat Brătilești, comuna Dudești, judetul Brăila, România", "sat Bratilesti, comuna Dudesti, judetul Braila, Romania")),
        createLoc("Călmatuiu", "sat", createAdresaCompleta("sat Călmatuiu, comuna Dudești, judetul Brăila, România", "sat Calmatuiu, comuna Dudesti, judetul Braila, Romania")),
        createLoc("Călmatuiu de Sus", "sat", createAdresaCompleta("sat Călmatuiu de Sus, comuna Dudești, judetul Brăila, România", "sat Calmatuiu de Sus, comuna Dudesti, judetul Braila, Romania")),
        createLoc("Stoicanesti", "sat", createAdresaCompleta("sat Stoicanesti, comuna Dudești, judetul Brăila, România", "sat Stoicanesti, comuna Dudesti, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Dudești, judetul BRAILA, România", "comuna Dudesti, judetul BRAILA, Romania")),
    createComuna("Frecăței", [
        createLoc("Frecăței", "sat", createAdresaCompleta("sat Frecăței, comuna Frecăței, judetul Brăila, România", "sat Frecatei, comuna Frecatei, judetul Braila, Romania")),
        createLoc("Căldărușa", "sat", createAdresaCompleta("sat Căldărușa, comuna Frecăței, judetul Brăila, România", "sat Caldarusa, comuna Frecatei, judetul Braila, Romania")),
        createLoc("Curcani", "sat", createAdresaCompleta("sat Curcani, comuna Frecăței, judetul Brăila, România", "sat Curcani, comuna Frecatei, judetul Braila, Romania")),
        createLoc("Mihail Kogălniceanu", "sat", createAdresaCompleta("sat Mihail Kogălniceanu, comuna Frecăței, judetul Brăila, România", "sat Mihail Kogalniceanu, comuna Frecatei, judetul Braila, Romania")),
        createLoc("Permunian", "sat", createAdresaCompleta("sat Permunian, comuna Frecăței, judetul Brăila, România", "sat Permunian, comuna Frecatei, judetul Braila, Romania")),
        createLoc("Plopi", "sat", createAdresaCompleta("sat Plopi, comuna Frecăței, judetul Brăila, România", "sat Plopi, comuna Frecatei, judetul Braila, Romania")),
        createLoc("Sălcioara", "sat", createAdresaCompleta("sat Sălcioara, comuna Frecăței, judetul Brăila, România", "sat Salcioara, comuna Frecatei, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Frecăței, judetul BRAILA, România", "comuna Frecatei, judetul BRAILA, Romania")),
    createComuna("Galbenu", [
        createLoc("Galbenu", "sat", createAdresaCompleta("sat Galbenu, comuna Galbenu, judetul Brăila, România", "sat Galbenu, comuna Galbenu, judetul Braila, Romania")),
        createLoc("Drogu", "sat", createAdresaCompleta("sat Drogu, comuna Galbenu, judetul Brăila, România", "sat Drogu, comuna Galbenu, judetul Braila, Romania")),
        createLoc("Răducani", "sat", createAdresaCompleta("sat Răducani, comuna Galbenu, judetul Brăila, România", "sat Raducani, comuna Galbenu, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Galbenu, judetul BRAILA, România", "comuna Galbenu, judetul BRAILA, Romania")),
    createComuna("Gemenele", [
        createLoc("Gemenele", "sat", createAdresaCompleta("sat Gemenele, comuna Gemenele, judetul Brăila, România", "sat Gemenele, comuna Gemenele, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Gemenele, judetul BRAILA, România", "comuna Gemenele, judetul BRAILA, Romania")),
    createComuna("Grădiștea", [
        createLoc("Grădiștea", "sat", createAdresaCompleta("sat Grădiștea, comuna Grădiștea, judetul Brăila, România", "sat Gradistea, comuna Gradistea, judetul Braila, Romania")),
        createLoc("Constantinești", "sat", createAdresaCompleta("sat Constantinești, comuna Grădiștea, judetul Brăila, România", "sat Constantinesti, comuna Gradistea, judetul Braila, Romania")),
        createLoc("Ichim", "sat", createAdresaCompleta("sat Ichim, comuna Grădiștea, judetul Brăila, România", "sat Ichim, comuna Gradistea, judetul Braila, Romania")),
        createLoc("Lanurile", "sat", createAdresaCompleta("sat Lanurile, comuna Grădiștea, judetul Brăila, România", "sat Lanurile, comuna Gradistea, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Grădiștea, judetul BRAILA, România", "comuna Gradistea, judetul BRAILA, Romania")),
    createComuna("Gropeni", [
        createLoc("Gropeni", "sat", createAdresaCompleta("sat Gropeni, comuna Gropeni, judetul Brăila, România", "sat Gropeni, comuna Gropeni, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Gropeni, judetul BRAILA, România", "comuna Gropeni, judetul BRAILA, Romania")),
    createComuna("Jirlău", [
        createLoc("Jirlău", "sat", createAdresaCompleta("sat Jirlău, comuna Jirlău, judetul Brăila, România", "sat Jirlau, comuna Jirlau, judetul Braila, Romania")),
        createLoc("Cotul", "sat", createAdresaCompleta("sat Cotul, comuna Jirlău, judetul Brăila, România", "sat Cotul, comuna Jirlau, judetul Braila, Romania")),
        createLoc("Felesti", "sat", createAdresaCompleta("sat Felesti, comuna Jirlău, judetul Brăila, România", "sat Felesti, comuna Jirlau, judetul Braila, Romania")),
        createLoc("Matei", "sat", createAdresaCompleta("sat Matei, comuna Jirlău, judetul Brăila, România", "sat Matei, comuna Jirlau, judetul Braila, Romania")),
        createLoc("Modoșa", "sat", createAdresaCompleta("sat Modoșa, comuna Jirlău, judetul Brăila, România", "sat Modosa, comuna Jirlau, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Jirlău, judetul BRAILA, România", "comuna Jirlau, judetul BRAILA, Romania")),
    createComuna("Mărașu", [
        createLoc("Mărașu", "sat", createAdresaCompleta("sat Mărașu, comuna Mărașu, judetul Brăila, România", "sat Marasu, comuna Marasu, judetul Braila, Romania")),
        createLoc("Căpățânești", "sat", createAdresaCompleta("sat Căpățânești, comuna Mărașu, judetul Brăila, România", "sat Capatanesti, comuna Marasu, judetul Braila, Romania")),
        createLoc("Corbu", "sat", createAdresaCompleta("sat Corbu, comuna Mărașu, judetul Brăila, România", "sat Corbu, comuna Marasu, judetul Braila, Romania")),
        createLoc("Ibrianu", "sat", createAdresaCompleta("sat Ibrianu, comuna Mărașu, judetul Brăila, România", "sat Ibrianu, comuna Marasu, judetul Braila, Romania")),
        createLoc("Linia", "sat", createAdresaCompleta("sat Linia, comuna Mărașu, judetul Brăila, România", "sat Linia, comuna Marasu, judetul Braila, Romania")),
        createLoc("Măxineni", "sat", createAdresaCompleta("sat Măxineni, comuna Mărașu, judetul Brăila, România", "sat Maxineni, comuna Marasu, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Mărașu, judetul BRAILA, România", "comuna Marasu, judetul BRAILA, Romania")),
    createComuna("Măxineni", [
        createLoc("Măxineni", "sat", createAdresaCompleta("sat Măxineni, comuna Măxineni, judetul Brăila, România", "sat Maxineni, comuna Maxineni, judetul Braila, Romania")),
        createLoc("Corodin", "sat", createAdresaCompleta("sat Corodin, comuna Măxineni, judetul Brăila, România", "sat Corodin, comuna Maxineni, judetul Braila, Romania")),
        createLoc("Mihai Viteazu", "sat", createAdresaCompleta("sat Mihai Viteazu, comuna Măxineni, judetul Brăila, România", "sat Mihai Viteazu, comuna Maxineni, judetul Braila, Romania")),
        createLoc("Șerbeștii Vechi", "sat", createAdresaCompleta("sat Șerbeștii Vechi, comuna Măxineni, judetul Brăila, România", "sat Serbestii Vechi, comuna Maxineni, judetul Braila, Romania")),
        createLoc("Zăvoaia", "sat", createAdresaCompleta("sat Zăvoaia, comuna Măxineni, judetul Brăila, România", "sat Zavoaia, comuna Maxineni, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Măxineni, judetul BRAILA, România", "comuna Maxineni, judetul BRAILA, Romania")),
    createComuna("Mircea Vodă", [
        createLoc("Mircea Vodă", "sat", createAdresaCompleta("sat Mircea Vodă, comuna Mircea Vodă, judetul Brăila, România", "sat Mircea Voda, comuna Mircea Voda, judetul Braila, Romania")),
        createLoc("Corbu", "sat", createAdresaCompleta("sat Corbu, comuna Mircea Vodă, judetul Brăila, România", "sat Corbu, comuna Mircea Voda, judetul Braila, Romania")),
        createLoc("Lanurile", "sat", createAdresaCompleta("sat Lanurile, comuna Mircea Vodă, judetul Brăila, România", "sat Lanurile, comuna Mircea Voda, judetul Braila, Romania")),
        createLoc("Poșta", "sat", createAdresaCompleta("sat Poșta, comuna Mircea Vodă, judetul Brăila, România", "sat Posta, comuna Mircea Voda, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Mircea Vodă, judetul BRAILA, România", "comuna Mircea Voda, judetul BRAILA, Romania")),
    createComuna("Movila Miresii", [
        createLoc("Movila Miresii", "sat", createAdresaCompleta("sat Movila Miresii, comuna Movila Miresii, judetul Brăila, România", "sat Movila Miresii, comuna Movila Miresii, judetul Braila, Romania")),
        createLoc("Gulia", "sat", createAdresaCompleta("sat Gulia, comuna Movila Miresii, judetul Brăila, România", "sat Gulia, comuna Movila Miresii, judetul Braila, Romania")),
        createLoc("Mihail Kogălniceanu", "sat", createAdresaCompleta("sat Mihail Kogălniceanu, comuna Movila Miresii, judetul Brăila, România", "sat Mihail Kogalniceanu, comuna Movila Miresii, judetul Braila, Romania")),
        createLoc("Panduru", "sat", createAdresaCompleta("sat Panduru, comuna Movila Miresii, judetul Brăila, România", "sat Panduru, comuna Movila Miresii, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Movila Miresii, judetul BRAILA, România", "comuna Movila Miresii, judetul BRAILA, Romania")),
    createComuna("Racovița", [
        createLoc("Racovița", "sat", createAdresaCompleta("sat Racovița, comuna Racovița, judetul Brăila, România", "sat Racovita, comuna Racovita, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Racovița, judetul BRAILA, România", "comuna Racovita, judetul BRAILA, Romania")),
    createComuna("Râmnicelu", [
        createLoc("Râmnicelu", "sat", createAdresaCompleta("sat Râmnicelu, comuna Râmnicelu, judetul Brăila, România", "sat Ramnicelu, comuna Ramnicelu, judetul Braila, Romania")),
        createLoc("Băile Bălcești", "sat", createAdresaCompleta("sat Băile Bălcești, comuna Râmnicelu, judetul Brăila, România", "sat Baile Balcesti, comuna Ramnicelu, judetul Braila, Romania")),
        createLoc("Ciorăști", "sat", createAdresaCompleta("sat Ciorăști, comuna Râmnicelu, judetul Brăila, România", "sat Ciorasti, comuna Ramnicelu, judetul Braila, Romania")),
        createLoc("Gara Râmnicelu", "sat", createAdresaCompleta("sat Gara Râmnicelu, comuna Râmnicelu, judetul Brăila, România", "sat Gara Ramnicelu, comuna Ramnicelu, judetul Braila, Romania")),
        createLoc("Gura Călmățui", "sat", createAdresaCompleta("sat Gura Călmățui, comuna Râmnicelu, judetul Brăila, România", "sat Gura Calmatui, comuna Ramnicelu, judetul Braila, Romania")),
        createLoc("Stoian", "sat", createAdresaCompleta("sat Stoian, comuna Râmnicelu, judetul Brăila, România", "sat Stoian, comuna Ramnicelu, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Râmnicelu, judetul BRAILA, România", "comuna Ramnicelu, judetul BRAILA, Romania")),
    createComuna("Romanu", [
        createLoc("Romanu", "sat", createAdresaCompleta("sat Romanu, comuna Romanu, judetul Brăila, România", "sat Romanu, comuna Romanu, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Romanu, judetul BRAILA, România", "comuna Romanu, judetul BRAILA, Romania")),
    createComuna("Roșiori", [
        createLoc("Roșiori", "sat", createAdresaCompleta("sat Roșiori, comuna Roșiori, judetul Brăila, România", "sat Rosiori, comuna Rosiori, judetul Braila, Romania")),
        createLoc("Balintesti", "sat", createAdresaCompleta("sat Balintesti, comuna Roșiori, judetul Brăila, România", "sat Balintesti, comuna Rosiori, judetul Braila, Romania")),
        createLoc("Băltăgari", "sat", createAdresaCompleta("sat Băltăgari, comuna Roșiori, judetul Brăila, România", "sat Baltagari, comuna Rosiori, judetul Braila, Romania")),
        createLoc("Căldărușa", "sat", createAdresaCompleta("sat Căldărușa, comuna Roșiori, judetul Brăila, România", "sat Caldarusa, comuna Rosiori, judetul Braila, Romania")),
        createLoc("Chioibasesti", "sat", createAdresaCompleta("sat Chioibasesti, comuna Roșiori, judetul Brăila, România", "sat Chioibasesti, comuna Rosiori, judetul Braila, Romania")),
        createLoc("Chiraz", "sat", createAdresaCompleta("sat Chiraz, comuna Roșiori, judetul Brăila, România", "sat Chiraz, comuna Rosiori, judetul Braila, Romania")),
        createLoc("Corbu", "sat", createAdresaCompleta("sat Corbu, comuna Roșiori, judetul Brăila, România", "sat Corbu, comuna Rosiori, judetul Braila, Romania")),
        createLoc("Cuza Voda", "sat", createAdresaCompleta("sat Cuza Voda, comuna Roșiori, judetul Brăila, România", "sat Cuza Voda, comuna Rosiori, judetul Braila, Romania")),
        createLoc("Florica", "sat", createAdresaCompleta("sat Florica, comuna Roșiori, judetul Brăila, România", "sat Florica, comuna Rosiori, judetul Braila, Romania")),
        createLoc("Lacu Saulei", "sat", createAdresaCompleta("sat Lacu Saulei, comuna Roșiori, judetul Brăila, România", "sat Lacu Saulei, comuna Rosiori, judetul Braila, Romania")),
        createLoc("Mihail Kogalniceanu", "sat", createAdresaCompleta("sat Mihail Kogalniceanu, comuna Roșiori, judetul Brăila, România", "sat Mihail Kogalniceanu, comuna Rosiori, judetul Braila, Romania")),
        createLoc("Morotesti", "sat", createAdresaCompleta("sat Morotesti, comuna Roșiori, judetul Brăila, România", "sat Morotesti, comuna Rosiori, judetul Braila, Romania")),
        createLoc("Plopi", "sat", createAdresaCompleta("sat Plopi, comuna Roșiori, judetul Brăila, România", "sat Plopi, comuna Rosiori, judetul Braila, Romania")),
        createLoc("Valea Lunga", "sat", createAdresaCompleta("sat Valea Lunga, comuna Roșiori, judetul Brăila, România", "sat Valea Lunga, comuna Rosiori, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Roșiori, judetul BRAILA, România", "comuna Rosiori, judetul BRAILA, Romania")),
    createComuna("Salcia Tudor", [
        createLoc("Salcia Tudor", "sat", createAdresaCompleta("sat Salcia Tudor, comuna Salcia Tudor, judetul Brăila, România", "sat Salcia Tudor, comuna Salcia Tudor, judetul Braila, Romania")),
        createLoc("Berlesu", "sat", createAdresaCompleta("sat Berlesu, comuna Salcia Tudor, judetul Brăila, România", "sat Berlesu, comuna Salcia Tudor, judetul Braila, Romania")),
        createLoc("Gheorghe Doja", "sat", createAdresaCompleta("sat Gheorghe Doja, comuna Salcia Tudor, judetul Brăila, România", "sat Gheorghe Doja, comuna Salcia Tudor, judetul Braila, Romania")),
        createLoc("Silistraru", "sat", createAdresaCompleta("sat Silistraru, comuna Salcia Tudor, judetul Brăila, România", "sat Silistraru, comuna Salcia Tudor, judetul Braila, Romania")),
        createLoc("Tătaru", "sat", createAdresaCompleta("sat Tătaru, comuna Salcia Tudor, judetul Brăila, România", "sat Tataru, comuna Salcia Tudor, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Salcia Tudor, judetul BRAILA, România", "comuna Salcia Tudor, judetul BRAILA, Romania")),
    createComuna("Scorțaru Nou", [
        createLoc("Scorțaru Nou", "sat", createAdresaCompleta("sat Scorțaru Nou, comuna Scorțaru Nou, judetul Brăila, România", "sat Scortaru Nou, comuna Scortaru Nou, judetul Braila, Romania")),
        createLoc("Scorțaru Vechi", "sat", createAdresaCompleta("sat Scorțaru Vechi, comuna Scorțaru Nou, judetul Brăila, România", "sat Scortaru Vechi, comuna Scortaru Nou, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Scorțaru Nou, judetul BRAILA, România", "comuna Scortaru Nou, judetul BRAILA, Romania")),
    createComuna("Siliștea", [
        createLoc("Siliștea", "sat", createAdresaCompleta("sat Siliștea, comuna Siliștea, judetul Brăila, România", "sat Silistea, comuna Silistea, judetul Braila, Romania")),
        createLoc("Gemenele", "sat", createAdresaCompleta("sat Gemenele, comuna Siliștea, judetul Brăila, România", "sat Gemenele, comuna Silistea, judetul Braila, Romania")),
        createLoc("Mihail Kogălniceanu", "sat", createAdresaCompleta("sat Mihail Kogălniceanu, comuna Siliștea, judetul Brăila, România", "sat Mihail Kogalniceanu, comuna Silistea, judetul Braila, Romania")),
        createLoc("Zamfira", "sat", createAdresaCompleta("sat Zamfira, comuna Siliștea, judetul Brăila, România", "sat Zamfira, comuna Silistea, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Siliștea, judetul BRAILA, România", "comuna Silistea, judetul BRAILA, Romania")),
    createComuna("Stăncuța", [
        createLoc("Stăncuța", "sat", createAdresaCompleta("sat Stăncuța, comuna Stăncuța, judetul Brăila, România", "sat Stancuta, comuna Stancuta, judetul Braila, Romania")),
        createLoc("Aristed", "sat", createAdresaCompleta("sat Aristed, comuna Stăncuța, judetul Brăila, România", "sat Aristed, comuna Stancuta, judetul Braila, Romania")),
        createLoc("Chioibășești", "sat", createAdresaCompleta("sat Chioibășești, comuna Stăncuța, judetul Brăila, România", "sat Chioibasesti, comuna Stancuta, judetul Braila, Romania")),
        createLoc("Hultanesti", "sat", createAdresaCompleta("sat Hultanesti, comuna Stăncuța, judetul Brăila, România", "sat Hultanesti, comuna Stancuta, judetul Braila, Romania")),
        createLoc("Lunca", "sat", createAdresaCompleta("sat Lunca, comuna Stăncuța, judetul Brăila, România", "sat Lunca, comuna Stancuta, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Stăncuța, judetul BRAILA, România", "comuna Stancuta, judetul BRAILA, Romania")),
    createComuna("Surdila-Găiseanca", [
        createLoc("Surdila-Găiseanca", "sat", createAdresaCompleta("sat Surdila-Găiseanca, comuna Surdila-Găiseanca, judetul Brăila, România", "sat Surdila-Gaiseanca, comuna Surdila-Gaiseanca, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Surdila-Găiseanca, judetul BRAILA, România", "comuna Surdila-Gaiseanca, judetul BRAILA, Romania")),
    createComuna("Surdila-Greci", [
        createLoc("Surdila-Greci", "sat", createAdresaCompleta("sat Surdila-Greci, comuna Surdila-Greci, judetul Brăila, România", "sat Surdila-Greci, comuna Surdila-Greci, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Surdila-Greci, judetul BRAILA, România", "comuna Surdila-Greci, judetul BRAILA, Romania")),
    createComuna("Șuțești", [
        createLoc("Șuțești", "sat", createAdresaCompleta("sat Șuțești, comuna Șuțești, judetul Brăila, România", "sat Sutesti, comuna Sutesti, judetul Braila, Romania")),
        createLoc("Berlesu", "sat", createAdresaCompleta("sat Berlesu, comuna Șuțești, judetul Brăila, România", "sat Berlesu, comuna Sutesti, judetul Braila, Romania")),
        createLoc("Condrea", "sat", createAdresaCompleta("sat Condrea, comuna Șuțești, judetul Brăila, România", "sat Condrea, comuna Sutesti, judetul Braila, Romania")),
        createLoc("Mihail Kogălniceanu", "sat", createAdresaCompleta("sat Mihail Kogălniceanu, comuna Șuțești, judetul Brăila, România", "sat Mihail Kogalniceanu, comuna Sutesti, judetul Braila, Romania")),
        createLoc("Plopi", "sat", createAdresaCompleta("sat Plopi, comuna Șuțești, judetul Brăila, România", "sat Plopi, comuna Sutesti, judetul Braila, Romania")),
        createLoc("Stoicanesti", "sat", createAdresaCompleta("sat Stoicanesti, comuna Șuțești, judetul Brăila, România", "sat Stoicanesti, comuna Sutesti, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Șuțești, judetul BRAILA, România", "comuna Sutesti, judetul BRAILA, Romania")),
    createComuna("Tichilești", [
        createLoc("Tichilești", "sat", createAdresaCompleta("sat Tichilești, comuna Tichilești, judetul Brăila, România", "sat Tichilesti, comuna Tichilesti, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Tichilești, judetul BRAILA, România", "comuna Tichilesti, judetul BRAILA, Romania")),
    createComuna("Traian", [
        createLoc("Traian", "sat", createAdresaCompleta("sat Traian, comuna Traian, judetul Brăila, România", "sat Traian, comuna Traian, judetul Braila, Romania")),
        createLoc("Călmatuiu", "sat", createAdresaCompleta("sat Călmatuiu, comuna Traian, judetul Brăila, România", "sat Calmatuiu, comuna Traian, judetul Braila, Romania")),
        createLoc("Călmatuiu de Sus", "sat", createAdresaCompleta("sat Călmatuiu de Sus, comuna Traian, judetul Brăila, România", "sat Calmatuiu de Sus, comuna Traian, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Traian, judetul BRAILA, România", "comuna Traian, judetul BRAILA, Romania")),
    createComuna("Tudor Vladimirescu", [
        createLoc("Tudor Vladimirescu", "sat", createAdresaCompleta("sat Tudor Vladimirescu, comuna Tudor Vladimirescu, judetul Brăila, România", "sat Tudor Vladimirescu, comuna Tudor Vladimirescu, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Tudor Vladimirescu, judetul BRAILA, România", "comuna Tudor Vladimirescu, judetul BRAILA, Romania")),
    createComuna("Tufești", [
        createLoc("Tufești", "sat", createAdresaCompleta("sat Tufești, comuna Tufești, judetul Brăila, România", "sat Tufesti, comuna Tufesti, judetul Braila, Romania")),
        createLoc("Făurești", "sat", createAdresaCompleta("sat Făurești, comuna Tufești, judetul Brăila, România", "sat Fauresti, comuna Tufesti, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Tufești, judetul BRAILA, România", "comuna Tufesti, judetul BRAILA, Romania")),
    createComuna("Ulmu", [
        createLoc("Ulmu", "sat", createAdresaCompleta("sat Ulmu, comuna Ulmu, judetul Brăila, România", "sat Ulmu, comuna Ulmu, judetul Braila, Romania")),
        createLoc("Il Independenta", "sat", createAdresaCompleta("sat Il Independenta, comuna Ulmu, judetul Brăila, România", "sat Il Independenta, comuna Ulmu, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Ulmu, judetul BRAILA, România", "comuna Ulmu, judetul BRAILA, Romania")),
    createComuna("Unirea", [
        createLoc("Unirea", "sat", createAdresaCompleta("sat Unirea, comuna Unirea, judetul Brăila, România", "sat Unirea, comuna Unirea, judetul Braila, Romania")),
        createLoc("Buzia", "sat", createAdresaCompleta("sat Buzia, comuna Unirea, judetul Brăila, România", "sat Buzia, comuna Unirea, judetul Braila, Romania")),
        createLoc("Hagiești", "sat", createAdresaCompleta("sat Hagiești, comuna Unirea, judetul Brăila, România", "sat Hagiesti, comuna Unirea, judetul Braila, Romania")),
        createLoc("Ion Ghica", "sat", createAdresaCompleta("sat Ion Ghica, comuna Unirea, judetul Brăila, România", "sat Ion Ghica, comuna Unirea, judetul Braila, Romania")),
        createLoc("Lunca", "sat", createAdresaCompleta("sat Lunca, comuna Unirea, judetul Brăila, România", "sat Lunca, comuna Unirea, judetul Braila, Romania")),
        createLoc("Marascu", "sat", createAdresaCompleta("sat Marascu, comuna Unirea, judetul Brăila, România", "sat Marascu, comuna Unirea, judetul Braila, Romania")),
        createLoc("Stoianesti", "sat", createAdresaCompleta("sat Stoianesti, comuna Unirea, judetul Brăila, România", "sat Stoianesti, comuna Unirea, judetul Braila, Romania")),
        createLoc("Valea Nazarcu", "sat", createAdresaCompleta("sat Valea Nazarcu, comuna Unirea, judetul Brăila, România", "sat Valea Nazarcu, comuna Unirea, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Unirea, judetul BRAILA, România", "comuna Unirea, judetul BRAILA, Romania")),
    createComuna("Vădeni", [
        createLoc("Vădeni", "sat", createAdresaCompleta("sat Vădeni, comuna Vădeni, judetul Brăila, România", "sat Vadeni, comuna Vadeni, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Vădeni, judetul BRAILA, România", "comuna Vadeni, judetul BRAILA, Romania")),
    createComuna("Victoria", [
        createLoc("Victoria", "sat", createAdresaCompleta("sat Victoria, comuna Victoria, judetul Brăila, România", "sat Victoria, comuna Victoria, judetul Braila, Romania")),
        createLoc("Mihail Kogălniceanu", "sat", createAdresaCompleta("sat Mihail Kogălniceanu, comuna Victoria, judetul Brăila, România", "sat Mihail Kogalniceanu, comuna Victoria, judetul Braila, Romania")),
        createLoc("Vultureni", "sat", createAdresaCompleta("sat Vultureni, comuna Victoria, judetul Brăila, România", "sat Vultureni, comuna Victoria, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Victoria, judetul BRAILA, România", "comuna Victoria, judetul BRAILA, Romania")),
    createComuna("Vișani", [
        createLoc("Vișani", "sat", createAdresaCompleta("sat Vișani, comuna Vișani, judetul Brăila, România", "sat Visani, comuna Visani, judetul Braila, Romania")),
        createLoc("Bradet", "sat", createAdresaCompleta("sat Bradet, comuna Vișani, judetul Brăila, România", "sat Bradet, comuna Visani, judetul Braila, Romania")),
        createLoc("Căldărușa", "sat", createAdresaCompleta("sat Căldărușa, comuna Vișani, judetul Brăila, România", "sat Caldarusa, comuna Visani, judetul Braila, Romania")),
        createLoc("Mihail Kogălniceanu", "sat", createAdresaCompleta("sat Mihail Kogălniceanu, comuna Vișani, judetul Brăila, România", "sat Mihail Kogalniceanu, comuna Visani, judetul Braila, Romania")),
        createLoc("Plopi", "sat", createAdresaCompleta("sat Plopi, comuna Vișani, judetul Brăila, România", "sat Plopi, comuna Visani, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Vișani, judetul BRAILA, România", "comuna Visani, judetul BRAILA, Romania")),
    createComuna("Viziru", [
        createLoc("Viziru", "sat", createAdresaCompleta("sat Viziru, comuna Viziru, judetul Brăila, România", "sat Viziru, comuna Viziru, judetul Braila, Romania")),
        createLoc("Căldărușa", "sat", createAdresaCompleta("sat Căldărușa, comuna Viziru, judetul Brăila, România", "sat Caldarusa, comuna Viziru, judetul Braila, Romania")),
        createLoc("Stoicanesti", "sat", createAdresaCompleta("sat Stoicanesti, comuna Viziru, judetul Brăila, România", "sat Stoicanesti, comuna Viziru, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Viziru, judetul BRAILA, România", "comuna Viziru, judetul BRAILA, Romania")),
    createComuna("Zăvoaia", [
        createLoc("Zăvoaia", "sat", createAdresaCompleta("sat Zăvoaia, comuna Zăvoaia, judetul Brăila, România", "sat Zavoaia, comuna Zavoaia, judetul Braila, Romania")),
        createLoc("Călmatuiu", "sat", createAdresaCompleta("sat Călmatuiu, comuna Zăvoaia, judetul Brăila, România", "sat Calmatuiu, comuna Zavoaia, judetul Braila, Romania")),
        createLoc("Căldărușa", "sat", createAdresaCompleta("sat Căldărușa, comuna Zăvoaia, judetul Brăila, România", "sat Caldarusa, comuna Zavoaia, judetul Braila, Romania")),
        createLoc("Chichineti", "sat", createAdresaCompleta("sat Chichineti, comuna Zăvoaia, judetul Brăila, România", "sat Chichineti, comuna Zavoaia, judetul Braila, Romania")),
        createLoc("Mihail Kogălniceanu", "sat", createAdresaCompleta("sat Mihail Kogălniceanu, comuna Zăvoaia, judetul Brăila, România", "sat Mihail Kogalniceanu, comuna Zavoaia, judetul Braila, Romania")),
        createLoc("Stoicanesti", "sat", createAdresaCompleta("sat Stoicanesti, comuna Zăvoaia, judetul Brăila, România", "sat Stoicanesti, comuna Zavoaia, judetul Braila, Romania")),
    ], createAdresaCompleta("comuna Zăvoaia, judetul BRAILA, România", "comuna Zavoaia, judetul BRAILA, Romania")),
];
?>