<?php
$comune = [

    createComuna("Albeștii de Argeș", [
        createLoc("Albeștii Pământeni", "sat"),
        createLoc("Albeștii Ungureni", "sat"),
        createLoc("Brătești", "sat"),
        createLoc("Doblea", "sat"),
        createLoc("Dobrotu", "sat"),
        createLoc("Dumirești", "sat"),
        createLoc("Florieni", "sat"),
    ]),
    createComuna("Albeștii de Muscel", [
        createLoc("Albești", "sat"),
        createLoc("Cândești", "sat"),
    ]),
    createComuna("Albota", [
        createLoc("Albota", "sat"),
        createLoc("Cerbu", "sat"),
        createLoc("Frătești", "sat"),
        createLoc("Gura Văii", "sat"),
        createLoc("Mareș", "sat"),
    ]),
    createComuna("Aninoasa", [
        createLoc("Aninoasa", "sat"),
        createLoc("Broșteni", "sat"),
        createLoc("Slănic", "sat"),
        createLoc("Valea Siliștii", "sat"),
    ]),
    createComuna("Arefu", [
        createLoc("Căpățânenii Pământeni", "sat"),
        createLoc("Arefu", "sat"),
        createLoc("Căpățânenii Ungureni", "sat"),
    ]),
    createComuna("Bascov", [
        createLoc("Bascov", "sat"),
        createLoc("Brăileni", "sat"),
        createLoc("Glâmbocu", "sat"),
        createLoc("Mica", "sat"),
        createLoc("Prislopu Mic", "sat"),
        createLoc("Schiau", "sat"),
        createLoc("Uiasca", "sat"),
        createLoc("Valea Ursului", "sat"),
    ]),
    createComuna("Băbana", [
        createLoc("Băbana", "sat"),
        createLoc("Băjănești", "sat"),
        createLoc("Ciobănești", "sat"),
        createLoc("Cotmenița", "sat"),
        createLoc("Groși", "sat"),
        createLoc("Lupueni", "sat"),
        createLoc("Slătioarele", "sat"),
    ]),
    createComuna("Băiculești", [
        createLoc("Băiculești", "sat"),
        createLoc("Alunișu", "sat"),
        createLoc("Anghinești", "sat"),
        createLoc("Argeșani", "sat"),
        createLoc("Mănicești", "sat"),
        createLoc("Stejari", "sat"),
        createLoc("Tutana", "sat"),
        createLoc("Valea Brazilor", "sat"),
        createLoc("Valea lui Enache", "sat"),
        createLoc("Zigoneni", "sat"),
    ]),
    createComuna("Bălilești", [
        createLoc("Bălilești", "sat"),
        createLoc("Băjești", "sat"),
        createLoc("Golești", "sat"),
        createLoc("Poienița", "sat"),
        createLoc("Priboaia", "sat"),
        createLoc("Ulita", "sat"),
        createLoc("Valea Mare-Bratia", "sat"),
    ]),
    createComuna("Beleți-Negrești", [
        createLoc("Zgripcești", "sat"),
        createLoc("Beleți", "sat"),
        createLoc("Lențea", "sat"),
        createLoc("Negrești", "sat"),
    ]),
    createComuna("Berevoești", [
        createLoc("Berevoești", "sat"),
        createLoc("Bratia", "sat"),
        createLoc("Gămăcești", "sat"),
        createLoc("Oțelu", "sat"),
    ]),
    createComuna("Bârla", [
        createLoc("Bârla", "sat"),
        createLoc("Afrimești", "sat"),
        createLoc("Bădești", "sat"),
        createLoc("Brabeți", "sat"),
        createLoc("Ciocești", "sat"),
        createLoc("Malu", "sat"),
        createLoc("Mândra", "sat"),
        createLoc("Mozăcenii-Vale", "sat"),
        createLoc("Podișoru", "sat"),
        createLoc("Șelăreasca", "sat"),
        createLoc("Urlueni", "sat"),
        createLoc("Zuvelcați", "sat"),
    ]),
    createComuna("Bogați", [
        createLoc("Bogați", "sat"),
        createLoc("Bârloi", "sat"),
        createLoc("Bujoi", "sat"),
        createLoc("Chițești", "sat"),
        createLoc("Dumbrava", "sat"),
        createLoc("Glâmbocel", "sat"),
        createLoc("Glâmbocelu", "sat"),
        createLoc("Suseni", "sat"),
    ]),
    createComuna("Boteni", [
        createLoc("Boteni", "sat"),
        createLoc("Balabani", "sat"),
        createLoc("Lunca", "sat"),
        createLoc("Mușcel", "sat"),
    ]),
    createComuna("Boțești", [
        createLoc("Boțești", "sat"),
        createLoc("Moșteni-Greci", "sat"),
    ]),
    createComuna("Bradu", [
        createLoc("Bradu", "sat"),
        createLoc("Geamăna", "sat"),
    ]),
    createComuna("Brăduleț", [
        createLoc("Brăduleț", "sat"),
        createLoc("Alunișu", "sat"),
        createLoc("Brădetu", "sat"),
        createLoc("Cosaci", "sat"),
        createLoc("Galeșu", "sat"),
        createLoc("Piatra", "sat"),
        createLoc("Slămnești", "sat"),
        createLoc("Uleni", "sat"),
        createLoc("Ungureni", "sat"),
    ]),
    createComuna("Budeasa", [
        createLoc("Budeasa Mare", "sat"),
        createLoc("Budeasa Mică", "sat"),
        createLoc("Calotești", "sat"),
        createLoc("Gălășești", "sat"),
        createLoc("Rogojina", "sat"),
        createLoc("Valea Mărului", "sat"),
    ]),
    createComuna("Bughea de Jos", [
        createLoc("Bughea de Jos", "sat"),
    ]),
    createComuna("Bughea de Sus", [
        createLoc("Bughea de Sus", "sat"),
    ]),
    createComuna("Buzoești", [
        createLoc("Vulpești", "sat"),
        createLoc("Bujoreni", "sat"),
        createLoc("Buzoești", "sat"),
        createLoc("Cornățel", "sat"),
        createLoc("Curteanca", "sat"),
        createLoc("Ionești", "sat"),
        createLoc("Podeni", "sat"),
        createLoc("Redea", "sat"),
        createLoc("Șerboeni", "sat"),
        createLoc("Tomșanca", "sat"),
        createLoc("Vlăduța", "sat"),
    ]),
    createComuna("Căldăraru", [
        createLoc("Căldăraru", "sat"),
        createLoc("Burdea", "sat"),
        createLoc("Strâmbeni", "sat"),
    ]),
    createComuna("Călinești", [
        createLoc("Vrănești", "sat"),
        createLoc("Călinești", "sat"),
        createLoc("Ciocănești", "sat"),
        createLoc("Cârstieni", "sat"),
        createLoc("Glodu", "sat"),
        createLoc("Gorganu", "sat"),
        createLoc("Radu Negru", "sat"),
        createLoc("Râncăciov", "sat"),
        createLoc("Udeni-Zăvoi", "sat"),
        createLoc("Urlucea", "sat"),
        createLoc("Valea Corbului", "sat"),
        createLoc("Văleni-Podgoria", "sat"),
    ]),
    createComuna("Căteasca", [
        createLoc("Căteasca", "sat"),
        createLoc("Catanele", "sat"),
        createLoc("Cireșu", "sat"),
        createLoc("Coșeri", "sat"),
        createLoc("Gruiu", "sat"),
        createLoc("Recea", "sat"),
        createLoc("Siliștea", "sat"),
    ]),
    createComuna("Cepari", [
        createLoc("Ceparii Pământeni", "sat"),
        createLoc("Cărpeniș", "sat"),
        createLoc("Ceparii Ungureni", "sat"),
        createLoc("Morăști", "sat"),
        createLoc("Șendrulești", "sat"),
        createLoc("Urluiești", "sat"),
        createLoc("Valea Măgurei", "sat"),
        createLoc("Zamfirești", "sat"),
    ]),
    createComuna("Cetățeni", [
        createLoc("Cetățeni", "sat"),
        createLoc("Lăicăi", "sat"),
        createLoc("Valea Cetățuia", "sat"),
    ]),
    createComuna("Cicănești", [
        createLoc("Cicănești", "sat"),
        createLoc("Bărăști", "sat"),
        createLoc("Mioarele", "sat"),
        createLoc("Urechești", "sat"),
    ]),
    createComuna("Ciofrângeni", [
        createLoc("Ciofrângeni", "sat"),
        createLoc("Burluși", "sat"),
        createLoc("Lacurile", "sat"),
        createLoc("Piatra", "sat"),
        createLoc("Schitu-Matei", "sat"),
    ]),
    createComuna("Ciomăgești", [
        createLoc("Răduțești", "sat"),
        createLoc("Beculești", "sat"),
        createLoc("Bratia", "sat"),
        createLoc("Ciomăgești", "sat"),
        createLoc("Cungrea", "sat"),
        createLoc("Dogari", "sat"),
        createLoc("Fedeleșoiu", "sat"),
        createLoc("Giuclani", "sat"),
        createLoc("Păunești", "sat"),
    ]),
    createComuna("Cocu", [
        createLoc("Răchițele de Jos", "sat"),
        createLoc("Bărbătești", "sat"),
        createLoc("Cocu", "sat"),
        createLoc("Crucișoara", "sat"),
        createLoc("Făcălețești", "sat"),
        createLoc("Greabănu", "sat"),
        createLoc("Popești", "sat"),
        createLoc("Răchițele de Sus", "sat"),
    ]),
    createComuna("Corbeni", [
        createLoc("Corbeni", "sat"),
        createLoc("Berindești", "sat"),
        createLoc("Bucșenești", "sat"),
        createLoc("Oeștii Pământeni", "sat"),
        createLoc("Oeștii Ungureni", "sat"),
        createLoc("Poienari", "sat"),
        createLoc("Rotunda", "sat"),
        createLoc("Turburea", "sat"),
    ]),
    createComuna("Corbi", [
        createLoc("Corbi", "sat"),
        createLoc("Corbșori", "sat"),
        createLoc("Jgheaburi", "sat"),
        createLoc("Poduri", "sat"),
        createLoc("Poienărei", "sat"),
        createLoc("Stănești", "sat"),
    ]),
    createComuna("Coșești", [
        createLoc("Coșești", "sat"),
        createLoc("Jupânești", "sat"),
        createLoc("Lăpușani", "sat"),
        createLoc("Leicești", "sat"),
        createLoc("Păcioiu", "sat"),
        createLoc("Petrești", "sat"),
        createLoc("Priseaca", "sat"),
    ]),
    createComuna("Cotmeana", [
        createLoc("Cotmeana", "sat"),
        createLoc("Bascovele", "sat"),
        createLoc("Bunești", "sat"),
        createLoc("Costești", "sat"),
        createLoc("Dealu Pădurii", "sat"),
        createLoc("Drăgolești", "sat"),
        createLoc("Lintești", "sat"),
        createLoc("Negești", "sat"),
        createLoc("Pielești", "sat"),
        createLoc("Săndulești", "sat"),
        createLoc("Spiridoni", "sat"),
        createLoc("Ursoaia", "sat"),
        createLoc("Vârloveni", "sat"),
        createLoc("Zamfirești", "sat"),
    ]),
    createComuna("Cuca", [
        createLoc("Cuca", "sat"),
        createLoc("Bălțata", "sat"),
        createLoc("Bărbălani", "sat"),
        createLoc("Cârcești", "sat"),
        createLoc("Cotu", "sat"),
        createLoc("Crivățu", "sat"),
        createLoc("Lăunele de Sus", "sat"),
        createLoc("Măcăi", "sat"),
        createLoc("Mănești", "sat"),
        createLoc("Sinești", "sat"),
        createLoc("Stănicei", "sat"),
        createLoc("Teodorești", "sat"),
        createLoc("Valea Cucii", "sat"),
        createLoc("Vonigeasa", "sat"),
    ]),
    createComuna("Davidești", [
        createLoc("Davidești", "sat"),
        createLoc("Conțești", "sat"),
        createLoc("Voroveni", "sat"),
    ]),
    createComuna("Dâmbovicioara", [
        createLoc("Dâmbovicioara", "sat"),
        createLoc("Ciocanu", "sat"),
        createLoc("Podu Dâmboviței", "sat"),
    ]),
    createComuna("Dârmănești", [
        createLoc("Dârmănești", "sat"),
        createLoc("Negreni", "sat"),
        createLoc("Piscani", "sat"),
        createLoc("Valea Nandrii", "sat"),
        createLoc("Valea Rizii", "sat"),
    ]),
    createComuna("Dobrești", [
        createLoc("Dobrești", "sat"),
        createLoc("Furești", "sat"),
    ]),
    createComuna("Domnești", [
        createLoc("Domnești", "sat"),
    ]),
    createComuna("Dragoslavele", [
        createLoc("Dragoslavele", "sat"),
        createLoc("Valea Hotarului", "sat"),
    ]),
    createComuna("Drăganu", [
        createLoc("Drăganu-Olteni", "sat"),
        createLoc("Băcești", "sat"),
        createLoc("Dumbrăvești", "sat"),
        createLoc("Prislopu Mare", "sat"),
    ]),
    createComuna("Godeni", [
        createLoc("Godeni", "sat"),
        createLoc("Bordeieni", "sat"),
        createLoc("Capu Piscului", "sat"),
        createLoc("Cotești", "sat"),
        createLoc("Malu", "sat"),
    ]),
    createComuna("Hârsești", [
        createLoc("Hârsești", "sat"),
        createLoc("Ciobani", "sat"),
        createLoc("Martalogi", "sat"),
    ]),
    createComuna("Hârtiești", [
        createLoc("Hârtiești", "sat"),
        createLoc("Dealu", "sat"),
        createLoc("Lespezi", "sat"),
        createLoc("Lucieni", "sat"),
    ]),
    createComuna("Izvoru", [
        createLoc("Izvoru", "sat"),
    ]),
    createComuna("Leordeni", [
        createLoc("Leordeni", "sat"),
        createLoc("Baloteasca", "sat"),
        createLoc("Băila", "sat"),
        createLoc("Bântău", "sat"),
        createLoc("Budișteni", "sat"),
        createLoc("Ciolcești", "sat"),
        createLoc("Ciulnița", "sat"),
        createLoc("Cârciumărești", "sat"),
        createLoc("Cotu Malului", "sat"),
        createLoc("Glâmbocata", "sat"),
        createLoc("Glâmbocata-Deal", "sat"),
        createLoc("Glodu", "sat"),
        createLoc("Moara Mocanului", "sat"),
        createLoc("Schitu Scoicești", "sat"),
    ]),
    createComuna("Lerești", [
        createLoc("Lerești", "sat"),
        createLoc("Pojorâta", "sat"),
        createLoc("Voinești", "sat"),
    ]),
    createComuna("Lunca Corbului", [
        createLoc("Lunca Corbului", "sat"),
        createLoc("Bumbueni", "sat"),
        createLoc("Catane", "sat"),
        createLoc("Ciești", "sat"),
        createLoc("Lăngești", "sat"),
        createLoc("Mârghia de Jos", "sat"),
        createLoc("Mârghia de Sus", "sat"),
        createLoc("Pădureți", "sat"),
        createLoc("Silișteni", "sat"),
    ]),
    createComuna("Mălureni", [
        createLoc("Mălureni", "sat"),
        createLoc("Bunești", "sat"),
        createLoc("Păuleasca", "sat"),
        createLoc("Toplița", "sat"),
        createLoc("Zărnești", "sat"),
    ]),
    createComuna("Mărăcineni", [
        createLoc("Mărăcineni", "sat"),
        createLoc("Argeșelu", "sat"),
    ]),
    createComuna("Merișani", [
        createLoc("Merișani", "sat"),
        createLoc("Borlești", "sat"),
        createLoc("Brăteasca", "sat"),
        createLoc("Capu Piscului", "sat"),
        createLoc("Crâmpotani", "sat"),
        createLoc("Dobrogostea", "sat"),
        createLoc("Malu Vânăt", "sat"),
        createLoc("Vărzaru", "sat"),
        createLoc("Vâlcelele", "sat"),
    ]),
    createComuna("Micești", [
        createLoc("Micești", "sat"),
        createLoc("Brânzari", "sat"),
        createLoc("Păuleasca", "sat"),
        createLoc("Purcăreni", "sat"),
    ]),
    createComuna("Mihăești", [
        createLoc("Mihăești", "sat"),
        createLoc("Drăghici", "sat"),
        createLoc("Furnicoși", "sat"),
        createLoc("Rudeni", "sat"),
        createLoc("Valea Bradului", "sat"),
        createLoc("Valea Popii", "sat"),
        createLoc("Văcarea", "sat"),
    ]),
    createComuna("Mioarele", [
        createLoc("Mățău", "sat"),
        createLoc("Aluniș", "sat"),
        createLoc("Chilii", "sat"),
        createLoc("Cocenești", "sat"),
        createLoc("Suslănești", "sat"),
    ]),
    createComuna("Miroși", [
        createLoc("Miroși", "sat"),
        createLoc("Surdulești", "sat"),
    ]),
    createComuna("Morărești", [
        createLoc("Morărești", "sat"),
        createLoc("Dedulești", "sat"),
        createLoc("Dealu Obejdeanului", "sat"),
        createLoc("Luminile", "sat"),
        createLoc("Măncioiu", "sat"),
        createLoc("Săpunari", "sat"),
    ]),
    createComuna("Moșoaia", [
        createLoc("Moșoaia", "sat"),
        createLoc("Bătrâni", "sat"),
        createLoc("Ciocănăi", "sat"),
        createLoc("Dealu Viilor", "sat"),
        createLoc("Hințești", "sat"),
        createLoc("Lăzărești", "sat"),
        createLoc("Smeura", "sat"),
    ]),
    createComuna("Mozăceni", [
        createLoc("Mozăceni", "sat"),
        createLoc("Babaroaga", "sat"),
        createLoc("Zidurile", "sat"),
    ]),
    createComuna("Mușătești", [
        createLoc("Vâlsănești", "sat"),
        createLoc("Bolovănești", "sat"),
        createLoc("Costești-Vâlsan", "sat"),
        createLoc("Mușătești", "sat"),
        createLoc("Prosia", "sat"),
        createLoc("Robaia", "sat"),
        createLoc("Stroești", "sat"),
        createLoc("Valea Faurului", "sat"),
        createLoc("Valea lui Maș", "sat"),
        createLoc("Valea Muscelului", "sat"),
    ]),
    createComuna("Negrași", [
        createLoc("Negrași", "sat"),
        createLoc("Bârlogu", "sat"),
        createLoc("Buta", "sat"),
        createLoc("Mozacu", "sat"),
    ]),
    createComuna("Nucșoara", [
        createLoc("Nucșoara", "sat"),
        createLoc("Gruiu", "sat"),
        createLoc("Sboghițești", "sat"),
        createLoc("Slatina", "sat"),
    ]),
    createComuna("Oarja", [
        createLoc("Oarja", "sat"),
        createLoc("Ceaușești", "sat"),
    ]),
    createComuna("Pietroșani", [
        createLoc("Pietroșani", "sat"),
        createLoc("Bădești", "sat"),
        createLoc("Gănești", "sat"),
        createLoc("Retevoiești", "sat"),
        createLoc("Vărzăroaia", "sat"),
    ]),
    createComuna("Poiana Lacului", [
        createLoc("Poiana Lacului", "sat"),
        createLoc("Cătunași", "sat"),
        createLoc("Cepari", "sat"),
        createLoc("Dealu Orașului", "sat"),
        createLoc("Dealu Viilor", "sat"),
        createLoc("Dinculești", "sat"),
        createLoc("Gălețeanu", "sat"),
        createLoc("Gărdinești", "sat"),
        createLoc("Gâlcești", "sat"),
        createLoc("Metofu", "sat"),
        createLoc("Păduroiu din Deal", "sat"),
        createLoc("Păduroiu din Vale", "sat"),
        createLoc("Sămara", "sat"),
    ]),
    createComuna("Poienarii de Argeș", [
        createLoc("Poienari", "sat"),
        createLoc("Ceaurești", "sat"),
        createLoc("Ioanicești", "sat"),
        createLoc("Tomulești", "sat"),
    ]),
    createComuna("Poienarii de Muscel", [
        createLoc("Poienari", "sat"),
        createLoc("Groșani", "sat"),
        createLoc("Jugur", "sat"),
        createLoc("Șerbănești", "sat"),
        createLoc("Valea Îndărăt", "sat"),
    ]),
    createComuna("Popești", [
        createLoc("Popești", "sat"),
        createLoc("Palanga", "sat"),
        createLoc("Purcăreni", "sat"),
        createLoc("Slobozia", "sat"),
    ]),
    createComuna("Priboieni", [
        createLoc("Priboieni", "sat"),
        createLoc("Albotele", "sat"),
        createLoc("Paraschivești", "sat"),
        createLoc("Sămăila", "sat"),
        createLoc("Pitoi", "sat"),
        createLoc("Valea Mare", "sat"),
        createLoc("Valea Nenii", "sat"),
        createLoc("Valea Popii", "sat"),
    ]),
    createComuna("Rătești", [
        createLoc("Rătești", "sat"),
        createLoc("Ciupa-Mănciulescu", "sat"),
        createLoc("Furduești", "sat"),
        createLoc("Mavrodolu", "sat"),
        createLoc("Nejlovelu", "sat"),
        createLoc("Pătuleni", "sat"),
        createLoc("Tigveni", "sat"),
    ]),
    createComuna("Râca", [
        createLoc("Râca", "sat"),
        createLoc("Adunați", "sat"),
        createLoc("Bucov", "sat"),
    ]),
    createComuna("Recea", [
        createLoc("Recea", "sat"),
        createLoc("Deagu de Jos", "sat"),
        createLoc("Deagu de Sus", "sat"),
        createLoc("Goleasca", "sat"),
        createLoc("Orodel", "sat"),
    ]),
    createComuna("Rociu", [
        createLoc("Rociu", "sat"),
        createLoc("Gliganu de Jos", "sat"),
        createLoc("Gliganu de Sus", "sat"),
        createLoc("Șerbănești", "sat"),
    ]),
    createComuna("Rucăr", [
        createLoc("Rucăr", "sat"),
        createLoc("Sătic", "sat"),
    ]),
    createComuna("Sălătrucu", [
        createLoc("Sălătrucu", "sat"),
        createLoc("Văleni", "sat"),
    ]),
    createComuna("Săpata", [
        createLoc("Mârțești", "sat"),
        createLoc("Bănărești", "sat"),
        createLoc("Dealu Bradului", "sat"),
        createLoc("Drăghicești", "sat"),
        createLoc("Găinușa", "sat"),
        createLoc("Lipia", "sat"),
        createLoc("Popești", "sat"),
        createLoc("Turcești", "sat"),
    ]),
    createComuna("Schitu Golești", [
        createLoc("Schitu Golești", "sat"),
        createLoc("Burnești", "sat"),
        createLoc("Costiță", "sat"),
        createLoc("Lăzărești", "sat"),
        createLoc("Loturi", "sat"),
        createLoc("Valea Pechii", "sat"),
    ]),
    createComuna("Slobozia", [
        createLoc("Slobozia", "sat"),
        createLoc("Nigrișoara", "sat"),
    ]),
    createComuna("Stâlpeni", [
        createLoc("Stâlpeni", "sat"),
        createLoc("Dealu Frumos", "sat"),
        createLoc("Livezeni", "sat"),
        createLoc("Ogrezea", "sat"),
        createLoc("Oprești", "sat"),
        createLoc("Pițigaia", "sat"),
        createLoc("Rădești", "sat"),
    ]),
    createComuna("Stoenești", [
        createLoc("Stoenești", "sat"),
        createLoc("Bădeni", "sat"),
        createLoc("Cotenești", "sat"),
        createLoc("Lunca Gârtii", "sat"),
        createLoc("Piatra", "sat"),
        createLoc("Slobozia", "sat"),
        createLoc("Valea Bădenilor", "sat"),
    ]),
    createComuna("Stolnici", [
        createLoc("Stolnici", "sat"),
        createLoc("Cochinești", "sat"),
        createLoc("Cotmeana", "sat"),
        createLoc("Fâlfani", "sat"),
        createLoc("Izbășești", "sat"),
        createLoc("Vlășcuța", "sat"),
    ]),
    createComuna("Suseni", [
        createLoc("Suseni", "sat"),
        createLoc("Burdești", "sat"),
        createLoc("Cerșani", "sat"),
        createLoc("Chirițești", "sat"),
        createLoc("Găleșești", "sat"),
        createLoc("Odăeni", "sat"),
        createLoc("Pădureni", "sat"),
        createLoc("Strâmbeni", "sat"),
        createLoc("Ștefănești", "sat"),
        createLoc("Țuțulești", "sat"),
    ]),
    createComuna("Ștefan cel Mare", [
        createLoc("Ștefan cel Mare", "sat"),
        createLoc("Glavacioc", "sat"),
    ]),
    createComuna("Șuici", [
        createLoc("Șuici", "sat"),
        createLoc("Ianculești", "sat"),
        createLoc("Paltenu", "sat"),
        createLoc("Păuleni", "sat"),
        createLoc("Rudeni", "sat"),
        createLoc("Valea Calului", "sat"),
    ]),
    createComuna("Teiu", [
        createLoc("Teiu", "sat"),
        createLoc("Leșile", "sat"),
    ]),
    createComuna("Tigveni", [
        createLoc("Tigveni", "sat"),
        createLoc("Bădislava", "sat"),
        createLoc("Bălilești", "sat"),
        createLoc("Bălteni", "sat"),
        createLoc("Bârseștii de Jos", "sat"),
        createLoc("Bârseștii de Sus", "sat"),
        createLoc("Blaju", "sat"),
        createLoc("Vlădești", "sat"),
    ]),
    createComuna("Țițești", [
        createLoc("Țițești", "sat"),
        createLoc("Bucșenești-Lotași", "sat"),
        createLoc("Cișmea", "sat"),
        createLoc("Valea Mănăstirii", "sat"),
        createLoc("Valea Stânii", "sat"),
    ]),
    createComuna("Uda", [
        createLoc("Uda", "sat"),
        createLoc("Bădulești", "sat"),
        createLoc("Bărănești", "sat"),
        createLoc("Braniștea", "sat"),
        createLoc("Chirițești", "sat"),
        createLoc("Cotu", "sat"),
        createLoc("Dealu Bisericii", "sat"),
        createLoc("Dealu Tolcesii", "sat"),
        createLoc("Diconești", "sat"),
        createLoc("Gorani", "sat"),
        createLoc("Greabăn", "sat"),
        createLoc("Lungulești", "sat"),
        createLoc("Miercani", "sat"),
        createLoc("Râjlețu-Govora", "sat"),
        createLoc("Romana", "sat"),
        createLoc("Săliștea", "sat"),
    ]),
    createComuna("Ungheni", [
        createLoc("Ungheni", "sat"),
        createLoc("Colțu", "sat"),
        createLoc("Găujani", "sat"),
        createLoc("Goia", "sat"),
        createLoc("Humele", "sat"),
        createLoc("Satu Nou", "sat"),
    ]),
    createComuna("Valea Danului", [
        createLoc("Valea Danului", "sat"),
        createLoc("Bănicești", "sat"),
        createLoc("Bolculești", "sat"),
        createLoc("Borobănești", "sat"),
        createLoc("Vernești", "sat"),
    ]),
    createComuna("Valea Iașului", [
        createLoc("Valea Iașului", "sat"),
        createLoc("Bădila", "sat"),
        createLoc("Bărbălătești", "sat"),
        createLoc("Borovinești", "sat"),
        createLoc("Cerbureni", "sat"),
        createLoc("Mustățești", "sat"),
        createLoc("Ruginoasa", "sat"),
        createLoc("Ungureni", "sat"),
        createLoc("Valea Uleiului", "sat"),
    ]),
    createComuna("Valea Mare-Pravăț", [
        createLoc("Valea Mare-Pravăț", "sat"),
        createLoc("Bilcești", "sat"),
        createLoc("Colnic", "sat"),
        createLoc("Fântânea", "sat"),
        createLoc("Gura Pravăț", "sat"),
        createLoc("Nămăești", "sat"),
        createLoc("Pietroasa", "sat"),
        createLoc("Șelari", "sat"),
    ]),
    createComuna("Vedea", [
        createLoc("Vedea", "sat"),
        createLoc("Bădicea", "sat"),
        createLoc("Blejani", "sat"),
        createLoc("Burețești", "sat"),
        createLoc("Chirițești", "sat"),
        createLoc("Chițani", "sat"),
        createLoc("Ciurești", "sat"),
        createLoc("Dincani", "sat"),
        createLoc("Fata", "sat"),
        createLoc("Frătici", "sat"),
        createLoc("Izvoru de Jos", "sat"),
        createLoc("Izvoru de Sus", "sat"),
        createLoc("Lungani", "sat"),
        createLoc("Mogoșești", "sat"),
        createLoc("Prodani", "sat"),
        createLoc("Rățoi", "sat"),
        createLoc("Vața", "sat"),
        createLoc("Vețișoara", "sat"),
        createLoc("Vârșești", "sat"),
    ]),
    createComuna("Vlădești", [
        createLoc("Vlădești", "sat"),
        createLoc("Coteasca", "sat"),
        createLoc("Drăghescu", "sat"),
        createLoc("Putina", "sat"),
    ]),
    createComuna("Vulturești", [
        createLoc("Vulturești", "sat"),
        createLoc("Bârzești", "sat"),
        createLoc("Huluba", "sat"),
    ]),

];
