<?php
$comune =[

			createComuna("Albeștii de Argeș", [
				    createLoc("Albeștii Pământeni", "sat"),
				    createLoc("Albeștii Ungureni", "sat"),
					createLoc("Brătești", "sat"),
					createLoc("Doblea", "sat"),
					createLoc("Dobrotu", "sat"),
					createLoc("Dumirești", "sat"),
					createLoc("Florieni", "sat"),
							  ]),	
		    createComuna("Albeștii de Muscel", [
				    createLoc("Albești", "sat"),
				    createLoc("Cândești", "sat"),
							  ]),
		    createComuna("Albota", [
				    createLoc("Albota", "sat"),
				    createLoc("Cerbu", "sat"),
					createLoc("Frătești", "sat"),
					createLoc("Gura Văii", "sat"),
					createLoc("Mareș", "sat"),
							  ]),	
		    createComuna("Aninoasa", [
				    createLoc("Aninoasa", "sat"),
				    createLoc("Broșteni", "sat"),
					createLoc("Slănic", "sat"),
					createLoc("Valea Siliștii", "sat"),
							  ]),
			createComuna("Arefu", [
				    createLoc("Căpățânenii Pământeni", "sat"),
				    createLoc("Arefu", "sat"),
					createLoc("Căpățânenii Ungureni", "sat"),
							  ]),	
		    createComuna("Bascov", [
				    createLoc("Bascov", "sat"),
				    createLoc("Brăileni", "sat"),
					createLoc("Glâmbocu", "sat"),
					createLoc("Mica", "sat"),
					createLoc("Prislopu Mic", "sat"),
					createLoc("Schiau", "sat"),
					createLoc("Uiasca", "sat"),
					createLoc("Valea Ursului", "sat"),
							  ]),
			createComuna("Băbana", [
				    createLoc("Băbana", "sat"),
				    createLoc("Băjănești", "sat"),
					createLoc("Ciobănești", "sat"),
					createLoc("Cotmenița", "sat"),
					createLoc("Groși", "sat"),
					createLoc("Lupueni", "sat"),
					createLoc("Slătioarele", "sat"),
							  ]),	
		    createComuna("Băiculești", [
				    createLoc("Băiculești", "sat"),
				    createLoc("Alunișu", "sat"),
					createLoc("Anghinești", "sat"),
					createLoc("Argeșani", "sat"),
					createLoc("Mănicești", "sat"),
					createLoc("Stejari", "sat"),
					createLoc("Tutana", "sat"),
					createLoc("Valea Brazilor", "sat"),
					createLoc("Valea lui Enache", "sat"),
					createLoc("Zigoneni", "sat"),
							  ]),
			createComuna("Bălilești", [
				    createLoc("Bălilești", "sat"),
				    createLoc("Băjești", "sat"),
					createLoc("Golești", "sat"),
					createLoc("Poienița", "sat"),
					createLoc("Priboaia", "sat"),
					createLoc("Ulita", "sat"),
					createLoc("Valea Mare-Bratia", "sat"),
							  ]),
		    createComuna("Beleți-Negrești", [
				    createLoc("Zgripcești", "sat"),
				    createLoc("Beleți", "sat"),
					createLoc("Lențea", "sat"),
					createLoc("Negrești", "sat"),
							  ]),
			createComuna("Berevoești", [
				    createLoc("Berevoești", "sat"),
				    createLoc("Bratia", "sat"),
					createLoc("Gămăcești", "sat"),
					createLoc("Oțelu", "sat"),
							  ]),	
		    createComuna("Bârla", [
				    createLoc("Bârla", "sat"),
				    createLoc("Afrimești", "sat"),
					createLoc("Bădești", "sat"),
					createLoc("Brabeți", "sat"),
					createLoc("Ciocești", "sat"),
					createLoc("Malu", "sat"),
					createLoc("Mândra", "sat"),
					createLoc("Mozăcenii-Vale", "sat"),
					createLoc("Podișoru", "sat"),
					createLoc("Șelăreasca", "sat"),
					createLoc("Urlueni", "sat"),
					createLoc("Zuvelcați", "sat"),
							  ]),
			createComuna("Bogați", [
				    createLoc("Bogați", "sat"),
				    createLoc("Bârloi", "sat"),
					createLoc("Bujoi", "sat"),
					createLoc("Chițești", "sat"),
					createLoc("Dumbrava", "sat"),
					createLoc("Glâmbocel", "sat"),
					createLoc("Suseni", "sat"),
							  ]),	
		    createComuna("Boteni", [
				    createLoc("Boteni", "sat"),
				    createLoc("Balabani", "sat"),
					createLoc("Lunca", "sat"),
					createLoc("Mușcel", "sat"),
							  ]),							  
			
];
?>