<?php
$comune =[

				createComuna("Apața", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Apața", "sat"),
								  ]),						  
				createComuna("Augustin", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Augustin", "sat"),	
								  ]),
				createComuna("Beclean", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Beclean", "sat"),
					createLoc("Boholț", "sat"),
					createLoc("Calbor", "sat"),
					createLoc("Hurez", "sat"),
					createLoc("Luța", "sat"),
								  ]),
				createComuna("Bod", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Bod", "sat"),	
					createLoc("Colonia Bod", "sat"),
								  ]),		
				createComuna("Bran", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Bran", "sat"),
					createLoc("Predeluț", "sat"),
					createLoc("Sohodol", "sat"),
					createLoc("Șimon", "sat"),
								  ]),
				createComuna("Budila", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Budila", "sat"),	
								  ]),
				createComuna("Bunești", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Bunești", "sat"),
					createLoc("Criț", "sat"),
					createLoc("Meșendorf", "sat"),
					createLoc("Roadeș", "sat"),
					createLoc("Viscri", "sat"),
								  ]),
				createComuna("Cața", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Cața", "sat"),
					createLoc("Beia", "sat"),
					createLoc("Drăușeni", "sat"),
					createLoc("Ionești", "sat"),
					createLoc("Paloș", "sat"),
								  ]),
				createComuna("Cincu", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Cincu", "sat"),	
					createLoc("Toarcla", "sat"),
								  ]),	
				createComuna("Comana", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Comana de Jos", "sat"),
					createLoc("Comana de Sus", "sat"),
					createLoc("Crihalma ", "sat"),
					createLoc("Ticușu Nou", "sat"),
								  ]),
				createComuna("Cristian", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Cristian", "sat"),	
								  ]),	
				createComuna("Crizbav", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Crizbav", "sat"),	
					createLoc("Cutuș", "sat"),
								  ]),
				createComuna("Drăguș", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Drăguș", "sat"),	
								  ]),
				createComuna("Dumbrăvița", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Dumbrăvița", "sat"),	
					createLoc("Vlădeni", "sat"),
								  ]),
				createComuna("Feldioara", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Feldioara", "sat"),	
					createLoc("Colonia Reconstrucția", "sat"),
					createLoc("Rotbav", "sat"),
								  ]),	
				createComuna("Fundata", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Fundata", "sat"),	
					createLoc("Fundățica ", "sat"),
					createLoc("Șirnea", "sat"),
								  ]),
				createComuna("Hălchiu", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Hălchiu", "sat"),	
					createLoc("Satu Nou", "sat"),
								  ]),
				createComuna("Hărman", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Hărman", "sat"),	
					createLoc("Podu Oltului", "sat"),
								  ]),
				createComuna("Hârseni", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Hârseni", "sat"),
					createLoc("Copăcel", "sat"),
					createLoc("Măliniș", "sat"),
					createLoc("Mărgineni", "sat"),
					createLoc("Sebeș", "sat"),
								  ]),	
				createComuna("Hoghiz", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Hoghiz", "sat"),
					createLoc("Bogata Olteană", "sat"),
					createLoc("Cuciulata", "sat"),
					createLoc("Dopca", "sat"),
					createLoc("Fântâna", "sat"),
					createLoc("Lupșa", "sat"),
								  ]),
				createComuna("Holbav", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Holbav", "sat"),	
								  ]),
				createComuna("Homorod", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Homorod", "sat"),	
					createLoc("Jimbor", "sat"),
					createLoc("Mercheașa", "sat"),
								  ]),
				createComuna("Jibert", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Jibert", "sat"),
					createLoc("Dacia", "sat"),
					createLoc("Grânari", "sat"),
					createLoc("Lovnic", "sat"),
					createLoc("Văleni", "sat"),
								  ]),
				createComuna("Lisa", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Lisa", "sat"),	
					createLoc("Breaza ", "sat"),
					createLoc("Pojorta", "sat"),
								  ]),	
				createComuna("Măieruș", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Măieruș", "sat"),	
					createLoc("Arini", "sat"),
								  ]),
				createComuna("Mândra", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Mândra", "sat"),
					createLoc("Ileni", "sat"),
					createLoc("Râușor", "sat"),
					createLoc("Șona", "sat"),
					createLoc("Toderița", "sat"),
								  ]),	
				createComuna("Moieciu", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Moieciu de Jos", "sat"),
					createLoc("Cheia", "sat"),
					createLoc("Drumul Carului", "sat"),
					createLoc("Măgura", "sat"),
					createLoc("Moieciu de Sus", "sat"),
					createLoc("Peștera", "sat"),
								  ]),
				createComuna("Ormeniș", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Ormeniș", "sat"),	
								  ]),
				createComuna("Părău", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Părău", "sat"),
					createLoc("Grid", "sat"),
					createLoc("Veneția de Jos", "sat"),
					createLoc("Veneția de Sus", "sat"),
								  ]),
				createComuna("Poiana Mărului", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Poiana Mărului", "sat"),	
								  ]),
				createComuna("Prejmer", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Prejmer", "sat"),	
					createLoc("Lunca Calnicului", "sat"),
					createLoc("Stupinii Prejmerului", "sat"),
								  ]),	
				createComuna("Racoș", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Racoș", "sat"),	
					createLoc("Mateiaș", "sat"),
								  ]),
				createComuna("Recea", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Recea", "sat"),
					createLoc("Berivoi", "sat"),
					createLoc("Dejani", "sat"),
					createLoc("Gura Văii", "sat"),
					createLoc("Iași", "sat"),
					createLoc("Săsciori", "sat"),
					createLoc("Săvăstreni", "sat"),
								  ]),
				createComuna("Sâmbăta de Sus", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Sâmbăta de Sus", "sat"),	
					createLoc("Stațiunea Climaterică Sâmbăta", "sat"),
								  ]),
				createComuna("Sânpetru", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Sânpetru", "sat"),	
								  ]),
				createComuna("Șercaia", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Șercaia", "sat"),	
					createLoc("Hălmeag", "sat"),
					createLoc("Vad", "sat"),
								  ]),
				createComuna("Șinca", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Șinca Veche", "sat"),
					createLoc("Bucium", "sat"),
					createLoc("Ohaba", "sat"),
					createLoc("Perșani", "sat"),
					createLoc("Șercăița", "sat"),
					createLoc("Vâlcea", "sat"),
								  ]),	
				createComuna("Șinca Nouă", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Șinca Nouă", "sat"),	
					createLoc("Paltin", "sat"),
								  ]),
				createComuna("Șoarș", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Șoarș", "sat"),
					createLoc("Bărcut", "sat"),
					createLoc("Felmer", "sat"),
					createLoc("Rodbav", "sat"),
					createLoc("Seliștat", "sat"),
								  ]),
				createComuna("Tărlungeni", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Tărlungeni", "sat"),
					createLoc("Cărpiniș", "sat"),
					createLoc("Purcăreni", "sat"),
					createLoc("Zizin", "sat"),
								  ]),
				createComuna("Teliu", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Teliu", "sat"),	
								  ]),
				createComuna("Ticușu", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Ticușu Vechi", "sat"),	
					createLoc("Cobor", "sat"),
								  ]),
				createComuna("Ucea", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Ucea de Jos", "sat"),
					createLoc("Corbi", "sat"),
					createLoc("Feldioara", "sat"),
					createLoc("Ucea de Sus", "sat"),
								  ]),
				createComuna("Ungra", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Ungra", "sat"),	
					createLoc("Dăișoara", "sat"),
								  ]),
				createComuna("Vama Buzăului", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Vama Buzăului", "sat"),
					createLoc("Acriș", "sat"),
					createLoc("Buzăiel", "sat"),
					createLoc("Dălghiu", "sat"),
								  ]),
				createComuna("Viștea", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Viștea de Jos", "sat"),
					createLoc("Olteț", "sat"),
					createLoc("Rucăr", "sat"),
					createLoc("Viștea de Sus", "sat"),
					createLoc("Viștișoara", "sat"),
								  ]),
				createComuna("Voila", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Voila", "sat"),
					createLoc("Cincșor", "sat"),
					createLoc("Dridif", "sat"),
					createLoc("Ludișor", "sat"),
					createLoc("Sâmbăta de Jos", "sat"),
					createLoc("Voivodeni", "sat"),
								  ]),
				createComuna("Vulcan", [
					createAdresaCompleta("BRASOV", "BRASOV"),
					createLoc("Vulcan", "sat"),	
					createLoc("Colonia 1 Mai", "sat"),
								  ]),							  
								  
];
?>