<?php
$comune =[
	createComuna("Apața", [
						createAdresaCompleta("comuna Apața, judetul BRASOV, România", "comuna Apata, judetul BRASOV, Romania"),
						createLoc("Apața", "sat", createAdresaCompleta("sat Apața, comuna Apața, judetul Brasov, România", "sat Apata, comuna Apata, judetul Brasov, Romania")),
		]),
	createComuna("Augustin", [
						createAdresaCompleta("comuna Augustin, judetul BRASOV, România", "comuna Augustin, judetul BRASOV, Romania"),
						createLoc("Augustin", "sat", createAdresaCompleta("sat Augustin, comuna Augustin, judetul Brasov, România", "sat Augustin, comuna Augustin, judetul Brasov, Romania")),
		]),
	createComuna("Beclean", [
						createAdresaCompleta("comuna Beclean, judetul BRASOV, România", "comuna Beclean, judetul BRASOV, Romania"),
						createLoc("Beclean", "sat", createAdresaCompleta("sat Beclean, comuna Beclean, judetul Brasov, România", "sat Beclean, comuna Beclean, judetul Brasov, Romania")),
						createLoc("Boholț", "sat", createAdresaCompleta("sat Boholț, comuna Beclean, judetul Brasov, România", "sat Boholt, comuna Beclean, judetul Brasov, Romania")),
						createLoc("Calbor", "sat", createAdresaCompleta("sat Calbor, comuna Beclean, judetul Brasov, România", "sat Calbor, comuna Beclean, judetul Brasov, Romania")),
						createLoc("Hurez", "sat", createAdresaCompleta("sat Hurez, comuna Beclean, judetul Brasov, România", "sat Hurez, comuna Beclean, judetul Brasov, Romania")),
						createLoc("Luța", "sat", createAdresaCompleta("sat Luța, comuna Beclean, judetul Brasov, România", "sat Luta, comuna Beclean, judetul Brasov, Romania")),
		]),
	createComuna("Bod", [
						createAdresaCompleta("comuna Bod, judetul BRASOV, România", "comuna Bod, judetul BRASOV, Romania"),
						createLoc("Bod", "sat", createAdresaCompleta("sat Bod, comuna Bod, judetul Brasov, România", "sat Bod, comuna Bod, judetul Brasov, Romania")),
						createLoc("Colonia Bod", "sat", createAdresaCompleta("sat Colonia Bod, comuna Bod, judetul Brasov, România", "sat Colonia Bod, comuna Bod, judetul Brasov, Romania")),
		]),
	createComuna("Bran", [
						createAdresaCompleta("comuna Bran, judetul BRASOV, România", "comuna Bran, judetul BRASOV, Romania"),
						createLoc("Bran", "sat", createAdresaCompleta("sat Bran, comuna Bran, judetul Brasov, România", "sat Bran, comuna Bran, judetul Brasov, Romania")),
						createLoc("Predeluț", "sat", createAdresaCompleta("sat Predeluț, comuna Bran, judetul Brasov, România", "sat Predelut, comuna Bran, judetul Brasov, Romania")),
						createLoc("Sohodol", "sat", createAdresaCompleta("sat Sohodol, comuna Bran, judetul Brasov, România", "sat Sohodol, comuna Bran, judetul Brasov, Romania")),
						createLoc("Șimon", "sat", createAdresaCompleta("sat Șimon, comuna Bran, judetul Brasov, România", "sat Simon, comuna Bran, judetul Brasov, Romania")),
		]),
	createComuna("Budila", [
						createAdresaCompleta("comuna Budila, judetul BRASOV, România", "comuna Budila, judetul BRASOV, Romania"),
						createLoc("Budila", "sat", createAdresaCompleta("sat Budila, comuna Budila, judetul Brasov, România", "sat Budila, comuna Budila, judetul Brasov, Romania")),
		]),
	createComuna("Bunești", [
						createAdresaCompleta("comuna Bunești, judetul BRASOV, România", "comuna Bunesti, judetul BRASOV, Romania"),
						createLoc("Bunești", "sat", createAdresaCompleta("sat Bunești, comuna Bunești, judetul Brasov, România", "sat Bunesti, comuna Bunesti, judetul Brasov, Romania")),
						createLoc("Criț", "sat", createAdresaCompleta("sat Criț, comuna Bunești, judetul Brasov, România", "sat Crit, comuna Bunesti, judetul Brasov, Romania")),
						createLoc("Meșendorf", "sat", createAdresaCompleta("sat Meșendorf, comuna Bunești, judetul Brasov, România", "sat Mesendorf, comuna Bunesti, judetul Brasov, Romania")),
						createLoc("Roadeș", "sat", createAdresaCompleta("sat Roadeș, comuna Bunești, judetul Brasov, România", "sat Roades, comuna Bunesti, judetul Brasov, Romania")),
						createLoc("Viscri", "sat", createAdresaCompleta("sat Viscri, comuna Bunești, judetul Brasov, România", "sat Viscri, comuna Bunesti, judetul Brasov, Romania")),
		]),
	createComuna("Cața", [
						createAdresaCompleta("comuna Cața, judetul BRASOV, România", "comuna Cata, judetul BRASOV, Romania"),
						createLoc("Cața", "sat", createAdresaCompleta("sat Cața, comuna Cața, judetul Brasov, România", "sat Cata, comuna Cata, judetul Brasov, Romania")),
						createLoc("Beia", "sat", createAdresaCompleta("sat Beia, comuna Cața, judetul Brasov, România", "sat Beia, comuna Cata, judetul Brasov, Romania")),
						createLoc("Drăușeni", "sat", createAdresaCompleta("sat Drăușeni, comuna Cața, judetul Brasov, România", "sat Drauseni, comuna Cata, judetul Brasov, Romania")),
						createLoc("Ionești", "sat", createAdresaCompleta("sat Ionești, comuna Cața, judetul Brasov, România", "sat Ionesti, comuna Cata, judetul Brasov, Romania")),
						createLoc("Paloș", "sat", createAdresaCompleta("sat Paloș, comuna Cața, judetul Brasov, România", "sat Palos, comuna Cata, judetul Brasov, Romania")),
		]),
	createComuna("Cincu", [
						createAdresaCompleta("comuna Cincu, judetul BRASOV, România", "comuna Cincu, judetul BRASOV, Romania"),
						createLoc("Cincu", "sat", createAdresaCompleta("sat Cincu, comuna Cincu, judetul Brasov, România", "sat Cincu, comuna Cincu, judetul Brasov, Romania")),
						createLoc("Toarcla", "sat", createAdresaCompleta("sat Toarcla, comuna Cincu, judetul Brasov, România", "sat Toarcla, comuna Cincu, judetul Brasov, Romania")),
		]),
	createComuna("Comana", [
						createAdresaCompleta("comuna Comana, judetul BRASOV, România", "comuna Comana, judetul BRASOV, Romania"),
						createLoc("Comana de Jos", "sat", createAdresaCompleta("sat Comana de Jos, comuna Comana, judetul Brasov, România", "sat Comana de Jos, comuna Comana, judetul Brasov, Romania")),
						createLoc("Comana de Sus", "sat", createAdresaCompleta("sat Comana de Sus, comuna Comana, judetul Brasov, România", "sat Comana de Sus, comuna Comana, judetul Brasov, Romania")),
						createLoc("Crihalma ", "sat", createAdresaCompleta("sat Crihalma , comuna Comana, judetul Brasov, România", "sat Crihalma , comuna Comana, judetul Brasov, Romania")),
						createLoc("Ticușu Nou", "sat", createAdresaCompleta("sat Ticușu Nou, comuna Comana, judetul Brasov, România", "sat Ticusu Nou, comuna Comana, judetul Brasov, Romania")),
		]),
	createComuna("Cristian", [
						createAdresaCompleta("comuna Cristian, judetul BRASOV, România", "comuna Cristian, judetul BRASOV, Romania"),
						createLoc("Cristian", "sat", createAdresaCompleta("sat Cristian, comuna Cristian, judetul Brasov, România", "sat Cristian, comuna Cristian, judetul Brasov, Romania")),
		]),
	createComuna("Crizbav", [
						createAdresaCompleta("comuna Crizbav, judetul BRASOV, România", "comuna Crizbav, judetul BRASOV, Romania"),
						createLoc("Crizbav", "sat", createAdresaCompleta("sat Crizbav, comuna Crizbav, judetul Brasov, România", "sat Crizbav, comuna Crizbav, judetul Brasov, Romania")),
						createLoc("Cutuș", "sat", createAdresaCompleta("sat Cutuș, comuna Crizbav, judetul Brasov, România", "sat Cutus, comuna Crizbav, judetul Brasov, Romania")),
		]),
	createComuna("Drăguș", [
						createAdresaCompleta("comuna Drăguș, judetul BRASOV, România", "comuna Dragus, judetul BRASOV, Romania"),
						createLoc("Drăguș", "sat", createAdresaCompleta("sat Drăguș, comuna Drăguș, judetul Brasov, România", "sat Dragus, comuna Dragus, judetul Brasov, Romania")),
		]),
	createComuna("Dumbrăvița", [
						createAdresaCompleta("comuna Dumbrăvița, judetul BRASOV, România", "comuna Dumbravita, judetul BRASOV, Romania"),
						createLoc("Dumbrăvița", "sat", createAdresaCompleta("sat Dumbrăvița, comuna Dumbrăvița, judetul Brasov, România", "sat Dumbravita, comuna Dumbravita, judetul Brasov, Romania")),
						createLoc("Vlădeni", "sat", createAdresaCompleta("sat Vlădeni, comuna Dumbrăvița, judetul Brasov, România", "sat Vladeni, comuna Dumbravita, judetul Brasov, Romania")),
		]),
	createComuna("Feldioara", [
						createAdresaCompleta("comuna Feldioara, judetul BRASOV, România", "comuna Feldioara, judetul BRASOV, Romania"),
						createLoc("Feldioara", "sat", createAdresaCompleta("sat Feldioara, comuna Feldioara, judetul Brasov, România", "sat Feldioara, comuna Feldioara, judetul Brasov, Romania")),
						createLoc("Colonia Reconstrucția", "sat", createAdresaCompleta("sat Colonia Reconstrucția, comuna Feldioara, judetul Brasov, România", "sat Colonia Reconstructia, comuna Feldioara, judetul Brasov, Romania")),
						createLoc("Rotbav", "sat", createAdresaCompleta("sat Rotbav, comuna Feldioara, judetul Brasov, România", "sat Rotbav, comuna Feldioara, judetul Brasov, Romania")),
		]),
	createComuna("Fundata", [
						createAdresaCompleta("comuna Fundata, judetul BRASOV, România", "comuna Fundata, judetul BRASOV, Romania"),
						createLoc("Fundata", "sat", createAdresaCompleta("sat Fundata, comuna Fundata, judetul Brasov, România", "sat Fundata, comuna Fundata, judetul Brasov, Romania")),
						createLoc("Fundățica ", "sat", createAdresaCompleta("sat Fundățica , comuna Fundata, judetul Brasov, România", "sat Fundatica , comuna Fundata, judetul Brasov, Romania")),
						createLoc("Șirnea", "sat", createAdresaCompleta("sat Șirnea, comuna Fundata, judetul Brasov, România", "sat Sirnea, comuna Fundata, judetul Brasov, Romania")),
		]),
	createComuna("Hălchiu", [
						createAdresaCompleta("comuna Hălchiu, judetul BRASOV, România", "comuna Halchiu, judetul BRASOV, Romania"),
						createLoc("Hălchiu", "sat", createAdresaCompleta("sat Hălchiu, comuna Hălchiu, judetul Brasov, România", "sat Halchiu, comuna Halchiu, judetul Brasov, Romania")),
						createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Hălchiu, judetul Brasov, România", "sat Satu Nou, comuna Halchiu, judetul Brasov, Romania")),
		]),
	createComuna("Hărman", [
						createAdresaCompleta("comuna Hărman, judetul BRASOV, România", "comuna Harman, judetul BRASOV, Romania"),
						createLoc("Hărman", "sat", createAdresaCompleta("sat Hărman, comuna Hărman, judetul Brasov, România", "sat Harman, comuna Harman, judetul Brasov, Romania")),
						createLoc("Podu Oltului", "sat", createAdresaCompleta("sat Podu Oltului, comuna Hărman, judetul Brasov, România", "sat Podu Oltului, comuna Harman, judetul Brasov, Romania")),
		]),
	createComuna("Hârseni", [
						createAdresaCompleta("comuna Hârseni, judetul BRASOV, România", "comuna Harseni, judetul BRASOV, Romania"),
						createLoc("Hârseni", "sat", createAdresaCompleta("sat Hârseni, comuna Hârseni, judetul Brasov, România", "sat Harseni, comuna Harseni, judetul Brasov, Romania")),
						createLoc("Copăcel", "sat", createAdresaCompleta("sat Copăcel, comuna Hârseni, judetul Brasov, România", "sat Copacel, comuna Harseni, judetul Brasov, Romania")),
						createLoc("Măliniș", "sat", createAdresaCompleta("sat Măliniș, comuna Hârseni, judetul Brasov, România", "sat Malinis, comuna Harseni, judetul Brasov, Romania")),
						createLoc("Mărgineni", "sat", createAdresaCompleta("sat Mărgineni, comuna Hârseni, judetul Brasov, România", "sat Margineni, comuna Harseni, judetul Brasov, Romania")),
						createLoc("Sebeș", "sat", createAdresaCompleta("sat Sebeș, comuna Hârseni, judetul Brasov, România", "sat Sebes, comuna Harseni, judetul Brasov, Romania")),
		]),
	createComuna("Hoghiz", [
						createAdresaCompleta("comuna Hoghiz, judetul BRASOV, România", "comuna Hoghiz, judetul BRASOV, Romania"),
						createLoc("Hoghiz", "sat", createAdresaCompleta("sat Hoghiz, comuna Hoghiz, judetul Brasov, România", "sat Hoghiz, comuna Hoghiz, judetul Brasov, Romania")),
						createLoc("Bogata Olteană", "sat", createAdresaCompleta("sat Bogata Olteană, comuna Hoghiz, judetul Brasov, România", "sat Bogata Olteana, comuna Hoghiz, judetul Brasov, Romania")),
						createLoc("Cuciulata", "sat", createAdresaCompleta("sat Cuciulata, comuna Hoghiz, judetul Brasov, România", "sat Cuciulata, comuna Hoghiz, judetul Brasov, Romania")),
						createLoc("Dopca", "sat", createAdresaCompleta("sat Dopca, comuna Hoghiz, judetul Brasov, România", "sat Dopca, comuna Hoghiz, judetul Brasov, Romania")),
						createLoc("Fântâna", "sat", createAdresaCompleta("sat Fântâna, comuna Hoghiz, judetul Brasov, România", "sat Fantana, comuna Hoghiz, judetul Brasov, Romania")),
						createLoc("Lupșa", "sat", createAdresaCompleta("sat Lupșa, comuna Hoghiz, judetul Brasov, România", "sat Lupsa, comuna Hoghiz, judetul Brasov, Romania")),
		]),
	createComuna("Holbav", [
						createAdresaCompleta("comuna Holbav, judetul BRASOV, România", "comuna Holbav, judetul BRASOV, Romania"),
						createLoc("Holbav", "sat", createAdresaCompleta("sat Holbav, comuna Holbav, judetul Brasov, România", "sat Holbav, comuna Holbav, judetul Brasov, Romania")),
		]),
	createComuna("Homorod", [
						createAdresaCompleta("comuna Homorod, judetul BRASOV, România", "comuna Homorod, judetul BRASOV, Romania"),
						createLoc("Homorod", "sat", createAdresaCompleta("sat Homorod, comuna Homorod, judetul Brasov, România", "sat Homorod, comuna Homorod, judetul Brasov, Romania")),
						createLoc("Jimbor", "sat", createAdresaCompleta("sat Jimbor, comuna Homorod, judetul Brasov, România", "sat Jimbor, comuna Homorod, judetul Brasov, Romania")),
						createLoc("Mercheașa", "sat", createAdresaCompleta("sat Mercheașa, comuna Homorod, judetul Brasov, România", "sat Mercheasa, comuna Homorod, judetul Brasov, Romania")),
		]),
	createComuna("Jibert", [
						createAdresaCompleta("comuna Jibert, judetul BRASOV, România", "comuna Jibert, judetul BRASOV, Romania"),
						createLoc("Jibert", "sat", createAdresaCompleta("sat Jibert, comuna Jibert, judetul Brasov, România", "sat Jibert, comuna Jibert, judetul Brasov, Romania")),
						createLoc("Dacia", "sat", createAdresaCompleta("sat Dacia, comuna Jibert, judetul Brasov, România", "sat Dacia, comuna Jibert, judetul Brasov, Romania")),
						createLoc("Grânari", "sat", createAdresaCompleta("sat Grânari, comuna Jibert, judetul Brasov, România", "sat Granari, comuna Jibert, judetul Brasov, Romania")),
						createLoc("Lovnic", "sat", createAdresaCompleta("sat Lovnic, comuna Jibert, judetul Brasov, România", "sat Lovnic, comuna Jibert, judetul Brasov, Romania")),
						createLoc("Văleni", "sat", createAdresaCompleta("sat Văleni, comuna Jibert, judetul Brasov, România", "sat Valeni, comuna Jibert, judetul Brasov, Romania")),
		]),
	createComuna("Lisa", [
						createAdresaCompleta("comuna Lisa, judetul BRASOV, România", "comuna Lisa, judetul BRASOV, Romania"),
						createLoc("Lisa", "sat", createAdresaCompleta("sat Lisa, comuna Lisa, judetul Brasov, România", "sat Lisa, comuna Lisa, judetul Brasov, Romania")),
						createLoc("Breaza ", "sat", createAdresaCompleta("sat Breaza , comuna Lisa, judetul Brasov, România", "sat Breaza , comuna Lisa, judetul Brasov, Romania")),
						createLoc("Pojorta", "sat", createAdresaCompleta("sat Pojorta, comuna Lisa, judetul Brasov, România", "sat Pojorta, comuna Lisa, judetul Brasov, Romania")),
		]),
	createComuna("Măieruș", [
						createAdresaCompleta("comuna Măieruș, judetul BRASOV, România", "comuna Maierus, judetul BRASOV, Romania"),
						createLoc("Măieruș", "sat", createAdresaCompleta("sat Măieruș, comuna Măieruș, judetul Brasov, România", "sat Maierus, comuna Maierus, judetul Brasov, Romania")),
						createLoc("Arini", "sat", createAdresaCompleta("sat Arini, comuna Măieruș, judetul Brasov, România", "sat Arini, comuna Maierus, judetul Brasov, Romania")),
		]),
	createComuna("Mândra", [
						createAdresaCompleta("comuna Mândra, judetul BRASOV, România", "comuna Mandra, judetul BRASOV, Romania"),
						createLoc("Mândra", "sat", createAdresaCompleta("sat Mândra, comuna Mândra, judetul Brasov, România", "sat Mandra, comuna Mandra, judetul Brasov, Romania")),
						createLoc("Ileni", "sat", createAdresaCompleta("sat Ileni, comuna Mândra, judetul Brasov, România", "sat Ileni, comuna Mandra, judetul Brasov, Romania")),
						createLoc("Râușor", "sat", createAdresaCompleta("sat Râușor, comuna Mândra, judetul Brasov, România", "sat Rausor, comuna Mandra, judetul Brasov, Romania")),
						createLoc("Șona", "sat", createAdresaCompleta("sat Șona, comuna Mândra, judetul Brasov, România", "sat Sona, comuna Mandra, judetul Brasov, Romania")),
						createLoc("Toderița", "sat", createAdresaCompleta("sat Toderița, comuna Mândra, judetul Brasov, România", "sat Toderita, comuna Mandra, judetul Brasov, Romania")),
		]),
	createComuna("Moieciu", [
						createAdresaCompleta("comuna Moieciu, judetul BRASOV, România", "comuna Moieciu, judetul BRASOV, Romania"),
						createLoc("Moieciu de Jos", "sat", createAdresaCompleta("sat Moieciu de Jos, comuna Moieciu, judetul Brasov, România", "sat Moieciu de Jos, comuna Moieciu, judetul Brasov, Romania")),
						createLoc("Cheia", "sat", createAdresaCompleta("sat Cheia, comuna Moieciu, judetul Brasov, România", "sat Cheia, comuna Moieciu, judetul Brasov, Romania")),
						createLoc("Drumul Carului", "sat", createAdresaCompleta("sat Drumul Carului, comuna Moieciu, judetul Brasov, România", "sat Drumul Carului, comuna Moieciu, judetul Brasov, Romania")),
						createLoc("Măgura", "sat", createAdresaCompleta("sat Măgura, comuna Moieciu, judetul Brasov, România", "sat Magura, comuna Moieciu, judetul Brasov, Romania")),
						createLoc("Moieciu de Sus", "sat", createAdresaCompleta("sat Moieciu de Sus, comuna Moieciu, judetul Brasov, România", "sat Moieciu de Sus, comuna Moieciu, judetul Brasov, Romania")),
						createLoc("Peștera", "sat", createAdresaCompleta("sat Peștera, comuna Moieciu, judetul Brasov, România", "sat Pestera, comuna Moieciu, judetul Brasov, Romania")),
		]),
	createComuna("Ormeniș", [
						createAdresaCompleta("comuna Ormeniș, judetul BRASOV, România", "comuna Ormenis, judetul BRASOV, Romania"),
						createLoc("Ormeniș", "sat", createAdresaCompleta("sat Ormeniș, comuna Ormeniș, judetul Brasov, România", "sat Ormenis, comuna Ormenis, judetul Brasov, Romania")),
		]),
	createComuna("Părău", [
						createAdresaCompleta("comuna Părău, judetul BRASOV, România", "comuna Parau, judetul BRASOV, Romania"),
						createLoc("Părău", "sat", createAdresaCompleta("sat Părău, comuna Părău, judetul Brasov, România", "sat Parau, comuna Parau, judetul Brasov, Romania")),
						createLoc("Grid", "sat", createAdresaCompleta("sat Grid, comuna Părău, judetul Brasov, România", "sat Grid, comuna Parau, judetul Brasov, Romania")),
						createLoc("Veneția de Jos", "sat", createAdresaCompleta("sat Veneția de Jos, comuna Părău, judetul Brasov, România", "sat Venetia de Jos, comuna Parau, judetul Brasov, Romania")),
						createLoc("Veneția de Sus", "sat", createAdresaCompleta("sat Veneția de Sus, comuna Părău, judetul Brasov, România", "sat Venetia de Sus, comuna Parau, judetul Brasov, Romania")),
		]),
	createComuna("Poiana Mărului", [
						createAdresaCompleta("comuna Poiana Mărului, judetul BRASOV, România", "comuna Poiana Marului, judetul BRASOV, Romania"),
						createLoc("Poiana Mărului", "sat", createAdresaCompleta("sat Poiana Mărului, comuna Poiana Mărului, judetul Brasov, România", "sat Poiana Marului, comuna Poiana Marului, judetul Brasov, Romania")),
		]),
	createComuna("Prejmer", [
						createAdresaCompleta("comuna Prejmer, judetul BRASOV, România", "comuna Prejmer, judetul BRASOV, Romania"),
						createLoc("Prejmer", "sat", createAdresaCompleta("sat Prejmer, comuna Prejmer, judetul Brasov, România", "sat Prejmer, comuna Prejmer, judetul Brasov, Romania")),
						createLoc("Lunca Calnicului", "sat", createAdresaCompleta("sat Lunca Calnicului, comuna Prejmer, judetul Brasov, România", "sat Lunca Calnicului, comuna Prejmer, judetul Brasov, Romania")),
						createLoc("Stupinii Prejmerului", "sat", createAdresaCompleta("sat Stupinii Prejmerului, comuna Prejmer, judetul Brasov, România", "sat Stupinii Prejmerului, comuna Prejmer, judetul Brasov, Romania")),
		]),
	createComuna("Racoș", [
						createAdresaCompleta("comuna Racoș, judetul BRASOV, România", "comuna Racos, judetul BRASOV, Romania"),
						createLoc("Racoș", "sat", createAdresaCompleta("sat Racoș, comuna Racoș, judetul Brasov, România", "sat Racos, comuna Racos, judetul Brasov, Romania")),
						createLoc("Mateiaș", "sat", createAdresaCompleta("sat Mateiaș, comuna Racoș, judetul Brasov, România", "sat Mateias, comuna Racos, judetul Brasov, Romania")),
		]),
	createComuna("Recea", [
						createAdresaCompleta("comuna Recea, judetul BRASOV, România", "comuna Recea, judetul BRASOV, Romania"),
						createLoc("Recea", "sat", createAdresaCompleta("sat Recea, comuna Recea, judetul Brasov, România", "sat Recea, comuna Recea, judetul Brasov, Romania")),
						createLoc("Berivoi", "sat", createAdresaCompleta("sat Berivoi, comuna Recea, judetul Brasov, România", "sat Berivoi, comuna Recea, judetul Brasov, Romania")),
						createLoc("Dejani", "sat", createAdresaCompleta("sat Dejani, comuna Recea, judetul Brasov, România", "sat Dejani, comuna Recea, judetul Brasov, Romania")),
						createLoc("Gura Văii", "sat", createAdresaCompleta("sat Gura Văii, comuna Recea, judetul Brasov, România", "sat Gura Vaii, comuna Recea, judetul Brasov, Romania")),
						createLoc("Iași", "sat", createAdresaCompleta("sat Iași, comuna Recea, judetul Brasov, România", "sat Iasi, comuna Recea, judetul Brasov, Romania")),
						createLoc("Săsciori", "sat", createAdresaCompleta("sat Săsciori, comuna Recea, judetul Brasov, România", "sat Sasciori, comuna Recea, judetul Brasov, Romania")),
						createLoc("Săvăstreni", "sat", createAdresaCompleta("sat Săvăstreni, comuna Recea, judetul Brasov, România", "sat Savastreni, comuna Recea, judetul Brasov, Romania")),
		]),
	createComuna("Sâmbăta de Sus", [
						createAdresaCompleta("comuna Sâmbăta de Sus, judetul BRASOV, România", "comuna Sambata de Sus, judetul BRASOV, Romania"),
						createLoc("Sâmbăta de Sus", "sat", createAdresaCompleta("sat Sâmbăta de Sus, comuna Sâmbăta de Sus, judetul Brasov, România", "sat Sambata de Sus, comuna Sambata de Sus, judetul Brasov, Romania")),
						createLoc("Stațiunea Climaterică Sâmbăta", "sat", createAdresaCompleta("sat Stațiunea Climaterică Sâmbăta, comuna Sâmbăta de Sus, judetul Brasov, România", "sat Statiunea Climaterica Sambata, comuna Sambata de Sus, judetul Brasov, Romania")),
		]),
	createComuna("Sânpetru", [
						createAdresaCompleta("comuna Sânpetru, judetul BRASOV, România", "comuna Sanpetru, judetul BRASOV, Romania"),
						createLoc("Sânpetru", "sat", createAdresaCompleta("sat Sânpetru, comuna Sânpetru, judetul Brasov, România", "sat Sanpetru, comuna Sanpetru, judetul Brasov, Romania")),
		]),
	createComuna("Șercaia", [
						createAdresaCompleta("comuna Șercaia, judetul BRASOV, România", "comuna Sercaia, judetul BRASOV, Romania"),
						createLoc("Șercaia", "sat", createAdresaCompleta("sat Șercaia, comuna Șercaia, judetul Brasov, România", "sat Sercaia, comuna Sercaia, judetul Brasov, Romania")),
						createLoc("Hălmeag", "sat", createAdresaCompleta("sat Hălmeag, comuna Șercaia, judetul Brasov, România", "sat Halmeag, comuna Sercaia, judetul Brasov, Romania")),
						createLoc("Vad", "sat", createAdresaCompleta("sat Vad, comuna Șercaia, judetul Brasov, România", "sat Vad, comuna Sercaia, judetul Brasov, Romania")),
		]),
	createComuna("Șinca", [
						createAdresaCompleta("comuna Șinca, judetul BRASOV, România", "comuna Sinca, judetul BRASOV, Romania"),
						createLoc("Șinca Veche", "sat", createAdresaCompleta("sat Șinca Veche, comuna Șinca, judetul Brasov, România", "sat Sinca Veche, comuna Sinca, judetul Brasov, Romania")),
						createLoc("Bucium", "sat", createAdresaCompleta("sat Bucium, comuna Șinca, judetul Brasov, România", "sat Bucium, comuna Sinca, judetul Brasov, Romania")),
						createLoc("Ohaba", "sat", createAdresaCompleta("sat Ohaba, comuna Șinca, judetul Brasov, România", "sat Ohaba, comuna Sinca, judetul Brasov, Romania")),
						createLoc("Perșani", "sat", createAdresaCompleta("sat Perșani, comuna Șinca, judetul Brasov, România", "sat Persani, comuna Sinca, judetul Brasov, Romania")),
						createLoc("Șercăița", "sat", createAdresaCompleta("sat Șercăița, comuna Șinca, judetul Brasov, România", "sat Sercaita, comuna Sinca, judetul Brasov, Romania")),
						createLoc("Vâlcea", "sat", createAdresaCompleta("sat Vâlcea, comuna Șinca, judetul Brasov, România", "sat Valcea, comuna Sinca, judetul Brasov, Romania")),
		]),
	createComuna("Șinca Nouă", [
						createAdresaCompleta("comuna Șinca Nouă, judetul BRASOV, România", "comuna Sinca Noua, judetul BRASOV, Romania"),
						createLoc("Șinca Nouă", "sat", createAdresaCompleta("sat Șinca Nouă, comuna Șinca Nouă, judetul Brasov, România", "sat Sinca Noua, comuna Sinca Noua, judetul Brasov, Romania")),
						createLoc("Paltin", "sat", createAdresaCompleta("sat Paltin, comuna Șinca Nouă, judetul Brasov, România", "sat Paltin, comuna Sinca Noua, judetul Brasov, Romania")),
		]),
	createComuna("Șoarș", [
						createAdresaCompleta("comuna Șoarș, judetul BRASOV, România", "comuna Soars, judetul BRASOV, Romania"),
						createLoc("Șoarș", "sat", createAdresaCompleta("sat Șoarș, comuna Șoarș, judetul Brasov, România", "sat Soars, comuna Soars, judetul Brasov, Romania")),
						createLoc("Bărcut", "sat", createAdresaCompleta("sat Bărcut, comuna Șoarș, judetul Brasov, România", "sat Barcut, comuna Soars, judetul Brasov, Romania")),
						createLoc("Felmer", "sat", createAdresaCompleta("sat Felmer, comuna Șoarș, judetul Brasov, România", "sat Felmer, comuna Soars, judetul Brasov, Romania")),
						createLoc("Rodbav", "sat", createAdresaCompleta("sat Rodbav, comuna Șoarș, judetul Brasov, România", "sat Rodbav, comuna Soars, judetul Brasov, Romania")),
						createLoc("Seliștat", "sat", createAdresaCompleta("sat Seliștat, comuna Șoarș, judetul Brasov, România", "sat Selistat, comuna Soars, judetul Brasov, Romania")),
		]),
	createComuna("Tărlungeni", [
						createAdresaCompleta("comuna Tărlungeni, judetul BRASOV, România", "comuna Tarlungeni, judetul BRASOV, Romania"),
						createLoc("Tărlungeni", "sat", createAdresaCompleta("sat Tărlungeni, comuna Tărlungeni, judetul Brasov, România", "sat Tarlungeni, comuna Tarlungeni, judetul Brasov, Romania")),
						createLoc("Cărpiniș", "sat", createAdresaCompleta("sat Cărpiniș, comuna Tărlungeni, judetul Brasov, România", "sat Carpinis, comuna Tarlungeni, judetul Brasov, Romania")),
						createLoc("Purcăreni", "sat", createAdresaCompleta("sat Purcăreni, comuna Tărlungeni, judetul Brasov, România", "sat Purcareni, comuna Tarlungeni, judetul Brasov, Romania")),
						createLoc("Zizin", "sat", createAdresaCompleta("sat Zizin, comuna Tărlungeni, judetul Brasov, România", "sat Zizin, comuna Tarlungeni, judetul Brasov, Romania")),
		]),
	createComuna("Teliu", [
						createAdresaCompleta("comuna Teliu, judetul BRASOV, România", "comuna Teliu, judetul BRASOV, Romania"),
						createLoc("Teliu", "sat", createAdresaCompleta("sat Teliu, comuna Teliu, judetul Brasov, România", "sat Teliu, comuna Teliu, judetul Brasov, Romania")),
		]),
	createComuna("Ticușu", [
						createAdresaCompleta("comuna Ticușu, judetul BRASOV, România", "comuna Ticusu, judetul BRASOV, Romania"),
						createLoc("Ticușu Vechi", "sat", createAdresaCompleta("sat Ticușu Vechi, comuna Ticușu, judetul Brasov, România", "sat Ticusu Vechi, comuna Ticusu, judetul Brasov, Romania")),
						createLoc("Cobor", "sat", createAdresaCompleta("sat Cobor, comuna Ticușu, judetul Brasov, România", "sat Cobor, comuna Ticusu, judetul Brasov, Romania")),
		]),
	createComuna("Ucea", [
						createAdresaCompleta("comuna Ucea, judetul BRASOV, România", "comuna Ucea, judetul BRASOV, Romania"),
						createLoc("Ucea de Jos", "sat", createAdresaCompleta("sat Ucea de Jos, comuna Ucea, judetul Brasov, România", "sat Ucea de Jos, comuna Ucea, judetul Brasov, Romania")),
						createLoc("Corbi", "sat", createAdresaCompleta("sat Corbi, comuna Ucea, judetul Brasov, România", "sat Corbi, comuna Ucea, judetul Brasov, Romania")),
						createLoc("Feldioara", "sat", createAdresaCompleta("sat Feldioara, comuna Ucea, judetul Brasov, România", "sat Feldioara, comuna Ucea, judetul Brasov, Romania")),
						createLoc("Ucea de Sus", "sat", createAdresaCompleta("sat Ucea de Sus, comuna Ucea, judetul Brasov, România", "sat Ucea de Sus, comuna Ucea, judetul Brasov, Romania")),
		]),
	createComuna("Ungra", [
						createAdresaCompleta("comuna Ungra, judetul BRASOV, România", "comuna Ungra, judetul BRASOV, Romania"),
						createLoc("Ungra", "sat", createAdresaCompleta("sat Ungra, comuna Ungra, judetul Brasov, România", "sat Ungra, comuna Ungra, judetul Brasov, Romania")),
						createLoc("Dăișoara", "sat", createAdresaCompleta("sat Dăișoara, comuna Ungra, judetul Brasov, România", "sat Daisoara, comuna Ungra, judetul Brasov, Romania")),
		]),
	createComuna("Vama Buzăului", [
						createAdresaCompleta("comuna Vama Buzăului, judetul BRASOV, România", "comuna Vama Buzaului, judetul BRASOV, Romania"),
						createLoc("Vama Buzăului", "sat", createAdresaCompleta("sat Vama Buzăului, comuna Vama Buzăului, judetul Brasov, România", "sat Vama Buzaului, comuna Vama Buzaului, judetul Brasov, Romania")),
						createLoc("Acriș", "sat", createAdresaCompleta("sat Acriș, comuna Vama Buzăului, judetul Brasov, România", "sat Acris, comuna Vama Buzaului, judetul Brasov, Romania")),
						createLoc("Buzăiel", "sat", createAdresaCompleta("sat Buzăiel, comuna Vama Buzăului, judetul Brasov, România", "sat Buzaiel, comuna Vama Buzaului, judetul Brasov, Romania")),
						createLoc("Dălghiu", "sat", createAdresaCompleta("sat Dălghiu, comuna Vama Buzăului, judetul Brasov, România", "sat Dalghiu, comuna Vama Buzaului, judetul Brasov, Romania")),
		]),
	createComuna("Viștea", [
						createAdresaCompleta("comuna Viștea, judetul BRASOV, România", "comuna Vistea, judetul BRASOV, Romania"),
						createLoc("Viștea de Jos", "sat", createAdresaCompleta("sat Viștea de Jos, comuna Viștea, judetul Brasov, România", "sat Vistea de Jos, comuna Vistea, judetul Brasov, Romania")),
						createLoc("Olteț", "sat", createAdresaCompleta("sat Olteț, comuna Viștea, judetul Brasov, România", "sat Oltet, comuna Vistea, judetul Brasov, Romania")),
						createLoc("Rucăr", "sat", createAdresaCompleta("sat Rucăr, comuna Viștea, judetul Brasov, România", "sat Rucar, comuna Vistea, judetul Brasov, Romania")),
						createLoc("Viștea de Sus", "sat", createAdresaCompleta("sat Viștea de Sus, comuna Viștea, judetul Brasov, România", "sat Vistea de Sus, comuna Vistea, judetul Brasov, Romania")),
						createLoc("Viștișoara", "sat", createAdresaCompleta("sat Viștișoara, comuna Viștea, judetul Brasov, România", "sat Vistisoara, comuna Vistea, judetul Brasov, Romania")),
		]),
	createComuna("Voila", [
						createAdresaCompleta("comuna Voila, judetul BRASOV, România", "comuna Voila, judetul BRASOV, Romania"),
						createLoc("Voila", "sat", createAdresaCompleta("sat Voila, comuna Voila, judetul Brasov, România", "sat Voila, comuna Voila, judetul Brasov, Romania")),
						createLoc("Cincșor", "sat", createAdresaCompleta("sat Cincșor, comuna Voila, judetul Brasov, România", "sat Cincsor, comuna Voila, judetul Brasov, Romania")),
						createLoc("Dridif", "sat", createAdresaCompleta("sat Dridif, comuna Voila, judetul Brasov, România", "sat Dridif, comuna Voila, judetul Brasov, Romania")),
						createLoc("Ludișor", "sat", createAdresaCompleta("sat Ludișor, comuna Voila, judetul Brasov, România", "sat Ludisor, comuna Voila, judetul Brasov, Romania")),
						createLoc("Sâmbăta de Jos", "sat", createAdresaCompleta("sat Sâmbăta de Jos, comuna Voila, judetul Brasov, România", "sat Sambata de Jos, comuna Voila, judetul Brasov, Romania")),
						createLoc("Voivodeni", "sat", createAdresaCompleta("sat Voivodeni, comuna Voila, judetul Brasov, România", "sat Voivodeni, comuna Voila, judetul Brasov, Romania")),
		]),
	createComuna("Vulcan", [
						createAdresaCompleta("comuna Vulcan, judetul BRASOV, România", "comuna Vulcan, judetul BRASOV, Romania"),
						createLoc("Vulcan", "sat", createAdresaCompleta("sat Vulcan, comuna Vulcan, judetul Brasov, România", "sat Vulcan, comuna Vulcan, judetul Brasov, Romania")),
						createLoc("Colonia 1 Mai", "sat", createAdresaCompleta("sat Colonia 1 Mai, comuna Vulcan, judetul Brasov, România", "sat Colonia 1 Mai, comuna Vulcan, judetul Brasov, Romania")),
		]),
];
?>