<?php
$comune =[
	createComuna("Afumați", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Afumați", "sat", createAdresaCompleta("sat Afumați, comuna Afumați, judetul Dolj, România", "sat Afumati, comuna Afumati, judetul Dolj, Romania")),
						createLoc("Boureni", "sat", createAdresaCompleta("sat Boureni, comuna Afumați, judetul Dolj, România", "sat Boureni, comuna Afumati, judetul Dolj, Romania")),
						createLoc("Covei", "sat", createAdresaCompleta("sat Covei, comuna Afumați, judetul Dolj, România", "sat Covei, comuna Afumati, judetul Dolj, Romania")),
		]),
	createComuna("Almăj", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Almăj", "sat", createAdresaCompleta("sat Almăj, comuna Almăj, judetul Dolj, România", "sat Almaj, comuna Almaj, judetul Dolj, Romania")),
						createLoc("Bogea", "sat", createAdresaCompleta("sat Bogea, comuna Almăj, judetul Dolj, România", "sat Bogea, comuna Almaj, judetul Dolj, Romania")),
						createLoc("Moșneni", "sat", createAdresaCompleta("sat Moșneni, comuna Almăj, judetul Dolj, România", "sat Mosneni, comuna Almaj, judetul Dolj, Romania")),
						createLoc("Șitoaia", "sat", createAdresaCompleta("sat Șitoaia, comuna Almăj, judetul Dolj, România", "sat Sitoaia, comuna Almaj, judetul Dolj, Romania")),
		]),
	createComuna("Amărăștii de Jos", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Amărăștii de Jos", "sat", createAdresaCompleta("sat Amărăștii de Jos, comuna Amărăștii de Jos, judetul Dolj, România", "sat Amarastii de Jos, comuna Amarastii de Jos, judetul Dolj, Romania")),
						createLoc("Ocolna", "sat", createAdresaCompleta("sat Ocolna, comuna Amărăștii de Jos, judetul Dolj, România", "sat Ocolna, comuna Amarastii de Jos, judetul Dolj, Romania")),
						createLoc("Prapor", "sat", createAdresaCompleta("sat Prapor, comuna Amărăștii de Jos, judetul Dolj, România", "sat Prapor, comuna Amarastii de Jos, judetul Dolj, Romania")),
		]),
	createComuna("Amărăștii de Sus", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Amărăștii de Sus", "sat", createAdresaCompleta("sat Amărăștii de Sus, comuna Amărăștii de Sus, judetul Dolj, România", "sat Amarastii de Sus, comuna Amarastii de Sus, judetul Dolj, Romania")),
						createLoc("Zvorsca", "sat", createAdresaCompleta("sat Zvorsca, comuna Amărăștii de Sus, judetul Dolj, România", "sat Zvorsca, comuna Amarastii de Sus, judetul Dolj, Romania")),
		]),
	createComuna("Apele Vii", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Apele Vii", "sat", createAdresaCompleta("sat Apele Vii, comuna Apele Vii, judetul Dolj, România", "sat Apele Vii, comuna Apele Vii, judetul Dolj, Romania")),
		]),
	createComuna("Argetoaia", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Argetoaia", "sat", createAdresaCompleta("sat Argetoaia, comuna Argetoaia, judetul Dolj, România", "sat Argetoaia, comuna Argetoaia, judetul Dolj, Romania")),
						createLoc("Băranu", "sat", createAdresaCompleta("sat Băranu, comuna Argetoaia, judetul Dolj, România", "sat Baranu, comuna Argetoaia, judetul Dolj, Romania")),
						createLoc("Berbeșu", "sat", createAdresaCompleta("sat Berbeșu, comuna Argetoaia, judetul Dolj, România", "sat Berbesu, comuna Argetoaia, judetul Dolj, Romania")),
						createLoc("Iordăchești", "sat", createAdresaCompleta("sat Iordăchești, comuna Argetoaia, judetul Dolj, România", "sat Iordachesti, comuna Argetoaia, judetul Dolj, Romania")),
						createLoc("Leordoasa", "sat", createAdresaCompleta("sat Leordoasa, comuna Argetoaia, judetul Dolj, România", "sat Leordoasa, comuna Argetoaia, judetul Dolj, Romania")),
						createLoc("Malumnic", "sat", createAdresaCompleta("sat Malumnic, comuna Argetoaia, judetul Dolj, România", "sat Malumnic, comuna Argetoaia, judetul Dolj, Romania")),
						createLoc("Novac", "sat", createAdresaCompleta("sat Novac, comuna Argetoaia, judetul Dolj, România", "sat Novac, comuna Argetoaia, judetul Dolj, Romania")),
						createLoc("Piria", "sat", createAdresaCompleta("sat Piria, comuna Argetoaia, judetul Dolj, România", "sat Piria, comuna Argetoaia, judetul Dolj, Romania")),
						createLoc("Poiana Fântânii", "sat", createAdresaCompleta("sat Poiana Fântânii, comuna Argetoaia, judetul Dolj, România", "sat Poiana Fantanii, comuna Argetoaia, judetul Dolj, Romania")),
						createLoc("Salcia", "sat", createAdresaCompleta("sat Salcia, comuna Argetoaia, judetul Dolj, România", "sat Salcia, comuna Argetoaia, judetul Dolj, Romania")),
						createLoc("Teascu din Deal", "sat", createAdresaCompleta("sat Teascu din Deal, comuna Argetoaia, judetul Dolj, România", "sat Teascu din Deal, comuna Argetoaia, judetul Dolj, Romania")),
						createLoc("Ursoaia", "sat", createAdresaCompleta("sat Ursoaia, comuna Argetoaia, judetul Dolj, România", "sat Ursoaia, comuna Argetoaia, judetul Dolj, Romania")),
		]),
	createComuna("Bistreț", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Bistreț", "sat", createAdresaCompleta("sat Bistreț, comuna Bistreț, judetul Dolj, România", "sat Bistret, comuna Bistret, judetul Dolj, Romania")),
						createLoc("Bistrețu Nou", "sat", createAdresaCompleta("sat Bistrețu Nou, comuna Bistreț, judetul Dolj, România", "sat Bistretu Nou, comuna Bistret, judetul Dolj, Romania")),
						createLoc("Brândușa", "sat", createAdresaCompleta("sat Brândușa, comuna Bistreț, judetul Dolj, România", "sat Brandusa, comuna Bistret, judetul Dolj, Romania")),
						createLoc("Plosca", "sat", createAdresaCompleta("sat Plosca, comuna Bistreț, judetul Dolj, România", "sat Plosca, comuna Bistret, judetul Dolj, Romania")),
		]),
	createComuna("Bârca", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Bârca", "sat", createAdresaCompleta("sat Bârca, comuna Bârca, judetul Dolj, România", "sat Barca, comuna Barca, judetul Dolj, Romania")),
		]),
	createComuna("Botoșești-Paia", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Botoșești-Paia", "sat", createAdresaCompleta("sat Botoșești-Paia, comuna Botoșești-Paia, judetul Dolj, România", "sat Botosesti-Paia, comuna Botosesti-Paia, judetul Dolj, Romania")),
		]),
	createComuna("Brabova", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Brabova", "sat", createAdresaCompleta("sat Brabova, comuna Brabova, judetul Dolj, România", "sat Brabova, comuna Brabova, judetul Dolj, Romania")),
						createLoc("Caraiman", "sat", createAdresaCompleta("sat Caraiman, comuna Brabova, judetul Dolj, România", "sat Caraiman, comuna Brabova, judetul Dolj, Romania")),
						createLoc("Mosna", "sat", createAdresaCompleta("sat Mosna, comuna Brabova, judetul Dolj, România", "sat Mosna, comuna Brabova, judetul Dolj, Romania")),
						createLoc("Răchita de Jos", "sat", createAdresaCompleta("sat Răchita de Jos, comuna Brabova, judetul Dolj, România", "sat Rachita de Jos, comuna Brabova, judetul Dolj, Romania")),
						createLoc("Urdinița", "sat", createAdresaCompleta("sat Urdinița, comuna Brabova, judetul Dolj, România", "sat Urdinita, comuna Brabova, judetul Dolj, Romania")),
						createLoc("Voita", "sat", createAdresaCompleta("sat Voita, comuna Brabova, judetul Dolj, România", "sat Voita, comuna Brabova, judetul Dolj, Romania")),
		]),
	createComuna("Braloștița", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Braloștița", "sat", createAdresaCompleta("sat Braloștița, comuna Braloștița, judetul Dolj, România", "sat Bralostita, comuna Bralostita, judetul Dolj, Romania")),
						createLoc("Ciocanele", "sat", createAdresaCompleta("sat Ciocanele, comuna Braloștița, judetul Dolj, România", "sat Ciocanele, comuna Bralostita, judetul Dolj, Romania")),
						createLoc("Racovița", "sat", createAdresaCompleta("sat Racovița, comuna Braloștița, judetul Dolj, România", "sat Racovita, comuna Bralostita, judetul Dolj, Romania")),
						createLoc("Schitu", "sat", createAdresaCompleta("sat Schitu, comuna Braloștița, judetul Dolj, România", "sat Schitu, comuna Bralostita, judetul Dolj, Romania")),
						createLoc("Sfircea", "sat", createAdresaCompleta("sat Sfircea, comuna Braloștița, judetul Dolj, România", "sat Sfircea, comuna Bralostita, judetul Dolj, Romania")),
						createLoc("Valea Fântânilor", "sat", createAdresaCompleta("sat Valea Fântânilor, comuna Braloștița, judetul Dolj, România", "sat Valea Fantanilor, comuna Bralostita, judetul Dolj, Romania")),
		]),
	createComuna("Bratovoești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Bratovoești", "sat", createAdresaCompleta("sat Bratovoești, comuna Bratovoești, judetul Dolj, România", "sat Bratovoesti, comuna Bratovoesti, judetul Dolj, Romania")),
						createLoc("Bădoși", "sat", createAdresaCompleta("sat Bădoși, comuna Bratovoești, judetul Dolj, România", "sat Badosi, comuna Bratovoesti, judetul Dolj, Romania")),
						createLoc("Georocu Mare", "sat", createAdresaCompleta("sat Georocu Mare, comuna Bratovoești, judetul Dolj, România", "sat Georocu Mare, comuna Bratovoesti, judetul Dolj, Romania")),
						createLoc("Prunet", "sat", createAdresaCompleta("sat Prunet, comuna Bratovoești, judetul Dolj, România", "sat Prunet, comuna Bratovoesti, judetul Dolj, Romania")),
		]),
	createComuna("Brădești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Brădești", "sat", createAdresaCompleta("sat Brădești, comuna Brădești, judetul Dolj, România", "sat Bradesti, comuna Bradesti, judetul Dolj, Romania")),
						createLoc("Brădeștii Bătrâni", "sat", createAdresaCompleta("sat Brădeștii Bătrâni, comuna Brădești, judetul Dolj, România", "sat Bradestii Batrani, comuna Bradesti, judetul Dolj, Romania")),
						createLoc("Meteu", "sat", createAdresaCompleta("sat Meteu, comuna Brădești, judetul Dolj, România", "sat Meteu, comuna Bradesti, judetul Dolj, Romania")),
						createLoc("Piscani", "sat", createAdresaCompleta("sat Piscani, comuna Brădești, judetul Dolj, România", "sat Piscani, comuna Bradesti, judetul Dolj, Romania")),
						createLoc("Răcari", "sat", createAdresaCompleta("sat Răcari, comuna Brădești, judetul Dolj, România", "sat Racari, comuna Bradesti, judetul Dolj, Romania")),
						createLoc("Tatomirești", "sat", createAdresaCompleta("sat Tatomirești, comuna Brădești, judetul Dolj, România", "sat Tatomiresti, comuna Bradesti, judetul Dolj, Romania")),
		]),
	createComuna("Breasta", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Breasta", "sat", createAdresaCompleta("sat Breasta, comuna Breasta, judetul Dolj, România", "sat Breasta, comuna Breasta, judetul Dolj, Romania")),
						createLoc("Cotu", "sat", createAdresaCompleta("sat Cotu, comuna Breasta, judetul Dolj, România", "sat Cotu, comuna Breasta, judetul Dolj, Romania")),
						createLoc("Crovna", "sat", createAdresaCompleta("sat Crovna, comuna Breasta, judetul Dolj, România", "sat Crovna, comuna Breasta, judetul Dolj, Romania")),
						createLoc("Făget", "sat", createAdresaCompleta("sat Făget, comuna Breasta, judetul Dolj, România", "sat Faget, comuna Breasta, judetul Dolj, Romania")),
						createLoc("Obedin", "sat", createAdresaCompleta("sat Obedin, comuna Breasta, judetul Dolj, România", "sat Obedin, comuna Breasta, judetul Dolj, Romania")),
						createLoc("Roșieni", "sat", createAdresaCompleta("sat Roșieni, comuna Breasta, judetul Dolj, România", "sat Rosieni, comuna Breasta, judetul Dolj, Romania")),
						createLoc("Valea Lungului", "sat", createAdresaCompleta("sat Valea Lungului, comuna Breasta, judetul Dolj, România", "sat Valea Lungului, comuna Breasta, judetul Dolj, Romania")),
		]),
	createComuna("Bucovăț", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Bucovăț", "sat", createAdresaCompleta("sat Bucovăț, comuna Bucovăț, judetul Dolj, România", "sat Bucovat, comuna Bucovat, judetul Dolj, Romania")),
						createLoc("Cârligei", "sat", createAdresaCompleta("sat Cârligei, comuna Bucovăț, judetul Dolj, România", "sat Carligei, comuna Bucovat, judetul Dolj, Romania")),
						createLoc("Italieni", "sat", createAdresaCompleta("sat Italieni, comuna Bucovăț, judetul Dolj, România", "sat Italieni, comuna Bucovat, judetul Dolj, Romania")),
						createLoc("Leamna de Jos", "sat", createAdresaCompleta("sat Leamna de Jos, comuna Bucovăț, judetul Dolj, România", "sat Leamna de Jos, comuna Bucovat, judetul Dolj, Romania")),
						createLoc("Leamna de Sus", "sat", createAdresaCompleta("sat Leamna de Sus, comuna Bucovăț, judetul Dolj, România", "sat Leamna de Sus, comuna Bucovat, judetul Dolj, Romania")),
						createLoc("Palilula", "sat", createAdresaCompleta("sat Palilula, comuna Bucovăț, judetul Dolj, România", "sat Palilula, comuna Bucovat, judetul Dolj, Romania")),
						createLoc("Sărbătoarea", "sat", createAdresaCompleta("sat Sărbătoarea, comuna Bucovăț, judetul Dolj, România", "sat Sarbatoarea, comuna Bucovat, judetul Dolj, Romania")),
		]),
	createComuna("Bulzești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Prejoi", "sat", createAdresaCompleta("sat Prejoi, comuna Bulzești, judetul Dolj, România", "sat Prejoi, comuna Bulzesti, judetul Dolj, Romania")),
						createLoc("Bulzești", "sat", createAdresaCompleta("sat Bulzești, comuna Bulzești, judetul Dolj, România", "sat Bulzesti, comuna Bulzesti, judetul Dolj, Romania")),
						createLoc("Frățila", "sat", createAdresaCompleta("sat Frățila, comuna Bulzești, judetul Dolj, România", "sat Fratila, comuna Bulzesti, judetul Dolj, Romania")),
						createLoc("Gura Racului", "sat", createAdresaCompleta("sat Gura Racului, comuna Bulzești, judetul Dolj, România", "sat Gura Racului, comuna Bulzesti, judetul Dolj, Romania")),
						createLoc("Înfrățirea", "sat", createAdresaCompleta("sat Înfrățirea, comuna Bulzești, judetul Dolj, România", "sat Infratirea, comuna Bulzesti, judetul Dolj, Romania")),
						createLoc("Piscu Lung", "sat", createAdresaCompleta("sat Piscu Lung, comuna Bulzești, judetul Dolj, România", "sat Piscu Lung, comuna Bulzesti, judetul Dolj, Romania")),
						createLoc("Poienile", "sat", createAdresaCompleta("sat Poienile, comuna Bulzești, judetul Dolj, România", "sat Poienile, comuna Bulzesti, judetul Dolj, Romania")),
						createLoc("Săliște", "sat", createAdresaCompleta("sat Săliște, comuna Bulzești, judetul Dolj, România", "sat Saliste, comuna Bulzesti, judetul Dolj, Romania")),
						createLoc("Seculești", "sat", createAdresaCompleta("sat Seculești, comuna Bulzești, judetul Dolj, România", "sat Seculesti, comuna Bulzesti, judetul Dolj, Romania")),
						createLoc("Stoicești", "sat", createAdresaCompleta("sat Stoicești, comuna Bulzești, judetul Dolj, România", "sat Stoicesti, comuna Bulzesti, judetul Dolj, Romania")),
		]),
	createComuna("Calopăr", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Calopăr", "sat", createAdresaCompleta("sat Calopăr, comuna Calopăr, judetul Dolj, România", "sat Calopar, comuna Calopar, judetul Dolj, Romania")),
						createLoc("Belcinu", "sat", createAdresaCompleta("sat Belcinu, comuna Calopăr, judetul Dolj, România", "sat Belcinu, comuna Calopar, judetul Dolj, Romania")),
						createLoc("Bâzdâna", "sat", createAdresaCompleta("sat Bâzdâna, comuna Calopăr, judetul Dolj, România", "sat Bazdana, comuna Calopar, judetul Dolj, Romania")),
						createLoc("Panaghia", "sat", createAdresaCompleta("sat Panaghia, comuna Calopăr, judetul Dolj, România", "sat Panaghia, comuna Calopar, judetul Dolj, Romania")),
						createLoc("Sălcuța", "sat", createAdresaCompleta("sat Sălcuța, comuna Calopăr, judetul Dolj, România", "sat Salcuta, comuna Calopar, judetul Dolj, Romania")),
		]),
	createComuna("Caraula", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Caraula", "sat", createAdresaCompleta("sat Caraula, comuna Caraula, judetul Dolj, România", "sat Caraula, comuna Caraula, judetul Dolj, Romania")),
		]),
	createComuna("Carpen", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Carpen", "sat", createAdresaCompleta("sat Carpen, comuna Carpen, judetul Dolj, România", "sat Carpen, comuna Carpen, judetul Dolj, Romania")),
						createLoc("Cleanov", "sat", createAdresaCompleta("sat Cleanov, comuna Carpen, judetul Dolj, România", "sat Cleanov, comuna Carpen, judetul Dolj, Romania")),
						createLoc("Geblești", "sat", createAdresaCompleta("sat Geblești, comuna Carpen, judetul Dolj, România", "sat Geblesti, comuna Carpen, judetul Dolj, Romania")),
		]),
	createComuna("Castranova", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Castranova", "sat", createAdresaCompleta("sat Castranova, comuna Castranova, judetul Dolj, România", "sat Castranova, comuna Castranova, judetul Dolj, Romania")),
						createLoc("Puțuri", "sat", createAdresaCompleta("sat Puțuri, comuna Castranova, judetul Dolj, România", "sat Puturi, comuna Castranova, judetul Dolj, Romania")),
		]),
	createComuna("Catane", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Catane", "sat", createAdresaCompleta("sat Catane, comuna Catane, judetul Dolj, România", "sat Catane, comuna Catane, judetul Dolj, Romania")),
						createLoc("Catanele Noi", "sat", createAdresaCompleta("sat Catanele Noi, comuna Catane, judetul Dolj, România", "sat Catanele Noi, comuna Catane, judetul Dolj, Romania")),
		]),
	createComuna("Călărași", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Călărași", "sat", createAdresaCompleta("sat Călărași, comuna Călărași, judetul Dolj, România", "sat Calarasi, comuna Calarasi, judetul Dolj, Romania")),
						createLoc("Sărata", "sat", createAdresaCompleta("sat Sărata, comuna Călărași, judetul Dolj, România", "sat Sarata, comuna Calarasi, judetul Dolj, Romania")),
		]),
	createComuna("Cârcea", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Cârcea", "sat", createAdresaCompleta("sat Cârcea, comuna Cârcea, judetul Dolj, România", "sat Carcea, comuna Carcea, judetul Dolj, Romania")),
		]),
	createComuna("Cârna", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Cârna", "sat", createAdresaCompleta("sat Cârna, comuna Cârna, judetul Dolj, România", "sat Carna, comuna Carna, judetul Dolj, Romania")),
		]),
	createComuna("Celaru", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Celaru", "sat", createAdresaCompleta("sat Celaru, comuna Celaru, judetul Dolj, România", "sat Celaru, comuna Celaru, judetul Dolj, Romania")),
						createLoc("Ghizdăvești", "sat", createAdresaCompleta("sat Ghizdăvești, comuna Celaru, judetul Dolj, România", "sat Ghizdavesti, comuna Celaru, judetul Dolj, Romania")),
						createLoc("Marotinu de Jos", "sat", createAdresaCompleta("sat Marotinu de Jos, comuna Celaru, judetul Dolj, România", "sat Marotinu de Jos, comuna Celaru, judetul Dolj, Romania")),
						createLoc("Marotinu de Sus", "sat", createAdresaCompleta("sat Marotinu de Sus, comuna Celaru, judetul Dolj, România", "sat Marotinu de Sus, comuna Celaru, judetul Dolj, Romania")),
						createLoc("Soreni", "sat", createAdresaCompleta("sat Soreni, comuna Celaru, judetul Dolj, România", "sat Soreni, comuna Celaru, judetul Dolj, Romania")),
		]),
	createComuna("Cerăt", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Cerăt", "sat", createAdresaCompleta("sat Cerăt, comuna Cerăt, judetul Dolj, România", "sat Cerat, comuna Cerat, judetul Dolj, Romania")),
						createLoc("Malaica", "sat", createAdresaCompleta("sat Malaica, comuna Cerăt, judetul Dolj, România", "sat Malaica, comuna Cerat, judetul Dolj, Romania")),
		]),
	createComuna("Cernătești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Cernătești", "sat", createAdresaCompleta("sat Cernătești, comuna Cernătești, judetul Dolj, România", "sat Cernatesti, comuna Cernatesti, judetul Dolj, Romania")),
						createLoc("Cornița", "sat", createAdresaCompleta("sat Cornița, comuna Cernătești, judetul Dolj, România", "sat Cornita, comuna Cernatesti, judetul Dolj, Romania")),
						createLoc("Rasnicu Bătrân", "sat", createAdresaCompleta("sat Rasnicu Bătrân, comuna Cernătești, judetul Dolj, România", "sat Rasnicu Batran, comuna Cernatesti, judetul Dolj, Romania")),
						createLoc("Rasnicu Oghian", "sat", createAdresaCompleta("sat Rasnicu Oghian, comuna Cernătești, judetul Dolj, România", "sat Rasnicu Oghian, comuna Cernatesti, judetul Dolj, Romania")),
						createLoc("Țiu", "sat", createAdresaCompleta("sat Țiu, comuna Cernătești, judetul Dolj, România", "sat Tiu, comuna Cernatesti, judetul Dolj, Romania")),
		]),
	createComuna("Cetate", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Cetate", "sat", createAdresaCompleta("sat Cetate, comuna Cetate, judetul Dolj, România", "sat Cetate, comuna Cetate, judetul Dolj, Romania")),
						createLoc("Moreni", "sat", createAdresaCompleta("sat Moreni, comuna Cetate, judetul Dolj, România", "sat Moreni, comuna Cetate, judetul Dolj, Romania")),
		]),
	createComuna("Cioroiași", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Cioroiași", "sat", createAdresaCompleta("sat Cioroiași, comuna Cioroiași, judetul Dolj, România", "sat Cioroiasi, comuna Cioroiasi, judetul Dolj, Romania")),
						createLoc("Cetățuia", "sat", createAdresaCompleta("sat Cetățuia, comuna Cioroiași, judetul Dolj, România", "sat Cetatuia, comuna Cioroiasi, judetul Dolj, Romania")),
						createLoc("Cioroiu Nou", "sat", createAdresaCompleta("sat Cioroiu Nou, comuna Cioroiași, judetul Dolj, România", "sat Cioroiu Nou, comuna Cioroiasi, judetul Dolj, Romania")),
		]),
	createComuna("Ciupercenii Noi", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Ciupercenii Noi", "sat", createAdresaCompleta("sat Ciupercenii Noi, comuna Ciupercenii Noi, judetul Dolj, România", "sat Ciupercenii Noi, comuna Ciupercenii Noi, judetul Dolj, Romania")),
						createLoc("Smârdan", "sat", createAdresaCompleta("sat Smârdan, comuna Ciupercenii Noi, judetul Dolj, România", "sat Smardan, comuna Ciupercenii Noi, judetul Dolj, Romania")),
		]),
	createComuna("Coșoveni", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Coșoveni", "sat", createAdresaCompleta("sat Coșoveni, comuna Coșoveni, judetul Dolj, România", "sat Cosoveni, comuna Cosoveni, judetul Dolj, Romania")),
		]),
	createComuna("Coțofenii din Dos", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Coțofenii din Dos", "sat", createAdresaCompleta("sat Coțofenii din Dos, comuna Coțofenii din Dos, judetul Dolj, România", "sat Cotofenii din Dos, comuna Cotofenii din Dos, judetul Dolj, Romania")),
						createLoc("Mihăița", "sat", createAdresaCompleta("sat Mihăița, comuna Coțofenii din Dos, judetul Dolj, România", "sat Mihaita, comuna Cotofenii din Dos, judetul Dolj, Romania")),
						createLoc("Potmelțu", "sat", createAdresaCompleta("sat Potmelțu, comuna Coțofenii din Dos, judetul Dolj, România", "sat Potmeltu, comuna Cotofenii din Dos, judetul Dolj, Romania")),
		]),
	createComuna("Coțofenii din Față", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Coțofenii din Față", "sat", createAdresaCompleta("sat Coțofenii din Față, comuna Coțofenii din Față, judetul Dolj, România", "sat Cotofenii din Fata, comuna Cotofenii din Fata, judetul Dolj, Romania")),
						createLoc("Beharca", "sat", createAdresaCompleta("sat Beharca, comuna Coțofenii din Față, judetul Dolj, România", "sat Beharca, comuna Cotofenii din Fata, judetul Dolj, Romania")),
		]),
	createComuna("Daneți", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Daneți", "sat", createAdresaCompleta("sat Daneți, comuna Daneți, judetul Dolj, România", "sat Daneti, comuna Daneti, judetul Dolj, Romania")),
						createLoc("Brabeți", "sat", createAdresaCompleta("sat Brabeți, comuna Daneți, judetul Dolj, România", "sat Brabeti, comuna Daneti, judetul Dolj, Romania")),
						createLoc("Braniște", "sat", createAdresaCompleta("sat Braniște, comuna Daneți, judetul Dolj, România", "sat Braniste, comuna Daneti, judetul Dolj, Romania")),
						createLoc("Locusteni", "sat", createAdresaCompleta("sat Locusteni, comuna Daneți, judetul Dolj, România", "sat Locusteni, comuna Daneti, judetul Dolj, Romania")),
		]),
	createComuna("Desa", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Desa", "sat", createAdresaCompleta("sat Desa, comuna Desa, judetul Dolj, România", "sat Desa, comuna Desa, judetul Dolj, Romania")),
		]),
	createComuna("Dioști", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Dioști", "sat", createAdresaCompleta("sat Dioști, comuna Dioști, judetul Dolj, România", "sat Diosti, comuna Diosti, judetul Dolj, Romania")),
						createLoc("Ciocănești", "sat", createAdresaCompleta("sat Ciocănești, comuna Dioști, judetul Dolj, România", "sat Ciocanesti, comuna Diosti, judetul Dolj, Romania")),
						createLoc("Radomir", "sat", createAdresaCompleta("sat Radomir, comuna Dioști, judetul Dolj, România", "sat Radomir, comuna Diosti, judetul Dolj, Romania")),
		]),
	createComuna("Dobrești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Dobrești", "sat", createAdresaCompleta("sat Dobrești, comuna Dobrești, judetul Dolj, România", "sat Dobresti, comuna Dobresti, judetul Dolj, Romania")),
						createLoc("Căciulătești", "sat", createAdresaCompleta("sat Căciulătești, comuna Dobrești, judetul Dolj, România", "sat Caciulatesti, comuna Dobresti, judetul Dolj, Romania")),
						createLoc("Georocel", "sat", createAdresaCompleta("sat Georocel, comuna Dobrești, judetul Dolj, România", "sat Georocel, comuna Dobresti, judetul Dolj, Romania")),
						createLoc("Murta", "sat", createAdresaCompleta("sat Murta, comuna Dobrești, judetul Dolj, România", "sat Murta, comuna Dobresti, judetul Dolj, Romania")),
						createLoc("Toceni", "sat", createAdresaCompleta("sat Toceni, comuna Dobrești, judetul Dolj, România", "sat Toceni, comuna Dobresti, judetul Dolj, Romania")),
		]),
	createComuna("Dobrotești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Dobrotești", "sat", createAdresaCompleta("sat Dobrotești, comuna Dobrotești, judetul Dolj, România", "sat Dobrotesti, comuna Dobrotesti, judetul Dolj, Romania")),
						createLoc("Nisipuri", "sat", createAdresaCompleta("sat Nisipuri, comuna Dobrotești, judetul Dolj, România", "sat Nisipuri, comuna Dobrotesti, judetul Dolj, Romania")),
		]),
	createComuna("Drăgotești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Drăgotești", "sat", createAdresaCompleta("sat Drăgotești, comuna Drăgotești, judetul Dolj, România", "sat Dragotesti, comuna Dragotesti, judetul Dolj, Romania")),
						createLoc("Benești", "sat", createAdresaCompleta("sat Benești, comuna Drăgotești, judetul Dolj, România", "sat Benesti, comuna Dragotesti, judetul Dolj, Romania")),
						createLoc("Bobeanu", "sat", createAdresaCompleta("sat Bobeanu, comuna Drăgotești, judetul Dolj, România", "sat Bobeanu, comuna Dragotesti, judetul Dolj, Romania")),
						createLoc("Buzduc", "sat", createAdresaCompleta("sat Buzduc, comuna Drăgotești, judetul Dolj, România", "sat Buzduc, comuna Dragotesti, judetul Dolj, Romania")),
						createLoc("Popânzălești", "sat", createAdresaCompleta("sat Popânzălești, comuna Drăgotești, judetul Dolj, România", "sat Popanzalesti, comuna Dragotesti, judetul Dolj, Romania")),
						createLoc("Viișoara", "sat", createAdresaCompleta("sat Viișoara, comuna Drăgotești, judetul Dolj, România", "sat Viisoara, comuna Dragotesti, judetul Dolj, Romania")),
		]),
	createComuna("Drănic", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Drănic", "sat", createAdresaCompleta("sat Drănic, comuna Drănic, judetul Dolj, România", "sat Dranic, comuna Dranic, judetul Dolj, Romania")),
						createLoc("Booveni", "sat", createAdresaCompleta("sat Booveni, comuna Drănic, judetul Dolj, România", "sat Booveni, comuna Dranic, judetul Dolj, Romania")),
						createLoc("Foișor", "sat", createAdresaCompleta("sat Foișor, comuna Drănic, judetul Dolj, România", "sat Foisor, comuna Dranic, judetul Dolj, Romania")),
						createLoc("Padea", "sat", createAdresaCompleta("sat Padea, comuna Drănic, judetul Dolj, România", "sat Padea, comuna Dranic, judetul Dolj, Romania")),
		]),
	createComuna("Fărcaș", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Fărcaș", "sat", createAdresaCompleta("sat Fărcaș, comuna Fărcaș, judetul Dolj, România", "sat Farcas, comuna Farcas, judetul Dolj, Romania")),
						createLoc("Amărăști", "sat", createAdresaCompleta("sat Amărăști, comuna Fărcaș, judetul Dolj, România", "sat Amarasti, comuna Farcas, judetul Dolj, Romania")),
						createLoc("Golumbelu", "sat", createAdresaCompleta("sat Golumbelu, comuna Fărcaș, judetul Dolj, România", "sat Golumbelu, comuna Farcas, judetul Dolj, Romania")),
						createLoc("Golumbu", "sat", createAdresaCompleta("sat Golumbu, comuna Fărcaș, judetul Dolj, România", "sat Golumbu, comuna Farcas, judetul Dolj, Romania")),
						createLoc("Plopu-Amărăști", "sat", createAdresaCompleta("sat Plopu-Amărăști, comuna Fărcaș, judetul Dolj, România", "sat Plopu-Amarasti, comuna Farcas, judetul Dolj, Romania")),
		]),
	createComuna("Galicea Mare", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Galicea Mare", "sat", createAdresaCompleta("sat Galicea Mare, comuna Galicea Mare, judetul Dolj, România", "sat Galicea Mare, comuna Galicea Mare, judetul Dolj, Romania")),
		]),
	createComuna("Galiciuica", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Galiciuica", "sat", createAdresaCompleta("sat Galiciuica, comuna Galiciuica, judetul Dolj, România", "sat Galiciuica, comuna Galiciuica, judetul Dolj, Romania")),
		]),
	createComuna("Ghercești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Ghercești", "sat", createAdresaCompleta("sat Ghercești, comuna Ghercești, judetul Dolj, România", "sat Ghercesti, comuna Ghercesti, judetul Dolj, Romania")),
						createLoc("Gârlești", "sat", createAdresaCompleta("sat Gârlești, comuna Ghercești, judetul Dolj, România", "sat Garlesti, comuna Ghercesti, judetul Dolj, Romania")),
						createLoc("Luncșoru", "sat", createAdresaCompleta("sat Luncșoru, comuna Ghercești, judetul Dolj, România", "sat Luncsoru, comuna Ghercesti, judetul Dolj, Romania")),
						createLoc("Ungureni", "sat", createAdresaCompleta("sat Ungureni, comuna Ghercești, judetul Dolj, România", "sat Ungureni, comuna Ghercesti, judetul Dolj, Romania")),
						createLoc("Ungurenii Mici", "sat", createAdresaCompleta("sat Ungurenii Mici, comuna Ghercești, judetul Dolj, România", "sat Ungurenii Mici, comuna Ghercesti, judetul Dolj, Romania")),
		]),
	createComuna("Ghidici", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Ghidici", "sat", createAdresaCompleta("sat Ghidici, comuna Ghidici, judetul Dolj, România", "sat Ghidici, comuna Ghidici, judetul Dolj, Romania")),
		]),
	createComuna("Ghindeni", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Ghindeni", "sat", createAdresaCompleta("sat Ghindeni, comuna Ghindeni, judetul Dolj, România", "sat Ghindeni, comuna Ghindeni, judetul Dolj, Romania")),
		]),
	createComuna("Gighera", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Gighera", "sat", createAdresaCompleta("sat Gighera, comuna Gighera, judetul Dolj, România", "sat Gighera, comuna Gighera, judetul Dolj, Romania")),
						createLoc("Nedeia", "sat", createAdresaCompleta("sat Nedeia, comuna Gighera, judetul Dolj, România", "sat Nedeia, comuna Gighera, judetul Dolj, Romania")),
						createLoc("Zăval", "sat", createAdresaCompleta("sat Zăval, comuna Gighera, judetul Dolj, România", "sat Zaval, comuna Gighera, judetul Dolj, Romania")),
		]),
	createComuna("Giubega", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Giubega", "sat", createAdresaCompleta("sat Giubega, comuna Giubega, judetul Dolj, România", "sat Giubega, comuna Giubega, judetul Dolj, Romania")),
		]),
	createComuna("Giurgița", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Giurgița", "sat", createAdresaCompleta("sat Giurgița, comuna Giurgița, judetul Dolj, România", "sat Giurgita, comuna Giurgita, judetul Dolj, Romania")),
						createLoc("Curmătura", "sat", createAdresaCompleta("sat Curmătura, comuna Giurgița, judetul Dolj, România", "sat Curmatura, comuna Giurgita, judetul Dolj, Romania")),
						createLoc("Filaret", "sat", createAdresaCompleta("sat Filaret, comuna Giurgița, judetul Dolj, România", "sat Filaret, comuna Giurgita, judetul Dolj, Romania")),
		]),
	createComuna("Gângiova", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Gângiova", "sat", createAdresaCompleta("sat Gângiova, comuna Gângiova, judetul Dolj, România", "sat Gangiova, comuna Gangiova, judetul Dolj, Romania")),
						createLoc("Comoșteni", "sat", createAdresaCompleta("sat Comoșteni, comuna Gângiova, judetul Dolj, România", "sat Comosteni, comuna Gangiova, judetul Dolj, Romania")),
		]),
	createComuna("Gogoșu", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Gogoșu", "sat", createAdresaCompleta("sat Gogoșu, comuna Gogoșu, judetul Dolj, România", "sat Gogosu, comuna Gogosu, judetul Dolj, Romania")),
						createLoc("Gogoșița", "sat", createAdresaCompleta("sat Gogoșița, comuna Gogoșu, judetul Dolj, România", "sat Gogosita, comuna Gogosu, judetul Dolj, Romania")),
						createLoc("Ștefănel", "sat", createAdresaCompleta("sat Ștefănel, comuna Gogoșu, judetul Dolj, România", "sat Stefanel, comuna Gogosu, judetul Dolj, Romania")),
		]),
	createComuna("Goicea", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Goicea", "sat", createAdresaCompleta("sat Goicea, comuna Goicea, judetul Dolj, România", "sat Goicea, comuna Goicea, judetul Dolj, Romania")),
		]),
	createComuna("Goiești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Goiești", "sat", createAdresaCompleta("sat Goiești, comuna Goiești, judetul Dolj, România", "sat Goiesti, comuna Goiesti, judetul Dolj, Romania")),
						createLoc("Adâncata", "sat", createAdresaCompleta("sat Adâncata, comuna Goiești, judetul Dolj, România", "sat Adancata, comuna Goiesti, judetul Dolj, Romania")),
						createLoc("Fântâni", "sat", createAdresaCompleta("sat Fântâni, comuna Goiești, judetul Dolj, România", "sat Fantani, comuna Goiesti, judetul Dolj, Romania")),
						createLoc("Gruița", "sat", createAdresaCompleta("sat Gruița, comuna Goiești, judetul Dolj, România", "sat Gruita, comuna Goiesti, judetul Dolj, Romania")),
						createLoc("Mălăești", "sat", createAdresaCompleta("sat Mălăești, comuna Goiești, judetul Dolj, România", "sat Malaesti, comuna Goiesti, judetul Dolj, Romania")),
						createLoc("Mogoșești", "sat", createAdresaCompleta("sat Mogoșești, comuna Goiești, judetul Dolj, România", "sat Mogosesti, comuna Goiesti, judetul Dolj, Romania")),
						createLoc("Muereni", "sat", createAdresaCompleta("sat Muereni, comuna Goiești, judetul Dolj, România", "sat Muereni, comuna Goiesti, judetul Dolj, Romania")),
						createLoc("Piorești", "sat", createAdresaCompleta("sat Piorești, comuna Goiești, judetul Dolj, România", "sat Pioresti, comuna Goiesti, judetul Dolj, Romania")),
						createLoc("Pometești", "sat", createAdresaCompleta("sat Pometești, comuna Goiești, judetul Dolj, România", "sat Pometesti, comuna Goiesti, judetul Dolj, Romania")),
						createLoc("Popeasa", "sat", createAdresaCompleta("sat Popeasa, comuna Goiești, judetul Dolj, România", "sat Popeasa, comuna Goiesti, judetul Dolj, Romania")),
						createLoc("Țandăra", "sat", createAdresaCompleta("sat Țandăra, comuna Goiești, judetul Dolj, România", "sat Tandara, comuna Goiesti, judetul Dolj, Romania")),
						createLoc("Vladimir", "sat", createAdresaCompleta("sat Vladimir, comuna Goiești, judetul Dolj, România", "sat Vladimir, comuna Goiesti, judetul Dolj, Romania")),
						createLoc("Zlătari", "sat", createAdresaCompleta("sat Zlătari, comuna Goiești, judetul Dolj, România", "sat Zlatari, comuna Goiesti, judetul Dolj, Romania")),
		]),
	createComuna("Grecești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Grecești", "sat", createAdresaCompleta("sat Grecești, comuna Grecești, judetul Dolj, România", "sat Grecesti, comuna Grecesti, judetul Dolj, Romania")),
						createLoc("Bărboi", "sat", createAdresaCompleta("sat Bărboi, comuna Grecești, judetul Dolj, România", "sat Barboi, comuna Grecesti, judetul Dolj, Romania")),
						createLoc("Busu", "sat", createAdresaCompleta("sat Busu, comuna Grecești, judetul Dolj, România", "sat Busu, comuna Grecesti, judetul Dolj, Romania")),
						createLoc("Busulețu", "sat", createAdresaCompleta("sat Busulețu, comuna Grecești, judetul Dolj, România", "sat Busuletu, comuna Grecesti, judetul Dolj, Romania")),
						createLoc("Grădiștea", "sat", createAdresaCompleta("sat Grădiștea, comuna Grecești, judetul Dolj, România", "sat Gradistea, comuna Grecesti, judetul Dolj, Romania")),
						createLoc("Gropanele", "sat", createAdresaCompleta("sat Gropanele, comuna Grecești, judetul Dolj, România", "sat Gropanele, comuna Grecesti, judetul Dolj, Romania")),
		]),
	createComuna("Ișalnița", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Ișalnița", "sat", createAdresaCompleta("sat Ișalnița, comuna Ișalnița, judetul Dolj, România", "sat Isalnita, comuna Isalnita, judetul Dolj, Romania")),
		]),
	createComuna("Izvoare", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Izvoare", "sat", createAdresaCompleta("sat Izvoare, comuna Izvoare, judetul Dolj, România", "sat Izvoare, comuna Izvoare, judetul Dolj, Romania")),
						createLoc("Corlate", "sat", createAdresaCompleta("sat Corlate, comuna Izvoare, judetul Dolj, România", "sat Corlate, comuna Izvoare, judetul Dolj, Romania")),
						createLoc("Domnu Tudor", "sat", createAdresaCompleta("sat Domnu Tudor, comuna Izvoare, judetul Dolj, România", "sat Domnu Tudor, comuna Izvoare, judetul Dolj, Romania")),
		]),
	createComuna("Întorsura", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Întorsura", "sat", createAdresaCompleta("sat Întorsura, comuna Întorsura, judetul Dolj, România", "sat Intorsura, comuna Intorsura, judetul Dolj, Romania")),
		]),
	createComuna("Leu", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Leu", "sat", createAdresaCompleta("sat Leu, comuna Leu, judetul Dolj, România", "sat Leu, comuna Leu, judetul Dolj, Romania")),
						createLoc("Zănoaga", "sat", createAdresaCompleta("sat Zănoaga, comuna Leu, judetul Dolj, România", "sat Zanoaga, comuna Leu, judetul Dolj, Romania")),
		]),
	createComuna("Lipovu", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Lipovu", "sat", createAdresaCompleta("sat Lipovu, comuna Lipovu, judetul Dolj, România", "sat Lipovu, comuna Lipovu, judetul Dolj, Romania")),
						createLoc("Lipovu de Sus", "sat", createAdresaCompleta("sat Lipovu de Sus, comuna Lipovu, judetul Dolj, România", "sat Lipovu de Sus, comuna Lipovu, judetul Dolj, Romania")),
		]),
	createComuna("Maglavit", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Maglavit", "sat", createAdresaCompleta("sat Maglavit, comuna Maglavit, judetul Dolj, România", "sat Maglavit, comuna Maglavit, judetul Dolj, Romania")),
						createLoc("Hunia", "sat", createAdresaCompleta("sat Hunia, comuna Maglavit, judetul Dolj, România", "sat Hunia, comuna Maglavit, judetul Dolj, Romania")),
		]),
	createComuna("Malu Mare", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Malu Mare", "sat", createAdresaCompleta("sat Malu Mare, comuna Malu Mare, judetul Dolj, România", "sat Malu Mare, comuna Malu Mare, judetul Dolj, Romania")),
						createLoc("Preajba", "sat", createAdresaCompleta("sat Preajba, comuna Malu Mare, judetul Dolj, România", "sat Preajba, comuna Malu Mare, judetul Dolj, Romania")),
		]),
	createComuna("Măceșu de Jos", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Măceșu de Jos", "sat", createAdresaCompleta("sat Măceșu de Jos, comuna Măceșu de Jos, judetul Dolj, România", "sat Macesu de Jos, comuna Macesu de Jos, judetul Dolj, Romania")),
						createLoc("Săpata", "sat", createAdresaCompleta("sat Săpata, comuna Măceșu de Jos, judetul Dolj, România", "sat Sapata, comuna Macesu de Jos, judetul Dolj, Romania")),
		]),
	createComuna("Măceșu de Sus", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Măceșu de Sus", "sat", createAdresaCompleta("sat Măceșu de Sus, comuna Măceșu de Sus, judetul Dolj, România", "sat Macesu de Sus, comuna Macesu de Sus, judetul Dolj, Romania")),
		]),
	createComuna("Melinești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Melinești", "sat", createAdresaCompleta("sat Melinești, comuna Melinești, judetul Dolj, România", "sat Melinesti, comuna Melinesti, judetul Dolj, Romania")),
						createLoc("Bodăiești", "sat", createAdresaCompleta("sat Bodăiești, comuna Melinești, judetul Dolj, România", "sat Bodaiesti, comuna Melinesti, judetul Dolj, Romania")),
						createLoc("Bodăieștii de Sus", "sat", createAdresaCompleta("sat Bodăieștii de Sus, comuna Melinești, judetul Dolj, România", "sat Bodaiestii de Sus, comuna Melinesti, judetul Dolj, Romania")),
						createLoc("Godeni", "sat", createAdresaCompleta("sat Godeni, comuna Melinești, judetul Dolj, România", "sat Godeni, comuna Melinesti, judetul Dolj, Romania")),
						createLoc("Muierușu", "sat", createAdresaCompleta("sat Muierușu, comuna Melinești, judetul Dolj, România", "sat Muierusu, comuna Melinesti, judetul Dolj, Romania")),
						createLoc("Negoiești", "sat", createAdresaCompleta("sat Negoiești, comuna Melinești, judetul Dolj, România", "sat Negoiesti, comuna Melinesti, judetul Dolj, Romania")),
						createLoc("Odoleni", "sat", createAdresaCompleta("sat Odoleni, comuna Melinești, judetul Dolj, România", "sat Odoleni, comuna Melinesti, judetul Dolj, Romania")),
						createLoc("Ohaba", "sat", createAdresaCompleta("sat Ohaba, comuna Melinești, judetul Dolj, România", "sat Ohaba, comuna Melinesti, judetul Dolj, Romania")),
						createLoc("Ploștina", "sat", createAdresaCompleta("sat Ploștina, comuna Melinești, judetul Dolj, România", "sat Plostina, comuna Melinesti, judetul Dolj, Romania")),
						createLoc("Popești", "sat", createAdresaCompleta("sat Popești, comuna Melinești, judetul Dolj, România", "sat Popesti, comuna Melinesti, judetul Dolj, Romania")),
						createLoc("Spineni", "sat", createAdresaCompleta("sat Spineni, comuna Melinești, judetul Dolj, România", "sat Spineni, comuna Melinesti, judetul Dolj, Romania")),
						createLoc("Valea Mare", "sat", createAdresaCompleta("sat Valea Mare, comuna Melinești, judetul Dolj, România", "sat Valea Mare, comuna Melinesti, judetul Dolj, Romania")),
						createLoc("Valea Muierii de Jos", "sat", createAdresaCompleta("sat Valea Muierii de Jos, comuna Melinești, judetul Dolj, România", "sat Valea Muierii de Jos, comuna Melinesti, judetul Dolj, Romania")),
		]),
	createComuna("Mischii", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Mischii", "sat", createAdresaCompleta("sat Mischii, comuna Mischii, judetul Dolj, România", "sat Mischii, comuna Mischii, judetul Dolj, Romania")),
						createLoc("Călinești", "sat", createAdresaCompleta("sat Călinești, comuna Mischii, judetul Dolj, România", "sat Calinesti, comuna Mischii, judetul Dolj, Romania")),
						createLoc("Gogoșești", "sat", createAdresaCompleta("sat Gogoșești, comuna Mischii, judetul Dolj, România", "sat Gogosesti, comuna Mischii, judetul Dolj, Romania")),
						createLoc("Mlecănești", "sat", createAdresaCompleta("sat Mlecănești, comuna Mischii, judetul Dolj, România", "sat Mlecanesti, comuna Mischii, judetul Dolj, Romania")),
						createLoc("Motoci", "sat", createAdresaCompleta("sat Motoci, comuna Mischii, judetul Dolj, România", "sat Motoci, comuna Mischii, judetul Dolj, Romania")),
						createLoc("Urechești", "sat", createAdresaCompleta("sat Urechești, comuna Mischii, judetul Dolj, România", "sat Urechesti, comuna Mischii, judetul Dolj, Romania")),
		]),
	createComuna("Mârșani", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Mârșani", "sat", createAdresaCompleta("sat Mârșani, comuna Mârșani, judetul Dolj, România", "sat Marsani, comuna Marsani, judetul Dolj, Romania")),
		]),
	createComuna("Moțăței", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Moțăței", "sat", createAdresaCompleta("sat Moțăței, comuna Moțăței, judetul Dolj, România", "sat Motatei, comuna Motatei, judetul Dolj, Romania")),
						createLoc("Dobridor", "sat", createAdresaCompleta("sat Dobridor, comuna Moțăței, judetul Dolj, România", "sat Dobridor, comuna Motatei, judetul Dolj, Romania")),
						createLoc("Moțăței-Gară", "sat", createAdresaCompleta("sat Moțăței-Gară, comuna Moțăței, judetul Dolj, România", "sat Motatei-Gara, comuna Motatei, judetul Dolj, Romania")),
		]),
	createComuna("Murgași", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Balota de Jos", "sat", createAdresaCompleta("sat Balota de Jos, comuna Murgași, judetul Dolj, România", "sat Balota de Jos, comuna Murgasi, judetul Dolj, Romania")),
						createLoc("Balota de Sus", "sat", createAdresaCompleta("sat Balota de Sus, comuna Murgași, judetul Dolj, România", "sat Balota de Sus, comuna Murgasi, judetul Dolj, Romania")),
						createLoc("Bușteni", "sat", createAdresaCompleta("sat Bușteni, comuna Murgași, judetul Dolj, România", "sat Busteni, comuna Murgasi, judetul Dolj, Romania")),
						createLoc("Gaia", "sat", createAdresaCompleta("sat Gaia, comuna Murgași, judetul Dolj, România", "sat Gaia, comuna Murgasi, judetul Dolj, Romania")),
						createLoc("Murgași", "sat", createAdresaCompleta("sat Murgași, comuna Murgași, judetul Dolj, România", "sat Murgasi, comuna Murgasi, judetul Dolj, Romania")),
						createLoc("Picăturile", "sat", createAdresaCompleta("sat Picăturile, comuna Murgași, judetul Dolj, România", "sat Picaturile, comuna Murgasi, judetul Dolj, Romania")),
						createLoc("Rupturile", "sat", createAdresaCompleta("sat Rupturile, comuna Murgași, judetul Dolj, România", "sat Rupturile, comuna Murgasi, judetul Dolj, Romania")),
						createLoc("Velești", "sat", createAdresaCompleta("sat Velești, comuna Murgași, judetul Dolj, România", "sat Velesti, comuna Murgasi, judetul Dolj, Romania")),
		]),
	createComuna("Negoi", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Negoi", "sat", createAdresaCompleta("sat Negoi, comuna Negoi, judetul Dolj, România", "sat Negoi, comuna Negoi, judetul Dolj, Romania")),
		]),
	createComuna("Orodel", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Orodel", "sat", createAdresaCompleta("sat Orodel, comuna Orodel, judetul Dolj, România", "sat Orodel, comuna Orodel, judetul Dolj, Romania")),
						createLoc("Bechet", "sat", createAdresaCompleta("sat Bechet, comuna Orodel, judetul Dolj, România", "sat Bechet, comuna Orodel, judetul Dolj, Romania")),
						createLoc("Călugărei", "sat", createAdresaCompleta("sat Călugărei, comuna Orodel, judetul Dolj, România", "sat Calugarei, comuna Orodel, judetul Dolj, Romania")),
						createLoc("Cornu", "sat", createAdresaCompleta("sat Cornu, comuna Orodel, judetul Dolj, România", "sat Cornu, comuna Orodel, judetul Dolj, Romania")),
						createLoc("Teiu", "sat", createAdresaCompleta("sat Teiu, comuna Orodel, judetul Dolj, România", "sat Teiu, comuna Orodel, judetul Dolj, Romania")),
		]),
	createComuna("Ostroveni", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Ostroveni", "sat", createAdresaCompleta("sat Ostroveni, comuna Ostroveni, judetul Dolj, România", "sat Ostroveni, comuna Ostroveni, judetul Dolj, Romania")),
						createLoc("Lișteava", "sat", createAdresaCompleta("sat Lișteava, comuna Ostroveni, judetul Dolj, România", "sat Listeava, comuna Ostroveni, judetul Dolj, Romania")),
		]),
	createComuna("Perișor", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Perișor", "sat", createAdresaCompleta("sat Perișor, comuna Perișor, judetul Dolj, România", "sat Perisor, comuna Perisor, judetul Dolj, Romania")),
						createLoc("Mărăcinele", "sat", createAdresaCompleta("sat Mărăcinele, comuna Perișor, judetul Dolj, România", "sat Maracinele, comuna Perisor, judetul Dolj, Romania")),
		]),
	createComuna("Pielești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Pielești", "sat", createAdresaCompleta("sat Pielești, comuna Pielești, judetul Dolj, România", "sat Pielesti, comuna Pielesti, judetul Dolj, Romania")),
						createLoc("Câmpeni", "sat", createAdresaCompleta("sat Câmpeni, comuna Pielești, judetul Dolj, România", "sat Campeni, comuna Pielesti, judetul Dolj, Romania")),
						createLoc("Lânga", "sat", createAdresaCompleta("sat Lânga, comuna Pielești, judetul Dolj, România", "sat Langa, comuna Pielesti, judetul Dolj, Romania")),
		]),
	createComuna("Piscu Vechi", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Piscu Vechi", "sat", createAdresaCompleta("sat Piscu Vechi, comuna Piscu Vechi, judetul Dolj, România", "sat Piscu Vechi, comuna Piscu Vechi, judetul Dolj, Romania")),
						createLoc("Pisculeț", "sat", createAdresaCompleta("sat Pisculeț, comuna Piscu Vechi, judetul Dolj, România", "sat Pisculet, comuna Piscu Vechi, judetul Dolj, Romania")),
		]),
	createComuna("Plenița", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Plenița", "sat", createAdresaCompleta("sat Plenița, comuna Plenița, judetul Dolj, România", "sat Plenita, comuna Plenita, judetul Dolj, Romania")),
						createLoc("Castrele Traiane", "sat", createAdresaCompleta("sat Castrele Traiane, comuna Plenița, judetul Dolj, România", "sat Castrele Traiane, comuna Plenita, judetul Dolj, Romania")),
		]),
	createComuna("Pleșoi", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Pleșoi", "sat", createAdresaCompleta("sat Pleșoi, comuna Pleșoi, judetul Dolj, România", "sat Plesoi, comuna Plesoi, judetul Dolj, Romania")),
						createLoc("Cârstovani", "sat", createAdresaCompleta("sat Cârstovani, comuna Pleșoi, judetul Dolj, România", "sat Carstovani, comuna Plesoi, judetul Dolj, Romania")),
						createLoc("Frasin", "sat", createAdresaCompleta("sat Frasin, comuna Pleșoi, judetul Dolj, România", "sat Frasin, comuna Plesoi, judetul Dolj, Romania")),
						createLoc("Milovan", "sat", createAdresaCompleta("sat Milovan, comuna Pleșoi, judetul Dolj, România", "sat Milovan, comuna Plesoi, judetul Dolj, Romania")),
		]),
	createComuna("Podari", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Podari", "sat", createAdresaCompleta("sat Podari, comuna Podari, judetul Dolj, România", "sat Podari, comuna Podari, judetul Dolj, Romania")),
						createLoc("Balta Verde", "sat", createAdresaCompleta("sat Balta Verde, comuna Podari, judetul Dolj, România", "sat Balta Verde, comuna Podari, judetul Dolj, Romania")),
						createLoc("Braniște", "sat", createAdresaCompleta("sat Braniște, comuna Podari, judetul Dolj, România", "sat Braniste, comuna Podari, judetul Dolj, Romania")),
						createLoc("Gura Văii", "sat", createAdresaCompleta("sat Gura Văii, comuna Podari, judetul Dolj, România", "sat Gura Vaii, comuna Podari, judetul Dolj, Romania")),
						createLoc("Livezi", "sat", createAdresaCompleta("sat Livezi, comuna Podari, judetul Dolj, România", "sat Livezi, comuna Podari, judetul Dolj, Romania")),
		]),
	createComuna("Poiana Mare", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Poiana Mare", "sat", createAdresaCompleta("sat Poiana Mare, comuna Poiana Mare, judetul Dolj, România", "sat Poiana Mare, comuna Poiana Mare, judetul Dolj, Romania")),
						createLoc("Tunarii Noi", "sat", createAdresaCompleta("sat Tunarii Noi, comuna Poiana Mare, judetul Dolj, România", "sat Tunarii Noi, comuna Poiana Mare, judetul Dolj, Romania")),
						createLoc("Tunarii Vechi", "sat", createAdresaCompleta("sat Tunarii Vechi, comuna Poiana Mare, judetul Dolj, România", "sat Tunarii Vechi, comuna Poiana Mare, judetul Dolj, Romania")),
		]),
	createComuna("Predești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Predești", "sat", createAdresaCompleta("sat Predești, comuna Predești, judetul Dolj, România", "sat Predesti, comuna Predesti, judetul Dolj, Romania")),
						createLoc("Bucicani", "sat", createAdresaCompleta("sat Bucicani, comuna Predești, judetul Dolj, România", "sat Bucicani, comuna Predesti, judetul Dolj, Romania")),
						createLoc("Predeștii Mici", "sat", createAdresaCompleta("sat Predeștii Mici, comuna Predești, judetul Dolj, România", "sat Predestii Mici, comuna Predesti, judetul Dolj, Romania")),
		]),
	createComuna("Radovan", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Radovan", "sat", createAdresaCompleta("sat Radovan, comuna Radovan, judetul Dolj, România", "sat Radovan, comuna Radovan, judetul Dolj, Romania")),
						createLoc("Fântânele", "sat", createAdresaCompleta("sat Fântânele, comuna Radovan, judetul Dolj, România", "sat Fantanele, comuna Radovan, judetul Dolj, Romania")),
						createLoc("Târnava", "sat", createAdresaCompleta("sat Târnava, comuna Radovan, judetul Dolj, România", "sat Tarnava, comuna Radovan, judetul Dolj, Romania")),
		]),
	createComuna("Rast", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Rast", "sat", createAdresaCompleta("sat Rast, comuna Rast, judetul Dolj, România", "sat Rast, comuna Rast, judetul Dolj, Romania")),
		]),
	createComuna("Robănești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Robăneștii de Jos", "sat", createAdresaCompleta("sat Robăneștii de Jos, comuna Robănești, judetul Dolj, România", "sat Robanestii de Jos, comuna Robanesti, judetul Dolj, Romania")),
						createLoc("Bojoiu", "sat", createAdresaCompleta("sat Bojoiu, comuna Robănești, judetul Dolj, România", "sat Bojoiu, comuna Robanesti, judetul Dolj, Romania")),
						createLoc("Golfin", "sat", createAdresaCompleta("sat Golfin, comuna Robănești, judetul Dolj, România", "sat Golfin, comuna Robanesti, judetul Dolj, Romania")),
						createLoc("Lăcrița Mare", "sat", createAdresaCompleta("sat Lăcrița Mare, comuna Robănești, judetul Dolj, România", "sat Lacrita Mare, comuna Robanesti, judetul Dolj, Romania")),
						createLoc("Lăcrița Mică", "sat", createAdresaCompleta("sat Lăcrița Mică, comuna Robănești, judetul Dolj, România", "sat Lacrita Mica, comuna Robanesti, judetul Dolj, Romania")),
						createLoc("Robăneștii de Sus", "sat", createAdresaCompleta("sat Robăneștii de Sus, comuna Robănești, judetul Dolj, România", "sat Robanestii de Sus, comuna Robanesti, judetul Dolj, Romania")),
		]),
	createComuna("Rojiște", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Rojiște", "sat", createAdresaCompleta("sat Rojiște, comuna Rojiște, judetul Dolj, România", "sat Rojiste, comuna Rojiste, judetul Dolj, Romania")),
						createLoc("Tâmburești", "sat", createAdresaCompleta("sat Tâmburești, comuna Rojiște, judetul Dolj, România", "sat Tamburesti, comuna Rojiste, judetul Dolj, Romania")),
		]),
	createComuna("Sadova", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Sadova", "sat", createAdresaCompleta("sat Sadova, comuna Sadova, judetul Dolj, România", "sat Sadova, comuna Sadova, judetul Dolj, Romania")),
						createLoc("Piscu Sadovei", "sat", createAdresaCompleta("sat Piscu Sadovei, comuna Sadova, judetul Dolj, România", "sat Piscu Sadovei, comuna Sadova, judetul Dolj, Romania")),
		]),
	createComuna("Sălcuța", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Sălcuța", "sat", createAdresaCompleta("sat Sălcuța, comuna Sălcuța, judetul Dolj, România", "sat Salcuta, comuna Salcuta, judetul Dolj, Romania")),
						createLoc("Mârza", "sat", createAdresaCompleta("sat Mârza, comuna Sălcuța, judetul Dolj, România", "sat Marza, comuna Salcuta, judetul Dolj, Romania")),
						createLoc("Plopșor", "sat", createAdresaCompleta("sat Plopșor, comuna Sălcuța, judetul Dolj, România", "sat Plopsor, comuna Salcuta, judetul Dolj, Romania")),
						createLoc("Tencănău", "sat", createAdresaCompleta("sat Tencănău, comuna Sălcuța, judetul Dolj, România", "sat Tencanau, comuna Salcuta, judetul Dolj, Romania")),
		]),
	createComuna("Scăești", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Scăești", "sat", createAdresaCompleta("sat Scăești, comuna Scăești, judetul Dolj, România", "sat Scaesti, comuna Scaesti, judetul Dolj, Romania")),
						createLoc("Valea lui Pătru", "sat", createAdresaCompleta("sat Valea lui Pătru, comuna Scăești, judetul Dolj, România", "sat Valea lui Patru, comuna Scaesti, judetul Dolj, Romania")),
		]),
	createComuna("Seaca de Câmp", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Seaca de Câmp", "sat", createAdresaCompleta("sat Seaca de Câmp, comuna Seaca de Câmp, judetul Dolj, România", "sat Seaca de Camp, comuna Seaca de Camp, judetul Dolj, Romania")),
						createLoc("Piscu Nou", "sat", createAdresaCompleta("sat Piscu Nou, comuna Seaca de Câmp, judetul Dolj, România", "sat Piscu Nou, comuna Seaca de Camp, judetul Dolj, Romania")),
		]),
	createComuna("Seaca de Pădure", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Seaca de Pădure", "sat", createAdresaCompleta("sat Seaca de Pădure, comuna Seaca de Pădure, judetul Dolj, România", "sat Seaca de Padure, comuna Seaca de Padure, judetul Dolj, Romania")),
						createLoc("Răchita de Sus", "sat", createAdresaCompleta("sat Răchita de Sus, comuna Seaca de Pădure, judetul Dolj, România", "sat Rachita de Sus, comuna Seaca de Padure, judetul Dolj, Romania")),
						createLoc("Veleni", "sat", createAdresaCompleta("sat Veleni, comuna Seaca de Pădure, judetul Dolj, România", "sat Veleni, comuna Seaca de Padure, judetul Dolj, Romania")),
		]),
	createComuna("Secu", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Secu", "sat", createAdresaCompleta("sat Secu, comuna Secu, judetul Dolj, România", "sat Secu, comuna Secu, judetul Dolj, Romania")),
						createLoc("Comănicea", "sat", createAdresaCompleta("sat Comănicea, comuna Secu, judetul Dolj, România", "sat Comanicea, comuna Secu, judetul Dolj, Romania")),
						createLoc("Smadovicioara de Secu", "sat", createAdresaCompleta("sat Smadovicioara de Secu, comuna Secu, judetul Dolj, România", "sat Smadovicioara de Secu, comuna Secu, judetul Dolj, Romania")),
						createLoc("Șumandra", "sat", createAdresaCompleta("sat Șumandra, comuna Secu, judetul Dolj, România", "sat Sumandra, comuna Secu, judetul Dolj, Romania")),
		]),
	createComuna("Siliștea Crucii", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Siliștea Crucii", "sat", createAdresaCompleta("sat Siliștea Crucii, comuna Siliștea Crucii, judetul Dolj, România", "sat Silistea Crucii, comuna Silistea Crucii, judetul Dolj, Romania")),
		]),
	createComuna("Sopot", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Sopot", "sat", createAdresaCompleta("sat Sopot, comuna Sopot, judetul Dolj, România", "sat Sopot, comuna Sopot, judetul Dolj, Romania")),
						createLoc("Bașcov", "sat", createAdresaCompleta("sat Bașcov, comuna Sopot, judetul Dolj, România", "sat Bascov, comuna Sopot, judetul Dolj, Romania")),
						createLoc("Beloț", "sat", createAdresaCompleta("sat Beloț, comuna Sopot, judetul Dolj, România", "sat Belot, comuna Sopot, judetul Dolj, Romania")),
						createLoc("Cernat", "sat", createAdresaCompleta("sat Cernat, comuna Sopot, judetul Dolj, România", "sat Cernat, comuna Sopot, judetul Dolj, Romania")),
						createLoc("Pereni", "sat", createAdresaCompleta("sat Pereni, comuna Sopot, judetul Dolj, România", "sat Pereni, comuna Sopot, judetul Dolj, Romania")),
						createLoc("Pietroaia", "sat", createAdresaCompleta("sat Pietroaia, comuna Sopot, judetul Dolj, România", "sat Pietroaia, comuna Sopot, judetul Dolj, Romania")),
						createLoc("Sârsca", "sat", createAdresaCompleta("sat Sârsca, comuna Sopot, judetul Dolj, România", "sat Sarsca, comuna Sopot, judetul Dolj, Romania")),
		]),
	createComuna("Șimnicu de Sus", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Șimnicu de Sus", "sat", createAdresaCompleta("sat Șimnicu de Sus, comuna Șimnicu de Sus, judetul Dolj, România", "sat Simnicu de Sus, comuna Simnicu de Sus, judetul Dolj, Romania")),
						createLoc("Albești", "sat", createAdresaCompleta("sat Albești, comuna Șimnicu de Sus, judetul Dolj, România", "sat Albesti, comuna Simnicu de Sus, judetul Dolj, Romania")),
						createLoc("Cornetu", "sat", createAdresaCompleta("sat Cornetu, comuna Șimnicu de Sus, judetul Dolj, România", "sat Cornetu, comuna Simnicu de Sus, judetul Dolj, Romania")),
						createLoc("Deleni", "sat", createAdresaCompleta("sat Deleni, comuna Șimnicu de Sus, judetul Dolj, România", "sat Deleni, comuna Simnicu de Sus, judetul Dolj, Romania")),
						createLoc("Dudovicești", "sat", createAdresaCompleta("sat Dudovicești, comuna Șimnicu de Sus, judetul Dolj, România", "sat Dudovicesti, comuna Simnicu de Sus, judetul Dolj, Romania")),
						createLoc("Duțulești", "sat", createAdresaCompleta("sat Duțulești, comuna Șimnicu de Sus, judetul Dolj, România", "sat Dutulesti, comuna Simnicu de Sus, judetul Dolj, Romania")),
						createLoc("Florești", "sat", createAdresaCompleta("sat Florești, comuna Șimnicu de Sus, judetul Dolj, România", "sat Floresti, comuna Simnicu de Sus, judetul Dolj, Romania")),
						createLoc("Izvor", "sat", createAdresaCompleta("sat Izvor, comuna Șimnicu de Sus, judetul Dolj, România", "sat Izvor, comuna Simnicu de Sus, judetul Dolj, Romania")),
						createLoc("Jieni", "sat", createAdresaCompleta("sat Jieni, comuna Șimnicu de Sus, judetul Dolj, România", "sat Jieni, comuna Simnicu de Sus, judetul Dolj, Romania")),
						createLoc("Leșile", "sat", createAdresaCompleta("sat Leșile, comuna Șimnicu de Sus, judetul Dolj, România", "sat Lesile, comuna Simnicu de Sus, judetul Dolj, Romania")),
						createLoc("Milești", "sat", createAdresaCompleta("sat Milești, comuna Șimnicu de Sus, judetul Dolj, România", "sat Milesti, comuna Simnicu de Sus, judetul Dolj, Romania")),
						createLoc("Românești", "sat", createAdresaCompleta("sat Românești, comuna Șimnicu de Sus, judetul Dolj, România", "sat Romanesti, comuna Simnicu de Sus, judetul Dolj, Romania")),
		]),
	createComuna("Tălpaș", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Tălpaș", "sat", createAdresaCompleta("sat Tălpaș, comuna Tălpaș, judetul Dolj, România", "sat Talpas, comuna Talpas, judetul Dolj, Romania")),
						createLoc("Moflești", "sat", createAdresaCompleta("sat Moflești, comuna Tălpaș, judetul Dolj, România", "sat Moflesti, comuna Talpas, judetul Dolj, Romania")),
						createLoc("Nistoi", "sat", createAdresaCompleta("sat Nistoi, comuna Tălpaș, judetul Dolj, România", "sat Nistoi, comuna Talpas, judetul Dolj, Romania")),
						createLoc("Puținei", "sat", createAdresaCompleta("sat Puținei, comuna Tălpaș, judetul Dolj, România", "sat Putinei, comuna Talpas, judetul Dolj, Romania")),
						createLoc("Soceni", "sat", createAdresaCompleta("sat Soceni, comuna Tălpaș, judetul Dolj, România", "sat Soceni, comuna Talpas, judetul Dolj, Romania")),
		]),
	createComuna("Teasc", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Teasc", "sat", createAdresaCompleta("sat Teasc, comuna Teasc, judetul Dolj, România", "sat Teasc, comuna Teasc, judetul Dolj, Romania")),
						createLoc("Secui", "sat", createAdresaCompleta("sat Secui, comuna Teasc, judetul Dolj, România", "sat Secui, comuna Teasc, judetul Dolj, Romania")),
		]),
	createComuna("Terpezița", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Terpezița", "sat", createAdresaCompleta("sat Terpezița, comuna Terpezița, judetul Dolj, România", "sat Terpezita, comuna Terpezita, judetul Dolj, Romania")),
						createLoc("Căruia", "sat", createAdresaCompleta("sat Căruia, comuna Terpezița, judetul Dolj, România", "sat Caruia, comuna Terpezita, judetul Dolj, Romania")),
						createLoc("Căciulatu", "sat", createAdresaCompleta("sat Căciulatu, comuna Terpezița, judetul Dolj, România", "sat Caciulatu, comuna Terpezita, judetul Dolj, Romania")),
						createLoc("Floran", "sat", createAdresaCompleta("sat Floran, comuna Terpezița, judetul Dolj, România", "sat Floran, comuna Terpezita, judetul Dolj, Romania")),
						createLoc("Lazu", "sat", createAdresaCompleta("sat Lazu, comuna Terpezița, judetul Dolj, România", "sat Lazu, comuna Terpezita, judetul Dolj, Romania")),
		]),
	createComuna("Teslui", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Teslui", "sat", createAdresaCompleta("sat Teslui, comuna Teslui, judetul Dolj, România", "sat Teslui, comuna Teslui, judetul Dolj, Romania")),
						createLoc("Coșereni", "sat", createAdresaCompleta("sat Coșereni, comuna Teslui, judetul Dolj, România", "sat Cosereni, comuna Teslui, judetul Dolj, Romania")),
						createLoc("Fântânele", "sat", createAdresaCompleta("sat Fântânele, comuna Teslui, judetul Dolj, România", "sat Fantanele, comuna Teslui, judetul Dolj, Romania")),
						createLoc("Preajba de Jos", "sat", createAdresaCompleta("sat Preajba de Jos, comuna Teslui, judetul Dolj, România", "sat Preajba de Jos, comuna Teslui, judetul Dolj, Romania")),
						createLoc("Preajba de Pădure", "sat", createAdresaCompleta("sat Preajba de Pădure, comuna Teslui, judetul Dolj, România", "sat Preajba de Padure, comuna Teslui, judetul Dolj, Romania")),
						createLoc("Țărțăl", "sat", createAdresaCompleta("sat Țărțăl, comuna Teslui, judetul Dolj, România", "sat Tartal, comuna Teslui, judetul Dolj, Romania")),
						createLoc("Urieni", "sat", createAdresaCompleta("sat Urieni, comuna Teslui, judetul Dolj, România", "sat Urieni, comuna Teslui, judetul Dolj, Romania")),
						createLoc("Viișoara-Moșneni", "sat", createAdresaCompleta("sat Viișoara-Moșneni, comuna Teslui, judetul Dolj, România", "sat Viisoara-Mosneni, comuna Teslui, judetul Dolj, Romania")),
		]),
	createComuna("Țuglui", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Țuglui", "sat", createAdresaCompleta("sat Țuglui, comuna Țuglui, judetul Dolj, România", "sat Tuglui, comuna Tuglui, judetul Dolj, Romania")),
						createLoc("Jiul", "sat", createAdresaCompleta("sat Jiul, comuna Țuglui, judetul Dolj, România", "sat Jiul, comuna Tuglui, judetul Dolj, Romania")),
		]),
	createComuna("Unirea", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Unirea", "sat", createAdresaCompleta("sat Unirea, comuna Unirea, judetul Dolj, România", "sat Unirea, comuna Unirea, judetul Dolj, Romania")),
		]),
	createComuna("Urzicuța", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Urzicuța", "sat", createAdresaCompleta("sat Urzicuța, comuna Urzicuța, judetul Dolj, România", "sat Urzicuta, comuna Urzicuta, judetul Dolj, Romania")),
						createLoc("Urzica Mare", "sat", createAdresaCompleta("sat Urzica Mare, comuna Urzicuța, judetul Dolj, România", "sat Urzica Mare, comuna Urzicuta, judetul Dolj, Romania")),
		]),
	createComuna("Valea Stanciului", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Valea Stanciului", "sat", createAdresaCompleta("sat Valea Stanciului, comuna Valea Stanciului, judetul Dolj, România", "sat Valea Stanciului, comuna Valea Stanciului, judetul Dolj, Romania")),
						createLoc("Horezu-Poenari", "sat", createAdresaCompleta("sat Horezu-Poenari, comuna Valea Stanciului, judetul Dolj, România", "sat Horezu-Poenari, comuna Valea Stanciului, judetul Dolj, Romania")),
		]),
	createComuna("Vela", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Vela", "sat", createAdresaCompleta("sat Vela, comuna Vela, judetul Dolj, România", "sat Vela, comuna Vela, judetul Dolj, Romania")),
						createLoc("Bucovicior", "sat", createAdresaCompleta("sat Bucovicior, comuna Vela, judetul Dolj, România", "sat Bucovicior, comuna Vela, judetul Dolj, Romania")),
						createLoc("Cetățuia", "sat", createAdresaCompleta("sat Cetățuia, comuna Vela, judetul Dolj, România", "sat Cetatuia, comuna Vela, judetul Dolj, Romania")),
						createLoc("Desnățui", "sat", createAdresaCompleta("sat Desnățui, comuna Vela, judetul Dolj, România", "sat Desnatui, comuna Vela, judetul Dolj, Romania")),
						createLoc("Gubaucea", "sat", createAdresaCompleta("sat Gubaucea, comuna Vela, judetul Dolj, România", "sat Gubaucea, comuna Vela, judetul Dolj, Romania")),
						createLoc("Segleț", "sat", createAdresaCompleta("sat Segleț, comuna Vela, judetul Dolj, România", "sat Seglet, comuna Vela, judetul Dolj, Romania")),
						createLoc("Suharu", "sat", createAdresaCompleta("sat Suharu, comuna Vela, judetul Dolj, România", "sat Suharu, comuna Vela, judetul Dolj, Romania")),
						createLoc("Știubei", "sat", createAdresaCompleta("sat Știubei, comuna Vela, judetul Dolj, România", "sat Stiubei, comuna Vela, judetul Dolj, Romania")),
		]),
	createComuna("Verbița", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Verbița", "sat", createAdresaCompleta("sat Verbița, comuna Verbița, judetul Dolj, România", "sat Verbita, comuna Verbita, judetul Dolj, Romania")),
						createLoc("Verbicioara", "sat", createAdresaCompleta("sat Verbicioara, comuna Verbița, judetul Dolj, România", "sat Verbicioara, comuna Verbita, judetul Dolj, Romania")),
		]),
	createComuna("Vârtop", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Vârtop", "sat", createAdresaCompleta("sat Vârtop, comuna Vârtop, judetul Dolj, România", "sat Vartop, comuna Vartop, judetul Dolj, Romania")),
		]),
	createComuna("Vârvoru de Jos", [
						createAdresaCompleta("comuna Afumați, judetul DOLJ, România", "comuna Afumati, judetul DOLJ, Romania"),
						createLoc("Vârvoru de Jos", "sat", createAdresaCompleta("sat Vârvoru de Jos, comuna Vârvoru de Jos, judetul Dolj, România", "sat Varvoru de Jos, comuna Varvoru de Jos, judetul Dolj, Romania")),
						createLoc("Bujor", "sat", createAdresaCompleta("sat Bujor, comuna Vârvoru de Jos, judetul Dolj, România", "sat Bujor, comuna Varvoru de Jos, judetul Dolj, Romania")),
						createLoc("Ciutura", "sat", createAdresaCompleta("sat Ciutura, comuna Vârvoru de Jos, judetul Dolj, România", "sat Ciutura, comuna Varvoru de Jos, judetul Dolj, Romania")),
						createLoc("Criva", "sat", createAdresaCompleta("sat Criva, comuna Vârvoru de Jos, judetul Dolj, România", "sat Criva, comuna Varvoru de Jos, judetul Dolj, Romania")),
						createLoc("Dobromira", "sat", createAdresaCompleta("sat Dobromira, comuna Vârvoru de Jos, judetul Dolj, România", "sat Dobromira, comuna Varvoru de Jos, judetul Dolj, Romania")),
						createLoc("Drăgoaia", "sat", createAdresaCompleta("sat Drăgoaia, comuna Vârvoru de Jos, judetul Dolj, România", "sat Dragoaia, comuna Varvoru de Jos, judetul Dolj, Romania")),
						createLoc("Gabru", "sat", createAdresaCompleta("sat Gabru, comuna Vârvoru de Jos, judetul Dolj, România", "sat Gabru, comuna Varvoru de Jos, judetul Dolj, Romania")),
						createLoc("Vârvor", "sat", createAdresaCompleta("sat Vârvor, comuna Vârvoru de Jos, judetul Dolj, România", "sat Varvor, comuna Varvoru de Jos, judetul Dolj, Romania")),
		]),
];
?>