<?php
$comune =[
    createComuna("Agăș", [
        createLoc("Agăș", "sat", createAdresaCompleta("sat Agăș, comuna Agăș, judetul BACĂU, România")),
        createLoc("Beleghet", "sat", createAdresaCompleta("sat Beleghet, comuna Agăș, judetul BACĂU, România")),
        createLoc("Coșnea", "sat", createAdresaCompleta("sat Coșnea, comuna Agăș, judetul BACĂU, România")),
        createLoc("Cotumba", "sat", createAdresaCompleta("sat Cotumba, comuna Agăș, judetul BACĂU, România")),
        createLoc("Diaconești", "sat", createAdresaCompleta("sat Diaconești, comuna Agăș, judetul BACĂU, România")),
        createLoc("Goioasa", "sat", createAdresaCompleta("sat Goioasa, comuna Agăș, judetul BACĂU, România")),
        createLoc("Preluci", "sat", createAdresaCompleta("sat Preluci, comuna Agăș, judetul BACĂU, România")),
        createLoc("Sulța", "sat", createAdresaCompleta("sat Sulța, comuna Agăș, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Agăș, judetul BACĂU, România")),
    createComuna("Ardeoani", [
        createLoc("Ardeoani", "sat", createAdresaCompleta("sat Ardeoani, comuna Ardeoani, judetul BACĂU, România")),
        createLoc("Leontinești", "sat", createAdresaCompleta("sat Leontinești, comuna Ardeoani, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Ardeoani, judetul BACĂU, România")),
    createComuna("Asău", [
        createLoc("Asău", "sat", createAdresaCompleta("sat Asău, comuna Asău, judetul BACĂU, România")),
        createLoc("Apa Asău", "sat", createAdresaCompleta("sat Apa Asău, comuna Asău, judetul BACĂU, România")),
        createLoc("Ciobănuș", "sat", createAdresaCompleta("sat Ciobănuș, comuna Asău, judetul BACĂU, România")),
        createLoc("Lunca Asău", "sat", createAdresaCompleta("sat Lunca Asău, comuna Asău, judetul BACĂU, România")),
        createLoc("Păltiniș", "sat", createAdresaCompleta("sat Păltiniș, comuna Asău, judetul BACĂU, România")),
        createLoc("Straja", "sat", createAdresaCompleta("sat Straja, comuna Asău, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Asău, judetul BACĂU, România")),
    createComuna("Balcani", [
        createLoc("Balcani", "sat", createAdresaCompleta("sat Balcani, comuna Balcani, judetul BACĂU, România")),
        createLoc("Frumoasa", "sat", createAdresaCompleta("sat Frumoasa, comuna Balcani, judetul BACĂU, România")),
        createLoc("Ludași", "sat", createAdresaCompleta("sat Ludași, comuna Balcani, judetul BACĂU, România")),
        createLoc("Schitu Frumoasa", "sat", createAdresaCompleta("sat Schitu Frumoasa, comuna Balcani, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Balcani, judetul BACĂU, România")),
    createComuna("Berești-Bistrița", [
        createLoc("Berești-Bistrița", "sat", createAdresaCompleta("sat Berești-Bistrița, comuna Berești-Bistrița, judetul BACĂU, România")),
        createLoc("Brad", "sat", createAdresaCompleta("sat Brad, comuna Berești-Bistrița, judetul BACĂU, România")),
        createLoc("Climești", "sat", createAdresaCompleta("sat Climești, comuna Berești-Bistrița, judetul BACĂU, România")),
        createLoc("Pădureni", "sat", createAdresaCompleta("sat Pădureni, comuna Berești-Bistrița, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Berești-Bistrița, judetul BACĂU, România")),
    createComuna("Berești-Tazlău", [
        createLoc("Berești-Tazlău", "sat", createAdresaCompleta("sat Berești-Tazlău, comuna Berești-Tazlău, judetul BACĂU, România")),
        createLoc("Boșoteni", "sat", createAdresaCompleta("sat Boșoteni, comuna Berești-Tazlău, judetul BACĂU, România")),
        createLoc("Enăchești", "sat", createAdresaCompleta("sat Enăchești, comuna Berești-Tazlău, judetul BACĂU, România")),
        createLoc("Prisaca", "sat", createAdresaCompleta("sat Prisaca, comuna Berești-Tazlău, judetul BACĂU, România")),
        createLoc("Românești", "sat", createAdresaCompleta("sat Românești, comuna Berești-Tazlău, judetul BACĂU, România")),
        createLoc("Tescani", "sat", createAdresaCompleta("sat Tescani, comuna Berești-Tazlău, judetul BACĂU, România")),
        createLoc("Turluianu", "sat", createAdresaCompleta("sat Turluianu, comuna Berești-Tazlău, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Berești-Tazlău, judetul BACĂU, România")),
    createComuna("Berzunți", [
        createLoc("Berzunți", "sat", createAdresaCompleta("sat Berzunți, comuna Berzunți, judetul BACĂU, România")),
        createLoc("Buda", "sat", createAdresaCompleta("sat Buda, comuna Berzunți, judetul BACĂU, România")),
        createLoc("Dragomir", "sat", createAdresaCompleta("sat Dragomir, comuna Berzunți, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Berzunți, judetul BACĂU, România")),
    createComuna("Bârsănești", [
        createLoc("Bârsănești", "sat", createAdresaCompleta("sat Bârsănești, comuna Bârsănești, judetul BACĂU, România")),
        createLoc("Albele", "sat", createAdresaCompleta("sat Albele, comuna Bârsănești, judetul BACĂU, România")),
        createLoc("Brătești", "sat", createAdresaCompleta("sat Brătești, comuna Bârsănești, judetul BACĂU, România")),
        createLoc("Caraclău", "sat", createAdresaCompleta("sat Caraclău, comuna Bârsănești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Bârsănești, judetul BACĂU, România")),
    createComuna("Blăgești", [
        createLoc("Blăgești", "sat", createAdresaCompleta("sat Blăgești, comuna Blăgești, judetul BACĂU, România")),
        createLoc("Buda", "sat", createAdresaCompleta("sat Buda, comuna Blăgești, judetul BACĂU, România")),
        createLoc("Poiana Negustorului", "sat", createAdresaCompleta("sat Poiana Negustorului, comuna Blăgești, judetul BACĂU, România")),
        createLoc("Țârdenii Mari", "sat", createAdresaCompleta("sat Țârdenii Mari, comuna Blăgești, judetul BACĂU, România")),
        createLoc("Valea lui Ion", "sat", createAdresaCompleta("sat Valea lui Ion, comuna Blăgești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Blăgești, judetul BACĂU, România")),
    createComuna("Bogdănești", [
        createLoc("Bogdănești", "sat", createAdresaCompleta("sat Bogdănești, comuna Bogdănești, judetul BACĂU, România")),
        createLoc("Filipești", "sat", createAdresaCompleta("sat Filipești, comuna Bogdănești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Bogdănești, judetul BACĂU, România")),
	    createComuna("Brusturoasa", [
        createLoc("Brusturoasa", "sat", createAdresaCompleta("sat Brusturoasa, comuna Brusturoasa, judetul BACĂU, România")),
        createLoc("Buruieniș", "sat", createAdresaCompleta("sat Buruieniș, comuna Brusturoasa, judetul BACĂU, România")),
        createLoc("Buruienișu de Sus", "sat", createAdresaCompleta("sat Buruienișu de Sus, comuna Brusturoasa, judetul BACĂU, România")),
        createLoc("Camenca", "sat", createAdresaCompleta("sat Camenca, comuna Brusturoasa, judetul BACĂU, România")),
        createLoc("Cuchiniș", "sat", createAdresaCompleta("sat Cuchiniș, comuna Brusturoasa, judetul BACĂU, România")),
        createLoc("Hângănești", "sat", createAdresaCompleta("sat Hângănești, comuna Brusturoasa, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Brusturoasa, judetul BACĂU, România")),
    createComuna("Buciumi", [
        createLoc("Buciumi", "sat", createAdresaCompleta("sat Buciumi, comuna Buciumi, judetul BACĂU, România")),
        createLoc("Răcăuți", "sat", createAdresaCompleta("sat Răcăuți, comuna Buciumi, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Buciumi, judetul BACĂU, România")),
    createComuna("Buhoci", [
        createLoc("Buhoci", "sat", createAdresaCompleta("sat Buhoci, comuna Buhoci, judetul BACĂU, România")),
        createLoc("Bijghir", "sat", createAdresaCompleta("sat Bijghir, comuna Buhoci, judetul BACĂU, România")),
        createLoc("Buhocel", "sat", createAdresaCompleta("sat Buhocel, comuna Buhoci, judetul BACĂU, România")),
        createLoc("Coteni", "sat", createAdresaCompleta("sat Coteni, comuna Buhoci, judetul BACĂU, România")),
        createLoc("Dospinești", "sat", createAdresaCompleta("sat Dospinești, comuna Buhoci, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Buhoci, judetul BACĂU, România")),
    createComuna("Cașin", [
        createLoc("Cașin", "sat", createAdresaCompleta("sat Cașin, comuna Cașin, judetul BACĂU, România")),
        createLoc("Curița", "sat", createAdresaCompleta("sat Curița, comuna Cașin, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Cașin, judetul BACĂU, România")),
    createComuna("Căiuți", [
        createLoc("Căiuți", "sat", createAdresaCompleta("sat Căiuți, comuna Căiuți, judetul BACĂU, România")),
        createLoc("Blidari", "sat", createAdresaCompleta("sat Blidari, comuna Căiuți, judetul BACĂU, România")),
        createLoc("Boiștea", "sat", createAdresaCompleta("sat Boiștea, comuna Căiuți, judetul BACĂU, România")),
        createLoc("Florești", "sat", createAdresaCompleta("sat Florești, comuna Căiuți, judetul BACĂU, România")),
        createLoc("Heltiu", "sat", createAdresaCompleta("sat Heltiu, comuna Căiuți, judetul BACĂU, România")),
        createLoc("Mărcești", "sat", createAdresaCompleta("sat Mărcești, comuna Căiuți, judetul BACĂU, România")),
        createLoc("Popeni", "sat", createAdresaCompleta("sat Popeni, comuna Căiuți, judetul BACĂU, România")),
        createLoc("Pralea", "sat", createAdresaCompleta("sat Pralea, comuna Căiuți, judetul BACĂU, România")),
        createLoc("Vrânceni", "sat", createAdresaCompleta("sat Vrânceni, comuna Căiuți, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Căiuți, judetul BACĂU, România")),
    createComuna("Cleja", [
        createLoc("Cleja", "sat", createAdresaCompleta("sat Cleja, comuna Cleja, judetul BACĂU, România")),
        createLoc("Somușca", "sat", createAdresaCompleta("sat Somușca, comuna Cleja, judetul BACĂU, România")),
        createLoc("Valea Mică", "sat", createAdresaCompleta("sat Valea Mică, comuna Cleja, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Cleja, judetul BACĂU, România")),
    createComuna("Colonești", [
        createLoc("Colonești", "sat", createAdresaCompleta("sat Colonești, comuna Colonești, judetul BACĂU, România")),
        createLoc("Călini", "sat", createAdresaCompleta("sat Călini, comuna Colonești, judetul BACĂU, România")),
        createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Colonești, judetul BACĂU, România")),
        createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Colonești, judetul BACĂU, România")),
        createLoc("Spria", "sat", createAdresaCompleta("sat Spria, comuna Colonești, judetul BACĂU, România")),
        createLoc("Valea Mare", "sat", createAdresaCompleta("sat Valea Mare, comuna Colonești, judetul BACĂU, România")),
        createLoc("Zăpodia", "sat", createAdresaCompleta("sat Zăpodia, comuna Colonești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Colonești, judetul BACĂU, România")),
    createComuna("Corbasca", [
        createLoc("Corbasca", "sat", createAdresaCompleta("sat Corbasca, comuna Corbasca, judetul BACĂU, România")),
        createLoc("Băcioiu", "sat", createAdresaCompleta("sat Băcioiu, comuna Corbasca, judetul BACĂU, România")),
        createLoc("Marvila", "sat", createAdresaCompleta("sat Marvila, comuna Corbasca, judetul BACĂU, România")),
        createLoc("Pogleț", "sat", createAdresaCompleta("sat Pogleț, comuna Corbasca, judetul BACĂU, România")),
        createLoc("Rogoaza", "sat", createAdresaCompleta("sat Rogoaza, comuna Corbasca, judetul BACĂU, România")),
        createLoc("Scărișoara", "sat", createAdresaCompleta("sat Scărișoara, comuna Corbasca, judetul BACĂU, România")),
        createLoc("Vâlcele", "sat", createAdresaCompleta("sat Vâlcele, comuna Corbasca, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Corbasca, judetul BACĂU, România")),
    createComuna("Coțofănești", [
        createLoc("Coțofănești", "sat", createAdresaCompleta("sat Coțofănești, comuna Coțofănești, judetul BACĂU, România")),
        createLoc("Bâlca", "sat", createAdresaCompleta("sat Bâlca, comuna Coțofănești, judetul BACĂU, România")),
        createLoc("Boiștea de Jos", "sat", createAdresaCompleta("sat Boiștea de Jos, comuna Coțofănești, judetul BACĂU, România")),
        createLoc("Borșani", "sat", createAdresaCompleta("sat Borșani, comuna Coțofănești, judetul BACĂU, România")),
        createLoc("Tămășoaia", "sat", createAdresaCompleta("sat Tămășoaia, comuna Coțofănești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Coțofănești, judetul BACĂU, România")),
    createComuna("Dămienești", [
        createLoc("Dămienești", "sat", createAdresaCompleta("sat Dămienești, comuna Dămienești, judetul BACĂU, România")),
        createLoc("Călugăreni", "sat", createAdresaCompleta("sat Călugăreni, comuna Dămienești, judetul BACĂU, România")),
        createLoc("Drăgești", "sat", createAdresaCompleta("sat Drăgești, comuna Dămienești, judetul BACĂU, România")),
        createLoc("Pădureni", "sat", createAdresaCompleta("sat Pădureni, comuna Dămienești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Dămienești, judetul BACĂU, România")),
    createComuna("Dealu Morii", [
        createLoc("Dealu Morii", "sat", createAdresaCompleta("sat Dealu Morii, comuna Dealu Morii, judetul BACĂU, România")),
        createLoc("Banca", "sat", createAdresaCompleta("sat Banca, comuna Dealu Morii, judetul BACĂU, România")),
        createLoc("Bălănești", "sat", createAdresaCompleta("sat Bălănești, comuna Dealu Morii, judetul BACĂU, România")),
        createLoc("Blaga", "sat", createAdresaCompleta("sat Blaga, comuna Dealu Morii, judetul BACĂU, România")),
        createLoc("Boboș", "sat", createAdresaCompleta("sat Boboș, comuna Dealu Morii, judetul BACĂU, România")),
        createLoc("Bodeasa", "sat", createAdresaCompleta("sat Bodeasa, comuna Dealu Morii, judetul BACĂU, România")),
        createLoc("Bostănești", "sat", createAdresaCompleta("sat Bostănești, comuna Dealu Morii, judetul BACĂU, România")),
        createLoc("Calapodești", "sat", createAdresaCompleta("sat Calapodești, comuna Dealu Morii, judetul BACĂU, România")),
        createLoc("Căuia", "sat", createAdresaCompleta("sat Căuia, comuna Dealu Morii, judetul BACĂU, România")),
        createLoc("Dorofei", "sat", createAdresaCompleta("sat Dorofei, comuna Dealu Morii, judetul BACĂU, România")),
        createLoc("Ghionoaia", "sat", createAdresaCompleta("sat Ghionoaia, comuna Dealu Morii, judetul BACĂU, România")),
        createLoc("Grădești", "sat", createAdresaCompleta("sat Grădești, comuna Dealu Morii, judetul BACĂU, România")),
        createLoc("Negulești", "sat", createAdresaCompleta("sat Negulești, comuna Dealu Morii, judetul BACĂU, România")),
        createLoc("Tăvădărești", "sat", createAdresaCompleta("sat Tăvădărești, comuna Dealu Morii, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Dealu Morii, judetul BACĂU, România")),
    createComuna("Dofteana", [
        createLoc("Dofteana", "sat", createAdresaCompleta("sat Dofteana, comuna Dofteana, judetul BACĂU, România")),
        createLoc("Bogata", "sat", createAdresaCompleta("sat Bogata, comuna Dofteana, judetul BACĂU, România")),
        createLoc("Cucuieți", "sat", createAdresaCompleta("sat Cucuieți, comuna Dofteana, judetul BACĂU, România")),
        createLoc("Hăghiac", "sat", createAdresaCompleta("sat Hăghiac, comuna Dofteana, judetul BACĂU, România")),
        createLoc("Larga", "sat", createAdresaCompleta("sat Larga, comuna Dofteana, judetul BACĂU, România")),
        createLoc("Seaca", "sat", createAdresaCompleta("sat Seaca, comuna Dofteana, judetul BACĂU, România")),
        createLoc("Ștefan Vodă", "sat", createAdresaCompleta("sat Ștefan Vodă, comuna Dofteana, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Dofteana, judetul BACĂU, România")),
    createComuna("Faraoani", [
        createLoc("Faraoani", "sat", createAdresaCompleta("sat Faraoani, comuna Faraoani, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Faraoani, judetul BACĂU, România")),
    createComuna("Filipeni", [
        createLoc("Filipeni", "sat", createAdresaCompleta("sat Filipeni, comuna Filipeni, judetul BACĂU, România")),
        createLoc("Bălaia", "sat", createAdresaCompleta("sat Bălaia, comuna Filipeni, judetul BACĂU, România")),
        createLoc("Brad", "sat", createAdresaCompleta("sat Brad, comuna Filipeni, judetul BACĂU, România")),
        createLoc("Fruntești", "sat", createAdresaCompleta("sat Fruntești, comuna Filipeni, judetul BACĂU, România")),
        createLoc("Mărăști", "sat", createAdresaCompleta("sat Mărăști, comuna Filipeni, judetul BACĂU, România")),
        createLoc("Pădureni", "sat", createAdresaCompleta("sat Pădureni, comuna Filipeni, judetul BACĂU, România")),
        createLoc("Slobozia", "sat", createAdresaCompleta("sat Slobozia, comuna Filipeni, judetul BACĂU, România")),
        createLoc("Valea Boțului", "sat", createAdresaCompleta("sat Valea Boțului, comuna Filipeni, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Filipeni, judetul BACĂU, România")),
    createComuna("Filipești", [
        createLoc("Filipești", "sat", createAdresaCompleta("sat Filipești, comuna Filipești, judetul BACĂU, România")),
        createLoc("Boanța", "sat", createAdresaCompleta("sat Boanța, comuna Filipești, judetul BACĂU, România")),
        createLoc("Cârligi", "sat", createAdresaCompleta("sat Cârligi, comuna Filipești, judetul BACĂU, România")),
        createLoc("Cornești", "sat", createAdresaCompleta("sat Cornești, comuna Filipești, judetul BACĂU, România")),
        createLoc("Cotu Grosului", "sat", createAdresaCompleta("sat Cotu Grosului, comuna Filipești, judetul BACĂU, România")),
        createLoc("Galbeni", "sat", createAdresaCompleta("sat Galbeni, comuna Filipești, judetul BACĂU, România")),
        createLoc("Hârlești", "sat", createAdresaCompleta("sat Hârlești, comuna Filipești, judetul BACĂU, România")),
        createLoc("Onișcani", "sat", createAdresaCompleta("sat Onișcani, comuna Filipești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Filipești, judetul BACĂU, România")),
    createComuna("Găiceana", [
        createLoc("Găiceana", "sat", createAdresaCompleta("sat Găiceana, comuna Găiceana, judetul BACĂU, România")),
        createLoc("Arini", "sat", createAdresaCompleta("sat Arini, comuna Găiceana, judetul BACĂU, România")),
        createLoc("Huțu", "sat", createAdresaCompleta("sat Huțu, comuna Găiceana, judetul BACĂU, România")),
        createLoc("Popești", "sat", createAdresaCompleta("sat Popești, comuna Găiceana, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Găiceana, judetul BACĂU, România")),
    createComuna("Ghimeș-Făget", [
        createLoc("Făget", "sat", createAdresaCompleta("sat Făget, comuna Ghimeș-Făget, judetul BACĂU, România")),
        createLoc("Bolovăniș", "sat", createAdresaCompleta("sat Bolovăniș, comuna Ghimeș-Făget, judetul BACĂU, România")),
        createLoc("Făgetu de Sus", "sat", createAdresaCompleta("sat Făgetu de Sus, comuna Ghimeș-Făget, judetul BACĂU, România")),
        createLoc("Ghimeș", "sat", createAdresaCompleta("sat Ghimeș, comuna Ghimeș-Făget, judetul BACĂU, România")),
        createLoc("Răchitiș", "sat", createAdresaCompleta("sat Răchitiș, comuna Ghimeș-Făget, judetul BACĂU, România")),
        createLoc("Tărhăuși", "sat", createAdresaCompleta("sat Tărhăuși, comuna Ghimeș-Făget, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Ghimeș-Făget, judetul BACĂU, România")),
    createComuna("Gioseni", [
        createLoc("Gioseni", "sat", createAdresaCompleta("sat Gioseni, comuna Gioseni, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Gioseni, judetul BACĂU, România")),
    createComuna("Gârleni", [
        createLoc("Gârlenii de Sus", "sat", createAdresaCompleta("sat Gârlenii de Sus, comuna Gârleni, judetul BACĂU, România")),
        createLoc("Gârleni", "sat", createAdresaCompleta("sat Gârleni, comuna Gârleni, judetul BACĂU, România")),
        createLoc("Lespezi", "sat", createAdresaCompleta("sat Lespezi, comuna Gârleni, judetul BACĂU, România")),
        createLoc("Șurina", "sat", createAdresaCompleta("sat Șurina, comuna Gârleni, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Gârleni, judetul BACĂU, România")),
    createComuna("Glăvănești", [
        createLoc("Glăvănești", "sat", createAdresaCompleta("sat Glăvănești, comuna Glăvănești, judetul BACĂU, România")),
        createLoc("Frumușelu", "sat", createAdresaCompleta("sat Frumușelu, comuna Glăvănești, judetul BACĂU, România")),
        createLoc("Muncelu", "sat", createAdresaCompleta("sat Muncelu, comuna Glăvănești, judetul BACĂU, România")),
        createLoc("Putredeni", "sat", createAdresaCompleta("sat Putredeni, comuna Glăvănești, judetul BACĂU, România")),
        createLoc("Răzeșu", "sat", createAdresaCompleta("sat Răzeșu, comuna Glăvănești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Glăvănești, judetul BACĂU, România")),
    createComuna("Gura Văii", [
        createLoc("Gura Văii", "sat", createAdresaCompleta("sat Gura Văii, comuna Gura Văii, judetul BACĂU, România")),
        createLoc("Capăta", "sat", createAdresaCompleta("sat Capăta, comuna Gura Văii, judetul BACĂU, România")),
        createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, comuna Gura Văii, judetul BACĂU, România")),
        createLoc("Motocești", "sat", createAdresaCompleta("sat Motocești, comuna Gura Văii, judetul BACĂU, România")),
        createLoc("Păltinata", "sat", createAdresaCompleta("sat Păltinata, comuna Gura Văii, judetul BACĂU, România")),
        createLoc("Temelia", "sat", createAdresaCompleta("sat Temelia, comuna Gura Văii, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Gura Văii, judetul BACĂU, România")),
    createComuna("Helegiu", [
        createLoc("Helegiu", "sat", createAdresaCompleta("sat Helegiu, comuna Helegiu, judetul BACĂU, România")),
        createLoc("Brătila", "sat", createAdresaCompleta("sat Brătila, comuna Helegiu, judetul BACĂU, România")),
        createLoc("Deleni", "sat", createAdresaCompleta("sat Deleni, comuna Helegiu, judetul BACĂU, România")),
        createLoc("Drăgugești", "sat", createAdresaCompleta("sat Drăgugești, comuna Helegiu, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Helegiu, judetul BACĂU, România")),
    createComuna("Hemeiuș", [
        createLoc("Hemeiuș", "sat", createAdresaCompleta("sat Hemeiuș, comuna Hemeiuș, judetul BACĂU, România")),
        createLoc("Fântânele", "sat", createAdresaCompleta("sat Fântânele, comuna Hemeiuș, judetul BACĂU, România")),
        createLoc("Lilieci", "sat", createAdresaCompleta("sat Lilieci, comuna Hemeiuș, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Hemeiuș, judetul BACĂU, România")),
    createComuna("Horgești", [
        createLoc("Horgești", "sat", createAdresaCompleta("sat Horgești, comuna Horgești, judetul BACĂU, România")),
        createLoc("Bazga", "sat", createAdresaCompleta("sat Bazga, comuna Horgești, judetul BACĂU, România")),
        createLoc("Galeri", "sat", createAdresaCompleta("sat Galeri, comuna Horgești, judetul BACĂU, România")),
        createLoc("Mărăscu", "sat", createAdresaCompleta("sat Mărăscu, comuna Horgești, judetul BACĂU, România")),
        createLoc("Răcătău-Răzeși", "sat", createAdresaCompleta("sat Răcătău-Răzeși, comuna Horgești, judetul BACĂU, România")),
        createLoc("Răcătău de Jos", "sat", createAdresaCompleta("sat Răcătău de Jos, comuna Horgești, judetul BACĂU, România")),
        createLoc("Recea", "sat", createAdresaCompleta("sat Recea, comuna Horgești, judetul BACĂU, România")),
        createLoc("Sohodor", "sat", createAdresaCompleta("sat Sohodor, comuna Horgești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Horgești, judetul BACĂU, România")),
    createComuna("Huruiești", [
        createLoc("Huruiești", "sat", createAdresaCompleta("sat Huruiești, comuna Huruiești, judetul BACĂU, România")),
        createLoc("Căpotești", "sat", createAdresaCompleta("sat Căpotești, comuna Huruiești, judetul BACĂU, România")),
        createLoc("Florești", "sat", createAdresaCompleta("sat Florești, comuna Huruiești, judetul BACĂU, România")),
        createLoc("Fundoaia", "sat", createAdresaCompleta("sat Fundoaia, comuna Huruiești, judetul BACĂU, România")),
        createLoc("Ocheni", "sat", createAdresaCompleta("sat Ocheni, comuna Huruiești, judetul BACĂU, România")),
        createLoc("Perchiu", "sat", createAdresaCompleta("sat Perchiu, comuna Huruiești, judetul BACĂU, România")),
        createLoc("Prădaiș", "sat", createAdresaCompleta("sat Prădaiș, comuna Huruiești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Huruiești, judetul BACĂU, România")),
    createComuna("Itești", [
        createLoc("Itești", "sat", createAdresaCompleta("sat Itești, comuna Itești, judetul BACĂU, România")),
        createLoc("Ciumași", "sat", createAdresaCompleta("sat Ciumași, comuna Itești, judetul BACĂU, România")),
        createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, comuna Itești, judetul BACĂU, România")),
        createLoc("Făgețel", "sat", createAdresaCompleta("sat Făgețel, comuna Itești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Itești, judetul BACĂU, România")),
    createComuna("Izvoru Berheciului", [
        createLoc("Izvoru Berheciului", "sat", createAdresaCompleta("sat Izvoru Berheciului, comuna Izvoru Berheciului, judetul BACĂU, România")),
        createLoc("Antohești", "sat", createAdresaCompleta("sat Antohești, comuna Izvoru Berheciului, judetul BACĂU, România")),
        createLoc("Băimac", "sat", createAdresaCompleta("sat Băimac, comuna Izvoru Berheciului, judetul BACĂU, România")),
        createLoc("Făghieni", "sat", createAdresaCompleta("sat Făghieni, comuna Izvoru Berheciului, judetul BACĂU, România")),
        createLoc("Obârșia", "sat", createAdresaCompleta("sat Obârșia, comuna Izvoru Berheciului, judetul BACĂU, România")),
        createLoc("Oțelești", "sat", createAdresaCompleta("sat Oțelești, comuna Izvoru Berheciului, judetul BACĂU, România")),
        createLoc("Pădureni", "sat", createAdresaCompleta("sat Pădureni, comuna Izvoru Berheciului, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Izvoru Berheciului, judetul BACĂU, România")),
    createComuna("Letea Veche", [
        createLoc("Letea Veche", "sat", createAdresaCompleta("sat Letea Veche, comuna Letea Veche, judetul BACĂU, România")),
        createLoc("Holt", "sat", createAdresaCompleta("sat Holt, comuna Letea Veche, judetul BACĂU, România")),
        createLoc("Radomirești", "sat", createAdresaCompleta("sat Radomirești, comuna Letea Veche, judetul BACĂU, România")),
        createLoc("Ruși-Ciutea", "sat", createAdresaCompleta("sat Ruși-Ciutea, comuna Letea Veche, judetul BACĂU, România")),
        createLoc("Siretu", "sat", createAdresaCompleta("sat Siretu, comuna Letea Veche, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Letea Veche, judetul BACĂU, România")),
    createComuna("Lipova", [
        createLoc("Lipova", "sat", createAdresaCompleta("sat Lipova, comuna Lipova, judetul BACĂU, România")),
        createLoc("Mâlosu", "sat", createAdresaCompleta("sat Mâlosu, comuna Lipova, judetul BACĂU, România")),
        createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Lipova, judetul BACĂU, România")),
        createLoc("Valea Caselor", "sat", createAdresaCompleta("sat Valea Caselor, comuna Lipova, judetul BACĂU, România")),
        createLoc("Valea Hogei", "sat", createAdresaCompleta("sat Valea Hogei, comuna Lipova, judetul BACĂU, România")),
        createLoc("Valea Mărului", "sat", createAdresaCompleta("sat Valea Mărului, comuna Lipova, judetul BACĂU, România")),
        createLoc("Valea Moșneagului", "sat", createAdresaCompleta("sat Valea Moșneagului, comuna Lipova, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Lipova, judetul BACĂU, România")),
    createComuna("Livezi", [
        createLoc("Livezi", "sat", createAdresaCompleta("sat Livezi, comuna Livezi, judetul BACĂU, România")),
        createLoc("Bălăneasa", "sat", createAdresaCompleta("sat Bălăneasa, comuna Livezi, judetul BACĂU, România")),
        createLoc("Orășa", "sat", createAdresaCompleta("sat Orășa, comuna Livezi, judetul BACĂU, România")),
        createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Livezi, judetul BACĂU, România")),
        createLoc("Prăjoaia", "sat", createAdresaCompleta("sat Prăjoaia, comuna Livezi, judetul BACĂU, România")),
        createLoc("Scăriga", "sat", createAdresaCompleta("sat Scăriga, comuna Livezi, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Livezi, judetul BACĂU, România")),
    createComuna("Luizi-Călugăra", [
        createLoc("Luizi-Călugăra", "sat", createAdresaCompleta("sat Luizi-Călugăra, comuna Luizi-Călugăra, judetul BACĂU, România")),
        createLoc("Osebiți", "sat", createAdresaCompleta("sat Osebiți, comuna Luizi-Călugăra, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Luizi-Călugăra, judetul BACĂU, România")),
    createComuna("Măgirești", [
        createLoc("Măgirești", "sat", createAdresaCompleta("sat Măgirești, comuna Măgirești, judetul BACĂU, România")),
        createLoc("Prăjești", "sat", createAdresaCompleta("sat Prăjești, comuna Măgirești, judetul BACĂU, România")),
        createLoc("Stănești", "sat", createAdresaCompleta("sat Stănești, comuna Măgirești, judetul BACĂU, România")),
        createLoc("Șesuri", "sat", createAdresaCompleta("sat Șesuri, comuna Măgirești, judetul BACĂU, România")),
        createLoc("Valea Arinilor", "sat", createAdresaCompleta("sat Valea Arinilor, comuna Măgirești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Măgirești, judetul BACĂU, România")),
    createComuna("Măgura", [
        createLoc("Măgura", "sat", createAdresaCompleta("sat Măgura, comuna Măgura, judetul BACĂU, România")),
        createLoc("Crihan", "sat", createAdresaCompleta("sat Crihan, comuna Măgura, judetul BACĂU, România")),
        createLoc("Dealu Mare", "sat", createAdresaCompleta("sat Dealu Mare, comuna Măgura, judetul BACĂU, România")),
        createLoc("Sohodol", "sat", createAdresaCompleta("sat Sohodol, comuna Măgura, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Măgura, judetul BACĂU, România")),
    createComuna("Mănăstirea Cașin", [
        createLoc("Mănăstirea Cașin", "sat", createAdresaCompleta("sat Mănăstirea Cașin, comuna Mănăstirea Cașin, judetul BACĂU, România")),
        createLoc("Lupești", "sat", createAdresaCompleta("sat Lupești, comuna Mănăstirea Cașin, judetul BACĂU, România")),
        createLoc("Pârvulești", "sat", createAdresaCompleta("sat pârvulești, comuna Mănăstirea Cașin, judetul BACĂU, România")),
        createLoc("Scutaru", "sat", createAdresaCompleta("sat Scutaru, comuna Mănăstirea Cașin, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Mănăstirea Cașin, judetul BACĂU, România")),
    createComuna("Mărgineni", [
        createLoc("Mărgineni", "sat", createAdresaCompleta("sat Mărgineni, comuna Mărgineni, judetul BACĂU, România")),
        createLoc("Barați", "sat", createAdresaCompleta("sat Barați, comuna Mărgineni, judetul BACĂU, România")),
        createLoc("Luncani", "sat", createAdresaCompleta("sat Luncani, comuna Mărgineni, judetul BACĂU, România")),
        createLoc("Pădureni", "sat", createAdresaCompleta("sat Pădureni, comuna Mărgineni, judetul BACĂU, România")),
        createLoc("Podiș", "sat", createAdresaCompleta("sat Podiș, comuna Mărgineni, judetul BACĂU, România")),
        createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Mărgineni, judetul BACĂU, România")),
        createLoc("Trebeș", "sat", createAdresaCompleta("sat Trebeș, comuna Mărgineni, judetul BACĂU, România")),
        createLoc("Valea Budului", "sat", createAdresaCompleta("sat Valea Budului, comuna Mărgineni, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Mărgineni, judetul BACĂU, România")),
    createComuna("Motoșeni", [
        createLoc("Motoșeni", "sat", createAdresaCompleta("sat Motoșeni, comuna Motoșeni, judetul BACĂU, România")),
        createLoc("Bâclești", "sat", createAdresaCompleta("sat Bâclești, comuna Motoșeni, judetul BACĂU, România")),
        createLoc("Chetreni", "sat", createAdresaCompleta("sat Chetreni, comuna Motoșeni, judetul BACĂU, România")),
        createLoc("Chicerea", "sat", createAdresaCompleta("sat Chicerea, comuna Motoșeni, judetul BACĂU, România")),
        createLoc("Cociu", "sat", createAdresaCompleta("sat Cociu, comuna Motoșeni, judetul BACĂU, România")),
        createLoc("Cornățelu", "sat", createAdresaCompleta("sat Cornățelu, comuna Motoșeni, judetul BACĂU, România")),
        createLoc("Fântânele", "sat", createAdresaCompleta("sat Fântânele, comuna Motoșeni, judetul BACĂU, România")),
        createLoc("Fundătura", "sat", createAdresaCompleta("sat Fundătura, comuna Motoșeni, judetul BACĂU, România")),
        createLoc("Gura Crăiești", "sat", createAdresaCompleta("sat Gura Crăiești, comuna Motoșeni, judetul BACĂU, România")),
        createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Motoșeni, judetul BACĂU, România")),
        createLoc("Praja", "sat", createAdresaCompleta("sat Praja, comuna Motoșeni, judetul BACĂU, România")),
        createLoc("Rotăria", "sat", createAdresaCompleta("sat Rotăria, comuna Motoșeni, judetul BACĂU, România")),
        createLoc("Șendrești", "sat", createAdresaCompleta("sat Șendrești, comuna Motoșeni, judetul BACĂU, România")),
        createLoc("Țepoaia", "sat", createAdresaCompleta("sat Țepoaia, comuna Motoșeni, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Motoșeni, judetul BACĂU, România")),
    createComuna("Negri", [
        createLoc("Negri", "sat", createAdresaCompleta("sat Negri, comuna Negri, judetul BACĂU, România")),
        createLoc("Brad", "sat", createAdresaCompleta("sat Brad, comuna Negri, judetul BACĂU, România")),
        createLoc("Călinești", "sat", createAdresaCompleta("sat Călinești, comuna Negri, judetul BACĂU, România")),
        createLoc("Mâgla", "sat", createAdresaCompleta("sat Mâgla, comuna Negri, judetul BACĂU, România")),
        createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Negri, judetul BACĂU, România")),
        createLoc("Ursoaia", "sat", createAdresaCompleta("sat Ursoaia, comuna Negri, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Negri, judetul BACĂU, România")),
    createComuna("Nicolae Bălcescu", [
        createLoc("Nicolae Bălcescu", "sat", createAdresaCompleta("sat Nicolae Bălcescu, comuna Nicolae Bălcescu, judetul BACĂU, România")),
        createLoc("Buchila", "sat", createAdresaCompleta("sat Buchila, comuna Nicolae Bălcescu, judetul BACĂU, România")),
        createLoc("Galbeni", "sat", createAdresaCompleta("sat Galbeni, comuna Nicolae Bălcescu, judetul BACĂU, România")),
        createLoc("Lărguța", "sat", createAdresaCompleta("sat Lărguța, comuna Nicolae Bălcescu, judetul BACĂU, România")),
        createLoc("Valea Seacă", "sat", createAdresaCompleta("sat Valea Seacă, comuna Nicolae Bălcescu, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Nicolae Bălcescu, judetul BACĂU, România")),
    createComuna("Odobești", [
        createLoc("Odobești", "sat", createAdresaCompleta("sat Odobești, comuna Odobești, judetul BACĂU, România")),
        createLoc("Bălușa", "sat", createAdresaCompleta("sat Bălușa, comuna Odobești, judetul BACĂU, România")),
        createLoc("Ciuturești", "sat", createAdresaCompleta("sat Ciuturești, comuna Odobești, judetul BACĂU, România")),
        createLoc("Tisa-Silvestri", "sat", createAdresaCompleta("sat Tisa-Silvestri, comuna Odobești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Odobești, judetul BACĂU, România")),
    createComuna("Oituz", [
        createLoc("Oituz", "sat", createAdresaCompleta("sat Oituz, comuna Oituz, judetul BACĂU, România")),
        createLoc("Călcâi", "sat", createAdresaCompleta("sat Călcâi, comuna Oituz, judetul BACĂU, România")),
        createLoc("Ferestrău-Oituz", "sat", createAdresaCompleta("sat Ferestrău-Oituz, comuna Oituz, judetul BACĂU, România")),
        createLoc("Hârja", "sat", createAdresaCompleta("sat Hârja, comuna Oituz, judetul BACĂU, România")),
        createLoc("Marginea", "sat", createAdresaCompleta("sat Marginea, comuna Oituz, judetul BACĂU, România")),
        createLoc("Poiana Sărată", "sat", createAdresaCompleta("sat Poiana Sărată, comuna Oituz, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Oituz, judetul BACĂU, România")),
    createComuna("Oncești", [
        createLoc("Oncești", "sat", createAdresaCompleta("sat Oncești, comuna Oncești, judetul BACĂU, România")),
        createLoc("Bărboasa", "sat", createAdresaCompleta("sat Bărboasa, comuna Oncești, judetul BACĂU, România")),
        createLoc("Dealu Perjului", "sat", createAdresaCompleta("sat Dealu Perjului, comuna Oncești, judetul BACĂU, România")),
        createLoc("Onceștii Vechi", "sat", createAdresaCompleta("sat Onceștii Vechi, comuna Oncești, judetul BACĂU, România")),
        createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Oncești, judetul BACĂU, România")),
        createLoc("Tarnița", "sat", createAdresaCompleta("sat Tarnița, comuna Oncești, judetul BACĂU, România")),
        createLoc("Taula", "sat", createAdresaCompleta("sat Taula, comuna Oncești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Oncești, judetul BACĂU, România")),
    createComuna("Orbeni", [
        createLoc("Orbeni", "sat", createAdresaCompleta("sat Orbeni, comuna Orbeni, judetul BACĂU, România")),
        createLoc("Scurta", "sat", createAdresaCompleta("sat Scurta, comuna Orbeni, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Orbeni, judetul BACĂU, România")),
    createComuna("Palanca", [
        createLoc("Palanca", "sat", createAdresaCompleta("sat Palanca, comuna Palanca, judetul BACĂU, România")),
        createLoc("Cădărești", "sat", createAdresaCompleta("sat Cădărești, comuna Palanca, judetul BACĂU, România")),
        createLoc("Ciugheș", "sat", createAdresaCompleta("sat Ciugheș, comuna Palanca, judetul BACĂU, România")),
        createLoc("Pajiștea", "sat", createAdresaCompleta("sat Pajiștea, comuna Palanca, judetul BACĂU, România")),
        createLoc("Popoiu", "sat", createAdresaCompleta("sat Popoiu, comuna Palanca, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Palanca, judetul BACĂU, România")),
    createComuna("Parava", [
        createLoc("Parava", "sat", createAdresaCompleta("sat Parava, comuna Parava, judetul BACĂU, România")),
        createLoc("Drăgușani", "sat", createAdresaCompleta("sat Drăgușani, comuna Parava, judetul BACĂU, România")),
        createLoc("Rădoaia", "sat", createAdresaCompleta("sat Rădoaia, comuna Parava, judetul BACĂU, România")),
        createLoc("Teiuș", "sat", createAdresaCompleta("sat Teiuș, comuna Parava, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Parava, judetul BACĂU, România")),
    createComuna("Parincea", [
        createLoc("Parincea", "sat", createAdresaCompleta("sat Parincea, comuna Parincea, judetul BACĂU, România")),
        createLoc("Barna", "sat", createAdresaCompleta("sat Barna, comuna Parincea, judetul BACĂU, România")),
        createLoc("Mileștii de Jos", "sat", createAdresaCompleta("sat Mileștii de Jos, comuna Parincea, judetul BACĂU, România")),
        createLoc("Mileștii de Sus", "sat", createAdresaCompleta("sat Mileștii de Sus, comuna Parincea, judetul BACĂU, România")),
        createLoc("Nănești", "sat", createAdresaCompleta("sat Nănești, comuna Parincea, judetul BACĂU, România")),
        createLoc("Năstăseni", "sat", createAdresaCompleta("sat Năstăseni, comuna Parincea, judetul BACĂU, România")),
        createLoc("Poieni", "sat", createAdresaCompleta("sat Poieni, comuna Parincea, judetul BACĂU, România")),
        createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Parincea, judetul BACĂU, România")),
        createLoc("Văleni", "sat", createAdresaCompleta("sat Văleni, comuna Parincea, judetul BACĂU, România")),
        createLoc("Vladnic", "sat", createAdresaCompleta("sat Vladnic, comuna Parincea, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Parincea, judetul BACĂU, România")),
    createComuna("Pâncești", [
        createLoc("Pâncești", "sat", createAdresaCompleta("sat Pâncești, comuna Pâncești, judetul BACĂU, România")),
        createLoc("Chilia Benei", "sat", createAdresaCompleta("sat Chilia Benei, comuna Pâncești, judetul BACĂU, România")),
        createLoc("Dieneț", "sat", createAdresaCompleta("sat Dieneț, comuna Pâncești, judetul BACĂU, România")),
        createLoc("Fulgeriș", "sat", createAdresaCompleta("sat Fulgeriș, comuna Pâncești, judetul BACĂU, România")),
        createLoc("Fundu Văii", "sat", createAdresaCompleta("sat Fundu Văii, comuna Pâncești, judetul BACĂU, România")),
        createLoc("Motoc", "sat", createAdresaCompleta("sat Motoc, comuna Pâncești, judetul BACĂU, România")),
        createLoc("Petrești", "sat", createAdresaCompleta("sat Petrești, comuna Pâncești, judetul BACĂU, România")),
        createLoc("Soci", "sat", createAdresaCompleta("sat Soci, comuna Pâncești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Pâncești, judetul BACĂU, România")),
    createComuna("Pârgărești", [
        createLoc("Pârgărești", "sat", createAdresaCompleta("sat pârgărești, comuna pârgărești, judetul BACĂU, România")),
        createLoc("Bahna", "sat", createAdresaCompleta("sat Bahna, comuna pârgărești, judetul BACĂU, România")),
        createLoc("Nicorești", "sat", createAdresaCompleta("sat Nicorești, comuna pârgărești, judetul BACĂU, România")),
        createLoc("Pârâu Boghii", "sat", createAdresaCompleta("sat Pârâu Boghii, comuna pârgărești, judetul BACĂU, România")),
        createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna pârgărești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna pârgărești, judetul BACĂU, România")),
    createComuna("Pârjol", [
        createLoc("Pârjol", "sat", createAdresaCompleta("sat Pârjol, comuna Pârjol, judetul BACĂU, România")),
        createLoc("Băhnășeni", "sat", createAdresaCompleta("sat Băhnășeni, comuna Pârjol, judetul BACĂU, România")),
        createLoc("Bărnești", "sat", createAdresaCompleta("sat Bărnești, comuna Pârjol, judetul BACĂU, România")),
        createLoc("Băsăști", "sat", createAdresaCompleta("sat Băsăști, comuna Pârjol, judetul BACĂU, România")),
        createLoc("Câmpeni", "sat", createAdresaCompleta("sat Câmpeni, comuna Pârjol, judetul BACĂU, România")),
        createLoc("Hăineala", "sat", createAdresaCompleta("sat Hăineala, comuna Pârjol, judetul BACĂU, România")),
        createLoc("Hemieni", "sat", createAdresaCompleta("sat Hemieni, comuna Pârjol, judetul BACĂU, România")),
        createLoc("Pustiana", "sat", createAdresaCompleta("sat Pustiana, comuna Pârjol, judetul BACĂU, România")),
        createLoc("Tărâța", "sat", createAdresaCompleta("sat Tărâța, comuna Pârjol, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Pârjol, judetul BACĂU, România")),
    createComuna("Plopana", [
        createLoc("Plopana", "sat", createAdresaCompleta("sat Plopana, comuna Plopana, judetul BACĂU, România")),
        createLoc("Budești", "sat", createAdresaCompleta("sat Budești, comuna Plopana, judetul BACĂU, România")),
        createLoc("Dorneni", "sat", createAdresaCompleta("sat Dorneni, comuna Plopana, judetul BACĂU, România")),
        createLoc("Fundu Tutovei", "sat", createAdresaCompleta("sat Fundu Tutovei, comuna Plopana, judetul BACĂU, România")),
        createLoc("Ițcani", "sat", createAdresaCompleta("sat Ițcani, comuna Plopana, judetul BACĂU, România")),
        createLoc("Rusenii Răzeși", "sat", createAdresaCompleta("sat Rusenii Răzeși, comuna Plopana, judetul BACĂU, România")),
        createLoc("Rusenii de Sus", "sat", createAdresaCompleta("sat Rusenii de Sus, comuna Plopana, judetul BACĂU, România")),
        createLoc("Străminoasa", "sat", createAdresaCompleta("sat Străminoasa, comuna Plopana, judetul BACĂU, România")),
        createLoc("Țâgâra", "sat", createAdresaCompleta("sat Țâgâra, comuna Plopana, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Plopana, judetul BACĂU, România")),
    createComuna("Podu Turcului", [
        createLoc("Podu Turcului", "sat", createAdresaCompleta("sat Podu Turcului, comuna Podu Turcului, judetul BACĂU, România")),
        createLoc("Bălănești", "sat", createAdresaCompleta("sat Bălănești, comuna Podu Turcului, judetul BACĂU, România")),
        createLoc("Căbești", "sat", createAdresaCompleta("sat Căbești, comuna Podu Turcului, judetul BACĂU, România")),
        createLoc("Fichitești", "sat", createAdresaCompleta("sat Fichitești, comuna Podu Turcului, judetul BACĂU, România")),
        createLoc("Giurgioana", "sat", createAdresaCompleta("sat Giurgioana, comuna Podu Turcului, judetul BACĂU, România")),
        createLoc("Hanța", "sat", createAdresaCompleta("sat Hanța, comuna Podu Turcului, judetul BACĂU, România")),
        createLoc("Lehancea", "sat", createAdresaCompleta("sat Lehancea, comuna Podu Turcului, judetul BACĂU, România")),
        createLoc("Plopu", "sat", createAdresaCompleta("sat Plopu, comuna Podu Turcului, judetul BACĂU, România")),
        createLoc("Răcușana", "sat", createAdresaCompleta("sat Răcușana, comuna Podu Turcului, judetul BACĂU, România")),
        createLoc("Sârbi", "sat", createAdresaCompleta("sat Sârbi, comuna Podu Turcului, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Podu Turcului, judetul BACĂU, România")),
    createComuna("Poduri", [
        createLoc("Poduri", "sat", createAdresaCompleta("sat Poduri, comuna Poduri, judetul BACĂU, România")),
        createLoc("Bucșești", "sat", createAdresaCompleta("sat Bucșești, comuna Poduri, judetul BACĂU, România")),
        createLoc("Cernu", "sat", createAdresaCompleta("sat Cernu, comuna Poduri, judetul BACĂU, România")),
        createLoc("Cornet", "sat", createAdresaCompleta("sat Cornet, comuna Poduri, judetul BACĂU, România")),
        createLoc("Negreni", "sat", createAdresaCompleta("sat Negreni, comuna Poduri, judetul BACĂU, România")),
        createLoc("Prohozești", "sat", createAdresaCompleta("sat Prohozești, comuna Poduri, judetul BACĂU, România")),
        createLoc("Valea Șoșii", "sat", createAdresaCompleta("sat Valea Șoșii, comuna Poduri, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Poduri, judetul BACĂU, România")),
    createComuna("Prăjești", [
        createLoc("Prăjești", "sat", createAdresaCompleta("sat Prăjești, comuna Prăjești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Prăjești, judetul BACĂU, România")),
    createComuna("Racova", [
        createLoc("Racova", "sat", createAdresaCompleta("sat Racova, comuna Racova, judetul BACĂU, România")),
        createLoc("Gura Văii", "sat", createAdresaCompleta("sat Gura Văii, comuna Racova, judetul BACĂU, România")),
        createLoc("Hălmăcioaia", "sat", createAdresaCompleta("sat Hălmăcioaia, comuna Racova, judetul BACĂU, România")),
        createLoc("Ilieși", "sat", createAdresaCompleta("sat Ilieși, comuna Racova, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Racova, judetul BACĂU, România")),
    createComuna("Răcăciuni", [
        createLoc("Răcăciuni", "sat", createAdresaCompleta("sat Răcăciuni, comuna Răcăciuni, judetul BACĂU, România")),
        createLoc("Ciucani", "sat", createAdresaCompleta("sat Ciucani, comuna Răcăciuni, judetul BACĂU, România")),
        createLoc("Fundu Răcăciuni", "sat", createAdresaCompleta("sat Fundu Răcăciuni, comuna Răcăciuni, judetul BACĂU, România")),
        createLoc("Gheorghe Doja", "sat", createAdresaCompleta("sat Gheorghe Doja, comuna Răcăciuni, judetul BACĂU, România")),
        createLoc("Gâșteni", "sat", createAdresaCompleta("sat Gâșteni, comuna Răcăciuni, judetul BACĂU, România")),
        createLoc("Răstoaca", "sat", createAdresaCompleta("sat Răstoaca, comuna Răcăciuni, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Răcăciuni, judetul BACĂU, România")),
    createComuna("Răchitoasa", [
        createLoc("Răchitoasa", "sat", createAdresaCompleta("sat Răchitoasa, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Barcana", "sat", createAdresaCompleta("sat Barcana, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Bucșa", "sat", createAdresaCompleta("sat Bucșa, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Buda", "sat", createAdresaCompleta("sat Buda, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Burdusaci", "sat", createAdresaCompleta("sat Burdusaci, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Dănăila", "sat", createAdresaCompleta("sat Dănăila, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Farcașa", "sat", createAdresaCompleta("sat Farcașa, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Fundătura Răchitoasa", "sat", createAdresaCompleta("sat Fundătura Răchitoasa, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Hăghiac", "sat", createAdresaCompleta("sat Hăghiac, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Magazia", "sat", createAdresaCompleta("sat Magazia, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Movilița", "sat", createAdresaCompleta("sat Movilița, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Oprișești", "sat", createAdresaCompleta("sat Oprișești, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Putini", "sat", createAdresaCompleta("sat Putini, comuna Răchitoasa, judetul BACĂU, România")),
        createLoc("Tochilea", "sat", createAdresaCompleta("sat Tochilea, comuna Răchitoasa, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Răchitoasa, judetul BACĂU, România")),
    createComuna("Roșiori", [
        createLoc("Roșiori", "sat", createAdresaCompleta("sat Roșiori, comuna Roșiori, judetul BACĂU, România")),
        createLoc("Misihănești", "sat", createAdresaCompleta("sat Misihănești, comuna Roșiori, judetul BACĂU, România")),
        createLoc("Negușeni", "sat", createAdresaCompleta("sat Negușeni, comuna Roșiori, judetul BACĂU, România")),
        createLoc("Poieni", "sat", createAdresaCompleta("sat Poieni, comuna Roșiori, judetul BACĂU, România")),
        createLoc("Valea Mare", "sat", createAdresaCompleta("sat Valea Mare, comuna Roșiori, judetul BACĂU, România")),
        createLoc("Valea Mică", "sat", createAdresaCompleta("sat Valea Mică, comuna Roșiori, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Roșiori, judetul BACĂU, România")),
    createComuna("Sascut", [
        createLoc("Sascut", "sat", createAdresaCompleta("sat Sascut, comuna Sascut, judetul BACĂU, România")),
        createLoc("Berești", "sat", createAdresaCompleta("sat Berești, comuna Sascut, judetul BACĂU, România")),
        createLoc("Conțești", "sat", createAdresaCompleta("sat Conțești, comuna Sascut, judetul BACĂU, România")),
        createLoc("Păncești", "sat", createAdresaCompleta("sat Păncești, comuna Sascut, judetul BACĂU, România")),
        createLoc("Sascut-Sat", "sat", createAdresaCompleta("sat Sascut-Sat, comuna Sascut, judetul BACĂU, România")),
        createLoc("Schineni", "sat", createAdresaCompleta("sat Schineni, comuna Sascut, judetul BACĂU, România")),
        createLoc("Valea Nacului", "sat", createAdresaCompleta("sat Valea Nacului, comuna Sascut, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Sascut, judetul BACĂU, România")),
    createComuna("Sănduleni", [
        createLoc("Sănduleni", "sat", createAdresaCompleta("sat Sănduleni, comuna Sănduleni, judetul BACĂU, România")),
        createLoc("Bârzulești", "sat", createAdresaCompleta("sat Bârzulești, comuna Sănduleni, judetul BACĂU, România")),
        createLoc("Coman", "sat", createAdresaCompleta("sat Coman, comuna Sănduleni, judetul BACĂU, România")),
        createLoc("Mateiești", "sat", createAdresaCompleta("sat Mateiești, comuna Sănduleni, judetul BACĂU, România")),
        createLoc("Stufu", "sat", createAdresaCompleta("sat Stufu, comuna Sănduleni, judetul BACĂU, România")),
        createLoc("Tisa", "sat", createAdresaCompleta("sat Tisa, comuna Sănduleni, judetul BACĂU, România")),
        createLoc("Verșești", "sat", createAdresaCompleta("sat Verșești, comuna Sănduleni, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Sănduleni, judetul BACĂU, România")),
    createComuna("Sărata", [
        createLoc("Sărata", "sat", createAdresaCompleta("sat Sărata, comuna Sărata, judetul BACĂU, România")),
        createLoc("Bălțata", "sat", createAdresaCompleta("sat Bălțata, comuna Sărata, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Sărata, judetul BACĂU, România")),
    createComuna("Săucești", [
        createLoc("Săucești", "sat", createAdresaCompleta("sat Săucești, comuna Săucești, judetul BACĂU, România")),
        createLoc("Bogdan Vodă", "sat", createAdresaCompleta("sat Bogdan Vodă, comuna Săucești, judetul BACĂU, România")),
        createLoc("Costei", "sat", createAdresaCompleta("sat Costei, comuna Săucești, judetul BACĂU, România")),
        createLoc("Schineni", "sat", createAdresaCompleta("sat Schineni, comuna Săucești, judetul BACĂU, România")),
        createLoc("Siretu", "sat", createAdresaCompleta("sat Siretu, comuna Săucești, judetul BACĂU, România")),
        createLoc("Șerbești", "sat", createAdresaCompleta("sat Șerbești, comuna Săucești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Săucești, judetul BACĂU, România")),
    createComuna("Scorțeni", [
        createLoc("Scorțeni", "sat", createAdresaCompleta("sat Scorțeni, comuna Scorțeni, judetul BACĂU, România")),
        createLoc("Bogdănești", "sat", createAdresaCompleta("sat Bogdănești, comuna Scorțeni, judetul BACĂU, România")),
        createLoc("Florești", "sat", createAdresaCompleta("sat Florești, comuna Scorțeni, judetul BACĂU, România")),
        createLoc("Grigoreni", "sat", createAdresaCompleta("sat Grigoreni, comuna Scorțeni, judetul BACĂU, România")),
        createLoc("Stejaru", "sat", createAdresaCompleta("sat Stejaru, comuna Scorțeni, judetul BACĂU, România")),
        createLoc("Șerpeni", "sat", createAdresaCompleta("sat Șerpeni, comuna Scorțeni, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Scorțeni, judetul BACĂU, România")),
    createComuna("Secuieni", [
        createLoc("Secuieni", "sat", createAdresaCompleta("sat Secuieni, comuna Secuieni, judetul BACĂU, România")),
        createLoc("Berbinceni", "sat", createAdresaCompleta("sat Berbinceni, comuna Secuieni, judetul BACĂU, România")),
        createLoc("Chiticeni", "sat", createAdresaCompleta("sat Chiticeni, comuna Secuieni, judetul BACĂU, România")),
        createLoc("Fundeni", "sat", createAdresaCompleta("sat Fundeni, comuna Secuieni, judetul BACĂU, România")),
        createLoc("Glodișoarele", "sat", createAdresaCompleta("sat Glodișoarele, comuna Secuieni, judetul BACĂU, România")),
        createLoc("Valea Fânațului", "sat", createAdresaCompleta("sat Valea Fânațului, comuna Secuieni, judetul BACĂU, România")),
        createLoc("Văleni", "sat", createAdresaCompleta("sat Văleni, comuna Secuieni, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Secuieni, judetul BACĂU, România")),
    createComuna("Solonț", [
        createLoc("Solonț", "sat", createAdresaCompleta("sat Solonț, comuna Solonț, judetul BACĂU, România")),
        createLoc("Cucuieți", "sat", createAdresaCompleta("sat Cucuieți, comuna Solonț, judetul BACĂU, România")),
        createLoc("Sărata", "sat", createAdresaCompleta("sat Sărata, comuna Solonț, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Solonț, judetul BACĂU, România")),
    createComuna("Stănișești", [
        createLoc("Stănișești", "sat", createAdresaCompleta("sat Stănișești, comuna Stănișești, judetul BACĂU, România")),
        createLoc("Balotești", "sat", createAdresaCompleta("sat Balotești, comuna Stănișești, judetul BACĂU, România")),
        createLoc("Belciuneasa", "sat", createAdresaCompleta("sat Belciuneasa, comuna Stănișești, judetul BACĂU, România")),
        createLoc("Benești", "sat", createAdresaCompleta("sat Benești, comuna Stănișești, judetul BACĂU, România")),
        createLoc("Crăiești", "sat", createAdresaCompleta("sat Crăiești, comuna Stănișești, judetul BACĂU, România")),
        createLoc("Gorghești", "sat", createAdresaCompleta("sat Gorghești, comuna Stănișești, judetul BACĂU, România")),
        createLoc("Slobozia", "sat", createAdresaCompleta("sat Slobozia, comuna Stănișești, judetul BACĂU, România")),
        createLoc("Slobozia Nouă", "sat", createAdresaCompleta("sat Slobozia Nouă, comuna Stănișești, judetul BACĂU, România")),
        createLoc("Văleni", "sat", createAdresaCompleta("sat Văleni, comuna Stănișești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Stănișești, judetul BACĂU, România")),
    createComuna("Strugari", [
        createLoc("Strugari", "sat", createAdresaCompleta("sat Strugari, comuna Strugari, judetul BACĂU, România")),
        createLoc("Cetățuia", "sat", createAdresaCompleta("sat Cetățuia, comuna Strugari, judetul BACĂU, România")),
        createLoc("Iaz", "sat", createAdresaCompleta("sat Iaz, comuna Strugari, judetul BACĂU, România")),
        createLoc("Nadișa", "sat", createAdresaCompleta("sat Nadișa, comuna Strugari, judetul BACĂU, România")),
        createLoc("Petricica", "sat", createAdresaCompleta("sat Petricica, comuna Strugari, judetul BACĂU, România")),
        createLoc("Răchitișu", "sat", createAdresaCompleta("sat Răchitișu, comuna Strugari, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Strugari, judetul BACĂU, România")),
    createComuna("Ștefan cel Mare", [
        createLoc("Ștefan cel Mare", "sat", createAdresaCompleta("sat Ștefan cel Mare, comuna Ștefan cel Mare, judetul BACĂU, România")),
        createLoc("Bogdana", "sat", createAdresaCompleta("sat Bogdana, comuna Ștefan cel Mare, judetul BACĂU, România")),
        createLoc("Gutinaș", "sat", createAdresaCompleta("sat Gutinaș, comuna Ștefan cel Mare, judetul BACĂU, România")),
        createLoc("Negoiești", "sat", createAdresaCompleta("sat Negoiești, comuna Ștefan cel Mare, judetul BACĂU, România")),
        createLoc("Rădeana", "sat", createAdresaCompleta("sat Rădeana, comuna Ștefan cel Mare, judetul BACĂU, România")),
        createLoc("Viișoara", "sat", createAdresaCompleta("sat Viișoara, comuna Ștefan cel Mare, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Ștefan cel Mare, judetul BACĂU, România")),
    createComuna("Tamași", [
        createLoc("Tamași", "sat", createAdresaCompleta("sat Tamași, comuna Tamași, judetul BACĂU, România")),
        createLoc("Chetriș", "sat", createAdresaCompleta("sat Chetriș, comuna Tamași, judetul BACĂU, România")),
        createLoc("Furnicari", "sat", createAdresaCompleta("sat Furnicari, comuna Tamași, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Tamași, judetul BACĂU, România")),
    createComuna("Tătărăști", [
        createLoc("Tătărăști", "sat", createAdresaCompleta("sat Tătărăști, comuna Tătărăști, judetul BACĂU, România")),
        createLoc("Cornii de Jos", "sat", createAdresaCompleta("sat Cornii de Jos, comuna Tătărăști, judetul BACĂU, România")),
        createLoc("Cornii de Sus", "sat", createAdresaCompleta("sat Cornii de Sus, comuna Tătărăști, judetul BACĂU, România")),
        createLoc("Drăgești", "sat", createAdresaCompleta("sat Drăgești, comuna Tătărăști, judetul BACĂU, România")),
        createLoc("Gherdana", "sat", createAdresaCompleta("sat Gherdana, comuna Tătărăști, judetul BACĂU, România")),
        createLoc("Giurgeni", "sat", createAdresaCompleta("sat Giurgeni, comuna Tătărăști, judetul BACĂU, România")),
        createLoc("Ungureni", "sat", createAdresaCompleta("sat Ungureni, comuna Tătărăști, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Tătărăști, judetul BACĂU, România")),
    createComuna("Târgu Trotuș", [
        createLoc("Târgu Trotuș", "oras", createAdresaCompleta("orasul Târgu Trotuș, judetul BACĂU, România")),
        createLoc("Tuta", "sat", createAdresaCompleta("sat Tuta, orasul Târgu Trotuș, judetul BACĂU, România")),
        createLoc("Viișoara", "sat", createAdresaCompleta("sat Viișoara, orasul Târgu Trotuș, judetul BACĂU, România")),
    ], createAdresaCompleta("orasul Târgu Trotuș, judetul BACĂU, România")),
    createComuna("Traian", [
        createLoc("Traian", "sat", createAdresaCompleta("sat Traian, comuna Traian, judetul BACĂU, România")),
        createLoc("Bogdănești", "sat", createAdresaCompleta("sat Bogdănești, comuna Traian, judetul BACĂU, România")),
        createLoc("Hertioana de Jos", "sat", createAdresaCompleta("sat Hertioana de Jos, comuna Traian, judetul BACĂU, România")),
        createLoc("Hertioana-Răzeși", "sat", createAdresaCompleta("sat Hertioana-Răzeși, comuna Traian, judetul BACĂU, România")),
        createLoc("Zăpodia", "sat", createAdresaCompleta("sat Zăpodia, comuna Traian, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Traian, judetul BACĂU, România")),
    createComuna("Ungureni", [
        createLoc("Ungureni", "sat", createAdresaCompleta("sat Ungureni, comuna Ungureni, judetul BACĂU, România")),
        createLoc("Bărtășești", "sat", createAdresaCompleta("sat Bărtășești, comuna Ungureni, judetul BACĂU, România")),
        createLoc("Bibirești", "sat", createAdresaCompleta("sat Bibirești, comuna Ungureni, judetul BACĂU, România")),
        createLoc("Bota", "sat", createAdresaCompleta("sat Bota, comuna Ungureni, judetul BACĂU, România")),
        createLoc("Botești", "sat", createAdresaCompleta("sat Botești, comuna Ungureni, judetul BACĂU, România")),
        createLoc("Gârla Anei", "sat", createAdresaCompleta("sat Gârla Anei, comuna Ungureni, judetul BACĂU, România")),
        createLoc("Viforeni", "sat", createAdresaCompleta("sat Viforeni, comuna Ungureni, judetul BACĂU, România")),
        createLoc("Zlătari", "sat", createAdresaCompleta("sat Zlătari, comuna Ungureni, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Ungureni, judetul BACĂU, România")),
    createComuna("Urechești", [
        createLoc("Urechești", "sat", createAdresaCompleta("sat Urechești, comuna Urechești, judetul BACĂU, România")),
        createLoc("Cornățel", "sat", createAdresaCompleta("sat Cornățel, comuna Urechești, judetul BACĂU, România")),
        createLoc("Lunca Dochiei", "sat", createAdresaCompleta("sat Lunca Dochiei, comuna Urechești, judetul BACĂU, România")),
        createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Urechești, judetul BACĂU, România")),
        createLoc("Slobozia", "sat", createAdresaCompleta("sat Slobozia, comuna Urechești, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Urechești, judetul BACĂU, România")),
    createComuna("Valea Seacă", [
        createLoc("Valea Seacă", "sat", createAdresaCompleta("sat Valea Seacă, comuna Valea Seacă, judetul BACĂU, România")),
        createLoc("Cucova", "sat", createAdresaCompleta("sat Cucova, comuna Valea Seacă, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Valea Seacă, judetul BACĂU, România")),
    createComuna("Vultureni", [
        createLoc("Vultureni", "sat", createAdresaCompleta("sat Vultureni, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Bosia", "sat", createAdresaCompleta("sat Bosia, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Dădești", "sat", createAdresaCompleta("sat Dădești, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Dorneni", "sat", createAdresaCompleta("sat Dorneni, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Ghilăvești", "sat", createAdresaCompleta("sat Ghilăvești, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Godineștii de Jos", "sat", createAdresaCompleta("sat Godineștii de Jos, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Godineștii de Sus", "sat", createAdresaCompleta("sat Godineștii de Sus, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Lichitișeni", "sat", createAdresaCompleta("sat Lichitișeni, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Medeleni", "sat", createAdresaCompleta("sat Medeleni, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Năzărioaia", "sat", createAdresaCompleta("sat Năzărioaia, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Reprivăț", "sat", createAdresaCompleta("sat Reprivăț, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Tomozia", "sat", createAdresaCompleta("sat Tomozia, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Țigănești", "sat", createAdresaCompleta("sat Țigănești, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Valea Lupului", "sat", createAdresaCompleta("sat Valea Lupului, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Valea Merilor", "sat", createAdresaCompleta("sat Valea Merilor, comuna Vultureni, judetul BACĂU, România")),
        createLoc("Valea Salciei", "sat", createAdresaCompleta("sat Valea Salciei, comuna Vultureni, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Vultureni, judetul BACĂU, România")),
    createComuna("Zemeș", [
        createLoc("Zemeș", "sat", createAdresaCompleta("sat Zemeș, comuna Zemeș, judetul BACĂU, România")),
        createLoc("Bolătău", "sat", createAdresaCompleta("sat Bolătău, comuna Zemeș, judetul BACĂU, România")),
    ], createAdresaCompleta("comuna Zemeș, judetul BACĂU, România")),
];
?>