<?php
$comune =[
    createComuna("Agăș", [
        createLoc("Agăș", "sat"),
        createLoc("Beleghet", "sat"),
        createLoc("Coșnea", "sat"),
        createLoc("Cotumba", "sat"),
        createLoc("Diaconești", "sat"),
        createLoc("Goioasa", "sat"),
        createLoc("Preluci", "sat"),
        createLoc("Sulța", "sat"),
    ]),
    createComuna("Ardeoani", [
        createLoc("Ardeoani", "sat"),
        createLoc("Leontinești", "sat"),
    ]),
    createComuna("Asău", [
        createLoc("Asău", "sat"),
        createLoc("Apa Asău", "sat"),
        createLoc("Ciobănuș", "sat"),
        createLoc("Lunca Asău", "sat"),
        createLoc("Păltiniș", "sat"),
        createLoc("Straja", "sat"),
    ]),
    createComuna("Balcani", [
        createLoc("Balcani", "sat"),
        createLoc("Frumoasa", "sat"),
        createLoc("Ludași", "sat"),
        createLoc("Schitu Frumoasa", "sat"),
    ]),
    createComuna("Berești-Bistrița", [
        createLoc("Berești-Bistrița", "sat"),
        createLoc("Brad", "sat"),
        createLoc("Climești", "sat"),
        createLoc("Pădureni", "sat"),
    ]),
    createComuna("Berești-Tazlău", [
        createLoc("Berești-Tazlău", "sat"),
        createLoc("Boșoteni", "sat"),
        createLoc("Enăchești", "sat"),
        createLoc("Prisaca", "sat"),
        createLoc("Românești", "sat"),
        createLoc("Tescani", "sat"),
        createLoc("Turluianu", "sat"),
    ]),
    createComuna("Berzunți", [
        createLoc("Berzunți", "sat"),
        createLoc("Buda", "sat"),
        createLoc("Dragomir", "sat"),
    ]),
    createComuna("Bârsănești", [
        createLoc("Bârsănești", "sat"),
        createLoc("Albele", "sat"),
        createLoc("Brătești", "sat"),
        createLoc("Caraclău", "sat"),
    ]),
    createComuna("Blăgești", [
        createLoc("Blăgești", "sat"),
        createLoc("Buda", "sat"),
        createLoc("Poiana Negustorului", "sat"),
        createLoc("Țârdenii Mari", "sat"),
        createLoc("Valea lui Ion", "sat"),
    ]),
    createComuna("Bogdănești", [
        createLoc("Bogdănești", "sat"),
        createLoc("Filipești", "sat"),
    ]),
	    createComuna("Brusturoasa", [
        createLoc("Brusturoasa", "sat"),
        createLoc("Buruieniș", "sat"),
        createLoc("Buruienișu de Sus", "sat"),
        createLoc("Camenca", "sat"),
        createLoc("Cuchiniș", "sat"),
        createLoc("Hângănești", "sat"),
    ]),
    createComuna("Buciumi", [
        createLoc("Buciumi", "sat"),
        createLoc("Răcăuți", "sat"),
    ]),
    createComuna("Buhoci", [
        createLoc("Buhoci", "sat"),
        createLoc("Bijghir", "sat"),
        createLoc("Buhocel", "sat"),
        createLoc("Coteni", "sat"),
        createLoc("Dospinești", "sat"),
    ]),
    createComuna("Cașin", [
        createLoc("Cașin", "sat"),
        createLoc("Curița", "sat"),
    ]),
    createComuna("Căiuți", [
        createLoc("Căiuți", "sat"),
        createLoc("Blidari", "sat"),
        createLoc("Boiștea", "sat"),
        createLoc("Florești", "sat"),
        createLoc("Heltiu", "sat"),
        createLoc("Mărcești", "sat"),
        createLoc("Popeni", "sat"),
        createLoc("Pralea", "sat"),
        createLoc("Vrânceni", "sat"),
    ]),
    createComuna("Cleja", [
        createLoc("Cleja", "sat"),
        createLoc("Somușca", "sat"),
        createLoc("Valea Mică", "sat"),
    ]),
    createComuna("Colonești", [
        createLoc("Colonești", "sat"),
        createLoc("Călini", "sat"),
        createLoc("Poiana", "sat"),
        createLoc("Satu Nou", "sat"),
        createLoc("Spria", "sat"),
        createLoc("Valea Mare", "sat"),
        createLoc("Zăpodia", "sat"),
    ]),
    createComuna("Corbasca", [
        createLoc("Corbasca", "sat"),
        createLoc("Băcioiu", "sat"),
        createLoc("Marvila", "sat"),
        createLoc("Pogleț", "sat"),
        createLoc("Rogoaza", "sat"),
        createLoc("Scărișoara", "sat"),
        createLoc("Vâlcele", "sat"),
    ]),
    createComuna("Coțofănești", [
        createLoc("Coțofănești", "sat"),
        createLoc("Bâlca", "sat"),
        createLoc("Boiștea de Jos", "sat"),
        createLoc("Borșani", "sat"),
        createLoc("Tămășoaia", "sat"),
    ]),
    createComuna("Dămienești", [
        createLoc("Dămienești", "sat"),
        createLoc("Călugăreni", "sat"),
        createLoc("Drăgești", "sat"),
        createLoc("Pădureni", "sat"),
    ]),
    createComuna("Dealu Morii", [
        createLoc("Dealu Morii", "sat"),
        createLoc("Banca", "sat"),
        createLoc("Bălănești", "sat"),
        createLoc("Blaga", "sat"),
        createLoc("Boboș", "sat"),
        createLoc("Bodeasa", "sat"),
        createLoc("Bostănești", "sat"),
        createLoc("Calapodești", "sat"),
        createLoc("Căuia", "sat"),
        createLoc("Dorofei", "sat"),
        createLoc("Ghionoaia", "sat"),
        createLoc("Grădești", "sat"),
        createLoc("Negulești", "sat"),
        createLoc("Tăvădărești", "sat"),
    ]),
    createComuna("Dofteana", [
        createLoc("Dofteana", "sat"),
        createLoc("Bogata", "sat"),
        createLoc("Cucuieți", "sat"),
        createLoc("Hăghiac", "sat"),
        createLoc("Larga", "sat"),
        createLoc("Seaca", "sat"),
        createLoc("Ștefan Vodă", "sat"),
    ]),
    createComuna("Faraoani", [
        createLoc("Faraoani", "sat"),
    ]),
    createComuna("Filipeni", [
        createLoc("Filipeni", "sat"),
        createLoc("Bălaia", "sat"),
        createLoc("Brad", "sat"),
        createLoc("Fruntești", "sat"),
        createLoc("Mărăști", "sat"),
        createLoc("Pădureni", "sat"),
        createLoc("Slobozia", "sat"),
        createLoc("Valea Boțului", "sat"),
    ]),
    createComuna("Filipești", [
        createLoc("Filipești", "sat"),
        createLoc("Boanța", "sat"),
        createLoc("Cârligi", "sat"),
        createLoc("Cornești", "sat"),
        createLoc("Cotu Grosului", "sat"),
        createLoc("Galbeni", "sat"),
        createLoc("Hârlești", "sat"),
        createLoc("Onișcani", "sat"),
    ]),
    createComuna("Găiceana", [
        createLoc("Găiceana", "sat"),
        createLoc("Arini", "sat"),
        createLoc("Huțu", "sat"),
        createLoc("Popești", "sat"),
    ]),
    createComuna("Ghimeș-Făget", [
        createLoc("Făget", "sat"),
        createLoc("Bolovăniș", "sat"),
        createLoc("Făgetu de Sus", "sat"),
        createLoc("Ghimeș", "sat"),
        createLoc("Răchitiș", "sat"),
        createLoc("Tărhăuși", "sat"),
    ]),
    createComuna("Gioseni", [
        createLoc("Gioseni", "sat"),
    ]),
    createComuna("Gârleni", [
        createLoc("Gârlenii de Sus", "sat"),
        createLoc("Gârleni", "sat"),
        createLoc("Lespezi", "sat"),
        createLoc("Șurina", "sat"),
    ]),
    createComuna("Glăvănești", [
        createLoc("Glăvănești", "sat"),
        createLoc("Frumușelu", "sat"),
        createLoc("Muncelu", "sat"),
        createLoc("Putredeni", "sat"),
        createLoc("Răzeșu", "sat"),
    ]),
    createComuna("Gura Văii", [
        createLoc("Gura Văii", "sat"),
        createLoc("Capăta", "sat"),
        createLoc("Dumbrava", "sat"),
        createLoc("Motocești", "sat"),
        createLoc("Păltinata", "sat"),
        createLoc("Temelia", "sat"),
    ]),
    createComuna("Helegiu", [
        createLoc("Helegiu", "sat"),
        createLoc("Brătila", "sat"),
        createLoc("Deleni", "sat"),
        createLoc("Drăgugești", "sat"),
    ]),
    createComuna("Hemeiuș", [
        createLoc("Hemeiuș", "sat"),
        createLoc("Fântânele", "sat"),
        createLoc("Lilieci", "sat"),
    ]),
    createComuna("Horgești", [
        createLoc("Horgești", "sat"),
        createLoc("Bazga", "sat"),
        createLoc("Galeri", "sat"),
        createLoc("Mărăscu", "sat"),
        createLoc("Răcătău-Răzeși", "sat"),
        createLoc("Răcătău de Jos", "sat"),
        createLoc("Recea", "sat"),
        createLoc("Sohodor", "sat"),
    ]),
    createComuna("Huruiești", [
        createLoc("Huruiești", "sat"),
        createLoc("Căpotești", "sat"),
        createLoc("Florești", "sat"),
        createLoc("Fundoaia", "sat"),
        createLoc("Ocheni", "sat"),
        createLoc("Perchiu", "sat"),
        createLoc("Prădaiș", "sat"),
    ]),
    createComuna("Itești", [
        createLoc("Itești", "sat"),
        createLoc("Ciumași", "sat"),
        createLoc("Dumbrava", "sat"),
        createLoc("Făgețel", "sat"),
    ]),
    createComuna("Izvoru Berheciului", [
        createLoc("Izvoru Berheciului", "sat"),
        createLoc("Antohești", "sat"),
        createLoc("Băimac", "sat"),
        createLoc("Făghieni", "sat"),
        createLoc("Obârșia", "sat"),
        createLoc("Oțelești", "sat"),
        createLoc("Pădureni", "sat"),
    ]),
    createComuna("Letea Veche", [
        createLoc("Letea Veche", "sat"),
        createLoc("Holt", "sat"),
        createLoc("Radomirești", "sat"),
        createLoc("Ruși-Ciutea", "sat"),
        createLoc("Siretu", "sat"),
    ]),
    createComuna("Lipova", [
        createLoc("Lipova", "sat"),
        createLoc("Mâlosu", "sat"),
        createLoc("Satu Nou", "sat"),
        createLoc("Valea Caselor", "sat"),
        createLoc("Valea Hogei", "sat"),
        createLoc("Valea Mărului", "sat"),
        createLoc("Valea Moșneagului", "sat"),
    ]),
    createComuna("Livezi", [
        createLoc("Livezi", "sat"),
        createLoc("Bălăneasa", "sat"),
        createLoc("Orășa", "sat"),
        createLoc("Poiana", "sat"),
        createLoc("Prăjoaia", "sat"),
        createLoc("Scăriga", "sat"),
    ]),
    createComuna("Luizi-Călugăra", [
        createLoc("Luizi-Călugăra", "sat"),
        createLoc("Osebiți", "sat"),
    ]),
    createComuna("Măgirești", [
        createLoc("Măgirești", "sat"),
        createLoc("Prăjești", "sat"),
        createLoc("Stănești", "sat"),
        createLoc("Șesuri", "sat"),
        createLoc("Valea Arinilor", "sat"),
    ]),
    createComuna("Măgura", [
        createLoc("Măgura", "sat"),
        createLoc("Crihan", "sat"),
        createLoc("Dealu Mare", "sat"),
        createLoc("Sohodol", "sat"),
    ]),
    createComuna("Mănăstirea Cașin", [
        createLoc("Mănăstirea Cașin", "sat"),
        createLoc("Lupești", "sat"),
        createLoc("Pârvulești", "sat"),
        createLoc("Scutaru", "sat"),
    ]),
    createComuna("Mărgineni", [
        createLoc("Mărgineni", "sat"),
        createLoc("Barați", "sat"),
        createLoc("Luncani", "sat"),
        createLoc("Pădureni", "sat"),
        createLoc("Podiș", "sat"),
        createLoc("Poiana", "sat"),
        createLoc("Trebeș", "sat"),
        createLoc("Valea Budului", "sat"),
    ]),
    createComuna("Motoșeni", [
        createLoc("Motoșeni", "sat"),
        createLoc("Bâclești", "sat"),
        createLoc("Chetreni", "sat"),
        createLoc("Chicerea", "sat"),
        createLoc("Cociu", "sat"),
        createLoc("Cornățelu", "sat"),
        createLoc("Fântânele", "sat"),
        createLoc("Fundătura", "sat"),
        createLoc("Gura Crăiești", "sat"),
        createLoc("Poiana", "sat"),
        createLoc("Praja", "sat"),
        createLoc("Rotăria", "sat"),
        createLoc("Șendrești", "sat"),
        createLoc("Țepoaia", "sat"),
    ]),
    createComuna("Negri", [
        createLoc("Negri", "sat"),
        createLoc("Brad", "sat"),
        createLoc("Călinești", "sat"),
        createLoc("Mâgla", "sat"),
        createLoc("Poiana", "sat"),
        createLoc("Ursoaia", "sat"),
    ]),
    createComuna("Nicolae Bălcescu", [
        createLoc("Nicolae Bălcescu", "sat"),
        createLoc("Buchila", "sat"),
        createLoc("Galbeni", "sat"),
        createLoc("Lărguța", "sat"),
        createLoc("Valea Seacă", "sat"),
    ]),
    createComuna("Odobești", [
        createLoc("Odobești", "sat"),
        createLoc("Bălușa", "sat"),
        createLoc("Ciuturești", "sat"),
        createLoc("Tisa-Silvestri", "sat"),
    ]),
    createComuna("Oituz", [
        createLoc("Oituz", "sat"),
        createLoc("Călcâi", "sat"),
        createLoc("Ferestrău-Oituz", "sat"),
        createLoc("Hârja", "sat"),
        createLoc("Marginea", "sat"),
        createLoc("Poiana Sărată", "sat"),
    ]),
    createComuna("Oncești", [
        createLoc("Oncești", "sat"),
        createLoc("Bărboasa", "sat"),
        createLoc("Dealu Perjului", "sat"),
        createLoc("Onceștii Vechi", "sat"),
        createLoc("Satu Nou", "sat"),
        createLoc("Tarnița", "sat"),
        createLoc("Taula", "sat"),
    ]),
    createComuna("Orbeni", [
        createLoc("Orbeni", "sat"),
        createLoc("Scurta", "sat"),
    ]),
    createComuna("Palanca", [
        createLoc("Palanca", "sat"),
        createLoc("Cădărești", "sat"),
        createLoc("Ciugheș", "sat"),
        createLoc("Pajiștea", "sat"),
        createLoc("Popoiu", "sat"),
    ]),
    createComuna("Parava", [
        createLoc("Parava", "sat"),
        createLoc("Drăgușani", "sat"),
        createLoc("Rădoaia", "sat"),
        createLoc("Teiuș", "sat"),
    ]),
    createComuna("Parincea", [
        createLoc("Parincea", "sat"),
        createLoc("Barna", "sat"),
        createLoc("Mileștii de Jos", "sat"),
        createLoc("Mileștii de Sus", "sat"),
        createLoc("Nănești", "sat"),
        createLoc("Năstăseni", "sat"),
        createLoc("Poieni", "sat"),
        createLoc("Satu Nou", "sat"),
        createLoc("Văleni", "sat"),
        createLoc("Vladnic", "sat"),
    ]),
    createComuna("Pâncești", [
        createLoc("Pâncești", "sat"),
        createLoc("Chilia Benei", "sat"),
        createLoc("Dieneț", "sat"),
        createLoc("Fulgeriș", "sat"),
        createLoc("Fundu Văii", "sat"),
        createLoc("Motoc", "sat"),
        createLoc("Petrești", "sat"),
        createLoc("Soci", "sat"),
    ]),
    createComuna("Pârgărești", [
        createLoc("Pârgărești", "sat"),
        createLoc("Bahna", "sat"),
        createLoc("Nicorești", "sat"),
        createLoc("Pârâu Boghii", "sat"),
        createLoc("Satu Nou", "sat"),
    ]),
    createComuna("Pârjol", [
        createLoc("Pârjol", "sat"),
        createLoc("Băhnășeni", "sat"),
        createLoc("Bărnești", "sat"),
        createLoc("Băsăști", "sat"),
        createLoc("Câmpeni", "sat"),
        createLoc("Hăineala", "sat"),
        createLoc("Hemieni", "sat"),
        createLoc("Pustiana", "sat"),
        createLoc("Tărâța", "sat"),
    ]),
    createComuna("Plopana", [
        createLoc("Plopana", "sat"),
        createLoc("Budești", "sat"),
        createLoc("Dorneni", "sat"),
        createLoc("Fundu Tutovei", "sat"),
        createLoc("Ițcani", "sat"),
        createLoc("Rusenii Răzeși", "sat"),
        createLoc("Rusenii de Sus", "sat"),
        createLoc("Străminoasa", "sat"),
        createLoc("Țâgâra", "sat"),
    ]),
    createComuna("Podu Turcului", [
        createLoc("Podu Turcului", "sat"),
        createLoc("Bălănești", "sat"),
        createLoc("Căbești", "sat"),
        createLoc("Fichitești", "sat"),
        createLoc("Giurgioana", "sat"),
        createLoc("Hanța", "sat"),
        createLoc("Lehancea", "sat"),
        createLoc("Plopu", "sat"),
        createLoc("Răcușana", "sat"),
        createLoc("Sârbi", "sat"),
    ]),
    createComuna("Poduri", [
        createLoc("Poduri", "sat"),
        createLoc("Bucșești", "sat"),
        createLoc("Cernu", "sat"),
        createLoc("Cornet", "sat"),
        createLoc("Negreni", "sat"),
        createLoc("Prohozești", "sat"),
        createLoc("Valea Șoșii", "sat"),
    ]),
    createComuna("Prăjești", [
        createLoc("Prăjești", "sat"),
    ]),
    createComuna("Racova", [
        createLoc("Racova", "sat"),
        createLoc("Gura Văii", "sat"),
        createLoc("Hălmăcioaia", "sat"),
        createLoc("Ilieși", "sat"),
    ]),
    createComuna("Răcăciuni", [
        createLoc("Răcăciuni", "sat"),
        createLoc("Ciucani", "sat"),
        createLoc("Fundu Răcăciuni", "sat"),
        createLoc("Gheorghe Doja", "sat"),
        createLoc("Gâșteni", "sat"),
        createLoc("Răstoaca", "sat"),
    ]),
    createComuna("Răchitoasa", [
        createLoc("Răchitoasa", "sat"),
        createLoc("Barcana", "sat"),
        createLoc("Bucșa", "sat"),
        createLoc("Buda", "sat"),
        createLoc("Burdusaci", "sat"),
        createLoc("Dănăila", "sat"),
        createLoc("Dumbrava", "sat"),
        createLoc("Farcașa", "sat"),
        createLoc("Fundătura Răchitoasa", "sat"),
        createLoc("Hăghiac", "sat"),
        createLoc("Magazia", "sat"),
        createLoc("Movilița", "sat"),
        createLoc("Oprișești", "sat"),
        createLoc("Putini", "sat"),
        createLoc("Tochilea", "sat"),
    ]),
    createComuna("Roșiori", [
        createLoc("Roșiori", "sat"),
        createLoc("Misihănești", "sat"),
        createLoc("Negușeni", "sat"),
        createLoc("Poieni", "sat"),
        createLoc("Valea Mare", "sat"),
        createLoc("Valea Mică", "sat"),
    ]),
    createComuna("Sascut", [
        createLoc("Sascut", "sat"),
        createLoc("Berești", "sat"),
        createLoc("Conțești", "sat"),
        createLoc("Păncești", "sat"),
        createLoc("Sascut-Sat", "sat"),
        createLoc("Schineni", "sat"),
        createLoc("Valea Nacului", "sat"),
    ]),
    createComuna("Sănduleni", [
        createLoc("Sănduleni", "sat"),
        createLoc("Bârzulești", "sat"),
        createLoc("Coman", "sat"),
        createLoc("Mateiești", "sat"),
        createLoc("Stufu", "sat"),
        createLoc("Tisa", "sat"),
        createLoc("Verșești", "sat"),
    ]),
    createComuna("Sărata", [
        createLoc("Sărata", "sat"),
        createLoc("Bălțata", "sat"),
    ]),
    createComuna("Săucești", [
        createLoc("Săucești", "sat"),
        createLoc("Bogdan Vodă", "sat"),
        createLoc("Costei", "sat"),
        createLoc("Schineni", "sat"),
        createLoc("Siretu", "sat"),
        createLoc("Șerbești", "sat"),
    ]),
    createComuna("Scorțeni", [
        createLoc("Scorțeni", "sat"),
        createLoc("Bogdănești", "sat"),
        createLoc("Florești", "sat"),
        createLoc("Grigoreni", "sat"),
        createLoc("Stejaru", "sat"),
        createLoc("Șerpeni", "sat"),
    ]),
    createComuna("Secuieni", [
        createLoc("Secuieni", "sat"),
        createLoc("Berbinceni", "sat"),
        createLoc("Chiticeni", "sat"),
        createLoc("Fundeni", "sat"),
        createLoc("Glodișoarele", "sat"),
        createLoc("Valea Fânațului", "sat"),
        createLoc("Văleni", "sat"),
    ]),
    createComuna("Solonț", [
        createLoc("Solonț", "sat"),
        createLoc("Cucuieți", "sat"),
        createLoc("Sărata", "sat"),
    ]),
    createComuna("Stănișești", [
        createLoc("Stănișești", "sat"),
        createLoc("Balotești", "sat"),
        createLoc("Belciuneasa", "sat"),
        createLoc("Benești", "sat"),
        createLoc("Crăiești", "sat"),
        createLoc("Gorghești", "sat"),
        createLoc("Slobozia", "sat"),
        createLoc("Slobozia Nouă", "sat"),
        createLoc("Văleni", "sat"),
    ]),
    createComuna("Strugari", [
        createLoc("Strugari", "sat"),
        createLoc("Cetățuia", "sat"),
        createLoc("Iaz", "sat"),
        createLoc("Nadișa", "sat"),
        createLoc("Petricica", "sat"),
        createLoc("Răchitișu", "sat"),
    ]),
    createComuna("Ștefan cel Mare", [
        createLoc("Ștefan cel Mare", "sat"),
        createLoc("Bogdana", "sat"),
        createLoc("Gutinaș", "sat"),
        createLoc("Negoiești", "sat"),
        createLoc("Rădeana", "sat"),
        createLoc("Viișoara", "sat"),
    ]),
    createComuna("Tamași", [
        createLoc("Tamași", "sat"),
        createLoc("Chetriș", "sat"),
        createLoc("Furnicari", "sat"),
    ]),
    createComuna("Tătărăști", [
        createLoc("Tătărăști", "sat"),
        createLoc("Cornii de Jos", "sat"),
        createLoc("Cornii de Sus", "sat"),
        createLoc("Drăgești", "sat"),
        createLoc("Gherdana", "sat"),
        createLoc("Giurgeni", "sat"),
        createLoc("Ungureni", "sat"),
    ]),
    createComuna("Târgu Trotuș", [
        createLoc("Târgu Trotuș", "oras"),
        createLoc("Tuta", "sat"),
        createLoc("Viișoara", "sat"),
    ]),
    createComuna("Traian", [
        createLoc("Traian", "sat"),
        createLoc("Bogdănești", "sat"),
        createLoc("Hertioana de Jos", "sat"),
        createLoc("Hertioana-Răzeși", "sat"),
        createLoc("Zăpodia", "sat"),
    ]),
    createComuna("Ungureni", [
        createLoc("Ungureni", "sat"),
        createLoc("Bărtășești", "sat"),
        createLoc("Bibirești", "sat"),
        createLoc("Bota", "sat"),
        createLoc("Botești", "sat"),
        createLoc("Gârla Anei", "sat"),
        createLoc("Viforeni", "sat"),
        createLoc("Zlătari", "sat"),
    ]),
    createComuna("Urechești", [
        createLoc("Urechești", "sat"),
        createLoc("Cornățel", "sat"),
        createLoc("Lunca Dochiei", "sat"),
        createLoc("Satu Nou", "sat"),
        createLoc("Slobozia", "sat"),
    ]),
    createComuna("Valea Seacă", [
        createLoc("Valea Seacă", "sat"),
        createLoc("Cucova", "sat"),
    ]),
    createComuna("Vultureni", [
        createLoc("Vultureni", "sat"),
        createLoc("Bosia", "sat"),
        createLoc("Dădești", "sat"),
        createLoc("Dorneni", "sat"),
        createLoc("Ghilăvești", "sat"),
        createLoc("Godineștii de Jos", "sat"),
        createLoc("Godineștii de Sus", "sat"),
        createLoc("Lichitișeni", "sat"),
        createLoc("Medeleni", "sat"),
        createLoc("Năzărioaia", "sat"),
        createLoc("Reprivăț", "sat"),
        createLoc("Tomozia", "sat"),
        createLoc("Țigănești", "sat"),
        createLoc("Valea Lupului", "sat"),
        createLoc("Valea Merilor", "sat"),
        createLoc("Valea Salciei", "sat"),
    ]),
    createComuna("Zemeș", [
        createLoc("Zemeș", "sat"),
        createLoc("Bolătău", "sat"),
    ]),
									  
			
];
?>