<?php
$comune =[
    createComuna("Agăș", [
        createLoc("Agăș", "sat", createAdresaCompleta("sat Agăș, comuna Agăș, judetul BACĂU, România", "sat Agas, comuna Agas, judetul BACAU, Romania")),
        createLoc("Beleghet", "sat", createAdresaCompleta("sat Beleghet, comuna Agăș, judetul BACĂU, România", "sat Beleghet, comuna Agas, judetul BACAU, Romania")),
        createLoc("Coșnea", "sat", createAdresaCompleta("sat Coșnea, comuna Agăș, judetul BACĂU, România", "sat Cosnea, comuna Agas, judetul BACAU, Romania")),
        createLoc("Cotumba", "sat", createAdresaCompleta("sat Cotumba, comuna Agăș, judetul BACĂU, România", "sat Cotumba, comuna Agas, judetul BACAU, Romania")),
        createLoc("Diaconești", "sat", createAdresaCompleta("sat Diaconești, comuna Agăș, judetul BACĂU, România", "sat Diaconesti, comuna Agas, judetul BACAU, Romania")),
        createLoc("Goioasa", "sat", createAdresaCompleta("sat Goioasa, comuna Agăș, judetul BACĂU, România", "sat Goioasa, comuna Agas, judetul BACAU, Romania")),
        createLoc("Preluci", "sat", createAdresaCompleta("sat Preluci, comuna Agăș, judetul BACĂU, România", "sat Preluci, comuna Agas, judetul BACAU, Romania")),
        createLoc("Sulța", "sat", createAdresaCompleta("sat Sulța, comuna Agăș, judetul BACĂU, România", "sat Sulta, comuna Agas, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Agăș, judetul BACĂU, România", "comuna Agas, judetul BACAU, Romania")),
    createComuna("Ardeoani", [
        createLoc("Ardeoani", "sat", createAdresaCompleta("sat Ardeoani, comuna Ardeoani, judetul BACĂU, România", "sat Ardeoani, comuna Ardeoani, judetul BACAU, Romania")),
        createLoc("Leontinești", "sat", createAdresaCompleta("sat Leontinești, comuna Ardeoani, judetul BACĂU, România", "sat Leontinesti, comuna Ardeoani, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Ardeoani, judetul BACĂU, România", "comuna Ardeoani, judetul BACAU, Romania")),
    createComuna("Asău", [
        createLoc("Asău", "sat", createAdresaCompleta("sat Asău, comuna Asău, judetul BACĂU, România", "sat Asau, comuna Asau, judetul BACAU, Romania")),
        createLoc("Apa Asău", "sat", createAdresaCompleta("sat Apa Asău, comuna Asău, judetul BACĂU, România", "sat Apa Asau, comuna Asau, judetul BACAU, Romania")),
        createLoc("Ciobănuș", "sat", createAdresaCompleta("sat Ciobănuș, comuna Asău, judetul BACĂU, România", "sat Ciobanus, comuna Asau, judetul BACAU, Romania")),
        createLoc("Lunca Asău", "sat", createAdresaCompleta("sat Lunca Asău, comuna Asău, judetul BACĂU, România", "sat Lunca Asau, comuna Asau, judetul BACAU, Romania")),
        createLoc("Păltiniș", "sat", createAdresaCompleta("sat Păltiniș, comuna Asău, judetul BACĂU, România", "sat Paltinis, comuna Asau, judetul BACAU, Romania")),
        createLoc("Straja", "sat", createAdresaCompleta("sat Straja, comuna Asău, judetul BACĂU, România", "sat Straja, comuna Asau, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Asău, judetul BACĂU, România", "comuna Asau, judetul BACAU, Romania")),
    createComuna("Balcani", [
        createLoc("Balcani", "sat", createAdresaCompleta("sat Balcani, comuna Balcani, judetul BACĂU, România", "sat Balcani, comuna Balcani, judetul BACAU, Romania")),
        createLoc("Frumoasa", "sat", createAdresaCompleta("sat Frumoasa, comuna Balcani, judetul BACĂU, România", "sat Frumoasa, comuna Balcani, judetul BACAU, Romania")),
        createLoc("Ludași", "sat", createAdresaCompleta("sat Ludași, comuna Balcani, judetul BACĂU, România", "sat Ludasi, comuna Balcani, judetul BACAU, Romania")),
        createLoc("Schitu Frumoasa", "sat", createAdresaCompleta("sat Schitu Frumoasa, comuna Balcani, judetul BACĂU, România", "sat Schitu Frumoasa, comuna Balcani, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Balcani, judetul BACĂU, România", "comuna Balcani, judetul BACAU, Romania")),
    createComuna("Berești-Bistrița", [
        createLoc("Berești-Bistrița", "sat", createAdresaCompleta("sat Berești-Bistrița, comuna Berești-Bistrița, judetul BACĂU, România", "sat Beresti-Bistrita, comuna Beresti-Bistrita, judetul BACAU, Romania")),
        createLoc("Brad", "sat", createAdresaCompleta("sat Brad, comuna Berești-Bistrița, judetul BACĂU, România", "sat Brad, comuna Beresti-Bistrita, judetul BACAU, Romania")),
        createLoc("Climești", "sat", createAdresaCompleta("sat Climești, comuna Berești-Bistrița, judetul BACĂU, România", "sat Climesti, comuna Beresti-Bistrita, judetul BACAU, Romania")),
        createLoc("Pădureni", "sat", createAdresaCompleta("sat Pădureni, comuna Berești-Bistrița, judetul BACĂU, România", "sat Padureni, comuna Beresti-Bistrita, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Berești-Bistrița, judetul BACĂU, România", "comuna Beresti-Bistrita, judetul BACAU, Romania")),
    createComuna("Berești-Tazlău", [
        createLoc("Berești-Tazlău", "sat", createAdresaCompleta("sat Berești-Tazlău, comuna Berești-Tazlău, judetul BACĂU, România", "sat Beresti-Tazlau, comuna Beresti-Tazlau, judetul BACAU, Romania")),
        createLoc("Boșoteni", "sat", createAdresaCompleta("sat Boșoteni, comuna Berești-Tazlău, judetul BACĂU, România", "sat Bosoteni, comuna Beresti-Tazlau, judetul BACAU, Romania")),
        createLoc("Enăchești", "sat", createAdresaCompleta("sat Enăchești, comuna Berești-Tazlău, judetul BACĂU, România", "sat Enachesti, comuna Beresti-Tazlau, judetul BACAU, Romania")),
        createLoc("Prisaca", "sat", createAdresaCompleta("sat Prisaca, comuna Berești-Tazlău, judetul BACĂU, România", "sat Prisaca, comuna Beresti-Tazlau, judetul BACAU, Romania")),
        createLoc("Românești", "sat", createAdresaCompleta("sat Românești, comuna Berești-Tazlău, judetul BACĂU, România", "sat Romanesti, comuna Beresti-Tazlau, judetul BACAU, Romania")),
        createLoc("Tescani", "sat", createAdresaCompleta("sat Tescani, comuna Berești-Tazlău, judetul BACĂU, România", "sat Tescani, comuna Beresti-Tazlau, judetul BACAU, Romania")),
        createLoc("Turluianu", "sat", createAdresaCompleta("sat Turluianu, comuna Berești-Tazlău, judetul BACĂU, România", "sat Turluianu, comuna Beresti-Tazlau, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Berești-Tazlău, judetul BACĂU, România", "comuna Beresti-Tazlau, judetul BACAU, Romania")),
    createComuna("Berzunți", [
        createLoc("Berzunți", "sat", createAdresaCompleta("sat Berzunți, comuna Berzunți, judetul BACĂU, România", "sat Berzunti, comuna Berzunti, judetul BACAU, Romania")),
        createLoc("Buda", "sat", createAdresaCompleta("sat Buda, comuna Berzunți, judetul BACĂU, România", "sat Buda, comuna Berzunti, judetul BACAU, Romania")),
        createLoc("Dragomir", "sat", createAdresaCompleta("sat Dragomir, comuna Berzunți, judetul BACĂU, România", "sat Dragomir, comuna Berzunti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Berzunți, judetul BACĂU, România", "comuna Berzunti, judetul BACAU, Romania")),
    createComuna("Bârsănești", [
        createLoc("Bârsănești", "sat", createAdresaCompleta("sat Bârsănești, comuna Bârsănești, judetul BACĂU, România", "sat Barsanesti, comuna Barsanesti, judetul BACAU, Romania")),
        createLoc("Albele", "sat", createAdresaCompleta("sat Albele, comuna Bârsănești, judetul BACĂU, România", "sat Albele, comuna Barsanesti, judetul BACAU, Romania")),
        createLoc("Brătești", "sat", createAdresaCompleta("sat Brătești, comuna Bârsănești, judetul BACĂU, România", "sat Bratesti, comuna Barsanesti, judetul BACAU, Romania")),
        createLoc("Caraclău", "sat", createAdresaCompleta("sat Caraclău, comuna Bârsănești, judetul BACĂU, România", "sat Caraclau, comuna Barsanesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Bârsănești, judetul BACĂU, România", "comuna Barsanesti, judetul BACAU, Romania")),
    createComuna("Blăgești", [
        createLoc("Blăgești", "sat", createAdresaCompleta("sat Blăgești, comuna Blăgești, judetul BACĂU, România", "sat Blagesti, comuna Blagesti, judetul BACAU, Romania")),
        createLoc("Buda", "sat", createAdresaCompleta("sat Buda, comuna Blăgești, judetul BACĂU, România", "sat Buda, comuna Blagesti, judetul BACAU, Romania")),
        createLoc("Poiana Negustorului", "sat", createAdresaCompleta("sat Poiana Negustorului, comuna Blăgești, judetul BACĂU, România", "sat Poiana Negustorului, comuna Blagesti, judetul BACAU, Romania")),
        createLoc("Țârdenii Mari", "sat", createAdresaCompleta("sat Țârdenii Mari, comuna Blăgești, judetul BACĂU, România", "sat Tardenii Mari, comuna Blagesti, judetul BACAU, Romania")),
        createLoc("Valea lui Ion", "sat", createAdresaCompleta("sat Valea lui Ion, comuna Blăgești, judetul BACĂU, România", "sat Valea lui Ion, comuna Blagesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Blăgești, judetul BACĂU, România", "comuna Blagesti, judetul BACAU, Romania")),
    createComuna("Bogdănești", [
        createLoc("Bogdănești", "sat", createAdresaCompleta("sat Bogdănești, comuna Bogdănești, judetul BACĂU, România", "sat Bogdanesti, comuna Bogdanesti, judetul BACAU, Romania")),
        createLoc("Filipești", "sat", createAdresaCompleta("sat Filipești, comuna Bogdănești, judetul BACĂU, România", "sat Filipesti, comuna Bogdanesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Bogdănești, judetul BACĂU, România", "comuna Bogdanesti, judetul BACAU, Romania")),
	    createComuna("Brusturoasa", [
        createLoc("Brusturoasa", "sat", createAdresaCompleta("sat Brusturoasa, comuna Brusturoasa, judetul BACĂU, România", "sat Brusturoasa, comuna Brusturoasa, judetul BACAU, Romania")),
        createLoc("Buruieniș", "sat", createAdresaCompleta("sat Buruieniș, comuna Brusturoasa, judetul BACĂU, România", "sat Buruienis, comuna Brusturoasa, judetul BACAU, Romania")),
        createLoc("Buruienișu de Sus", "sat", createAdresaCompleta("sat Buruienișu de Sus, comuna Brusturoasa, judetul BACĂU, România", "sat Buruienisu de Sus, comuna Brusturoasa, judetul BACAU, Romania")),
        createLoc("Camenca", "sat", createAdresaCompleta("sat Camenca, comuna Brusturoasa, judetul BACĂU, România", "sat Camenca, comuna Brusturoasa, judetul BACAU, Romania")),
        createLoc("Cuchiniș", "sat", createAdresaCompleta("sat Cuchiniș, comuna Brusturoasa, judetul BACĂU, România", "sat Cuchinis, comuna Brusturoasa, judetul BACAU, Romania")),
        createLoc("Hângănești", "sat", createAdresaCompleta("sat Hângănești, comuna Brusturoasa, judetul BACĂU, România", "sat Hanganesti, comuna Brusturoasa, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Brusturoasa, judetul BACĂU, România", "comuna Brusturoasa, judetul BACAU, Romania")),
    createComuna("Buciumi", [
        createLoc("Buciumi", "sat", createAdresaCompleta("sat Buciumi, comuna Buciumi, judetul BACĂU, România", "sat Buciumi, comuna Buciumi, judetul BACAU, Romania")),
        createLoc("Răcăuți", "sat", createAdresaCompleta("sat Răcăuți, comuna Buciumi, judetul BACĂU, România", "sat Racauti, comuna Buciumi, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Buciumi, judetul BACĂU, România", "comuna Buciumi, judetul BACAU, Romania")),
    createComuna("Buhoci", [
        createLoc("Buhoci", "sat", createAdresaCompleta("sat Buhoci, comuna Buhoci, judetul BACĂU, România", "sat Buhoci, comuna Buhoci, judetul BACAU, Romania")),
        createLoc("Bijghir", "sat", createAdresaCompleta("sat Bijghir, comuna Buhoci, judetul BACĂU, România", "sat Bijghir, comuna Buhoci, judetul BACAU, Romania")),
        createLoc("Buhocel", "sat", createAdresaCompleta("sat Buhocel, comuna Buhoci, judetul BACĂU, România", "sat Buhocel, comuna Buhoci, judetul BACAU, Romania")),
        createLoc("Coteni", "sat", createAdresaCompleta("sat Coteni, comuna Buhoci, judetul BACĂU, România", "sat Coteni, comuna Buhoci, judetul BACAU, Romania")),
        createLoc("Dospinești", "sat", createAdresaCompleta("sat Dospinești, comuna Buhoci, judetul BACĂU, România", "sat Dospinesti, comuna Buhoci, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Buhoci, judetul BACĂU, România", "comuna Buhoci, judetul BACAU, Romania")),
    createComuna("Cașin", [
        createLoc("Cașin", "sat", createAdresaCompleta("sat Cașin, comuna Cașin, judetul BACĂU, România", "sat Casin, comuna Casin, judetul BACAU, Romania")),
        createLoc("Curița", "sat", createAdresaCompleta("sat Curița, comuna Cașin, judetul BACĂU, România", "sat Curita, comuna Casin, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Cașin, judetul BACĂU, România", "comuna Casin, judetul BACAU, Romania")),
    createComuna("Căiuți", [
        createLoc("Căiuți", "sat", createAdresaCompleta("sat Căiuți, comuna Căiuți, judetul BACĂU, România", "sat Caiuti, comuna Caiuti, judetul BACAU, Romania")),
        createLoc("Blidari", "sat", createAdresaCompleta("sat Blidari, comuna Căiuți, judetul BACĂU, România", "sat Blidari, comuna Caiuti, judetul BACAU, Romania")),
        createLoc("Boiștea", "sat", createAdresaCompleta("sat Boiștea, comuna Căiuți, judetul BACĂU, România", "sat Boistea, comuna Caiuti, judetul BACAU, Romania")),
        createLoc("Florești", "sat", createAdresaCompleta("sat Florești, comuna Căiuți, judetul BACĂU, România", "sat Floresti, comuna Caiuti, judetul BACAU, Romania")),
        createLoc("Heltiu", "sat", createAdresaCompleta("sat Heltiu, comuna Căiuți, judetul BACĂU, România", "sat Heltiu, comuna Caiuti, judetul BACAU, Romania")),
        createLoc("Mărcești", "sat", createAdresaCompleta("sat Mărcești, comuna Căiuți, judetul BACĂU, România", "sat Marcesti, comuna Caiuti, judetul BACAU, Romania")),
        createLoc("Popeni", "sat", createAdresaCompleta("sat Popeni, comuna Căiuți, judetul BACĂU, România", "sat Popeni, comuna Caiuti, judetul BACAU, Romania")),
        createLoc("Pralea", "sat", createAdresaCompleta("sat Pralea, comuna Căiuți, judetul BACĂU, România", "sat Pralea, comuna Caiuti, judetul BACAU, Romania")),
        createLoc("Vrânceni", "sat", createAdresaCompleta("sat Vrânceni, comuna Căiuți, judetul BACĂU, România", "sat Vranceni, comuna Caiuti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Căiuți, judetul BACĂU, România", "comuna Caiuti, judetul BACAU, Romania")),
    createComuna("Cleja", [
        createLoc("Cleja", "sat", createAdresaCompleta("sat Cleja, comuna Cleja, judetul BACĂU, România", "sat Cleja, comuna Cleja, judetul BACAU, Romania")),
        createLoc("Somușca", "sat", createAdresaCompleta("sat Somușca, comuna Cleja, judetul BACĂU, România", "sat Somusca, comuna Cleja, judetul BACAU, Romania")),
        createLoc("Valea Mică", "sat", createAdresaCompleta("sat Valea Mică, comuna Cleja, judetul BACĂU, România", "sat Valea Mica, comuna Cleja, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Cleja, judetul BACĂU, România", "comuna Cleja, judetul BACAU, Romania")),
    createComuna("Colonești", [
        createLoc("Colonești", "sat", createAdresaCompleta("sat Colonești, comuna Colonești, judetul BACĂU, România", "sat Colonesti, comuna Colonesti, judetul BACAU, Romania")),
        createLoc("Călini", "sat", createAdresaCompleta("sat Călini, comuna Colonești, judetul BACĂU, România", "sat Calini, comuna Colonesti, judetul BACAU, Romania")),
        createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Colonești, judetul BACĂU, România", "sat Poiana, comuna Colonesti, judetul BACAU, Romania")),
        createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Colonești, judetul BACĂU, România", "sat Satu Nou, comuna Colonesti, judetul BACAU, Romania")),
        createLoc("Spria", "sat", createAdresaCompleta("sat Spria, comuna Colonești, judetul BACĂU, România", "sat Spria, comuna Colonesti, judetul BACAU, Romania")),
        createLoc("Valea Mare", "sat", createAdresaCompleta("sat Valea Mare, comuna Colonești, judetul BACĂU, România", "sat Valea Mare, comuna Colonesti, judetul BACAU, Romania")),
        createLoc("Zăpodia", "sat", createAdresaCompleta("sat Zăpodia, comuna Colonești, judetul BACĂU, România", "sat Zapodia, comuna Colonesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Colonești, judetul BACĂU, România", "comuna Colonesti, judetul BACAU, Romania")),
    createComuna("Corbasca", [
        createLoc("Corbasca", "sat", createAdresaCompleta("sat Corbasca, comuna Corbasca, judetul BACĂU, România", "sat Corbasca, comuna Corbasca, judetul BACAU, Romania")),
        createLoc("Băcioiu", "sat", createAdresaCompleta("sat Băcioiu, comuna Corbasca, judetul BACĂU, România", "sat Bacioiu, comuna Corbasca, judetul BACAU, Romania")),
        createLoc("Marvila", "sat", createAdresaCompleta("sat Marvila, comuna Corbasca, judetul BACĂU, România", "sat Marvila, comuna Corbasca, judetul BACAU, Romania")),
        createLoc("Pogleț", "sat", createAdresaCompleta("sat Pogleț, comuna Corbasca, judetul BACĂU, România", "sat Poglet, comuna Corbasca, judetul BACAU, Romania")),
        createLoc("Rogoaza", "sat", createAdresaCompleta("sat Rogoaza, comuna Corbasca, judetul BACĂU, România", "sat Rogoaza, comuna Corbasca, judetul BACAU, Romania")),
        createLoc("Scărișoara", "sat", createAdresaCompleta("sat Scărișoara, comuna Corbasca, judetul BACĂU, România", "sat Scarisoara, comuna Corbasca, judetul BACAU, Romania")),
        createLoc("Vâlcele", "sat", createAdresaCompleta("sat Vâlcele, comuna Corbasca, judetul BACĂU, România", "sat Valcele, comuna Corbasca, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Corbasca, judetul BACĂU, România", "comuna Corbasca, judetul BACAU, Romania")),
    createComuna("Coțofănești", [
        createLoc("Coțofănești", "sat", createAdresaCompleta("sat Coțofănești, comuna Coțofănești, judetul BACĂU, România", "sat Cotofanesti, comuna Cotofanesti, judetul BACAU, Romania")),
        createLoc("Bâlca", "sat", createAdresaCompleta("sat Bâlca, comuna Coțofănești, judetul BACĂU, România", "sat Balca, comuna Cotofanesti, judetul BACAU, Romania")),
        createLoc("Boiștea de Jos", "sat", createAdresaCompleta("sat Boiștea de Jos, comuna Coțofănești, judetul BACĂU, România", "sat Boistea de Jos, comuna Cotofanesti, judetul BACAU, Romania")),
        createLoc("Borșani", "sat", createAdresaCompleta("sat Borșani, comuna Coțofănești, judetul BACĂU, România", "sat Borsani, comuna Cotofanesti, judetul BACAU, Romania")),
        createLoc("Tămășoaia", "sat", createAdresaCompleta("sat Tămășoaia, comuna Coțofănești, judetul BACĂU, România", "sat Tamasoaia, comuna Cotofanesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Coțofănești, judetul BACĂU, România", "comuna Cotofanesti, judetul BACAU, Romania")),
    createComuna("Dămienești", [
        createLoc("Dămienești", "sat", createAdresaCompleta("sat Dămienești, comuna Dămienești, judetul BACĂU, România", "sat Damienesti, comuna Damienesti, judetul BACAU, Romania")),
        createLoc("Călugăreni", "sat", createAdresaCompleta("sat Călugăreni, comuna Dămienești, judetul BACĂU, România", "sat Calugareni, comuna Damienesti, judetul BACAU, Romania")),
        createLoc("Drăgești", "sat", createAdresaCompleta("sat Drăgești, comuna Dămienești, judetul BACĂU, România", "sat Dragesti, comuna Damienesti, judetul BACAU, Romania")),
        createLoc("Pădureni", "sat", createAdresaCompleta("sat Pădureni, comuna Dămienești, judetul BACĂU, România", "sat Padureni, comuna Damienesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Dămienești, judetul BACĂU, România", "comuna Damienesti, judetul BACAU, Romania")),
    createComuna("Dealu Morii", [
        createLoc("Dealu Morii", "sat", createAdresaCompleta("sat Dealu Morii, comuna Dealu Morii, judetul BACĂU, România", "sat Dealu Morii, comuna Dealu Morii, judetul BACAU, Romania")),
        createLoc("Banca", "sat", createAdresaCompleta("sat Banca, comuna Dealu Morii, judetul BACĂU, România", "sat Banca, comuna Dealu Morii, judetul BACAU, Romania")),
        createLoc("Bălănești", "sat", createAdresaCompleta("sat Bălănești, comuna Dealu Morii, judetul BACĂU, România", "sat Balanesti, comuna Dealu Morii, judetul BACAU, Romania")),
        createLoc("Blaga", "sat", createAdresaCompleta("sat Blaga, comuna Dealu Morii, judetul BACĂU, România", "sat Blaga, comuna Dealu Morii, judetul BACAU, Romania")),
        createLoc("Boboș", "sat", createAdresaCompleta("sat Boboș, comuna Dealu Morii, judetul BACĂU, România", "sat Bobos, comuna Dealu Morii, judetul BACAU, Romania")),
        createLoc("Bodeasa", "sat", createAdresaCompleta("sat Bodeasa, comuna Dealu Morii, judetul BACĂU, România", "sat Bodeasa, comuna Dealu Morii, judetul BACAU, Romania")),
        createLoc("Bostănești", "sat", createAdresaCompleta("sat Bostănești, comuna Dealu Morii, judetul BACĂU, România", "sat Bostanesti, comuna Dealu Morii, judetul BACAU, Romania")),
        createLoc("Calapodești", "sat", createAdresaCompleta("sat Calapodești, comuna Dealu Morii, judetul BACĂU, România", "sat Calapodesti, comuna Dealu Morii, judetul BACAU, Romania")),
        createLoc("Căuia", "sat", createAdresaCompleta("sat Căuia, comuna Dealu Morii, judetul BACĂU, România", "sat Cauia, comuna Dealu Morii, judetul BACAU, Romania")),
        createLoc("Dorofei", "sat", createAdresaCompleta("sat Dorofei, comuna Dealu Morii, judetul BACĂU, România", "sat Dorofei, comuna Dealu Morii, judetul BACAU, Romania")),
        createLoc("Ghionoaia", "sat", createAdresaCompleta("sat Ghionoaia, comuna Dealu Morii, judetul BACĂU, România", "sat Ghionoaia, comuna Dealu Morii, judetul BACAU, Romania")),
        createLoc("Grădești", "sat", createAdresaCompleta("sat Grădești, comuna Dealu Morii, judetul BACĂU, România", "sat Gradesti, comuna Dealu Morii, judetul BACAU, Romania")),
        createLoc("Negulești", "sat", createAdresaCompleta("sat Negulești, comuna Dealu Morii, judetul BACĂU, România", "sat Negulesti, comuna Dealu Morii, judetul BACAU, Romania")),
        createLoc("Tăvădărești", "sat", createAdresaCompleta("sat Tăvădărești, comuna Dealu Morii, judetul BACĂU, România", "sat Tavadaresti, comuna Dealu Morii, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Dealu Morii, judetul BACĂU, România", "comuna Dealu Morii, judetul BACAU, Romania")),
    createComuna("Dofteana", [
        createLoc("Dofteana", "sat", createAdresaCompleta("sat Dofteana, comuna Dofteana, judetul BACĂU, România", "sat Dofteana, comuna Dofteana, judetul BACAU, Romania")),
        createLoc("Bogata", "sat", createAdresaCompleta("sat Bogata, comuna Dofteana, judetul BACĂU, România", "sat Bogata, comuna Dofteana, judetul BACAU, Romania")),
        createLoc("Cucuieți", "sat", createAdresaCompleta("sat Cucuieți, comuna Dofteana, judetul BACĂU, România", "sat Cucuieti, comuna Dofteana, judetul BACAU, Romania")),
        createLoc("Hăghiac", "sat", createAdresaCompleta("sat Hăghiac, comuna Dofteana, judetul BACĂU, România", "sat Haghiac, comuna Dofteana, judetul BACAU, Romania")),
        createLoc("Larga", "sat", createAdresaCompleta("sat Larga, comuna Dofteana, judetul BACĂU, România", "sat Larga, comuna Dofteana, judetul BACAU, Romania")),
        createLoc("Seaca", "sat", createAdresaCompleta("sat Seaca, comuna Dofteana, judetul BACĂU, România", "sat Seaca, comuna Dofteana, judetul BACAU, Romania")),
        createLoc("Ștefan Vodă", "sat", createAdresaCompleta("sat Ștefan Vodă, comuna Dofteana, judetul BACĂU, România", "sat Stefan Voda, comuna Dofteana, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Dofteana, judetul BACĂU, România", "comuna Dofteana, judetul BACAU, Romania")),
    createComuna("Faraoani", [
        createLoc("Faraoani", "sat", createAdresaCompleta("sat Faraoani, comuna Faraoani, judetul BACĂU, România", "sat Faraoani, comuna Faraoani, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Faraoani, judetul BACĂU, România", "comuna Faraoani, judetul BACAU, Romania")),
    createComuna("Filipeni", [
        createLoc("Filipeni", "sat", createAdresaCompleta("sat Filipeni, comuna Filipeni, judetul BACĂU, România", "sat Filipeni, comuna Filipeni, judetul BACAU, Romania")),
        createLoc("Bălaia", "sat", createAdresaCompleta("sat Bălaia, comuna Filipeni, judetul BACĂU, România", "sat Balaia, comuna Filipeni, judetul BACAU, Romania")),
        createLoc("Brad", "sat", createAdresaCompleta("sat Brad, comuna Filipeni, judetul BACĂU, România", "sat Brad, comuna Filipeni, judetul BACAU, Romania")),
        createLoc("Fruntești", "sat", createAdresaCompleta("sat Fruntești, comuna Filipeni, judetul BACĂU, România", "sat Fruntesti, comuna Filipeni, judetul BACAU, Romania")),
        createLoc("Mărăști", "sat", createAdresaCompleta("sat Mărăști, comuna Filipeni, judetul BACĂU, România", "sat Marasti, comuna Filipeni, judetul BACAU, Romania")),
        createLoc("Pădureni", "sat", createAdresaCompleta("sat Pădureni, comuna Filipeni, judetul BACĂU, România", "sat Padureni, comuna Filipeni, judetul BACAU, Romania")),
        createLoc("Slobozia", "sat", createAdresaCompleta("sat Slobozia, comuna Filipeni, judetul BACĂU, România", "sat Slobozia, comuna Filipeni, judetul BACAU, Romania")),
        createLoc("Valea Boțului", "sat", createAdresaCompleta("sat Valea Boțului, comuna Filipeni, judetul BACĂU, România", "sat Valea Botului, comuna Filipeni, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Filipeni, judetul BACĂU, România", "comuna Filipeni, judetul BACAU, Romania")),
    createComuna("Filipești", [
        createLoc("Filipești", "sat", createAdresaCompleta("sat Filipești, comuna Filipești, judetul BACĂU, România", "sat Filipesti, comuna Filipesti, judetul BACAU, Romania")),
        createLoc("Boanța", "sat", createAdresaCompleta("sat Boanța, comuna Filipești, judetul BACĂU, România", "sat Boanta, comuna Filipesti, judetul BACAU, Romania")),
        createLoc("Cârligi", "sat", createAdresaCompleta("sat Cârligi, comuna Filipești, judetul BACĂU, România", "sat Carligi, comuna Filipesti, judetul BACAU, Romania")),
        createLoc("Cornești", "sat", createAdresaCompleta("sat Cornești, comuna Filipești, judetul BACĂU, România", "sat Cornesti, comuna Filipesti, judetul BACAU, Romania")),
        createLoc("Cotu Grosului", "sat", createAdresaCompleta("sat Cotu Grosului, comuna Filipești, judetul BACĂU, România", "sat Cotu Grosului, comuna Filipesti, judetul BACAU, Romania")),
        createLoc("Galbeni", "sat", createAdresaCompleta("sat Galbeni, comuna Filipești, judetul BACĂU, România", "sat Galbeni, comuna Filipesti, judetul BACAU, Romania")),
        createLoc("Hârlești", "sat", createAdresaCompleta("sat Hârlești, comuna Filipești, judetul BACĂU, România", "sat Harlesti, comuna Filipesti, judetul BACAU, Romania")),
        createLoc("Onișcani", "sat", createAdresaCompleta("sat Onișcani, comuna Filipești, judetul BACĂU, România", "sat Oniscani, comuna Filipesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Filipești, judetul BACĂU, România", "comuna Filipesti, judetul BACAU, Romania")),
    createComuna("Găiceana", [
        createLoc("Găiceana", "sat", createAdresaCompleta("sat Găiceana, comuna Găiceana, judetul BACĂU, România", "sat Gaiceana, comuna Gaiceana, judetul BACAU, Romania")),
        createLoc("Arini", "sat", createAdresaCompleta("sat Arini, comuna Găiceana, judetul BACĂU, România", "sat Arini, comuna Gaiceana, judetul BACAU, Romania")),
        createLoc("Huțu", "sat", createAdresaCompleta("sat Huțu, comuna Găiceana, judetul BACĂU, România", "sat Hutu, comuna Gaiceana, judetul BACAU, Romania")),
        createLoc("Popești", "sat", createAdresaCompleta("sat Popești, comuna Găiceana, judetul BACĂU, România", "sat Popesti, comuna Gaiceana, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Găiceana, judetul BACĂU, România", "comuna Gaiceana, judetul BACAU, Romania")),
    createComuna("Ghimeș-Făget", [
        createLoc("Făget", "sat", createAdresaCompleta("sat Făget, comuna Ghimeș-Făget, judetul BACĂU, România", "sat Faget, comuna Ghimes-Faget, judetul BACAU, Romania")),
        createLoc("Bolovăniș", "sat", createAdresaCompleta("sat Bolovăniș, comuna Ghimeș-Făget, judetul BACĂU, România", "sat Bolovanis, comuna Ghimes-Faget, judetul BACAU, Romania")),
        createLoc("Făgetu de Sus", "sat", createAdresaCompleta("sat Făgetu de Sus, comuna Ghimeș-Făget, judetul BACĂU, România", "sat Fagetu de Sus, comuna Ghimes-Faget, judetul BACAU, Romania")),
        createLoc("Ghimeș", "sat", createAdresaCompleta("sat Ghimeș, comuna Ghimeș-Făget, judetul BACĂU, România", "sat Ghimes, comuna Ghimes-Faget, judetul BACAU, Romania")),
        createLoc("Răchitiș", "sat", createAdresaCompleta("sat Răchitiș, comuna Ghimeș-Făget, judetul BACĂU, România", "sat Rachitis, comuna Ghimes-Faget, judetul BACAU, Romania")),
        createLoc("Tărhăuși", "sat", createAdresaCompleta("sat Tărhăuși, comuna Ghimeș-Făget, judetul BACĂU, România", "sat Tarhausi, comuna Ghimes-Faget, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Ghimeș-Făget, judetul BACĂU, România", "comuna Ghimes-Faget, judetul BACAU, Romania")),
    createComuna("Gioseni", [
        createLoc("Gioseni", "sat", createAdresaCompleta("sat Gioseni, comuna Gioseni, judetul BACĂU, România", "sat Gioseni, comuna Gioseni, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Gioseni, judetul BACĂU, România", "comuna Gioseni, judetul BACAU, Romania")),
    createComuna("Gârleni", [
        createLoc("Gârlenii de Sus", "sat", createAdresaCompleta("sat Gârlenii de Sus, comuna Gârleni, judetul BACĂU, România", "sat Garlenii de Sus, comuna Garleni, judetul BACAU, Romania")),
        createLoc("Gârleni", "sat", createAdresaCompleta("sat Gârleni, comuna Gârleni, judetul BACĂU, România", "sat Garleni, comuna Garleni, judetul BACAU, Romania")),
        createLoc("Lespezi", "sat", createAdresaCompleta("sat Lespezi, comuna Gârleni, judetul BACĂU, România", "sat Lespezi, comuna Garleni, judetul BACAU, Romania")),
        createLoc("Șurina", "sat", createAdresaCompleta("sat Șurina, comuna Gârleni, judetul BACĂU, România", "sat Surina, comuna Garleni, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Gârleni, judetul BACĂU, România", "comuna Garleni, judetul BACAU, Romania")),
    createComuna("Glăvănești", [
        createLoc("Glăvănești", "sat", createAdresaCompleta("sat Glăvănești, comuna Glăvănești, judetul BACĂU, România", "sat Glavanesti, comuna Glavanesti, judetul BACAU, Romania")),
        createLoc("Frumușelu", "sat", createAdresaCompleta("sat Frumușelu, comuna Glăvănești, judetul BACĂU, România", "sat Frumuselu, comuna Glavanesti, judetul BACAU, Romania")),
        createLoc("Muncelu", "sat", createAdresaCompleta("sat Muncelu, comuna Glăvănești, judetul BACĂU, România", "sat Muncelu, comuna Glavanesti, judetul BACAU, Romania")),
        createLoc("Putredeni", "sat", createAdresaCompleta("sat Putredeni, comuna Glăvănești, judetul BACĂU, România", "sat Putredeni, comuna Glavanesti, judetul BACAU, Romania")),
        createLoc("Răzeșu", "sat", createAdresaCompleta("sat Răzeșu, comuna Glăvănești, judetul BACĂU, România", "sat Razesu, comuna Glavanesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Glăvănești, judetul BACĂU, România", "comuna Glavanesti, judetul BACAU, Romania")),
    createComuna("Gura Văii", [
        createLoc("Gura Văii", "sat", createAdresaCompleta("sat Gura Văii, comuna Gura Văii, judetul BACĂU, România", "sat Gura Vaii, comuna Gura Vaii, judetul BACAU, Romania")),
        createLoc("Capăta", "sat", createAdresaCompleta("sat Capăta, comuna Gura Văii, judetul BACĂU, România", "sat Capata, comuna Gura Vaii, judetul BACAU, Romania")),
        createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, comuna Gura Văii, judetul BACĂU, România", "sat Dumbrava, comuna Gura Vaii, judetul BACAU, Romania")),
        createLoc("Motocești", "sat", createAdresaCompleta("sat Motocești, comuna Gura Văii, judetul BACĂU, România", "sat Motocesti, comuna Gura Vaii, judetul BACAU, Romania")),
        createLoc("Păltinata", "sat", createAdresaCompleta("sat Păltinata, comuna Gura Văii, judetul BACĂU, România", "sat Paltinata, comuna Gura Vaii, judetul BACAU, Romania")),
        createLoc("Temelia", "sat", createAdresaCompleta("sat Temelia, comuna Gura Văii, judetul BACĂU, România", "sat Temelia, comuna Gura Vaii, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Gura Văii, judetul BACĂU, România", "comuna Gura Vaii, judetul BACAU, Romania")),
    createComuna("Helegiu", [
        createLoc("Helegiu", "sat", createAdresaCompleta("sat Helegiu, comuna Helegiu, judetul BACĂU, România", "sat Helegiu, comuna Helegiu, judetul BACAU, Romania")),
        createLoc("Brătila", "sat", createAdresaCompleta("sat Brătila, comuna Helegiu, judetul BACĂU, România", "sat Bratila, comuna Helegiu, judetul BACAU, Romania")),
        createLoc("Deleni", "sat", createAdresaCompleta("sat Deleni, comuna Helegiu, judetul BACĂU, România", "sat Deleni, comuna Helegiu, judetul BACAU, Romania")),
        createLoc("Drăgugești", "sat", createAdresaCompleta("sat Drăgugești, comuna Helegiu, judetul BACĂU, România", "sat Dragugesti, comuna Helegiu, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Helegiu, judetul BACĂU, România", "comuna Helegiu, judetul BACAU, Romania")),
    createComuna("Hemeiuș", [
        createLoc("Hemeiuș", "sat", createAdresaCompleta("sat Hemeiuș, comuna Hemeiuș, judetul BACĂU, România", "sat Hemeius, comuna Hemeius, judetul BACAU, Romania")),
        createLoc("Fântânele", "sat", createAdresaCompleta("sat Fântânele, comuna Hemeiuș, judetul BACĂU, România", "sat Fantanele, comuna Hemeius, judetul BACAU, Romania")),
        createLoc("Lilieci", "sat", createAdresaCompleta("sat Lilieci, comuna Hemeiuș, judetul BACĂU, România", "sat Lilieci, comuna Hemeius, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Hemeiuș, judetul BACĂU, România", "comuna Hemeius, judetul BACAU, Romania")),
    createComuna("Horgești", [
        createLoc("Horgești", "sat", createAdresaCompleta("sat Horgești, comuna Horgești, judetul BACĂU, România", "sat Horgesti, comuna Horgesti, judetul BACAU, Romania")),
        createLoc("Bazga", "sat", createAdresaCompleta("sat Bazga, comuna Horgești, judetul BACĂU, România", "sat Bazga, comuna Horgesti, judetul BACAU, Romania")),
        createLoc("Galeri", "sat", createAdresaCompleta("sat Galeri, comuna Horgești, judetul BACĂU, România", "sat Galeri, comuna Horgesti, judetul BACAU, Romania")),
        createLoc("Mărăscu", "sat", createAdresaCompleta("sat Mărăscu, comuna Horgești, judetul BACĂU, România", "sat Marascu, comuna Horgesti, judetul BACAU, Romania")),
        createLoc("Răcătău-Răzeși", "sat", createAdresaCompleta("sat Răcătău-Răzeși, comuna Horgești, judetul BACĂU, România", "sat Racatau-Razesi, comuna Horgesti, judetul BACAU, Romania")),
        createLoc("Răcătău de Jos", "sat", createAdresaCompleta("sat Răcătău de Jos, comuna Horgești, judetul BACĂU, România", "sat Racatau de Jos, comuna Horgesti, judetul BACAU, Romania")),
        createLoc("Recea", "sat", createAdresaCompleta("sat Recea, comuna Horgești, judetul BACĂU, România", "sat Recea, comuna Horgesti, judetul BACAU, Romania")),
        createLoc("Sohodor", "sat", createAdresaCompleta("sat Sohodor, comuna Horgești, judetul BACĂU, România", "sat Sohodor, comuna Horgesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Horgești, judetul BACĂU, România", "comuna Horgesti, judetul BACAU, Romania")),
    createComuna("Huruiești", [
        createLoc("Huruiești", "sat", createAdresaCompleta("sat Huruiești, comuna Huruiești, judetul BACĂU, România", "sat Huruiesti, comuna Huruiesti, judetul BACAU, Romania")),
        createLoc("Căpotești", "sat", createAdresaCompleta("sat Căpotești, comuna Huruiești, judetul BACĂU, România", "sat Capotesti, comuna Huruiesti, judetul BACAU, Romania")),
        createLoc("Florești", "sat", createAdresaCompleta("sat Florești, comuna Huruiești, judetul BACĂU, România", "sat Floresti, comuna Huruiesti, judetul BACAU, Romania")),
        createLoc("Fundoaia", "sat", createAdresaCompleta("sat Fundoaia, comuna Huruiești, judetul BACĂU, România", "sat Fundoaia, comuna Huruiesti, judetul BACAU, Romania")),
        createLoc("Ocheni", "sat", createAdresaCompleta("sat Ocheni, comuna Huruiești, judetul BACĂU, România", "sat Ocheni, comuna Huruiesti, judetul BACAU, Romania")),
        createLoc("Perchiu", "sat", createAdresaCompleta("sat Perchiu, comuna Huruiești, judetul BACĂU, România", "sat Perchiu, comuna Huruiesti, judetul BACAU, Romania")),
        createLoc("Prădaiș", "sat", createAdresaCompleta("sat Prădaiș, comuna Huruiești, judetul BACĂU, România", "sat Pradais, comuna Huruiesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Huruiești, judetul BACĂU, România", "comuna Huruiesti, judetul BACAU, Romania")),
    createComuna("Itești", [
        createLoc("Itești", "sat", createAdresaCompleta("sat Itești, comuna Itești, judetul BACĂU, România", "sat Itesti, comuna Itesti, judetul BACAU, Romania")),
        createLoc("Ciumași", "sat", createAdresaCompleta("sat Ciumași, comuna Itești, judetul BACĂU, România", "sat Ciumasi, comuna Itesti, judetul BACAU, Romania")),
        createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, comuna Itești, judetul BACĂU, România", "sat Dumbrava, comuna Itesti, judetul BACAU, Romania")),
        createLoc("Făgețel", "sat", createAdresaCompleta("sat Făgețel, comuna Itești, judetul BACĂU, România", "sat Fagetel, comuna Itesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Itești, judetul BACĂU, România", "comuna Itesti, judetul BACAU, Romania")),
    createComuna("Izvoru Berheciului", [
        createLoc("Izvoru Berheciului", "sat", createAdresaCompleta("sat Izvoru Berheciului, comuna Izvoru Berheciului, judetul BACĂU, România", "sat Izvoru Berheciului, comuna Izvoru Berheciului, judetul BACAU, Romania")),
        createLoc("Antohești", "sat", createAdresaCompleta("sat Antohești, comuna Izvoru Berheciului, judetul BACĂU, România", "sat Antohesti, comuna Izvoru Berheciului, judetul BACAU, Romania")),
        createLoc("Băimac", "sat", createAdresaCompleta("sat Băimac, comuna Izvoru Berheciului, judetul BACĂU, România", "sat Baimac, comuna Izvoru Berheciului, judetul BACAU, Romania")),
        createLoc("Făghieni", "sat", createAdresaCompleta("sat Făghieni, comuna Izvoru Berheciului, judetul BACĂU, România", "sat Faghieni, comuna Izvoru Berheciului, judetul BACAU, Romania")),
        createLoc("Obârșia", "sat", createAdresaCompleta("sat Obârșia, comuna Izvoru Berheciului, judetul BACĂU, România", "sat Obarsia, comuna Izvoru Berheciului, judetul BACAU, Romania")),
        createLoc("Oțelești", "sat", createAdresaCompleta("sat Oțelești, comuna Izvoru Berheciului, judetul BACĂU, România", "sat Otelesti, comuna Izvoru Berheciului, judetul BACAU, Romania")),
        createLoc("Pădureni", "sat", createAdresaCompleta("sat Pădureni, comuna Izvoru Berheciului, judetul BACĂU, România", "sat Padureni, comuna Izvoru Berheciului, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Izvoru Berheciului, judetul BACĂU, România", "comuna Izvoru Berheciului, judetul BACAU, Romania")),
    createComuna("Letea Veche", [
        createLoc("Letea Veche", "sat", createAdresaCompleta("sat Letea Veche, comuna Letea Veche, judetul BACĂU, România", "sat Letea Veche, comuna Letea Veche, judetul BACAU, Romania")),
        createLoc("Holt", "sat", createAdresaCompleta("sat Holt, comuna Letea Veche, judetul BACĂU, România", "sat Holt, comuna Letea Veche, judetul BACAU, Romania")),
        createLoc("Radomirești", "sat", createAdresaCompleta("sat Radomirești, comuna Letea Veche, judetul BACĂU, România", "sat Radomiresti, comuna Letea Veche, judetul BACAU, Romania")),
        createLoc("Ruși-Ciutea", "sat", createAdresaCompleta("sat Ruși-Ciutea, comuna Letea Veche, judetul BACĂU, România", "sat Rusi-Ciutea, comuna Letea Veche, judetul BACAU, Romania")),
        createLoc("Siretu", "sat", createAdresaCompleta("sat Siretu, comuna Letea Veche, judetul BACĂU, România", "sat Siretu, comuna Letea Veche, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Letea Veche, judetul BACĂU, România", "comuna Letea Veche, judetul BACAU, Romania")),
    createComuna("Lipova", [
        createLoc("Lipova", "sat", createAdresaCompleta("sat Lipova, comuna Lipova, judetul BACĂU, România", "sat Lipova, comuna Lipova, judetul BACAU, Romania")),
        createLoc("Mâlosu", "sat", createAdresaCompleta("sat Mâlosu, comuna Lipova, judetul BACĂU, România", "sat Malosu, comuna Lipova, judetul BACAU, Romania")),
        createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Lipova, judetul BACĂU, România", "sat Satu Nou, comuna Lipova, judetul BACAU, Romania")),
        createLoc("Valea Caselor", "sat", createAdresaCompleta("sat Valea Caselor, comuna Lipova, judetul BACĂU, România", "sat Valea Caselor, comuna Lipova, judetul BACAU, Romania")),
        createLoc("Valea Hogei", "sat", createAdresaCompleta("sat Valea Hogei, comuna Lipova, judetul BACĂU, România", "sat Valea Hogei, comuna Lipova, judetul BACAU, Romania")),
        createLoc("Valea Mărului", "sat", createAdresaCompleta("sat Valea Mărului, comuna Lipova, judetul BACĂU, România", "sat Valea Marului, comuna Lipova, judetul BACAU, Romania")),
        createLoc("Valea Moșneagului", "sat", createAdresaCompleta("sat Valea Moșneagului, comuna Lipova, judetul BACĂU, România", "sat Valea Mosneagului, comuna Lipova, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Lipova, judetul BACĂU, România", "comuna Lipova, judetul BACAU, Romania")),
    createComuna("Livezi", [
        createLoc("Livezi", "sat", createAdresaCompleta("sat Livezi, comuna Livezi, judetul BACĂU, România", "sat Livezi, comuna Livezi, judetul BACAU, Romania")),
        createLoc("Bălăneasa", "sat", createAdresaCompleta("sat Bălăneasa, comuna Livezi, judetul BACĂU, România", "sat Balaneasa, comuna Livezi, judetul BACAU, Romania")),
        createLoc("Orășa", "sat", createAdresaCompleta("sat Orășa, comuna Livezi, judetul BACĂU, România", "sat Orasa, comuna Livezi, judetul BACAU, Romania")),
        createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Livezi, judetul BACĂU, România", "sat Poiana, comuna Livezi, judetul BACAU, Romania")),
        createLoc("Prăjoaia", "sat", createAdresaCompleta("sat Prăjoaia, comuna Livezi, judetul BACĂU, România", "sat Prajoaia, comuna Livezi, judetul BACAU, Romania")),
        createLoc("Scăriga", "sat", createAdresaCompleta("sat Scăriga, comuna Livezi, judetul BACĂU, România", "sat Scariga, comuna Livezi, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Livezi, judetul BACĂU, România", "comuna Livezi, judetul BACAU, Romania")),
    createComuna("Luizi-Călugăra", [
        createLoc("Luizi-Călugăra", "sat", createAdresaCompleta("sat Luizi-Călugăra, comuna Luizi-Călugăra, judetul BACĂU, România", "sat Luizi-Calugara, comuna Luizi-Calugara, judetul BACAU, Romania")),
        createLoc("Osebiți", "sat", createAdresaCompleta("sat Osebiți, comuna Luizi-Călugăra, judetul BACĂU, România", "sat Osebiti, comuna Luizi-Calugara, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Luizi-Călugăra, judetul BACĂU, România", "comuna Luizi-Calugara, judetul BACAU, Romania")),
    createComuna("Măgirești", [
        createLoc("Măgirești", "sat", createAdresaCompleta("sat Măgirești, comuna Măgirești, judetul BACĂU, România", "sat Magiresti, comuna Magiresti, judetul BACAU, Romania")),
        createLoc("Prăjești", "sat", createAdresaCompleta("sat Prăjești, comuna Măgirești, judetul BACĂU, România", "sat Prajesti, comuna Magiresti, judetul BACAU, Romania")),
        createLoc("Stănești", "sat", createAdresaCompleta("sat Stănești, comuna Măgirești, judetul BACĂU, România", "sat Stanesti, comuna Magiresti, judetul BACAU, Romania")),
        createLoc("Șesuri", "sat", createAdresaCompleta("sat Șesuri, comuna Măgirești, judetul BACĂU, România", "sat Sesuri, comuna Magiresti, judetul BACAU, Romania")),
        createLoc("Valea Arinilor", "sat", createAdresaCompleta("sat Valea Arinilor, comuna Măgirești, judetul BACĂU, România", "sat Valea Arinilor, comuna Magiresti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Măgirești, judetul BACĂU, România", "comuna Magiresti, judetul BACAU, Romania")),
    createComuna("Măgura", [
        createLoc("Măgura", "sat", createAdresaCompleta("sat Măgura, comuna Măgura, judetul BACĂU, România", "sat Magura, comuna Magura, judetul BACAU, Romania")),
        createLoc("Crihan", "sat", createAdresaCompleta("sat Crihan, comuna Măgura, judetul BACĂU, România", "sat Crihan, comuna Magura, judetul BACAU, Romania")),
        createLoc("Dealu Mare", "sat", createAdresaCompleta("sat Dealu Mare, comuna Măgura, judetul BACĂU, România", "sat Dealu Mare, comuna Magura, judetul BACAU, Romania")),
        createLoc("Sohodol", "sat", createAdresaCompleta("sat Sohodol, comuna Măgura, judetul BACĂU, România", "sat Sohodol, comuna Magura, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Măgura, judetul BACĂU, România", "comuna Magura, judetul BACAU, Romania")),
    createComuna("Mănăstirea Cașin", [
        createLoc("Mănăstirea Cașin", "sat", createAdresaCompleta("sat Mănăstirea Cașin, comuna Mănăstirea Cașin, judetul BACĂU, România", "sat Manastirea Casin, comuna Manastirea Casin, judetul BACAU, Romania")),
        createLoc("Lupești", "sat", createAdresaCompleta("sat Lupești, comuna Mănăstirea Cașin, judetul BACĂU, România", "sat Lupesti, comuna Manastirea Casin, judetul BACAU, Romania")),
        createLoc("Pârvulești", "sat", createAdresaCompleta("sat pârvulești, comuna Mănăstirea Cașin, judetul BACĂU, România", "sat parvulesti, comuna Manastirea Casin, judetul BACAU, Romania")),
        createLoc("Scutaru", "sat", createAdresaCompleta("sat Scutaru, comuna Mănăstirea Cașin, judetul BACĂU, România", "sat Scutaru, comuna Manastirea Casin, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Mănăstirea Cașin, judetul BACĂU, România", "comuna Manastirea Casin, judetul BACAU, Romania")),
    createComuna("Mărgineni", [
        createLoc("Mărgineni", "sat", createAdresaCompleta("sat Mărgineni, comuna Mărgineni, judetul BACĂU, România", "sat Margineni, comuna Margineni, judetul BACAU, Romania")),
        createLoc("Barați", "sat", createAdresaCompleta("sat Barați, comuna Mărgineni, judetul BACĂU, România", "sat Barati, comuna Margineni, judetul BACAU, Romania")),
        createLoc("Luncani", "sat", createAdresaCompleta("sat Luncani, comuna Mărgineni, judetul BACĂU, România", "sat Luncani, comuna Margineni, judetul BACAU, Romania")),
        createLoc("Pădureni", "sat", createAdresaCompleta("sat Pădureni, comuna Mărgineni, judetul BACĂU, România", "sat Padureni, comuna Margineni, judetul BACAU, Romania")),
        createLoc("Podiș", "sat", createAdresaCompleta("sat Podiș, comuna Mărgineni, judetul BACĂU, România", "sat Podis, comuna Margineni, judetul BACAU, Romania")),
        createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Mărgineni, judetul BACĂU, România", "sat Poiana, comuna Margineni, judetul BACAU, Romania")),
        createLoc("Trebeș", "sat", createAdresaCompleta("sat Trebeș, comuna Mărgineni, judetul BACĂU, România", "sat Trebes, comuna Margineni, judetul BACAU, Romania")),
        createLoc("Valea Budului", "sat", createAdresaCompleta("sat Valea Budului, comuna Mărgineni, judetul BACĂU, România", "sat Valea Budului, comuna Margineni, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Mărgineni, judetul BACĂU, România", "comuna Margineni, judetul BACAU, Romania")),
    createComuna("Motoșeni", [
        createLoc("Motoșeni", "sat", createAdresaCompleta("sat Motoșeni, comuna Motoșeni, judetul BACĂU, România", "sat Motoseni, comuna Motoseni, judetul BACAU, Romania")),
        createLoc("Bâclești", "sat", createAdresaCompleta("sat Bâclești, comuna Motoșeni, judetul BACĂU, România", "sat Baclesti, comuna Motoseni, judetul BACAU, Romania")),
        createLoc("Chetreni", "sat", createAdresaCompleta("sat Chetreni, comuna Motoșeni, judetul BACĂU, România", "sat Chetreni, comuna Motoseni, judetul BACAU, Romania")),
        createLoc("Chicerea", "sat", createAdresaCompleta("sat Chicerea, comuna Motoșeni, judetul BACĂU, România", "sat Chicerea, comuna Motoseni, judetul BACAU, Romania")),
        createLoc("Cociu", "sat", createAdresaCompleta("sat Cociu, comuna Motoșeni, judetul BACĂU, România", "sat Cociu, comuna Motoseni, judetul BACAU, Romania")),
        createLoc("Cornățelu", "sat", createAdresaCompleta("sat Cornățelu, comuna Motoșeni, judetul BACĂU, România", "sat Cornatelu, comuna Motoseni, judetul BACAU, Romania")),
        createLoc("Fântânele", "sat", createAdresaCompleta("sat Fântânele, comuna Motoșeni, judetul BACĂU, România", "sat Fantanele, comuna Motoseni, judetul BACAU, Romania")),
        createLoc("Fundătura", "sat", createAdresaCompleta("sat Fundătura, comuna Motoșeni, judetul BACĂU, România", "sat Fundatura, comuna Motoseni, judetul BACAU, Romania")),
        createLoc("Gura Crăiești", "sat", createAdresaCompleta("sat Gura Crăiești, comuna Motoșeni, judetul BACĂU, România", "sat Gura Craiesti, comuna Motoseni, judetul BACAU, Romania")),
        createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Motoșeni, judetul BACĂU, România", "sat Poiana, comuna Motoseni, judetul BACAU, Romania")),
        createLoc("Praja", "sat", createAdresaCompleta("sat Praja, comuna Motoșeni, judetul BACĂU, România", "sat Praja, comuna Motoseni, judetul BACAU, Romania")),
        createLoc("Rotăria", "sat", createAdresaCompleta("sat Rotăria, comuna Motoșeni, judetul BACĂU, România", "sat Rotaria, comuna Motoseni, judetul BACAU, Romania")),
        createLoc("Șendrești", "sat", createAdresaCompleta("sat Șendrești, comuna Motoșeni, judetul BACĂU, România", "sat Sendresti, comuna Motoseni, judetul BACAU, Romania")),
        createLoc("Țepoaia", "sat", createAdresaCompleta("sat Țepoaia, comuna Motoșeni, judetul BACĂU, România", "sat Tepoaia, comuna Motoseni, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Motoșeni, judetul BACĂU, România", "comuna Motoseni, judetul BACAU, Romania")),
    createComuna("Negri", [
        createLoc("Negri", "sat", createAdresaCompleta("sat Negri, comuna Negri, judetul BACĂU, România", "sat Negri, comuna Negri, judetul BACAU, Romania")),
        createLoc("Brad", "sat", createAdresaCompleta("sat Brad, comuna Negri, judetul BACĂU, România", "sat Brad, comuna Negri, judetul BACAU, Romania")),
        createLoc("Călinești", "sat", createAdresaCompleta("sat Călinești, comuna Negri, judetul BACĂU, România", "sat Calinesti, comuna Negri, judetul BACAU, Romania")),
        createLoc("Mâgla", "sat", createAdresaCompleta("sat Mâgla, comuna Negri, judetul BACĂU, România", "sat Magla, comuna Negri, judetul BACAU, Romania")),
        createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Negri, judetul BACĂU, România", "sat Poiana, comuna Negri, judetul BACAU, Romania")),
        createLoc("Ursoaia", "sat", createAdresaCompleta("sat Ursoaia, comuna Negri, judetul BACĂU, România", "sat Ursoaia, comuna Negri, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Negri, judetul BACĂU, România", "comuna Negri, judetul BACAU, Romania")),
    createComuna("Nicolae Bălcescu", [
        createLoc("Nicolae Bălcescu", "sat", createAdresaCompleta("sat Nicolae Bălcescu, comuna Nicolae Bălcescu, judetul BACĂU, România", "sat Nicolae Balcescu, comuna Nicolae Balcescu, judetul BACAU, Romania")),
        createLoc("Buchila", "sat", createAdresaCompleta("sat Buchila, comuna Nicolae Bălcescu, judetul BACĂU, România", "sat Buchila, comuna Nicolae Balcescu, judetul BACAU, Romania")),
        createLoc("Galbeni", "sat", createAdresaCompleta("sat Galbeni, comuna Nicolae Bălcescu, judetul BACĂU, România", "sat Galbeni, comuna Nicolae Balcescu, judetul BACAU, Romania")),
        createLoc("Lărguța", "sat", createAdresaCompleta("sat Lărguța, comuna Nicolae Bălcescu, judetul BACĂU, România", "sat Larguta, comuna Nicolae Balcescu, judetul BACAU, Romania")),
        createLoc("Valea Seacă", "sat", createAdresaCompleta("sat Valea Seacă, comuna Nicolae Bălcescu, judetul BACĂU, România", "sat Valea Seaca, comuna Nicolae Balcescu, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Nicolae Bălcescu, judetul BACĂU, România", "comuna Nicolae Balcescu, judetul BACAU, Romania")),
    createComuna("Odobești", [
        createLoc("Odobești", "sat", createAdresaCompleta("sat Odobești, comuna Odobești, judetul BACĂU, România", "sat Odobesti, comuna Odobesti, judetul BACAU, Romania")),
        createLoc("Bălușa", "sat", createAdresaCompleta("sat Bălușa, comuna Odobești, judetul BACĂU, România", "sat Balusa, comuna Odobesti, judetul BACAU, Romania")),
        createLoc("Ciuturești", "sat", createAdresaCompleta("sat Ciuturești, comuna Odobești, judetul BACĂU, România", "sat Ciuturesti, comuna Odobesti, judetul BACAU, Romania")),
        createLoc("Tisa-Silvestri", "sat", createAdresaCompleta("sat Tisa-Silvestri, comuna Odobești, judetul BACĂU, România", "sat Tisa-Silvestri, comuna Odobesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Odobești, judetul BACĂU, România", "comuna Odobesti, judetul BACAU, Romania")),
    createComuna("Oituz", [
        createLoc("Oituz", "sat", createAdresaCompleta("sat Oituz, comuna Oituz, judetul BACĂU, România", "sat Oituz, comuna Oituz, judetul BACAU, Romania")),
        createLoc("Călcâi", "sat", createAdresaCompleta("sat Călcâi, comuna Oituz, judetul BACĂU, România", "sat Calcai, comuna Oituz, judetul BACAU, Romania")),
        createLoc("Ferestrău-Oituz", "sat", createAdresaCompleta("sat Ferestrău-Oituz, comuna Oituz, judetul BACĂU, România", "sat Ferestrau-Oituz, comuna Oituz, judetul BACAU, Romania")),
        createLoc("Hârja", "sat", createAdresaCompleta("sat Hârja, comuna Oituz, judetul BACĂU, România", "sat Harja, comuna Oituz, judetul BACAU, Romania")),
        createLoc("Marginea", "sat", createAdresaCompleta("sat Marginea, comuna Oituz, judetul BACĂU, România", "sat Marginea, comuna Oituz, judetul BACAU, Romania")),
        createLoc("Poiana Sărată", "sat", createAdresaCompleta("sat Poiana Sărată, comuna Oituz, judetul BACĂU, România", "sat Poiana Sarata, comuna Oituz, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Oituz, judetul BACĂU, România", "comuna Oituz, judetul BACAU, Romania")),
    createComuna("Oncești", [
        createLoc("Oncești", "sat", createAdresaCompleta("sat Oncești, comuna Oncești, judetul BACĂU, România", "sat Oncesti, comuna Oncesti, judetul BACAU, Romania")),
        createLoc("Bărboasa", "sat", createAdresaCompleta("sat Bărboasa, comuna Oncești, judetul BACĂU, România", "sat Barboasa, comuna Oncesti, judetul BACAU, Romania")),
        createLoc("Dealu Perjului", "sat", createAdresaCompleta("sat Dealu Perjului, comuna Oncești, judetul BACĂU, România", "sat Dealu Perjului, comuna Oncesti, judetul BACAU, Romania")),
        createLoc("Onceștii Vechi", "sat", createAdresaCompleta("sat Onceștii Vechi, comuna Oncești, judetul BACĂU, România", "sat Oncestii Vechi, comuna Oncesti, judetul BACAU, Romania")),
        createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Oncești, judetul BACĂU, România", "sat Satu Nou, comuna Oncesti, judetul BACAU, Romania")),
        createLoc("Tarnița", "sat", createAdresaCompleta("sat Tarnița, comuna Oncești, judetul BACĂU, România", "sat Tarnita, comuna Oncesti, judetul BACAU, Romania")),
        createLoc("Taula", "sat", createAdresaCompleta("sat Taula, comuna Oncești, judetul BACĂU, România", "sat Taula, comuna Oncesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Oncești, judetul BACĂU, România", "comuna Oncesti, judetul BACAU, Romania")),
    createComuna("Orbeni", [
        createLoc("Orbeni", "sat", createAdresaCompleta("sat Orbeni, comuna Orbeni, judetul BACĂU, România", "sat Orbeni, comuna Orbeni, judetul BACAU, Romania")),
        createLoc("Scurta", "sat", createAdresaCompleta("sat Scurta, comuna Orbeni, judetul BACĂU, România", "sat Scurta, comuna Orbeni, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Orbeni, judetul BACĂU, România", "comuna Orbeni, judetul BACAU, Romania")),
    createComuna("Palanca", [
        createLoc("Palanca", "sat", createAdresaCompleta("sat Palanca, comuna Palanca, judetul BACĂU, România", "sat Palanca, comuna Palanca, judetul BACAU, Romania")),
        createLoc("Cădărești", "sat", createAdresaCompleta("sat Cădărești, comuna Palanca, judetul BACĂU, România", "sat Cadaresti, comuna Palanca, judetul BACAU, Romania")),
        createLoc("Ciugheș", "sat", createAdresaCompleta("sat Ciugheș, comuna Palanca, judetul BACĂU, România", "sat Ciughes, comuna Palanca, judetul BACAU, Romania")),
        createLoc("Pajiștea", "sat", createAdresaCompleta("sat Pajiștea, comuna Palanca, judetul BACĂU, România", "sat Pajistea, comuna Palanca, judetul BACAU, Romania")),
        createLoc("Popoiu", "sat", createAdresaCompleta("sat Popoiu, comuna Palanca, judetul BACĂU, România", "sat Popoiu, comuna Palanca, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Palanca, judetul BACĂU, România", "comuna Palanca, judetul BACAU, Romania")),
    createComuna("Parava", [
        createLoc("Parava", "sat", createAdresaCompleta("sat Parava, comuna Parava, judetul BACĂU, România", "sat Parava, comuna Parava, judetul BACAU, Romania")),
        createLoc("Drăgușani", "sat", createAdresaCompleta("sat Drăgușani, comuna Parava, judetul BACĂU, România", "sat Dragusani, comuna Parava, judetul BACAU, Romania")),
        createLoc("Rădoaia", "sat", createAdresaCompleta("sat Rădoaia, comuna Parava, judetul BACĂU, România", "sat Radoaia, comuna Parava, judetul BACAU, Romania")),
        createLoc("Teiuș", "sat", createAdresaCompleta("sat Teiuș, comuna Parava, judetul BACĂU, România", "sat Teius, comuna Parava, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Parava, judetul BACĂU, România", "comuna Parava, judetul BACAU, Romania")),
    createComuna("Parincea", [
        createLoc("Parincea", "sat", createAdresaCompleta("sat Parincea, comuna Parincea, judetul BACĂU, România", "sat Parincea, comuna Parincea, judetul BACAU, Romania")),
        createLoc("Barna", "sat", createAdresaCompleta("sat Barna, comuna Parincea, judetul BACĂU, România", "sat Barna, comuna Parincea, judetul BACAU, Romania")),
        createLoc("Mileștii de Jos", "sat", createAdresaCompleta("sat Mileștii de Jos, comuna Parincea, judetul BACĂU, România", "sat Milestii de Jos, comuna Parincea, judetul BACAU, Romania")),
        createLoc("Mileștii de Sus", "sat", createAdresaCompleta("sat Mileștii de Sus, comuna Parincea, judetul BACĂU, România", "sat Milestii de Sus, comuna Parincea, judetul BACAU, Romania")),
        createLoc("Nănești", "sat", createAdresaCompleta("sat Nănești, comuna Parincea, judetul BACĂU, România", "sat Nanesti, comuna Parincea, judetul BACAU, Romania")),
        createLoc("Năstăseni", "sat", createAdresaCompleta("sat Năstăseni, comuna Parincea, judetul BACĂU, România", "sat Nastaseni, comuna Parincea, judetul BACAU, Romania")),
        createLoc("Poieni", "sat", createAdresaCompleta("sat Poieni, comuna Parincea, judetul BACĂU, România", "sat Poieni, comuna Parincea, judetul BACAU, Romania")),
        createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Parincea, judetul BACĂU, România", "sat Satu Nou, comuna Parincea, judetul BACAU, Romania")),
        createLoc("Văleni", "sat", createAdresaCompleta("sat Văleni, comuna Parincea, judetul BACĂU, România", "sat Valeni, comuna Parincea, judetul BACAU, Romania")),
        createLoc("Vladnic", "sat", createAdresaCompleta("sat Vladnic, comuna Parincea, judetul BACĂU, România", "sat Vladnic, comuna Parincea, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Parincea, judetul BACĂU, România", "comuna Parincea, judetul BACAU, Romania")),
    createComuna("Pâncești", [
        createLoc("Pâncești", "sat", createAdresaCompleta("sat Pâncești, comuna Pâncești, judetul BACĂU, România", "sat Pancesti, comuna Pancesti, judetul BACAU, Romania")),
        createLoc("Chilia Benei", "sat", createAdresaCompleta("sat Chilia Benei, comuna Pâncești, judetul BACĂU, România", "sat Chilia Benei, comuna Pancesti, judetul BACAU, Romania")),
        createLoc("Dieneț", "sat", createAdresaCompleta("sat Dieneț, comuna Pâncești, judetul BACĂU, România", "sat Dienet, comuna Pancesti, judetul BACAU, Romania")),
        createLoc("Fulgeriș", "sat", createAdresaCompleta("sat Fulgeriș, comuna Pâncești, judetul BACĂU, România", "sat Fulgeris, comuna Pancesti, judetul BACAU, Romania")),
        createLoc("Fundu Văii", "sat", createAdresaCompleta("sat Fundu Văii, comuna Pâncești, judetul BACĂU, România", "sat Fundu Vaii, comuna Pancesti, judetul BACAU, Romania")),
        createLoc("Motoc", "sat", createAdresaCompleta("sat Motoc, comuna Pâncești, judetul BACĂU, România", "sat Motoc, comuna Pancesti, judetul BACAU, Romania")),
        createLoc("Petrești", "sat", createAdresaCompleta("sat Petrești, comuna Pâncești, judetul BACĂU, România", "sat Petresti, comuna Pancesti, judetul BACAU, Romania")),
        createLoc("Soci", "sat", createAdresaCompleta("sat Soci, comuna Pâncești, judetul BACĂU, România", "sat Soci, comuna Pancesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Pâncești, judetul BACĂU, România", "comuna Pancesti, judetul BACAU, Romania")),
    createComuna("Pârgărești", [
        createLoc("Pârgărești", "sat", createAdresaCompleta("sat pârgărești, comuna pârgărești, judetul BACĂU, România", "sat pargaresti, comuna pargaresti, judetul BACAU, Romania")),
        createLoc("Bahna", "sat", createAdresaCompleta("sat Bahna, comuna pârgărești, judetul BACĂU, România", "sat Bahna, comuna pargaresti, judetul BACAU, Romania")),
        createLoc("Nicorești", "sat", createAdresaCompleta("sat Nicorești, comuna pârgărești, judetul BACĂU, România", "sat Nicoresti, comuna pargaresti, judetul BACAU, Romania")),
        createLoc("Pârâu Boghii", "sat", createAdresaCompleta("sat Pârâu Boghii, comuna pârgărești, judetul BACĂU, România", "sat Parau Boghii, comuna pargaresti, judetul BACAU, Romania")),
        createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna pârgărești, judetul BACĂU, România", "sat Satu Nou, comuna pargaresti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna pârgărești, judetul BACĂU, România", "comuna pargaresti, judetul BACAU, Romania")),
    createComuna("Pârjol", [
        createLoc("Pârjol", "sat", createAdresaCompleta("sat Pârjol, comuna Pârjol, judetul BACĂU, România", "sat Parjol, comuna Parjol, judetul BACAU, Romania")),
        createLoc("Băhnășeni", "sat", createAdresaCompleta("sat Băhnășeni, comuna Pârjol, judetul BACĂU, România", "sat Bahnaseni, comuna Parjol, judetul BACAU, Romania")),
        createLoc("Bărnești", "sat", createAdresaCompleta("sat Bărnești, comuna Pârjol, judetul BACĂU, România", "sat Barnesti, comuna Parjol, judetul BACAU, Romania")),
        createLoc("Băsăști", "sat", createAdresaCompleta("sat Băsăști, comuna Pârjol, judetul BACĂU, România", "sat Basasti, comuna Parjol, judetul BACAU, Romania")),
        createLoc("Câmpeni", "sat", createAdresaCompleta("sat Câmpeni, comuna Pârjol, judetul BACĂU, România", "sat Campeni, comuna Parjol, judetul BACAU, Romania")),
        createLoc("Hăineala", "sat", createAdresaCompleta("sat Hăineala, comuna Pârjol, judetul BACĂU, România", "sat Haineala, comuna Parjol, judetul BACAU, Romania")),
        createLoc("Hemieni", "sat", createAdresaCompleta("sat Hemieni, comuna Pârjol, judetul BACĂU, România", "sat Hemieni, comuna Parjol, judetul BACAU, Romania")),
        createLoc("Pustiana", "sat", createAdresaCompleta("sat Pustiana, comuna Pârjol, judetul BACĂU, România", "sat Pustiana, comuna Parjol, judetul BACAU, Romania")),
        createLoc("Tărâța", "sat", createAdresaCompleta("sat Tărâța, comuna Pârjol, judetul BACĂU, România", "sat Tarata, comuna Parjol, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Pârjol, judetul BACĂU, România", "comuna Parjol, judetul BACAU, Romania")),
    createComuna("Plopana", [
        createLoc("Plopana", "sat", createAdresaCompleta("sat Plopana, comuna Plopana, judetul BACĂU, România", "sat Plopana, comuna Plopana, judetul BACAU, Romania")),
        createLoc("Budești", "sat", createAdresaCompleta("sat Budești, comuna Plopana, judetul BACĂU, România", "sat Budesti, comuna Plopana, judetul BACAU, Romania")),
        createLoc("Dorneni", "sat", createAdresaCompleta("sat Dorneni, comuna Plopana, judetul BACĂU, România", "sat Dorneni, comuna Plopana, judetul BACAU, Romania")),
        createLoc("Fundu Tutovei", "sat", createAdresaCompleta("sat Fundu Tutovei, comuna Plopana, judetul BACĂU, România", "sat Fundu Tutovei, comuna Plopana, judetul BACAU, Romania")),
        createLoc("Ițcani", "sat", createAdresaCompleta("sat Ițcani, comuna Plopana, judetul BACĂU, România", "sat Itcani, comuna Plopana, judetul BACAU, Romania")),
        createLoc("Rusenii Răzeși", "sat", createAdresaCompleta("sat Rusenii Răzeși, comuna Plopana, judetul BACĂU, România", "sat Rusenii Razesi, comuna Plopana, judetul BACAU, Romania")),
        createLoc("Rusenii de Sus", "sat", createAdresaCompleta("sat Rusenii de Sus, comuna Plopana, judetul BACĂU, România", "sat Rusenii de Sus, comuna Plopana, judetul BACAU, Romania")),
        createLoc("Străminoasa", "sat", createAdresaCompleta("sat Străminoasa, comuna Plopana, judetul BACĂU, România", "sat Straminoasa, comuna Plopana, judetul BACAU, Romania")),
        createLoc("Țâgâra", "sat", createAdresaCompleta("sat Țâgâra, comuna Plopana, judetul BACĂU, România", "sat Tagara, comuna Plopana, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Plopana, judetul BACĂU, România", "comuna Plopana, judetul BACAU, Romania")),
    createComuna("Podu Turcului", [
        createLoc("Podu Turcului", "sat", createAdresaCompleta("sat Podu Turcului, comuna Podu Turcului, judetul BACĂU, România", "sat Podu Turcului, comuna Podu Turcului, judetul BACAU, Romania")),
        createLoc("Bălănești", "sat", createAdresaCompleta("sat Bălănești, comuna Podu Turcului, judetul BACĂU, România", "sat Balanesti, comuna Podu Turcului, judetul BACAU, Romania")),
        createLoc("Căbești", "sat", createAdresaCompleta("sat Căbești, comuna Podu Turcului, judetul BACĂU, România", "sat Cabesti, comuna Podu Turcului, judetul BACAU, Romania")),
        createLoc("Fichitești", "sat", createAdresaCompleta("sat Fichitești, comuna Podu Turcului, judetul BACĂU, România", "sat Fichitesti, comuna Podu Turcului, judetul BACAU, Romania")),
        createLoc("Giurgioana", "sat", createAdresaCompleta("sat Giurgioana, comuna Podu Turcului, judetul BACĂU, România", "sat Giurgioana, comuna Podu Turcului, judetul BACAU, Romania")),
        createLoc("Hanța", "sat", createAdresaCompleta("sat Hanța, comuna Podu Turcului, judetul BACĂU, România", "sat Hanta, comuna Podu Turcului, judetul BACAU, Romania")),
        createLoc("Lehancea", "sat", createAdresaCompleta("sat Lehancea, comuna Podu Turcului, judetul BACĂU, România", "sat Lehancea, comuna Podu Turcului, judetul BACAU, Romania")),
        createLoc("Plopu", "sat", createAdresaCompleta("sat Plopu, comuna Podu Turcului, judetul BACĂU, România", "sat Plopu, comuna Podu Turcului, judetul BACAU, Romania")),
        createLoc("Răcușana", "sat", createAdresaCompleta("sat Răcușana, comuna Podu Turcului, judetul BACĂU, România", "sat Racusana, comuna Podu Turcului, judetul BACAU, Romania")),
        createLoc("Sârbi", "sat", createAdresaCompleta("sat Sârbi, comuna Podu Turcului, judetul BACĂU, România", "sat Sarbi, comuna Podu Turcului, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Podu Turcului, judetul BACĂU, România", "comuna Podu Turcului, judetul BACAU, Romania")),
    createComuna("Poduri", [
        createLoc("Poduri", "sat", createAdresaCompleta("sat Poduri, comuna Poduri, judetul BACĂU, România", "sat Poduri, comuna Poduri, judetul BACAU, Romania")),
        createLoc("Bucșești", "sat", createAdresaCompleta("sat Bucșești, comuna Poduri, judetul BACĂU, România", "sat Bucsesti, comuna Poduri, judetul BACAU, Romania")),
        createLoc("Cernu", "sat", createAdresaCompleta("sat Cernu, comuna Poduri, judetul BACĂU, România", "sat Cernu, comuna Poduri, judetul BACAU, Romania")),
        createLoc("Cornet", "sat", createAdresaCompleta("sat Cornet, comuna Poduri, judetul BACĂU, România", "sat Cornet, comuna Poduri, judetul BACAU, Romania")),
        createLoc("Negreni", "sat", createAdresaCompleta("sat Negreni, comuna Poduri, judetul BACĂU, România", "sat Negreni, comuna Poduri, judetul BACAU, Romania")),
        createLoc("Prohozești", "sat", createAdresaCompleta("sat Prohozești, comuna Poduri, judetul BACĂU, România", "sat Prohozesti, comuna Poduri, judetul BACAU, Romania")),
        createLoc("Valea Șoșii", "sat", createAdresaCompleta("sat Valea Șoșii, comuna Poduri, judetul BACĂU, România", "sat Valea Sosii, comuna Poduri, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Poduri, judetul BACĂU, România", "comuna Poduri, judetul BACAU, Romania")),
    createComuna("Prăjești", [
        createLoc("Prăjești", "sat", createAdresaCompleta("sat Prăjești, comuna Prăjești, judetul BACĂU, România", "sat Prajesti, comuna Prajesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Prăjești, judetul BACĂU, România", "comuna Prajesti, judetul BACAU, Romania")),
    createComuna("Racova", [
        createLoc("Racova", "sat", createAdresaCompleta("sat Racova, comuna Racova, judetul BACĂU, România", "sat Racova, comuna Racova, judetul BACAU, Romania")),
        createLoc("Gura Văii", "sat", createAdresaCompleta("sat Gura Văii, comuna Racova, judetul BACĂU, România", "sat Gura Vaii, comuna Racova, judetul BACAU, Romania")),
        createLoc("Hălmăcioaia", "sat", createAdresaCompleta("sat Hălmăcioaia, comuna Racova, judetul BACĂU, România", "sat Halmacioaia, comuna Racova, judetul BACAU, Romania")),
        createLoc("Ilieși", "sat", createAdresaCompleta("sat Ilieși, comuna Racova, judetul BACĂU, România", "sat Iliesi, comuna Racova, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Racova, judetul BACĂU, România", "comuna Racova, judetul BACAU, Romania")),
    createComuna("Răcăciuni", [
        createLoc("Răcăciuni", "sat", createAdresaCompleta("sat Răcăciuni, comuna Răcăciuni, judetul BACĂU, România", "sat Racaciuni, comuna Racaciuni, judetul BACAU, Romania")),
        createLoc("Ciucani", "sat", createAdresaCompleta("sat Ciucani, comuna Răcăciuni, judetul BACĂU, România", "sat Ciucani, comuna Racaciuni, judetul BACAU, Romania")),
        createLoc("Fundu Răcăciuni", "sat", createAdresaCompleta("sat Fundu Răcăciuni, comuna Răcăciuni, judetul BACĂU, România", "sat Fundu Racaciuni, comuna Racaciuni, judetul BACAU, Romania")),
        createLoc("Gheorghe Doja", "sat", createAdresaCompleta("sat Gheorghe Doja, comuna Răcăciuni, judetul BACĂU, România", "sat Gheorghe Doja, comuna Racaciuni, judetul BACAU, Romania")),
        createLoc("Gâșteni", "sat", createAdresaCompleta("sat Gâșteni, comuna Răcăciuni, judetul BACĂU, România", "sat Gasteni, comuna Racaciuni, judetul BACAU, Romania")),
        createLoc("Răstoaca", "sat", createAdresaCompleta("sat Răstoaca, comuna Răcăciuni, judetul BACĂU, România", "sat Rastoaca, comuna Racaciuni, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Răcăciuni, judetul BACĂU, România", "comuna Racaciuni, judetul BACAU, Romania")),
    createComuna("Răchitoasa", [
        createLoc("Răchitoasa", "sat", createAdresaCompleta("sat Răchitoasa, comuna Răchitoasa, judetul BACĂU, România", "sat Rachitoasa, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Barcana", "sat", createAdresaCompleta("sat Barcana, comuna Răchitoasa, judetul BACĂU, România", "sat Barcana, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Bucșa", "sat", createAdresaCompleta("sat Bucșa, comuna Răchitoasa, judetul BACĂU, România", "sat Bucsa, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Buda", "sat", createAdresaCompleta("sat Buda, comuna Răchitoasa, judetul BACĂU, România", "sat Buda, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Burdusaci", "sat", createAdresaCompleta("sat Burdusaci, comuna Răchitoasa, judetul BACĂU, România", "sat Burdusaci, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Dănăila", "sat", createAdresaCompleta("sat Dănăila, comuna Răchitoasa, judetul BACĂU, România", "sat Danaila, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, comuna Răchitoasa, judetul BACĂU, România", "sat Dumbrava, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Farcașa", "sat", createAdresaCompleta("sat Farcașa, comuna Răchitoasa, judetul BACĂU, România", "sat Farcasa, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Fundătura Răchitoasa", "sat", createAdresaCompleta("sat Fundătura Răchitoasa, comuna Răchitoasa, judetul BACĂU, România", "sat Fundatura Rachitoasa, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Hăghiac", "sat", createAdresaCompleta("sat Hăghiac, comuna Răchitoasa, judetul BACĂU, România", "sat Haghiac, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Magazia", "sat", createAdresaCompleta("sat Magazia, comuna Răchitoasa, judetul BACĂU, România", "sat Magazia, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Movilița", "sat", createAdresaCompleta("sat Movilița, comuna Răchitoasa, judetul BACĂU, România", "sat Movilita, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Oprișești", "sat", createAdresaCompleta("sat Oprișești, comuna Răchitoasa, judetul BACĂU, România", "sat Oprisesti, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Putini", "sat", createAdresaCompleta("sat Putini, comuna Răchitoasa, judetul BACĂU, România", "sat Putini, comuna Rachitoasa, judetul BACAU, Romania")),
        createLoc("Tochilea", "sat", createAdresaCompleta("sat Tochilea, comuna Răchitoasa, judetul BACĂU, România", "sat Tochilea, comuna Rachitoasa, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Răchitoasa, judetul BACĂU, România", "comuna Rachitoasa, judetul BACAU, Romania")),
    createComuna("Roșiori", [
        createLoc("Roșiori", "sat", createAdresaCompleta("sat Roșiori, comuna Roșiori, judetul BACĂU, România", "sat Rosiori, comuna Rosiori, judetul BACAU, Romania")),
        createLoc("Misihănești", "sat", createAdresaCompleta("sat Misihănești, comuna Roșiori, judetul BACĂU, România", "sat Misihanesti, comuna Rosiori, judetul BACAU, Romania")),
        createLoc("Negușeni", "sat", createAdresaCompleta("sat Negușeni, comuna Roșiori, judetul BACĂU, România", "sat Neguseni, comuna Rosiori, judetul BACAU, Romania")),
        createLoc("Poieni", "sat", createAdresaCompleta("sat Poieni, comuna Roșiori, judetul BACĂU, România", "sat Poieni, comuna Rosiori, judetul BACAU, Romania")),
        createLoc("Valea Mare", "sat", createAdresaCompleta("sat Valea Mare, comuna Roșiori, judetul BACĂU, România", "sat Valea Mare, comuna Rosiori, judetul BACAU, Romania")),
        createLoc("Valea Mică", "sat", createAdresaCompleta("sat Valea Mică, comuna Roșiori, judetul BACĂU, România", "sat Valea Mica, comuna Rosiori, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Roșiori, judetul BACĂU, România", "comuna Rosiori, judetul BACAU, Romania")),
    createComuna("Sascut", [
        createLoc("Sascut", "sat", createAdresaCompleta("sat Sascut, comuna Sascut, judetul BACĂU, România", "sat Sascut, comuna Sascut, judetul BACAU, Romania")),
        createLoc("Berești", "sat", createAdresaCompleta("sat Berești, comuna Sascut, judetul BACĂU, România", "sat Beresti, comuna Sascut, judetul BACAU, Romania")),
        createLoc("Conțești", "sat", createAdresaCompleta("sat Conțești, comuna Sascut, judetul BACĂU, România", "sat Contesti, comuna Sascut, judetul BACAU, Romania")),
        createLoc("Păncești", "sat", createAdresaCompleta("sat Păncești, comuna Sascut, judetul BACĂU, România", "sat Pancesti, comuna Sascut, judetul BACAU, Romania")),
        createLoc("Sascut-Sat", "sat", createAdresaCompleta("sat Sascut-Sat, comuna Sascut, judetul BACĂU, România", "sat Sascut-Sat, comuna Sascut, judetul BACAU, Romania")),
        createLoc("Schineni", "sat", createAdresaCompleta("sat Schineni, comuna Sascut, judetul BACĂU, România", "sat Schineni, comuna Sascut, judetul BACAU, Romania")),
        createLoc("Valea Nacului", "sat", createAdresaCompleta("sat Valea Nacului, comuna Sascut, judetul BACĂU, România", "sat Valea Nacului, comuna Sascut, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Sascut, judetul BACĂU, România", "comuna Sascut, judetul BACAU, Romania")),
    createComuna("Sănduleni", [
        createLoc("Sănduleni", "sat", createAdresaCompleta("sat Sănduleni, comuna Sănduleni, judetul BACĂU, România", "sat Sanduleni, comuna Sanduleni, judetul BACAU, Romania")),
        createLoc("Bârzulești", "sat", createAdresaCompleta("sat Bârzulești, comuna Sănduleni, judetul BACĂU, România", "sat Barzulesti, comuna Sanduleni, judetul BACAU, Romania")),
        createLoc("Coman", "sat", createAdresaCompleta("sat Coman, comuna Sănduleni, judetul BACĂU, România", "sat Coman, comuna Sanduleni, judetul BACAU, Romania")),
        createLoc("Mateiești", "sat", createAdresaCompleta("sat Mateiești, comuna Sănduleni, judetul BACĂU, România", "sat Mateiesti, comuna Sanduleni, judetul BACAU, Romania")),
        createLoc("Stufu", "sat", createAdresaCompleta("sat Stufu, comuna Sănduleni, judetul BACĂU, România", "sat Stufu, comuna Sanduleni, judetul BACAU, Romania")),
        createLoc("Tisa", "sat", createAdresaCompleta("sat Tisa, comuna Sănduleni, judetul BACĂU, România", "sat Tisa, comuna Sanduleni, judetul BACAU, Romania")),
        createLoc("Verșești", "sat", createAdresaCompleta("sat Verșești, comuna Sănduleni, judetul BACĂU, România", "sat Versesti, comuna Sanduleni, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Sănduleni, judetul BACĂU, România", "comuna Sanduleni, judetul BACAU, Romania")),
    createComuna("Sărata", [
        createLoc("Sărata", "sat", createAdresaCompleta("sat Sărata, comuna Sărata, judetul BACĂU, România", "sat Sarata, comuna Sarata, judetul BACAU, Romania")),
        createLoc("Bălțata", "sat", createAdresaCompleta("sat Bălțata, comuna Sărata, judetul BACĂU, România", "sat Baltata, comuna Sarata, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Sărata, judetul BACĂU, România", "comuna Sarata, judetul BACAU, Romania")),
    createComuna("Săucești", [
        createLoc("Săucești", "sat", createAdresaCompleta("sat Săucești, comuna Săucești, judetul BACĂU, România", "sat Saucesti, comuna Saucesti, judetul BACAU, Romania")),
        createLoc("Bogdan Vodă", "sat", createAdresaCompleta("sat Bogdan Vodă, comuna Săucești, judetul BACĂU, România", "sat Bogdan Voda, comuna Saucesti, judetul BACAU, Romania")),
        createLoc("Costei", "sat", createAdresaCompleta("sat Costei, comuna Săucești, judetul BACĂU, România", "sat Costei, comuna Saucesti, judetul BACAU, Romania")),
        createLoc("Schineni", "sat", createAdresaCompleta("sat Schineni, comuna Săucești, judetul BACĂU, România", "sat Schineni, comuna Saucesti, judetul BACAU, Romania")),
        createLoc("Siretu", "sat", createAdresaCompleta("sat Siretu, comuna Săucești, judetul BACĂU, România", "sat Siretu, comuna Saucesti, judetul BACAU, Romania")),
        createLoc("Șerbești", "sat", createAdresaCompleta("sat Șerbești, comuna Săucești, judetul BACĂU, România", "sat Serbesti, comuna Saucesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Săucești, judetul BACĂU, România", "comuna Saucesti, judetul BACAU, Romania")),
    createComuna("Scorțeni", [
        createLoc("Scorțeni", "sat", createAdresaCompleta("sat Scorțeni, comuna Scorțeni, judetul BACĂU, România", "sat Scorteni, comuna Scorteni, judetul BACAU, Romania")),
        createLoc("Bogdănești", "sat", createAdresaCompleta("sat Bogdănești, comuna Scorțeni, judetul BACĂU, România", "sat Bogdanesti, comuna Scorteni, judetul BACAU, Romania")),
        createLoc("Florești", "sat", createAdresaCompleta("sat Florești, comuna Scorțeni, judetul BACĂU, România", "sat Floresti, comuna Scorteni, judetul BACAU, Romania")),
        createLoc("Grigoreni", "sat", createAdresaCompleta("sat Grigoreni, comuna Scorțeni, judetul BACĂU, România", "sat Grigoreni, comuna Scorteni, judetul BACAU, Romania")),
        createLoc("Stejaru", "sat", createAdresaCompleta("sat Stejaru, comuna Scorțeni, judetul BACĂU, România", "sat Stejaru, comuna Scorteni, judetul BACAU, Romania")),
        createLoc("Șerpeni", "sat", createAdresaCompleta("sat Șerpeni, comuna Scorțeni, judetul BACĂU, România", "sat Serpeni, comuna Scorteni, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Scorțeni, judetul BACĂU, România", "comuna Scorteni, judetul BACAU, Romania")),
    createComuna("Secuieni", [
        createLoc("Secuieni", "sat", createAdresaCompleta("sat Secuieni, comuna Secuieni, judetul BACĂU, România", "sat Secuieni, comuna Secuieni, judetul BACAU, Romania")),
        createLoc("Berbinceni", "sat", createAdresaCompleta("sat Berbinceni, comuna Secuieni, judetul BACĂU, România", "sat Berbinceni, comuna Secuieni, judetul BACAU, Romania")),
        createLoc("Chiticeni", "sat", createAdresaCompleta("sat Chiticeni, comuna Secuieni, judetul BACĂU, România", "sat Chiticeni, comuna Secuieni, judetul BACAU, Romania")),
        createLoc("Fundeni", "sat", createAdresaCompleta("sat Fundeni, comuna Secuieni, judetul BACĂU, România", "sat Fundeni, comuna Secuieni, judetul BACAU, Romania")),
        createLoc("Glodișoarele", "sat", createAdresaCompleta("sat Glodișoarele, comuna Secuieni, judetul BACĂU, România", "sat Glodisoarele, comuna Secuieni, judetul BACAU, Romania")),
        createLoc("Valea Fânațului", "sat", createAdresaCompleta("sat Valea Fânațului, comuna Secuieni, judetul BACĂU, România", "sat Valea Fanatului, comuna Secuieni, judetul BACAU, Romania")),
        createLoc("Văleni", "sat", createAdresaCompleta("sat Văleni, comuna Secuieni, judetul BACĂU, România", "sat Valeni, comuna Secuieni, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Secuieni, judetul BACĂU, România", "comuna Secuieni, judetul BACAU, Romania")),
    createComuna("Solonț", [
        createLoc("Solonț", "sat", createAdresaCompleta("sat Solonț, comuna Solonț, judetul BACĂU, România", "sat Solont, comuna Solont, judetul BACAU, Romania")),
        createLoc("Cucuieți", "sat", createAdresaCompleta("sat Cucuieți, comuna Solonț, judetul BACĂU, România", "sat Cucuieti, comuna Solont, judetul BACAU, Romania")),
        createLoc("Sărata", "sat", createAdresaCompleta("sat Sărata, comuna Solonț, judetul BACĂU, România", "sat Sarata, comuna Solont, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Solonț, judetul BACĂU, România", "comuna Solont, judetul BACAU, Romania")),
    createComuna("Stănișești", [
        createLoc("Stănișești", "sat", createAdresaCompleta("sat Stănișești, comuna Stănișești, judetul BACĂU, România", "sat Stanisesti, comuna Stanisesti, judetul BACAU, Romania")),
        createLoc("Balotești", "sat", createAdresaCompleta("sat Balotești, comuna Stănișești, judetul BACĂU, România", "sat Balotesti, comuna Stanisesti, judetul BACAU, Romania")),
        createLoc("Belciuneasa", "sat", createAdresaCompleta("sat Belciuneasa, comuna Stănișești, judetul BACĂU, România", "sat Belciuneasa, comuna Stanisesti, judetul BACAU, Romania")),
        createLoc("Benești", "sat", createAdresaCompleta("sat Benești, comuna Stănișești, judetul BACĂU, România", "sat Benesti, comuna Stanisesti, judetul BACAU, Romania")),
        createLoc("Crăiești", "sat", createAdresaCompleta("sat Crăiești, comuna Stănișești, judetul BACĂU, România", "sat Craiesti, comuna Stanisesti, judetul BACAU, Romania")),
        createLoc("Gorghești", "sat", createAdresaCompleta("sat Gorghești, comuna Stănișești, judetul BACĂU, România", "sat Gorghesti, comuna Stanisesti, judetul BACAU, Romania")),
        createLoc("Slobozia", "sat", createAdresaCompleta("sat Slobozia, comuna Stănișești, judetul BACĂU, România", "sat Slobozia, comuna Stanisesti, judetul BACAU, Romania")),
        createLoc("Slobozia Nouă", "sat", createAdresaCompleta("sat Slobozia Nouă, comuna Stănișești, judetul BACĂU, România", "sat Slobozia Noua, comuna Stanisesti, judetul BACAU, Romania")),
        createLoc("Văleni", "sat", createAdresaCompleta("sat Văleni, comuna Stănișești, judetul BACĂU, România", "sat Valeni, comuna Stanisesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Stănișești, judetul BACĂU, România", "comuna Stanisesti, judetul BACAU, Romania")),
    createComuna("Strugari", [
        createLoc("Strugari", "sat", createAdresaCompleta("sat Strugari, comuna Strugari, judetul BACĂU, România", "sat Strugari, comuna Strugari, judetul BACAU, Romania")),
        createLoc("Cetățuia", "sat", createAdresaCompleta("sat Cetățuia, comuna Strugari, judetul BACĂU, România", "sat Cetatuia, comuna Strugari, judetul BACAU, Romania")),
        createLoc("Iaz", "sat", createAdresaCompleta("sat Iaz, comuna Strugari, judetul BACĂU, România", "sat Iaz, comuna Strugari, judetul BACAU, Romania")),
        createLoc("Nadișa", "sat", createAdresaCompleta("sat Nadișa, comuna Strugari, judetul BACĂU, România", "sat Nadisa, comuna Strugari, judetul BACAU, Romania")),
        createLoc("Petricica", "sat", createAdresaCompleta("sat Petricica, comuna Strugari, judetul BACĂU, România", "sat Petricica, comuna Strugari, judetul BACAU, Romania")),
        createLoc("Răchitișu", "sat", createAdresaCompleta("sat Răchitișu, comuna Strugari, judetul BACĂU, România", "sat Rachitisu, comuna Strugari, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Strugari, judetul BACĂU, România", "comuna Strugari, judetul BACAU, Romania")),
    createComuna("Ștefan cel Mare", [
        createLoc("Ștefan cel Mare", "sat", createAdresaCompleta("sat Ștefan cel Mare, comuna Ștefan cel Mare, judetul BACĂU, România", "sat Stefan cel Mare, comuna Stefan cel Mare, judetul BACAU, Romania")),
        createLoc("Bogdana", "sat", createAdresaCompleta("sat Bogdana, comuna Ștefan cel Mare, judetul BACĂU, România", "sat Bogdana, comuna Stefan cel Mare, judetul BACAU, Romania")),
        createLoc("Gutinaș", "sat", createAdresaCompleta("sat Gutinaș, comuna Ștefan cel Mare, judetul BACĂU, România", "sat Gutinas, comuna Stefan cel Mare, judetul BACAU, Romania")),
        createLoc("Negoiești", "sat", createAdresaCompleta("sat Negoiești, comuna Ștefan cel Mare, judetul BACĂU, România", "sat Negoiesti, comuna Stefan cel Mare, judetul BACAU, Romania")),
        createLoc("Rădeana", "sat", createAdresaCompleta("sat Rădeana, comuna Ștefan cel Mare, judetul BACĂU, România", "sat Radeana, comuna Stefan cel Mare, judetul BACAU, Romania")),
        createLoc("Viișoara", "sat", createAdresaCompleta("sat Viișoara, comuna Ștefan cel Mare, judetul BACĂU, România", "sat Viisoara, comuna Stefan cel Mare, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Ștefan cel Mare, judetul BACĂU, România", "comuna Stefan cel Mare, judetul BACAU, Romania")),
    createComuna("Tamași", [
        createLoc("Tamași", "sat", createAdresaCompleta("sat Tamași, comuna Tamași, judetul BACĂU, România", "sat Tamasi, comuna Tamasi, judetul BACAU, Romania")),
        createLoc("Chetriș", "sat", createAdresaCompleta("sat Chetriș, comuna Tamași, judetul BACĂU, România", "sat Chetris, comuna Tamasi, judetul BACAU, Romania")),
        createLoc("Furnicari", "sat", createAdresaCompleta("sat Furnicari, comuna Tamași, judetul BACĂU, România", "sat Furnicari, comuna Tamasi, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Tamași, judetul BACĂU, România", "comuna Tamasi, judetul BACAU, Romania")),
    createComuna("Tătărăști", [
        createLoc("Tătărăști", "sat", createAdresaCompleta("sat Tătărăști, comuna Tătărăști, judetul BACĂU, România", "sat Tatarasti, comuna Tatarasti, judetul BACAU, Romania")),
        createLoc("Cornii de Jos", "sat", createAdresaCompleta("sat Cornii de Jos, comuna Tătărăști, judetul BACĂU, România", "sat Cornii de Jos, comuna Tatarasti, judetul BACAU, Romania")),
        createLoc("Cornii de Sus", "sat", createAdresaCompleta("sat Cornii de Sus, comuna Tătărăști, judetul BACĂU, România", "sat Cornii de Sus, comuna Tatarasti, judetul BACAU, Romania")),
        createLoc("Drăgești", "sat", createAdresaCompleta("sat Drăgești, comuna Tătărăști, judetul BACĂU, România", "sat Dragesti, comuna Tatarasti, judetul BACAU, Romania")),
        createLoc("Gherdana", "sat", createAdresaCompleta("sat Gherdana, comuna Tătărăști, judetul BACĂU, România", "sat Gherdana, comuna Tatarasti, judetul BACAU, Romania")),
        createLoc("Giurgeni", "sat", createAdresaCompleta("sat Giurgeni, comuna Tătărăști, judetul BACĂU, România", "sat Giurgeni, comuna Tatarasti, judetul BACAU, Romania")),
        createLoc("Ungureni", "sat", createAdresaCompleta("sat Ungureni, comuna Tătărăști, judetul BACĂU, România", "sat Ungureni, comuna Tatarasti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Tătărăști, judetul BACĂU, România", "comuna Tatarasti, judetul BACAU, Romania")),
    createComuna("Târgu Trotuș", [
        createLoc("Târgu Trotuș", "oras", createAdresaCompleta("orasul Târgu Trotuș, judetul BACĂU, România", "orasul Targu Trotus, judetul BACAU, Romania")),
        createLoc("Tuta", "sat", createAdresaCompleta("sat Tuta, orasul Târgu Trotuș, judetul BACĂU, România", "sat Tuta, orasul Targu Trotus, judetul BACAU, Romania")),
        createLoc("Viișoara", "sat", createAdresaCompleta("sat Viișoara, orasul Târgu Trotuș, judetul BACĂU, România", "sat Viisoara, orasul Targu Trotus, judetul BACAU, Romania")),
    ], createAdresaCompleta("orasul Târgu Trotuș, judetul BACĂU, România", "orasul Targu Trotus, judetul BACAU, Romania")),
    createComuna("Traian", [
        createLoc("Traian", "sat", createAdresaCompleta("sat Traian, comuna Traian, judetul BACĂU, România", "sat Traian, comuna Traian, judetul BACAU, Romania")),
        createLoc("Bogdănești", "sat", createAdresaCompleta("sat Bogdănești, comuna Traian, judetul BACĂU, România", "sat Bogdanesti, comuna Traian, judetul BACAU, Romania")),
        createLoc("Hertioana de Jos", "sat", createAdresaCompleta("sat Hertioana de Jos, comuna Traian, judetul BACĂU, România", "sat Hertioana de Jos, comuna Traian, judetul BACAU, Romania")),
        createLoc("Hertioana-Răzeși", "sat", createAdresaCompleta("sat Hertioana-Răzeși, comuna Traian, judetul BACĂU, România", "sat Hertioana-Razesi, comuna Traian, judetul BACAU, Romania")),
        createLoc("Zăpodia", "sat", createAdresaCompleta("sat Zăpodia, comuna Traian, judetul BACĂU, România", "sat Zapodia, comuna Traian, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Traian, judetul BACĂU, România", "comuna Traian, judetul BACAU, Romania")),
    createComuna("Ungureni", [
        createLoc("Ungureni", "sat", createAdresaCompleta("sat Ungureni, comuna Ungureni, judetul BACĂU, România", "sat Ungureni, comuna Ungureni, judetul BACAU, Romania")),
        createLoc("Bărtășești", "sat", createAdresaCompleta("sat Bărtășești, comuna Ungureni, judetul BACĂU, România", "sat Bartasesti, comuna Ungureni, judetul BACAU, Romania")),
        createLoc("Bibirești", "sat", createAdresaCompleta("sat Bibirești, comuna Ungureni, judetul BACĂU, România", "sat Bibiresti, comuna Ungureni, judetul BACAU, Romania")),
        createLoc("Bota", "sat", createAdresaCompleta("sat Bota, comuna Ungureni, judetul BACĂU, România", "sat Bota, comuna Ungureni, judetul BACAU, Romania")),
        createLoc("Botești", "sat", createAdresaCompleta("sat Botești, comuna Ungureni, judetul BACĂU, România", "sat Botesti, comuna Ungureni, judetul BACAU, Romania")),
        createLoc("Gârla Anei", "sat", createAdresaCompleta("sat Gârla Anei, comuna Ungureni, judetul BACĂU, România", "sat Garla Anei, comuna Ungureni, judetul BACAU, Romania")),
        createLoc("Viforeni", "sat", createAdresaCompleta("sat Viforeni, comuna Ungureni, judetul BACĂU, România", "sat Viforeni, comuna Ungureni, judetul BACAU, Romania")),
        createLoc("Zlătari", "sat", createAdresaCompleta("sat Zlătari, comuna Ungureni, judetul BACĂU, România", "sat Zlatari, comuna Ungureni, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Ungureni, judetul BACĂU, România", "comuna Ungureni, judetul BACAU, Romania")),
    createComuna("Urechești", [
        createLoc("Urechești", "sat", createAdresaCompleta("sat Urechești, comuna Urechești, judetul BACĂU, România", "sat Urechesti, comuna Urechesti, judetul BACAU, Romania")),
        createLoc("Cornățel", "sat", createAdresaCompleta("sat Cornățel, comuna Urechești, judetul BACĂU, România", "sat Cornatel, comuna Urechesti, judetul BACAU, Romania")),
        createLoc("Lunca Dochiei", "sat", createAdresaCompleta("sat Lunca Dochiei, comuna Urechești, judetul BACĂU, România", "sat Lunca Dochiei, comuna Urechesti, judetul BACAU, Romania")),
        createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Urechești, judetul BACĂU, România", "sat Satu Nou, comuna Urechesti, judetul BACAU, Romania")),
        createLoc("Slobozia", "sat", createAdresaCompleta("sat Slobozia, comuna Urechești, judetul BACĂU, România", "sat Slobozia, comuna Urechesti, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Urechești, judetul BACĂU, România", "comuna Urechesti, judetul BACAU, Romania")),
    createComuna("Valea Seacă", [
        createLoc("Valea Seacă", "sat", createAdresaCompleta("sat Valea Seacă, comuna Valea Seacă, judetul BACĂU, România", "sat Valea Seaca, comuna Valea Seaca, judetul BACAU, Romania")),
        createLoc("Cucova", "sat", createAdresaCompleta("sat Cucova, comuna Valea Seacă, judetul BACĂU, România", "sat Cucova, comuna Valea Seaca, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Valea Seacă, judetul BACĂU, România", "comuna Valea Seaca, judetul BACAU, Romania")),
    createComuna("Vultureni", [
        createLoc("Vultureni", "sat", createAdresaCompleta("sat Vultureni, comuna Vultureni, judetul BACĂU, România", "sat Vultureni, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Bosia", "sat", createAdresaCompleta("sat Bosia, comuna Vultureni, judetul BACĂU, România", "sat Bosia, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Dădești", "sat", createAdresaCompleta("sat Dădești, comuna Vultureni, judetul BACĂU, România", "sat Dadesti, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Dorneni", "sat", createAdresaCompleta("sat Dorneni, comuna Vultureni, judetul BACĂU, România", "sat Dorneni, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Ghilăvești", "sat", createAdresaCompleta("sat Ghilăvești, comuna Vultureni, judetul BACĂU, România", "sat Ghilavesti, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Godineștii de Jos", "sat", createAdresaCompleta("sat Godineștii de Jos, comuna Vultureni, judetul BACĂU, România", "sat Godinestii de Jos, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Godineștii de Sus", "sat", createAdresaCompleta("sat Godineștii de Sus, comuna Vultureni, judetul BACĂU, România", "sat Godinestii de Sus, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Lichitișeni", "sat", createAdresaCompleta("sat Lichitișeni, comuna Vultureni, judetul BACĂU, România", "sat Lichitiseni, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Medeleni", "sat", createAdresaCompleta("sat Medeleni, comuna Vultureni, judetul BACĂU, România", "sat Medeleni, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Năzărioaia", "sat", createAdresaCompleta("sat Năzărioaia, comuna Vultureni, judetul BACĂU, România", "sat Nazarioaia, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Reprivăț", "sat", createAdresaCompleta("sat Reprivăț, comuna Vultureni, judetul BACĂU, România", "sat Reprivat, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Tomozia", "sat", createAdresaCompleta("sat Tomozia, comuna Vultureni, judetul BACĂU, România", "sat Tomozia, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Țigănești", "sat", createAdresaCompleta("sat Țigănești, comuna Vultureni, judetul BACĂU, România", "sat Tiganesti, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Valea Lupului", "sat", createAdresaCompleta("sat Valea Lupului, comuna Vultureni, judetul BACĂU, România", "sat Valea Lupului, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Valea Merilor", "sat", createAdresaCompleta("sat Valea Merilor, comuna Vultureni, judetul BACĂU, România", "sat Valea Merilor, comuna Vultureni, judetul BACAU, Romania")),
        createLoc("Valea Salciei", "sat", createAdresaCompleta("sat Valea Salciei, comuna Vultureni, judetul BACĂU, România", "sat Valea Salciei, comuna Vultureni, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Vultureni, judetul BACĂU, România", "comuna Vultureni, judetul BACAU, Romania")),
    createComuna("Zemeș", [
        createLoc("Zemeș", "sat", createAdresaCompleta("sat Zemeș, comuna Zemeș, judetul BACĂU, România", "sat Zemes, comuna Zemes, judetul BACAU, Romania")),
        createLoc("Bolătău", "sat", createAdresaCompleta("sat Bolătău, comuna Zemeș, judetul BACĂU, România", "sat Bolatau, comuna Zemes, judetul BACAU, Romania")),
    ], createAdresaCompleta("comuna Zemeș, judetul BACĂU, România", "comuna Zemes, judetul BACAU, Romania")),
];
?>