<?php
$comune =[
			createComuna("Almaș", [
					createLoc("Almaș", "sat"),
					createLoc("Cil", "sat"),
					createLoc("Joia Mare", "sat"),
					createLoc("Rădești", "sat"),
								  ]),	
			createComuna("Apateu", [
					createLoc("Apateu", "sat"),
					createLoc("Berechiu", "sat"),
					createLoc("Moțiori", "sat"),
								  ]),
			createComuna("Archiș", [
					createLoc("Archiș", "sat"),
					createLoc("Bârzești", "sat"),
					createLoc("Groșeni", "sat"),
					createLoc("Nermiș", "sat"),
								  ]),	
			createComuna("Bata", [
					createLoc("Bata", "sat"),
					createLoc("Bacău de Mijloc", "sat"),
					createLoc("Bulci", "sat"),
					createLoc("Țela", "sat"),
								  ]),	
		    createComuna("Beliu", [
					createLoc("Beliu", "sat"),
					createLoc("Benești", "sat"),
					createLoc("Bochia", "sat"),
					createLoc("Secaci", "sat"),
					createLoc("Tăgădău", "sat"),
					createLoc("Vasile Goldiș", "sat"),
								  ]),	
			createComuna("Birchiș", [
					createLoc("Birchiș", "sat"),
					createLoc("Căpălnaș", "sat"),
					createLoc("Ostrov", "sat"),
					createLoc("Virismort", "sat"),
								  ]),
			createComuna("Bârsa", [
					createLoc("Bârsa", "sat"),
					createLoc("Aldești", "sat"),
					createLoc("Hodiș", "sat"),
					createLoc("Voivodeni", "sat"),
								  ]),	
			createComuna("Bârzava", [
					createLoc("Bârzava", "sat"),
					createLoc("Bătuța", "sat"),
					createLoc("Căpruța", "sat"),
					createLoc("Dumbrăvița", "sat"),
					createLoc("Groșii Noi", "sat"),
					createLoc("Lalașinț", "sat"),
					createLoc("Monoroștia", "sat"),
					createLoc("Slatina de Mureș", "sat"),
								  ]),
			createComuna("Bocsig", [
					createLoc("Bocsig", "sat"),
					createLoc("Mânerău", "sat"),
					createLoc("Răpsig", "sat"),
								  ]),	
			createComuna("Brazii", [
					createLoc("Brazii", "sat"),
					createLoc("Buceava-Șoimuș", "sat"),
					createLoc("Iacobini", "sat"),
					createLoc("Mădrigești", "sat"),
					createLoc("Secaș", "sat"),
								  ]),	
			createComuna("Buteni", [
					createLoc("Buteni", "sat"),
					createLoc("Berindia", "sat"),
					createLoc("Cuied", "sat"),
					createLoc("Păulian", "sat"),
								  ]),	
			createComuna("Cărand", [
					createLoc("Cărand", "sat"),
					createLoc("Seliștea", "sat"),
								  ]),
			createComuna("Cermei", [
					createLoc("Cermei", "sat"),
					createLoc("Avram Iancu", "sat"),
					createLoc("Șomoșcheș", "sat"),
								  ]),	
			createComuna("Chisindia", [
					createLoc("Chisindia", "sat"),
					createLoc("Păiușeni", "sat"),
					createLoc("Văsoaia", "sat"),
								  ]),
			createComuna("Conop", [
					createLoc("Conop", "sat"),
					createLoc("Belotinț", "sat"),
					createLoc("Chelmac", "sat"),
					createLoc("Milova", "sat"),
					createLoc("Odvoș", "sat"),
								  ]),	
			createComuna("Covăsinț", [
					createLoc("Covăsinț", "sat"),
								  ]),	
			createComuna("Craiva", [
					createLoc("Craiva", "sat"),
					createLoc("Chișlaca", "sat"),
					createLoc("Ciuntești", "sat"),
					createLoc("Coroi", "sat"),
					createLoc("Mărăuș", "sat"),
					createLoc("Rogoz de Beliu", "sat"),
					createLoc("Stoinești", "sat"),
					createLoc("Susag", "sat"),
					createLoc("Șiad", "sat"),
					createLoc("Tălmaci", "sat"),
								  ]),	
			createComuna("Dezna", [
					createLoc("Dezna", "sat"),
					createLoc("Buhani", "sat"),
					createLoc("Laz", "sat"),
					createLoc("Neagra", "sat"),
					createLoc("Slatina de Criș", "sat"),
								  ]),
			createComuna("Dieci", [
					createLoc("Dieci", "sat"),
					createLoc("Cociuba", "sat"),
					createLoc("Crocna", "sat"),
					createLoc("Revetiș", "sat"),
					createLoc("Roșia", "sat"),
								  ]),	
			createComuna("Dorobanți", [
					createLoc("Dorobanți", "sat"),
								  ]),	
			createComuna("Fântânele", [
					createLoc("Fântânele", "sat"),
					createLoc("Tisa Nouă", "sat"),
								  ]),	
			createComuna("Felnac", [
					createLoc("Felnac", "sat"),
					createLoc("Călugăreni", "sat"),
								  ]),
			createComuna("Frumușeni", [
					createLoc("Frumușeni", "sat"),
					createLoc("Aluniș", "sat"),
								  ]),	
			createComuna("Ghioroc", [
					createLoc("Ghioroc", "sat"),
					createLoc("Cuvin", "sat"),
					createLoc("Miniș", "sat"),
								  ]),
			createComuna("Grăniceri", [
					createLoc("Grăniceri", "sat"),
					createLoc("Șiclău", "sat"),
								  ]),	
			createComuna("Gurahonț", [
					createLoc("Gurahonț", "sat"),
					createLoc("Bonțești", "sat"),
					createLoc("Dulcele", "sat"),
					createLoc("Feniș", "sat"),
					createLoc("Honțișor", "sat"),
					createLoc("Iosaș", "sat"),
					createLoc("Mustești", "sat"),
					createLoc("Pescari", "sat"),
					createLoc("Valea Mare", "sat"),
					createLoc("Zimbru", "sat"),
								  ]),
			createComuna("Hălmagiu", [
					createLoc("Hălmagiu", "sat"),
					createLoc("Bănești", "sat"),
					createLoc("Bodești", "sat"),
					createLoc("Brusturi", "sat"),
					createLoc("Cristești", "sat"),
					createLoc("Ionești", "sat"),
					createLoc("Leasa", "sat"),
					createLoc("Leștioara", "sat"),
					createLoc("Poienari", "sat"),
					createLoc("Tisa", "sat"),
					createLoc("Țărmure", "sat"),
								  ]),	
			createComuna("Hălmăgel", [
					createLoc("Hălmăgel", "sat"),
					createLoc("Luncșoara", "sat"),
					createLoc("Sârbi", "sat"),
					createLoc("Târnăvița", "sat"),
					createLoc("Țohești", "sat"),
								  ]),
			createComuna("Hășmaș", [
					createLoc("Hășmaș", "sat"),
					createLoc("Agrișu Mic", "sat"),
					createLoc("Botfei", "sat"),
					createLoc("Clit", "sat"),
					createLoc("Comănești", "sat"),
					createLoc("Urvișu de Beliu", "sat"),
								  ]),	
			createComuna("Ignești", [
					createLoc("Ignești", "sat"),
					createLoc("Minead", "sat"),
					createLoc("Nădălbești", "sat"),
					createLoc("Susani", "sat"),
								  ]),
			createComuna("Iratoșu", [
					createLoc("Iratoșu", "sat"),
					createLoc("Variașu Mare", "sat"),
					createLoc("Variașu Mic", "sat"),
								  ]),	
			createComuna("Livada", [
					createLoc("Livada", "sat"),
					createLoc("Sânleani", "sat"),
								  ]),
			createComuna("Macea", [
					createLoc("Macea", "sat"),
					createLoc("Sânmartin", "sat"),
								  ]),	
			createComuna("Mișca", [
					createLoc("Mișca", "sat"),
					createLoc("Satu Nou", "sat"),
					createLoc("Vânători", "sat"),
					createLoc("Zerindu Mic", "sat"),
								  ]),
			createComuna("Moneasa", [
					createLoc("Moneasa", "sat"),
					createLoc("Rănușa", "sat"),
								  ]),	
			createComuna("Olari", [
					createLoc("Olari", "sat"),
					createLoc("Sintea Mică", "sat"),
								  ]),
			createComuna("Păuliș", [
					createLoc("Păuliș", "sat"),
					createLoc("Barațca", "sat"),
					createLoc("Cladova", "sat"),
					createLoc("Sâmbăteni", "sat"),
								  ]),	
			createComuna("Peregu Mare", [
					createLoc("Peregu Mare", "sat"),
					createLoc("Peregu Mic", "sat"),
								  ]),
			createComuna("Petriș", [
					createLoc("Petriș", "sat"),
					createLoc("Corbești", "sat"),
					createLoc("Ilteu", "sat"),
					createLoc("Obârșia", "sat"),
				    createLoc("Roșia Nouă", "sat"),
					createLoc("Seliște", "sat"),
								  ]),	
			createComuna("Pilu", [
					createLoc("Pilu", "sat"),
					createLoc("Vărșand", "sat"),
								  ]),
			createComuna("Pleșcuța", [
					createLoc("Pleșcuța", "sat"),
					createLoc("Aciuța", "sat"),
					createLoc("Budești", "sat"),
					createLoc("Dumbrava", "sat"),
				    createLoc("Gura Văii", "sat"),
					createLoc("Rostoci", "sat"),
					createLoc("Tălagiu", "sat"),
								  ]),	
			createComuna("Săvârșin", [
					createLoc("Săvârșin", "sat"),
					createLoc("Căprioara", "sat"),
					createLoc("Cuiaș", "sat"),
					createLoc("Hălăliș", "sat"),
					createLoc("Pârnești", "sat"),
					createLoc("Temeșești", "sat"),
					createLoc("Toc", "sat"),
					createLoc("Troaș", "sat"),
					createLoc("Valea Mare", "sat"),
								  ]),
			createComuna("Secusigiu", [
					createLoc("Secusigiu", "sat"),
					createLoc("Munar", "sat"),
					createLoc("Satu Mare", "sat"),
					createLoc("Sânpetru German", "sat"),
								  ]),	
			createComuna("Seleuș", [
					createLoc("Seleuș", "sat"),
					createLoc("Iermata", "sat"),
					createLoc("Moroda", "sat"),
								  ]),
			createComuna("Semlac", [
					createLoc("Semlac", "sat"),
								  ]),	
			createComuna("Sintea Mare", [
					createLoc("Sintea Mare", "sat"),
					createLoc("Adea", "sat"),
					createLoc("Țipar", "sat"),
								  ]),
			createComuna("Socodor", [
					createLoc("Socodor", "sat"),
								  ]),	
			createComuna("Șagu", [
					createLoc("Șagu", "sat"),
					createLoc("Cruceni", "sat"),
					createLoc("Firiteaz", "sat"),
					createLoc("Fiscut", "sat"),
					createLoc("Hunedoara Timișană", "sat"),
								  ]),
			createComuna("Șeitin", [
					createLoc("Șeitin", "sat"),
								  ]),	
			createComuna("Șepreuș", [
					createLoc("Șepreuș", "sat"),
								  ]),
			createComuna("Șicula", [
					createLoc("Șicula", "sat"),
					createLoc("Chereluș", "sat"),
					createLoc("Gurba", "sat"),
								  ]),	
			createComuna("Șilindia", [
					createLoc("Șilindia", "sat"),
					createLoc("Camna", "sat"),
					createLoc("Iercoșeni", "sat"),
					createLoc("Luguzău", "sat"),
					createLoc("Satu Mic", "sat"),
								  ]),
			createComuna("Șimand", [
					createLoc("Șimand", "sat"),
								  ]),	
			createComuna("Șiria", [
					createLoc("Șiria", "sat"),
					createLoc("Galșa", "sat"),
					createLoc("Mâsca", "sat"),
								  ]),
			createComuna("Șiștarovăț", [
					createLoc("Șiștarovăț","sat"),
					createLoc("Cuveșdia","sat"),
					createLoc("Labașinț","sat"),
					createLoc("Varnița","sat"),
								  ]),	
			createComuna("Șofronea", [
					createLoc("Șofronea", "sat"),
					createLoc("Sânpaul", "sat"),
								  ]),			
			createComuna("Tauț", [
					createLoc("Tauț", "sat"),
					createLoc("Minișel", "sat"),
					createLoc("Minișu de Sus", "sat"),
					createLoc("Nadăș", "sat"),
								  ]),	
			createComuna("Târnova", [
					createLoc("Târnova", "sat"),
					createLoc("Agrișu Mare", "sat"),
					createLoc("Arăneag", "sat"),
					createLoc("Chier", "sat"),
					createLoc("Drauț", "sat"),
					createLoc("Dud", "sat"),
								  ]),
			createComuna("Ususău", [
					createLoc("Ususău", "sat"),
					createLoc("Bruznic", "sat"),
					createLoc("Dorgoș", "sat"),
					createLoc("Pătârș", "sat"),
					createLoc("Zăbalț", "sat"),
								  ]),	
			createComuna("Vărădia de Mureș", [
					createLoc("Vărădia de Mureș", "sat"),
					createLoc("Baia", "sat"),
					createLoc("Julița", "sat"),
					createLoc("Lupești", "sat"),
					createLoc("Nicolae Bălcescu", "sat"),
					createLoc("Stejar", "sat"),
								  ]),
			createComuna("Vinga", [
					createLoc("Vinga", "sat"),
					createLoc("Mailat", "sat"),
					createLoc("Mănăștur", "sat"),
								  ]),	
			createComuna("Vârfurile", [
					createLoc("Vârfurile", "sat"),
					createLoc("Avram Iancu", "sat"),
					createLoc("Groși", "sat"),
					createLoc("Lazuri", "sat"),
					createLoc("Măgulicea", "sat"),
					createLoc("Mermești", "sat"),
					createLoc("Poiana", "sat"),
					createLoc("Vidra", "sat"),
								  ]),
			createComuna("Vladimirescu", [
					createLoc("Vladimirescu", "sat"),
					createLoc("Cicir", "sat"),
					createLoc("Horia", "sat"),
					createLoc("Mândruloc", "sat"),
								  ]),	
			createComuna("Zăbrani", [
					createLoc("Zăbrani", "sat"),
					createLoc("Chesinț", "sat"),
					createLoc("Neudorf", "sat"),
								  ]),
			createComuna("Zădăreni", [
					createLoc("Zădăreni", "sat"),
					createLoc("Bodrogu Nou", "sat"),
					createLoc("Horia", "sat"),
					createLoc("Mândruloc", "sat"),
								  ]),	
			createComuna("Zărand", [
					createLoc("Zărand", "sat"),
					createLoc("Cintei", "sat"),
					createLoc("Neudorf", "sat"),
								  ]),
			createComuna("Zerind", [
					createLoc("Zerind", "sat"),
					createLoc("Iermata Neagră", "sat"),
								  ]),	
			createComuna("Zimandu Nou", [
					createLoc("Zimandu Nou", "sat"),
					createLoc("Andrei Șaguna", "sat"),
					createLoc("Zimandcuz", "sat"),
								  ]),								  
			
];
?>