<?php
$comune =[
        createComuna("Almaș", [
            createLoc("Almaș", "sat", createAdresaCompleta("sat Almaș, comuna Almaș, judetul ARAD, România")),
            createLoc("Cil", "sat", createAdresaCompleta("sat Cil, comuna Almaș, judetul ARAD, România")),
            createLoc("Joia Mare", "sat", createAdresaCompleta("sat Joia Mare, comuna Almaș, judetul ARAD, România")),
            createLoc("Rădești", "sat", createAdresaCompleta("sat Rădești, comuna Almaș, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Almaș, judetul ARAD, România")),  
        createComuna("Apateu", [
            createLoc("Apateu", "sat", createAdresaCompleta("sat Apateu, comuna Apateu, judetul ARAD, România")),
            createLoc("Berechiu", "sat", createAdresaCompleta("sat Berechiu, comuna Apateu, judetul ARAD, România")),
            createLoc("Moțiori", "sat", createAdresaCompleta("sat Moțiori, comuna Apateu, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Apateu, judetul ARAD, România")),
        createComuna("Archiș", [
            createLoc("Archiș", "sat", createAdresaCompleta("sat Archiș, comuna Archiș, judetul ARAD, România")),
            createLoc("Bârzești", "sat", createAdresaCompleta("sat Bârzești, comuna Archiș, judetul ARAD, România")),
            createLoc("Groșeni", "sat", createAdresaCompleta("sat Groșeni, comuna Archiș, judetul ARAD, România")),
            createLoc("Nermiș", "sat", createAdresaCompleta("sat Nermiș, comuna Archiș, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Archiș, judetul ARAD, România")),  
        createComuna("Bata", [
            createLoc("Bata", "sat", createAdresaCompleta("sat Bata, comuna Bata, judetul ARAD, România")),
            createLoc("Bacău de Mijloc", "sat", createAdresaCompleta("sat Bacău de Mijloc, comuna Bata, judetul ARAD, România")),
            createLoc("Bulci", "sat", createAdresaCompleta("sat Bulci, comuna Bata, judetul ARAD, România")),
            createLoc("Țela", "sat", createAdresaCompleta("sat Țela, comuna Bata, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Bata, judetul ARAD, România")),  
        createComuna("Beliu", [
            createLoc("Beliu", "sat", createAdresaCompleta("sat Beliu, comuna Beliu, judetul ARAD, România")),
            createLoc("Benești", "sat", createAdresaCompleta("sat Benești, comuna Beliu, judetul ARAD, România")),
            createLoc("Bochia", "sat", createAdresaCompleta("sat Bochia, comuna Beliu, judetul ARAD, România")),
            createLoc("Secaci", "sat", createAdresaCompleta("sat Secaci, comuna Beliu, judetul ARAD, România")),
            createLoc("Tăgădău", "sat", createAdresaCompleta("sat Tăgădău, comuna Beliu, judetul ARAD, România")),
            createLoc("Vasile Goldiș", "sat", createAdresaCompleta("sat Vasile Goldiș, comuna Beliu, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Beliu, judetul ARAD, România")),  
        createComuna("Birchiș", [
            createLoc("Birchiș", "sat", createAdresaCompleta("sat Birchiș, comuna Birchiș, judetul ARAD, România")),
            createLoc("Căpălnaș", "sat", createAdresaCompleta("sat Căpălnaș, comuna Birchiș, judetul ARAD, România")),
            createLoc("Ostrov", "sat", createAdresaCompleta("sat Ostrov, comuna Birchiș, judetul ARAD, România")),
            createLoc("Virismort", "sat", createAdresaCompleta("sat Virismort, comuna Birchiș, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Birchiș, judetul ARAD, România")),
        createComuna("Bârsa", [
            createLoc("Bârsa", "sat", createAdresaCompleta("sat Bârsa, comuna Bârsa, judetul ARAD, România")),
            createLoc("Aldești", "sat", createAdresaCompleta("sat Aldești, comuna Bârsa, judetul ARAD, România")),
            createLoc("Hodiș", "sat", createAdresaCompleta("sat Hodiș, comuna Bârsa, judetul ARAD, România")),
            createLoc("Voivodeni", "sat", createAdresaCompleta("sat Voivodeni, comuna Bârsa, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Bârsa, judetul ARAD, România")),  
        createComuna("Bârzava", [
            createLoc("Bârzava", "sat", createAdresaCompleta("sat Bârzava, comuna Bârzava, judetul ARAD, România")),
            createLoc("Bătuța", "sat", createAdresaCompleta("sat Bătuța, comuna Bârzava, judetul ARAD, România")),
            createLoc("Căpruța", "sat", createAdresaCompleta("sat Căpruța, comuna Bârzava, judetul ARAD, România")),
            createLoc("Dumbrăvița", "sat", createAdresaCompleta("sat Dumbrăvița, comuna Bârzava, judetul ARAD, România")),
            createLoc("Groșii Noi", "sat", createAdresaCompleta("sat Groșii Noi, comuna Bârzava, judetul ARAD, România")),
            createLoc("Lalașinț", "sat", createAdresaCompleta("sat Lalașinț, comuna Bârzava, judetul ARAD, România")),
            createLoc("Monoroștia", "sat", createAdresaCompleta("sat Monoroștia, comuna Bârzava, judetul ARAD, România")),
            createLoc("Slatina de Mureș", "sat", createAdresaCompleta("sat Slatina de Mureș, comuna Bârzava, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Bârzava, judetul ARAD, România")),
        createComuna("Bocsig", [
            createLoc("Bocsig", "sat", createAdresaCompleta("sat Bocsig, comuna Bocsig, judetul ARAD, România")),
            createLoc("Mânerău", "sat", createAdresaCompleta("sat Mânerău, comuna Bocsig, judetul ARAD, România")),
            createLoc("Răpsig", "sat", createAdresaCompleta("sat Răpsig, comuna Bocsig, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Bocsig, judetul ARAD, România")),  
        createComuna("Brazii", [
            createLoc("Brazii", "sat", createAdresaCompleta("sat Brazii, comuna Brazii, judetul ARAD, România")),
            createLoc("Buceava-Șoimuș", "sat", createAdresaCompleta("sat Buceava-Șoimuș, comuna Brazii, judetul ARAD, România")),
            createLoc("Iacobini", "sat", createAdresaCompleta("sat Iacobini, comuna Brazii, judetul ARAD, România")),
            createLoc("Mădrigești", "sat", createAdresaCompleta("sat Mădrigești, comuna Brazii, judetul ARAD, România")),
            createLoc("Secaș", "sat", createAdresaCompleta("sat Secaș, comuna Brazii, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Brazii, judetul ARAD, România")),  
        createComuna("Buteni", [
            createLoc("Buteni", "sat", createAdresaCompleta("sat Buteni, comuna Buteni, judetul ARAD, România")),
            createLoc("Berindia", "sat", createAdresaCompleta("sat Berindia, comuna Buteni, judetul ARAD, România")),
            createLoc("Cuied", "sat", createAdresaCompleta("sat Cuied, comuna Buteni, judetul ARAD, România")),
            createLoc("Păulian", "sat", createAdresaCompleta("sat Păulian, comuna Buteni, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Buteni, judetul ARAD, România")),  
        createComuna("Cărand", [
            createLoc("Cărand", "sat", createAdresaCompleta("sat Cărand, comuna Cărand, judetul ARAD, România")),
            createLoc("Seliștea", "sat", createAdresaCompleta("sat Seliștea, comuna Cărand, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Cărand, judetul ARAD, România")),
        createComuna("Cermei", [
            createLoc("Cermei", "sat", createAdresaCompleta("sat Cermei, comuna Cermei, judetul ARAD, România")),
            createLoc("Avram Iancu", "sat", createAdresaCompleta("sat Avram Iancu, comuna Cermei, judetul ARAD, România")),
            createLoc("Șomoșcheș", "sat", createAdresaCompleta("sat Șomoșcheș, comuna Cermei, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Cermei, judetul ARAD, România")),  
        createComuna("Chisindia", [
            createLoc("Chisindia", "sat", createAdresaCompleta("sat Chisindia, comuna Chisindia, judetul ARAD, România")),
            createLoc("Păiușeni", "sat", createAdresaCompleta("sat Păiușeni, comuna Chisindia, judetul ARAD, România")),
            createLoc("Văsoaia", "sat", createAdresaCompleta("sat Văsoaia, comuna Chisindia, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Chisindia, judetul ARAD, România")),
        createComuna("Conop", [
            createLoc("Conop", "sat", createAdresaCompleta("sat Conop, comuna Conop, judetul ARAD, România")),
            createLoc("Belotinț", "sat", createAdresaCompleta("sat Belotinț, comuna Conop, judetul ARAD, România")),
            createLoc("Chelmac", "sat", createAdresaCompleta("sat Chelmac, comuna Conop, judetul ARAD, România")),
            createLoc("Milova", "sat", createAdresaCompleta("sat Milova, comuna Conop, judetul ARAD, România")),
            createLoc("Odvoș", "sat", createAdresaCompleta("sat Odvoș, comuna Conop, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Conop, judetul ARAD, România")),  
        createComuna("Covăsinț", [
            createLoc("Covăsinț", "sat", createAdresaCompleta("sat Covăsinț, comuna Covăsinț, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Covăsinț, judetul ARAD, România")),  
        createComuna("Craiva", [
            createLoc("Craiva", "sat", createAdresaCompleta("sat Craiva, comuna Craiva, judetul ARAD, România")),
            createLoc("Chișlaca", "sat", createAdresaCompleta("sat Chișlaca, comuna Craiva, judetul ARAD, România")),
            createLoc("Ciuntești", "sat", createAdresaCompleta("sat Ciuntești, comuna Craiva, judetul ARAD, România")),
            createLoc("Coroi", "sat", createAdresaCompleta("sat Coroi, comuna Craiva, judetul ARAD, România")),
            createLoc("Mărăuș", "sat", createAdresaCompleta("sat Mărăuș, comuna Craiva, judetul ARAD, România")),
            createLoc("Rogoz de Beliu", "sat", createAdresaCompleta("sat Rogoz de Beliu, comuna Craiva, judetul ARAD, România")),
            createLoc("Stoinești", "sat", createAdresaCompleta("sat Stoinești, comuna Craiva, judetul ARAD, România")),
            createLoc("Susag", "sat", createAdresaCompleta("sat Susag, comuna Craiva, judetul ARAD, România")),
            createLoc("Șiad", "sat", createAdresaCompleta("sat Șiad, comuna Craiva, judetul ARAD, România")),
            createLoc("Tălmaci", "sat", createAdresaCompleta("sat Tălmaci, comuna Craiva, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Craiva, judetul ARAD, România")),  
        createComuna("Dezna", [
            createLoc("Dezna", "sat", createAdresaCompleta("sat Dezna, comuna Dezna, judetul ARAD, România")),
            createLoc("Buhani", "sat", createAdresaCompleta("sat Buhani, comuna Dezna, judetul ARAD, România")),
            createLoc("Laz", "sat", createAdresaCompleta("sat Laz, comuna Dezna, judetul ARAD, România")),
            createLoc("Neagra", "sat", createAdresaCompleta("sat Neagra, comuna Dezna, judetul ARAD, România")),
            createLoc("Slatina de Criș", "sat", createAdresaCompleta("sat Slatina de Criș, comuna Dezna, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Dezna, judetul ARAD, România")),
        createComuna("Dieci", [
            createLoc("Dieci", "sat", createAdresaCompleta("sat Dieci, comuna Dieci, judetul ARAD, România")),
            createLoc("Cociuba", "sat", createAdresaCompleta("sat Cociuba, comuna Dieci, judetul ARAD, România")),
            createLoc("Crocna", "sat", createAdresaCompleta("sat Crocna, comuna Dieci, judetul ARAD, România")),
            createLoc("Revetiș", "sat", createAdresaCompleta("sat Revetiș, comuna Dieci, judetul ARAD, România")),
            createLoc("Roșia", "sat", createAdresaCompleta("sat Roșia, comuna Dieci, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Dieci, judetul ARAD, România")),  
        createComuna("Dorobanți", [
            createLoc("Dorobanți", "sat", createAdresaCompleta("sat Dorobanți, comuna Dorobanți, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Dorobanți, judetul ARAD, România")),  
        createComuna("Fântânele", [
            createLoc("Fântânele", "sat", createAdresaCompleta("sat Fântânele, comuna Fântânele, judetul ARAD, România")),
            createLoc("Tisa Nouă", "sat", createAdresaCompleta("sat Tisa Nouă, comuna Fântânele, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Fântânele, judetul ARAD, România")),  
        createComuna("Felnac", [
            createLoc("Felnac", "sat", createAdresaCompleta("sat Felnac, comuna Felnac, judetul ARAD, România")),
            createLoc("Călugăreni", "sat", createAdresaCompleta("sat Călugăreni, comuna Felnac, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Felnac, judetul ARAD, România")),
        createComuna("Frumușeni", [
            createLoc("Frumușeni", "sat", createAdresaCompleta("sat Frumușeni, comuna Frumușeni, judetul ARAD, România")),
            createLoc("Aluniș", "sat", createAdresaCompleta("sat Aluniș, comuna Frumușeni, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Frumușeni, judetul ARAD, România")),  
        createComuna("Ghioroc", [
            createLoc("Ghioroc", "sat", createAdresaCompleta("sat Ghioroc, comuna Ghioroc, judetul ARAD, România")),
            createLoc("Cuvin", "sat", createAdresaCompleta("sat Cuvin, comuna Ghioroc, judetul ARAD, România")),
            createLoc("Miniș", "sat", createAdresaCompleta("sat Miniș, comuna Ghioroc, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Ghioroc, judetul ARAD, România")),
        createComuna("Grăniceri", [
            createLoc("Grăniceri", "sat", createAdresaCompleta("sat Grăniceri, comuna Grăniceri, judetul ARAD, România")),
            createLoc("Șiclău", "sat", createAdresaCompleta("sat Șiclău, comuna Grăniceri, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Grăniceri, judetul ARAD, România")),  
        createComuna("Gurahonț", [
            createLoc("Gurahonț", "sat", createAdresaCompleta("sat Gurahonț, comuna Gurahonț, judetul ARAD, România")),
            createLoc("Bonțești", "sat", createAdresaCompleta("sat Bonțești, comuna Gurahonț, judetul ARAD, România")),
            createLoc("Dulcele", "sat", createAdresaCompleta("sat Dulcele, comuna Gurahonț, judetul ARAD, România")),
            createLoc("Feniș", "sat", createAdresaCompleta("sat Feniș, comuna Gurahonț, judetul ARAD, România")),
            createLoc("Honțișor", "sat", createAdresaCompleta("sat Honțișor, comuna Gurahonț, judetul ARAD, România")),
            createLoc("Iosaș", "sat", createAdresaCompleta("sat Iosaș, comuna Gurahonț, judetul ARAD, România")),
            createLoc("Mustești", "sat", createAdresaCompleta("sat Mustești, comuna Gurahonț, judetul ARAD, România")),
            createLoc("Pescari", "sat", createAdresaCompleta("sat Pescari, comuna Gurahonț, judetul ARAD, România")),
            createLoc("Valea Mare", "sat", createAdresaCompleta("sat Valea Mare, comuna Gurahonț, judetul ARAD, România")),
            createLoc("Zimbru", "sat", createAdresaCompleta("sat Zimbru, comuna Gurahonț, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Gurahonț, judetul ARAD, România")),
        createComuna("Hălmagiu", [
            createLoc("Hălmagiu", "sat", createAdresaCompleta("sat Hălmagiu, comuna Hălmagiu, judetul ARAD, România")),
            createLoc("Bănești", "sat", createAdresaCompleta("sat Bănești, comuna Hălmagiu, judetul ARAD, România")),
            createLoc("Bodești", "sat", createAdresaCompleta("sat Bodești, comuna Hălmagiu, judetul ARAD, România")),
            createLoc("Brusturi", "sat", createAdresaCompleta("sat Brusturi, comuna Hălmagiu, judetul ARAD, România")),
            createLoc("Cristești", "sat", createAdresaCompleta("sat Cristești, comuna Hălmagiu, judetul ARAD, România")),
            createLoc("Ionești", "sat", createAdresaCompleta("sat Ionești, comuna Hălmagiu, judetul ARAD, România")),
            createLoc("Leasa", "sat", createAdresaCompleta("sat Leasa, comuna Hălmagiu, judetul ARAD, România")),
            createLoc("Leștioara", "sat", createAdresaCompleta("sat Leștioara, comuna Hălmagiu, judetul ARAD, România")),
            createLoc("Poienari", "sat", createAdresaCompleta("sat Poienari, comuna Hălmagiu, judetul ARAD, România")),
            createLoc("Tisa", "sat", createAdresaCompleta("sat Tisa, comuna Hălmagiu, judetul ARAD, România")),
            createLoc("Țărmure", "sat", createAdresaCompleta("sat Țărmure, comuna Hălmagiu, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Hălmagiu, judetul ARAD, România")),  
        createComuna("Hălmăgel", [
            createLoc("Hălmăgel", "sat", createAdresaCompleta("sat Hălmăgel, comuna Hălmăgel, judetul ARAD, România")),
            createLoc("Luncșoara", "sat", createAdresaCompleta("sat Luncșoara, comuna Hălmăgel, judetul ARAD, România")),
            createLoc("Sârbi", "sat", createAdresaCompleta("sat Sârbi, comuna Hălmăgel, judetul ARAD, România")),
            createLoc("Târnăvița", "sat", createAdresaCompleta("sat Târnăvița, comuna Hălmăgel, judetul ARAD, România")),
            createLoc("Țohești", "sat", createAdresaCompleta("sat Țohești, comuna Hălmăgel, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Hălmăgel, judetul ARAD, România")),
        createComuna("Hășmaș", [
            createLoc("Hășmaș", "sat", createAdresaCompleta("sat Hășmaș, comuna Hășmaș, judetul ARAD, România")),
            createLoc("Agrișu Mic", "sat", createAdresaCompleta("sat Agrișu Mic, comuna Hășmaș, judetul ARAD, România")),
            createLoc("Botfei", "sat", createAdresaCompleta("sat Botfei, comuna Hășmaș, judetul ARAD, România")),
            createLoc("Clit", "sat", createAdresaCompleta("sat Clit, comuna Hășmaș, judetul ARAD, România")),
            createLoc("Comănești", "sat", createAdresaCompleta("sat Comănești, comuna Hășmaș, judetul ARAD, România")),
            createLoc("Urvișu de Beliu", "sat", createAdresaCompleta("sat Urvișu de Beliu, comuna Hășmaș, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Hășmaș, judetul ARAD, România")),  
        createComuna("Ignești", [
            createLoc("Ignești", "sat", createAdresaCompleta("sat Ignești, comuna Ignești, judetul ARAD, România")),
            createLoc("Minead", "sat", createAdresaCompleta("sat Minead, comuna Ignești, judetul ARAD, România")),
            createLoc("Nădălbești", "sat", createAdresaCompleta("sat Nădălbești, comuna Ignești, judetul ARAD, România")),
            createLoc("Susani", "sat", createAdresaCompleta("sat Susani, comuna Ignești, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Ignești, judetul ARAD, România")),
        createComuna("Iratoșu", [
            createLoc("Iratoșu", "sat", createAdresaCompleta("sat Iratoșu, comuna Iratoșu, judetul ARAD, România")),
            createLoc("Variașu Mare", "sat", createAdresaCompleta("sat Variașu Mare, comuna Iratoșu, judetul ARAD, România")),
            createLoc("Variașu Mic", "sat", createAdresaCompleta("sat Variașu Mic, comuna Iratoșu, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Iratoșu, judetul ARAD, România")),  
        createComuna("Livada", [
            createLoc("Livada", "sat", createAdresaCompleta("sat Livada, comuna Livada, judetul ARAD, România")),
            createLoc("Sânleani", "sat", createAdresaCompleta("sat Sânleani, comuna Livada, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Livada, judetul ARAD, România")),
        createComuna("Macea", [
            createLoc("Macea", "sat", createAdresaCompleta("sat Macea, comuna Macea, judetul ARAD, România")),
            createLoc("Sânmartin", "sat", createAdresaCompleta("sat Sânmartin, comuna Macea, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Macea, judetul ARAD, România")),  
        createComuna("Mișca", [
            createLoc("Mișca", "sat", createAdresaCompleta("sat Mișca, comuna Mișca, judetul ARAD, România")),
            createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Mișca, judetul ARAD, România")),
            createLoc("Vânători", "sat", createAdresaCompleta("sat Vânători, comuna Mișca, judetul ARAD, România")),
            createLoc("Zerindu Mic", "sat", createAdresaCompleta("sat Zerindu Mic, comuna Mișca, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Mișca, judetul ARAD, România")),
        createComuna("Moneasa", [
            createLoc("Moneasa", "sat", createAdresaCompleta("sat Moneasa, comuna Moneasa, judetul ARAD, România")),
            createLoc("Rănușa", "sat", createAdresaCompleta("sat Rănușa, comuna Moneasa, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Moneasa, judetul ARAD, România")),  
        createComuna("Olari", [
            createLoc("Olari", "sat", createAdresaCompleta("sat Olari, comuna Olari, judetul ARAD, România")),
            createLoc("Sintea Mică", "sat", createAdresaCompleta("sat Sintea Mică, comuna Olari, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Olari, judetul ARAD, România")),
        createComuna("Păuliș", [
            createLoc("Păuliș", "sat", createAdresaCompleta("sat Păuliș, comuna Păuliș, judetul ARAD, România")),
            createLoc("Barațca", "sat", createAdresaCompleta("sat Barațca, comuna Păuliș, judetul ARAD, România")),
            createLoc("Cladova", "sat", createAdresaCompleta("sat Cladova, comuna Păuliș, judetul ARAD, România")),
            createLoc("Sâmbăteni", "sat", createAdresaCompleta("sat Sâmbăteni, comuna Păuliș, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Păuliș, judetul ARAD, România")),  
        createComuna("Peregu Mare", [
            createLoc("Peregu Mare", "sat", createAdresaCompleta("sat Peregu Mare, comuna Peregu Mare, judetul ARAD, România")),
            createLoc("Peregu Mic", "sat", createAdresaCompleta("sat Peregu Mic, comuna Peregu Mare, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Peregu Mare, judetul ARAD, România")),
        createComuna("Petriș", [
            createLoc("Petriș", "sat", createAdresaCompleta("sat Petriș, comuna Petriș, judetul ARAD, România")),
            createLoc("Corbești", "sat", createAdresaCompleta("sat Corbești, comuna Petriș, judetul ARAD, România")),
            createLoc("Ilteu", "sat", createAdresaCompleta("sat Ilteu, comuna Petriș, judetul ARAD, România")),
            createLoc("Obârșia", "sat", createAdresaCompleta("sat Obârșia, comuna Petriș, judetul ARAD, România")),
            createLoc("Roșia Nouă", "sat", createAdresaCompleta("sat Roșia Nouă, comuna Petriș, judetul ARAD, România")),
            createLoc("Seliște", "sat", createAdresaCompleta("sat Seliște, comuna Petriș, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Petriș, judetul ARAD, România")),  
        createComuna("Pilu", [
            createLoc("Pilu", "sat", createAdresaCompleta("sat Pilu, comuna Pilu, judetul ARAD, România")),
            createLoc("Vărșand", "sat", createAdresaCompleta("sat Vărșand, comuna Pilu, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Pilu, judetul ARAD, România")),
        createComuna("Pleșcuța", [
            createLoc("Pleșcuța", "sat", createAdresaCompleta("sat Pleșcuța, comuna Pleșcuța, judetul ARAD, România")),
            createLoc("Aciuța", "sat", createAdresaCompleta("sat Aciuța, comuna Pleșcuța, judetul ARAD, România")),
            createLoc("Budești", "sat", createAdresaCompleta("sat Budești, comuna Pleșcuța, judetul ARAD, România")),
            createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, comuna Pleșcuța, judetul ARAD, România")),
            createLoc("Gura Văii", "sat", createAdresaCompleta("sat Gura Văii, comuna Pleșcuța, judetul ARAD, România")),
            createLoc("Rostoci", "sat", createAdresaCompleta("sat Rostoci, comuna Pleșcuța, judetul ARAD, România")),
            createLoc("Tălagiu", "sat", createAdresaCompleta("sat Tălagiu, comuna Pleșcuța, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Pleșcuța, judetul ARAD, România")),  
        createComuna("Săvârșin", [
            createLoc("Săvârșin", "sat", createAdresaCompleta("sat Săvârșin, comuna Săvârșin, judetul ARAD, România")),
            createLoc("Căprioara", "sat", createAdresaCompleta("sat Căprioara, comuna Săvârșin, judetul ARAD, România")),
            createLoc("Cuiaș", "sat", createAdresaCompleta("sat Cuiaș, comuna Săvârșin, judetul ARAD, România")),
            createLoc("Hălăliș", "sat", createAdresaCompleta("sat Hălăliș, comuna Săvârșin, judetul ARAD, România")),
            createLoc("Pârnești", "sat", createAdresaCompleta("sat Pâtnești, comuna Săvârșin, judetul ARAD, România")),
            createLoc("Temeșești", "sat", createAdresaCompleta("sat Temeșești, comuna Săvârșin, judetul ARAD, România")),
            createLoc("Toc", "sat", createAdresaCompleta("sat Toc, comuna Săvârșin, judetul ARAD, România")),
            createLoc("Troaș", "sat", createAdresaCompleta("sat Troaș, comuna Săvârșin, judetul ARAD, România")),
            createLoc("Valea Mare", "sat", createAdresaCompleta("sat Valea Mare, comuna Săvârșin, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Săvârșin, judetul ARAD, România")),
        createComuna("Secusigiu", [
            createLoc("Secusigiu", "sat", createAdresaCompleta("sat Secusigiu, comuna Secusigiu, judetul ARAD, România")),
            createLoc("Munar", "sat", createAdresaCompleta("sat Munar, comuna Secusigiu, judetul ARAD, România")),
            createLoc("Satu Mare", "sat", createAdresaCompleta("sat Satu Mare, comuna Secusigiu, judetul ARAD, România")),
            createLoc("Sânpetru German", "sat", createAdresaCompleta("sat Sânpetru German, comuna Secusigiu, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Secusigiu, judetul ARAD, România")),  
        createComuna("Seleuș", [
            createLoc("Seleuș", "sat", createAdresaCompleta("sat Seleuș, comuna Seleuș, judetul ARAD, România")),
            createLoc("Iermata", "sat", createAdresaCompleta("sat Iermata, comuna Seleuș, judetul ARAD, România")),
            createLoc("Moroda", "sat", createAdresaCompleta("sat Moroda, comuna Seleuș, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Seleuș, judetul ARAD, România")),
        createComuna("Semlac", [
            createLoc("Semlac", "sat", createAdresaCompleta("sat Semlac, comuna Semlac, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Semlac, judetul ARAD, România")),  
        createComuna("Sintea Mare", [
            createLoc("Sintea Mare", "sat", createAdresaCompleta("sat Sintea Mare, comuna Sintea Mare, judetul ARAD, România")),
            createLoc("Adea", "sat", createAdresaCompleta("sat Adea, comuna Sintea Mare, judetul ARAD, România")),
            createLoc("Țipar", "sat", createAdresaCompleta("sat Țipar, comuna Sintea Mare, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Sintea Mare, judetul ARAD, România")),
        createComuna("Socodor", [
            createLoc("Socodor", "sat", createAdresaCompleta("sat Socodor, comuna Socodor, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Socodor, judetul ARAD, România")),  
        createComuna("Șagu", [
            createLoc("Șagu", "sat", createAdresaCompleta("sat Șagu, comuna Șagu, judetul ARAD, România")),
            createLoc("Cruceni", "sat", createAdresaCompleta("sat Cruceni, comuna Șagu, judetul ARAD, România")),
            createLoc("Firiteaz", "sat", createAdresaCompleta("sat Firiteaz, comuna Șagu, judetul ARAD, România")),
            createLoc("Fiscut", "sat", createAdresaCompleta("sat Fiscut, comuna Șagu, judetul ARAD, România")),
            createLoc("Hunedoara Timișană", "sat", createAdresaCompleta("sat Hunedoara Timișană, comuna Șagu, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Șagu, judetul ARAD, România")),
        createComuna("Șeitin", [
            createLoc("Șeitin", "sat", createAdresaCompleta("sat Șeitin, comuna Șeitin, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Șeitin, judetul ARAD, România")),  
        createComuna("Șepreuș", [
            createLoc("Șepreuș", "sat", createAdresaCompleta("sat Șepreuș, comuna Șepreuș, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Șepreuș, judetul ARAD, România")),
        createComuna("Șicula", [
            createLoc("Șicula", "sat", createAdresaCompleta("sat Șicula, comuna Șicula, judetul ARAD, România")),
            createLoc("Chereluș", "sat", createAdresaCompleta("sat Chereluș, comuna Șicula, judetul ARAD, România")),
            createLoc("Gurba", "sat", createAdresaCompleta("sat Gurba, comuna Șicula, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Șicula, judetul ARAD, România")),  
        createComuna("Șilindia", [
            createLoc("Șilindia", "sat", createAdresaCompleta("sat Șilindia, comuna Șilindia, judetul ARAD, România")),
            createLoc("Camna", "sat", createAdresaCompleta("sat Camna, comuna Șilindia, judetul ARAD, România")),
            createLoc("Iercoșeni", "sat", createAdresaCompleta("sat Iercoșeni, comuna Șilindia, judetul ARAD, România")),
            createLoc("Luguzău", "sat", createAdresaCompleta("sat Luguzău, comuna Șilindia, judetul ARAD, România")),
            createLoc("Satu Mic", "sat", createAdresaCompleta("sat Satu Mic, comuna Șilindia, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Șilindia, judetul ARAD, România")),
        createComuna("Șimand", [
            createLoc("Șimand", "sat", createAdresaCompleta("sat Șimand, comuna Șimand, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Șimand, judetul ARAD, România")),  
        createComuna("Șiria", [
            createLoc("Șiria", "sat", createAdresaCompleta("sat Șiria, comuna Șiria, judetul ARAD, România")),
            createLoc("Galșa", "sat", createAdresaCompleta("sat Galșa, comuna Șiria, judetul ARAD, România")),
            createLoc("Mâsca", "sat", createAdresaCompleta("sat Mâsca, comuna Șiria, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Șiria, judetul ARAD, România")),
        createComuna("Șiștarovăț", [
            createLoc("Șiștarovăț", "sat", createAdresaCompleta("sat Șiștarovăț, comuna Șiștarovăț, judetul ARAD, România")),
            createLoc("Cuveșdia", "sat", createAdresaCompleta("sat Cuveșdia, comuna Șiștarovăț, judetul ARAD, România")),
            createLoc("Labașinț", "sat", createAdresaCompleta("sat Labașinț, comuna Șiștarovăț, judetul ARAD, România")),
            createLoc("Varnița", "sat", createAdresaCompleta("sat Varnița, comuna Șiștarovăț, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Șiștarovăț, judetul ARAD, România")),  
        createComuna("Șofronea", [
            createLoc("Șofronea", "sat", createAdresaCompleta("sat Șofronea, comuna Șofronea, judetul ARAD, România")),
            createLoc("Sânpaul", "sat", createAdresaCompleta("sat Sânpaul, comuna Șofronea, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Șofronea, judetul ARAD, România")),          
        createComuna("Tauț", [
            createLoc("Tauț", "sat", createAdresaCompleta("sat Tauț, comuna Tauț, judetul ARAD, România")),
            createLoc("Minișel", "sat", createAdresaCompleta("sat Minișel, comuna Tauț, judetul ARAD, România")),
            createLoc("Minișu de Sus", "sat", createAdresaCompleta("sat Minișu de Sus, comuna Tauț, judetul ARAD, România")),
            createLoc("Nadăș", "sat", createAdresaCompleta("sat Nadăș, comuna Tauț, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Tauț, judetul ARAD, România")),  
        createComuna("Târnova", [
            createLoc("Târnova", "sat", createAdresaCompleta("sat Târnova, comuna Târnova, judetul ARAD, România")),
            createLoc("Agrișu Mare", "sat", createAdresaCompleta("sat Agrișu Mare, comuna Târnova, judetul ARAD, România")),
            createLoc("Arăneag", "sat", createAdresaCompleta("sat Arăneag, comuna Târnova, judetul ARAD, România")),
            createLoc("Chier", "sat", createAdresaCompleta("sat Chier, comuna Târnova, judetul ARAD, România")),
            createLoc("Drauț", "sat", createAdresaCompleta("sat Drauț, comuna Târnova, judetul ARAD, România")),
            createLoc("Dud", "sat", createAdresaCompleta("sat Dud, comuna Târnova, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Târnova, judetul ARAD, România")),
        createComuna("Ususău", [
            createLoc("Ususău", "sat", createAdresaCompleta("sat Ususău, comuna Ususău, judetul ARAD, România")),
            createLoc("Bruznic", "sat", createAdresaCompleta("sat Bruznic, comuna Ususău, judetul ARAD, România")),
            createLoc("Dorgoș", "sat", createAdresaCompleta("sat Dorgoș, comuna Ususău, judetul ARAD, România")),
            createLoc("Pătârș", "sat", createAdresaCompleta("sat Pătârș, comuna Ususău, judetul ARAD, România")),
            createLoc("Zăbalț", "sat", createAdresaCompleta("sat Zăbalț, comuna Ususău, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Ususău, judetul ARAD, România")),  
        createComuna("Vărădia de Mureș", [
            createLoc("Vărădia de Mureș", "sat", createAdresaCompleta("sat Vărădia de Mureș, comuna Vărădia de Mureș, judetul ARAD, România")),
            createLoc("Baia", "sat", createAdresaCompleta("sat Baia, comuna Vărădia de Mureș, judetul ARAD, România")),
            createLoc("Julița", "sat", createAdresaCompleta("sat Julița, comuna Vărădia de Mureș, judetul ARAD, România")),
            createLoc("Lupești", "sat", createAdresaCompleta("sat Lupești, comuna Vărădia de Mureș, judetul ARAD, România")),
            createLoc("Nicolae Bălcescu", "sat", createAdresaCompleta("sat Nicolae Bălcescu, comuna Vărădia de Mureș, judetul ARAD, România")),
            createLoc("Stejar", "sat", createAdresaCompleta("sat Stejar, comuna Vărădia de Mureș, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Vărădia de Mureș, judetul ARAD, România")),
        createComuna("Vinga", [
            createLoc("Vinga", "sat", createAdresaCompleta("sat Vinga, comuna Vinga, judetul ARAD, România")),
            createLoc("Mailat", "sat", createAdresaCompleta("sat Mailat, comuna Vinga, judetul ARAD, România")),
            createLoc("Mănăștur", "sat", createAdresaCompleta("sat Mănăștur, comuna Vinga, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Vinga, judetul ARAD, România")),  
        createComuna("Vârfurile", [
            createLoc("Vârfurile", "sat", createAdresaCompleta("sat Vârfurile, comuna Vârfurile, judetul ARAD, România")),
            createLoc("Avram Iancu", "sat", createAdresaCompleta("sat Avram Iancu, comuna Vârfurile, judetul ARAD, România")),
            createLoc("Groși", "sat", createAdresaCompleta("sat Groși, comuna Vârfurile, judetul ARAD, România")),
            createLoc("Lazuri", "sat", createAdresaCompleta("sat Lazuri, comuna Vârfurile, judetul ARAD, România")),
            createLoc("Măgulicea", "sat", createAdresaCompleta("sat Măgulicea, comuna Vârfurile, judetul ARAD, România")),
            createLoc("Mermești", "sat", createAdresaCompleta("sat Mermești, comuna Vârfurile, judetul ARAD, România")),
            createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Vârfurile, judetul ARAD, România")),
            createLoc("Vidra", "sat", createAdresaCompleta("sat Vidra, comuna Vârfurile, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Vârfurile, judetul ARAD, România")),
        createComuna("Vladimirescu", [
            createLoc("Vladimirescu", "sat", createAdresaCompleta("sat Vladimirescu, comuna Vladimirescu, judetul ARAD, România")),
            createLoc("Cicir", "sat", createAdresaCompleta("sat Cicir, comuna Vladimirescu, judetul ARAD, România")),
            createLoc("Horia", "sat", createAdresaCompleta("sat Horia, comuna Vladimirescu, judetul ARAD, România")),
            createLoc("Mândruloc", "sat", createAdresaCompleta("sat Mândruloc, comuna Vladimirescu, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Vladimirescu, judetul ARAD, România")),  
        createComuna("Zăbrani", [
            createLoc("Zăbrani", "sat", createAdresaCompleta("sat Zăbrani, comuna Zăbrani, judetul ARAD, România")),
            createLoc("Chesinț", "sat", createAdresaCompleta("sat Chesinț, comuna Zăbrani, judetul ARAD, România")),
            createLoc("Neudorf", "sat", createAdresaCompleta("sat Neudorf, comuna Zăbrani, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Zăbrani, judetul ARAD, România")),
        createComuna("Zădăreni", [
            createLoc("Zădăreni", "sat", createAdresaCompleta("sat Zădăreni, comuna Zădăreni, judetul ARAD, România")),
            createLoc("Bodrogu Nou", "sat", createAdresaCompleta("sat Bodrogu Nou, comuna Zădăreni, judetul ARAD, România")),
            createLoc("Horia", "sat", createAdresaCompleta("sat Horia, comuna Zădăreni, judetul ARAD, România")),
            createLoc("Mândruloc", "sat", createAdresaCompleta("sat Mândruloc, comuna Zădăreni, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Zădăreni, judetul ARAD, România")),  
        createComuna("Zărand", [
            createLoc("Zărand", "sat", createAdresaCompleta("sat Zărand, comuna Zărand, judetul ARAD, România")),
            createLoc("Cintei", "sat", createAdresaCompleta("sat Cintei, comuna Zărand, judetul ARAD, România")),
            createLoc("Neudorf", "sat", createAdresaCompleta("sat Neudorf, comuna Zărand, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Zărand, judetul ARAD, România")),
        createComuna("Zerind", [
            createLoc("Zerind", "sat", createAdresaCompleta("sat Zerind, comuna Zerind, judetul ARAD, România")),
            createLoc("Iermata Neagră", "sat", createAdresaCompleta("sat Iermata Neagră, comuna Zerind, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Zerind, judetul ARAD, România")),  
        createComuna("Zimandu Nou", [
            createLoc("Zimandu Nou", "sat", createAdresaCompleta("sat Zimandu Nou, comuna Zimandu Nou, judetul ARAD, România")),
            createLoc("Andrei Șaguna", "sat", createAdresaCompleta("sat Andrei Șaguna, comuna Zimandu Nou, judetul ARAD, România")),
            createLoc("Zimandcuz", "sat", createAdresaCompleta("sat Zimandcuz, comuna Zimandu Nou, judetul ARAD, România")),
        ], createAdresaCompleta("comuna Zimandu Nou, judetul ARAD, România")),                                  
        
];
?>
