<?php
$comune =[
        createComuna("Almaș", [
            createLoc("Almaș", "sat", createAdresaCompleta("sat Almaș, comuna Almaș, judetul ARAD, România", "sat Almas, comuna Almas, judetul ARAD, Romania")),
            createLoc("Cil", "sat", createAdresaCompleta("sat Cil, comuna Almaș, judetul ARAD, România", "sat Cil, comuna Almas, judetul ARAD, Romania")),
            createLoc("Joia Mare", "sat", createAdresaCompleta("sat Joia Mare, comuna Almaș, judetul ARAD, România", "sat Joia Mare, comuna Almas, judetul ARAD, Romania")),
            createLoc("Rădești", "sat", createAdresaCompleta("sat Rădești, comuna Almaș, judetul ARAD, România", "sat Radesti, comuna Almas, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Almaș, judetul ARAD, România", "comuna Almas, judetul ARAD, Romania")),  
        createComuna("Apateu", [
            createLoc("Apateu", "sat", createAdresaCompleta("sat Apateu, comuna Apateu, judetul ARAD, România", "sat Apateu, comuna Apateu, judetul ARAD, Romania")),
            createLoc("Berechiu", "sat", createAdresaCompleta("sat Berechiu, comuna Apateu, judetul ARAD, România", "sat Berechiu, comuna Apateu, judetul ARAD, Romania")),
            createLoc("Moțiori", "sat", createAdresaCompleta("sat Moțiori, comuna Apateu, judetul ARAD, România", "sat Motiori, comuna Apateu, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Apateu, judetul ARAD, România", "comuna Apateu, judetul ARAD, Romania")),
        createComuna("Archiș", [
            createLoc("Archiș", "sat", createAdresaCompleta("sat Archiș, comuna Archiș, judetul ARAD, România", "sat Archis, comuna Archis, judetul ARAD, Romania")),
            createLoc("Bârzești", "sat", createAdresaCompleta("sat Bârzești, comuna Archiș, judetul ARAD, România", "sat Barzesti, comuna Archis, judetul ARAD, Romania")),
            createLoc("Groșeni", "sat", createAdresaCompleta("sat Groșeni, comuna Archiș, judetul ARAD, România", "sat Groseni, comuna Archis, judetul ARAD, Romania")),
            createLoc("Nermiș", "sat", createAdresaCompleta("sat Nermiș, comuna Archiș, judetul ARAD, România", "sat Nermis, comuna Archis, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Archiș, judetul ARAD, România", "comuna Archis, judetul ARAD, Romania")),  
        createComuna("Bata", [
            createLoc("Bata", "sat", createAdresaCompleta("sat Bata, comuna Bata, judetul ARAD, România", "sat Bata, comuna Bata, judetul ARAD, Romania")),
            createLoc("Bacău de Mijloc", "sat", createAdresaCompleta("sat Bacău de Mijloc, comuna Bata, judetul ARAD, România", "sat Bacau de Mijloc, comuna Bata, judetul ARAD, Romania")),
            createLoc("Bulci", "sat", createAdresaCompleta("sat Bulci, comuna Bata, judetul ARAD, România", "sat Bulci, comuna Bata, judetul ARAD, Romania")),
            createLoc("Țela", "sat", createAdresaCompleta("sat Țela, comuna Bata, judetul ARAD, România", "sat Tela, comuna Bata, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Bata, judetul ARAD, România", "comuna Bata, judetul ARAD, Romania")),  
        createComuna("Beliu", [
            createLoc("Beliu", "sat", createAdresaCompleta("sat Beliu, comuna Beliu, judetul ARAD, România", "sat Beliu, comuna Beliu, judetul ARAD, Romania")),
            createLoc("Benești", "sat", createAdresaCompleta("sat Benești, comuna Beliu, judetul ARAD, România", "sat Benesti, comuna Beliu, judetul ARAD, Romania")),
            createLoc("Bochia", "sat", createAdresaCompleta("sat Bochia, comuna Beliu, judetul ARAD, România", "sat Bochia, comuna Beliu, judetul ARAD, Romania")),
            createLoc("Secaci", "sat", createAdresaCompleta("sat Secaci, comuna Beliu, judetul ARAD, România", "sat Secaci, comuna Beliu, judetul ARAD, Romania")),
            createLoc("Tăgădău", "sat", createAdresaCompleta("sat Tăgădău, comuna Beliu, judetul ARAD, România", "sat Tagadau, comuna Beliu, judetul ARAD, Romania")),
            createLoc("Vasile Goldiș", "sat", createAdresaCompleta("sat Vasile Goldiș, comuna Beliu, judetul ARAD, România", "sat Vasile Goldis, comuna Beliu, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Beliu, judetul ARAD, România", "comuna Beliu, judetul ARAD, Romania")),  
        createComuna("Birchiș", [
            createLoc("Birchiș", "sat", createAdresaCompleta("sat Birchiș, comuna Birchiș, judetul ARAD, România", "sat Birchis, comuna Birchis, judetul ARAD, Romania")),
            createLoc("Căpălnaș", "sat", createAdresaCompleta("sat Căpălnaș, comuna Birchiș, judetul ARAD, România", "sat Capalnas, comuna Birchis, judetul ARAD, Romania")),
            createLoc("Ostrov", "sat", createAdresaCompleta("sat Ostrov, comuna Birchiș, judetul ARAD, România", "sat Ostrov, comuna Birchis, judetul ARAD, Romania")),
            createLoc("Virismort", "sat", createAdresaCompleta("sat Virismort, comuna Birchiș, judetul ARAD, România", "sat Virismort, comuna Birchis, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Birchiș, judetul ARAD, România", "comuna Birchis, judetul ARAD, Romania")),
        createComuna("Bârsa", [
            createLoc("Bârsa", "sat", createAdresaCompleta("sat Bârsa, comuna Bârsa, judetul ARAD, România", "sat Barsa, comuna Barsa, judetul ARAD, Romania")),
            createLoc("Aldești", "sat", createAdresaCompleta("sat Aldești, comuna Bârsa, judetul ARAD, România", "sat Aldesti, comuna Barsa, judetul ARAD, Romania")),
            createLoc("Hodiș", "sat", createAdresaCompleta("sat Hodiș, comuna Bârsa, judetul ARAD, România", "sat Hodis, comuna Barsa, judetul ARAD, Romania")),
            createLoc("Voivodeni", "sat", createAdresaCompleta("sat Voivodeni, comuna Bârsa, judetul ARAD, România", "sat Voivodeni, comuna Barsa, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Bârsa, judetul ARAD, România", "comuna Barsa, judetul ARAD, Romania")),  
        createComuna("Bârzava", [
            createLoc("Bârzava", "sat", createAdresaCompleta("sat Bârzava, comuna Bârzava, judetul ARAD, România", "sat Barzava, comuna Barzava, judetul ARAD, Romania")),
            createLoc("Bătuța", "sat", createAdresaCompleta("sat Bătuța, comuna Bârzava, judetul ARAD, România", "sat Batuta, comuna Barzava, judetul ARAD, Romania")),
            createLoc("Căpruța", "sat", createAdresaCompleta("sat Căpruța, comuna Bârzava, judetul ARAD, România", "sat Capruta, comuna Barzava, judetul ARAD, Romania")),
            createLoc("Dumbrăvița", "sat", createAdresaCompleta("sat Dumbrăvița, comuna Bârzava, judetul ARAD, România", "sat Dumbravita, comuna Barzava, judetul ARAD, Romania")),
            createLoc("Groșii Noi", "sat", createAdresaCompleta("sat Groșii Noi, comuna Bârzava, judetul ARAD, România", "sat Grosii Noi, comuna Barzava, judetul ARAD, Romania")),
            createLoc("Lalașinț", "sat", createAdresaCompleta("sat Lalașinț, comuna Bârzava, judetul ARAD, România", "sat Lalasint, comuna Barzava, judetul ARAD, Romania")),
            createLoc("Monoroștia", "sat", createAdresaCompleta("sat Monoroștia, comuna Bârzava, judetul ARAD, România", "sat Monorostia, comuna Barzava, judetul ARAD, Romania")),
            createLoc("Slatina de Mureș", "sat", createAdresaCompleta("sat Slatina de Mureș, comuna Bârzava, judetul ARAD, România", "sat Slatina de Mures, comuna Barzava, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Bârzava, judetul ARAD, România", "comuna Barzava, judetul ARAD, Romania")),
        createComuna("Bocsig", [
            createLoc("Bocsig", "sat", createAdresaCompleta("sat Bocsig, comuna Bocsig, judetul ARAD, România", "sat Bocsig, comuna Bocsig, judetul ARAD, Romania")),
            createLoc("Mânerău", "sat", createAdresaCompleta("sat Mânerău, comuna Bocsig, judetul ARAD, România", "sat Manerau, comuna Bocsig, judetul ARAD, Romania")),
            createLoc("Răpsig", "sat", createAdresaCompleta("sat Răpsig, comuna Bocsig, judetul ARAD, România", "sat Rapsig, comuna Bocsig, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Bocsig, judetul ARAD, România", "comuna Bocsig, judetul ARAD, Romania")),  
        createComuna("Brazii", [
            createLoc("Brazii", "sat", createAdresaCompleta("sat Brazii, comuna Brazii, judetul ARAD, România", "sat Brazii, comuna Brazii, judetul ARAD, Romania")),
            createLoc("Buceava-Șoimuș", "sat", createAdresaCompleta("sat Buceava-Șoimuș, comuna Brazii, judetul ARAD, România", "sat Buceava-Soimus, comuna Brazii, judetul ARAD, Romania")),
            createLoc("Iacobini", "sat", createAdresaCompleta("sat Iacobini, comuna Brazii, judetul ARAD, România", "sat Iacobini, comuna Brazii, judetul ARAD, Romania")),
            createLoc("Mădrigești", "sat", createAdresaCompleta("sat Mădrigești, comuna Brazii, judetul ARAD, România", "sat Madrigesti, comuna Brazii, judetul ARAD, Romania")),
            createLoc("Secaș", "sat", createAdresaCompleta("sat Secaș, comuna Brazii, judetul ARAD, România", "sat Secas, comuna Brazii, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Brazii, judetul ARAD, România", "comuna Brazii, judetul ARAD, Romania")),  
        createComuna("Buteni", [
            createLoc("Buteni", "sat", createAdresaCompleta("sat Buteni, comuna Buteni, judetul ARAD, România", "sat Buteni, comuna Buteni, judetul ARAD, Romania")),
            createLoc("Berindia", "sat", createAdresaCompleta("sat Berindia, comuna Buteni, judetul ARAD, România", "sat Berindia, comuna Buteni, judetul ARAD, Romania")),
            createLoc("Cuied", "sat", createAdresaCompleta("sat Cuied, comuna Buteni, judetul ARAD, România", "sat Cuied, comuna Buteni, judetul ARAD, Romania")),
            createLoc("Păulian", "sat", createAdresaCompleta("sat Păulian, comuna Buteni, judetul ARAD, România", "sat Paulian, comuna Buteni, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Buteni, judetul ARAD, România", "comuna Buteni, judetul ARAD, Romania")),  
        createComuna("Cărand", [
            createLoc("Cărand", "sat", createAdresaCompleta("sat Cărand, comuna Cărand, judetul ARAD, România", "sat Carand, comuna Carand, judetul ARAD, Romania")),
            createLoc("Seliștea", "sat", createAdresaCompleta("sat Seliștea, comuna Cărand, judetul ARAD, România", "sat Selistea, comuna Carand, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Cărand, judetul ARAD, România", "comuna Carand, judetul ARAD, Romania")),
        createComuna("Cermei", [
            createLoc("Cermei", "sat", createAdresaCompleta("sat Cermei, comuna Cermei, judetul ARAD, România", "sat Cermei, comuna Cermei, judetul ARAD, Romania")),
            createLoc("Avram Iancu", "sat", createAdresaCompleta("sat Avram Iancu, comuna Cermei, judetul ARAD, România", "sat Avram Iancu, comuna Cermei, judetul ARAD, Romania")),
            createLoc("Șomoșcheș", "sat", createAdresaCompleta("sat Șomoșcheș, comuna Cermei, judetul ARAD, România", "sat Somosches, comuna Cermei, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Cermei, judetul ARAD, România", "comuna Cermei, judetul ARAD, Romania")),  
        createComuna("Chisindia", [
            createLoc("Chisindia", "sat", createAdresaCompleta("sat Chisindia, comuna Chisindia, judetul ARAD, România", "sat Chisindia, comuna Chisindia, judetul ARAD, Romania")),
            createLoc("Păiușeni", "sat", createAdresaCompleta("sat Păiușeni, comuna Chisindia, judetul ARAD, România", "sat Paiuseni, comuna Chisindia, judetul ARAD, Romania")),
            createLoc("Văsoaia", "sat", createAdresaCompleta("sat Văsoaia, comuna Chisindia, judetul ARAD, România", "sat Vasoaia, comuna Chisindia, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Chisindia, judetul ARAD, România", "comuna Chisindia, judetul ARAD, Romania")),
        createComuna("Conop", [
            createLoc("Conop", "sat", createAdresaCompleta("sat Conop, comuna Conop, judetul ARAD, România", "sat Conop, comuna Conop, judetul ARAD, Romania")),
            createLoc("Belotinț", "sat", createAdresaCompleta("sat Belotinț, comuna Conop, judetul ARAD, România", "sat Belotint, comuna Conop, judetul ARAD, Romania")),
            createLoc("Chelmac", "sat", createAdresaCompleta("sat Chelmac, comuna Conop, judetul ARAD, România", "sat Chelmac, comuna Conop, judetul ARAD, Romania")),
            createLoc("Milova", "sat", createAdresaCompleta("sat Milova, comuna Conop, judetul ARAD, România", "sat Milova, comuna Conop, judetul ARAD, Romania")),
            createLoc("Odvoș", "sat", createAdresaCompleta("sat Odvoș, comuna Conop, judetul ARAD, România", "sat Odvos, comuna Conop, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Conop, judetul ARAD, România", "comuna Conop, judetul ARAD, Romania")),  
        createComuna("Covăsinț", [
            createLoc("Covăsinț", "sat", createAdresaCompleta("sat Covăsinț, comuna Covăsinț, judetul ARAD, România", "sat Covasint, comuna Covasint, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Covăsinț, judetul ARAD, România", "comuna Covasint, judetul ARAD, Romania")),  
        createComuna("Craiva", [
            createLoc("Craiva", "sat", createAdresaCompleta("sat Craiva, comuna Craiva, judetul ARAD, România", "sat Craiva, comuna Craiva, judetul ARAD, Romania")),
            createLoc("Chișlaca", "sat", createAdresaCompleta("sat Chișlaca, comuna Craiva, judetul ARAD, România", "sat Chislaca, comuna Craiva, judetul ARAD, Romania")),
            createLoc("Ciuntești", "sat", createAdresaCompleta("sat Ciuntești, comuna Craiva, judetul ARAD, România", "sat Ciuntesti, comuna Craiva, judetul ARAD, Romania")),
            createLoc("Coroi", "sat", createAdresaCompleta("sat Coroi, comuna Craiva, judetul ARAD, România", "sat Coroi, comuna Craiva, judetul ARAD, Romania")),
            createLoc("Mărăuș", "sat", createAdresaCompleta("sat Mărăuș, comuna Craiva, judetul ARAD, România", "sat Maraus, comuna Craiva, judetul ARAD, Romania")),
            createLoc("Rogoz de Beliu", "sat", createAdresaCompleta("sat Rogoz de Beliu, comuna Craiva, judetul ARAD, România", "sat Rogoz de Beliu, comuna Craiva, judetul ARAD, Romania")),
            createLoc("Stoinești", "sat", createAdresaCompleta("sat Stoinești, comuna Craiva, judetul ARAD, România", "sat Stoinesti, comuna Craiva, judetul ARAD, Romania")),
            createLoc("Susag", "sat", createAdresaCompleta("sat Susag, comuna Craiva, judetul ARAD, România", "sat Susag, comuna Craiva, judetul ARAD, Romania")),
            createLoc("Șiad", "sat", createAdresaCompleta("sat Șiad, comuna Craiva, judetul ARAD, România", "sat Siad, comuna Craiva, judetul ARAD, Romania")),
            createLoc("Tălmaci", "sat", createAdresaCompleta("sat Tălmaci, comuna Craiva, judetul ARAD, România", "sat Talmaci, comuna Craiva, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Craiva, judetul ARAD, România", "comuna Craiva, judetul ARAD, Romania")),  
        createComuna("Dezna", [
            createLoc("Dezna", "sat", createAdresaCompleta("sat Dezna, comuna Dezna, judetul ARAD, România", "sat Dezna, comuna Dezna, judetul ARAD, Romania")),
            createLoc("Buhani", "sat", createAdresaCompleta("sat Buhani, comuna Dezna, judetul ARAD, România", "sat Buhani, comuna Dezna, judetul ARAD, Romania")),
            createLoc("Laz", "sat", createAdresaCompleta("sat Laz, comuna Dezna, judetul ARAD, România", "sat Laz, comuna Dezna, judetul ARAD, Romania")),
            createLoc("Neagra", "sat", createAdresaCompleta("sat Neagra, comuna Dezna, judetul ARAD, România", "sat Neagra, comuna Dezna, judetul ARAD, Romania")),
            createLoc("Slatina de Criș", "sat", createAdresaCompleta("sat Slatina de Criș, comuna Dezna, judetul ARAD, România", "sat Slatina de Cris, comuna Dezna, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Dezna, judetul ARAD, România", "comuna Dezna, judetul ARAD, Romania")),
        createComuna("Dieci", [
            createLoc("Dieci", "sat", createAdresaCompleta("sat Dieci, comuna Dieci, judetul ARAD, România", "sat Dieci, comuna Dieci, judetul ARAD, Romania")),
            createLoc("Cociuba", "sat", createAdresaCompleta("sat Cociuba, comuna Dieci, judetul ARAD, România", "sat Cociuba, comuna Dieci, judetul ARAD, Romania")),
            createLoc("Crocna", "sat", createAdresaCompleta("sat Crocna, comuna Dieci, judetul ARAD, România", "sat Crocna, comuna Dieci, judetul ARAD, Romania")),
            createLoc("Revetiș", "sat", createAdresaCompleta("sat Revetiș, comuna Dieci, judetul ARAD, România", "sat Revetis, comuna Dieci, judetul ARAD, Romania")),
            createLoc("Roșia", "sat", createAdresaCompleta("sat Roșia, comuna Dieci, judetul ARAD, România", "sat Rosia, comuna Dieci, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Dieci, judetul ARAD, România", "comuna Dieci, judetul ARAD, Romania")),  
        createComuna("Dorobanți", [
            createLoc("Dorobanți", "sat", createAdresaCompleta("sat Dorobanți, comuna Dorobanți, judetul ARAD, România", "sat Dorobanti, comuna Dorobanti, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Dorobanți, judetul ARAD, România", "comuna Dorobanti, judetul ARAD, Romania")),  
        createComuna("Fântânele", [
            createLoc("Fântânele", "sat", createAdresaCompleta("sat Fântânele, comuna Fântânele, judetul ARAD, România", "sat Fantanele, comuna Fantanele, judetul ARAD, Romania")),
            createLoc("Tisa Nouă", "sat", createAdresaCompleta("sat Tisa Nouă, comuna Fântânele, judetul ARAD, România", "sat Tisa Noua, comuna Fantanele, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Fântânele, judetul ARAD, România", "comuna Fantanele, judetul ARAD, Romania")),  
        createComuna("Felnac", [
            createLoc("Felnac", "sat", createAdresaCompleta("sat Felnac, comuna Felnac, judetul ARAD, România", "sat Felnac, comuna Felnac, judetul ARAD, Romania")),
            createLoc("Călugăreni", "sat", createAdresaCompleta("sat Călugăreni, comuna Felnac, judetul ARAD, România", "sat Calugareni, comuna Felnac, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Felnac, judetul ARAD, România", "comuna Felnac, judetul ARAD, Romania")),
        createComuna("Frumușeni", [
            createLoc("Frumușeni", "sat", createAdresaCompleta("sat Frumușeni, comuna Frumușeni, judetul ARAD, România", "sat Frumuseni, comuna Frumuseni, judetul ARAD, Romania")),
            createLoc("Aluniș", "sat", createAdresaCompleta("sat Aluniș, comuna Frumușeni, judetul ARAD, România", "sat Alunis, comuna Frumuseni, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Frumușeni, judetul ARAD, România", "comuna Frumuseni, judetul ARAD, Romania")),  
        createComuna("Ghioroc", [
            createLoc("Ghioroc", "sat", createAdresaCompleta("sat Ghioroc, comuna Ghioroc, judetul ARAD, România", "sat Ghioroc, comuna Ghioroc, judetul ARAD, Romania")),
            createLoc("Cuvin", "sat", createAdresaCompleta("sat Cuvin, comuna Ghioroc, judetul ARAD, România", "sat Cuvin, comuna Ghioroc, judetul ARAD, Romania")),
            createLoc("Miniș", "sat", createAdresaCompleta("sat Miniș, comuna Ghioroc, judetul ARAD, România", "sat Minis, comuna Ghioroc, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Ghioroc, judetul ARAD, România", "comuna Ghioroc, judetul ARAD, Romania")),
        createComuna("Grăniceri", [
            createLoc("Grăniceri", "sat", createAdresaCompleta("sat Grăniceri, comuna Grăniceri, judetul ARAD, România", "sat Graniceri, comuna Graniceri, judetul ARAD, Romania")),
            createLoc("Șiclău", "sat", createAdresaCompleta("sat Șiclău, comuna Grăniceri, judetul ARAD, România", "sat Siclau, comuna Graniceri, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Grăniceri, judetul ARAD, România", "comuna Graniceri, judetul ARAD, Romania")),  
        createComuna("Gurahonț", [
            createLoc("Gurahonț", "sat", createAdresaCompleta("sat Gurahonț, comuna Gurahonț, judetul ARAD, România", "sat Gurahont, comuna Gurahont, judetul ARAD, Romania")),
            createLoc("Bonțești", "sat", createAdresaCompleta("sat Bonțești, comuna Gurahonț, judetul ARAD, România", "sat Bontesti, comuna Gurahont, judetul ARAD, Romania")),
            createLoc("Dulcele", "sat", createAdresaCompleta("sat Dulcele, comuna Gurahonț, judetul ARAD, România", "sat Dulcele, comuna Gurahont, judetul ARAD, Romania")),
            createLoc("Feniș", "sat", createAdresaCompleta("sat Feniș, comuna Gurahonț, judetul ARAD, România", "sat Fenis, comuna Gurahont, judetul ARAD, Romania")),
            createLoc("Honțișor", "sat", createAdresaCompleta("sat Honțișor, comuna Gurahonț, judetul ARAD, România", "sat Hontisor, comuna Gurahont, judetul ARAD, Romania")),
            createLoc("Iosaș", "sat", createAdresaCompleta("sat Iosaș, comuna Gurahonț, judetul ARAD, România", "sat Iosas, comuna Gurahont, judetul ARAD, Romania")),
            createLoc("Mustești", "sat", createAdresaCompleta("sat Mustești, comuna Gurahonț, judetul ARAD, România", "sat Mustesti, comuna Gurahont, judetul ARAD, Romania")),
            createLoc("Pescari", "sat", createAdresaCompleta("sat Pescari, comuna Gurahonț, judetul ARAD, România", "sat Pescari, comuna Gurahont, judetul ARAD, Romania")),
            createLoc("Valea Mare", "sat", createAdresaCompleta("sat Valea Mare, comuna Gurahonț, judetul ARAD, România", "sat Valea Mare, comuna Gurahont, judetul ARAD, Romania")),
            createLoc("Zimbru", "sat", createAdresaCompleta("sat Zimbru, comuna Gurahonț, judetul ARAD, România", "sat Zimbru, comuna Gurahont, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Gurahonț, judetul ARAD, România", "comuna Gurahont, judetul ARAD, Romania")),
        createComuna("Hălmagiu", [
            createLoc("Hălmagiu", "sat", createAdresaCompleta("sat Hălmagiu, comuna Hălmagiu, judetul ARAD, România", "sat Halmagiu, comuna Halmagiu, judetul ARAD, Romania")),
            createLoc("Bănești", "sat", createAdresaCompleta("sat Bănești, comuna Hălmagiu, judetul ARAD, România", "sat Banesti, comuna Halmagiu, judetul ARAD, Romania")),
            createLoc("Bodești", "sat", createAdresaCompleta("sat Bodești, comuna Hălmagiu, judetul ARAD, România", "sat Bodesti, comuna Halmagiu, judetul ARAD, Romania")),
            createLoc("Brusturi", "sat", createAdresaCompleta("sat Brusturi, comuna Hălmagiu, judetul ARAD, România", "sat Brusturi, comuna Halmagiu, judetul ARAD, Romania")),
            createLoc("Cristești", "sat", createAdresaCompleta("sat Cristești, comuna Hălmagiu, judetul ARAD, România", "sat Cristesti, comuna Halmagiu, judetul ARAD, Romania")),
            createLoc("Ionești", "sat", createAdresaCompleta("sat Ionești, comuna Hălmagiu, judetul ARAD, România", "sat Ionesti, comuna Halmagiu, judetul ARAD, Romania")),
            createLoc("Leasa", "sat", createAdresaCompleta("sat Leasa, comuna Hălmagiu, judetul ARAD, România", "sat Leasa, comuna Halmagiu, judetul ARAD, Romania")),
            createLoc("Leștioara", "sat", createAdresaCompleta("sat Leștioara, comuna Hălmagiu, judetul ARAD, România", "sat Lestioara, comuna Halmagiu, judetul ARAD, Romania")),
            createLoc("Poienari", "sat", createAdresaCompleta("sat Poienari, comuna Hălmagiu, judetul ARAD, România", "sat Poienari, comuna Halmagiu, judetul ARAD, Romania")),
            createLoc("Tisa", "sat", createAdresaCompleta("sat Tisa, comuna Hălmagiu, judetul ARAD, România", "sat Tisa, comuna Halmagiu, judetul ARAD, Romania")),
            createLoc("Țărmure", "sat", createAdresaCompleta("sat Țărmure, comuna Hălmagiu, judetul ARAD, România", "sat Tarmure, comuna Halmagiu, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Hălmagiu, judetul ARAD, România", "comuna Halmagiu, judetul ARAD, Romania")),  
        createComuna("Hălmăgel", [
            createLoc("Hălmăgel", "sat", createAdresaCompleta("sat Hălmăgel, comuna Hălmăgel, judetul ARAD, România", "sat Halmagel, comuna Halmagel, judetul ARAD, Romania")),
            createLoc("Luncșoara", "sat", createAdresaCompleta("sat Luncșoara, comuna Hălmăgel, judetul ARAD, România", "sat Luncsoara, comuna Halmagel, judetul ARAD, Romania")),
            createLoc("Sârbi", "sat", createAdresaCompleta("sat Sârbi, comuna Hălmăgel, judetul ARAD, România", "sat Sarbi, comuna Halmagel, judetul ARAD, Romania")),
            createLoc("Târnăvița", "sat", createAdresaCompleta("sat Târnăvița, comuna Hălmăgel, judetul ARAD, România", "sat Tarnavita, comuna Halmagel, judetul ARAD, Romania")),
            createLoc("Țohești", "sat", createAdresaCompleta("sat Țohești, comuna Hălmăgel, judetul ARAD, România", "sat Tohesti, comuna Halmagel, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Hălmăgel, judetul ARAD, România", "comuna Halmagel, judetul ARAD, Romania")),
        createComuna("Hășmaș", [
            createLoc("Hășmaș", "sat", createAdresaCompleta("sat Hășmaș, comuna Hășmaș, judetul ARAD, România", "sat Hasmas, comuna Hasmas, judetul ARAD, Romania")),
            createLoc("Agrișu Mic", "sat", createAdresaCompleta("sat Agrișu Mic, comuna Hășmaș, judetul ARAD, România", "sat Agrisu Mic, comuna Hasmas, judetul ARAD, Romania")),
            createLoc("Botfei", "sat", createAdresaCompleta("sat Botfei, comuna Hășmaș, judetul ARAD, România", "sat Botfei, comuna Hasmas, judetul ARAD, Romania")),
            createLoc("Clit", "sat", createAdresaCompleta("sat Clit, comuna Hășmaș, judetul ARAD, România", "sat Clit, comuna Hasmas, judetul ARAD, Romania")),
            createLoc("Comănești", "sat", createAdresaCompleta("sat Comănești, comuna Hășmaș, judetul ARAD, România", "sat Comanesti, comuna Hasmas, judetul ARAD, Romania")),
            createLoc("Urvișu de Beliu", "sat", createAdresaCompleta("sat Urvișu de Beliu, comuna Hășmaș, judetul ARAD, România", "sat Urvisu de Beliu, comuna Hasmas, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Hășmaș, judetul ARAD, România", "comuna Hasmas, judetul ARAD, Romania")),  
        createComuna("Ignești", [
            createLoc("Ignești", "sat", createAdresaCompleta("sat Ignești, comuna Ignești, judetul ARAD, România", "sat Ignesti, comuna Ignesti, judetul ARAD, Romania")),
            createLoc("Minead", "sat", createAdresaCompleta("sat Minead, comuna Ignești, judetul ARAD, România", "sat Minead, comuna Ignesti, judetul ARAD, Romania")),
            createLoc("Nădălbești", "sat", createAdresaCompleta("sat Nădălbești, comuna Ignești, judetul ARAD, România", "sat Nadalbesti, comuna Ignesti, judetul ARAD, Romania")),
            createLoc("Susani", "sat", createAdresaCompleta("sat Susani, comuna Ignești, judetul ARAD, România", "sat Susani, comuna Ignesti, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Ignești, judetul ARAD, România", "comuna Ignesti, judetul ARAD, Romania")),
        createComuna("Iratoșu", [
            createLoc("Iratoșu", "sat", createAdresaCompleta("sat Iratoșu, comuna Iratoșu, judetul ARAD, România", "sat Iratosu, comuna Iratosu, judetul ARAD, Romania")),
            createLoc("Variașu Mare", "sat", createAdresaCompleta("sat Variașu Mare, comuna Iratoșu, judetul ARAD, România", "sat Variasu Mare, comuna Iratosu, judetul ARAD, Romania")),
            createLoc("Variașu Mic", "sat", createAdresaCompleta("sat Variașu Mic, comuna Iratoșu, judetul ARAD, România", "sat Variasu Mic, comuna Iratosu, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Iratoșu, judetul ARAD, România", "comuna Iratosu, judetul ARAD, Romania")),  
        createComuna("Livada", [
            createLoc("Livada", "sat", createAdresaCompleta("sat Livada, comuna Livada, judetul ARAD, România", "sat Livada, comuna Livada, judetul ARAD, Romania")),
            createLoc("Sânleani", "sat", createAdresaCompleta("sat Sânleani, comuna Livada, judetul ARAD, România", "sat Sanleani, comuna Livada, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Livada, judetul ARAD, România", "comuna Livada, judetul ARAD, Romania")),
        createComuna("Macea", [
            createLoc("Macea", "sat", createAdresaCompleta("sat Macea, comuna Macea, judetul ARAD, România", "sat Macea, comuna Macea, judetul ARAD, Romania")),
            createLoc("Sânmartin", "sat", createAdresaCompleta("sat Sânmartin, comuna Macea, judetul ARAD, România", "sat Sanmartin, comuna Macea, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Macea, judetul ARAD, România", "comuna Macea, judetul ARAD, Romania")),  
        createComuna("Mișca", [
            createLoc("Mișca", "sat", createAdresaCompleta("sat Mișca, comuna Mișca, judetul ARAD, România", "sat Misca, comuna Misca, judetul ARAD, Romania")),
            createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Mișca, judetul ARAD, România", "sat Satu Nou, comuna Misca, judetul ARAD, Romania")),
            createLoc("Vânători", "sat", createAdresaCompleta("sat Vânători, comuna Mișca, judetul ARAD, România", "sat Vanatori, comuna Misca, judetul ARAD, Romania")),
            createLoc("Zerindu Mic", "sat", createAdresaCompleta("sat Zerindu Mic, comuna Mișca, judetul ARAD, România", "sat Zerindu Mic, comuna Misca, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Mișca, judetul ARAD, România", "comuna Misca, judetul ARAD, Romania")),
        createComuna("Moneasa", [
            createLoc("Moneasa", "sat", createAdresaCompleta("sat Moneasa, comuna Moneasa, judetul ARAD, România", "sat Moneasa, comuna Moneasa, judetul ARAD, Romania")),
            createLoc("Rănușa", "sat", createAdresaCompleta("sat Rănușa, comuna Moneasa, judetul ARAD, România", "sat Ranusa, comuna Moneasa, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Moneasa, judetul ARAD, România", "comuna Moneasa, judetul ARAD, Romania")),  
        createComuna("Olari", [
            createLoc("Olari", "sat", createAdresaCompleta("sat Olari, comuna Olari, judetul ARAD, România", "sat Olari, comuna Olari, judetul ARAD, Romania")),
            createLoc("Sintea Mică", "sat", createAdresaCompleta("sat Sintea Mică, comuna Olari, judetul ARAD, România", "sat Sintea Mica, comuna Olari, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Olari, judetul ARAD, România", "comuna Olari, judetul ARAD, Romania")),
        createComuna("Păuliș", [
            createLoc("Păuliș", "sat", createAdresaCompleta("sat Păuliș, comuna Păuliș, judetul ARAD, România", "sat Paulis, comuna Paulis, judetul ARAD, Romania")),
            createLoc("Barațca", "sat", createAdresaCompleta("sat Barațca, comuna Păuliș, judetul ARAD, România", "sat Baratca, comuna Paulis, judetul ARAD, Romania")),
            createLoc("Cladova", "sat", createAdresaCompleta("sat Cladova, comuna Păuliș, judetul ARAD, România", "sat Cladova, comuna Paulis, judetul ARAD, Romania")),
            createLoc("Sâmbăteni", "sat", createAdresaCompleta("sat Sâmbăteni, comuna Păuliș, judetul ARAD, România", "sat Sambateni, comuna Paulis, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Păuliș, judetul ARAD, România", "comuna Paulis, judetul ARAD, Romania")),  
        createComuna("Peregu Mare", [
            createLoc("Peregu Mare", "sat", createAdresaCompleta("sat Peregu Mare, comuna Peregu Mare, judetul ARAD, România", "sat Peregu Mare, comuna Peregu Mare, judetul ARAD, Romania")),
            createLoc("Peregu Mic", "sat", createAdresaCompleta("sat Peregu Mic, comuna Peregu Mare, judetul ARAD, România", "sat Peregu Mic, comuna Peregu Mare, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Peregu Mare, judetul ARAD, România", "comuna Peregu Mare, judetul ARAD, Romania")),
        createComuna("Petriș", [
            createLoc("Petriș", "sat", createAdresaCompleta("sat Petriș, comuna Petriș, judetul ARAD, România", "sat Petris, comuna Petris, judetul ARAD, Romania")),
            createLoc("Corbești", "sat", createAdresaCompleta("sat Corbești, comuna Petriș, judetul ARAD, România", "sat Corbesti, comuna Petris, judetul ARAD, Romania")),
            createLoc("Ilteu", "sat", createAdresaCompleta("sat Ilteu, comuna Petriș, judetul ARAD, România", "sat Ilteu, comuna Petris, judetul ARAD, Romania")),
            createLoc("Obârșia", "sat", createAdresaCompleta("sat Obârșia, comuna Petriș, judetul ARAD, România", "sat Obarsia, comuna Petris, judetul ARAD, Romania")),
            createLoc("Roșia Nouă", "sat", createAdresaCompleta("sat Roșia Nouă, comuna Petriș, judetul ARAD, România", "sat Rosia Noua, comuna Petris, judetul ARAD, Romania")),
            createLoc("Seliște", "sat", createAdresaCompleta("sat Seliște, comuna Petriș, judetul ARAD, România", "sat Seliste, comuna Petris, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Petriș, judetul ARAD, România", "comuna Petris, judetul ARAD, Romania")),  
        createComuna("Pilu", [
            createLoc("Pilu", "sat", createAdresaCompleta("sat Pilu, comuna Pilu, judetul ARAD, România", "sat Pilu, comuna Pilu, judetul ARAD, Romania")),
            createLoc("Vărșand", "sat", createAdresaCompleta("sat Vărșand, comuna Pilu, judetul ARAD, România", "sat Varsand, comuna Pilu, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Pilu, judetul ARAD, România", "comuna Pilu, judetul ARAD, Romania")),
        createComuna("Pleșcuța", [
            createLoc("Pleșcuța", "sat", createAdresaCompleta("sat Pleșcuța, comuna Pleșcuța, judetul ARAD, România", "sat Plescuta, comuna Plescuta, judetul ARAD, Romania")),
            createLoc("Aciuța", "sat", createAdresaCompleta("sat Aciuța, comuna Pleșcuța, judetul ARAD, România", "sat Aciuta, comuna Plescuta, judetul ARAD, Romania")),
            createLoc("Budești", "sat", createAdresaCompleta("sat Budești, comuna Pleșcuța, judetul ARAD, România", "sat Budesti, comuna Plescuta, judetul ARAD, Romania")),
            createLoc("Dumbrava", "sat", createAdresaCompleta("sat Dumbrava, comuna Pleșcuța, judetul ARAD, România", "sat Dumbrava, comuna Plescuta, judetul ARAD, Romania")),
            createLoc("Gura Văii", "sat", createAdresaCompleta("sat Gura Văii, comuna Pleșcuța, judetul ARAD, România", "sat Gura Vaii, comuna Plescuta, judetul ARAD, Romania")),
            createLoc("Rostoci", "sat", createAdresaCompleta("sat Rostoci, comuna Pleșcuța, judetul ARAD, România", "sat Rostoci, comuna Plescuta, judetul ARAD, Romania")),
            createLoc("Tălagiu", "sat", createAdresaCompleta("sat Tălagiu, comuna Pleșcuța, judetul ARAD, România", "sat Talagiu, comuna Plescuta, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Pleșcuța, judetul ARAD, România", "comuna Plescuta, judetul ARAD, Romania")),  
        createComuna("Săvârșin", [
            createLoc("Săvârșin", "sat", createAdresaCompleta("sat Săvârșin, comuna Săvârșin, judetul ARAD, România", "sat Savarsin, comuna Savarsin, judetul ARAD, Romania")),
            createLoc("Căprioara", "sat", createAdresaCompleta("sat Căprioara, comuna Săvârșin, judetul ARAD, România", "sat Caprioara, comuna Savarsin, judetul ARAD, Romania")),
            createLoc("Cuiaș", "sat", createAdresaCompleta("sat Cuiaș, comuna Săvârșin, judetul ARAD, România", "sat Cuias, comuna Savarsin, judetul ARAD, Romania")),
            createLoc("Hălăliș", "sat", createAdresaCompleta("sat Hălăliș, comuna Săvârșin, judetul ARAD, România", "sat Halalis, comuna Savarsin, judetul ARAD, Romania")),
            createLoc("Pârnești", "sat", createAdresaCompleta("sat Pâtnești, comuna Săvârșin, judetul ARAD, România", "sat Patnesti, comuna Savarsin, judetul ARAD, Romania")),
            createLoc("Temeșești", "sat", createAdresaCompleta("sat Temeșești, comuna Săvârșin, judetul ARAD, România", "sat Temesesti, comuna Savarsin, judetul ARAD, Romania")),
            createLoc("Toc", "sat", createAdresaCompleta("sat Toc, comuna Săvârșin, judetul ARAD, România", "sat Toc, comuna Savarsin, judetul ARAD, Romania")),
            createLoc("Troaș", "sat", createAdresaCompleta("sat Troaș, comuna Săvârșin, judetul ARAD, România", "sat Troas, comuna Savarsin, judetul ARAD, Romania")),
            createLoc("Valea Mare", "sat", createAdresaCompleta("sat Valea Mare, comuna Săvârșin, judetul ARAD, România", "sat Valea Mare, comuna Savarsin, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Săvârșin, judetul ARAD, România", "comuna Savarsin, judetul ARAD, Romania")),
        createComuna("Secusigiu", [
            createLoc("Secusigiu", "sat", createAdresaCompleta("sat Secusigiu, comuna Secusigiu, judetul ARAD, România", "sat Secusigiu, comuna Secusigiu, judetul ARAD, Romania")),
            createLoc("Munar", "sat", createAdresaCompleta("sat Munar, comuna Secusigiu, judetul ARAD, România", "sat Munar, comuna Secusigiu, judetul ARAD, Romania")),
            createLoc("Satu Mare", "sat", createAdresaCompleta("sat Satu Mare, comuna Secusigiu, judetul ARAD, România", "sat Satu Mare, comuna Secusigiu, judetul ARAD, Romania")),
            createLoc("Sânpetru German", "sat", createAdresaCompleta("sat Sânpetru German, comuna Secusigiu, judetul ARAD, România", "sat Sanpetru German, comuna Secusigiu, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Secusigiu, judetul ARAD, România", "comuna Secusigiu, judetul ARAD, Romania")),  
        createComuna("Seleuș", [
            createLoc("Seleuș", "sat", createAdresaCompleta("sat Seleuș, comuna Seleuș, judetul ARAD, România", "sat Seleus, comuna Seleus, judetul ARAD, Romania")),
            createLoc("Iermata", "sat", createAdresaCompleta("sat Iermata, comuna Seleuș, judetul ARAD, România", "sat Iermata, comuna Seleus, judetul ARAD, Romania")),
            createLoc("Moroda", "sat", createAdresaCompleta("sat Moroda, comuna Seleuș, judetul ARAD, România", "sat Moroda, comuna Seleus, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Seleuș, judetul ARAD, România", "comuna Seleus, judetul ARAD, Romania")),
        createComuna("Semlac", [
            createLoc("Semlac", "sat", createAdresaCompleta("sat Semlac, comuna Semlac, judetul ARAD, România", "sat Semlac, comuna Semlac, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Semlac, judetul ARAD, România", "comuna Semlac, judetul ARAD, Romania")),  
        createComuna("Sintea Mare", [
            createLoc("Sintea Mare", "sat", createAdresaCompleta("sat Sintea Mare, comuna Sintea Mare, judetul ARAD, România", "sat Sintea Mare, comuna Sintea Mare, judetul ARAD, Romania")),
            createLoc("Adea", "sat", createAdresaCompleta("sat Adea, comuna Sintea Mare, judetul ARAD, România", "sat Adea, comuna Sintea Mare, judetul ARAD, Romania")),
            createLoc("Țipar", "sat", createAdresaCompleta("sat Țipar, comuna Sintea Mare, judetul ARAD, România", "sat Tipar, comuna Sintea Mare, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Sintea Mare, judetul ARAD, România", "comuna Sintea Mare, judetul ARAD, Romania")),
        createComuna("Socodor", [
            createLoc("Socodor", "sat", createAdresaCompleta("sat Socodor, comuna Socodor, judetul ARAD, România", "sat Socodor, comuna Socodor, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Socodor, judetul ARAD, România", "comuna Socodor, judetul ARAD, Romania")),  
        createComuna("Șagu", [
            createLoc("Șagu", "sat", createAdresaCompleta("sat Șagu, comuna Șagu, judetul ARAD, România", "sat Sagu, comuna Sagu, judetul ARAD, Romania")),
            createLoc("Cruceni", "sat", createAdresaCompleta("sat Cruceni, comuna Șagu, judetul ARAD, România", "sat Cruceni, comuna Sagu, judetul ARAD, Romania")),
            createLoc("Firiteaz", "sat", createAdresaCompleta("sat Firiteaz, comuna Șagu, judetul ARAD, România", "sat Firiteaz, comuna Sagu, judetul ARAD, Romania")),
            createLoc("Fiscut", "sat", createAdresaCompleta("sat Fiscut, comuna Șagu, judetul ARAD, România", "sat Fiscut, comuna Sagu, judetul ARAD, Romania")),
            createLoc("Hunedoara Timișană", "sat", createAdresaCompleta("sat Hunedoara Timișană, comuna Șagu, judetul ARAD, România", "sat Hunedoara Timisana, comuna Sagu, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Șagu, judetul ARAD, România", "comuna Sagu, judetul ARAD, Romania")),
        createComuna("Șeitin", [
            createLoc("Șeitin", "sat", createAdresaCompleta("sat Șeitin, comuna Șeitin, judetul ARAD, România", "sat Seitin, comuna Seitin, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Șeitin, judetul ARAD, România", "comuna Seitin, judetul ARAD, Romania")),  
        createComuna("Șepreuș", [
            createLoc("Șepreuș", "sat", createAdresaCompleta("sat Șepreuș, comuna Șepreuș, judetul ARAD, România", "sat Sepreus, comuna Sepreus, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Șepreuș, judetul ARAD, România", "comuna Sepreus, judetul ARAD, Romania")),
        createComuna("Șicula", [
            createLoc("Șicula", "sat", createAdresaCompleta("sat Șicula, comuna Șicula, judetul ARAD, România", "sat Sicula, comuna Sicula, judetul ARAD, Romania")),
            createLoc("Chereluș", "sat", createAdresaCompleta("sat Chereluș, comuna Șicula, judetul ARAD, România", "sat Cherelus, comuna Sicula, judetul ARAD, Romania")),
            createLoc("Gurba", "sat", createAdresaCompleta("sat Gurba, comuna Șicula, judetul ARAD, România", "sat Gurba, comuna Sicula, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Șicula, judetul ARAD, România", "comuna Sicula, judetul ARAD, Romania")),  
        createComuna("Șilindia", [
            createLoc("Șilindia", "sat", createAdresaCompleta("sat Șilindia, comuna Șilindia, judetul ARAD, România", "sat Silindia, comuna Silindia, judetul ARAD, Romania")),
            createLoc("Camna", "sat", createAdresaCompleta("sat Camna, comuna Șilindia, judetul ARAD, România", "sat Camna, comuna Silindia, judetul ARAD, Romania")),
            createLoc("Iercoșeni", "sat", createAdresaCompleta("sat Iercoșeni, comuna Șilindia, judetul ARAD, România", "sat Iercoseni, comuna Silindia, judetul ARAD, Romania")),
            createLoc("Luguzău", "sat", createAdresaCompleta("sat Luguzău, comuna Șilindia, judetul ARAD, România", "sat Luguzau, comuna Silindia, judetul ARAD, Romania")),
            createLoc("Satu Mic", "sat", createAdresaCompleta("sat Satu Mic, comuna Șilindia, judetul ARAD, România", "sat Satu Mic, comuna Silindia, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Șilindia, judetul ARAD, România", "comuna Silindia, judetul ARAD, Romania")),
        createComuna("Șimand", [
            createLoc("Șimand", "sat", createAdresaCompleta("sat Șimand, comuna Șimand, judetul ARAD, România", "sat Simand, comuna Simand, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Șimand, judetul ARAD, România", "comuna Simand, judetul ARAD, Romania")),  
        createComuna("Șiria", [
            createLoc("Șiria", "sat", createAdresaCompleta("sat Șiria, comuna Șiria, judetul ARAD, România", "sat Siria, comuna Siria, judetul ARAD, Romania")),
            createLoc("Galșa", "sat", createAdresaCompleta("sat Galșa, comuna Șiria, judetul ARAD, România", "sat Galsa, comuna Siria, judetul ARAD, Romania")),
            createLoc("Mâsca", "sat", createAdresaCompleta("sat Mâsca, comuna Șiria, judetul ARAD, România", "sat Masca, comuna Siria, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Șiria, judetul ARAD, România", "comuna Siria, judetul ARAD, Romania")),
        createComuna("Șiștarovăț", [
            createLoc("Șiștarovăț", "sat", createAdresaCompleta("sat Șiștarovăț, comuna Șiștarovăț, judetul ARAD, România", "sat Sistarovat, comuna Sistarovat, judetul ARAD, Romania")),
            createLoc("Cuveșdia", "sat", createAdresaCompleta("sat Cuveșdia, comuna Șiștarovăț, judetul ARAD, România", "sat Cuvesdia, comuna Sistarovat, judetul ARAD, Romania")),
            createLoc("Labașinț", "sat", createAdresaCompleta("sat Labașinț, comuna Șiștarovăț, judetul ARAD, România", "sat Labasint, comuna Sistarovat, judetul ARAD, Romania")),
            createLoc("Varnița", "sat", createAdresaCompleta("sat Varnița, comuna Șiștarovăț, judetul ARAD, România", "sat Varnita, comuna Sistarovat, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Șiștarovăț, judetul ARAD, România", "comuna Sistarovat, judetul ARAD, Romania")),  
        createComuna("Șofronea", [
            createLoc("Șofronea", "sat", createAdresaCompleta("sat Șofronea, comuna Șofronea, judetul ARAD, România", "sat Sofronea, comuna Sofronea, judetul ARAD, Romania")),
            createLoc("Sânpaul", "sat", createAdresaCompleta("sat Sânpaul, comuna Șofronea, judetul ARAD, România", "sat Sanpaul, comuna Sofronea, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Șofronea, judetul ARAD, România", "comuna Sofronea, judetul ARAD, Romania")),          
        createComuna("Tauț", [
            createLoc("Tauț", "sat", createAdresaCompleta("sat Tauț, comuna Tauț, judetul ARAD, România", "sat Taut, comuna Taut, judetul ARAD, Romania")),
            createLoc("Minișel", "sat", createAdresaCompleta("sat Minișel, comuna Tauț, judetul ARAD, România", "sat Minisel, comuna Taut, judetul ARAD, Romania")),
            createLoc("Minișu de Sus", "sat", createAdresaCompleta("sat Minișu de Sus, comuna Tauț, judetul ARAD, România", "sat Minisu de Sus, comuna Taut, judetul ARAD, Romania")),
            createLoc("Nadăș", "sat", createAdresaCompleta("sat Nadăș, comuna Tauț, judetul ARAD, România", "sat Nadas, comuna Taut, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Tauț, judetul ARAD, România", "comuna Taut, judetul ARAD, Romania")),  
        createComuna("Târnova", [
            createLoc("Târnova", "sat", createAdresaCompleta("sat Târnova, comuna Târnova, judetul ARAD, România", "sat Tarnova, comuna Tarnova, judetul ARAD, Romania")),
            createLoc("Agrișu Mare", "sat", createAdresaCompleta("sat Agrișu Mare, comuna Târnova, judetul ARAD, România", "sat Agrisu Mare, comuna Tarnova, judetul ARAD, Romania")),
            createLoc("Arăneag", "sat", createAdresaCompleta("sat Arăneag, comuna Târnova, judetul ARAD, România", "sat Araneag, comuna Tarnova, judetul ARAD, Romania")),
            createLoc("Chier", "sat", createAdresaCompleta("sat Chier, comuna Târnova, judetul ARAD, România", "sat Chier, comuna Tarnova, judetul ARAD, Romania")),
            createLoc("Drauț", "sat", createAdresaCompleta("sat Drauț, comuna Târnova, judetul ARAD, România", "sat Draut, comuna Tarnova, judetul ARAD, Romania")),
            createLoc("Dud", "sat", createAdresaCompleta("sat Dud, comuna Târnova, judetul ARAD, România", "sat Dud, comuna Tarnova, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Târnova, judetul ARAD, România", "comuna Tarnova, judetul ARAD, Romania")),
        createComuna("Ususău", [
            createLoc("Ususău", "sat", createAdresaCompleta("sat Ususău, comuna Ususău, judetul ARAD, România", "sat Ususau, comuna Ususau, judetul ARAD, Romania")),
            createLoc("Bruznic", "sat", createAdresaCompleta("sat Bruznic, comuna Ususău, judetul ARAD, România", "sat Bruznic, comuna Ususau, judetul ARAD, Romania")),
            createLoc("Dorgoș", "sat", createAdresaCompleta("sat Dorgoș, comuna Ususău, judetul ARAD, România", "sat Dorgos, comuna Ususau, judetul ARAD, Romania")),
            createLoc("Pătârș", "sat", createAdresaCompleta("sat Pătârș, comuna Ususău, judetul ARAD, România", "sat Patars, comuna Ususau, judetul ARAD, Romania")),
            createLoc("Zăbalț", "sat", createAdresaCompleta("sat Zăbalț, comuna Ususău, judetul ARAD, România", "sat Zabalt, comuna Ususau, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Ususău, judetul ARAD, România", "comuna Ususau, judetul ARAD, Romania")),  
        createComuna("Vărădia de Mureș", [
            createLoc("Vărădia de Mureș", "sat", createAdresaCompleta("sat Vărădia de Mureș, comuna Vărădia de Mureș, judetul ARAD, România", "sat Varadia de Mures, comuna Varadia de Mures, judetul ARAD, Romania")),
            createLoc("Baia", "sat", createAdresaCompleta("sat Baia, comuna Vărădia de Mureș, judetul ARAD, România", "sat Baia, comuna Varadia de Mures, judetul ARAD, Romania")),
            createLoc("Julița", "sat", createAdresaCompleta("sat Julița, comuna Vărădia de Mureș, judetul ARAD, România", "sat Julita, comuna Varadia de Mures, judetul ARAD, Romania")),
            createLoc("Lupești", "sat", createAdresaCompleta("sat Lupești, comuna Vărădia de Mureș, judetul ARAD, România", "sat Lupesti, comuna Varadia de Mures, judetul ARAD, Romania")),
            createLoc("Nicolae Bălcescu", "sat", createAdresaCompleta("sat Nicolae Bălcescu, comuna Vărădia de Mureș, judetul ARAD, România", "sat Nicolae Balcescu, comuna Varadia de Mures, judetul ARAD, Romania")),
            createLoc("Stejar", "sat", createAdresaCompleta("sat Stejar, comuna Vărădia de Mureș, judetul ARAD, România", "sat Stejar, comuna Varadia de Mures, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Vărădia de Mureș, judetul ARAD, România", "comuna Varadia de Mures, judetul ARAD, Romania")),
        createComuna("Vinga", [
            createLoc("Vinga", "sat", createAdresaCompleta("sat Vinga, comuna Vinga, judetul ARAD, România", "sat Vinga, comuna Vinga, judetul ARAD, Romania")),
            createLoc("Mailat", "sat", createAdresaCompleta("sat Mailat, comuna Vinga, judetul ARAD, România", "sat Mailat, comuna Vinga, judetul ARAD, Romania")),
            createLoc("Mănăștur", "sat", createAdresaCompleta("sat Mănăștur, comuna Vinga, judetul ARAD, România", "sat Manastur, comuna Vinga, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Vinga, judetul ARAD, România", "comuna Vinga, judetul ARAD, Romania")),  
        createComuna("Vârfurile", [
            createLoc("Vârfurile", "sat", createAdresaCompleta("sat Vârfurile, comuna Vârfurile, judetul ARAD, România", "sat Varfurile, comuna Varfurile, judetul ARAD, Romania")),
            createLoc("Avram Iancu", "sat", createAdresaCompleta("sat Avram Iancu, comuna Vârfurile, judetul ARAD, România", "sat Avram Iancu, comuna Varfurile, judetul ARAD, Romania")),
            createLoc("Groși", "sat", createAdresaCompleta("sat Groși, comuna Vârfurile, judetul ARAD, România", "sat Grosi, comuna Varfurile, judetul ARAD, Romania")),
            createLoc("Lazuri", "sat", createAdresaCompleta("sat Lazuri, comuna Vârfurile, judetul ARAD, România", "sat Lazuri, comuna Varfurile, judetul ARAD, Romania")),
            createLoc("Măgulicea", "sat", createAdresaCompleta("sat Măgulicea, comuna Vârfurile, judetul ARAD, România", "sat Magulicea, comuna Varfurile, judetul ARAD, Romania")),
            createLoc("Mermești", "sat", createAdresaCompleta("sat Mermești, comuna Vârfurile, judetul ARAD, România", "sat Mermesti, comuna Varfurile, judetul ARAD, Romania")),
            createLoc("Poiana", "sat", createAdresaCompleta("sat Poiana, comuna Vârfurile, judetul ARAD, România", "sat Poiana, comuna Varfurile, judetul ARAD, Romania")),
            createLoc("Vidra", "sat", createAdresaCompleta("sat Vidra, comuna Vârfurile, judetul ARAD, România", "sat Vidra, comuna Varfurile, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Vârfurile, judetul ARAD, România", "comuna Varfurile, judetul ARAD, Romania")),
        createComuna("Vladimirescu", [
            createLoc("Vladimirescu", "sat", createAdresaCompleta("sat Vladimirescu, comuna Vladimirescu, judetul ARAD, România", "sat Vladimirescu, comuna Vladimirescu, judetul ARAD, Romania")),
            createLoc("Cicir", "sat", createAdresaCompleta("sat Cicir, comuna Vladimirescu, judetul ARAD, România", "sat Cicir, comuna Vladimirescu, judetul ARAD, Romania")),
            createLoc("Horia", "sat", createAdresaCompleta("sat Horia, comuna Vladimirescu, judetul ARAD, România", "sat Horia, comuna Vladimirescu, judetul ARAD, Romania")),
            createLoc("Mândruloc", "sat", createAdresaCompleta("sat Mândruloc, comuna Vladimirescu, judetul ARAD, România", "sat Mandruloc, comuna Vladimirescu, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Vladimirescu, judetul ARAD, România", "comuna Vladimirescu, judetul ARAD, Romania")),  
        createComuna("Zăbrani", [
            createLoc("Zăbrani", "sat", createAdresaCompleta("sat Zăbrani, comuna Zăbrani, judetul ARAD, România", "sat Zabrani, comuna Zabrani, judetul ARAD, Romania")),
            createLoc("Chesinț", "sat", createAdresaCompleta("sat Chesinț, comuna Zăbrani, judetul ARAD, România", "sat Chesint, comuna Zabrani, judetul ARAD, Romania")),
            createLoc("Neudorf", "sat", createAdresaCompleta("sat Neudorf, comuna Zăbrani, judetul ARAD, România", "sat Neudorf, comuna Zabrani, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Zăbrani, judetul ARAD, România", "comuna Zabrani, judetul ARAD, Romania")),
        createComuna("Zădăreni", [
            createLoc("Zădăreni", "sat", createAdresaCompleta("sat Zădăreni, comuna Zădăreni, judetul ARAD, România", "sat Zadareni, comuna Zadareni, judetul ARAD, Romania")),
            createLoc("Bodrogu Nou", "sat", createAdresaCompleta("sat Bodrogu Nou, comuna Zădăreni, judetul ARAD, România", "sat Bodrogu Nou, comuna Zadareni, judetul ARAD, Romania")),
            createLoc("Horia", "sat", createAdresaCompleta("sat Horia, comuna Zădăreni, judetul ARAD, România", "sat Horia, comuna Zadareni, judetul ARAD, Romania")),
            createLoc("Mândruloc", "sat", createAdresaCompleta("sat Mândruloc, comuna Zădăreni, judetul ARAD, România", "sat Mandruloc, comuna Zadareni, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Zădăreni, judetul ARAD, România", "comuna Zadareni, judetul ARAD, Romania")),  
        createComuna("Zărand", [
            createLoc("Zărand", "sat", createAdresaCompleta("sat Zărand, comuna Zărand, judetul ARAD, România", "sat Zarand, comuna Zarand, judetul ARAD, Romania")),
            createLoc("Cintei", "sat", createAdresaCompleta("sat Cintei, comuna Zărand, judetul ARAD, România", "sat Cintei, comuna Zarand, judetul ARAD, Romania")),
            createLoc("Neudorf", "sat", createAdresaCompleta("sat Neudorf, comuna Zărand, judetul ARAD, România", "sat Neudorf, comuna Zarand, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Zărand, judetul ARAD, România", "comuna Zarand, judetul ARAD, Romania")),
        createComuna("Zerind", [
            createLoc("Zerind", "sat", createAdresaCompleta("sat Zerind, comuna Zerind, judetul ARAD, România", "sat Zerind, comuna Zerind, judetul ARAD, Romania")),
            createLoc("Iermata Neagră", "sat", createAdresaCompleta("sat Iermata Neagră, comuna Zerind, judetul ARAD, România", "sat Iermata Neagra, comuna Zerind, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Zerind, judetul ARAD, România", "comuna Zerind, judetul ARAD, Romania")),  
        createComuna("Zimandu Nou", [
            createLoc("Zimandu Nou", "sat", createAdresaCompleta("sat Zimandu Nou, comuna Zimandu Nou, judetul ARAD, România", "sat Zimandu Nou, comuna Zimandu Nou, judetul ARAD, Romania")),
            createLoc("Andrei Șaguna", "sat", createAdresaCompleta("sat Andrei Șaguna, comuna Zimandu Nou, judetul ARAD, România", "sat Andrei Saguna, comuna Zimandu Nou, judetul ARAD, Romania")),
            createLoc("Zimandcuz", "sat", createAdresaCompleta("sat Zimandcuz, comuna Zimandu Nou, judetul ARAD, România", "sat Zimandcuz, comuna Zimandu Nou, judetul ARAD, Romania")),
        ], createAdresaCompleta("comuna Zimandu Nou, judetul ARAD, România", "comuna Zimandu Nou, judetul ARAD, Romania")),                                  
        
];
?>
