<?php
$comune =[
	createComuna("Amaru", [
						createAdresaCompleta("comuna Amaru, judetul BUZAU, România", "comuna Amaru, judetul BUZAU, Romania"),
						createLoc("Amaru", "sat", createAdresaCompleta("sat Amaru, comuna Amaru, judetul Buzau, România", "sat Amaru, comuna Amaru, judetul Buzau, Romania")),
						createLoc("Câmpeni", "sat", createAdresaCompleta("sat Câmpeni, comuna Amaru, judetul Buzau, România", "sat Campeni, comuna Amaru, judetul Buzau, Romania")),
						createLoc("Dulbanu", "sat", createAdresaCompleta("sat Dulbanu, comuna Amaru, judetul Buzau, România", "sat Dulbanu, comuna Amaru, judetul Buzau, Romania")),
						createLoc("Lacu Sinaia", "sat", createAdresaCompleta("sat Lacu Sinaia, comuna Amaru, judetul Buzau, România", "sat Lacu Sinaia, comuna Amaru, judetul Buzau, Romania")),
						createLoc("Lunca", "sat", createAdresaCompleta("sat Lunca, comuna Amaru, judetul Buzau, România", "sat Lunca, comuna Amaru, judetul Buzau, Romania")),
						createLoc("Scorțeanca", "sat", createAdresaCompleta("sat Scorțeanca, comuna Amaru, judetul Buzau, România", "sat Scorteanca, comuna Amaru, judetul Buzau, Romania")),
		]),
	createComuna("Balta Albă", [
						createAdresaCompleta("comuna Balta Albă, judetul BUZAU, România", "comuna Balta Alba, judetul BUZAU, Romania"),
						createLoc("Balta Albă", "sat", createAdresaCompleta("sat Balta Albă, comuna Balta Albă, judetul Buzau, România", "sat Balta Alba, comuna Balta Alba, judetul Buzau, Romania")),
						createLoc("Amara", "sat", createAdresaCompleta("sat Amara, comuna Balta Albă, judetul Buzau, România", "sat Amara, comuna Balta Alba, judetul Buzau, Romania")),
						createLoc("Băile", "sat", createAdresaCompleta("sat Băile, comuna Balta Albă, judetul Buzau, România", "sat Baile, comuna Balta Alba, judetul Buzau, Romania")),
						createLoc("Stăvărăști", "sat", createAdresaCompleta("sat Stăvărăști, comuna Balta Albă, judetul Buzau, România", "sat Stavarasti, comuna Balta Alba, judetul Buzau, Romania")),
		]),
	createComuna("Bălăceanu", [
						createAdresaCompleta("comuna Bălăceanu, judetul BUZAU, România", "comuna Balaceanu, judetul BUZAU, Romania"),
						createLoc("Bălăceanu", "sat", createAdresaCompleta("sat Bălăceanu, comuna Bălăceanu, judetul Buzau, România", "sat Balaceanu, comuna Balaceanu, judetul Buzau, Romania")),
		]),
	createComuna("Beceni", [
						createAdresaCompleta("comuna Beceni, judetul BUZAU, România", "comuna Beceni, judetul BUZAU, Romania"),
						createLoc("Beceni", "sat", createAdresaCompleta("sat Beceni, comuna Beceni, judetul Buzau, România", "sat Beceni, comuna Beceni, judetul Buzau, Romania")),
						createLoc("Arbănași", "sat", createAdresaCompleta("sat Arbănași, comuna Beceni, judetul Buzau, România", "sat Arbanasi, comuna Beceni, judetul Buzau, Romania")),
						createLoc("Cărpiniștea", "sat", createAdresaCompleta("sat Cărpiniștea, comuna Beceni, judetul Buzau, România", "sat Carpinistea, comuna Beceni, judetul Buzau, Romania")),
						createLoc("Dogari", "sat", createAdresaCompleta("sat Dogari, comuna Beceni, judetul Buzau, România", "sat Dogari, comuna Beceni, judetul Buzau, Romania")),
						createLoc("Florești", "sat", createAdresaCompleta("sat Florești, comuna Beceni, judetul Buzau, România", "sat Floresti, comuna Beceni, judetul Buzau, Romania")),
						createLoc("Gura Dimienii", "sat", createAdresaCompleta("sat Gura Dimienii, comuna Beceni, judetul Buzau, România", "sat Gura Dimienii, comuna Beceni, judetul Buzau, Romania")),
						createLoc("Izvoru Dulce", "sat", createAdresaCompleta("sat Izvoru Dulce, comuna Beceni, judetul Buzau, România", "sat Izvoru Dulce, comuna Beceni, judetul Buzau, Romania")),
						createLoc("Mărgăriți", "sat", createAdresaCompleta("sat Mărgăriți, comuna Beceni, judetul Buzau, România", "sat Margariti, comuna Beceni, judetul Buzau, Romania")),
						createLoc("Valea Părului", "sat", createAdresaCompleta("sat Valea Părului, comuna Beceni, judetul Buzau, România", "sat Valea Parului, comuna Beceni, judetul Buzau, Romania")),
		]),
	createComuna("Berca", [
						createAdresaCompleta("comuna Berca, judetul BUZAU, România", "comuna Berca, judetul BUZAU, Romania"),
						createLoc("Berca", "sat", createAdresaCompleta("sat Berca, comuna Berca, judetul Buzau, România", "sat Berca, comuna Berca, judetul Buzau, Romania")),
						createLoc("Băceni", "sat", createAdresaCompleta("sat Băceni, comuna Berca, judetul Buzau, România", "sat Baceni, comuna Berca, judetul Buzau, Romania")),
						createLoc("Cojanu", "sat", createAdresaCompleta("sat Cojanu, comuna Berca, judetul Buzau, România", "sat Cojanu, comuna Berca, judetul Buzau, Romania")),
						createLoc("Joseni", "sat", createAdresaCompleta("sat Joseni, comuna Berca, judetul Buzau, România", "sat Joseni, comuna Berca, judetul Buzau, Romania")),
						createLoc("Mânăstirea Rătești", "sat", createAdresaCompleta("sat Mânăstirea Rătești, comuna Berca, judetul Buzau, România", "sat Manastirea Ratesti, comuna Berca, judetul Buzau, Romania")),
						createLoc("Pâclele", "sat", createAdresaCompleta("sat Pâclele, comuna Berca, judetul Buzau, România", "sat Paclele, comuna Berca, judetul Buzau, Romania")),
						createLoc("Pleșcoi", "sat", createAdresaCompleta("sat Pleșcoi, comuna Berca, judetul Buzau, România", "sat Plescoi, comuna Berca, judetul Buzau, Romania")),
						createLoc("Pleșești", "sat", createAdresaCompleta("sat Pleșești, comuna Berca, judetul Buzau, România", "sat Plesesti, comuna Berca, judetul Buzau, Romania")),
						createLoc("Rătești", "sat", createAdresaCompleta("sat Rătești, comuna Berca, judetul Buzau, România", "sat Ratesti, comuna Berca, judetul Buzau, Romania")),
						createLoc("Sătuc", "sat", createAdresaCompleta("sat Sătuc, comuna Berca, judetul Buzau, România", "sat Satuc, comuna Berca, judetul Buzau, Romania")),
						createLoc("Tâțârligu", "sat", createAdresaCompleta("sat Tâțârligu, comuna Berca, judetul Buzau, România", "sat Tatarligu, comuna Berca, judetul Buzau, Romania")),
						createLoc("Valea Nucului", "sat", createAdresaCompleta("sat Valea Nucului, comuna Berca, judetul Buzau, România", "sat Valea Nucului, comuna Berca, judetul Buzau, Romania")),
						createLoc("Viforâta", "sat", createAdresaCompleta("sat Viforâta, comuna Berca, judetul Buzau, România", "sat Viforata, comuna Berca, judetul Buzau, Romania")),
		]),
	createComuna("Bisoca", [
						createAdresaCompleta("comuna Bisoca, judetul BUZAU, România", "comuna Bisoca, judetul BUZAU, Romania"),
						createLoc("Bisoca", "sat", createAdresaCompleta("sat Bisoca, comuna Bisoca, judetul Buzau, România", "sat Bisoca, comuna Bisoca, judetul Buzau, Romania")),
						createLoc("Băltăgari", "sat", createAdresaCompleta("sat Băltăgari, comuna Bisoca, judetul Buzau, România", "sat Baltagari, comuna Bisoca, judetul Buzau, Romania")),
						createLoc("Lacurile", "sat", createAdresaCompleta("sat Lacurile, comuna Bisoca, judetul Buzau, România", "sat Lacurile, comuna Bisoca, judetul Buzau, Romania")),
						createLoc("Lopătăreasa", "sat", createAdresaCompleta("sat Lopătăreasa, comuna Bisoca, judetul Buzau, România", "sat Lopatareasa, comuna Bisoca, judetul Buzau, Romania")),
						createLoc("Pleși", "sat", createAdresaCompleta("sat Pleși, comuna Bisoca, judetul Buzau, România", "sat Plesi, comuna Bisoca, judetul Buzau, Romania")),
						createLoc("Recea", "sat", createAdresaCompleta("sat Recea, comuna Bisoca, judetul Buzau, România", "sat Recea, comuna Bisoca, judetul Buzau, Romania")),
						createLoc("Sările", "sat", createAdresaCompleta("sat Sările, comuna Bisoca, judetul Buzau, România", "sat Sarile, comuna Bisoca, judetul Buzau, Romania")),
						createLoc("Șindrila", "sat", createAdresaCompleta("sat Șindrila, comuna Bisoca, judetul Buzau, România", "sat Sindrila, comuna Bisoca, judetul Buzau, Romania")),
		]),
	createComuna("Blăjani", [
						createAdresaCompleta("comuna Blăjani, judetul BUZAU, România", "comuna Blajani, judetul BUZAU, Romania"),
						createLoc("Blăjani", "sat", createAdresaCompleta("sat Blăjani, comuna Blăjani, judetul Buzau, România", "sat Blajani, comuna Blajani, judetul Buzau, Romania")),
						createLoc("Sorești", "sat", createAdresaCompleta("sat Sorești, comuna Blăjani, judetul Buzau, România", "sat Soresti, comuna Blajani, judetul Buzau, Romania")),
		]),
	createComuna("Boldu", [
						createAdresaCompleta("comuna Boldu, judetul BUZAU, România", "comuna Boldu, judetul BUZAU, Romania"),
						createLoc("Boldu", "sat", createAdresaCompleta("sat Boldu, comuna Boldu, judetul Buzau, România", "sat Boldu, comuna Boldu, judetul Buzau, Romania")),
		]),
	createComuna("Bozioru", [
						createAdresaCompleta("comuna Bozioru, judetul BUZAU, România", "comuna Bozioru, judetul BUZAU, Romania"),
						createLoc("Bozioru", "sat", createAdresaCompleta("sat Bozioru, comuna Bozioru, judetul Buzau, România", "sat Bozioru, comuna Bozioru, judetul Buzau, Romania")),
						createLoc("Buduile", "sat", createAdresaCompleta("sat Buduile, comuna Bozioru, judetul Buzau, România", "sat Buduile, comuna Bozioru, judetul Buzau, Romania")),
						createLoc("Fișici", "sat", createAdresaCompleta("sat Fișici, comuna Bozioru, judetul Buzau, România", "sat Fisici, comuna Bozioru, judetul Buzau, Romania")),
						createLoc("Găvanele", "sat", createAdresaCompleta("sat Găvanele, comuna Bozioru, judetul Buzau, România", "sat Gavanele, comuna Bozioru, judetul Buzau, Romania")),
						createLoc("Gresia", "sat", createAdresaCompleta("sat Gresia, comuna Bozioru, judetul Buzau, România", "sat Gresia, comuna Bozioru, judetul Buzau, Romania")),
						createLoc("Izvoarele", "sat", createAdresaCompleta("sat Izvoarele, comuna Bozioru, judetul Buzau, România", "sat Izvoarele, comuna Bozioru, judetul Buzau, Romania")),
						createLoc("Nucu", "sat", createAdresaCompleta("sat Nucu, comuna Bozioru, judetul Buzau, România", "sat Nucu, comuna Bozioru, judetul Buzau, Romania")),
						createLoc("Scăeni", "sat", createAdresaCompleta("sat Scăeni, comuna Bozioru, judetul Buzau, România", "sat Scaeni, comuna Bozioru, judetul Buzau, Romania")),
						createLoc("Ulmet", "sat", createAdresaCompleta("sat Ulmet, comuna Bozioru, judetul Buzau, România", "sat Ulmet, comuna Bozioru, judetul Buzau, Romania")),
						createLoc("Văvălucile", "sat", createAdresaCompleta("sat Văvălucile, comuna Bozioru, judetul Buzau, România", "sat Vavalucile, comuna Bozioru, judetul Buzau, Romania")),
		]),
	createComuna("Brădeanu", [
						createAdresaCompleta("comuna Brădeanu, judetul BUZAU, România", "comuna Bradeanu, judetul BUZAU, Romania"),
						createLoc("Brădeanu", "sat", createAdresaCompleta("sat Brădeanu, comuna Brădeanu, judetul Buzau, România", "sat Bradeanu, comuna Bradeanu, judetul Buzau, Romania")),
						createLoc("Mitropolia", "sat", createAdresaCompleta("sat Mitropolia, comuna Brădeanu, judetul Buzau, România", "sat Mitropolia, comuna Bradeanu, judetul Buzau, Romania")),
						createLoc("Smârdan", "sat", createAdresaCompleta("sat Smârdan, comuna Brădeanu, judetul Buzau, România", "sat Smardan, comuna Bradeanu, judetul Buzau, Romania")),
		]),
	createComuna("Brăești", [
						createAdresaCompleta("comuna Brăești, judetul BUZAU, România", "comuna Braesti, judetul BUZAU, Romania"),
						createLoc("Brăești", "sat", createAdresaCompleta("sat Brăești, comuna Brăești, judetul Buzau, România", "sat Braesti, comuna Braesti, judetul Buzau, Romania")),
						createLoc("Brătilești", "sat", createAdresaCompleta("sat Brătilești, comuna Brăești, judetul Buzau, România", "sat Bratilesti, comuna Braesti, judetul Buzau, Romania")),
						createLoc("Goidești", "sat", createAdresaCompleta("sat Goidești, comuna Brăești, judetul Buzau, România", "sat Goidesti, comuna Braesti, judetul Buzau, Romania")),
						createLoc("Ivănețu", "sat", createAdresaCompleta("sat Ivănețu, comuna Brăești, judetul Buzau, România", "sat Ivanetu, comuna Braesti, judetul Buzau, Romania")),
						createLoc("Pinu", "sat", createAdresaCompleta("sat Pinu, comuna Brăești, judetul Buzau, România", "sat Pinu, comuna Braesti, judetul Buzau, Romania")),
						createLoc("Pârscovelu", "sat", createAdresaCompleta("sat Pârscovelu, comuna Brăești, judetul Buzau, România", "sat Parscovelu, comuna Braesti, judetul Buzau, Romania")),
						createLoc("Ruginoasa", "sat", createAdresaCompleta("sat Ruginoasa, comuna Brăești, judetul Buzau, România", "sat Ruginoasa, comuna Braesti, judetul Buzau, Romania")),
		]),
	createComuna("Breaza", [
						createAdresaCompleta("comuna Breaza, judetul BUZAU, România", "comuna Breaza, judetul BUZAU, Romania"),
						createLoc("Breaza", "sat", createAdresaCompleta("sat Breaza, comuna Breaza, judetul Buzau, România", "sat Breaza, comuna Breaza, judetul Buzau, Romania")),
						createLoc("Bădeni", "sat", createAdresaCompleta("sat Bădeni, comuna Breaza, judetul Buzau, România", "sat Badeni, comuna Breaza, judetul Buzau, Romania")),
						createLoc("Greceanca", "sat", createAdresaCompleta("sat Greceanca, comuna Breaza, judetul Buzau, România", "sat Greceanca, comuna Breaza, judetul Buzau, Romania")),
						createLoc("Văleanca-Vilănești", "sat", createAdresaCompleta("sat Văleanca-Vilănești, comuna Breaza, judetul Buzau, România", "sat Valeanca-Vilanesti, comuna Breaza, judetul Buzau, Romania")),
						createLoc("Vispești", "sat", createAdresaCompleta("sat Vispești, comuna Breaza, judetul Buzau, România", "sat Vispesti, comuna Breaza, judetul Buzau, Romania")),
		]),
	createComuna("Buda", [
						createAdresaCompleta("comuna Buda, judetul BUZAU, România", "comuna Buda, judetul BUZAU, Romania"),
						createLoc("Buda", "sat", createAdresaCompleta("sat Buda, comuna Buda, judetul Buzau, România", "sat Buda, comuna Buda, judetul Buzau, Romania")),
						createLoc("Alexandru Odobescu", "sat", createAdresaCompleta("sat Alexandru Odobescu, comuna Buda, judetul Buzau, România", "sat Alexandru Odobescu, comuna Buda, judetul Buzau, Romania")),
						createLoc("Dănulești", "sat", createAdresaCompleta("sat Dănulești, comuna Buda, judetul Buzau, România", "sat Danulesti, comuna Buda, judetul Buzau, Romania")),
						createLoc("Mucești-Dănulești", "sat", createAdresaCompleta("sat Mucești-Dănulești, comuna Buda, judetul Buzau, România", "sat Mucesti-Danulesti, comuna Buda, judetul Buzau, Romania")),
						createLoc("Spidele", "sat", createAdresaCompleta("sat Spidele, comuna Buda, judetul Buzau, România", "sat Spidele, comuna Buda, judetul Buzau, Romania")),
						createLoc("Toropălești", "sat", createAdresaCompleta("sat Toropălești, comuna Buda, judetul Buzau, România", "sat Toropalesti, comuna Buda, judetul Buzau, Romania")),
						createLoc("Valea Largă", "sat", createAdresaCompleta("sat Valea Largă, comuna Buda, judetul Buzau, România", "sat Valea Larga, comuna Buda, judetul Buzau, Romania")),
		]),
	createComuna("Calvini", [
						createAdresaCompleta("comuna Calvini, judetul BUZAU, România", "comuna Calvini, judetul BUZAU, Romania"),
						createLoc("Calvini", "sat", createAdresaCompleta("sat Calvini, comuna Calvini, judetul Buzau, România", "sat Calvini, comuna Calvini, judetul Buzau, Romania")),
						createLoc("Bâscenii de Jos", "sat", createAdresaCompleta("sat Bâscenii de Jos, comuna Calvini, judetul Buzau, România", "sat Bascenii de Jos, comuna Calvini, judetul Buzau, Romania")),
						createLoc("Bâscenii de Sus", "sat", createAdresaCompleta("sat Bâscenii de Sus, comuna Calvini, judetul Buzau, România", "sat Bascenii de Sus, comuna Calvini, judetul Buzau, Romania")),
						createLoc("Frăsinet", "sat", createAdresaCompleta("sat Frăsinet, comuna Calvini, judetul Buzau, România", "sat Frasinet, comuna Calvini, judetul Buzau, Romania")),
						createLoc("Olari", "sat", createAdresaCompleta("sat Olari, comuna Calvini, judetul Buzau, România", "sat Olari, comuna Calvini, judetul Buzau, Romania")),
		]),
	createComuna("C.A. Rosetti", [
						createAdresaCompleta("comuna C.A. Rosetti, judetul BUZAU, România", "comuna C.A. Rosetti, judetul BUZAU, Romania"),
						createLoc("C.A. Rosetti", "sat", createAdresaCompleta("sat C.A. Rosetti, comuna C.A. Rosetti, judetul Buzau, România", "sat C.A. Rosetti, comuna C.A. Rosetti, judetul Buzau, Romania")),
						createLoc("Bălteni", "sat", createAdresaCompleta("sat Bălteni, comuna C.A. Rosetti, judetul Buzau, România", "sat Balteni, comuna C.A. Rosetti, judetul Buzau, Romania")),
						createLoc("Bâlhacu", "sat", createAdresaCompleta("sat Bâlhacu, comuna C.A. Rosetti, judetul Buzau, România", "sat Balhacu, comuna C.A. Rosetti, judetul Buzau, Romania")),
						createLoc("Cotu Ciorii", "sat", createAdresaCompleta("sat Cotu Ciorii, comuna C.A. Rosetti, judetul Buzau, România", "sat Cotu Ciorii, comuna C.A. Rosetti, judetul Buzau, Romania")),
						createLoc("Lunca", "sat", createAdresaCompleta("sat Lunca, comuna C.A. Rosetti, judetul Buzau, România", "sat Lunca, comuna C.A. Rosetti, judetul Buzau, Romania")),
						createLoc("Vizireni", "sat", createAdresaCompleta("sat Vizireni, comuna C.A. Rosetti, judetul Buzau, România", "sat Vizireni, comuna C.A. Rosetti, judetul Buzau, Romania")),
		]),
	createComuna("Cănești", [
						createAdresaCompleta("comuna Cănești, judetul BUZAU, România", "comuna Canesti, judetul BUZAU, Romania"),
						createLoc("Cănești", "sat", createAdresaCompleta("sat Cănești, comuna Cănești, judetul Buzau, România", "sat Canesti, comuna Canesti, judetul Buzau, Romania")),
						createLoc("Gonțești", "sat", createAdresaCompleta("sat Gonțești, comuna Cănești, judetul Buzau, România", "sat Gontesti, comuna Canesti, judetul Buzau, Romania")),
						createLoc("Negoșina", "sat", createAdresaCompleta("sat Negoșina, comuna Cănești, judetul Buzau, România", "sat Negosina, comuna Canesti, judetul Buzau, Romania")),
						createLoc("Păcurile", "sat", createAdresaCompleta("sat Păcurile, comuna Cănești, judetul Buzau, România", "sat Pacurile, comuna Canesti, judetul Buzau, Romania")),
						createLoc("Șuchea", "sat", createAdresaCompleta("sat Șuchea, comuna Cănești, judetul Buzau, România", "sat Suchea, comuna Canesti, judetul Buzau, Romania")),
						createLoc("Valea Verzei", "sat", createAdresaCompleta("sat Valea Verzei, comuna Cănești, judetul Buzau, România", "sat Valea Verzei, comuna Canesti, judetul Buzau, Romania")),
		]),
	createComuna("Cătina", [
						createAdresaCompleta("comuna Cătina, judetul BUZAU, România", "comuna Catina, judetul BUZAU, Romania"),
						createLoc("Cătina", "sat", createAdresaCompleta("sat Cătina, comuna Cătina, judetul Buzau, România", "sat Catina, comuna Catina, judetul Buzau, Romania")),
						createLoc("Corbu", "sat", createAdresaCompleta("sat Corbu, comuna Cătina, judetul Buzau, România", "sat Corbu, comuna Catina, judetul Buzau, Romania")),
						createLoc("Slobozia", "sat", createAdresaCompleta("sat Slobozia, comuna Cătina, judetul Buzau, România", "sat Slobozia, comuna Catina, judetul Buzau, Romania")),
						createLoc("Valea Cătinei", "sat", createAdresaCompleta("sat Valea Cătinei, comuna Cătina, judetul Buzau, România", "sat Valea Catinei, comuna Catina, judetul Buzau, Romania")),
						createLoc("Zeletin", "sat", createAdresaCompleta("sat Zeletin, comuna Cătina, judetul Buzau, România", "sat Zeletin, comuna Catina, judetul Buzau, Romania")),
		]),
	createComuna("Cernătești", [
						createAdresaCompleta("comuna Cernătești, judetul BUZAU, România", "comuna Cernatesti, judetul BUZAU, Romania"),
						createLoc("Cernătești", "sat", createAdresaCompleta("sat Cernătești, comuna Cernătești, judetul Buzau, România", "sat Cernatesti, comuna Cernatesti, judetul Buzau, Romania")),
						createLoc("Aldeni", "sat", createAdresaCompleta("sat Aldeni, comuna Cernătești, judetul Buzau, România", "sat Aldeni, comuna Cernatesti, judetul Buzau, Romania")),
						createLoc("Băești", "sat", createAdresaCompleta("sat Băești, comuna Cernătești, judetul Buzau, România", "sat Baesti, comuna Cernatesti, judetul Buzau, Romania")),
						createLoc("Căldărușa", "sat", createAdresaCompleta("sat Căldărușa, comuna Cernătești, judetul Buzau, România", "sat Caldarusa, comuna Cernatesti, judetul Buzau, Romania")),
						createLoc("Fulga", "sat", createAdresaCompleta("sat Fulga, comuna Cernătești, judetul Buzau, România", "sat Fulga, comuna Cernatesti, judetul Buzau, Romania")),
						createLoc("Manasia", "sat", createAdresaCompleta("sat Manasia, comuna Cernătești, judetul Buzau, România", "sat Manasia, comuna Cernatesti, judetul Buzau, Romania")),
						createLoc("Vlădeni", "sat", createAdresaCompleta("sat Vlădeni, comuna Cernătești, judetul Buzau, România", "sat Vladeni, comuna Cernatesti, judetul Buzau, Romania")),
						createLoc("Zărneștii de Slănic", "sat", createAdresaCompleta("sat Zărneștii de Slănic, comuna Cernătești, judetul Buzau, România", "sat Zarnestii de Slanic, comuna Cernatesti, judetul Buzau, Romania")),
		]),
	createComuna("Chiliile", [
						createAdresaCompleta("comuna Chiliile, judetul BUZAU, România", "comuna Chiliile, judetul BUZAU, Romania"),
						createLoc("Chiliile", "sat", createAdresaCompleta("sat Chiliile, comuna Chiliile, judetul Buzau, România", "sat Chiliile, comuna Chiliile, judetul Buzau, Romania")),
						createLoc("Budești", "sat", createAdresaCompleta("sat Budești, comuna Chiliile, judetul Buzau, România", "sat Budesti, comuna Chiliile, judetul Buzau, Romania")),
						createLoc("Crevelești", "sat", createAdresaCompleta("sat Crevelești, comuna Chiliile, judetul Buzau, România", "sat Crevelesti, comuna Chiliile, judetul Buzau, Romania")),
						createLoc("Ghiocari", "sat", createAdresaCompleta("sat Ghiocari, comuna Chiliile, judetul Buzau, România", "sat Ghiocari, comuna Chiliile, judetul Buzau, Romania")),
						createLoc("Glodu-Petcari", "sat", createAdresaCompleta("sat Glodu-Petcari, comuna Chiliile, judetul Buzau, România", "sat Glodu-Petcari, comuna Chiliile, judetul Buzau, Romania")),
						createLoc("Poiana Pletari", "sat", createAdresaCompleta("sat Poiana Pletari, comuna Chiliile, judetul Buzau, România", "sat Poiana Pletari, comuna Chiliile, judetul Buzau, Romania")),
						createLoc("Trestioora", "sat", createAdresaCompleta("sat Trestioora, comuna Chiliile, judetul Buzau, România", "sat Trestioora, comuna Chiliile, judetul Buzau, Romania")),
		]),
	createComuna("Chiojdu", [
						createAdresaCompleta("comuna Chiojdu, judetul BUZAU, România", "comuna Chiojdu, judetul BUZAU, Romania"),
						createLoc("Chiojdu", "sat", createAdresaCompleta("sat Chiojdu, comuna Chiojdu, judetul Buzau, România", "sat Chiojdu, comuna Chiojdu, judetul Buzau, Romania")),
						createLoc("Bâsca Chiojdului", "sat", createAdresaCompleta("sat Bâsca Chiojdului, comuna Chiojdu, judetul Buzau, România", "sat Basca Chiojdului, comuna Chiojdu, judetul Buzau, Romania")),
						createLoc("Cătiașu", "sat", createAdresaCompleta("sat Cătiașu, comuna Chiojdu, judetul Buzau, România", "sat Catiasu, comuna Chiojdu, judetul Buzau, Romania")),
						createLoc("Lera", "sat", createAdresaCompleta("sat Lera, comuna Chiojdu, judetul Buzau, România", "sat Lera, comuna Chiojdu, judetul Buzau, Romania")),
						createLoc("Plescioara", "sat", createAdresaCompleta("sat Plescioara, comuna Chiojdu, judetul Buzau, România", "sat Plescioara, comuna Chiojdu, judetul Buzau, Romania")),
						createLoc("Poenițele", "sat", createAdresaCompleta("sat Poenițele, comuna Chiojdu, judetul Buzau, România", "sat Poenitele, comuna Chiojdu, judetul Buzau, Romania")),
		]),
	createComuna("Cilibia", [
						createAdresaCompleta("comuna Cilibia, judetul BUZAU, România", "comuna Cilibia, judetul BUZAU, Romania"),
						createLoc("Cilibia", "sat", createAdresaCompleta("sat Cilibia, comuna Cilibia, judetul Buzau, România", "sat Cilibia, comuna Cilibia, judetul Buzau, Romania")),
						createLoc("Gara Cilibia", "sat", createAdresaCompleta("sat Gara Cilibia, comuna Cilibia, judetul Buzau, România", "sat Gara Cilibia, comuna Cilibia, judetul Buzau, Romania")),
						createLoc("Mânzu", "sat", createAdresaCompleta("sat Mânzu, comuna Cilibia, judetul Buzau, România", "sat Manzu, comuna Cilibia, judetul Buzau, Romania")),
						createLoc("Movila Oii", "sat", createAdresaCompleta("sat Movila Oii, comuna Cilibia, judetul Buzau, România", "sat Movila Oii, comuna Cilibia, judetul Buzau, Romania")),
						createLoc("Poșta", "sat", createAdresaCompleta("sat Poșta, comuna Cilibia, judetul Buzau, România", "sat Posta, comuna Cilibia, judetul Buzau, Romania")),
		]),
	createComuna("Cislău", [
						createAdresaCompleta("comuna Cislău, judetul BUZAU, România", "comuna Cislau, judetul BUZAU, Romania"),
						createLoc("Cislău", "sat", createAdresaCompleta("sat Cislău, comuna Cislău, judetul Buzau, România", "sat Cislau, comuna Cislau, judetul Buzau, Romania")),
						createLoc("Bărăști", "sat", createAdresaCompleta("sat Bărăști, comuna Cislău, judetul Buzau, România", "sat Barasti, comuna Cislau, judetul Buzau, Romania")),
						createLoc("Buda Crăciunești", "sat", createAdresaCompleta("sat Buda Crăciunești, comuna Cislău, judetul Buzau, România", "sat Buda Craciunesti, comuna Cislau, judetul Buzau, Romania")),
						createLoc("Gura Bâscei", "sat", createAdresaCompleta("sat Gura Bâscei, comuna Cislău, judetul Buzau, România", "sat Gura Bascei, comuna Cislau, judetul Buzau, Romania")),
						createLoc("Scărișoara", "sat", createAdresaCompleta("sat Scărișoara, comuna Cislău, judetul Buzau, România", "sat Scarisoara, comuna Cislau, judetul Buzau, Romania")),
		]),
	createComuna("Cochirleanca", [
						createAdresaCompleta("comuna Cochirleanca, judetul BUZAU, România", "comuna Cochirleanca, judetul BUZAU, Romania"),
						createLoc("Cochirleanca", "sat", createAdresaCompleta("sat Cochirleanca, comuna Cochirleanca, judetul Buzau, România", "sat Cochirleanca, comuna Cochirleanca, judetul Buzau, Romania")),
						createLoc("Boboc", "sat", createAdresaCompleta("sat Boboc, comuna Cochirleanca, judetul Buzau, România", "sat Boboc, comuna Cochirleanca, judetul Buzau, Romania")),
						createLoc("Gara Bobocu", "sat", createAdresaCompleta("sat Gara Bobocu, comuna Cochirleanca, judetul Buzau, România", "sat Gara Bobocu, comuna Cochirleanca, judetul Buzau, Romania")),
						createLoc("Roșioru", "sat", createAdresaCompleta("sat Roșioru, comuna Cochirleanca, judetul Buzau, România", "sat Rosioru, comuna Cochirleanca, judetul Buzau, Romania")),
						createLoc("Târlele", "sat", createAdresaCompleta("sat Târlele, comuna Cochirleanca, judetul Buzau, România", "sat Tarlele, comuna Cochirleanca, judetul Buzau, Romania")),
		]),
	createComuna("Colți", [
						createAdresaCompleta("comuna Colți, judetul BUZAU, România", "comuna Colti, judetul BUZAU, Romania"),
						createLoc("Colți", "sat", createAdresaCompleta("sat Colți, comuna Colți, judetul Buzau, România", "sat Colti, comuna Colti, judetul Buzau, Romania")),
						createLoc("Aluniș", "sat", createAdresaCompleta("sat Aluniș, comuna Colți, judetul Buzau, România", "sat Alunis, comuna Colti, judetul Buzau, Romania")),
						createLoc("Colții de Jos", "sat", createAdresaCompleta("sat Colții de Jos, comuna Colți, judetul Buzau, România", "sat Coltii de Jos, comuna Colti, judetul Buzau, Romania")),
						createLoc("Muscelu Cărămănești", "sat", createAdresaCompleta("sat Muscelu Cărămănești, comuna Colți, judetul Buzau, România", "sat Muscelu Caramanesti, comuna Colti, judetul Buzau, Romania")),
		]),
	createComuna("Costești", [
						createAdresaCompleta("comuna Costești, judetul BUZAU, România", "comuna Costesti, judetul BUZAU, Romania"),
						createLoc("Costești", "sat", createAdresaCompleta("sat Costești, comuna Costești, judetul Buzau, România", "sat Costesti, comuna Costesti, judetul Buzau, Romania")),
						createLoc("Budișteni", "sat", createAdresaCompleta("sat Budișteni, comuna Costești, judetul Buzau, România", "sat Budisteni, comuna Costesti, judetul Buzau, Romania")),
						createLoc("Gomoești", "sat", createAdresaCompleta("sat Gomoești, comuna Costești, judetul Buzau, România", "sat Gomoesti, comuna Costesti, judetul Buzau, Romania")),
						createLoc("Groșani", "sat", createAdresaCompleta("sat Groșani, comuna Costești, judetul Buzau, România", "sat Grosani, comuna Costesti, judetul Buzau, Romania")),
						createLoc("Pietrosu", "sat", createAdresaCompleta("sat Pietrosu, comuna Costești, judetul Buzau, România", "sat Pietrosu, comuna Costesti, judetul Buzau, Romania")),
						createLoc("Spătaru", "sat", createAdresaCompleta("sat Spătaru, comuna Costești, judetul Buzau, România", "sat Spataru, comuna Costesti, judetul Buzau, Romania")),
		]),
	createComuna("Cozieni", [
						createAdresaCompleta("comuna Cozieni, judetul BUZAU, România", "comuna Cozieni, judetul BUZAU, Romania"),
						createLoc("Cozieni", "sat", createAdresaCompleta("sat Cozieni, comuna Cozieni, judetul Buzau, România", "sat Cozieni, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Anini", "sat", createAdresaCompleta("sat Anini, comuna Cozieni, judetul Buzau, România", "sat Anini, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Bălănești", "sat", createAdresaCompleta("sat Bălănești, comuna Cozieni, judetul Buzau, România", "sat Balanesti, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Bercești", "sat", createAdresaCompleta("sat Bercești, comuna Cozieni, judetul Buzau, România", "sat Bercesti, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Ciocănești", "sat", createAdresaCompleta("sat Ciocănești, comuna Cozieni, judetul Buzau, România", "sat Ciocanesti, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Cocârceni", "sat", createAdresaCompleta("sat Cocârceni, comuna Cozieni, judetul Buzau, România", "sat Cocarceni, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Colțeni", "sat", createAdresaCompleta("sat Colțeni, comuna Cozieni, judetul Buzau, România", "sat Colteni, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Fața lui Nan", "sat", createAdresaCompleta("sat Fața lui Nan, comuna Cozieni, judetul Buzau, România", "sat Fata lui Nan, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Glodurile", "sat", createAdresaCompleta("sat Glodurile, comuna Cozieni, judetul Buzau, România", "sat Glodurile, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Izvoru", "sat", createAdresaCompleta("sat Izvoru, comuna Cozieni, judetul Buzau, România", "sat Izvoru, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Lungești", "sat", createAdresaCompleta("sat Lungești, comuna Cozieni, judetul Buzau, România", "sat Lungesti, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Nistorești", "sat", createAdresaCompleta("sat Nistorești, comuna Cozieni, judetul Buzau, România", "sat Nistoresti, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Pietraru", "sat", createAdresaCompleta("sat Pietraru, comuna Cozieni, judetul Buzau, România", "sat Pietraru, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Punga", "sat", createAdresaCompleta("sat Punga, comuna Cozieni, judetul Buzau, România", "sat Punga, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Teișu", "sat", createAdresaCompleta("sat Teișu, comuna Cozieni, judetul Buzau, România", "sat Teisu, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Trestia", "sat", createAdresaCompleta("sat Trestia, comuna Cozieni, judetul Buzau, România", "sat Trestia, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Tulburea", "sat", createAdresaCompleta("sat Tulburea, comuna Cozieni, judetul Buzau, România", "sat Tulburea, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Valea Banului", "sat", createAdresaCompleta("sat Valea Banului, comuna Cozieni, judetul Buzau, România", "sat Valea Banului, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Valea Roatei", "sat", createAdresaCompleta("sat Valea Roatei, comuna Cozieni, judetul Buzau, România", "sat Valea Roatei, comuna Cozieni, judetul Buzau, Romania")),
						createLoc("Zăpodia", "sat", createAdresaCompleta("sat Zăpodia, comuna Cozieni, judetul Buzau, România", "sat Zapodia, comuna Cozieni, judetul Buzau, Romania")),
		]),
	createComuna("Florica", [
						createAdresaCompleta("comuna Florica, judetul BUZAU, România", "comuna Florica, judetul BUZAU, Romania"),
						createLoc("Florica", "sat", createAdresaCompleta("sat Florica, comuna Florica, judetul Buzau, România", "sat Florica, comuna Florica, judetul Buzau, Romania")),
		]),
	createComuna("Gălbinași", [
						createAdresaCompleta("comuna Gălbinași, judetul BUZAU, România", "comuna Galbinasi, judetul BUZAU, Romania"),
						createLoc("Gălbinași", "sat", createAdresaCompleta("sat Gălbinași, comuna Gălbinași, judetul Buzau, România", "sat Galbinasi, comuna Galbinasi, judetul Buzau, Romania")),
						createLoc("Bentu", "sat", createAdresaCompleta("sat Bentu, comuna Gălbinași, judetul Buzau, România", "sat Bentu, comuna Galbinasi, judetul Buzau, Romania")),
						createLoc("Tăbărăști", "sat", createAdresaCompleta("sat Tăbărăști, comuna Gălbinași, judetul Buzau, România", "sat Tabarasti, comuna Galbinasi, judetul Buzau, Romania")),
		]),
	createComuna("Gherăseni", [
						createAdresaCompleta("comuna Gherăseni, judetul BUZAU, România", "comuna Gheraseni, judetul BUZAU, Romania"),
						createLoc("Gherăseni", "sat", createAdresaCompleta("sat Gherăseni, comuna Gherăseni, judetul Buzau, România", "sat Gheraseni, comuna Gheraseni, judetul Buzau, Romania")),
						createLoc("Sudiți", "sat", createAdresaCompleta("sat Sudiți, comuna Gherăseni, judetul Buzau, România", "sat Suditi, comuna Gheraseni, judetul Buzau, Romania")),
		]),
	createComuna("Ghergheasa", [
						createAdresaCompleta("comuna Ghergheasa, judetul BUZAU, România", "comuna Ghergheasa, judetul BUZAU, Romania"),
						createLoc("Ghergheasa", "sat", createAdresaCompleta("sat Ghergheasa, comuna Ghergheasa, judetul Buzau, România", "sat Ghergheasa, comuna Ghergheasa, judetul Buzau, Romania")),
						createLoc("Sălcioara", "sat", createAdresaCompleta("sat Sălcioara, comuna Ghergheasa, judetul Buzau, România", "sat Salcioara, comuna Ghergheasa, judetul Buzau, Romania")),
		]),
	createComuna("Glodeanu Sărat", [
						createAdresaCompleta("comuna Glodeanu Sărat, judetul BUZAU, România", "comuna Glodeanu Sarat, judetul BUZAU, Romania"),
						createLoc("Glodeanu Sărat", "sat", createAdresaCompleta("sat Glodeanu Sărat, comuna Glodeanu Sărat, judetul Buzau, România", "sat Glodeanu Sarat, comuna Glodeanu Sarat, judetul Buzau, Romania")),
						createLoc("Căldărușeanca", "sat", createAdresaCompleta("sat Căldărușeanca, comuna Glodeanu Sărat, judetul Buzau, România", "sat Caldaruseanca, comuna Glodeanu Sarat, judetul Buzau, Romania")),
						createLoc("Ileana", "sat", createAdresaCompleta("sat Ileana, comuna Glodeanu Sărat, judetul Buzau, România", "sat Ileana, comuna Glodeanu Sarat, judetul Buzau, Romania")),
						createLoc("Pitulicea", "sat", createAdresaCompleta("sat Pitulicea, comuna Glodeanu Sărat, judetul Buzau, România", "sat Pitulicea, comuna Glodeanu Sarat, judetul Buzau, Romania")),
		]),
	createComuna("Glodeanu-Siliștea", [
						createAdresaCompleta("comuna Glodeanu-Siliștea, judetul BUZAU, România", "comuna Glodeanu-Silistea, judetul BUZAU, Romania"),
						createLoc("Glodeanu-Siliștea", "sat", createAdresaCompleta("sat Glodeanu-Siliștea, comuna Glodeanu-Siliștea, judetul Buzau, România", "sat Glodeanu-Silistea, comuna Glodeanu-Silistea, judetul Buzau, Romania")),
						createLoc("Casota", "sat", createAdresaCompleta("sat Casota, comuna Glodeanu-Siliștea, judetul Buzau, România", "sat Casota, comuna Glodeanu-Silistea, judetul Buzau, Romania")),
						createLoc("Cârligu Mare", "sat", createAdresaCompleta("sat Cârligu Mare, comuna Glodeanu-Siliștea, judetul Buzau, România", "sat Carligu Mare, comuna Glodeanu-Silistea, judetul Buzau, Romania")),
						createLoc("Cârligu Mic", "sat", createAdresaCompleta("sat Cârligu Mic, comuna Glodeanu-Siliștea, judetul Buzau, România", "sat Carligu Mic, comuna Glodeanu-Silistea, judetul Buzau, Romania")),
						createLoc("Corbu", "sat", createAdresaCompleta("sat Corbu, comuna Glodeanu-Siliștea, judetul Buzau, România", "sat Corbu, comuna Glodeanu-Silistea, judetul Buzau, Romania")),
						createLoc("Cotorca", "sat", createAdresaCompleta("sat Cotorca, comuna Glodeanu-Siliștea, judetul Buzau, România", "sat Cotorca, comuna Glodeanu-Silistea, judetul Buzau, Romania")),
						createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Glodeanu-Siliștea, judetul Buzau, România", "sat Satu Nou, comuna Glodeanu-Silistea, judetul Buzau, Romania")),
						createLoc("Văcăreasca", "sat", createAdresaCompleta("sat Văcăreasca, comuna Glodeanu-Siliștea, judetul Buzau, România", "sat Vacareasca, comuna Glodeanu-Silistea, judetul Buzau, Romania")),
		]),
	createComuna("Grebănu", [
						createAdresaCompleta("comuna Grebănu, judetul BUZAU, România", "comuna Grebanu, judetul BUZAU, Romania"),
						createLoc("Grebănu", "sat", createAdresaCompleta("sat Grebănu, comuna Grebănu, judetul Buzau, România", "sat Grebanu, comuna Grebanu, judetul Buzau, Romania")),
						createLoc("Homești", "sat", createAdresaCompleta("sat Homești, comuna Grebănu, judetul Buzau, România", "sat Homesti, comuna Grebanu, judetul Buzau, Romania")),
						createLoc("Livada", "sat", createAdresaCompleta("sat Livada, comuna Grebănu, judetul Buzau, România", "sat Livada, comuna Grebanu, judetul Buzau, Romania")),
						createLoc("Livada Mică", "sat", createAdresaCompleta("sat Livada Mică, comuna Grebănu, judetul Buzau, România", "sat Livada Mica, comuna Grebanu, judetul Buzau, Romania")),
						createLoc("Plevna", "sat", createAdresaCompleta("sat Plevna, comuna Grebănu, judetul Buzau, România", "sat Plevna, comuna Grebanu, judetul Buzau, Romania")),
						createLoc("Zăplazi", "sat", createAdresaCompleta("sat Zăplazi, comuna Grebănu, judetul Buzau, România", "sat Zaplazi, comuna Grebanu, judetul Buzau, Romania")),
		]),
	createComuna("Gura Teghii", [
						createAdresaCompleta("comuna Gura Teghii, judetul BUZAU, România", "comuna Gura Teghii, judetul BUZAU, Romania"),
						createLoc("Gura Teghii", "sat", createAdresaCompleta("sat Gura Teghii, comuna Gura Teghii, judetul Buzau, România", "sat Gura Teghii, comuna Gura Teghii, judetul Buzau, Romania")),
						createLoc("Furtunești", "sat", createAdresaCompleta("sat Furtunești, comuna Gura Teghii, judetul Buzau, România", "sat Furtunesti, comuna Gura Teghii, judetul Buzau, Romania")),
						createLoc("Nemertea", "sat", createAdresaCompleta("sat Nemertea, comuna Gura Teghii, judetul Buzau, România", "sat Nemertea, comuna Gura Teghii, judetul Buzau, Romania")),
						createLoc("Păltiniș", "sat", createAdresaCompleta("sat Păltiniș, comuna Gura Teghii, judetul Buzau, România", "sat Paltinis, comuna Gura Teghii, judetul Buzau, Romania")),
						createLoc("Secuiu", "sat", createAdresaCompleta("sat Secuiu, comuna Gura Teghii, judetul Buzau, România", "sat Secuiu, comuna Gura Teghii, judetul Buzau, Romania")),
						createLoc("Vadu Oii", "sat", createAdresaCompleta("sat Vadu Oii, comuna Gura Teghii, judetul Buzau, România", "sat Vadu Oii, comuna Gura Teghii, judetul Buzau, Romania")),
						createLoc("Varlaam", "sat", createAdresaCompleta("sat Varlaam, comuna Gura Teghii, judetul Buzau, România", "sat Varlaam, comuna Gura Teghii, judetul Buzau, Romania")),
		]),
	createComuna("Largu", [
						createAdresaCompleta("comuna Largu, judetul BUZAU, România", "comuna Largu, judetul BUZAU, Romania"),
						createLoc("Largu", "sat", createAdresaCompleta("sat Largu, comuna Largu, judetul Buzau, România", "sat Largu, comuna Largu, judetul Buzau, Romania")),
						createLoc("Scărlătești", "sat", createAdresaCompleta("sat Scărlătești, comuna Largu, judetul Buzau, România", "sat Scarlatesti, comuna Largu, judetul Buzau, Romania")),
		]),
	createComuna("Lopătari", [
						createAdresaCompleta("comuna Lopătari, judetul BUZAU, România", "comuna Lopatari, judetul BUZAU, Romania"),
						createLoc("Lopătari", "sat", createAdresaCompleta("sat Lopătari, comuna Lopătari, judetul Buzau, România", "sat Lopatari, comuna Lopatari, judetul Buzau, Romania")),
						createLoc("Brebu", "sat", createAdresaCompleta("sat Brebu, comuna Lopătari, judetul Buzau, România", "sat Brebu, comuna Lopatari, judetul Buzau, Romania")),
						createLoc("Fundata", "sat", createAdresaCompleta("sat Fundata, comuna Lopătari, judetul Buzau, România", "sat Fundata, comuna Lopatari, judetul Buzau, Romania")),
						createLoc("Luncile", "sat", createAdresaCompleta("sat Luncile, comuna Lopătari, judetul Buzau, România", "sat Luncile, comuna Lopatari, judetul Buzau, Romania")),
						createLoc("Pestrițu", "sat", createAdresaCompleta("sat Pestrițu, comuna Lopătari, judetul Buzau, România", "sat Pestritu, comuna Lopatari, judetul Buzau, Romania")),
						createLoc("Plaiu Nucului", "sat", createAdresaCompleta("sat Plaiu Nucului, comuna Lopătari, judetul Buzau, România", "sat Plaiu Nucului, comuna Lopatari, judetul Buzau, Romania")),
						createLoc("Ploștina", "sat", createAdresaCompleta("sat Ploștina, comuna Lopătari, judetul Buzau, România", "sat Plostina, comuna Lopatari, judetul Buzau, Romania")),
						createLoc("Potecu", "sat", createAdresaCompleta("sat Potecu, comuna Lopătari, judetul Buzau, România", "sat Potecu, comuna Lopatari, judetul Buzau, Romania")),
						createLoc("Săreni", "sat", createAdresaCompleta("sat Săreni, comuna Lopătari, judetul Buzau, România", "sat Sareni, comuna Lopatari, judetul Buzau, Romania")),
						createLoc("Terca", "sat", createAdresaCompleta("sat Terca, comuna Lopătari, judetul Buzau, România", "sat Terca, comuna Lopatari, judetul Buzau, Romania")),
						createLoc("Vârteju", "sat", createAdresaCompleta("sat Vârteju, comuna Lopătari, judetul Buzau, România", "sat Varteju, comuna Lopatari, judetul Buzau, Romania")),
		]),
	createComuna("Luciu", [
						createAdresaCompleta("comuna Luciu, judetul BUZAU, România", "comuna Luciu, judetul BUZAU, Romania"),
						createLoc("Luciu", "sat", createAdresaCompleta("sat Luciu, comuna Luciu, judetul Buzau, România", "sat Luciu, comuna Luciu, judetul Buzau, Romania")),
						createLoc("Caragele", "sat", createAdresaCompleta("sat Caragele, comuna Luciu, judetul Buzau, România", "sat Caragele, comuna Luciu, judetul Buzau, Romania")),
		]),
	createComuna("Măgura", [
						createAdresaCompleta("comuna Măgura, judetul BUZAU, România", "comuna Magura, judetul BUZAU, Romania"),
						createLoc("Măgura", "sat", createAdresaCompleta("sat Măgura, comuna Măgura, judetul Buzau, România", "sat Magura, comuna Magura, judetul Buzau, Romania")),
						createLoc("Ciuta", "sat", createAdresaCompleta("sat Ciuta, comuna Măgura, judetul Buzau, România", "sat Ciuta, comuna Magura, judetul Buzau, Romania")),
		]),
	createComuna("Mărăcineni", [
						createAdresaCompleta("comuna Mărăcineni, judetul BUZAU, România", "comuna Maracineni, judetul BUZAU, Romania"),
						createLoc("Mărăcineni", "sat", createAdresaCompleta("sat Mărăcineni, comuna Mărăcineni, judetul Buzau, România", "sat Maracineni, comuna Maracineni, judetul Buzau, Romania")),
						createLoc("Căpățânești", "sat", createAdresaCompleta("sat Căpățânești, comuna Mărăcineni, judetul Buzau, România", "sat Capatanesti, comuna Maracineni, judetul Buzau, Romania")),
						createLoc("Potoceni", "sat", createAdresaCompleta("sat Potoceni, comuna Mărăcineni, judetul Buzau, România", "sat Potoceni, comuna Maracineni, judetul Buzau, Romania")),
		]),
	createComuna("Mărgăritești", [
						createAdresaCompleta("comuna Mărgăritești, judetul BUZAU, România", "comuna Margaritesti, judetul BUZAU, Romania"),
						createLoc("Mărgăritești", "sat", createAdresaCompleta("sat Mărgăritești, comuna Mărgăritești, judetul Buzau, România", "sat Margaritesti, comuna Margaritesti, judetul Buzau, Romania")),
						createLoc("Câmpulungeanca", "sat", createAdresaCompleta("sat Câmpulungeanca, comuna Mărgăritești, judetul Buzau, România", "sat Campulungeanca, comuna Margaritesti, judetul Buzau, Romania")),
						createLoc("Fântânele", "sat", createAdresaCompleta("sat Fântânele, comuna Mărgăritești, judetul Buzau, România", "sat Fantanele, comuna Margaritesti, judetul Buzau, Romania")),
		]),
	createComuna("Merei", [
						createAdresaCompleta("comuna Merei, judetul BUZAU, România", "comuna Merei, judetul BUZAU, Romania"),
						createLoc("Merei", "sat", createAdresaCompleta("sat Merei, comuna Merei, judetul Buzau, România", "sat Merei, comuna Merei, judetul Buzau, Romania")),
						createLoc("Ciobănoaia", "sat", createAdresaCompleta("sat Ciobănoaia, comuna Merei, judetul Buzau, România", "sat Ciobanoaia, comuna Merei, judetul Buzau, Romania")),
						createLoc("Dealul Viei", "sat", createAdresaCompleta("sat Dealul Viei, comuna Merei, judetul Buzau, România", "sat Dealul Viei, comuna Merei, judetul Buzau, Romania")),
						createLoc("Dobrilești", "sat", createAdresaCompleta("sat Dobrilești, comuna Merei, judetul Buzau, România", "sat Dobrilesti, comuna Merei, judetul Buzau, Romania")),
						createLoc("Gura Sărății", "sat", createAdresaCompleta("sat Gura Sărății, comuna Merei, judetul Buzau, România", "sat Gura Saratii, comuna Merei, judetul Buzau, Romania")),
						createLoc("Izvoru Dulce", "sat", createAdresaCompleta("sat Izvoru Dulce, comuna Merei, judetul Buzau, România", "sat Izvoru Dulce, comuna Merei, judetul Buzau, Romania")),
						createLoc("Lipia", "sat", createAdresaCompleta("sat Lipia, comuna Merei, judetul Buzau, România", "sat Lipia, comuna Merei, judetul Buzau, Romania")),
						createLoc("Nenciulești", "sat", createAdresaCompleta("sat Nenciulești, comuna Merei, judetul Buzau, România", "sat Nenciulesti, comuna Merei, judetul Buzau, Romania")),
						createLoc("Ogrăzile", "sat", createAdresaCompleta("sat Ogrăzile, comuna Merei, judetul Buzau, România", "sat Ograzile, comuna Merei, judetul Buzau, Romania")),
						createLoc("Sărata-Monteoru", "sat", createAdresaCompleta("sat Sărata-Monteoru, comuna Merei, judetul Buzau, România", "sat Sarata-Monteoru, comuna Merei, judetul Buzau, Romania")),
						createLoc("Valea Puțului Merei", "sat", createAdresaCompleta("sat Valea Puțului Merei, comuna Merei, judetul Buzau, România", "sat Valea Putului Merei, comuna Merei, judetul Buzau, Romania")),
		]),
	createComuna("Mihăilești", [
						createAdresaCompleta("comuna Mihăilești, judetul BUZAU, România", "comuna Mihailesti, judetul BUZAU, Romania"),
						createLoc("Mihăilești", "sat", createAdresaCompleta("sat Mihăilești, comuna Mihăilești, judetul Buzau, România", "sat Mihailesti, comuna Mihailesti, judetul Buzau, Romania")),
						createLoc("Colțăneni", "sat", createAdresaCompleta("sat Colțăneni, comuna Mihăilești, judetul Buzau, România", "sat Coltaneni, comuna Mihailesti, judetul Buzau, Romania")),
						createLoc("Mărgineanu", "sat", createAdresaCompleta("sat Mărgineanu, comuna Mihăilești, judetul Buzau, România", "sat Margineanu, comuna Mihailesti, judetul Buzau, Romania")),
						createLoc("Satu Nou", "sat", createAdresaCompleta("sat Satu Nou, comuna Mihăilești, judetul Buzau, România", "sat Satu Nou, comuna Mihailesti, judetul Buzau, Romania")),
		]),
	createComuna("Mânzălești", [
						createAdresaCompleta("comuna Mânzălești, judetul BUZAU, România", "comuna Manzalesti, judetul BUZAU, Romania"),
						createLoc("Mânzălești", "sat", createAdresaCompleta("sat Mânzălești, comuna Mânzălești, judetul Buzau, România", "sat Manzalesti, comuna Manzalesti, judetul Buzau, Romania")),
						createLoc("Beșlii", "sat", createAdresaCompleta("sat Beșlii, comuna Mânzălești, judetul Buzau, România", "sat Beslii, comuna Manzalesti, judetul Buzau, Romania")),
						createLoc("Buștea", "sat", createAdresaCompleta("sat Buștea, comuna Mânzălești, judetul Buzau, România", "sat Bustea, comuna Manzalesti, judetul Buzau, Romania")),
						createLoc("Cireșu", "sat", createAdresaCompleta("sat Cireșu, comuna Mânzălești, judetul Buzau, România", "sat Ciresu, comuna Manzalesti, judetul Buzau, Romania")),
						createLoc("Ghizdita", "sat", createAdresaCompleta("sat Ghizdita, comuna Mânzălești, judetul Buzau, România", "sat Ghizdita, comuna Manzalesti, judetul Buzau, Romania")),
						createLoc("Gura Bădicului", "sat", createAdresaCompleta("sat Gura Bădicului, comuna Mânzălești, judetul Buzau, România", "sat Gura Badicului, comuna Manzalesti, judetul Buzau, Romania")),
						createLoc("Jghiab", "sat", createAdresaCompleta("sat Jghiab, comuna Mânzălești, judetul Buzau, România", "sat Jghiab, comuna Manzalesti, judetul Buzau, Romania")),
						createLoc("Plavățu", "sat", createAdresaCompleta("sat Plavățu, comuna Mânzălești, judetul Buzau, România", "sat Plavatu, comuna Manzalesti, judetul Buzau, Romania")),
						createLoc("Poiana Vâlcului", "sat", createAdresaCompleta("sat Poiana Vâlcului, comuna Mânzălești, judetul Buzau, România", "sat Poiana Valcului, comuna Manzalesti, judetul Buzau, Romania")),
						createLoc("Satu Vechi", "sat", createAdresaCompleta("sat Satu Vechi, comuna Mânzălești, judetul Buzau, România", "sat Satu Vechi, comuna Manzalesti, judetul Buzau, Romania")),
						createLoc("Trestioora", "sat", createAdresaCompleta("sat Trestioora, comuna Mânzălești, judetul Buzau, România", "sat Trestioora, comuna Manzalesti, judetul Buzau, Romania")),
						createLoc("Valea Cotoarei", "sat", createAdresaCompleta("sat Valea Cotoarei, comuna Mânzălești, judetul Buzau, România", "sat Valea Cotoarei, comuna Manzalesti, judetul Buzau, Romania")),
						createLoc("Valea Ursului", "sat", createAdresaCompleta("sat Valea Ursului, comuna Mânzălești, judetul Buzau, România", "sat Valea Ursului, comuna Manzalesti, judetul Buzau, Romania")),
		]),
	createComuna("Movila Banului", [
						createAdresaCompleta("comuna Movila Banului, judetul BUZAU, România", "comuna Movila Banului, judetul BUZAU, Romania"),
						createLoc("Movila Banului", "sat", createAdresaCompleta("sat Movila Banului, comuna Movila Banului, judetul Buzau, România", "sat Movila Banului, comuna Movila Banului, judetul Buzau, Romania")),
						createLoc("Cioranca", "sat", createAdresaCompleta("sat Cioranca, comuna Movila Banului, judetul Buzau, România", "sat Cioranca, comuna Movila Banului, judetul Buzau, Romania")),
						createLoc("Limpeziș", "sat", createAdresaCompleta("sat Limpeziș, comuna Movila Banului, judetul Buzau, România", "sat Limpezis, comuna Movila Banului, judetul Buzau, Romania")),
		]),
	createComuna("Murgești", [
						createAdresaCompleta("comuna Murgești, judetul BUZAU, România", "comuna Murgesti, judetul BUZAU, Romania"),
						createLoc("Murgești", "sat", createAdresaCompleta("sat Murgești, comuna Murgești, judetul Buzau, România", "sat Murgesti, comuna Murgesti, judetul Buzau, Romania")),
						createLoc("Batogu", "sat", createAdresaCompleta("sat Batogu, comuna Murgești, judetul Buzau, România", "sat Batogu, comuna Murgesti, judetul Buzau, Romania")),
						createLoc("Valea Ratei", "sat", createAdresaCompleta("sat Valea Ratei, comuna Murgești, judetul Buzau, România", "sat Valea Ratei, comuna Murgesti, judetul Buzau, Romania")),
		]),
	createComuna("Năeni", [
						createAdresaCompleta("comuna Năeni, judetul BUZAU, România", "comuna Naeni, judetul BUZAU, Romania"),
						createLoc("Năeni", "sat", createAdresaCompleta("sat Năeni, comuna Năeni, judetul Buzau, România", "sat Naeni, comuna Naeni, judetul Buzau, Romania")),
						createLoc("Fințești", "sat", createAdresaCompleta("sat Fințești, comuna Năeni, judetul Buzau, România", "sat Fintesti, comuna Naeni, judetul Buzau, Romania")),
						createLoc("Fântânele", "sat", createAdresaCompleta("sat Fântânele, comuna Năeni, judetul Buzau, România", "sat Fantanele, comuna Naeni, judetul Buzau, Romania")),
						createLoc("Proșca", "sat", createAdresaCompleta("sat Proșca, comuna Năeni, judetul Buzau, România", "sat Prosca, comuna Naeni, judetul Buzau, Romania")),
						createLoc("Vârf", "sat", createAdresaCompleta("sat Vârf, comuna Năeni, judetul Buzau, România", "sat Varf, comuna Naeni, judetul Buzau, Romania")),
		]),
	createComuna("Odăile", [
						createAdresaCompleta("comuna Odăile, judetul BUZAU, România", "comuna Odaile, judetul BUZAU, Romania"),
						createLoc("Odăile", "sat", createAdresaCompleta("sat Odăile, comuna Odăile, judetul Buzau, România", "sat Odaile, comuna Odaile, judetul Buzau, Romania")),
						createLoc("Capu Satului", "sat", createAdresaCompleta("sat Capu Satului, comuna Odăile, judetul Buzau, România", "sat Capu Satului, comuna Odaile, judetul Buzau, Romania")),
						createLoc("Corneanu", "sat", createAdresaCompleta("sat Corneanu, comuna Odăile, judetul Buzau, România", "sat Corneanu, comuna Odaile, judetul Buzau, Romania")),
						createLoc("Gorâni", "sat", createAdresaCompleta("sat Gorâni, comuna Odăile, judetul Buzau, România", "sat Gorani, comuna Odaile, judetul Buzau, Romania")),
						createLoc("Lacu", "sat", createAdresaCompleta("sat Lacu, comuna Odăile, judetul Buzau, România", "sat Lacu, comuna Odaile, judetul Buzau, Romania")),
						createLoc("Piatra Albă", "sat", createAdresaCompleta("sat Piatra Albă, comuna Odăile, judetul Buzau, România", "sat Piatra Alba, comuna Odaile, judetul Buzau, Romania")),
						createLoc("Posobești", "sat", createAdresaCompleta("sat Posobești, comuna Odăile, judetul Buzau, România", "sat Posobesti, comuna Odaile, judetul Buzau, Romania")),
						createLoc("Scoroșești", "sat", createAdresaCompleta("sat Scoroșești, comuna Odăile, judetul Buzau, România", "sat Scorosesti, comuna Odaile, judetul Buzau, Romania")),
						createLoc("Valea Fântânei", "sat", createAdresaCompleta("sat Valea Fântânei, comuna Odăile, judetul Buzau, România", "sat Valea Fantanei, comuna Odaile, judetul Buzau, Romania")),
						createLoc("Valea Ștefanului", "sat", createAdresaCompleta("sat Valea Ștefanului, comuna Odăile, judetul Buzau, România", "sat Valea Stefanului, comuna Odaile, judetul Buzau, Romania")),
		]),
	createComuna("Padina", [
						createAdresaCompleta("comuna Padina, judetul BUZAU, România", "comuna Padina, judetul BUZAU, Romania"),
						createLoc("Padina", "sat", createAdresaCompleta("sat Padina, comuna Padina, judetul Buzau, România", "sat Padina, comuna Padina, judetul Buzau, Romania")),
						createLoc("Tătulești", "sat", createAdresaCompleta("sat Tătulești, comuna Padina, judetul Buzau, România", "sat Tatulesti, comuna Padina, judetul Buzau, Romania")),
		]),
	createComuna("Pardoși", [
						createAdresaCompleta("comuna Pardoși, judetul BUZAU, România", "comuna Pardosi, judetul BUZAU, Romania"),
						createLoc("Pardoși", "sat", createAdresaCompleta("sat Pardoși, comuna Pardoși, judetul Buzau, România", "sat Pardosi, comuna Pardosi, judetul Buzau, Romania")),
						createLoc("Chiperu", "sat", createAdresaCompleta("sat Chiperu, comuna Pardoși, judetul Buzau, România", "sat Chiperu, comuna Pardosi, judetul Buzau, Romania")),
						createLoc("Costomiru", "sat", createAdresaCompleta("sat Costomiru, comuna Pardoși, judetul Buzau, România", "sat Costomiru, comuna Pardosi, judetul Buzau, Romania")),
						createLoc("Valea lui Lalu", "sat", createAdresaCompleta("sat Valea lui Lalu, comuna Pardoși, judetul Buzau, România", "sat Valea lui Lalu, comuna Pardosi, judetul Buzau, Romania")),
						createLoc("Valea Șchiopului", "sat", createAdresaCompleta("sat Valea Șchiopului, comuna Pardoși, judetul Buzau, România", "sat Valea Schiopului, comuna Pardosi, judetul Buzau, Romania")),
		]),
	createComuna("Pănătău", [
						createAdresaCompleta("comuna Pănătău, judetul BUZAU, România", "comuna Panatau, judetul BUZAU, Romania"),
						createLoc("Pănătău", "sat", createAdresaCompleta("sat Pănătău, comuna Pănătău, judetul Buzau, România", "sat Panatau, comuna Panatau, judetul Buzau, Romania")),
						createLoc("Begu", "sat", createAdresaCompleta("sat Begu, comuna Pănătău, judetul Buzau, România", "sat Begu, comuna Panatau, judetul Buzau, Romania")),
						createLoc("Lacu cu Anini", "sat", createAdresaCompleta("sat Lacu cu Anini, comuna Pănătău, judetul Buzau, România", "sat Lacu cu Anini, comuna Panatau, judetul Buzau, Romania")),
						createLoc("Măguricea", "sat", createAdresaCompleta("sat Măguricea, comuna Pănătău, judetul Buzau, România", "sat Maguricea, comuna Panatau, judetul Buzau, Romania")),
						createLoc("Plăișor", "sat", createAdresaCompleta("sat Plăișor, comuna Pănătău, judetul Buzau, România", "sat Plaisor, comuna Panatau, judetul Buzau, Romania")),
						createLoc("Râpile", "sat", createAdresaCompleta("sat Râpile, comuna Pănătău, judetul Buzau, România", "sat Rapile, comuna Panatau, judetul Buzau, Romania")),
						createLoc("Sibiciu de Jos", "sat", createAdresaCompleta("sat Sibiciu de Jos, comuna Pănătău, judetul Buzau, România", "sat Sibiciu de Jos, comuna Panatau, judetul Buzau, Romania")),
						createLoc("Tega", "sat", createAdresaCompleta("sat Tega, comuna Pănătău, judetul Buzau, România", "sat Tega, comuna Panatau, judetul Buzau, Romania")),
						createLoc("Zaharești", "sat", createAdresaCompleta("sat Zaharești, comuna Pănătău, judetul Buzau, România", "sat Zaharesti, comuna Panatau, judetul Buzau, Romania")),
		]),
	createComuna("Pietroasele", [
						createAdresaCompleta("comuna Pietroasele, judetul BUZAU, România", "comuna Pietroasele, judetul BUZAU, Romania"),
						createLoc("Pietroasele", "sat", createAdresaCompleta("sat Pietroasele, comuna Pietroasele, judetul Buzau, România", "sat Pietroasele, comuna Pietroasele, judetul Buzau, Romania")),
						createLoc("Câlțești", "sat", createAdresaCompleta("sat Câlțești, comuna Pietroasele, judetul Buzau, România", "sat Caltesti, comuna Pietroasele, judetul Buzau, Romania")),
						createLoc("Clondiru de Sus", "sat", createAdresaCompleta("sat Clondiru de Sus, comuna Pietroasele, judetul Buzau, România", "sat Clondiru de Sus, comuna Pietroasele, judetul Buzau, Romania")),
						createLoc("Dara", "sat", createAdresaCompleta("sat Dara, comuna Pietroasele, judetul Buzau, România", "sat Dara, comuna Pietroasele, judetul Buzau, Romania")),
						createLoc("Pietroasa Mică", "sat", createAdresaCompleta("sat Pietroasa Mică, comuna Pietroasele, judetul Buzau, România", "sat Pietroasa Mica, comuna Pietroasele, judetul Buzau, Romania")),
						createLoc("Șarânga", "sat", createAdresaCompleta("sat Șarânga, comuna Pietroasele, judetul Buzau, România", "sat Saranga, comuna Pietroasele, judetul Buzau, Romania")),
		]),
	createComuna("Pârscov", [
						createAdresaCompleta("comuna Pârscov, judetul BUZAU, România", "comuna Parscov, judetul BUZAU, Romania"),
						createLoc("Pârscov", "sat", createAdresaCompleta("sat Pârscov, comuna Pârscov, judetul Buzau, România", "sat Parscov, comuna Parscov, judetul Buzau, Romania")),
						createLoc("Bădila", "sat", createAdresaCompleta("sat Bădila, comuna Pârscov, judetul Buzau, România", "sat Badila, comuna Parscov, judetul Buzau, Romania")),
						createLoc("Curcănești", "sat", createAdresaCompleta("sat Curcănești, comuna Pârscov, judetul Buzau, România", "sat Curcanesti, comuna Parscov, judetul Buzau, Romania")),
						createLoc("Lunca Frumoasă", "sat", createAdresaCompleta("sat Lunca Frumoasă, comuna Pârscov, judetul Buzau, România", "sat Lunca Frumoasa, comuna Parscov, judetul Buzau, Romania")),
						createLoc("Oleșești", "sat", createAdresaCompleta("sat Oleșești, comuna Pârscov, judetul Buzau, România", "sat Olesesti, comuna Parscov, judetul Buzau, Romania")),
						createLoc("Pârjolești", "sat", createAdresaCompleta("sat Pârjolești, comuna Pârscov, judetul Buzau, România", "sat Parjolesti, comuna Parscov, judetul Buzau, Romania")),
						createLoc("Robești", "sat", createAdresaCompleta("sat Robești, comuna Pârscov, judetul Buzau, România", "sat Robesti, comuna Parscov, judetul Buzau, Romania")),
						createLoc("Runcu", "sat", createAdresaCompleta("sat Runcu, comuna Pârscov, judetul Buzau, România", "sat Runcu, comuna Parscov, judetul Buzau, Romania")),
						createLoc("Târcov", "sat", createAdresaCompleta("sat Târcov, comuna Pârscov, judetul Buzau, România", "sat Tarcov, comuna Parscov, judetul Buzau, Romania")),
						createLoc("Tocileni", "sat", createAdresaCompleta("sat Tocileni, comuna Pârscov, judetul Buzau, România", "sat Tocileni, comuna Parscov, judetul Buzau, Romania")),
						createLoc("Trestieni", "sat", createAdresaCompleta("sat Trestieni, comuna Pârscov, judetul Buzau, România", "sat Trestieni, comuna Parscov, judetul Buzau, Romania")),
						createLoc("Valea Purcarului", "sat", createAdresaCompleta("sat Valea Purcarului, comuna Pârscov, judetul Buzau, România", "sat Valea Purcarului, comuna Parscov, judetul Buzau, Romania")),
		]),
	createComuna("Podgoria", [
						createAdresaCompleta("comuna Podgoria, judetul BUZAU, România", "comuna Podgoria, judetul BUZAU, Romania"),
						createLoc("Podgoria", "sat", createAdresaCompleta("sat Podgoria, comuna Podgoria, judetul Buzau, România", "sat Podgoria, comuna Podgoria, judetul Buzau, Romania")),
						createLoc("Coțatcu", "sat", createAdresaCompleta("sat Coțatcu, comuna Podgoria, judetul Buzau, România", "sat Cotatcu, comuna Podgoria, judetul Buzau, Romania")),
						createLoc("Oratia", "sat", createAdresaCompleta("sat Oratia, comuna Podgoria, judetul Buzau, România", "sat Oratia, comuna Podgoria, judetul Buzau, Romania")),
						createLoc("Pleșești", "sat", createAdresaCompleta("sat Pleșești, comuna Podgoria, judetul Buzau, România", "sat Plesesti, comuna Podgoria, judetul Buzau, Romania")),
						createLoc("Tăbăcari", "sat", createAdresaCompleta("sat Tăbăcari, comuna Podgoria, judetul Buzau, România", "sat Tabacari, comuna Podgoria, judetul Buzau, Romania")),
		]),
	createComuna("Poșta Câlnău", [
						createAdresaCompleta("comuna Poșta Câlnău, judetul BUZAU, România", "comuna Posta Calnau, judetul BUZAU, Romania"),
						createLoc("Poșta Câlnău", "sat", createAdresaCompleta("sat Poșta Câlnău, comuna Poșta Câlnău, judetul Buzau, România", "sat Posta Calnau, comuna Posta Calnau, judetul Buzau, Romania")),
						createLoc("Aliceni", "sat", createAdresaCompleta("sat Aliceni, comuna Poșta Câlnău, judetul Buzau, România", "sat Aliceni, comuna Posta Calnau, judetul Buzau, Romania")),
						createLoc("Coconari", "sat", createAdresaCompleta("sat Coconari, comuna Poșta Câlnău, judetul Buzau, România", "sat Coconari, comuna Posta Calnau, judetul Buzau, Romania")),
						createLoc("Potârnichești", "sat", createAdresaCompleta("sat Potârnichești, comuna Poșta Câlnău, judetul Buzau, România", "sat Potarnichesti, comuna Posta Calnau, judetul Buzau, Romania")),
						createLoc("Sudiți", "sat", createAdresaCompleta("sat Sudiți, comuna Poșta Câlnău, judetul Buzau, România", "sat Suditi, comuna Posta Calnau, judetul Buzau, Romania")),
						createLoc("Zilișteanca", "sat", createAdresaCompleta("sat Zilișteanca, comuna Poșta Câlnău, judetul Buzau, România", "sat Zilisteanca, comuna Posta Calnau, judetul Buzau, Romania")),
		]),
	createComuna("Puiești", [
						createAdresaCompleta("comuna Puiești, judetul BUZAU, România", "comuna Puiesti, judetul BUZAU, Romania"),
						createLoc("Puieștii de Jos", "sat", createAdresaCompleta("sat Puieștii de Jos, comuna Puiești, judetul Buzau, România", "sat Puiestii de Jos, comuna Puiesti, judetul Buzau, Romania")),
						createLoc("Dăscălești", "sat", createAdresaCompleta("sat Dăscălești, comuna Puiești, judetul Buzau, România", "sat Dascalesti, comuna Puiesti, judetul Buzau, Romania")),
						createLoc("Lunca", "sat", createAdresaCompleta("sat Lunca, comuna Puiești, judetul Buzau, România", "sat Lunca, comuna Puiesti, judetul Buzau, Romania")),
						createLoc("Măcrina", "sat", createAdresaCompleta("sat Măcrina, comuna Puiești, judetul Buzau, România", "sat Macrina, comuna Puiesti, judetul Buzau, Romania")),
						createLoc("Nicolești", "sat", createAdresaCompleta("sat Nicolești, comuna Puiești, judetul Buzau, România", "sat Nicolesti, comuna Puiesti, judetul Buzau, Romania")),
						createLoc("Plopi", "sat", createAdresaCompleta("sat Plopi, comuna Puiești, judetul Buzau, România", "sat Plopi, comuna Puiesti, judetul Buzau, Romania")),
						createLoc("Puieștii de Sus", "sat", createAdresaCompleta("sat Puieștii de Sus, comuna Puiești, judetul Buzau, România", "sat Puiestii de Sus, comuna Puiesti, judetul Buzau, Romania")),
		]),
	createComuna("Racovițeni", [
						createAdresaCompleta("comuna Racovițeni, judetul BUZAU, România", "comuna Racoviteni, judetul BUZAU, Romania"),
						createLoc("Racovițeni", "sat", createAdresaCompleta("sat Racovițeni, comuna Racovițeni, judetul Buzau, România", "sat Racoviteni, comuna Racoviteni, judetul Buzau, Romania")),
						createLoc("Budrea", "sat", createAdresaCompleta("sat Budrea, comuna Racovițeni, judetul Buzau, România", "sat Budrea, comuna Racoviteni, judetul Buzau, Romania")),
						createLoc("Petrișoru", "sat", createAdresaCompleta("sat Petrișoru, comuna Racovițeni, judetul Buzau, România", "sat Petrisoru, comuna Racoviteni, judetul Buzau, Romania")),
		]),
	createComuna("Râmnicelu", [
						createAdresaCompleta("comuna Râmnicelu, judetul BUZAU, România", "comuna Ramnicelu, judetul BUZAU, Romania"),
						createLoc("Râmnicelu", "sat", createAdresaCompleta("sat Râmnicelu, comuna Râmnicelu, judetul Buzau, România", "sat Ramnicelu, comuna Ramnicelu, judetul Buzau, Romania")),
						createLoc("Colibași", "sat", createAdresaCompleta("sat Colibași, comuna Râmnicelu, judetul Buzau, România", "sat Colibasi, comuna Ramnicelu, judetul Buzau, Romania")),
						createLoc("Fotin", "sat", createAdresaCompleta("sat Fotin, comuna Râmnicelu, judetul Buzau, România", "sat Fotin, comuna Ramnicelu, judetul Buzau, Romania")),
						createLoc("Știubei", "sat", createAdresaCompleta("sat Știubei, comuna Râmnicelu, judetul Buzau, România", "sat Stiubei, comuna Ramnicelu, judetul Buzau, Romania")),
		]),
	createComuna("Robeasca", [
						createAdresaCompleta("comuna Robeasca, judetul BUZAU, România", "comuna Robeasca, judetul BUZAU, Romania"),
						createLoc("Robeasca", "sat", createAdresaCompleta("sat Robeasca, comuna Robeasca, judetul Buzau, România", "sat Robeasca, comuna Robeasca, judetul Buzau, Romania")),
						createLoc("Moșești", "sat", createAdresaCompleta("sat Moșești, comuna Robeasca, judetul Buzau, România", "sat Mosesti, comuna Robeasca, judetul Buzau, Romania")),
		]),
	createComuna("Rușețu", [
						createAdresaCompleta("comuna Rușețu, judetul BUZAU, România", "comuna Rusetu, judetul BUZAU, Romania"),
						createLoc("Rușețu", "sat", createAdresaCompleta("sat Rușețu, comuna Rușețu, judetul Buzau, România", "sat Rusetu, comuna Rusetu, judetul Buzau, Romania")),
						createLoc("Sergent Ionel Ștefan", "sat", createAdresaCompleta("sat Sergent Ionel Ștefan, comuna Rușețu, judetul Buzau, România", "sat Sergent Ionel Stefan, comuna Rusetu, judetul Buzau, Romania")),
		]),
	createComuna("Săgeata", [
						createAdresaCompleta("comuna Săgeata, judetul BUZAU, România", "comuna Sageata, judetul BUZAU, Romania"),
						createLoc("Săgeata", "sat", createAdresaCompleta("sat Săgeata, comuna Săgeata, judetul Buzau, România", "sat Sageata, comuna Sageata, judetul Buzau, Romania")),
						createLoc("Banița", "sat", createAdresaCompleta("sat Banița, comuna Săgeata, judetul Buzau, România", "sat Banita, comuna Sageata, judetul Buzau, Romania")),
						createLoc("Beilic", "sat", createAdresaCompleta("sat Beilic, comuna Săgeata, judetul Buzau, România", "sat Beilic, comuna Sageata, judetul Buzau, Romania")),
						createLoc("Bordușani", "sat", createAdresaCompleta("sat Bordușani, comuna Săgeata, judetul Buzau, România", "sat Bordusani, comuna Sageata, judetul Buzau, Romania")),
						createLoc("Dâmbroca", "sat", createAdresaCompleta("sat Dâmbroca, comuna Săgeata, judetul Buzau, România", "sat Dambroca, comuna Sageata, judetul Buzau, Romania")),
						createLoc("Găvănești", "sat", createAdresaCompleta("sat Găvănești, comuna Săgeata, judetul Buzau, România", "sat Gavanesti, comuna Sageata, judetul Buzau, Romania")),
						createLoc("Movilița", "sat", createAdresaCompleta("sat Movilița, comuna Săgeata, judetul Buzau, România", "sat Movilita, comuna Sageata, judetul Buzau, Romania")),
		]),
	createComuna("Săhăteni", [
						createAdresaCompleta("comuna Săhăteni, judetul BUZAU, România", "comuna Sahateni, judetul BUZAU, Romania"),
						createLoc("Săhăteni", "sat", createAdresaCompleta("sat Săhăteni, comuna Săhăteni, judetul Buzau, România", "sat Sahateni, comuna Sahateni, judetul Buzau, Romania")),
						createLoc("Găgeni", "sat", createAdresaCompleta("sat Găgeni, comuna Săhăteni, judetul Buzau, România", "sat Gageni, comuna Sahateni, judetul Buzau, Romania")),
						createLoc("Istrița de Jos", "sat", createAdresaCompleta("sat Istrița de Jos, comuna Săhăteni, judetul Buzau, România", "sat Istrita de Jos, comuna Sahateni, judetul Buzau, Romania")),
						createLoc("Vintileanca", "sat", createAdresaCompleta("sat Vintileanca, comuna Săhăteni, judetul Buzau, România", "sat Vintileanca, comuna Sahateni, judetul Buzau, Romania")),
		]),
	createComuna("Săpoca", [
						createAdresaCompleta("comuna Săpoca, judetul BUZAU, România", "comuna Sapoca, judetul BUZAU, Romania"),
						createLoc("Săpoca", "sat", createAdresaCompleta("sat Săpoca, comuna Săpoca, judetul Buzau, România", "sat Sapoca, comuna Sapoca, judetul Buzau, Romania")),
						createLoc("Mătești", "sat", createAdresaCompleta("sat Mătești, comuna Săpoca, judetul Buzau, România", "sat Matesti, comuna Sapoca, judetul Buzau, Romania")),
		]),
	createComuna("Sărulești", [
						createAdresaCompleta("comuna Sărulești, judetul BUZAU, România", "comuna Sarulesti, judetul BUZAU, Romania"),
						createLoc("Sărulești", "sat", createAdresaCompleta("sat Sărulești, comuna Sărulești, judetul Buzau, România", "sat Sarulesti, comuna Sarulesti, judetul Buzau, Romania")),
						createLoc("Cărătnău de Jos", "sat", createAdresaCompleta("sat Cărătnău de Jos, comuna Sărulești, judetul Buzau, România", "sat Caratnau de Jos, comuna Sarulesti, judetul Buzau, Romania")),
						createLoc("Cărătnău de Sus", "sat", createAdresaCompleta("sat Cărătnău de Sus, comuna Sărulești, judetul Buzau, România", "sat Caratnau de Sus, comuna Sarulesti, judetul Buzau, Romania")),
						createLoc("Goicelu", "sat", createAdresaCompleta("sat Goicelu, comuna Sărulești, judetul Buzau, România", "sat Goicelu, comuna Sarulesti, judetul Buzau, Romania")),
						createLoc("Sările-Cătun", "sat", createAdresaCompleta("sat Sările-Cătun, comuna Sărulești, judetul Buzau, România", "sat Sarile-Catun, comuna Sarulesti, judetul Buzau, Romania")),
						createLoc("Valea Largă-Sărulești", "sat", createAdresaCompleta("sat Valea Largă-Sărulești, comuna Sărulești, judetul Buzau, România", "sat Valea Larga-Sarulesti, comuna Sarulesti, judetul Buzau, Romania")),
						createLoc("Valea Stânei", "sat", createAdresaCompleta("sat Valea Stânei, comuna Sărulești, judetul Buzau, România", "sat Valea Stanei, comuna Sarulesti, judetul Buzau, Romania")),
		]),
	createComuna("Scorțoasa", [
						createAdresaCompleta("comuna Scorțoasa, judetul BUZAU, România", "comuna Scortoasa, judetul BUZAU, Romania"),
						createLoc("Scorțoasa", "sat", createAdresaCompleta("sat Scorțoasa, comuna Scorțoasa, judetul Buzau, România", "sat Scortoasa, comuna Scortoasa, judetul Buzau, Romania")),
						createLoc("Balta Tocila", "sat", createAdresaCompleta("sat Balta Tocila, comuna Scorțoasa, judetul Buzau, România", "sat Balta Tocila, comuna Scortoasa, judetul Buzau, Romania")),
						createLoc("Beciu", "sat", createAdresaCompleta("sat Beciu, comuna Scorțoasa, judetul Buzau, România", "sat Beciu, comuna Scortoasa, judetul Buzau, Romania")),
						createLoc("Deleni", "sat", createAdresaCompleta("sat Deleni, comuna Scorțoasa, judetul Buzau, România", "sat Deleni, comuna Scortoasa, judetul Buzau, Romania")),
						createLoc("Dâlma", "sat", createAdresaCompleta("sat Dâlma, comuna Scorțoasa, judetul Buzau, România", "sat Dalma, comuna Scortoasa, judetul Buzau, Romania")),
						createLoc("Golu Grabicina", "sat", createAdresaCompleta("sat Golu Grabicina, comuna Scorțoasa, judetul Buzau, România", "sat Golu Grabicina, comuna Scortoasa, judetul Buzau, Romania")),
						createLoc("Grabicina de Jos", "sat", createAdresaCompleta("sat Grabicina de Jos, comuna Scorțoasa, judetul Buzau, România", "sat Grabicina de Jos, comuna Scortoasa, judetul Buzau, Romania")),
						createLoc("Grabicina de Sus", "sat", createAdresaCompleta("sat Grabicina de Sus, comuna Scorțoasa, judetul Buzau, România", "sat Grabicina de Sus, comuna Scortoasa, judetul Buzau, Romania")),
						createLoc("Gura Văii", "sat", createAdresaCompleta("sat Gura Văii, comuna Scorțoasa, judetul Buzau, România", "sat Gura Vaii, comuna Scortoasa, judetul Buzau, Romania")),
						createLoc("Plopeasa", "sat", createAdresaCompleta("sat Plopeasa, comuna Scorțoasa, judetul Buzau, România", "sat Plopeasa, comuna Scortoasa, judetul Buzau, Romania")),
						createLoc("Policiori", "sat", createAdresaCompleta("sat Policiori, comuna Scorțoasa, judetul Buzau, România", "sat Policiori, comuna Scortoasa, judetul Buzau, Romania")),
		]),
	createComuna("Scutelnici", [
						createAdresaCompleta("comuna Scutelnici, judetul BUZAU, România", "comuna Scutelnici, judetul BUZAU, Romania"),
						createLoc("Scutelnici", "sat", createAdresaCompleta("sat Scutelnici, comuna Scutelnici, judetul Buzau, România", "sat Scutelnici, comuna Scutelnici, judetul Buzau, Romania")),
						createLoc("Arcanu", "sat", createAdresaCompleta("sat Arcanu, comuna Scutelnici, judetul Buzau, România", "sat Arcanu, comuna Scutelnici, judetul Buzau, Romania")),
						createLoc("Brăgăreasa", "sat", createAdresaCompleta("sat Brăgăreasa, comuna Scutelnici, judetul Buzau, România", "sat Bragareasa, comuna Scutelnici, judetul Buzau, Romania")),
						createLoc("Lipănescu", "sat", createAdresaCompleta("sat Lipănescu, comuna Scutelnici, judetul Buzau, România", "sat Lipanescu, comuna Scutelnici, judetul Buzau, Romania")),
		]),
	createComuna("Siriu", [
						createAdresaCompleta("comuna Siriu, judetul BUZAU, România", "comuna Siriu, judetul BUZAU, Romania"),
						createLoc("Lunca Jariștei", "sat", createAdresaCompleta("sat Lunca Jariștei, comuna Siriu, judetul Buzau, România", "sat Lunca Jaristei, comuna Siriu, judetul Buzau, Romania")),
						createLoc("Colțu Pietrii", "sat", createAdresaCompleta("sat Colțu Pietrii, comuna Siriu, judetul Buzau, România", "sat Coltu Pietrii, comuna Siriu, judetul Buzau, Romania")),
						createLoc("Cașoca", "sat", createAdresaCompleta("sat Cașoca, comuna Siriu, judetul Buzau, România", "sat Casoca, comuna Siriu, judetul Buzau, Romania")),
						createLoc("Gura Siriului", "sat", createAdresaCompleta("sat Gura Siriului, comuna Siriu, judetul Buzau, România", "sat Gura Siriului, comuna Siriu, judetul Buzau, Romania")),
						createLoc("Mușcelușa", "sat", createAdresaCompleta("sat Mușcelușa, comuna Siriu, judetul Buzau, România", "sat Muscelusa, comuna Siriu, judetul Buzau, Romania")),
		]),
	createComuna("Smeeni", [
						createAdresaCompleta("comuna Smeeni, judetul BUZAU, România", "comuna Smeeni, judetul BUZAU, Romania"),
						createLoc("Smeeni", "sat", createAdresaCompleta("sat Smeeni, comuna Smeeni, judetul Buzau, România", "sat Smeeni, comuna Smeeni, judetul Buzau, Romania")),
						createLoc("Albești", "sat", createAdresaCompleta("sat Albești, comuna Smeeni, judetul Buzau, România", "sat Albesti, comuna Smeeni, judetul Buzau, Romania")),
						createLoc("Bălaia", "sat", createAdresaCompleta("sat Bălaia, comuna Smeeni, judetul Buzau, România", "sat Balaia, comuna Smeeni, judetul Buzau, Romania")),
						createLoc("Călțuna", "sat", createAdresaCompleta("sat Călțuna, comuna Smeeni, judetul Buzau, România", "sat Caltuna, comuna Smeeni, judetul Buzau, Romania")),
						createLoc("Moisica", "sat", createAdresaCompleta("sat Moisica, comuna Smeeni, judetul Buzau, România", "sat Moisica, comuna Smeeni, judetul Buzau, Romania")),
						createLoc("Udați-Lucieni", "sat", createAdresaCompleta("sat Udați-Lucieni, comuna Smeeni, judetul Buzau, România", "sat Udati-Lucieni, comuna Smeeni, judetul Buzau, Romania")),
						createLoc("Udați-Mânzu", "sat", createAdresaCompleta("sat Udați-Mânzu, comuna Smeeni, judetul Buzau, România", "sat Udati-Manzu, comuna Smeeni, judetul Buzau, Romania")),
		]),
	createComuna("Stâlpu", [
						createAdresaCompleta("comuna Stâlpu, judetul BUZAU, România", "comuna Stalpu, judetul BUZAU, Romania"),
						createLoc("Stâlpu", "sat", createAdresaCompleta("sat Stâlpu, comuna Stâlpu, judetul Buzau, România", "sat Stalpu, comuna Stalpu, judetul Buzau, Romania")),
		]),
	createComuna("Tisău", [
						createAdresaCompleta("comuna Tisău, judetul BUZAU, România", "comuna Tisau, judetul BUZAU, Romania"),
						createLoc("Izvoru", "sat", createAdresaCompleta("sat Izvoru, comuna Tisău, judetul Buzau, România", "sat Izvoru, comuna Tisau, judetul Buzau, Romania")),
						createLoc("Bărbuncești", "sat", createAdresaCompleta("sat Bărbuncești, comuna Tisău, judetul Buzau, România", "sat Barbuncesti, comuna Tisau, judetul Buzau, Romania")),
						createLoc("Grăjdana", "sat", createAdresaCompleta("sat Grăjdana, comuna Tisău, judetul Buzau, România", "sat Grajdana, comuna Tisau, judetul Buzau, Romania")),
						createLoc("Haleș", "sat", createAdresaCompleta("sat Haleș, comuna Tisău, judetul Buzau, România", "sat Hales, comuna Tisau, judetul Buzau, Romania")),
						createLoc("Izvoranu", "sat", createAdresaCompleta("sat Izvoranu, comuna Tisău, judetul Buzau, România", "sat Izvoranu, comuna Tisau, judetul Buzau, Romania")),
						createLoc("Leiculești", "sat", createAdresaCompleta("sat Leiculești, comuna Tisău, judetul Buzau, România", "sat Leiculesti, comuna Tisau, judetul Buzau, Romania")),
						createLoc("Pădurenii", "sat", createAdresaCompleta("sat Pădurenii, comuna Tisău, judetul Buzau, România", "sat Padurenii, comuna Tisau, judetul Buzau, Romania")),
						createLoc("Salcia", "sat", createAdresaCompleta("sat Salcia, comuna Tisău, judetul Buzau, România", "sat Salcia, comuna Tisau, judetul Buzau, Romania")),
						createLoc("Strezeni", "sat", createAdresaCompleta("sat Strezeni, comuna Tisău, judetul Buzau, România", "sat Strezeni, comuna Tisau, judetul Buzau, Romania")),
						createLoc("Tisău", "sat", createAdresaCompleta("sat Tisău, comuna Tisău, judetul Buzau, România", "sat Tisau, comuna Tisau, judetul Buzau, Romania")),
						createLoc("Valea Sălciilor", "sat", createAdresaCompleta("sat Valea Sălciilor, comuna Tisău, judetul Buzau, România", "sat Valea Salciilor, comuna Tisau, judetul Buzau, Romania")),
		]),
	createComuna("Topliceni", [
						createAdresaCompleta("comuna Topliceni, judetul BUZAU, România", "comuna Topliceni, judetul BUZAU, Romania"),
						createLoc("Topliceni", "sat", createAdresaCompleta("sat Topliceni, comuna Topliceni, judetul Buzau, România", "sat Topliceni, comuna Topliceni, judetul Buzau, Romania")),
						createLoc("Băbeni", "sat", createAdresaCompleta("sat Băbeni, comuna Topliceni, judetul Buzau, România", "sat Babeni, comuna Topliceni, judetul Buzau, Romania")),
						createLoc("Ceairu", "sat", createAdresaCompleta("sat Ceairu, comuna Topliceni, judetul Buzau, România", "sat Ceairu, comuna Topliceni, judetul Buzau, Romania")),
						createLoc("Dedulești", "sat", createAdresaCompleta("sat Dedulești, comuna Topliceni, judetul Buzau, România", "sat Dedulesti, comuna Topliceni, judetul Buzau, Romania")),
						createLoc("Gura Făgetului", "sat", createAdresaCompleta("sat Gura Făgetului, comuna Topliceni, judetul Buzau, România", "sat Gura Fagetului, comuna Topliceni, judetul Buzau, Romania")),
						createLoc("Poșta", "sat", createAdresaCompleta("sat Poșta, comuna Topliceni, judetul Buzau, România", "sat Posta, comuna Topliceni, judetul Buzau, Romania")),
						createLoc("Răducești", "sat", createAdresaCompleta("sat Răducești, comuna Topliceni, judetul Buzau, România", "sat Raducesti, comuna Topliceni, judetul Buzau, Romania")),
		]),
	createComuna("Țintești", [
						createAdresaCompleta("comuna Țintești, judetul BUZAU, România", "comuna Tintesti, judetul BUZAU, Romania"),
						createLoc("Țintești", "sat", createAdresaCompleta("sat Țintești, comuna Țintești, judetul Buzau, România", "sat Tintesti, comuna Tintesti, judetul Buzau, Romania")),
						createLoc("Maxenu", "sat", createAdresaCompleta("sat Maxenu, comuna Țintești, judetul Buzau, România", "sat Maxenu, comuna Tintesti, judetul Buzau, Romania")),
						createLoc("Odaia Banului", "sat", createAdresaCompleta("sat Odaia Banului, comuna Țintești, judetul Buzau, România", "sat Odaia Banului, comuna Tintesti, judetul Buzau, Romania")),
						createLoc("Pogonele", "sat", createAdresaCompleta("sat Pogonele, comuna Țintești, judetul Buzau, România", "sat Pogonele, comuna Tintesti, judetul Buzau, Romania")),
		]),
	createComuna("Ulmeni", [
						createAdresaCompleta("comuna Ulmeni, judetul BUZAU, România", "comuna Ulmeni, judetul BUZAU, Romania"),
						createLoc("Ulmeni", "sat", createAdresaCompleta("sat Ulmeni, comuna Ulmeni, judetul Buzau, România", "sat Ulmeni, comuna Ulmeni, judetul Buzau, Romania")),
						createLoc("Băltăreți", "sat", createAdresaCompleta("sat Băltăreți, comuna Ulmeni, judetul Buzau, România", "sat Baltareti, comuna Ulmeni, judetul Buzau, Romania")),
						createLoc("Clondiru", "sat", createAdresaCompleta("sat Clondiru, comuna Ulmeni, judetul Buzau, România", "sat Clondiru, comuna Ulmeni, judetul Buzau, Romania")),
						createLoc("Sărata", "sat", createAdresaCompleta("sat Sărata, comuna Ulmeni, judetul Buzau, România", "sat Sarata, comuna Ulmeni, judetul Buzau, Romania")),
						createLoc("Vâlcele", "sat", createAdresaCompleta("sat Vâlcele, comuna Ulmeni, judetul Buzau, România", "sat Valcele, comuna Ulmeni, judetul Buzau, Romania")),
		]),
	createComuna("Unguriu", [
						createAdresaCompleta("comuna Unguriu, judetul BUZAU, România", "comuna Unguriu, judetul BUZAU, Romania"),
						createLoc("Unguriu", "sat", createAdresaCompleta("sat Unguriu, comuna Unguriu, judetul Buzau, România", "sat Unguriu, comuna Unguriu, judetul Buzau, Romania")),
						createLoc("Ojasca", "sat", createAdresaCompleta("sat Ojasca, comuna Unguriu, judetul Buzau, România", "sat Ojasca, comuna Unguriu, judetul Buzau, Romania")),
		]),
	createComuna("Vadu Pașii", [
						createAdresaCompleta("comuna Vadu Pașii, judetul BUZAU, România", "comuna Vadu Pasii, judetul BUZAU, Romania"),
						createLoc("Vadu Pașii", "sat", createAdresaCompleta("sat Vadu Pașii, comuna Vadu Pașii, judetul Buzau, România", "sat Vadu Pasii, comuna Vadu Pasii, judetul Buzau, Romania")),
						createLoc("Băjani", "sat", createAdresaCompleta("sat Băjani, comuna Vadu Pașii, judetul Buzau, România", "sat Bajani, comuna Vadu Pasii, judetul Buzau, Romania")),
						createLoc("Focșănei", "sat", createAdresaCompleta("sat Focșănei, comuna Vadu Pașii, judetul Buzau, România", "sat Focsanei, comuna Vadu Pasii, judetul Buzau, Romania")),
						createLoc("Gura Câlnăului", "sat", createAdresaCompleta("sat Gura Câlnăului, comuna Vadu Pașii, judetul Buzau, România", "sat Gura Calnaului, comuna Vadu Pasii, judetul Buzau, Romania")),
						createLoc("Scurtești", "sat", createAdresaCompleta("sat Scurtești, comuna Vadu Pașii, judetul Buzau, România", "sat Scurtesti, comuna Vadu Pasii, judetul Buzau, Romania")),
						createLoc("Stăncești", "sat", createAdresaCompleta("sat Stăncești, comuna Vadu Pașii, judetul Buzau, România", "sat Stancesti, comuna Vadu Pasii, judetul Buzau, Romania")),
		]),
	createComuna("Valea Râmnicului", [
						createAdresaCompleta("comuna Valea Râmnicului, judetul BUZAU, România", "comuna Valea Ramnicului, judetul BUZAU, Romania"),
						createLoc("Valea Râmnicului", "sat", createAdresaCompleta("sat Valea Râmnicului, comuna Valea Râmnicului, judetul Buzau, România", "sat Valea Ramnicului, comuna Valea Ramnicului, judetul Buzau, Romania")),
						createLoc("Oreavul", "sat", createAdresaCompleta("sat Oreavul, comuna Valea Râmnicului, judetul Buzau, România", "sat Oreavul, comuna Valea Ramnicului, judetul Buzau, Romania")),
						createLoc("Rubla", "sat", createAdresaCompleta("sat Rubla, comuna Valea Râmnicului, judetul Buzau, România", "sat Rubla, comuna Valea Ramnicului, judetul Buzau, Romania")),
		]),
	createComuna("Valea Salciei", [
						createAdresaCompleta("comuna Valea Salciei, judetul BUZAU, România", "comuna Valea Salciei, judetul BUZAU, Romania"),
						createLoc("Valea Salciei", "sat", createAdresaCompleta("sat Valea Salciei, comuna Valea Salciei, judetul Buzau, România", "sat Valea Salciei, comuna Valea Salciei, judetul Buzau, Romania")),
						createLoc("Modreni", "sat", createAdresaCompleta("sat Modreni, comuna Valea Salciei, judetul Buzau, România", "sat Modreni, comuna Valea Salciei, judetul Buzau, Romania")),
						createLoc("Valea Salciei-Cătun", "sat", createAdresaCompleta("sat Valea Salciei-Cătun, comuna Valea Salciei, judetul Buzau, România", "sat Valea Salciei-Catun, comuna Valea Salciei, judetul Buzau, Romania")),
		]),
	createComuna("Vernești", [
						createAdresaCompleta("comuna Vernești, judetul BUZAU, România", "comuna Vernesti, judetul BUZAU, Romania"),
						createLoc("Vernești", "sat", createAdresaCompleta("sat Vernești, comuna Vernești, judetul Buzau, România", "sat Vernesti, comuna Vernesti, judetul Buzau, Romania")),
						createLoc("Brădeanca", "sat", createAdresaCompleta("sat Brădeanca, comuna Vernești, judetul Buzau, România", "sat Bradeanca, comuna Vernesti, judetul Buzau, Romania")),
						createLoc("Cândești", "sat", createAdresaCompleta("sat Cândești, comuna Vernești, judetul Buzau, România", "sat Candesti, comuna Vernesti, judetul Buzau, Romania")),
						createLoc("Cârlomănești", "sat", createAdresaCompleta("sat Cârlomănești, comuna Vernești, judetul Buzau, România", "sat Carlomanesti, comuna Vernesti, judetul Buzau, Romania")),
						createLoc("Mierea", "sat", createAdresaCompleta("sat Mierea, comuna Vernești, judetul Buzau, România", "sat Mierea, comuna Vernesti, judetul Buzau, Romania")),
						createLoc("Nenciu", "sat", createAdresaCompleta("sat Nenciu, comuna Vernești, judetul Buzau, România", "sat Nenciu, comuna Vernesti, judetul Buzau, Romania")),
						createLoc("Nișcov", "sat", createAdresaCompleta("sat Nișcov, comuna Vernești, judetul Buzau, România", "sat Niscov, comuna Vernesti, judetul Buzau, Romania")),
						createLoc("Săsenii Noi", "sat", createAdresaCompleta("sat Săsenii Noi, comuna Vernești, judetul Buzau, România", "sat Sasenii Noi, comuna Vernesti, judetul Buzau, Romania")),
						createLoc("Săsenii pe Vale", "sat", createAdresaCompleta("sat Săsenii pe Vale, comuna Vernești, judetul Buzau, România", "sat Sasenii pe Vale, comuna Vernesti, judetul Buzau, Romania")),
						createLoc("Săsenii Vechi", "sat", createAdresaCompleta("sat Săsenii Vechi, comuna Vernești, judetul Buzau, România", "sat Sasenii Vechi, comuna Vernesti, judetul Buzau, Romania")),
						createLoc("Zorești", "sat", createAdresaCompleta("sat Zorești, comuna Vernești, judetul Buzau, România", "sat Zoresti, comuna Vernesti, judetul Buzau, Romania")),
		]),
	createComuna("Vintilă Vodă", [
						createAdresaCompleta("comuna Vintilă Vodă, judetul BUZAU, România", "comuna Vintila Voda, judetul BUZAU, Romania"),
						createLoc("Vintilă Vodă", "sat", createAdresaCompleta("sat Vintilă Vodă, comuna Vintilă Vodă, judetul Buzau, România", "sat Vintila Voda, comuna Vintila Voda, judetul Buzau, Romania")),
						createLoc("Bodinești", "sat", createAdresaCompleta("sat Bodinești, comuna Vintilă Vodă, judetul Buzau, România", "sat Bodinesti, comuna Vintila Voda, judetul Buzau, Romania")),
						createLoc("Coca-Antimirești", "sat", createAdresaCompleta("sat Coca-Antimirești, comuna Vintilă Vodă, judetul Buzau, România", "sat Coca-Antimiresti, comuna Vintila Voda, judetul Buzau, Romania")),
						createLoc("Coca-Niculești", "sat", createAdresaCompleta("sat Coca-Niculești, comuna Vintilă Vodă, judetul Buzau, România", "sat Coca-Niculesti, comuna Vintila Voda, judetul Buzau, Romania")),
						createLoc("Niculești", "sat", createAdresaCompleta("sat Niculești, comuna Vintilă Vodă, judetul Buzau, România", "sat Niculesti, comuna Vintila Voda, judetul Buzau, Romania")),
						createLoc("Petrăchești", "sat", createAdresaCompleta("sat Petrăchești, comuna Vintilă Vodă, judetul Buzau, România", "sat Petrachesti, comuna Vintila Voda, judetul Buzau, Romania")),
						createLoc("Podu Muncii", "sat", createAdresaCompleta("sat Podu Muncii, comuna Vintilă Vodă, judetul Buzau, România", "sat Podu Muncii, comuna Vintila Voda, judetul Buzau, Romania")),
						createLoc("Sârbești", "sat", createAdresaCompleta("sat Sârbești, comuna Vintilă Vodă, judetul Buzau, România", "sat Sarbesti, comuna Vintila Voda, judetul Buzau, Romania")),
						createLoc("Smeești", "sat", createAdresaCompleta("sat Smeești, comuna Vintilă Vodă, judetul Buzau, România", "sat Smeesti, comuna Vintila Voda, judetul Buzau, Romania")),
		]),
	createComuna("Viperești", [
						createAdresaCompleta("comuna Viperești, judetul BUZAU, România", "comuna Viperesti, judetul BUZAU, Romania"),
						createLoc("Viperești", "sat", createAdresaCompleta("sat Viperești, comuna Viperești, judetul Buzau, România", "sat Viperesti, comuna Viperesti, judetul Buzau, Romania")),
						createLoc("Muscel", "sat", createAdresaCompleta("sat Muscel, comuna Viperești, judetul Buzau, România", "sat Muscel, comuna Viperesti, judetul Buzau, Romania")),
						createLoc("Pălici", "sat", createAdresaCompleta("sat Pălici, comuna Viperești, judetul Buzau, România", "sat Palici, comuna Viperesti, judetul Buzau, Romania")),
						createLoc("Rușavăț", "sat", createAdresaCompleta("sat Rușavăț, comuna Viperești, judetul Buzau, România", "sat Rusavat, comuna Viperesti, judetul Buzau, Romania")),
						createLoc("Tronari", "sat", createAdresaCompleta("sat Tronari, comuna Viperești, judetul Buzau, România", "sat Tronari, comuna Viperesti, judetul Buzau, Romania")),
						createLoc("Ursoaia", "sat", createAdresaCompleta("sat Ursoaia, comuna Viperești, judetul Buzau, România", "sat Ursoaia, comuna Viperesti, judetul Buzau, Romania")),
		]),
	createComuna("Vâlcelele", [
						createAdresaCompleta("comuna Vâlcelele, judetul BUZAU, România", "comuna Valcelele, judetul BUZAU, Romania"),
						createLoc("Vâlcelele", "sat", createAdresaCompleta("sat Vâlcelele, comuna Vâlcelele, judetul Buzau, România", "sat Valcelele, comuna Valcelele, judetul Buzau, Romania")),
		]),
	createComuna("Zărnești", [
						createAdresaCompleta("comuna Zărnești, judetul BUZAU, România", "comuna Zarnesti, judetul BUZAU, Romania"),
						createLoc("Fundeni", "sat", createAdresaCompleta("sat Fundeni, comuna Zărnești, judetul Buzau, România", "sat Fundeni, comuna Zarnesti, judetul Buzau, Romania")),
						createLoc("Comisoaia", "sat", createAdresaCompleta("sat Comisoaia, comuna Zărnești, judetul Buzau, România", "sat Comisoaia, comuna Zarnesti, judetul Buzau, Romania")),
						createLoc("Pruneni", "sat", createAdresaCompleta("sat Pruneni, comuna Zărnești, judetul Buzau, România", "sat Pruneni, comuna Zarnesti, judetul Buzau, Romania")),
						createLoc("Vadu Sorești", "sat", createAdresaCompleta("sat Vadu Sorești, comuna Zărnești, judetul Buzau, România", "sat Vadu Soresti, comuna Zarnesti, judetul Buzau, Romania")),
						createLoc("Zărnești", "sat", createAdresaCompleta("sat Zărnești, comuna Zărnești, judetul Buzau, România", "sat Zarnesti, comuna Zarnesti, judetul Buzau, Romania")),
		]),
	createComuna("Ziduri", [
						createAdresaCompleta("comuna Ziduri, judetul BUZAU, România", "comuna Ziduri, judetul BUZAU, Romania"),
						createLoc("Ziduri", "sat", createAdresaCompleta("sat Ziduri, comuna Ziduri, judetul Buzau, România", "sat Ziduri, comuna Ziduri, judetul Buzau, Romania")),
						createLoc("Costieni", "sat", createAdresaCompleta("sat Costieni, comuna Ziduri, judetul Buzau, România", "sat Costieni, comuna Ziduri, judetul Buzau, Romania")),
						createLoc("Cuculeasa", "sat", createAdresaCompleta("sat Cuculeasa, comuna Ziduri, judetul Buzau, România", "sat Cuculeasa, comuna Ziduri, judetul Buzau, Romania")),
						createLoc("Heliade Rădulescu", "sat", createAdresaCompleta("sat Heliade Rădulescu, comuna Ziduri, judetul Buzau, România", "sat Heliade Radulescu, comuna Ziduri, judetul Buzau, Romania")),
						createLoc("Lanurile", "sat", createAdresaCompleta("sat Lanurile, comuna Ziduri, judetul Buzau, România", "sat Lanurile, comuna Ziduri, judetul Buzau, Romania")),
						createLoc("Zoița", "sat", createAdresaCompleta("sat Zoița, comuna Ziduri, judetul Buzau, România", "sat Zoita, comuna Ziduri, judetul Buzau, Romania")),
		]),
];
?>