<?php
$comune =[
			createComuna("Ardusat", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Ardusat", "sat", createAdresaCompleta("sat Ardusat, comuna Ardusat, judetul Maramureș, România", "sat Ardusat, comuna Ardusat, judetul Maramures, Romania"))),
					createLoc("Arieșu de Câmp", "sat", createAdresaCompleta("sat Arieșu de Câmp, comuna Ardusat, judetul Maramureș, România", "sat Ariesu de Camp, comuna Ardusat, judetul Maramures, Romania"))),
					createLoc("Colțirea", "sat", createAdresaCompleta("sat Colțirea, comuna Ardusat, judetul Maramureș, România", "sat Coltirea, comuna Ardusat, judetul Maramures, Romania"))),
								  ]),
			createComuna("Ariniș", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Ariniș", "sat", createAdresaCompleta("sat Ariniș, comuna Ariniș, judetul Maramureș, România", "sat Arinis, comuna Arinis, judetul Maramures, Romania"))),
					createLoc("Rodina", "sat", createAdresaCompleta("sat Rodina, comuna Ariniș, judetul Maramureș, România", "sat Rodina, comuna Arinis, judetul Maramures, Romania"))),
					createLoc("Tămășești", "sat", createAdresaCompleta("sat Tămășești, comuna Ariniș, judetul Maramureș, România", "sat Tamasesti, comuna Arinis, judetul Maramures, Romania"))),
								  ]),							  
			createComuna("Asuaju de Sus", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Asuaju de Sus", "sat", createAdresaCompleta("sat Asuaju de Sus, comuna Asuaju de Sus, judetul Maramureș, România", "sat Asuaju de Sus, comuna Asuaju de Sus, judetul Maramures, Romania"))),
					createLoc("Asuaju de Jos", "sat", createAdresaCompleta("sat Asuaju de Jos, comuna Asuaju de Sus, judetul Maramureș, România", "sat Asuaju de Jos, comuna Asuaju de Sus, judetul Maramures, Romania"))),
								  ]),
			createComuna("Băița de sub Codru", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Băița de sub Codru", "sat", createAdresaCompleta("sat Băița de sub Codru, comuna Băița de sub Codru, judetul Maramureș, România", "sat Baita de sub Codru, comuna Baita de sub Codru, judetul Maramures, Romania"))),
					createLoc("Urmeniș", "sat", createAdresaCompleta("sat Urmeniș, comuna Băița de sub Codru, judetul Maramureș, România", "sat Urmenis, comuna Baita de sub Codru, judetul Maramures, Romania"))),
								  ]),									  
			createComuna("Băiuț", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Băiuț", "sat", createAdresaCompleta("sat Băiuț, comuna Băiuț, judetul Maramureș, România", "sat Baiut, comuna Baiut, judetul Maramures, Romania"))),
					createLoc("Poiana Botizii", "sat", createAdresaCompleta("sat Poiana Botizii, comuna Băiuț, judetul Maramureș, România", "sat Poiana Botizii, comuna Baiut, judetul Maramures, Romania"))),
					createLoc("Strâmbu-Băiuț", "sat", createAdresaCompleta("sat Strâmbu-Băiuț, comuna Băiuț, judetul Maramureș, România", "sat Strambu-Baiut, comuna Baiut, judetul Maramures, Romania"))),
								  ]),	
			createComuna("Băsești", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Băsești", "sat", createAdresaCompleta("sat Băsești, comuna Băsești, judetul Maramureș, România", "sat Basesti, comuna Basesti, judetul Maramures, Romania"))),
					createLoc("Odești", "sat", createAdresaCompleta("sat Odești, comuna Băsești, judetul Maramureș, România", "sat Odesti, comuna Basesti, judetul Maramures, Romania"))),
					createLoc("Săliște", "sat", createAdresaCompleta("sat Săliște, comuna Băsești, judetul Maramureș, România", "sat Saliste, comuna Basesti, judetul Maramures, Romania"))),
					createLoc("Stremț", "sat", createAdresaCompleta("sat Stremț, comuna Băsești, judetul Maramureș, România", "sat Stremt, comuna Basesti, judetul Maramures, Romania"))),
								  ]),	
			createComuna("Bârsana", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Bârsana", "sat", createAdresaCompleta("sat Bârsana, comuna Bârsana, judetul Maramureș, România", "sat Barsana, comuna Barsana, judetul Maramures, Romania"))),
					createLoc("Nănești", "sat", createAdresaCompleta("sat Nănești, comuna Bârsana, judetul Maramureș, România", "sat Nanesti, comuna Barsana, judetul Maramures, Romania"))),
								  ]),
			createComuna("Bicaz", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Bicaz", "sat", createAdresaCompleta("sat Bicaz, comuna Bicaz, judetul Maramureș, România", "sat Bicaz, comuna Bicaz, judetul Maramures, Romania"))),
					createLoc("Ciuta", "sat", createAdresaCompleta("sat Ciuta, comuna Bicaz, judetul Maramureș, România", "sat Ciuta, comuna Bicaz, judetul Maramures, Romania"))),
					createLoc("Corni", "sat", createAdresaCompleta("sat Corni, comuna Bicaz, judetul Maramureș, România", "sat Corni, comuna Bicaz, judetul Maramures, Romania"))),
								  ]),
			createComuna("Bistra", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Bistra", "sat", createAdresaCompleta("sat Bistra, comuna Bistra, judetul Maramureș, România", "sat Bistra, comuna Bistra, judetul Maramures, Romania"))),
					createLoc("Crasna Vișeului", "sat", createAdresaCompleta("sat Crasna Vișeului, comuna Bistra, judetul Maramureș, România", "sat Crasna Viseului, comuna Bistra, judetul Maramures, Romania"))),
					createLoc("Valea Vișeului", "sat", createAdresaCompleta("sat Valea Vișeului, comuna Bistra, judetul Maramureș, România", "sat Valea Viseului, comuna Bistra, judetul Maramures, Romania"))),
								  ]),
			createComuna("Bocicoiu Mare", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Bocicoiu Mare", "sat", createAdresaCompleta("sat Bocicoiu Mare, comuna Bocicoiu Mare, judetul Maramureș, România", "sat Bocicoiu Mare, comuna Bocicoiu Mare, judetul Maramures, Romania"))),
					createLoc("Crăciunești", "sat", createAdresaCompleta("sat Crăciunești, comuna Bocicoiu Mare, judetul Maramureș, România", "sat Craciunesti, comuna Bocicoiu Mare, judetul Maramures, Romania"))),
					createLoc("Lunca la Tisa", "sat", createAdresaCompleta("sat Lunca la Tisa, comuna Bocicoiu Mare, judetul Maramureș, România", "sat Lunca la Tisa, comuna Bocicoiu Mare, judetul Maramures, Romania"))),
					createLoc("Tisa", "sat", createAdresaCompleta("sat Tisa, comuna Bocicoiu Mare, judetul Maramureș, România", "sat Tisa, comuna Bocicoiu Mare, judetul Maramures, Romania"))),
								  ]),	
			createComuna("Bogdan Vodă", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Bogdan Vodă", "sat", createAdresaCompleta("sat Bogdan Vodă, comuna Bogdan Vodă, judetul Maramureș, România", "sat Bogdan Voda, comuna Bogdan Voda, judetul Maramures, Romania"))),
					createLoc("Bocicoel", "sat", createAdresaCompleta("sat Bocicoel, comuna Bogdan Vodă, judetul Maramureș, România", "sat Bocicoel, comuna Bogdan Voda, judetul Maramures, Romania"))),
								  ]),
			createComuna("Boiu Mare", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Boiu Mare", "sat", createAdresaCompleta("sat Boiu Mare, comuna Boiu Mare, judetul Maramureș, România", "sat Boiu Mare, comuna Boiu Mare, judetul Maramures, Romania"))),
					createLoc("Frâncenii Boiului", "sat", createAdresaCompleta("sat Frâncenii Boiului, comuna Boiu Mare, judetul Maramureș, România", "sat Francenii Boiului, comuna Boiu Mare, judetul Maramures, Romania"))),
					createLoc("Prislop", "sat", createAdresaCompleta("sat Prislop, comuna Boiu Mare, judetul Maramureș, România", "sat Prislop, comuna Boiu Mare, judetul Maramures, Romania"))),
					createLoc("Românești", "sat", createAdresaCompleta("sat Românești, comuna Boiu Mare, judetul Maramureș, România", "sat Romanesti, comuna Boiu Mare, judetul Maramures, Romania"))),
								  ]),	
			createComuna("Botiza", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Botiza", "sat", createAdresaCompleta("sat Botiza, comuna Botiza, judetul Maramureș, România", "sat Botiza, comuna Botiza, judetul Maramures, Romania"))),
								  ]),
			createComuna("Budești", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Budești", "sat", createAdresaCompleta("sat Budești, comuna Budești, judetul Maramureș, România", "sat Budesti, comuna Budesti, judetul Maramures, Romania"))),
					createLoc("Sârbi", "sat", createAdresaCompleta("sat Sârbi, comuna Fărcașa, judetul Maramureș, România", "sat Sarbi, comuna Farcasa, judetul Maramures, Romania")), createAdresaCompleta("sat Sârbi, comuna Budești, judetul Maramureș, România", "sat Sarbi, comuna Budesti, judetul Maramures, Romania"))),
								  ]),
			createComuna("Călinești", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Călinești", "sat", createAdresaCompleta("sat Călinești, comuna Călinești, judetul Maramureș, România", "sat Calinesti, comuna Calinesti, judetul Maramures, Romania"))),
					createLoc("Cornești", "sat", createAdresaCompleta("sat Cornești, comuna Călinești, judetul Maramureș, România", "sat Cornesti, comuna Calinesti, judetul Maramures, Romania"))),
					createLoc("Văleni", "sat", createAdresaCompleta("sat Văleni, comuna Călinești, judetul Maramureș, România", "sat Valeni, comuna Calinesti, judetul Maramures, Romania"))),
								  ]),
			createComuna("Cernești", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Cernești", "sat", createAdresaCompleta("sat Cernești, comuna Cernești, judetul Maramureș, România", "sat Cernesti, comuna Cernesti, judetul Maramures, Romania"))),
					createLoc("Brebeni", "sat", createAdresaCompleta("sat Brebeni, comuna Cernești, judetul Maramureș, România", "sat Brebeni, comuna Cernesti, judetul Maramures, Romania"))),
					createLoc("Ciocotiș", "sat", createAdresaCompleta("sat Ciocotiș, comuna Cernești, judetul Maramureș, România", "sat Ciocotis, comuna Cernesti, judetul Maramures, Romania"))),
					createLoc("Fânațe", "sat", createAdresaCompleta("sat Fânațe, comuna Cernești, judetul Maramureș, România", "sat Fanate, comuna Cernesti, judetul Maramures, Romania"))),
					createLoc("Izvoarele", "sat", createAdresaCompleta("sat Izvoarele, comuna Cernești, judetul Maramureș, România", "sat Izvoarele, comuna Cernesti, judetul Maramures, Romania"))),
					createLoc("Măgureni", "sat", createAdresaCompleta("sat Măgureni, comuna Cernești, judetul Maramureș, România", "sat Magureni, comuna Cernesti, judetul Maramures, Romania"))),
					createLoc("Trestia", "sat", createAdresaCompleta("sat Trestia, comuna Cernești, judetul Maramureș, România", "sat Trestia, comuna Cernesti, judetul Maramures, Romania"))),
								  ]),
			createComuna("Cicârlău", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Cicârlău", "sat", createAdresaCompleta("sat Cicârlău, comuna Cicârlău, judetul Maramureș, România", "sat Cicarlau, comuna Cicarlau, judetul Maramures, Romania"))),
					createLoc("Bârgău", "sat", createAdresaCompleta("sat Bârgău, comuna Cicârlău, judetul Maramureș, România", "sat Bargau, comuna Cicarlau, judetul Maramures, Romania"))),
					createLoc("Handalu Ilbei", "sat", createAdresaCompleta("sat Handalu Ilbei, comuna Cicârlău, judetul Maramureș, România", "sat Handalu Ilbei, comuna Cicarlau, judetul Maramures, Romania"))),
					createLoc("Ilba", "sat", createAdresaCompleta("sat Ilba, comuna Cicârlău, judetul Maramureș, România", "sat Ilba, comuna Cicarlau, judetul Maramures, Romania"))),
								  ]),
			createComuna("Câmpulung la Tisa", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Câmpulung la Tisa", "sat", createAdresaCompleta("sat Câmpulung la Tisa, comuna Câmpulung la Tisa, judetul Maramureș, România", "sat Campulung la Tisa, comuna Campulung la Tisa, judetul Maramures, Romania"))),
								  ]),
			createComuna("Coaș", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Coaș", "sat", createAdresaCompleta("sat Coaș, comuna Coaș, judetul Maramureș, România", "sat Coas, comuna Coas, judetul Maramures, Romania"))),
					createLoc("Întrerâuri", "sat", createAdresaCompleta("sat Întrerâuri, comuna Coaș, judetul Maramureș, România", "sat Intrerauri, comuna Coas, judetul Maramures, Romania"))),
								  ]),
			createComuna("Coltău", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Coltău", "sat", createAdresaCompleta("sat Coltău, comuna Coltău, judetul Maramureș, România", "sat Coltau, comuna Coltau, judetul Maramures, Romania"))),
					createLoc("Cătălina", "sat", createAdresaCompleta("sat Cătălina, comuna Coltău, judetul Maramureș, România", "sat Catalina, comuna Coltau, judetul Maramures, Romania"))),
								  ]),
			createComuna("Copalnic-Mănăștur", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Copalnic-Mănăștur", "sat", createAdresaCompleta("sat Copalnic-Mănăștur, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Copalnic-Manastur, comuna Copalnic-Manastur, judetul Maramures, Romania"))),
					createLoc("Berința", "sat", createAdresaCompleta("sat Berința, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Berinta, comuna Copalnic-Manastur, judetul Maramures, Romania")), createAdresaCompleta("sat Berința, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Berinta, comuna Copalnic-Manastur, judetul Maramures, Romania"))),
					createLoc("Berința", "sat", createAdresaCompleta("sat Berința, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Berinta, comuna Copalnic-Manastur, judetul Maramures, Romania")), createAdresaCompleta("sat Berința, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Berinta, comuna Copalnic-Manastur, judetul Maramures, Romania"))),
					createLoc("Cărpiniș", "sat", createAdresaCompleta("sat Cărpiniș, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Carpinis, comuna Copalnic-Manastur, judetul Maramures, Romania"))),
					createLoc("Copalnic", "sat", createAdresaCompleta("sat Copalnic, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Copalnic, comuna Copalnic-Manastur, judetul Maramures, Romania"))),
					createLoc("Copalnic-Deal", "sat", createAdresaCompleta("sat Copalnic-Deal, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Copalnic-Deal, comuna Copalnic-Manastur, judetul Maramures, Romania"))),
					createLoc("Curtuiușu Mic", "sat", createAdresaCompleta("sat Curtuiușu Mic, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Curtuiusu Mic, comuna Copalnic-Manastur, judetul Maramures, Romania"))),
					createLoc("Făurești", "sat", createAdresaCompleta("sat Făurești, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Fauresti, comuna Copalnic-Manastur, judetul Maramures, Romania"))),
					createLoc("Lăschia", "sat", createAdresaCompleta("sat Lăschia, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Laschia, comuna Copalnic-Manastur, judetul Maramures, Romania"))),
					createLoc("Preluca Nouă", "sat", createAdresaCompleta("sat Preluca Nouă, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Preluca Noua, comuna Copalnic-Manastur, judetul Maramures, Romania"))),
					createLoc("Preluca Veche", "sat", createAdresaCompleta("sat Preluca Veche, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Preluca Veche, comuna Copalnic-Manastur, judetul Maramures, Romania"))),
					createLoc("Rușor", "sat", createAdresaCompleta("sat Rușor, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Rusor, comuna Copalnic-Manastur, judetul Maramures, Romania"))),
					createLoc("Vad", "sat", createAdresaCompleta("sat Vad, comuna Copalnic-Mănăștur, judetul Maramureș, România", "sat Vad, comuna Copalnic-Manastur, judetul Maramures, Romania"))),
								  ]),
			createComuna("Coroieni", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Coroieni", "sat", createAdresaCompleta("sat Coroieni, comuna Coroieni, judetul Maramureș, România", "sat Coroieni, comuna Coroieni, judetul Maramures, Romania"))),
					createLoc("Baba", "sat", createAdresaCompleta("sat Baba, comuna Coroieni, judetul Maramureș, România", "sat Baba, comuna Coroieni, judetul Maramures, Romania"))),
					createLoc("Dealu Mare", "sat", createAdresaCompleta("sat Dealu Mare, comuna Coroieni, judetul Maramureș, România", "sat Dealu Mare, comuna Coroieni, judetul Maramures, Romania"))),
					createLoc("Drăghia", "sat", createAdresaCompleta("sat Drăghia, comuna Coroieni, judetul Maramureș, România", "sat Draghia, comuna Coroieni, judetul Maramures, Romania"))),
					createLoc("Vălenii Lăpușului", "sat", createAdresaCompleta("sat Vălenii Lăpușului, comuna Coroieni, judetul Maramureș, România", "sat Valenii Lapusului, comuna Coroieni, judetul Maramures, Romania"))),
								  ]),
			createComuna("Cupșeni", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Cupșeni", "sat", createAdresaCompleta("sat Cupșeni, comuna Cupșeni, judetul Maramureș, România", "sat Cupseni, comuna Cupseni, judetul Maramures, Romania"))),
					createLoc("Costeni", "sat", createAdresaCompleta("sat Costeni, comuna Cupșeni, judetul Maramureș, România", "sat Costeni, comuna Cupseni, judetul Maramures, Romania"))),
					createLoc("Libotin", "sat", createAdresaCompleta("sat Libotin, comuna Cupșeni, judetul Maramureș, România", "sat Libotin, comuna Cupseni, judetul Maramures, Romania"))),
					createLoc("Ungureni", "sat", createAdresaCompleta("sat Ungureni, comuna Cupșeni, judetul Maramureș, România", "sat Ungureni, comuna Cupseni, judetul Maramures, Romania"))),
								  ]),
			createComuna("Desești", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Desești", "sat", createAdresaCompleta("sat Desești, comuna Desești, judetul Maramureș, România", "sat Desesti, comuna Desesti, judetul Maramures, Romania"))),
					createLoc("Hărnicești", "sat", createAdresaCompleta("sat Hărnicești, comuna Desești, judetul Maramureș, România", "sat Harnicesti, comuna Desesti, judetul Maramures, Romania"))),
					createLoc("Mara", "sat", createAdresaCompleta("sat Mara, comuna Desești, judetul Maramureș, România", "sat Mara, comuna Desesti, judetul Maramures, Romania"))),
								  ]),
			createComuna("Dumbrăvița", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Dumbrăvița", "sat", createAdresaCompleta("sat Dumbrăvița, comuna Dumbrăvița, judetul Maramureș, România", "sat Dumbravita, comuna Dumbravita, judetul Maramures, Romania"))),
					createLoc("Cărbunari", "sat", createAdresaCompleta("sat Cărbunari, comuna Dumbrăvița, judetul Maramureș, România", "sat Carbunari, comuna Dumbravita, judetul Maramures, Romania"))),
					createLoc("Chechiș", "sat", createAdresaCompleta("sat Chechiș, comuna Dumbrăvița, judetul Maramureș, România", "sat Chechis, comuna Dumbravita, judetul Maramures, Romania"))),
					createLoc("Rus", "sat", createAdresaCompleta("sat Rus, comuna Dumbrăvița, judetul Maramureș, România", "sat Rus, comuna Dumbravita, judetul Maramures, Romania"))),
					createLoc("Sindrești", "sat", createAdresaCompleta("sat Sindrești, comuna Dumbrăvița, judetul Maramureș, România", "sat Sindresti, comuna Dumbravita, judetul Maramures, Romania"))),
					createLoc("Unguraș", "sat", createAdresaCompleta("sat Unguraș, comuna Dumbrăvița, judetul Maramureș, România", "sat Unguras, comuna Dumbravita, judetul Maramures, Romania"))),
								  ]),
			createComuna("Fărcașa", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Fărcașa", "sat", createAdresaCompleta("sat Fărcașa, comuna Fărcașa, judetul Maramureș, România", "sat Farcasa, comuna Farcasa, judetul Maramures, Romania"))),
					createLoc("Buzești", "sat", createAdresaCompleta("sat Buzești, comuna Fărcașa, judetul Maramureș, România", "sat Buzesti, comuna Farcasa, judetul Maramures, Romania"))),
					createLoc("Sârbi", "sat", createAdresaCompleta("sat Sârbi, comuna Fărcașa, judetul Maramureș, România", "sat Sarbi, comuna Farcasa, judetul Maramures, Romania")), createAdresaCompleta("sat Sârbi, comuna Budești, judetul Maramureș, România", "sat Sarbi, comuna Budesti, judetul Maramures, Romania"))),
					createLoc("Tămaia", "sat", createAdresaCompleta("sat Tămaia, comuna Fărcașa, judetul Maramureș, România", "sat Tamaia, comuna Farcasa, judetul Maramures, Romania"))),
								  ]),
			createComuna("Gârdani", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Gârdani", "sat", createAdresaCompleta("sat Gârdani, comuna Gârdani, judetul Maramureș, România", "sat Gardani, comuna Gardani, judetul Maramures, Romania"))),
								  ]),
			createComuna("Giulești", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Giulești", "sat", createAdresaCompleta("sat Giulești, comuna Giulești, judetul Maramureș, România", "sat Giulesti, comuna Giulesti, judetul Maramures, Romania"))),
					createLoc("Berbești", "sat", createAdresaCompleta("sat Berbești, comuna Giulești, judetul Maramureș, România", "sat Berbesti, comuna Giulesti, judetul Maramures, Romania"))),
					createLoc("Ferești", "sat", createAdresaCompleta("sat Ferești, comuna Giulești, judetul Maramureș, România", "sat Feresti, comuna Giulesti, judetul Maramures, Romania"))),
					createLoc("Mănăstirea", "sat", createAdresaCompleta("sat Mănăstirea, comuna Giulești, judetul Maramureș, România", "sat Manastirea, comuna Giulesti, judetul Maramures, Romania"))),
								  ]),
			createComuna("Groși", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Groși", "sat", createAdresaCompleta("sat Groși, comuna Groși, judetul Maramureș, România", "sat Grosi, comuna Grosi, judetul Maramures, Romania"))),
					createLoc("Ocoliș", "sat", createAdresaCompleta("sat Ocoliș, comuna Groși, judetul Maramureș, România", "sat Ocolis, comuna Grosi, judetul Maramures, Romania"))),
					createLoc("Satu Nou de Jos", "sat", createAdresaCompleta("sat Satu Nou de Jos, comuna Groși, judetul Maramureș, România", "sat Satu Nou de Jos, comuna Grosi, judetul Maramures, Romania"))),
								  ]),
			createComuna("Groșii Țibleșului", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Groșii Țibleșului", "sat", createAdresaCompleta("sat Groșii Țibleșului, comuna Groșii Țibleșului, judetul Maramureș, România", "sat Grosii Tiblesului, comuna Grosii Tiblesului, judetul Maramures, Romania"))),
								  ]),
			createComuna("Ieud", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Ieud", "sat", createAdresaCompleta("sat Ieud, comuna Ieud, judetul Maramureș, România", "sat Ieud, comuna Ieud, judetul Maramures, Romania"))),
								  ]),
			createComuna("Lăpuș", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Lăpuș", "sat", createAdresaCompleta("sat Lăpuș, comuna Lăpuș, judetul Maramureș, România", "sat Lapus, comuna Lapus, judetul Maramures, Romania"))),
								  ]),
			createComuna("Leordina", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Leordina", "sat", createAdresaCompleta("sat Leordina, comuna Leordina, judetul Maramureș, România", "sat Leordina, comuna Leordina, judetul Maramures, Romania"))),
								  ]),
			createComuna("Mireșu Mare", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Mireșu Mare", "sat", createAdresaCompleta("sat Mireșu Mare, comuna Mireșu Mare, judetul Maramureș, România", "sat Miresu Mare, comuna Miresu Mare, judetul Maramures, Romania"))),
					createLoc("Dăneștii Chioarului", "sat", createAdresaCompleta("sat Dăneștii Chioarului, comuna Mireșu Mare, judetul Maramureș, România", "sat Danestii Chioarului, comuna Miresu Mare, judetul Maramures, Romania"))),
					createLoc("Iadăra", "sat", createAdresaCompleta("sat Iadăra, comuna Mireșu Mare, judetul Maramureș, România", "sat Iadara, comuna Miresu Mare, judetul Maramures, Romania"))),
					createLoc("Lucăcești", "sat", createAdresaCompleta("sat Lucăcești, comuna Mireșu Mare, judetul Maramureș, România", "sat Lucacesti, comuna Miresu Mare, judetul Maramures, Romania"))),
					createLoc("Remeți pe Someș", "sat", createAdresaCompleta("sat Remeți pe Someș, comuna Mireșu Mare, judetul Maramureș, România", "sat Remeti pe Somes, comuna Miresu Mare, judetul Maramures, Romania"))),
					createLoc("Stejera", "sat", createAdresaCompleta("sat Stejera, comuna Mireșu Mare, judetul Maramureș, România", "sat Stejera, comuna Miresu Mare, judetul Maramures, Romania"))),
					createLoc("Tulghieș", "sat", createAdresaCompleta("sat Tulghieș, comuna Mireșu Mare, judetul Maramureș, România", "sat Tulghies, comuna Miresu Mare, judetul Maramures, Romania"))),
								  ]),
			createComuna("Moisei", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Moisei", "sat", createAdresaCompleta("sat Moisei, comuna Moisei, judetul Maramureș, România", "sat Moisei, comuna Moisei, judetul Maramures, Romania"))),
								  ]),
			createComuna("Oarța de Jos", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Oarța de Jos", "sat", createAdresaCompleta("sat Oarța de Jos, comuna Oarța de Jos, judetul Maramureș, România", "sat Oarta de Jos, comuna Oarta de Jos, judetul Maramures, Romania"))),
					createLoc("Oarța de Sus", "sat", createAdresaCompleta("sat Oarța de Sus, comuna Oarța de Jos, judetul Maramureș, România", "sat Oarta de Sus, comuna Oarta de Jos, judetul Maramures, Romania"))),
					createLoc("Orțița", "sat", createAdresaCompleta("sat Orțița, comuna Oarța de Jos, judetul Maramureș, România", "sat Ortita, comuna Oarta de Jos, judetul Maramures, Romania"))),
								  ]),
			createComuna("Ocna Șugatag", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Ocna Șugatag", "sat", createAdresaCompleta("sat Ocna Șugatag, comuna Ocna Șugatag, judetul Maramureș, România", "sat Ocna Sugatag, comuna Ocna Sugatag, judetul Maramures, Romania"))),
					createLoc("Breb", "sat", createAdresaCompleta("sat Breb, comuna Ocna Șugatag, judetul Maramureș, România", "sat Breb, comuna Ocna Sugatag, judetul Maramures, Romania"))),
					createLoc("Hoteni", "sat", createAdresaCompleta("sat Hoteni, comuna Ocna Șugatag, judetul Maramureș, România", "sat Hoteni, comuna Ocna Sugatag, judetul Maramures, Romania"))),
					createLoc("Sat-Șugatag", "sat", createAdresaCompleta("sat Sat-Șugatag, comuna Ocna Șugatag, judetul Maramureș, România", "sat Sat-Sugatag, comuna Ocna Sugatag, judetul Maramures, Romania"))),
								  ]),
			createComuna("Oncești", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Oncești", "sat", createAdresaCompleta("sat Oncești, comuna Oncești, judetul Maramureș, România", "sat Oncesti, comuna Oncesti, judetul Maramures, Romania"))),
								  ]),
			createComuna("Petrova", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Petrova", "sat", createAdresaCompleta("sat Petrova, comuna Petrova, judetul Maramureș, România", "sat Petrova, comuna Petrova, judetul Maramures, Romania"))),
								  ]),
			createComuna("Poienile de sub Munte", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Poienile de sub Munte", "sat", createAdresaCompleta("sat Poienile de sub Munte, comuna Poienile de sub Munte, judetul Maramureș, România", "sat Poienile de sub Munte, comuna Poienile de sub Munte, judetul Maramures, Romania"))),
								  ]),
			createComuna("Poienile Izei", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Poienile Izei", "sat", createAdresaCompleta("sat Poienile Izei, comuna Poienile Izei, judetul Maramureș, România", "sat Poienile Izei, comuna Poienile Izei, judetul Maramures, Romania"))),
								  ]),
			createComuna("Recea", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
					createLoc("Recea", "sat", createAdresaCompleta("sat Recea, comuna Recea, judetul Maramureș, România", "sat Recea, comuna Recea, judetul Maramures, Romania"))),
					createLoc("Bozânta Mică", "sat", createAdresaCompleta("sat Bozânta Mică, comuna Recea, judetul Maramureș, România", "sat Bozanta Mica, comuna Recea, judetul Maramures, Romania"))),
					createLoc("Lăpușel", "sat", createAdresaCompleta("sat Lăpușel, comuna Recea, judetul Maramureș, România", "sat Lapusel, comuna Recea, judetul Maramures, Romania"))),
					createLoc("Mocira", "sat", createAdresaCompleta("sat Mocira, comuna Recea, judetul Maramureș, România", "sat Mocira, comuna Recea, judetul Maramures, Romania"))),
					createLoc("Săsar", "sat", createAdresaCompleta("sat Săsar, comuna Recea, judetul Maramureș, România", "sat Sasar, comuna Recea, judetul Maramures, Romania"))),
								  ]),
    createComuna("Remetea Chioarului", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Remetea Chioarului", "sat", createAdresaCompleta("sat Remetea Chioarului, comuna Remetea Chioarului, judetul Maramureș, România", "sat Remetea Chioarului, comuna Remetea Chioarului, judetul Maramures, Romania"))),
        createLoc("Berchez", "sat", createAdresaCompleta("sat Berchez, comuna Remetea Chioarului, judetul Maramureș, România", "sat Berchez, comuna Remetea Chioarului, judetul Maramures, Romania"))),
        createLoc("Berchezoaia", "sat", createAdresaCompleta("sat Berchezoaia, comuna Remetea Chioarului, judetul Maramureș, România", "sat Berchezoaia, comuna Remetea Chioarului, judetul Maramures, Romania"))),
        createLoc("Posta", "sat", createAdresaCompleta("sat Posta, comuna Remetea Chioarului, judetul Maramureș, România", "sat Posta, comuna Remetea Chioarului, judetul Maramures, Romania"))),
        createLoc("Remecioara", "sat", createAdresaCompleta("sat Remecioara, comuna Remetea Chioarului, judetul Maramureș, România", "sat Remecioara, comuna Remetea Chioarului, judetul Maramures, Romania"))),
    ]),
    createComuna("Remeți", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Remeți", "sat", createAdresaCompleta("sat Remeți, comuna Remeți, judetul Maramureș, România", "sat Remeti, comuna Remeti, judetul Maramures, Romania"))),
        createLoc("Piatra", "sat", createAdresaCompleta("sat Piatra, comuna Remeți, judetul Maramureș, România", "sat Piatra, comuna Remeti, judetul Maramures, Romania"))),
        createLoc("Teceu Mic", "sat", createAdresaCompleta("sat Teceu Mic, comuna Remeți, judetul Maramureș, România", "sat Teceu Mic, comuna Remeti, judetul Maramures, Romania"))),
    ]),
    createComuna("Repedea", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Repedea", "sat", createAdresaCompleta("sat Repedea, comuna Repedea, judetul Maramureș, România", "sat Repedea, comuna Repedea, judetul Maramures, Romania"))),
    ]),
    createComuna("Rona de Jos", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Rona de Jos", "sat", createAdresaCompleta("sat Rona de Jos, comuna Rona de Jos, judetul Maramureș, România", "sat Rona de Jos, comuna Rona de Jos, judetul Maramures, Romania"))),
    ]),
    createComuna("Rona de Sus", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Rona de Sus", "sat", createAdresaCompleta("sat Rona de Sus, comuna Rona de Sus, judetul Maramureș, România", "sat Rona de Sus, comuna Rona de Sus, judetul Maramures, Romania"))),
        createLoc("Coștiui", "sat", createAdresaCompleta("sat Coștiui, comuna Rona de Sus, judetul Maramureș, România", "sat Costiui, comuna Rona de Sus, judetul Maramures, Romania"))),
    ]),
    createComuna("Rozavlea", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Rozavlea", "sat", createAdresaCompleta("sat Rozavlea, comuna Rozavlea, judetul Maramureș, România", "sat Rozavlea, comuna Rozavlea, judetul Maramures, Romania"))),
        createLoc("Sâlța", "sat", createAdresaCompleta("sat Sâlța, comuna Rozavlea, judetul Maramureș, România", "sat Salta, comuna Rozavlea, judetul Maramures, Romania"))),
    ]),
    createComuna("Ruscova", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Ruscova", "sat", createAdresaCompleta("sat Ruscova, comuna Ruscova, judetul Maramureș, România", "sat Ruscova, comuna Ruscova, judetul Maramures, Romania"))),
    ]),
    createComuna("Sarasău", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Sarasău", "sat", createAdresaCompleta("sat Sarasău, comuna Sarasău, judetul Maramureș, România", "sat Sarasau, comuna Sarasau, judetul Maramures, Romania"))),
    ]),
    createComuna("Satulung", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Satulung", "sat", createAdresaCompleta("sat Satulung, comuna Satulung, judetul Maramureș, România", "sat Satulung, comuna Satulung, judetul Maramures, Romania"))),
        createLoc("Arieșu de Pădure", "sat", createAdresaCompleta("sat Arieșu de Pădure, comuna Satulung, judetul Maramureș, România", "sat Ariesu de Padure, comuna Satulung, judetul Maramures, Romania"))),
        createLoc("Fersig", "sat", createAdresaCompleta("sat Fersig, comuna Satulung, judetul Maramureș, România", "sat Fersig, comuna Satulung, judetul Maramures, Romania"))),
        createLoc("Finteușu Mic", "sat", createAdresaCompleta("sat Finteușu Mic, comuna Satulung, judetul Maramureș, România", "sat Finteusu Mic, comuna Satulung, judetul Maramures, Romania"))),
        createLoc("Hideaga", "sat", createAdresaCompleta("sat Hideaga, comuna Satulung, judetul Maramureș, România", "sat Hideaga, comuna Satulung, judetul Maramures, Romania"))),
        createLoc("Mogoșești", "sat", createAdresaCompleta("sat Mogoșești, comuna Satulung, judetul Maramureș, România", "sat Mogosesti, comuna Satulung, judetul Maramures, Romania"))),
        createLoc("Pribilești", "sat", createAdresaCompleta("sat Pribilești, comuna Satulung, judetul Maramureș, România", "sat Pribilesti, comuna Satulung, judetul Maramures, Romania"))),
    ]),
    createComuna("Săcălășeni", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Săcălășeni", "sat", createAdresaCompleta("sat Săcălășeni, comuna Săcălășeni, judetul Maramureș, România", "sat Sacalaseni, comuna Sacalaseni, judetul Maramures, Romania"))),
        createLoc("Coruia", "sat", createAdresaCompleta("sat Coruia, comuna Săcălășeni, judetul Maramureș, România", "sat Coruia, comuna Sacalaseni, judetul Maramures, Romania"))),
        createLoc("Culcea", "sat", createAdresaCompleta("sat Culcea, comuna Săcălășeni, judetul Maramureș, România", "sat Culcea, comuna Sacalaseni, judetul Maramures, Romania"))),
    ]),
    createComuna("Săcel", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Săcel", "sat", createAdresaCompleta("sat Săcel, comuna Săcel, judetul Maramureș, România", "sat Sacel, comuna Sacel, judetul Maramures, Romania"))),
    ]),
    createComuna("Sălsig", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Sălsig", "sat", createAdresaCompleta("sat Sălsig, comuna Sălsig, judetul Maramureș, România", "sat Salsig, comuna Salsig, judetul Maramures, Romania"))),
    ]),
    createComuna("Săpânța", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Săpânța", "sat", createAdresaCompleta("sat Săpânța, comuna Săpânța, judetul Maramureș, România", "sat Sapanta, comuna Sapanta, judetul Maramures, Romania"))),
    ]),
    createComuna("Strâmtura", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Strâmtura", "sat", createAdresaCompleta("sat Strâmtura, comuna Strâmtura, judetul Maramureș, România", "sat Stramtura, comuna Stramtura, judetul Maramures, Romania"))),
        createLoc("Glod", "sat", createAdresaCompleta("sat Glod, comuna Strâmtura, judetul Maramureș, România", "sat Glod, comuna Stramtura, judetul Maramures, Romania"))),
        createLoc("Slătioara", "sat", createAdresaCompleta("sat Slătioara, comuna Strâmtura, judetul Maramureș, România", "sat Slatioara, comuna Stramtura, judetul Maramures, Romania"))),
    ]),
    createComuna("Suciu de Sus", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Suciu de Sus", "sat", createAdresaCompleta("sat Suciu de Sus, comuna Suciu de Sus, judetul Maramureș, România", "sat Suciu de Sus, comuna Suciu de Sus, judetul Maramures, Romania"))),
        createLoc("Larga", "sat", createAdresaCompleta("sat Larga, comuna Suciu de Sus, judetul Maramureș, România", "sat Larga, comuna Suciu de Sus, judetul Maramures, Romania"))),
        createLoc("Suciu de Jos", "sat", createAdresaCompleta("sat Suciu de Jos, comuna Suciu de Sus, judetul Maramureș, România", "sat Suciu de Jos, comuna Suciu de Sus, judetul Maramures, Romania"))),
    ]),
    createComuna("Șieu", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Șieu", "sat", createAdresaCompleta("sat Șieu, comuna Șieu, judetul Maramureș, România", "sat Sieu, comuna Sieu, judetul Maramures, Romania"))),
    ]),
    createComuna("Șișești", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Șișești", "sat", createAdresaCompleta("sat Șișești, comuna Șișești, judetul Maramureș, România", "sat Sisesti, comuna Sisesti, judetul Maramures, Romania"))),
        createLoc("Bontăieni", "sat", createAdresaCompleta("sat Bontăieni, comuna Șișești, judetul Maramureș, România", "sat Bontaieni, comuna Sisesti, judetul Maramures, Romania"))),
        createLoc("Cetățele", "sat", createAdresaCompleta("sat Cetățele, comuna Șișești, judetul Maramureș, România", "sat Cetatele, comuna Sisesti, judetul Maramures, Romania"))),
        createLoc("Dănești", "sat", createAdresaCompleta("sat Dănești, comuna Șișești, judetul Maramureș, România", "sat Danesti, comuna Sisesti, judetul Maramures, Romania"))),
        createLoc("Negreia", "sat", createAdresaCompleta("sat Negreia, comuna Șișești, judetul Maramureș, România", "sat Negreia, comuna Sisesti, judetul Maramures, Romania"))),
        createLoc("Plopis", "sat", createAdresaCompleta("sat Plopis, comuna Șișești, judetul Maramureș, România", "sat Plopis, comuna Sisesti, judetul Maramures, Romania"))),
        createLoc("Șurdești", "sat", createAdresaCompleta("sat Șurdești, comuna Șișești, judetul Maramureș, România", "sat Surdesti, comuna Sisesti, judetul Maramures, Romania"))),
    ]),
    createComuna("Vadu Izei", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Vadu lzei", "sat", createAdresaCompleta("sat Vadu lzei, comuna Vadu Izei, judetul Maramureș, România", "sat Vadu lzei, comuna Vadu Izei, judetul Maramures, Romania"))),
        createLoc("Valea Stejarului", "sat", createAdresaCompleta("sat Valea Stejarului, comuna Vadu Izei, judetul Maramureș, România", "sat Valea Stejarului, comuna Vadu Izei, judetul Maramures, Romania"))),
    ]),
    createComuna("Valea Chioarului", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Valea Chioarului", "sat", createAdresaCompleta("sat Valea Chioarului, comuna Valea Chioarului, judetul Maramureș, România", "sat Valea Chioarului, comuna Valea Chioarului, judetul Maramures, Romania"))),
        createLoc("Curtuiușu Mare", "sat", createAdresaCompleta("sat Curtuiușu Mare, comuna Valea Chioarului, judetul Maramureș, România", "sat Curtuiusu Mare, comuna Valea Chioarului, judetul Maramures, Romania"))),
        createLoc("Durușa", "sat", createAdresaCompleta("sat Durușa, comuna Valea Chioarului, judetul Maramureș, România", "sat Durusa, comuna Valea Chioarului, judetul Maramures, Romania"))),
        createLoc("Fericea", "sat", createAdresaCompleta("sat Fericea, comuna Valea Chioarului, judetul Maramureș, România", "sat Fericea, comuna Valea Chioarului, judetul Maramures, Romania"))),
        createLoc("Mesteacăn", "sat", createAdresaCompleta("sat Mesteacăn, comuna Valea Chioarului, judetul Maramureș, România", "sat Mesteacan, comuna Valea Chioarului, judetul Maramures, Romania"))),
        createLoc("Vărai", "sat", createAdresaCompleta("sat Vărai, comuna Valea Chioarului, judetul Maramureș, România", "sat Varai, comuna Valea Chioarului, judetul Maramures, Romania"))),
    ]),
    createComuna("Vima Mică", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Vima Mică", "sat", createAdresaCompleta("sat Vima Mică, comuna Vima Mică, judetul Maramureș, România", "sat Vima Mica, comuna Vima Mica, judetul Maramures, Romania"))),
        createLoc("Aspra", "sat", createAdresaCompleta("sat Aspra, comuna Vima Mică, judetul Maramureș, România", "sat Aspra, comuna Vima Mica, judetul Maramures, Romania"))),
        createLoc("Dealu Corbului", "sat", createAdresaCompleta("sat Dealu Corbului, comuna Vima Mică, judetul Maramureș, România", "sat Dealu Corbului, comuna Vima Mica, judetul Maramures, Romania"))),
        createLoc("Jugăstreni", "sat", createAdresaCompleta("sat Jugăstreni, comuna Vima Mică, judetul Maramureș, România", "sat Jugastreni, comuna Vima Mica, judetul Maramures, Romania"))),
        createLoc("Peteritea", "sat", createAdresaCompleta("sat Peteritea, comuna Vima Mică, judetul Maramureș, România", "sat Peteritea, comuna Vima Mica, judetul Maramures, Romania"))),
        createLoc("Sălnița", "sat", createAdresaCompleta("sat Sălnița, comuna Vima Mică, judetul Maramureș, România", "sat Salnita, comuna Vima Mica, judetul Maramures, Romania"))),
        createLoc("Vima Mare", "sat", createAdresaCompleta("sat Vima Mare, comuna Vima Mică, judetul Maramureș, România", "sat Vima Mare, comuna Vima Mica, judetul Maramures, Romania"))),
    ]),
    createComuna("Vișeu de Jos", [
				createAdresaCompleta("comuna Ardusat, judetul MARAMURES, România", "comuna Ardusat, judetul MARAMURES, Romania"),
        createLoc("Vișeu de Jos", "sat", createAdresaCompleta("sat Vișeu de Jos, comuna Vișeu de Jos, judetul Maramureș, România", "sat Viseu de Jos, comuna Viseu de Jos, judetul Maramures, Romania"))),
    ]),	
								  
];
?>